from pathlib import Path
import sys,json,gzip,re,time,collections
import pandas as pd
O=Path(__file__).parent;E=O.parent;ROOT=E.parents[1];C=E/'additional_uncached_census_histories_20261008';sys.path.insert(0,str(ROOT/'research_rebuild/mass_linkage'))
from working_state_20261007 import load,PARTITION_MEMBERS
from current_chain_state_20261007 import sha,normalize,distance_km
T=time.monotonic();s=load(25);f=pd.read_csv(C/'candidate_series.csv').fillna('');assert len(f)==614 and f.sid.nunique()==614 and f.qid.nunique()==614
manifest=json.loads((C/'source_manifest.json').read_text());pins={};credited=set();activeq=set();groups={r:g for r,g in s.obs.groupby('root')}
for root,g in groups.items():
 if set(g.census_year)=={2002,2010,2021} and g.population.notna().all() and all(x in s.point_rows for x in g.source_record_id):credited.update(g.source_record_id)
paths=[PARTITION_MEMBERS,E/'additional_complete_partition_application_20261007/accepted_exclusive_member_projection.csv',E/'wikidata_secondary_full3_application_20261007/preapplication_qualified_credit_ids_frozen.csv']+[E/d/'accepted_qualified_physical_observations.csv' for d in ['wikidata_secondary_full3_application_20261007','current_unpointed_own_wiki_mass_application_20261007','existing_event_scope_application_20261007','wikidata_secondary_full3_expansion_application_20261007','remaining_large_own_points_followup_application_20261007','cached_secondary_native_year_mass_application_20261008']]+[E/d/'accepted_constituent_credit_union.csv' for d in ['named_urban_merger_application_20261007','next_named_urban_merger_application_20261007','further_urban_merger_application_20261007','voronezh_closed_roster_application_20261008']]+[E/'native_from_secondary_census_binding_application_20261007/accepted_native_source_id_credit_union.csv',E/'old_native_from_existing_secondary_binding_application_20261007/accepted_native_reference_credit_union.csv']
for p in paths:
 d=pd.read_csv(p,dtype=str).fillna('');pins[str(p)]=sha(p)
 for col in d:
  if 'source_record_id' in col:credited.update(x for x in d[col] if x)
  if col in ('trajectory_id','wikidata_id','qid','point_origin_locator','raw_source_locator'):activeq.update(q for x in d[col] for q in re.findall(r'Q\d+',x))
assert not activeq.intersection(f.qid)
cache={};rows=[];credits=[];audit=[];held=[];guidchecks=0;nativehashes={}
samples=set(f.sort_values('qid').iloc[[round(i*(len(f)-1)/14) for i in range(15)]].qid)|set(f.nlargest(5,'population').qid)
for t in f.to_dict('records'):
 q=t['qid'];sid=t['sid'];cur=s.by_id.loc[sid];point=s.point_rows[sid];component=groups[s.uf.find(sid)];assert cur.population==t['population'] and cur.is_additive_settlement_record
 pts=[s.point_rows[x] for x in component.source_record_id if x in s.point_rows];assert not any(x in s.conflicting_point_targets for x in component.source_record_id)
 assert max([distance_km((a['latitude'],a['longitude']),(b['latitude'],b['longitude'])) for a in pts for b in pts] or [0])<=5
 p=Path(t['entity_source_path']);assert sha(p)==t['entity_source_sha256']
 if str(p) not in cache:
  raw=p.read_bytes();d=json.loads(gzip.decompress(raw) if p.name.endswith('.gz') else raw);cache[str(p)]=d.get('entities',d.get('payload',{}).get('entities',{})) if 'claims' not in d else {d['id']:d}
 e=cache[str(p)][q];cs=e['claims'];assert not cs.get('P576');assert not any(z['mainsnak'].get('datavalue',{}).get('value',{}).get('id') in ('Q15284','Q1849719') for z in cs.get('P31',[]))
 years=json.loads(t['years'])+[{'year':2021,'population':cur.population,'kind':'native_current','source_record_id':sid}]
 nativecontext=[];secondarychecks=[]
 for v in years:
  y=v['year'];native=bool(v['source_record_id']);nid=v['source_record_id'];n=s.by_id.loc[nid] if native else None
  if native:
   assert s.uf.find(nid)==s.uf.find(sid) and n.population==v['population'] and n.is_additive_settlement_record and int(n.census_year)==y
   assert pd.isna(n.population_scope) or str(n.population_scope) not in ('municipality','parent_total','aggregate')
   nativecontext.append({'id':nid,'year':y,'name':n.settlement_name,'type':n.settlement_type,'region':n.region_norm,'county':str(n.district_raw),'population':float(n.population),'quality':n.population_value_quality,'source_locator':str(n.source_locator),'source_file':str(n.source_file)})
  else:
   st=next(z for z in cs['P1082'] if z['id']==v['statement_id']);assert float(st['mainsnak']['datavalue']['value']['amount'])==v['population'];assert st.get('rank')!='deprecated' and not st.get('qualifiers',{}).get('P518')
   assert any(z.get('datavalue',{}).get('value',{}).get('time')==v['declared_date'] and z['datavalue']['value']['precision']==v['date_precision'] for z in st['qualifiers']['P585']);assert v['census_proof'];guidchecks+=1;secondarychecks.append(v)
  source='/workspace/settlements-raw/'+str(n.source_file) if native else v['source_path'];sourcehash=str(n.source_sha256) if native and pd.notna(n.source_sha256) else ('' if native else t['entity_source_sha256']);locator='selected own census source_record_id='+nid if native else v['source_locator']
  if native and Path(source).is_file() and source not in nativehashes:nativehashes[source]=sha(Path(source))
  origin={k:point.get(k,'') for k in ['target_source_record_id','latitude','longitude','coordinate_source_record_id','point_origin_file','point_origin_sha256','point_origin_locator','point_origin_kind','point_ledger_path']}
  r={'trajectory_id':'additional_uncached_census_mass:'+q,'year':y,'population_source_value':float(v['population']),'source_record_id':nid,'settlement_name':t['name'],'region_norm':t['region'],'county_context':t['county'],'latitude':point['latitude'],'longitude':point['longitude'],'population_quality':n.population_value_quality if native else 'secondary_explicit_census_reference_date_or_title_primary_not_independently_verified','grain':'own physical locality selected native census observation' if native else 'own physical locality actual dated secondary census observation','nonadditive_observation':not native,'source_path':source,'source_sha256':sourcehash,'source_locator':locator,'decision_status':'qualified_accepted_secondary_census_referenced_own_item','ordinary_NP3_asserted':False,'boundary_comparability_asserted':False,'point_binding_json':json.dumps(origin,ensure_ascii=False),'retrospective_point_use_is_continuity_inference':y!=2021,'selected_credit_previously_present':native and nid in credited,'selected_source_sha256_as_loaded':sourcehash if native else '', 'scope':'additional_uncached_census_histories_20261008','boundary_comparability':'UNKNOWN','wikidata_id':q,'declared_date':f'+{y}-00-00T00:00:00Z' if native else v['declared_date'],'date_precision':9 if native else v['date_precision'],'census_proof_class':'existing_selected_native_census_row_in_accepted_own_NP_component' if native else v['census_proof'],'census_reference_titles_json':json.dumps([] if native else v['titles'],ensure_ascii=False),'P248_ids_json':json.dumps([] if native else v['P248_ids']),'P248_labels_json':json.dumps([] if native else v['P248_labels'],ensure_ascii=False),'P459_method_ids_json':'[]','reference_urls_json':json.dumps([] if native else v['urls']),'statement_id':'' if native else v['statement_id'],'own_item_binding':t['binding'],'own_physical_description':t['own_description'],'own_code_positive':t['own_code_positive'],'own_name_or_alias_positive':t['own_name_or_alias_positive'],'admin_source_positive':t['admin_source_positive'],'optional_Wiki_P625_count':len(cs.get('P625',[])),'optional_Wiki_coordinates_imported':False,'coordinate_bounds':'UNKNOWN','error_rate':'uncalibrated','accepted_physical_three_observed_census_year_path':True,'accepted_scoped_representative_point':True,'historical_native_selected_source_ID_binding_asserted':native and y!=2021,'population_primary_reference_verified':False,'native_current_source_record_id':sid,'native_existing_component_binding':native,'native_population_scope_legacy_null':native and pd.isna(n.population_scope),'native_raw_file_sha256_checked':nativehashes.get(source,'') if native else '', 'native_raw_source_missing_flag':native and not Path(source).is_file(),'native_source_context_json':json.dumps(nativecontext[-1],ensure_ascii=False) if native else ''}
  for k in ['point_origin_file','point_origin_sha256','point_origin_locator']:r[k]=point.get(k,'')
  rows.append(r)
  if native:credits.append({'source_record_id':nid,'year':y,'source_population':float(n.population),'trajectory_id':r['trajectory_id'],'scope':r['scope'],'previously_credited':nid in credited,'net_new_selected_ID_credit':nid not in credited})
 if q in samples:
  audit.append({'qid':q,'current_source_record_id':sid,'sample':('fixed15' if q in set(f.sort_values('qid').iloc[[round(i*(len(f)-1)/14) for i in range(15)]].qid) else '')+(';largest5' if q in set(f.nlargest(5,'population').qid) else ''),'own_label':t['own_label'],'own_description':t['own_description'],'native_name':t['name'],'native_type':t['type'],'native_region':t['region'],'native_county':t['county'],'exact_code_and_alias_witness':t['source_code_witnesses'],'P31_ids':json.dumps([z['mainsnak'].get('datavalue',{}).get('value',{}).get('id') for z in cs.get('P31',[])]),'native_contexts_json':json.dumps(nativecontext,ensure_ascii=False),'actual_secondary_proofs_json':json.dumps(secondarychecks,ensure_ascii=False),'entity_source_path':str(p),'entity_source_sha256':sha(p),'component_max_distance_km':t['component_points_max_distance_km'],'scope_check':'own physical NP; current native point retained; no parent/municipal/subset/event grain detected; boundaries UNKNOWN','status':'pass'})
assert len(rows)==1842 and guidchecks==614
out=pd.DataFrame(rows);cr=pd.DataFrame(credits).drop_duplicates('source_record_id');out.to_csv(O/'accepted_qualified_physical_observations.csv',index=False);cr.to_csv(O/'accepted_selected_source_id_credit_union.csv',index=False);pd.DataFrame(audit).to_csv(O/'fixed15_and_largest5_source_checks.csv',index=False)
(O/'held_reasons_preserved.json').write_text(json.dumps({'candidate_holds_path':str(C/'holds.csv'),'sha256':sha(C/'holds.csv'),'new_holds':held},indent=2))
verification={'status':'passed','series':614,'observations':len(rows),'direct_GUID_value_date_precision_subset_checks':guidchecks,'native_count_quality_component_point_checks':len(cr),'independent_fixed15_plus_largest5_cases':len(audit),'active_qualified_QID_overlap':0,'municipal_class_or_parent_subset_claims_admitted':0,'all_component_points_max_distance_km':5,'ordinary_edges_or_points_added':0};(O/'verification_receipt.json').write_text(json.dumps(verification,indent=2))
for p in list(dict.fromkeys(s.inputs+paths+[C/'candidate_series.csv',C/'source_manifest.json',C/'verification_receipt.json',C/'holds.csv',C/'network_receipt.json',C/'census_reference_source_witnesses.json',Path(__file__)])):pins[str(p)]=sha(p)
pins.update(manifest['raw_entity_cache']);pins.update(nativehashes);(O/'source_manifest.json').write_text(json.dumps(pins,indent=2))

# Export bounded hard-conflict case inventory for a later separately authorized coordinate correction.
holds=pd.read_csv(C/'holds.csv').fillna('');targets=pd.read_csv(C/'all_residual_targets.csv').fillna('');hc=targets.merge(holds[holds.hold_reason.str.contains('existing_component_point_hard_conflict')],on=['qid','sid','name']);conflicts=[]
for t in hc.sort_values('population',ascending=False).to_dict('records'):
 sid=t['sid'];g=groups[s.uf.find(sid)];points=[{'source_record_id':x,**s.point_rows[x]} for x in g.source_record_id if x in s.point_rows];distances=[{'source_record_id_a':a['source_record_id'],'source_record_id_b':b['source_record_id'],'distance_km':distance_km((a['latitude'],a['longitude']),(b['latitude'],b['longitude']))} for i,a in enumerate(points) for b in points[i+1:]];entity=None;entitypath=''
 for pth,es in cache.items():
  if t['qid'] in es:entity=es[t['qid']];entitypath=pth;break
 if entity is None:
  for p in Path('/workspace/settlements-work/additional_uncached_census_histories_20261008').glob('batch_*.json.gz'):
   es=json.loads(gzip.decompress(p.read_bytes()))['entities']
   if t['qid'] in es:entity=es[t['qid']];entitypath=str(p);break
 conflicts.append({'wikidata_id':t['qid'],'current_source_record_id':sid,'current_name':t['name'],'current_population':t['population'],'all_component_native_IDs_json':json.dumps(list(g.source_record_id)),'all_component_native_context_json':g[['source_record_id','census_year','settlement_name','settlement_type','region_norm','district_raw','population','population_value_quality']].to_json(orient='records',force_ascii=False),'active_points_and_origin_provenance_json':json.dumps(points,ensure_ascii=False),'point_pair_distances_json':json.dumps(distances),'own_P625_claims_json':json.dumps((entity or {}).get('claims',{}).get('P625',[]),ensure_ascii=False),'entity_source_path':entitypath,'entity_source_sha256':sha(Path(entitypath)) if entitypath else '', 'article_proof_status':'not_in_requested_cached_entity_payload; no new article or coordinate assertion','hold_reason':t['hold_reason'],'status':'held_for_separate_own_source_coordinate_correction'})
pd.DataFrame(conflicts).to_csv(O/'largest_hard_point_conflicts.csv',index=False)
refs=json.loads((C/'census_reference_source_witnesses.json').read_text());(O/'census_reference_source_witnesses.json').write_text(json.dumps(refs,indent=2,ensure_ascii=False))
for v in refs.values():pins[v['source_path']]=v['source_sha256']

net={str(y):{'rows':int(((cr.year==y)&cr.net_new_selected_ID_credit).sum()),'population':int(cr.loc[(cr.year==y)&cr.net_new_selected_ID_credit,'source_population'].sum())} for y in [2002,2010,2021]}
(O/'source_manifest.json').write_text(json.dumps(pins,indent=2))
receipt={'status':'applied_qualified_secondary_census_referenced_own_physical_series','baseline_stage':25,'accepted_series':614,'accepted_observations':len(out),'historical_secondary_nonadditive_observations':guidchecks,'native_observations_by_year':{str(y):int(((out.year==y)&~out.nonadditive_observation).sum()) for y in [2002,2010,2021]},'net_selected_source_id_credit_by_year':net,'native_literal_zero_rows_preserved':int((cr.source_population==0).sum()),'API_requests':0,'ordinary_graph_modified':False,'protected_population_values_modified':False,'bound_historical_native_rows_only':True,'secondary_histories_nonadditive_blank_selected_IDs':True,'boundary_comparability':'UNKNOWN','error_rate':'uncalibrated','historical_point_use':'retrospective continuity inference from current admitted ownNP representative point; not historical coordinate measurement','raw_source_primary_authentication':'secondary census references not independently primary verified; native source quality retained','wall_seconds':time.monotonic()-T,'outputs':{p.name:sha(p) for p in O.glob('*') if p.suffix in ('.csv','.json') and p.name!='application_receipt.json'}}
tmp=O/'application_receipt.tmp';tmp.write_text(json.dumps(receipt,indent=2,ensure_ascii=False));tmp.replace(O/'application_receipt.json');print(json.dumps(receipt,ensure_ascii=False))
