from pathlib import Path
import pandas as pd,json,gzip,hashlib,re,xlrd
O=Path(__file__).parent;A=Path('research_rebuild/evidence/over500_east_alternative_point_sources_20261009');R=pd.read_csv(O.parent/'remaining81_native_point_targets.csv').fillna('');D=pd.read_pickle('/dev/shm/over500-20261009/east_enriched.pkl');N=pd.read_csv(A/'nominatim_own_feature_candidates.csv.gz').fillna('');F=A/'nominatim_all81_capture_bundle.json.gz';J=json.load(gzip.open(F));sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();W=[];P=[];raw=[]
for t in R[R.settlement_name.eq('Воронина')].itertuples():
 fid='node/1376406329';n=N[N.source_record_id.eq(t.source_record_id)&N.feature_id.eq(fid)].iloc[0];a=json.loads(n.address_json);assert a['city']=='Тюмень';d=D[D.source_record_id.eq(t.source_record_id)].iloc[0];competitors=N[N.source_record_id.eq(t.source_record_id)];rule='Native ownВоронина physically in Tyumen:2002 raw explicit parent Сельсоветы подчиненные администрации Калининского района г.Тюмени and Рощинскийсельсовет;2010 native publishedcountyТюмень. Distinct Ишимскийsame-name hamlet rejected; selected ownsuburbpoint, not citycenter.'
 if t.census_year==2010:assert t.district_raw=='Тюмень'

 bi=next(i for i,v in enumerate(J)if v['receipt']['source_record_id']==t.source_record_id);fi=next(i for i,v in enumerate(J[bi]['response'])if str(v['osm_type'])+'/'+str(v['osm_id'])==fid);s=J[bi]['response'][fi];assert float(s['lat'])==n.latitude and float(s['lon'])==n.longitude
 nativefile=Path('/workspace/settlements-raw')/d.source_file;b=xlrd.open_workbook(str(nativefile));sn=t.source_record_id.rsplit(':',2)[1];sh=b.sheet_by_name(sn);row=int(t.source_record_id.rsplit(':',1)[1])-1
 if t.census_year==2002:assert 'Калининского района г. Тюмени' in str(sh.row_values(2))
 raw.append(dict(source_record_id=t.source_record_id,source_file=str(nativefile),sha256=sha(nativefile),row0=row,raw_cells=sh.row_values(row),native_parent_heading=(sh.row_values(2)if t.census_year==2002 else t.district_raw)))
 idx=len(W);W.append(dict(target_source_record_id=t.source_record_id,native_name=t.settlement_name,native_type=t.settlement_type,native_county=t.district_raw,native_population=t.population,actual_own_feature=s,all_returned_rival_features=competitors.to_dict('records'),rule=rule,retrospective_inference=True,source_accuracy_unknown=True))
 P.append(dict(target_source_record_id=t.source_record_id,latitude=n.latitude,longitude=n.longitude,coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_source_record_id='osm:'+fid,point_origin_file=str(F),point_origin_sha256=sha(F),point_origin_locator=f'[{bi}].response[{fi}];osm={fid}',point_origin_kind='direct_OSM_own_named_populated_locality_coordinate',coordinate_binding_rule=rule,point_use_inference='Explicit retrospective own-locality representative point inference; exact censusday measurement and population boundaries unknown.',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,external_provider_ID_binding_asserted=True,evidence_file=str(O/'point_binding_witnesses.json.gz'),evidence_locator=f'[{idx}]'))
pd.DataFrame(P).to_csv(O/'accepted_point_use_delta.csv',index=False);pd.DataFrame(columns=['from_source_record_id','to_source_record_id','relation','decision_status','admission_method','admission_rule','evidence_file','evidence_locator']).to_csv(O/'accepted_identity_edge_delta.csv',index=False);pd.DataFrame([dict(source_record_id=p['target_source_record_id'],disposition='accepted_native_county_and_distinct_ownplace_OSM_point',ordinary_identity_edges_added=False,missing_year_population_assigned=False)for p in P]).to_csv(O/'record_dispositions.csv',index=False)
for name,values in [('point_binding_witnesses.json.gz',W),('native_source_row_witnesses.json.gz',raw)]:
 with gzip.open(O/name,'wt')as f:json.dump(values,f,ensure_ascii=False)
m=dict(baseline_stage=71,accepted_own_point_uses=len(P),identity_edges_added=0,population_values_modified=False,source_capture=dict(path=str(F),sha256=sha(F)),validation=dict(durable_actual_capture_reopened=True,native_raw_rows_reopened=True,native_counties_bound=True,distinct_station_settlement_not_station_infrastructure=True),frozen_files=[dict(name=f.name,sha256=sha(f),bytes=f.stat().st_size)for f in sorted(O.iterdir())if f.is_file()]);(O/'freeze_manifest.json').write_text(json.dumps(m,ensure_ascii=False,indent=2));print(len(P))
