"""Closed published source-hierarchy territorial event scope; not ordinary NP identity."""
import sys,json,re,gzip,collections,math
from pathlib import Path
import pandas as pd,pyarrow.parquet as pq,xlrd
ROOT=Path('/workspace/russian-settlements-research');E=ROOT/'research_rebuild/evidence';OUT=Path(__file__).parent;R=E/'voronezh_closed_roster_resolution_20261008';OLD=E/'voronezh_complete_named_event_reserve_20261007';REPORT=E/'working_full_chain_20261007';RAW=Path('/workspace/settlements-raw');sys.path.insert(0,str(ROOT/'research_rebuild/mass_linkage'))
from working_state_20261007 import load
from current_chain_state_20261007 import sha,normalize
STATUS='accepted_complete_named_event_scope_secondary_event_witness';GROUP='Voronezh_2011_closed_source_hierarchy'
text=(R/'archive.txt').read_text();clause=re.search(r'Статья 1\s+(.*?)\s+Статья 2',text,re.S).group(1);literal=re.search(r'город Воронеж:\s*(.*?)\s*в форме их присоединения',clause,re.S).group(1);names=[n.strip() for n in literal.split(',')];assert len(names)==22
assert 'N 136-ОЗ' in text and 'с 1 января 2011 года' in text and 'строки 32.2 - 32.23 исключить' in text
legal=pd.DataFrame({'legal_order':range(1,23),'literal_legal_unit':names,'law_date':'2010-12-24','effective_relations_date':'2011-01-01','law_number':'136-ОЗ','source_path':str(R/'archive.html.gz'),'source_sha256':sha(R/'archive.html.gz')});legal.to_csv(R/'actual_22_legal_names.csv',index=False)
s=load(stage=24);meta=pq.read_table(s.inputs[0],columns=['source_record_id','source_sheet','source_row','source_name_raw']).to_pandas();o=s.obs.merge(meta,on='source_record_id');inventory=pd.read_csv(OLD/'literal_native_parent_hierarchy_inventory.csv',keep_default_na=False)
selected=[];witness=[]
def add(g,role,raw=''):
 assert len(g)==1;row=g.iloc[0];assert row.is_additive_settlement_record and math.isfinite(row.population)
 selected.append((row,role));path=RAW/row.source_file
 witness.append({'source_record_id':row.source_record_id,'census_year':int(row.census_year),'population':int(row.population),'settlement_name':row.settlement_name,'settlement_type':row.settlement_type,'region_norm':row.region_norm,'district_raw':row.district_raw,'source_file':row.source_file,'source_file_sha256':sha(path),'source_row_locator':f'{row.source_sheet}!row={row.source_row}','source_population_quality':row.population_value_quality,'raw_row':raw,'source_grain_role':role,'selected_population_unmodified':True})
city=o[o.region_norm.eq('воронежская')&o.settlement_name.eq('Воронеж')&o.settlement_type.eq('город')];assert len(city)==3
for year in [2002,2010,2021]:add(city[city.census_year.eq(year)],'own_receiving_city_atomic_NP')
ur=inventory[inventory.census_year.eq(2002)&inventory.source_file.str.contains('2002_official')&inventory.source_row_1based.between(364,367)];assert len(ur)==4
for r in ur.itertuples():
 g=o[o.census_year.eq(2002)&o.source_file.eq(r.source_file.replace(str(RAW)+'/',''))&o.source_row.eq(r.source_row_1based)&o.source_sheet.eq('0')];add(g,'2002_own_urban_subordinate_atomic_NP',r.raw_row);assert int(g.iloc[0].population)==int(float(r.actual_first_count))
rural=inventory[inventory.census_year.eq(2002)&inventory.source_file.str.contains('004_f58')&inventory.native_NP_label.astype(str).str.lower().eq('true')];assert len(rural)==56 and int(pd.to_numeric(rural.actual_first_count).sum())==36402
for r in rural.itertuples():
 g=o[o.census_year.eq(2002)&o.source_file.eq(r.source_file.replace(str(RAW)+'/',''))&o.source_row.eq(r.source_row_1based)&o.source_sheet.eq('Sheet1')];add(g,'2002_atomic_rural_leaf_of_complete_printed_city_subordination_hierarchy',r.raw_row);assert int(g.iloc[0].population)==int(float(r.actual_first_count))
# Original closed rural block next row is the next city; all aggregate headings are controls, never members.
rbook=xlrd.open_workbook(str(RAW/'data/raw/2002/004_f58b08b4f6_02c_Voronezhskaja.xls'));rsh=rbook.sheet_by_name('Sheet1');boundary=' | '.join(str(v) for v in rsh.row_values(71) if v!='');assert 'администрации г. Лиски' in boundary
raw2010=pd.read_csv(OLD/'observed_2010_subordinate_22_names_NOT_complete_event_roster.csv');primary={'Краснолесный':'ROSSTAT2010:T5:p20:l20','Придонской':'ROSSTAT2010:T5:p20:l21','Сомово':'ROSSTAT2010:T5:p20:l22','Шилово':'ROSSTAT2010:T5:p20:l23'};replacements=[];bindings=[]
def unit_key(label):
 x=normalize(label);m=re.match(r'^(рабочий поселок|пгт|поселок|село)\s+(.*)$',x);assert m,label
 kind='пгт' if m.group(1) in ['рабочий поселок','пгт'] else m.group(1);name=re.sub(r'\s+рп$','',m.group(2));return kind+'|'+name
legal_keys={unit_key(n):n for n in names};assert len(legal_keys)==22
for r in raw2010.itertuples():
 key=unit_key(r.native_label);assert key in legal_keys
 if key.startswith('пгт|'):
  name=next(x for x in primary if unit_key('пгт '+x)==key);g=o[o.source_record_id.eq(primary[name])];add(g,'2010_own_urban_subordinate_primary_replacement',r.raw_row);row=g.iloc[0]
  loc=json.loads(row.source_locator);assert unit_key(loc['raw_label'])==key
  primarytext=(R/'native2010_primary_page20.txt').read_text();matching=[line for line in primarytext.splitlines() if name in line and 'пгт' in line];assert len(matching)==1 and str(int(row.population)) in matching[0]
  replacements.append({'legal_unit':legal_keys[key],'selected_primary_id':row.source_record_id,'selected_primary_count':int(row.population),'raw_secondary_xls_count':int(float(r.actual_first_count)),'count_difference_preserved':int(row.population)-int(float(r.actual_first_count)),'primary_raw_line':matching[0],'primary_file':str(RAW/row.source_file),'primary_sha256':sha(RAW/row.source_file),'primary_locator':row.source_locator,'protected_secondary_alternative_not_overwritten':True})
 else:
  g=o[o.census_year.eq(2010)&o.source_file.eq(r.source_file.replace(str(RAW)+'/',''))&o.source_sheet.eq('Data Sheet')&o.source_row.eq(r.source_row_1based)];add(g,'2010_closed_named_rural_NP_protected_secondary_observation',r.raw_row);row=g.iloc[0];assert int(row.population)==int(float(r.actual_first_count))
 bindings.append({'legal_unit':legal_keys[key],'literal_native_2010_label':r.native_label,'native_2010_source_record_id':g.iloc[0].source_record_id,'native_2010_population':int(g.iloc[0].population),'native_2010_population_quality':g.iloc[0].population_value_quality,'source_row':r.source_row_1based,'law_year':2011})
assert {unit_key(n) for n in raw2010.native_label}==set(legal_keys)
pd.DataFrame(replacements).to_csv(OUT/'primary2010_urban_replacement_proof.csv',index=False);pd.DataFrame(bindings).to_csv(OUT/'exact_22_legal_to_native2010_bindings.csv',index=False)
# Raw published2021 parent contains exactly one NP; both counts agree. Parent row is a control only.
cur=city[city.census_year.eq(2021)].iloc[0];path=RAW/cur.source_file;raw=pq.read_table(path,columns=['object_level','object_name','region','mun_upper','mun_lower','settlement','population','oktmo']).to_pandas();current_scope=raw[raw.region.eq('Воронежская область')&raw.mun_upper.eq('Городской округ город Воронеж')].copy();assert len(current_scope)==2
np=current_scope[current_scope.object_level.eq('Населенный пункт')];parents=current_scope[current_scope.object_level.eq('Муниципалитет верхнего уровня')];assert len(np)==len(parents)==1 and np.iloc[0].object_name=='г. Воронеж' and int(np.iloc[0].population)==int(parents.iloc[0].population)==int(cur.population)==1057681
current_scope['raw_parquet_row_1based']=current_scope.index+1;current_scope['source_file']=str(path);current_scope['source_sha256']=sha(path);current_scope['member_status']=['atomic_city_member' if x=='Населенный пункт' else 'aggregate_control_only' for x in current_scope.object_level];current_scope.to_csv(OUT/'published2021_complete_parent_child_scope.csv',index=False)
ids=[r.source_record_id for r,role in selected];assert len(ids)==len(set(ids))==85
frame=pd.DataFrame([{'source_record_id':r.source_record_id,'census_year':int(r.census_year),'population':int(r.population)} for r,role in selected]);totals=frame.groupby('census_year').population.sum().to_dict();assert totals=={2002:928410,2010:975305,2021:1057681}
# Preserve primary control disagreement in2010 instead of distributing68 across protected rural observations.
control_rows=[{'census_year':2002,'source_grain':'published city-with-all-subordinates aggregate control only','printed_control':928410,'own_city':848752,'urban_atomic_sum':43256,'rural_atomic_sum':36402,'complete_selected_atomic_sum':928410,'difference_control_minus_selected':0,'roster_complete':True,'control_credited_as_NP':False},{'census_year':2010,'source_grain':'published city-okrug aggregate control only','printed_control':975373,'own_city':889680,'urban_atomic_sum':45087,'rural_atomic_sum':40538,'complete_selected_atomic_sum':975305,'difference_control_minus_selected':68,'roster_complete':True,'control_credited_as_NP':False},{'census_year':2021,'source_grain':'published city-okrug aggregate control only; sole NP has same count','printed_control':1057681,'own_city':1057681,'urban_atomic_sum':0,'rural_atomic_sum':0,'complete_selected_atomic_sum':1057681,'difference_control_minus_selected':0,'roster_complete':True,'control_credited_as_NP':False}];pd.DataFrame(control_rows).to_csv(OUT/'printed_parent_controls_and_atomic_conservation.csv',index=False)
# Frozen stage24 finite all-three-point + accepted partitions/qualified/nine named-merger union.
report=json.loads((REPORT/'coverage_receipt.json').read_text());assert report['working_stage']==24
root_members=collections.defaultdict(list)
for r in s.obs.itertuples():root_members[s.uf.find(r.source_record_id)].append(r)
finite=set()
for root,rs in root_members.items():
 if s.years[root]=={2002,2010,2021} and all(r.source_record_id in s.point_rows and pd.notna(r.population) and math.isfinite(float(r.population)) for r in rs):finite.update(r.source_record_id for r in rs)
prior=finite.copy();creditpaths=[REPORT/'complete_publisher_partition_members.csv',REPORT/'qualified_scope_source_id_credit_union.csv',REPORT/'named_merger_lineage_constituents.csv']
for p in creditpaths:prior.update(pd.read_csv(p).source_record_id)
ordinary=s.obs[s.obs.is_additive_settlement_record.fillna(False)&~s.obs.region_norm.isin(['москва','санкт петербург','севастополь'])&~(s.obs.census_year.eq(2021)&s.obs.region_norm.eq('крым'))]
for y,g in ordinary.groupby('census_year'):
 expected=report['named_merger_lineage_extended_population_axis']['by_year'][str(y)];assert int(g[g.source_record_id.isin(prior)].population.sum())==expected['selected_source_ID_union_population'];assert len(g[g.source_record_id.isin(prior)])==expected['selected_source_ID_union_rows']
net=[]
for year,g in frame.groupby('census_year'):
 new=g[~g.source_record_id.isin(prior)];net.append({'group':GROUP,'census_year':int(year),'baseline_active_state':24,'new_unique_source_IDs':len(new),'net_population_gain_if_admitted':int(new.population.sum()),'net_source_record_ids_json':json.dumps(list(new.source_record_id),ensure_ascii=False),'candidate_only':False})
point=s.point_rows[cur.source_record_id];assert point['coordinate_source_record_id']==cur.source_record_id and cur.source_record_id not in s.conflicting_point_targets
# A frozen reviewed baseline may have no original measurement asset: bind the exact admitted ledger row transparently.
provenance=dict(point)
if not provenance.get('point_origin_file'):
 provenance['frozen_original_point_provenance']=dict(point);provenance['point_origin_file']=point['point_ledger_path'];provenance['point_origin_sha256']=sha(Path(point['point_ledger_path']));provenance['point_origin_locator']='target_source_record_id='+cur.source_record_id;provenance['point_origin_kind']='reviewed_frozen_assertion_ledger_row_not_historical_measurement'
law={'key':'voronezh136oz','source_class':'archived_actual_act_body','official_verified':False,'source_path':str(R/'archive.html.gz'),'source_sha256':sha(R/'archive.html.gz'),'retrieval_url':'https://web.archive.org/web/20241212043650id_/https://docs.cntd.ru/document/469702421','original_url':'https://docs.cntd.ru/document/469702421','law_number':'136-ОЗ','law_date':'2010-12-24','adopted_date':'2010-12-23','relations_effective_from':'2011-01-01','clause_or_event_provenance':clause,'secondary24_roster_error_corrected':True}
observations=[];members=[]
for year in [2002,2010,2021]:
 rows=[(r,role) for r,role in selected if int(r.census_year)==year];yearids=[r.source_record_id for r,role in rows]
 observations.append({'group':GROUP,'census_year':year,'observation_id':f'named_merger:{GROUP}:{year}','population':totals[year],'population_derivation':'sum_complete_published_source_hierarchy_atomic_leaves' if year!=2021 else 'direct_published_successor_city_sole_NP_in_parent','constituent_count':len(rows),'source_record_ids_json':json.dumps(yearids,ensure_ascii=False),'roster_complete':True,'event_source_witness_keys_json':json.dumps(['voronezh136oz']),'population_series_scope':'complete published city-with-subordinates territorial/source-hierarchy scope by census year; historical atomic rosters differ; not constant modern boundary estimate','boundary_comparability':'UNKNOWN','ordinary_same_place':False,'point_role':'representative_scope','representative_parent_source_record_id':cur.source_record_id,'latitude':point['latitude'],'longitude':point['longitude'],'point_provenance_json':json.dumps(provenance,ensure_ascii=False),'candidate_only':False,'no_fake_2021_child_population':True,'legal_basis_json':json.dumps([law],ensure_ascii=False),'members_json':json.dumps([{'source_record_id':r.source_record_id,'settlement_name':r.settlement_name,'population':int(r.population),'source_grain_role':role,'population_quality':r.population_value_quality} for r,role in rows],ensure_ascii=False),'identity_axis':'named_merger_event_lineage','official_act_verified':False,'decision_status':STATUS,'historical_2002_atomic_to_2010_legal_units_one_to_one_asserted':False,'parent_aggregate_credited_as_NP':False,'printed_parent_control':next(c['printed_control'] for c in control_rows if c['census_year']==year),'protected_value_control_difference':next(c['difference_control_minus_selected'] for c in control_rows if c['census_year']==year)})
 for r,role in rows:
  w=next(w for w in witness if w['source_record_id']==r.source_record_id);members.append({'group':GROUP,'census_year':year,'source_record_id':r.source_record_id,'settlement_name':r.settlement_name,'settlement_type':r.settlement_type,'population':int(r.population),'source_population_unmodified':True,'source_file':r.source_file,'source_file_sha256':w['source_file_sha256'],'source_row_locator':w['source_row_locator'],'component_population_separately_additive':False,'exclusive_source_ID_credit':True,'ordinary_same_place':False,'already_in_existing_source_ID_union':r.source_record_id in prior,'district_raw':r.district_raw,'additive_only_within_complete_named_year_group':True,'separate_population_credit_in_addition_to_group':False,'ordinary_same_place_edge_created':False,'own_native_point_available':r.source_record_id in s.point_rows,'candidate_only':False,'decision_status':STATUS,'source_population_quality':r.population_value_quality,'source_grain_role':role})
points=[{'group':GROUP,'parent_source_record_id':cur.source_record_id,'latitude':point['latitude'],'longitude':point['longitude'],'scope_point_role':'representative_scope','verified_active_state':24,'historical_constituent_own_point_asserted':False,'point_provenance_json':json.dumps(provenance,ensure_ascii=False),'candidate_only':False,'decision_status':STATUS}]
edges=[{'group':GROUP,'from_observation_id':f'named_merger:{GROUP}:{a}','to_observation_id':f'named_merger:{GROUP}:{b}','relation':'complete_named_merger_lineage','ordinary_same_place':False,'boundary_comparability':'UNKNOWN','candidate_only':False,'decision_status':STATUS,'event_relations_effective_date':'2011-01-01'} for a,b in [(2002,2010),(2010,2021)]]
for key,rows in [('group_observations',observations),('constituent_credit_union',members),('representative_scope_points',points),('event_edges',edges)]:pd.DataFrame(rows).to_csv(OUT/('accepted_'+key+'.csv'),index=False)
pd.DataFrame(witness).to_csv(OUT/'verified_native_source_bindings.csv',index=False);pd.DataFrame(net).to_csv(OUT/'net_source_ID_union_gain.csv',index=False)
inputpaths=s.inputs+creditpaths+[R/'native2002_eight_subgroup_closure.csv']+[REPORT/'coverage_receipt.json',OLD/'literal_native_parent_hierarchy_inventory.csv',OLD/'observed_2010_subordinate_22_names_NOT_complete_event_roster.csv',R/'archive.html.gz',R/'archive.txt',R/'native2010_primary_page20.txt']+[RAW/r.source_file for r,role in selected]
receipt={'status':'applied_separate_complete_named_merger_event_lineage','groups':1,'observations':3,'constituents':85,'representative_scope_points':1,'event_edges':2,'admission_stage':24,'actual_legal_names':22,'secondary24_named_roster_claim_rejected':True,'actual_act_number':'136-ОЗ','actual_act_date':'2010-12-24','event_relations_effective_from':'2011-01-01','ordinary_same_place_graph_modified':False,'historical_child_points_or_missing_year_populations_created':False,'boundary_comparability':'UNKNOWN','modern_boundary_harmonization_asserted':False,'official_act_verified':False,'legal_source_quality':'full actual primary-law text preserved via exact archived CNTD act snapshot; live publisher authentication unasserted','source_population_values_modified':False,'group_populations':{str(y):totals[y] for y in totals},'printed_primary2010_parent_control':975373,'selected_protected2010_sum':975305,'protected2010_control_difference_not_allocated':68,'new_ordinary_NP_rows_or_parent_reinterpretations':0,'net_gain':net,'inputs_sha256':{str(p):sha(p) for p in dict.fromkeys(inputpaths)},'outputs':{p.name:sha(p) for p in OUT.glob('*.csv')},'scope_limits':['Complete observed city-with-subordinates source-hierarchy territories by census year, not identical modern borders.','2002 56 rural atomic leaves are not individually equated to2010 22 legal units.','Aggregate parent and subordinate headings are controls only, never NP members.','Current receiving-city representative point applies to group scope, not individual historical constituents.']};(OUT/'application_receipt.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n');print(json.dumps({k:receipt[k] for k in ['status','group_populations','net_gain']},ensure_ascii=False,indent=2))
