from pathlib import Path
import sys,json,hashlib,re,math
import pandas as pd
OUT=Path(__file__).parent;sys.path.insert(0,'/workspace/russian-settlements-research/research_rebuild/mass_linkage')
from working_state_20261007 import load
from current_chain_state_20261007 import normalize,distance_km
s=load(17);s.obs['simple_name']=s.obs.settlement_name.map(normalize);r=pd.read_csv(OUT/'reference_confirmed_full3_reserve.csv').fillna('');a=pd.read_csv(OUT/'actual_target_year_claims.csv').fillna('');qc=pd.read_csv(OUT/'census_reference_checks.csv').fillna('');exclude=json.loads((OUT/'exclusion_frozen.json').read_text())['source_ids'];partition=pd.read_csv('/workspace/russian-settlements-research/research_rebuild/evidence/complete_numbered_partition_batch_20261007/accepted_exclusive_member_projection.csv',dtype=str); exclude=list(set(exclude)|set(partition.source_record_id)); covered={sid for sid in s.point_rows if s.years[s.uf.find(sid)]=={2002,2010,2021}}|set(exclude);records=[];held=[]
for t in r.itertuples():
 if t.sid in covered:
  held.append({'qid':t.qid,'name':t.name,'hold_reason':'current_source_id_already_credited_in_partition_or_qualified_scope','population_2021':t.population_2021_selected});continue
 e=json.loads(Path(t.source_path).read_text())['entities'][t.qid];cs=e.get('claims',{});v=cs.get('P625',[{}])[0].get('mainsnak',{}).get('datavalue',{}).get('value',{});hold=[]
 if 'бывш' in t.description.lower() or cs.get('P576'):hold.append('former_or_dissolved_locality_requires_event_review')
 # Optional Wiki coordinates do not replace the independently admitted NP point.
 if hold:held.append({'qid':t.qid,'name':t.name,'hold_reason':';'.join(hold),'population_2021':t.population_2021_selected});continue
 aliases={normalize(t.name),normalize(t.wikidata_label)};aliases.update(normalize(x['value']) for x in e.get('aliases',{}).get('ru',[])); aliases.update(normalize(x.get('datavalue',{}).get('value',{}).get('text')) for st in cs.get('P1448',[]) for x in [st.get('mainsnak',{})] if isinstance(x.get('datavalue',{}).get('value'),dict))
 for y in (2002,2010,2021):
  pp=getattr(t,'p'+str(y));cand=s.obs[(s.obs.census_year==y)&(s.obs.region_norm==t.region)&s.obs.simple_name.isin(aliases)]
  if y==2021:cand=s.by_id.loc[[t.sid]]
  # Reuse candidates shown explicitly. Similarity or count equality alone is never binding.
  ids=cand.source_record_id.tolist();rr=qc[(qc.qid==t.qid)&(qc.year==y)&(qc.census_reference_confirmed.astype(str).str.lower()=='true')];row=rr.iloc[0] if len(rr) else qc[(qc.qid==t.qid)&(qc.year==y)].iloc[0]
  records.append({'physical_series_candidate_id':'WIKIDATA-ACTUAL-'+t.qid,'wikidata_id':t.qid,'census_year':y,'population':pp,'current2021_source_record_id':t.sid,'preferred_existing_selected_source_record_id':ids[0] if len(ids)==1 else '', 'existing_selected_source_candidates_json':json.dumps(ids),'selected_source_reuse_status':'unique_same_region_name_or_own_alias; county_source_review_pending; native_count_preserved' if len(ids)==1 else 'missing_or_ambiguous_selected_source; own_dated_secondary_alternative_only','existing_selected_source_contexts_json':cand[['source_record_id','settlement_name','settlement_type','district_raw','region_norm','population','source_file','source_sha256','source_locator']].to_json(orient='records',force_ascii=False), 'native_selected_population':float(cand.population.iloc[0]) if len(ids)==1 else '', 'secondary_claim_differs_from_native':len(ids)==1 and float(cand.population.iloc[0])!=pp, 'existing_selected_source_already_credited':len(ids)==1 and ids[0] in covered,'is_additive_settlement_record':False,'status':'candidate_only_secondary_not_primary_verified','date_precision':int(a[a.statement_id==row.statement_id].iloc[0].date_precision),'declared_date':row.declared_date,'date_assignment':'explicit_census_reference_year_only; no_exact_day_asserted','population_scope':'own_physical_locality_secondary_claim_continuity_pending','statement_id':row.statement_id,'source_file':t.source_path,'source_sha256':t.source_sha256,'source_locator':f'entities.{t.qid}.claims.P1082[{row.statement_id}]','census_reference_ids':row.reference_ids,'census_reference_labels_json':row.reference_labels_json,'latitude':t.latitude,'longitude':t.longitude,'point_reuse_flag':'accepted_current_own_point; historical_continuity_inference_pending','bounds':'UNKNOWN','error_rate':'uncalibrated'})
f=pd.DataFrame(records);f.to_csv(OUT/'candidate_nonadditive_physical_observations.csv',index=False);pd.DataFrame(held).to_csv(OUT/'event_or_coordinate_holds.csv',index=False)
net=[]
for y,g in f.groupby('census_year'):
 ids=set(g.loc[~g.existing_selected_source_already_credited,'preferred_existing_selected_source_record_id'])-{''};pop=float(s.by_id.loc[list(ids),'population'].sum()) if ids else 0
 net.append({'year':y,'unique_uncredited_selected_source_ids':len(ids),'conditional_selected_population_net_potential':pop,'candidate_population_all_own_dated_secondary':float(g.population.sum()),'actual_admitted_gain':0,'qualification':'not admitted; historical continuity/county/type/source reuse review pending; alternative rows nonadditive'})
pd.DataFrame(net).to_csv(OUT/'unique_source_id_net_potential.csv',index=False);rc=json.loads((OUT/'receipt.json').read_text());rc.update({'event_coordinate_held_series':len(held),'final_reference_confirmed_nonheld_series':int(f.physical_series_candidate_id.nunique()),'final_current2021_population_candidate_potential':float(f[f.census_year==2021].population.sum()),'selected_id_conditional_net_potential_by_year':net});(OUT/'receipt.json').write_text(json.dumps(rc,indent=2,ensure_ascii=False));print(json.dumps(net));print('held',held)
