from pathlib import Path
import sys,json,gzip,re
import pandas as pd,duckdb,xlrd
R=Path('/workspace/russian-settlements-research');O=Path(__file__).parent;sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from current_chain_state_20261007 import normalize,sha,distance_km
S=Path('/workspace/settlements-delivery/continuation-consolidated-20261003/selected_observations.parquet');P=O/'SHARED_points_compact_stage61.parquet';C=O/'SHARED_component_snapshot_stage61.csv.gz';Q=Path('/workspace/settlements-work/continuation_20261004/R4/residual_alias_fetch/raw_entity_batches/raw_alias_batch_001.json');L=Path('/workspace/settlements-work/temporal_residual_mass_20261008_raw/chechnya_2019_54rz_county_transfer.pdf');T=O/'chechnya_2019_54rz_county_transfer.txt';W=O/'ilaskhan_own_article.json.gz';con=duckdb.connect();f=con.execute("select * from read_parquet(?) where region_norm='чеченская' and (settlement_name ilike '%ласхан%' or settlement_name ilike '%лсхан%')",[str(S)]).fetchdf();assert len(f)==3 and set(f.census_year)=={2002,2010,2021};assert list(f.sort_values('census_year').population)==[4486,5042,5862];f=f.sort_values('census_year');cur=f[f.census_year.eq(2021)].iloc[0];p=con.execute('select * from read_parquet(?) where source_record_id=?',[str(P),cur.source_record_id]).fetchdf().iloc[0].to_dict();assert p['conflicting_point_target']=='False';cs=pd.read_csv(C,dtype=str,keep_default_na=False).set_index('source_record_id');assert len(set(cs.loc[f.source_record_id,'root']))==3;assert all(cs.loc[z.source_record_id,'component_years']==str(z.census_year) for z in f.itertuples());e=json.loads(Q.read_text())['entities']['Q4199185'];claims=e['claims'];get=lambda prop:[x['mainsnak'].get('datavalue',{}).get('value') for x in claims.get(prop,[]) if x.get('rank')!='deprecated'];assert '96212000007' in get('P721') and '96612495101' in get('P764');assert cur.okato=='96212000007' and cur.oktmo=='96612495101';coords=get('P625')[0];d=distance_km((coords['latitude'],coords['longitude']),(float(p['latitude']),float(p['longitude'])));assert d<1;assert any(x['id']=='Q532' for x in get('P31'));law=T.read_text();assert 'селе Илсхан-Юрт' in law and '1 января 2020 года' in law and 'Гудермесского муниципального района' in law and 'Курчалоевского муниципального района' in law;wiki=json.loads(gzip.decompress(W.read_bytes()));page=next(x for x in wiki['query']['pages'].values() if x.get('revisions'));text=page['revisions'][0]['slots']['main']['*'];assert page['title']=='Иласхан-Юрт' and 'Илсхан-Йурт' in text and '1 января 2020' in text
pins={str(q):sha(q) for q in [S,P,C,Q,L,T,W]};proof=[]
for z in f.itertuples():
 rawpath=Path('/workspace/settlements-raw')/z.source_file;assert rawpath.is_file();pins[str(rawpath)]=sha(rawpath)
 if z.census_year<2021:
  book=xlrd.open_workbook(str(rawpath),on_demand=True);sh=book.sheet_by_name(str(z.source_sheet));rn=int(z.source_row)-1;vals=sh.row_values(rn);positions=[i for i,v in enumerate(vals) if isinstance(v,str) and normalize(v)==normalize(z.source_name_raw)];assert positions;assert any((isinstance(v,(int,float)) or (isinstance(v,str) and re.fullmatch('[0-9]+',v.strip()))) and float(v)==z.population for v in vals[min(positions)+1:]);record={'source_record_id':z.source_record_id,'year':z.census_year,'native_name':z.settlement_name,'native_population':int(z.population),'source_file':str(rawpath),'source_sha256':pins[str(rawpath)],'source_locator':f'sheet={sh.name};row1based={rn+1}','raw_own_label_count_passed':True,'raw_row_cells_json':json.dumps(vals,ensure_ascii=False)}
  if z.census_year==2002:
   headers=[]
   for nr in range(rn-1,max(-1,rn-250),-1):
    vs=sh.row_values(nr)
    if any(isinstance(v,str) and 'гудермес' in normalize(v) and 'район' in normalize(v) for v in vs):headers.append((nr+1,vs));break
   assert headers;record['actual_historical_county_header_json']=json.dumps(headers,ensure_ascii=False)
  book.release_resources()
 else:
  rr=con.execute('select object_name,population,mun_upper,okato_dadata,oktmo from read_parquet(?) limit1 offset161749'.replace('limit1','limit 1').replace('offset161749','offset 161749'),[str(rawpath)]).fetchone();assert rr[0]==z.source_name_raw and rr[1]==5862 and 'Курчалоевский' in rr[2];record={'source_record_id':z.source_record_id,'year':2021,'native_name':z.settlement_name,'native_population':5862,'source_file':str(rawpath),'source_sha256':pins[str(rawpath)],'source_locator':'parquet_row_1based=161750','raw_own_label_count_passed':True,'raw_native_object_json':json.dumps(rr,ensure_ascii=False)}
 proof.append(record)
# Existing ownpoint cannot already serve a different same-year historical native record.
pointall=con.execute('select source_record_id,latitude,longitude from read_parquet(?) where latitude=? and longitude=?',[str(P),p['latitude'],p['longitude']]).fetchall();assert pointall==[(cur.source_record_id,p['latitude'],p['longitude'])];con.close();rule='Literal unique Chechen native village rows4486/5042/5862; old spellingИласхан-Юрт bound to currentИлсхан-Юрт by own physical-villageQ4199185 with exact current nativeOKATO/OKTMO and independentownP625<1km; actual2002printedGudermescounty; officialChechnya54-РЗ19.11.2019 Article1/2 moves named village-containing settlementGudermes→Kurchaloy effective01.01.2020Article4; independent ownarticle literal spelling/history corroboration; same physical locality with dated county transfer, no newsettlement or merge/split claimed; old pointuses explicit currentrepresentative continuity inference'
edges=[];points=[]
for z in f[f.census_year.lt(2021)].itertuples():
 edges.append({'from_source_record_id':z.source_record_id,'to_source_record_id':cur.source_record_id,'relation':'same_place','decision_status':'checked_rule_accepted','admission_rule':rule,'source_binding_proof':'ilaskhan_native_source_checks.csv.gz;ilaskhan_admission_receipt.json','population_boundary_comparability_asserted':False});pp={k:v for k,v in p.items() if k not in ['source_record_id','point_ledger_path','conflicting_point_target']};pp.update(target_source_record_id=z.source_record_id,latitude=float(p['latitude']),longitude=float(p['longitude']),coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_binding_rule=rule,point_use_inference='modern_own_representative_point_reused_through_dated_county_transfer_native_identity',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False);points.append(pp)
pd.DataFrame(proof).to_csv(O/'ilaskhan_native_source_checks.csv.gz',index=False,compression={'method':'gzip','mtime':0});r={'status':'checked_rule_accepted_source_bound_dated_county_transfer_same_place','native_year_populations':{str(int(x.census_year)):int(x.population) for x in f.itertuples()},'native_source_record_ids':list(f.source_record_id),'current_ownpoint_source_record_id':cur.source_record_id,'own_Q4199185_point_distance_km':d,'own_native_OKATO_OKTMO_match':True,'official_law':'Chechnya54-РЗ19.11.2019 Articles1/2/4','effective_date':'2020-01-01','wiki_revision_id':page['revisions'][0]['revid'],'source_input_pins':pins,'raw_source_checks_sha256':sha(O/'ilaskhan_native_source_checks.csv.gz'),'edge_count':2,'inferred_old_point_count':2,'scope_population_values_imputed':False,'historical_census_coordinates_asserted':False};(O/'ilaskhan_admission_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n')
for n,new in [('accepted_identity_edge_delta.csv.gz',edges),('accepted_point_use_delta.csv.gz',points)]:
 old=pd.read_csv(O/n,dtype=str,keep_default_na=False);combined=pd.concat([old,pd.DataFrame(new)],ignore_index=True);combined.to_csv(O/n,index=False,compression={'method':'gzip','mtime':0})
g=pd.read_csv(O/'exact_net_primary_source_ID_union_gain.csv.gz',keep_default_na=False);new=pd.DataFrame([{'source_record_id':z.source_record_id,'year':z.census_year,'population':int(z.population),'name':z.settlement_name,'population_quality':z.population_value_quality} for z in f.itertuples()]);g=pd.concat([g,new],ignore_index=True);assert g.source_record_id.is_unique;g.to_csv(O/'exact_net_primary_source_ID_union_gain.csv.gz',index=False,compression={'method':'gzip','mtime':0});receipt=json.loads((O/'admission_receipt.json').read_text());receipt['accepted_edges']+=2;receipt['accepted_continuity_point_uses']+=2;receipt['actual_formation_plus_direct_native_UID_delta']={str(y):{'source_records':int(g.year.eq(y).sum()),'population':int(g.loc[g.year.eq(y),'population'].sum())} for y in [2002,2010,2021]};receipt['input_pins'].update(pins);receipt['targeted_dated_county_transfer_packet']='ilaskhan_admission_receipt.json';receipt['output_pins']={q.name:sha(q) for q in O.glob('*.csv.gz') if not q.name.startswith('SHARED')};(O/'admission_receipt.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n');print(json.dumps({k:v for k,v in receipt.items() if k not in ['input_pins','output_pins']},ensure_ascii=False))
