"""Discovery only: preserve raw namespaces; one exact source header interprets its region."""
import json,sys
from pathlib import Path
import duckdb,xlrd,pandas as pd
R=Path('/workspace/russian-settlements-research');O=Path(__file__).parent;sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from current_chain_state_20261007 import sha,normalize
from scan import nm,ty,cn
source=Path('/workspace/settlements-raw/data/raw/2002/086_3c3b73a0d2_EvrejskajaAO.xls');book=xlrd.open_workbook(str(source),on_demand=True);sheet=book.sheet_by_name('Sheet1');assert sheet.cell_value(0,0)=='Еврейская АО'
selected=Path('/workspace/settlements-delivery/continuation-consolidated-20261003/selected_observations.parquet');c=duckdb.connect();old=c.execute("select source_record_id,census_year,settlement_name,settlement_type,region_norm,district_raw,population,population_value_quality,source_file,source_locator,source_row,source_sheet,source_name_raw from read_parquet(?)where census_year=2002 and source_file='data/raw/2002/086_3c3b73a0d2_EvrejskajaAO.xls'",[str(selected)]).fetchdf();other=c.execute("select source_record_id,census_year,settlement_name,settlement_type,region_norm,district_raw,population,population_value_quality,source_file,source_locator from read_parquet(?)where census_year in(2010,2021) and region_norm='еврейская'",[str(selected)]).fetchdf();c.close();out=[];checks=[]
for a in old.itertuples():
 rn=int(a.source_row)-1;vals=sheet.row_values(rn);assert normalize(vals[0])==normalize(a.source_name_raw);assert float(vals[1])==a.population;checks.append({'source_record_id':a.source_record_id,'raw_own_label':vals[0],'raw_whole_population':vals[1],'protected_native_population':a.population,'protected_native_quality':a.population_value_quality,'raw_region_norm_preserved':a.region_norm,'interpreted_source_region':'еврейская','region_header_raw':'Еврейская АО','source_namespace_witness':'Sheet1!A1','source_sha256':sha(source),'raw_locator':f'Sheet1;row1based={rn+1}'})
 peers=other[other.settlement_name.map(nm).eq(nm(a.settlement_name))]
 for b in peers.itertuples():out.append({'old2002_source_record_id':a.source_record_id,'old2002_native_name':a.settlement_name,'old2002_native_type':a.settlement_type,'old2002_native_county':a.district_raw,'old2002_native_population':a.population,'old2002_raw_region_norm':a.region_norm,'interpreted_source_region':'еврейская','target_source_record_id':b.source_record_id,'target_year':b.census_year,'target_name':b.settlement_name,'target_type':b.settlement_type,'target_county':b.district_raw,'target_population':b.population,'literal_class_compatible':ty(a.settlement_type)==ty(b.settlement_type),'literal_county_compatible':cn(a.district_raw)==cn(b.district_raw),'admission_status':'discovery_only_requires_actual51_component_and_rival_review','source_namespace_witness':'Sheet1!A1=Еврейская АО','source_namespace_raw_file':str(source),'source_namespace_raw_file_sha256':sha(source),'population_equality_not_checked':True})
pd.DataFrame(out).to_csv(O/'source_namespace_eao_candidate_discovery.csv.gz',index=False,compression={'method':'gzip','mtime':0});pd.DataFrame(checks).to_csv(O/'source_namespace_eao_raw_leaf_checks.csv.gz',index=False,compression={'method':'gzip','mtime':0});r={'status':'one_exact_source_header_alias_verified_discovery_only_no_admission_or_shared_mutation','affected_selected_native_rows':len(old),'native_population_unchanged':int(old.population.sum()),'all_literal_native_leaf_rows_reopened':True,'source_region_header':'Еврейская АО','source_region_header_locator':'Sheet1!A1','raw_region_namespace_not_rewritten':True,'source_header_and_leaf_file':str(source),'source_header_and_leaf_file_sha256':sha(source),'selected_sha256':sha(selected),'all_name_rival_pairs':len(out),'class_and_literal_county_compatible_pairs':sum(x['literal_class_compatible'] and x['literal_county_compatible'] for x in out),'outputs':{n:sha(O/n) for n in ['source_namespace_eao_candidate_discovery.csv.gz','source_namespace_eao_raw_leaf_checks.csv.gz']}};(O/'source_namespace_eao_discovery_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2));print(json.dumps(r,ensure_ascii=False))
