from pathlib import Path
import pandas as pd,json,gzip,hashlib,xlrd,re
from bs4 import BeautifulSoup
O=Path(__file__).parent;D=pd.read_pickle('/dev/shm/over500-20261009/east_enriched.pkl');sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();F=O/'all_chirshkasy_OSM_ownnamed_features.json.gz';J=json.load(gzip.open(F));si=next(i for i,v in enumerate(J['elements'])if v['type']=='node'and v['id']==972150154);s=J['elements'][si];assert s['tags']['oktmo:user']=='97544000530'and s['tags']['wikidata']=='Q99012665'and s['tags']['wikipedia']=='ru:Чиршкасы (Чиршкасинское сельское поселение)'and s['tags']['place']=='village';C=Path('research_rebuild/evidence/over500_chirshkasy_correct_ownpoint_sources_20261009/classinform_explicit_recoding.html.gz');b=gzip.open(C,'rb').read().decode('cp1251');assert re.search(r'97644482101.{0,400}97544000530',b);nf=Path('/workspace/settlements-raw/data/interim/2021_tochno/data_allsettlements_anon_156_v20251217.parquet');R=pd.read_parquet(nf,columns=['oktmo','mun_lower','settlement','population']);own=R.iloc[163718];assert str(own.oktmo)=='97644482101'and 'Чиршкасинское' in own.mun_lower;AF=O/'correct_own_chirshkasinsky_rendered_article.json.gz';AJ=json.load(gzip.open(AF));assert AJ['parse']['title']=='Чиршкасы (Чиршкасинское сельское поселение)';txt=BeautifulSoup(AJ['parse']['text']['*'],'html.parser').get_text(' ',strip=True);assert 'Чиршкасинского' in txt and '471' in txt and '97' in txt;anchors=[]
for k in [13934,13935,13936,13937]:
 t=D[D.source_record_id.eq('2010:017_68e0e4537e_9._20Basq_Mari_Mord_Tatar_Udm_Chuv_2010.xls:!!!:'+str(k))].iloc[0];current=D[D.root.eq(t.root)&D.census_year.eq(2021)];assert len(current)==1;row=int(current.iloc[0].source_record_id.rsplit(':',1)[1])-1;rr=R.iloc[row];assert 'Чиршкасинское' in rr.mun_lower and str(rr.oktmo).startswith('97644482');anchors.append(dict(native2010=t.fillna('').to_dict(),accepted_current=current.iloc[0].fillna('').to_dict(),rawcurrent_code_and_parent=rr.fillna('').to_dict()))
BF=Path('/workspace/settlements-raw/data/raw/2002/046_228ab1ba5a_Chuvashia_1.xls');sh=xlrd.open_workbook(str(BF)).sheet_by_name('Sheet1');assert 'Чиршкасинский сельсовет' in str(sh.row_values(1770))and sh.row_values(1771)[1]=='471'and sh.row_values(1771)[3]==97;P=[];W=[]
for sid in ['2021:data_allsettlements_anon_156_v20251217.parquet:parquet:163719','2010:017_68e0e4537e_9._20Basq_Mari_Mord_Tatar_Udm_Chuv_2010.xls:!!!:13933']:
 t=D[D.source_record_id.eq(sid)].iloc[0];assert t.settlement_name=='Чиршкасы';rule='Native currentfullowncode97644482101 explicitly recodes97544000530; actualOSMownvillage node972150154 exactnewcode, ownQ99012665 and qualifiedЧиршкасинскоеarticle bind independently. Historical2010ownleaf is firstЧиршкасы before four independently accepted named2010peers allinthis samecurrentЧиршкасинскоеcode82 municipalblock. Old2002own471/bash97 and rawЧиршкасинскийparent independentlycorroborate correctarticle. Sixotherregionalhomonyms and SinyalQ18806434 excluded; native2010count514 versussecondary513 retained, no count substitution/full3 edge.'
  # Current correction is additional to the original81-target task and follows the separately frozen exactledger rejection batch21.
 if t.census_year==2010:
  f=Path('/workspace/settlements-raw')/t.source_file;ss=xlrd.open_workbook(str(f)).sheet_by_name('!!!');rn=13932;assert 'Чиршкасы' in str(ss.row_values(rn));native_raw=dict(file=str(f),sha256=sha(f),raw_row0=rn,raw_cells=ss.row_values(rn),four_next_scope_rows=[dict(row0=i,cells=ss.row_values(i))for i in range(rn+1,rn+5)])
 else:native_raw=dict(file=str(nf),sha256=sha(nf),parquet_row_1based=163719,ownfields=own.fillna('').to_dict())
 wi=len(W);W.append(dict(target_source_record_id=sid,native_observation=t.fillna('').to_dict(),native_raw=native_raw,own_fullcode_crosswalk_file=str(C),own_fullcode_crosswalk_sha256=sha(C),crosswalk_source_role='Secondary Classinform mirror claiming Rosstat recoding tables; official workbook not independently fetched',actual_ownOSM_feature=s,all_named_OSM_rivals=J['elements'],correct_own_article_file=str(AF),correct_own_article_sha256=sha(AF),correct_own_article=AJ['parse'],sourcecounty_block_accepted_peer_witnesses=anchors,old2002_native_file=str(BF),old2002_native_sha256=sha(BF),old2002_ownrow0=1771,old2002_owncells=sh.row_values(1771),old2002_parentcells=sh.row_values(1770),rule=rule,knownGeo_sharedcoordinate_interpretation='This actualownChirshkasinsky site is independently confirmed at55.92835,47.0223. Six other distincthomonym Geo rows copied itscoordinate and remain invalid for those otherplaces.',source2010_population_discrepancy_kept_unknown_boundary=True))
 P.append(dict(target_source_record_id=sid,latitude=s['lat'],longitude=s['lon'],coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_source_record_id='OSM:node:972150154',point_origin_file=str(F),point_origin_sha256=sha(F),point_origin_locator=f'elements[{si}];node972150154;lat,lon',point_origin_kind='direct_source_bound_owncoded_OSM_village_coordinate',coordinate_binding_rule=rule,point_use_inference='Ownphysicalvillage representative point; historicalcensusday measurement and population boundaries unknown.',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,external_provider_ID_binding_asserted=True,evidence_file=str(O/'point_binding_witnesses.json.gz'),evidence_locator=f'[{wi}]'))
pd.DataFrame(P).to_csv(O/'accepted_point_use_delta.csv',index=False);pd.DataFrame(columns=['from_source_record_id','to_source_record_id','relation','decision_status','admission_method','admission_rule','evidence_file','evidence_locator']).to_csv(O/'accepted_identity_edge_delta.csv',index=False);pd.DataFrame([dict(source_record_id=p['target_source_record_id'],disposition='accepted_correct_Chirshkasinsky_ownvillage_point',population_values_modified=False,identity_edges_added=False)for p in P]).to_csv(O/'record_dispositions.csv',index=False)
with gzip.open(O/'point_binding_witnesses.json.gz','wt')as f:json.dump(W,f,ensure_ascii=False)
m=dict(baseline_stage=71,accepted_own_point_uses=2,identity_edges_added=0,population_values_modified=False,prerequisite='batch21 accepted_point_rejection_delta.csv must be applied before current163719 replacement',validation=dict(actualown_fullcode_recoding_verified=True,allregional_actualOSM_ownname_rivals_retained=True,correctqualified_ownarticle_reopened=True,native2010_four_accepted_named_scope_peers_verified=True),frozen_files=[dict(name=f.name,sha256=sha(f),bytes=f.stat().st_size)for f in sorted(O.iterdir())if f.is_file()]);(O/'freeze_manifest.json').write_text(json.dumps(m,ensure_ascii=False,indent=2));print(2)
