from pathlib import Path
import pandas as pd,json,gzip,hashlib,xlrd,duckdb,bs4,math
O=Path(__file__).parent;B=O.parent;sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();d=pd.read_parquet('/dev/shm/over500-moscow-complete-batch4.parquet');p=pd.concat([pd.read_parquet('/dev/shm/over500-moscow-points.parquet')]+[pd.read_csv(dr/'accepted_point_use_delta.csv')for dr in[B,B/'batch2_lifecycle_homonyms',B/'batch3_remaining',B/'batch4_ownpoint_followup',B/'batch4_ownpoint_followup/timokhovsky']],ignore_index=True).drop_duplicates('target_source_record_id',keep='last').set_index('target_source_record_id');edges=[];pts=[];pgs={};tables={}
for dr in [B,B/'batch2_lifecycle_homonyms']:
 for f in dr.glob('own_wikipedia_batch*.json.gz'):
  for pg in json.load(gzip.open(f,'rt'))['query']['pages'].values():
   if 'missing'not in pg:pgs[pg['title']]=(pg,f)
for f in [B/'own_population_template_expansions.json.gz',B/'batch2_lifecycle_homonyms/own_population_template_expansions2.json.gz']:
 for z in json.load(gzip.open(f,'rt')):
  html=z.get('response',{}).get('expandtemplates',{}).get('wikitext','');soup=bs4.BeautifulSoup(html,'html.parser');yy=[x.get_text()[:4]for x in soup.select('th')];vv=[x.get_text().strip('↗↘→ ').replace('\xa0','')for x in soup.select('td')];tables[z['title']]=(dict(zip(yy,vv)),f,z)
raw2=Path('/workspace/settlements-raw/data/raw/2002/010_3e630cc803_02c_Moskovskaya-oblast.xls');raw10=Path('/workspace/settlements-raw/data/raw/2010/010_711691e352_2._20Kostrom_Kur_Lip_Moscow_MoscObl_Orlov_2010.xls');b2=xlrd.open_workbook(str(raw2)).sheet_by_index(0);b10=xlrd.open_workbook(str(raw10)).sheet_by_name('Data Sheet');clfile=Path('/workspace/settlements-raw/data/raw/historical_classifiers/okato_142_2009/dump-142_2009.sql');c=duckdb.connect();cl=c.execute("select * from read_parquet('/workspace/settlements-work/sources/raw_okato_2009_verification_v1/raw_classifier.parquet')where historical_okato like '46%'").fetchdf();lines=clfile.read_text(errors='replace').splitlines();proof=[];rivals=[];raws=[];parent={x:x for x in d.after_root.unique()}
def find(x):
 while parent[x]!=x:x=parent[x]
 return x
def sid(y,n):
 k='010_3e630cc803'if y==2002 else'010_711691e352'if y==2010 else'data_allsettlements';z=d[d.census_year.eq(y)&d.source_record_id.str.contains(k)&d.source_record_id.str.endswith(':'+str(n))];assert len(z)==1;(r,)=z.to_dict('records');return r
configs=[(6455,13828,70761,'Пешково (село, городской округ Чехов)','Пешково (деревня, городской округ Чехов)','Пешково (сельское поселение Стремиловское)','Пешково (сельское поселение Баранцевское)','Стремиловский','46256828058')]
for n2,n10,n21,title,other_title,tn,otn,sub,code in configs:
 old=sid(2002,n2);ten=sid(2010,n10);cur=sid(2021,n21)if n21 else None;pg,f=pgs[title];other,of=pgs[other_title];txt=pg['revisions'][0]['slots']['main']['*'];othertext=other['revisions'][0]['slots']['main']['*'];tb,tf,record=tables[tn];otb,otf,orecord=tables[otn];assert str(int(old['population']))==tb['2002'],(title,old['population'],tb)
 cls=cl[cl.historical_okato.eq(code)];assert len(cls)==1 and cls.iloc[0]['name'].lower().replace('ё','е')==old['name_norm'];parentcl=cl[cl.historical_okato.eq(code[:8])];assert len(parentcl)==1 and parentcl.iloc[0]['name']==sub;num=int(cls.iloc[0].source_line_1based);assert code in lines[num-1]
 # Positive source hierarchy proof: exact own parent heading in the target's literal2002 block.
 head=next((i+1,str(b2.cell_value(i,1)).strip())for i in range(n2-2,-1,-1)if'сельский округ'in str(b2.cell_value(i,1)));assert 'Чепелевский'in head[1]or'Чепелёвский'in head[1],(title,head,sub)
 countyfile=O/'owncounty_and_both_peshkovo_articles.json.gz';countyproof=json.load(gzip.open(countyfile,'rt'))['query']['pages'];chep=next(q for q in countyproof.values()if q.get('title')=='Чепелёвский сельский округ');strem=next(q for q in countyproof.values()if q.get('title')=='Стремиловский сельский округ');cheptxt=chep['revisions'][0]['slots']['main']['*'];stremtxt=strem['revisions'][0]['slots']['main']['*'];assert'2 июля 2004 года'in cheptxt and'Стремиловский'in cheptxt and'2 июля 2004 года'in stremtxt and'Чепелёвский'in stremtxt;assert'6 августа 2018 года'in txt and'322-ПГ'in txt
 county=old['derived_oldcounty'];cand=d[d.census_year.eq(2010)&d.name_norm.eq(ten['name_norm'])&d.type_norm.eq(ten['type_norm'])&d.derived_oldcounty.eq(county)];assert len(cand)==2 and ten['source_record_id']in set(cand.source_record_id);opp=cand[cand.source_record_id.ne(ten['source_record_id'])].iloc[0]
 # Case-specific comparative witnesses; no universal numeric tolerance/equality identity rule.
 assert float(tb['2010'])>float(otb['2010']) and float(ten['population'])>float(opp.population);assert old['derived_oldcounty']==ten['derived_oldcounty'];assert old['name_norm']==ten['name_norm'];rivals.extend(cand.assign(case=title,chosen_UID=ten['source_record_id'],counterpart_own_article=other_title).to_dict('records'))
 selected=[old,ten]+([cur]if cur else[]);roots={find(z['after_root'])for z in selected};full=d[d.after_root.map(find).isin(roots)];assert not full.census_year.duplicated().any();co=pg['coordinates'][0];wp=(co['lat'],co['lon']);loc=f'pageid={pg["pageid"]};revision={pg["revisions"][0]["revid"]}';case='moscow_two_article_homonym_'+str(pg['pageid'])
 for z in full.itertuples():
  if z.source_record_id in p.index:assert 111*math.hypot(p.loc[z.source_record_id].latitude-wp[0],(p.loc[z.source_record_id].longitude-wp[1])*math.cos(math.radians(wp[0])))<2,(case,z.source_record_id)
 anchor=selected[-1]
 for z in selected[:-1]:
  if find(z['after_root'])!=find(anchor['after_root']):edges.append(dict(from_source_record_id=z['source_record_id'],to_source_record_id=anchor['source_record_id'],relation='same_place',decision_status='checked_rule_accepted',case=case,admission_rule='Exact ownnative name/type/sourcecounty, original2002Chepelevskysubcounty and2009Stremilovskyowncode joined only by independentlyBOTHcountyarticles literal2004-07-02wholeterritorytransfer; explicit2018-08-06№322-ПГ village→selo explainscurrentnativekind; BOTH independently qualified own articles positively distinguish the two countyhomonyms; own modern point/code context; dated secondary counts used only as approximate comparative disambiguation with all actual native values and quality preserved',source_binding_proof=str(O/'two_article_homonym_binding_witnesses.csv')+';'+str(O/'all_native2010_homonym_rivals.csv.gz'),population_boundary_comparability_asserted=False,municipal_event_date='UNKNOWN'));parent[find(z['after_root'])]=find(anchor['after_root'])
 for z in full.itertuples():
  if z.source_record_id not in p.index:pts.append(dict(target_source_record_id=z.source_record_id,latitude=wp[0],longitude=wp[1],coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_source_record_id='Wikipedia:page'+str(pg['pageid']),source_sha256=sha(f),source_locator=loc+':coordinates[0]',point_origin_file=str(f),point_origin_sha256=sha(f),point_origin_locator=loc+':coordinates[0]',point_origin_kind='own_Wikipedia_qualified_native_locality_representative_point',case=case,coordinate_binding_rule='Literal source2002ownsubcounty +unique ownhistoricalcode, both owncountyhomonym articles and fullnative rivals; dated2004wholeChepelevsky→Stremilovskytransfer resolvesoriginalcountyvariation; dated2018ownvillage→selo explainscurrentkind; no GeoKLADR shared/default point reused',point_use_inference='own_modern_representative_point_on_source_bound_native_identity',population_boundary_comparability_asserted=False,historical_census_coordinate_asserted=False,secondary_population_not_substituted_for_native=True))
 proof.append(dict(case=case,own_title=title,own_article_file=str(f),own_article_sha256=sha(f),own_article_locator=loc,own_article_literal=txt,counterpart_title=other_title,counterpart_article_file=str(of),counterpart_article_sha256=sha(of),counterpart_article_literal=othertext,population_template_file=str(tf),population_template_sha256=sha(tf),own_template=tn,counterpart_template=otn,counterpart_template_file=str(otf),counterpart_template_sha256=sha(otf),own_secondary_population2002=tb['2002'],own_secondary_population2010=tb['2010'],own_actual_native_population2010=ten['population'],native_quality2010=ten['population_value_quality'],counterpart_secondary_population2010=otb['2010'],counterpart_actual_native_population2010=opp.population,secondary_count_exact_native_equality_claimed=False,own_2002_UID=old['source_record_id'],own_2010_UID=ten['source_record_id'],own_2021_UID=cur['source_record_id']if cur else'',native2002subcounty_raw=head[1],native2002subcounty_heading_row=head[0],classifier_file=str(clfile),classifier_sha256=sha(clfile),classifier_locator=f'line{num};OKATO={code}',classifier_literal=lines[num-1],modern_point_latitude=wp[0],modern_point_longitude=wp[1],county_transfer_source_file=str(countyfile),county_transfer_source_sha256=sha(countyfile),original_Chepelevsky_source_literal=cheptxt,new_Stremilovsky_source_literal=stremtxt,original_native_subcounty_not_rewritten=True,own_village_to_selo_event_date='2018-08-06',own_village_to_selo_act='322-ПГ',article_inaccurate_before2005_Stremilovsky_generalization_retained=True,unlocated_GeoKLADR_or_shared_point_reused=False,population_values_or_quality_modified=False))
 for z in [old,ten]:
  y=z['census_year'];n=int(z['source_record_id'].rsplit(':',1)[-1]);sh=b2 if y==2002 else b10;sf=raw2 if y==2002 else raw10;vv=sh.row_values(n-1);assert any(str(v).replace('.0','')==str(int(z['population']))for v in vv);raws.append(dict(source_record_id=z['source_record_id'],year=y,native_population=z['population'],native_quality=z['population_value_quality'],source_path=str(sf),source_sha256=sha(sf),source_locator=f'{sh.name}:row{n}',raw_cells_json=json.dumps(vv[:8],ensure_ascii=False),source_neighborhood_json=json.dumps([(i+1,sh.row_values(i)[:8])for i in range(n-3,n+2)],ensure_ascii=False),native_values_preserved=True))
d.after_root=d.after_root.map(find);d.to_parquet('/dev/shm/over500-moscow-complete-batch5.parquet',index=False);pd.DataFrame(edges).drop_duplicates(['from_source_record_id','to_source_record_id']).to_csv(O/'accepted_identity_edge_delta.csv',index=False);pd.DataFrame(pts).drop_duplicates('target_source_record_id',keep='last').to_csv(O/'accepted_point_use_delta.csv',index=False);pd.DataFrame(proof).to_csv(O/'two_article_homonym_binding_witnesses.csv',index=False);pd.DataFrame(rivals).to_csv(O/'all_native2010_homonym_rivals.csv.gz',index=False);pd.DataFrame(raws).to_csv(O/'homonym_native_raw_row_witnesses.csv',index=False);print('cases',len(proof),'edges',len(edges),'points',len(pts))
