from pathlib import Path
import pandas as pd,json,gzip,hashlib,re,ast,xlrd,sys
O=Path(__file__).parent;R=Path('/workspace/russian-settlements-research');N=R/'research_rebuild/evidence/over500_north_20261009';A=R/'research_rebuild/evidence/over500_north_alternative_point_sources_20261009';sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();norm=lambda x:re.sub('[^а-яa-z0-9]','',str(x).lower().replace('ё','е'));w=pd.read_csv(N/'direct_native_witnesses.csv.gz').fillna('').set_index('source_record_id');c=pd.concat([pd.read_csv(A/f) for f in ['nominatim_own_feature_candidates.csv.gz','nominatim_fallback_candidates.csv.gz']]).fillna('').drop_duplicates(['source_record_id','feature_id']);diag=pd.read_csv('/dev/shm/over500-20261009/north_expanded_anchor_diagnostic.csv.gz').fillna('').set_index('source_record_id');obs=pd.read_parquet('/dev/shm/settlements-stage71-20261009/applied_state_observations.parquet').fillna('');meta=pd.read_parquet('/workspace/settlements-delivery/continuation-consolidated-20261003/selected_observations.parquet').fillna('').set_index('source_record_id');native2021=Path('/workspace/settlements-raw/data/interim/2021_tochno/data_allsettlements_anon_156_v20251217.parquet');raw2021=pd.read_parquet(native2021,columns=['object_name','population','oktmo','mun_upper','mun_lower']);rows=[];proof=[];pins={str(q):sha(q) for q in [N/'direct_native_witnesses.csv.gz',A/'nominatim_own_feature_candidates.csv.gz',A/'nominatim_fallback_candidates.csv.gz','/dev/shm/settlements-stage71-20261009/applied_state_observations.parquet',native2021]};books={}
def reopen(sid):
 x=w.loc[sid].to_dict();assert x['literal_label_population_passed'];q=Path(x['source_file']);assert sha(q)==x['source_sha256'];pins[str(q)]=sha(q)
 if str(q) not in books:books[str(q)]=xlrd.open_workbook(q)
 bk=books[str(q)];s=bk.sheet_by_name(str(x['source_sheet'])) if str(x['source_sheet']) in bk.sheet_names() else bk.sheet_by_index(int(x['source_sheet']));r=int(x['source_row']);v=s.row_values(r-1);assert any(norm(x['native_name']) in norm(a) for a in v if isinstance(a,str));assert any(str(a).replace('.','',1).isdigit() and float(a)==float(x['native_population']) for a in v);x['reopened_raw_row']=v;return x,s,r
specs=[('2002:022_862ad8a69d_02c_Vologodskaya.xls:2C:3147','node/2646590505','historical_own_named_neighborhood'),('2002:022_862ad8a69d_02c_Vologodskaya.xls:2C:3160','node/3104652116','historical_own_named_neighborhood'),('2002:016_3aa889d669_02c_Tulskaja.xls:Sheet1:3105','relation/2435209','literal_own_subcounty_anchors'),('2010:011_040325482b_3._20Ryaz_Smol_Tambov_Tula_Jaroslavl_20L1_20ethn_2010.xls:Data Sheet:12135','relation/2435209','literal_own_subcounty_anchors'),('2002:024_2d3f550c6f_02c_Leningradskaja_obl_new.xls:!!!!!!:160','way/1344793661','literal_native_parish')]
for sid,fid,mode in specs:
 x,s,r=reopen(sid);v=c[(c.source_record_id==sid)&(c.feature_id==fid)].iloc[0].to_dict();assert norm(v['own_name'])==norm(x['native_name']);assert v['feature_category']=='place';address=json.loads(v['address_json']);e=json.loads(v['extratags_json'] or '{}');extra={}
 if mode=='historical_own_named_neighborhood':
  assert v['feature_type']=='neighbourhood' and 'Вытегорский' in address.get('county','');assert x['native_type']=='деревня';own=obs[(obs.census_year==2002)&(obs.region_norm=='вологодская')&(obs.name_norm.map(norm)==norm(x['native_name']))&(obs.district_raw.str.contains('Вытегорский'))];assert len(own)==1
  reason='Original counted whole village ownname/type and Vytегорский native county uniquely match distinct own named OSM neighbourhood feature in same county. Point is representative of historical own site surviving as named part; no current whole-NP status, incorporation date or ordinary sameplace relation asserted.'
 elif mode=='literal_own_subcounty_anchors':
  z=diag.loc[sid].to_dict();lo=ast.literal_eval(z['lower_anchor']);hi=ast.literal_eval(z['upper_anchor']);assert lo['source_row']<r<hi['source_row'] and r-lo['source_row']<=20 and hi['source_row']-r<=20 and lo['name']!=hi['name'];assert norm(z['native_mun_lower'])==norm(address.get('municipality',''));aa=[]
  for a in [lo,hi]:
   cur=a['current_source_record_id'];raw=raw2021.iloc[int(meta.loc[cur,'source_row'])-1];assert norm(raw.object_name)==norm(meta.loc[cur,'source_name_raw']);assert str(raw.oktmo)==str(obs.set_index('source_record_id').loc[cur,'oktmo']);assert norm(raw.mun_lower)==norm(z['native_mun_lower']);aa.append({'anchor':a,'current_raw':raw.to_dict(),'historical_raw_cells':s.row_values(a['source_row']-1)})
  extra['independent_actual_own_native_anchors']=aa;reason='Two distinct full3 ownnamed anchors strictly flank native row within20 and actual primarycurrent publisher parish agrees with direct own OSM place address Turgenевское; North-parish OSM namesake excluded. Original name/type/count retained; modern generic village role is representative only.'
 else:
  parent=s.row_values(r-2);assert any('Климовская волость' in str(a) for a in parent);assert 'Климовское' in e.get('wikipedia','');extra['reopened_literal_parent']={'row1based':r-1,'rawcells':parent};reason='Own primary2002 village is directly under printed Климовская волость; direct own OSM place includes Климовское parish in own Wikipedia title. Samecounty Samoylov parish namesake excluded; modern Efimov municipality change does not imply old boundary equivalence.'
 q=Path(v['source_file']);pins[str(q)]=sha(q);bundle=json.load(gzip.open(q,'rt'));req=next(b for b in bundle if b['source_record_id']==sid and b['response_sha256']==v['source_response_sha256']);feature=next(a for a in req['response'] if f"{a['osm_type']}/{a['osm_id']}"==fid);assert float(feature['lat'])==float(v['latitude']) and float(feature['lon'])==float(v['longitude']);rows.append(dict(target_source_record_id=sid,latitude=float(v['latitude']),longitude=float(v['longitude']),coordinate_source_record_id=sid,coordinate_admission_status='reviewed_extension_rule_accepted',decision_status='checked_rule_accepted',admission_allowed=True,own_locality_point=True,recipient_point_assigned_to_child=False,source_sha256=x['source_sha256'],source_locator=f"{x['source_sheet']}:{r}",point_origin_file=str(q),point_origin_sha256=sha(q),point_origin_locator=v['source_locator'],point_origin_kind='direct_captured_OSM_own_named_locality_representative',external_own_feature_id=fid,admission_rule=reason,point_temporal_interpretation='Modern representative of own named locality site reused for historical NP by explicit continuity inference; no censusday measurement or boundary equivalence.',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,native_population_quality_preserved=True));proof.append({'source_record_id':sid,'native_source':x,'own_feature':feature,'source_binding':extra,'rival_disposition':reason})
# Explicit ownarticle pre2008 parish history binds two oldSadovoe rows to their already admitted own article points.
wiki=R/'research_rebuild/evidence/over500_north_wiki_sources_20261009/additional_kaliningrad_v5_article_candidates.csv.gz';vc=pd.read_csv(wiki);donors=pd.read_csv(N/'dated_subcounty_accepted_point_use_delta.csv').fillna('').set_index('target_source_record_id');pins[str(wiki)]=sha(wiki);pins[str(N/'dated_subcounty_accepted_point_use_delta.csv')]=sha(N/'dated_subcounty_accepted_point_use_delta.csv')
for sid,donor,title,stem in [('2002:023_38d853be37_02c_Kaliningrad.xls:Sheet1:716','KAL2010:TOM1:S4:R0704','Садовое (Илюшинское сельское поселение)','Заветинского сельского округа'),('2002:023_38d853be37_02c_Kaliningrad.xls:Sheet1:900','KAL2010:TOM1:S4:R0815','Садовое (Красноярское сельское поселение)','одноименного сельсовета Озёрского района')]:
 x,s,r=reopen(sid);v=vc[vc.article_title==title].iloc[0];q=Path(v.capture);assert sha(q)==v.capture_sha256;p=json.load(gzip.open(q,'rt'))['query']['pages'];p=list(p.values()) if isinstance(p,dict) else p;pg=next(a for a in p if a.get('title')==title);tx=pg['revisions'][0]['slots']['main']['*'];assert stem in tx
 if ':716' in sid:assert 'Заветинский' in x['primary_native_parent_header'] and 'До 2008' in tx
 else:assert 'Садовский' in x['primary_native_parent_header']
 pins[str(q)]=sha(q);d=donors.loc[donor].to_dict();row={k:d[k] for k in ['latitude','longitude','point_origin_file','point_origin_sha256','point_origin_locator','point_origin_kind']};row.update(target_source_record_id=sid,coordinate_source_record_id=donor,coordinate_admission_status='reviewed_extension_rule_accepted',decision_status='checked_rule_accepted',admission_allowed=True,own_locality_point=True,recipient_point_assigned_to_child=False,source_sha256=x['source_sha256'],source_locator=f"{x['source_sheet']}:{r}",admission_rule='Native2002 counted own poselok Sadovoe and explicit original parish; own article explicit pre2008 parish/council history directly matches oldnative hierarchy, disambiguating samecounty otherSadovoe. Reuse separately admitted ownarticle point; no ordinaryedge or boundary/day claim.',point_temporal_interpretation='Modern own representative reused historically by explicit continuity inference.',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,native_population_quality_preserved=True);rows.append(row);proof.append({'source_record_id':sid,'native_source':x,'own_article_pageid':pg['pageid'],'revid':pg['revisions'][0]['revid'],'own_article_text':tx,'accepted_own_donor':d})
assert len(rows)==7;pd.DataFrame(rows).to_csv(O/'accepted_point_use_delta_02.csv',index=False)
with gzip.GzipFile(filename=str(O/'point_witnesses_02.json.gz'),mode='wb',mtime=0) as z:z.write(json.dumps(proof,ensure_ascii=False,default=str).encode())
(O/'manifest_02.json').write_text(json.dumps({'status':'frozen_accepted_ownpoints_only','points':7,'identity_edges':0,'sourcecounts_or_quality_modified':False,'input_pins':pins,'output_pins':{str(q):sha(q) for q in [O/'accepted_point_use_delta_02.csv',O/'point_witnesses_02.json.gz']}},ensure_ascii=False,indent=2)+'\n');print('accepted7')
