from pathlib import Path
import pandas as pd,json,gzip,hashlib,ast,re,xlrd,sys,shutil
from bs4 import BeautifulSoup
R=Path('/workspace/russian-settlements-research');O=Path(__file__).parent;N=R/'research_rebuild/evidence/over500_north_20261009';A=R/'research_rebuild/evidence/over500_north_alternative_point_sources_20261009';S=Path('/dev/shm/settlements-stage71-20261009');sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from current_chain_state_20261007 import normalize,distance_km
from apply_unique_county_name_bridge_20261007 import county_key
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();f=pd.read_parquet(S/'applied_state_observations.parquet').fillna('');b=f.set_index('source_record_id');sel=Path('/workspace/settlements-delivery/continuation-consolidated-20261003/selected_observations.parquet');m=pd.read_parquet(sel).fillna('').set_index('source_record_id');ps=S/'applied_point_snapshot.parquet';p=pd.read_parquet(ps,columns=['target_source_record_id','latitude','longitude','coordinate_source_record_id','point_origin_file','point_origin_sha256','point_origin_locator','point_origin_kind','coordinate_admission_status']).fillna('').drop_duplicates('target_source_record_id').set_index('target_source_record_id').to_dict('index');pins={str(q):sha(q) for q in [S/'applied_state_observations.parquet',sel,ps]};books={};checks={};rawpar={};fn=ast.unparse(next(x for x in ast.parse((N/'build_packet.py').read_text()).body if isinstance(x,ast.FunctionDef) and x.name=='check')).replace("actual = re.sub('ского$', 'ский', actual)","actual = re.sub('ского$', 'ский', actual); actual = re.sub('цкого$', 'цкий', actual)");exec(fn);c=pd.concat([pd.read_csv(A/f) for f in ['nominatim_own_feature_candidates.csv.gz','nominatim_fallback_candidates.csv.gz']]).fillna('').drop_duplicates(['source_record_id','feature_id']);rows=[];edges=[];proof=[]
def addpoint(sid,cp,rule,old,extra):
 row={k:cp[k] for k in ['latitude','longitude','point_origin_file','point_origin_sha256','point_origin_locator','point_origin_kind']};row.update(target_source_record_id=sid,coordinate_source_record_id=cp.get('coordinate_source_record_id',sid),coordinate_admission_status='reviewed_extension_rule_accepted',decision_status='checked_rule_accepted',admission_allowed=True,own_locality_point=True,recipient_point_assigned_to_child=False,source_sha256=old['source_sha256'],source_locator=old.get('source_locator') or f"{old['source_sheet']}:{old['source_row']}",admission_rule=rule,point_temporal_interpretation='Source-bound ownplace representative reused for historical NP by explicit continuity inference; exact censusday geometry and population boundary equivalence unknown.',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,native_population_quality_preserved=True);rows.append(row);proof.append({'source_record_id':sid,'native_source':old,'ownpoint_donor':cp,'source_binding':extra})
def edge(sid,oid,rule):
 groups=f[f.root.isin([b.loc[sid,'root'],b.loc[oid,'root']])];assert not groups.census_year.duplicated().any();edges.append(dict(from_source_record_id=sid,to_source_record_id=oid,relation='same_place',decision_status='checked_rule_accepted',admission_rule=rule,source_context_witness_file=str(O/'point_witnesses_05.json.gz'),source_counts_changed=False,boundary_comparability_asserted=False))
def rawparent(sid,stem):
 x=check(sid);assert x['literal_label_population_passed'];bk=books[x['source_file']];sh=bk.sheet_by_name(str(x['source_sheet'])) if str(x['source_sheet']) in bk.sheet_names() else bk.sheet_by_index(int(x['source_sheet']));r=int(x['source_row']);
 for rn in range(r-1,max(0,r-500),-1):
  v=sh.row_values(rn-1)
  if any('сельсовет' in normalize(z) or 'сельский округ' in normalize(z) or 'волость' in normalize(z) for z in v if isinstance(z,str)):
   assert any(stem in str(z) for z in v);return {'row1based':rn,'rawcells':v}
 raise AssertionError('No native parish')
for sid,fid,stem in [('2002:020_e4f979c6c7_02c_Arxang-new.xls:Sheet1:3358','way/661776790','Березницкий'),('2002:020_e4f979c6c7_02c_Arxang-new.xls:Sheet1:3920','way/446842145','Селецкий')]:
 x=check(sid);parent=rawparent(sid,stem);v=c[(c.source_record_id==sid)&(c.feature_id==fid)].iloc[0].to_dict();et=json.loads(v['extratags_json']);assert v['feature_category']=='place' and v['feature_type'] in ['hamlet','village'];assert normalize(v['own_name'])==normalize(x['native_name']);expected='Березницкое' if stem.startswith('Берез') else 'Селецкое';assert expected in et['wikipedia'];q=Path(v['source_file']);pins[str(q)]=sha(q);bundle=json.load(gzip.open(q,'rt'));req=next(z for z in bundle if z['source_record_id']==sid and z['response_sha256']==v['source_response_sha256']);feat=next(a for a in req['response'] if f"{a['osm_type']}/{a['osm_id']}"==fid);assert float(feat['lat'])==float(v['latitude']) and float(feat['lon'])==float(v['longitude']);cp={'latitude':float(v['latitude']),'longitude':float(v['longitude']),'point_origin_file':str(q),'point_origin_sha256':sha(q),'point_origin_locator':v['source_locator'],'point_origin_kind':'direct_captured_OSM_own_settlement_place_feature_representative'};rule='Original2002 own counted leaf/name/type/count and literal printed '+stem+' parish independently reopened; direct own OSM place feature same propername/county and explicit parish-qualified ownarticle title. Other samecounty parish homonyms screened separately; provider population ignored. OwnNP historicaltype preserved despite modern typevariant, no ordinaryedge/legalchange claim.';addpoint(sid,cp,rule,x,{'literal_native_parent':parent,'own_OSM_feature':feat,'provider_all_same_query_namesake_features':c[c.source_record_id==sid].to_dict('records')})
# Ownquoted farm is same full named object, not a settlement recipient.
sid='2010:013_f60b2d2bcf_5._20Belg_Bryan_Vlad_Voron_Ivanov_Kalug_20L1_ethn_2010.xls:Data Sheet:12068';oldid='2002:006_1916564aaa_02c_Kaluzhskaja.xls:Sheet1:592';dsid='2021:data_allsettlements_anon_156_v20251217.parquet:parquet:27646';x=check(sid);ox=check(oldid);cw=check(dsid);assert all(z['literal_label_population_passed'] for z in [x,ox,cw]);assert 'Дзержинск' in ox['actual_printed_county'];assert b.loc[dsid,'settlement_name']=='Совхоз "Чкаловский"' and b.loc[dsid,'type_norm']=='село';seq=json.load(open('/dev/shm/over500-20261009/north_native_sequence_diag.json'));ctx=next(a for a in seq if a['source_record_id']==sid);assert len(ctx['hits'])==1 and ctx['hits'][0]['old_source_record_id']==oldid;ns=[check(z[0][2]) for z in ctx['hits'][0]['pairs']]+[check(z[1][2]) for z in ctx['hits'][0]['pairs']];assert all(z['literal_label_population_passed'] for z in ns);rule='Full ownfarm name совхоза Чкаловский (genitive) directly matches independently admitted owncoded primary2021 named NP Совхоз "Чкаловский" (literalquote/base-case only); exact same own2010/current selo role, unique samecounty full farm propername. Primary2002 ownleaf and explicit Dzержинский county plus4 distinct rawreopened signed adjacent native neighbours match own2010 row, separately from othercounty Chkalovo. Nativecounts/oldtype retained; no recipientcentre or ordinarytypechange edge.';addpoint(sid,p[dsid],rule,x,{'primary2002_ownleaf':ox,'all4_native_sequence_matches':ctx,'all_reopened_neighbours':ns,'own_current_native_leaf':cw})
# Literal spelling AleShenka/AleShinka is independently source-bound by3 adjacent ownnames.
sid='2010:013_f60b2d2bcf_5._20Belg_Bryan_Vlad_Voron_Ivanov_Kalug_20L1_ethn_2010.xls:Data Sheet:3047';oldid='2002:002_d4cda9574f_02c_Bryanskaja.xls:Sheet1:1724';x=check(sid);ox=check(oldid);assert all(z['literal_label_population_passed'] for z in [x,ox]);ctx=next(a for a in json.load(open('/dev/shm/over500-20261009/north_alias_sequence_diag.json')) if a['source_record_id']==sid);assert len(ctx['hits'])==1 and ctx['hits'][0]['old_source_record_id']==oldid and len(ctx['hits'][0]['pairs'])>=2;ns=[check(z[0][2]) for z in ctx['hits'][0]['pairs']]+[check(z[1][2]) for z in ctx['hits'][0]['pairs']];assert all(z['literal_label_population_passed'] for z in ns);rule='Explicit literal ownname Алешенка/Алешинка one vowel spelling variant; same native selo role/region, unique sourcepair under independently reopened original2002 Navлинский county. Three distinct rawreopened ownneighbours in identical signed physical source sequence Шешуево/ГлубокиеЛужи/Еловики bind this place, exclude Trubchevsk namesake. Reuse independently admitted primary2002 ownpoint, no legalrename/day-boundary assertion.';addpoint(sid,p[oldid],rule,x,{'primary2002_ownleaf':ox,'own_source_sequence':ctx,'all_native_neighbours':ns});edge(sid,oldid,rule)
# Fresh ownarticle explicitly retains singular native name and nativeparish/fullcode.
cap=O/'own_named_article_capture_05.json.gz';shutil.copyfile('/dev/shm/over500-20261009/north_own_admin_articles.json.gz',cap);pins[str(cap)]=sha(cap);doc=json.load(gzip.open(cap,'rt'));pg=next(z for z in doc['response']['query']['pages'].values() if z['title']=='Старомочалеи');tx=pg['revisions'][0]['slots']['main']['*'];assert re.search(r'русское название\s*= Старомочалей',tx) and 'Новомочалеевский сельсовет' in tx and '22245840001' in tx;cc=pg['coordinates'][0];cp={'latitude':cc['lat'],'longitude':cc['lon'],'point_origin_file':str(cap),'point_origin_sha256':sha(cap),'point_origin_locator':f"ownpageid={pg['pageid']};revid={pg['revisions'][0]['revid']};primary ownarticle coordinate",'point_origin_kind':'direct_own_named_Wikipedia_article_primary_coordinate'};oldid='2002:048_4f024587eb_02c_Nizhegorod_obl_new.xls:11:3790';newid='2010:014_5ca759eea0_5._20Nizheg_Kirov_202010.xls:Data Sheet:2948';parent=rawparent(oldid,'Новомочалеевский');ctx=next(a for a in seq if a['source_record_id']==newid);assert len(ctx['hits'])==1 and ctx['hits'][0]['old_source_record_id']==oldid;ns=[check(z[0][2]) for z in ctx['hits'][0]['pairs']]+[check(z[1][2]) for z in ctx['hits'][0]['pairs']];assert all(z['literal_label_population_passed'] for z in ns);rule='Ownarticle titleplural Старомочалеи explicitly nativeinfoboxname Старомочалей, selo role, Pilнинский county/Новомочалеевский nativecouncil and owncode22245840001; direct own primarycoordinate. Native2002 counted ownleaf under printed matching council;2010 exacttypedownname uniquely sourcebound through two distinct signed adjacent rawreopened ownnames Новомочалей/Куликовка. No providerpopulation use, no sourcecode backfill/day/boundary claim.'
for sid in [oldid,newid]:
 x=check(sid);assert x['literal_label_population_passed'];addpoint(sid,cp,rule,x,{'own_pageid':pg['pageid'],'revid':pg['revisions'][0]['revid'],'own_article_text':tx,'native2002_parent':parent,'native_source_pair':ctx,'all_native_neighbours':ns})
edge(newid,oldid,rule)
# Primary2010 directhtml actualparish distinguishes Lastol namesake; counts unchanged.
sid='ARK2010:archive20131022:html_table1_tr3162';oldid='2002:020_e4f979c6c7_02c_Arxang-new.xls:Sheet1:3176';rec=R/'research_rebuild/evidence/over500_north_supplemental_native_20261009/recovered_direct_native_witnesses.csv';x=pd.read_csv(rec).fillna('').set_index('source_record_id').loc[sid].to_dict();q=Path(x['source_file']);assert sha(q)==x['source_sha256'];pins[str(q)]=sha(q);pins[str(rec)]=sha(rec);trs=BeautifulSoup(q.read_bytes(),'html.parser').find_all('tr');cells=lambda i:[z.get_text(' ',strip=True) for z in trs[i].find_all(['td','th'])];assert cells(3162)==['деревня Лахта','593'];assert 'Катунинское' in cells(3159)[0] and 'Ластольское' in cells(3178)[0];assert cells(3187)==['деревня Лахта','0'];ox=check(oldid);assert ox['literal_label_population_passed'];parent=rawparent(oldid,'Катунинский');rival=check('2002:020_e4f979c6c7_02c_Arxang-new.xls:Sheet1:3201');rparent=rawparent(rival['source_record_id'],'Ластольский');rule='Direct2010 originalhtml counted деревняЛахта593 under printedKatунино/Primорский hierarchy and primary2002 ownдеревняЛахта675 under same namednativeKatунинский council; fullsamecounty otherLahta0 underLastol parish rawreopened separately in BOTHsources. Exactliteralname/ownvillage role and explicitnativecounty+parish distinguish rivals; reuse independently admitted own2002 representative. No sourcepopulation/quality/day/boundary edit.';addpoint(sid,p[oldid],rule,x,{'raw_primary2010_target_and_parish':[cells(i) for i in [3097,3159,3162,3163]],'raw_primary2010_rival_and_parish':[cells(i) for i in [3178,3187]],'native2002_target':ox,'native2002_target_parent':parent,'native2002_rival':rival,'native2002_rival_parent':rparent});edge(sid,oldid,rule)
assert len(rows)==7 and len(edges)==3;pd.DataFrame(rows).to_csv(O/'accepted_point_use_delta_05.csv',index=False);pd.DataFrame(edges).to_csv(O/'accepted_identity_edges_05.csv',index=False)
with gzip.GzipFile(filename=str(O/'point_witnesses_05.json.gz'),mode='wb',mtime=0) as z:z.write(json.dumps(proof,ensure_ascii=False,default=str).encode())
(O/'manifest_05.json').write_text(json.dumps({'status':'frozen_accepted_ownpoints_and_sourcebound_typed_edges','points':7,'identity_edges':3,'sourcecounts_or_quality_modified':False,'input_pins':pins,'output_pins':{str(q):sha(q) for q in [O/'accepted_point_use_delta_05.csv',O/'accepted_identity_edges_05.csv',O/'point_witnesses_05.json.gz',cap]}},ensure_ascii=False,indent=2)+'\n');print('accepted7points,3edges')
