from pathlib import Path
import pandas as pd,json,gzip,hashlib,ast,re,xlrd,sys,shutil
from bs4 import BeautifulSoup
R=Path('/workspace/russian-settlements-research');O=Path(__file__).parent;N=R/'research_rebuild/evidence/over500_north_20261009';A=R/'research_rebuild/evidence/over500_north_alternative_point_sources_20261009';S=Path('/dev/shm/settlements-stage71-20261009');sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from current_chain_state_20261007 import normalize,distance_km
from apply_unique_county_name_bridge_20261007 import county_key
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();f=pd.read_parquet(S/'applied_state_observations.parquet').fillna('');b=f.set_index('source_record_id');sel=Path('/workspace/settlements-delivery/continuation-consolidated-20261003/selected_observations.parquet');m=pd.read_parquet(sel).fillna('').set_index('source_record_id');ps=S/'applied_point_snapshot.parquet';p=pd.read_parquet(ps,columns=['target_source_record_id','latitude','longitude','coordinate_source_record_id','point_origin_file','point_origin_sha256','point_origin_locator','point_origin_kind','coordinate_admission_status']).fillna('').drop_duplicates('target_source_record_id').set_index('target_source_record_id').to_dict('index');pins={str(q):sha(q) for q in [S/'applied_state_observations.parquet',sel,ps]};books={};checks={};rawpar={};fn=ast.unparse(next(x for x in ast.parse((N/'build_packet.py').read_text()).body if isinstance(x,ast.FunctionDef) and x.name=='check')).replace("actual = re.sub('ского$', 'ский', actual)","actual = re.sub('ского$', 'ский', actual); actual = re.sub('цкого$', 'цкий', actual)");exec(fn);c=pd.concat([pd.read_csv(A/f) for f in ['nominatim_own_feature_candidates.csv.gz','nominatim_fallback_candidates.csv.gz']]).fillna('').drop_duplicates(['source_record_id','feature_id']);rows=[];edges=[];proof=[]
def addpoint(sid,cp,rule,old,extra):
 row={k:cp[k] for k in ['latitude','longitude','point_origin_file','point_origin_sha256','point_origin_locator','point_origin_kind']};row.update(target_source_record_id=sid,coordinate_source_record_id=cp.get('coordinate_source_record_id',sid),coordinate_admission_status='reviewed_extension_rule_accepted',decision_status='checked_rule_accepted',admission_allowed=True,own_locality_point=True,recipient_point_assigned_to_child=False,source_sha256=old['source_sha256'],source_locator=old.get('source_locator') or f"{old['source_sheet']}:{old['source_row']}",admission_rule=rule,point_temporal_interpretation='Source-bound ownplace representative reused for historical NP by explicit continuity inference; exact censusday geometry and population boundary equivalence unknown.',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,native_population_quality_preserved=True);rows.append(row);proof.append({'source_record_id':sid,'native_source':old,'ownpoint_donor':cp,'source_binding':extra})
def edge(sid,oid,rule):
 groups=f[f.root.isin([b.loc[sid,'root'],b.loc[oid,'root']])];assert not groups.census_year.duplicated().any();edges.append(dict(from_source_record_id=sid,to_source_record_id=oid,relation='same_place',decision_status='checked_rule_accepted',admission_rule=rule,source_context_witness_file=str(O/'point_witnesses_10.json.gz'),source_counts_changed=False,boundary_comparability_asserted=False))
def rawparent(sid,stem):
 x=check(sid);assert x['literal_label_population_passed'];bk=books[x['source_file']];sh=bk.sheet_by_name(str(x['source_sheet'])) if str(x['source_sheet']) in bk.sheet_names() else bk.sheet_by_index(int(x['source_sheet']));r=int(x['source_row']);
 for rn in range(r-1,max(0,r-500),-1):
  v=sh.row_values(rn-1)
  if any('сельсовет' in normalize(z) or 'сельский округ' in normalize(z) or 'волость' in normalize(z) for z in v if isinstance(z,str)):
   assert any(stem in str(z) for z in v);return {'row1based':rn,'rawcells':v}
 raise AssertionError('No native parish')

H=R/'research_rebuild/evidence/over500_efremov3_own_housing_sources_20261009';ep=H/'efremov3_full_own_article.json.gz';ip=H/'separate_istye_exact_lowercase_article.json.gz'
for q in [ep,ip]:pins[str(q)]=sha(q)
# Explicit own residential alias, never the airfield infobox point.
pg=next(z for z in json.load(gzip.open(ep,'rt'))['query']['pages'].values() if z['title']=='Ефремов-3');tx=pg['revisions'][0]['slots']['main']['*'];assert 'ранее военный городок Ефремов-3' in tx and 'их семьи' in tx and 'Квартиры в ДОСах' in tx
sid='2002:016_3aa889d669_02c_Tulskaja.xls:Sheet1:1103';mid='2010:011_040325482b_3._20Ryaz_Smol_Tambov_Tula_Jaroslavl_20L1_20ethn_2010.xls:Data Sheet:10254';cid='2021:data_allsettlements_anon_156_v20251217.parquet:parquet:152894';x=check(sid);mx=check(mid);parent=rawparent(sid,'Лобановский');assert x['literal_label_population_passed'] and x['native_population']==584 and mx['literal_label_population_passed'];rule='Original2002 own counted поселокЕфремов3 under printedЛобановский nativeSO/Eфремов county, explicit full captured own article paragraph names nearby поселокВосточный as formerly residential militarytownЕфремов3 with families and DOShousing. Ownresidential alias binds independently admitted currentВосточный ownhousingpoint, consistent separately captured ownOSM residential way91075233. Main airfield infobox coordinate53.115151,38.242035 EXCLUDED, no factory/citycentre. Actualnative2010Восточный ownblock independently bound in08; same ownposelok role, physical residential continuity with reportednamevariant, no legalrename/date assertion. Count584 and protected2010count751 kept independent; no populationboundary equivalence.';addpoint(sid,p[cid],rule,x,{'actual_printed_native_parent':parent,'source2010_own_leaf':mx,'article_title':pg['title'],'revid':pg['revisions'][0]['revid'],'full_literal_article':tx,'main_airfield_coordinate_rejected':True,'own_housing_current_point':p[cid]});edge(sid,mid,rule)
# Exact lowercase ownarticle preserves former standalone estate, not recipient centre.
pg=json.load(gzip.open(ip,'rt'))['parse'];tx=pg['wikitext']['*'];assert pg['title']=='Истьинское отделение' and 'отделений свиноводческого совхоза «Тарутинский»' in tx and 'Жуковский район' in tx;lat=float(re.search(r'lat_deg\s*=\s*([0-9.]+)',tx).group(1));lon=float(re.search(r'lon_deg\s*=\s*([0-9.]+)',tx).group(1));assert (lat,lon)==(55.128885,36.852142)
sid='2010:013_f60b2d2bcf_5._20Belg_Bryan_Vlad_Voron_Ivanov_Kalug_20L1_ethn_2010.xls:Data Sheet:12318';x=check(sid);oldid='2002:006_1916564aaa_02c_Kaluzhskaja.xls:Sheet1:878';ox=check(oldid);parent=rawparent(oldid,'Воробьевский');assert x['literal_label_population_passed'] and ox['literal_label_population_passed'];sql=Path('/workspace/settlements-raw/data/raw/historical_classifiers/okato_142_2009/dump-142_2009.sql');pins[str(sql)]=sha(sql);lines=[v.strip() for v in sql.open() if v.startswith(('29213804006\t','29213804007\t'))];assert len(lines)==2 and 'Истьинское Отделение' in lines[1];rule='Direct captured ownarticle exact lowercase titleИстьинское отделение explicitly same named former ownсело, Жуковский county/ownТарутинский estatebranch, owninfobox coordinate55.128885,36.852142; independently original2002ownleaf/printedВоробьевский nativecouncil and original2010own503 countedleaf reopened. Original2009 classifier separates ownсело29213804007 from recipientдерИстье29213804006. Actualdated1984map separately labels estateсвхТарутинский versus Истье, corroborates ownestate/site rather than recipientcentroid. OwnformerNP infobox representative admitted with300m uncertainty; no exact historicalcensusgeometry. Later2012 inclusion in ownarticle retained as sourcecontextONLY, no legaledge/identitymerge into recipient. Secondaryarticlecounts/percentages not used; nativecounts/protectedquality/oldposeloktype retained unchanged.';cp={'latitude':lat,'longitude':lon,'coordinate_source_record_id':sid,'point_origin_file':str(ip),'point_origin_sha256':sha(ip),'point_origin_locator':f"ownpageid={pg['pageid']};revid={pg['revid']}; own formerNP lat_deg/lon_deg infobox",'point_origin_kind':'direct_own_named_Wikipedia_former_settlement_infobox_coordinate'};maps=R/'research_rebuild/evidence/over500_north_last_historical_point_sources_20261009';mf=maps/'istye_estate_n-37-026.jpg';pins[str(mf)]=sha(mf);addpoint(sid,cp,rule,x,{'native2002own_leaf':ox,'actual_native2002_parent':parent,'literal2009_distinct_classifier_leaves':lines,'ownarticle_full_text':tx,'ownarticle_pageid':pg['pageid'],'ownarticle_revid':pg['revid'],'independent_dated_map_original':str(mf),'independent_dated_map_sha256':sha(mf),'map_context_crop':str(maps/'istye_estate_ownlabel_crop.png'),'source_lifecycle_context_is_not_identity_edge':True});rows[-1]['coordinate_uncertainty_m']=300
assert len(rows)==2 and len(edges)==1;pd.DataFrame(rows).to_csv(O/'accepted_point_use_delta_10.csv',index=False);pd.DataFrame(edges).to_csv(O/'accepted_identity_edges_10.csv',index=False)
with gzip.GzipFile(filename=str(O/'point_witnesses_10.json.gz'),mode='wb',mtime=0) as z:z.write(json.dumps(proof,ensure_ascii=False,default=str).encode())
(O/'manifest_10.json').write_text(json.dumps({'status':'frozen_final_two_historical_ownpoints','points':2,'identity_edges':1,'sourcecounts_or_quality_modified':False,'input_pins':pins,'output_pins':{str(q):sha(q) for q in [O/'accepted_point_use_delta_10.csv',O/'accepted_identity_edges_10.csv',O/'point_witnesses_10.json.gz']}},ensure_ascii=False,indent=2)+'\n');print('10acceptedfinal2points,1truehousingedge')
