from pathlib import Path
import pandas as pd,json,gzip,hashlib,ast,re,xlrd,sys,shutil
from bs4 import BeautifulSoup
R=Path('/workspace/russian-settlements-research');O=Path(__file__).parent;N=R/'research_rebuild/evidence/over500_north_20261009';A=R/'research_rebuild/evidence/over500_north_alternative_point_sources_20261009';S=Path('/dev/shm/settlements-stage71-20261009');sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from current_chain_state_20261007 import normalize,distance_km
from apply_unique_county_name_bridge_20261007 import county_key
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();f=pd.read_parquet(S/'applied_state_observations.parquet').fillna('');b=f.set_index('source_record_id');sel=Path('/workspace/settlements-delivery/continuation-consolidated-20261003/selected_observations.parquet');m=pd.read_parquet(sel).fillna('').set_index('source_record_id');ps=S/'applied_point_snapshot.parquet';p=pd.read_parquet(ps,columns=['target_source_record_id','latitude','longitude','coordinate_source_record_id','point_origin_file','point_origin_sha256','point_origin_locator','point_origin_kind','coordinate_admission_status']).fillna('').drop_duplicates('target_source_record_id').set_index('target_source_record_id').to_dict('index');pins={str(q):sha(q) for q in [S/'applied_state_observations.parquet',sel,ps]};books={};checks={};rawpar={};fn=ast.unparse(next(x for x in ast.parse((N/'build_packet.py').read_text()).body if isinstance(x,ast.FunctionDef) and x.name=='check')).replace("actual = re.sub('ского$', 'ский', actual)","actual = re.sub('ского$', 'ский', actual); actual = re.sub('цкого$', 'цкий', actual)");exec(fn);c=pd.concat([pd.read_csv(A/f) for f in ['nominatim_own_feature_candidates.csv.gz','nominatim_fallback_candidates.csv.gz']]).fillna('').drop_duplicates(['source_record_id','feature_id']);rows=[];edges=[];proof=[]
def addpoint(sid,cp,rule,old,extra):
 row={k:cp[k] for k in ['latitude','longitude','point_origin_file','point_origin_sha256','point_origin_locator','point_origin_kind']};row.update(target_source_record_id=sid,coordinate_source_record_id=cp.get('coordinate_source_record_id',sid),coordinate_admission_status='reviewed_extension_rule_accepted',decision_status='checked_rule_accepted',admission_allowed=True,own_locality_point=True,recipient_point_assigned_to_child=False,source_sha256=old['source_sha256'],source_locator=old.get('source_locator') or f"{old['source_sheet']}:{old['source_row']}",admission_rule=rule,point_temporal_interpretation='Source-bound ownplace representative reused for historical NP by explicit continuity inference; exact censusday geometry and population boundary equivalence unknown.',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,native_population_quality_preserved=True);rows.append(row);proof.append({'source_record_id':sid,'native_source':old,'ownpoint_donor':cp,'source_binding':extra})
def edge(sid,oid,rule):
 groups=f[f.root.isin([b.loc[sid,'root'],b.loc[oid,'root']])];assert not groups.census_year.duplicated().any();edges.append(dict(from_source_record_id=sid,to_source_record_id=oid,relation='same_place',decision_status='checked_rule_accepted',admission_rule=rule,source_context_witness_file=str(O/'point_witnesses_09.json.gz'),source_counts_changed=False,boundary_comparability_asserted=False))
def rawparent(sid,stem):
 x=check(sid);assert x['literal_label_population_passed'];bk=books[x['source_file']];sh=bk.sheet_by_name(str(x['source_sheet'])) if str(x['source_sheet']) in bk.sheet_names() else bk.sheet_by_index(int(x['source_sheet']));r=int(x['source_row']);
 for rn in range(r-1,max(0,r-500),-1):
  v=sh.row_values(rn-1)
  if any('сельсовет' in normalize(z) or 'сельский округ' in normalize(z) or 'волость' in normalize(z) for z in v if isinstance(z,str)):
   assert any(stem in str(z) for z in v);return {'row1based':rn,'rawcells':v}
 raise AssertionError('No native parish')

oldid='2002:048_4f024587eb_02c_Nizhegorod_obl_new.xls:11:455';sid='2010:014_5ca759eea0_5._20Nizheg_Kirov_202010.xls:Data Sheet:265';ox=check(oldid);x=check(sid);parent=rawparent(oldid,'Шварихинский');rival='2002:048_4f024587eb_02c_Nizhegorod_obl_new.xls:11:386';rx=check(rival);rp=rawparent(rival,'Каменский');ctx=next(z for z in json.load(open('/dev/shm/over500-20261009/north_native_sequence_diag.json')) if z['source_record_id']==sid);assert len(ctx['hits'])==1 and ctx['hits'][0]['old_source_record_id']==oldid;ns=[];coded=[];raw21=pd.read_parquet('/workspace/settlements-raw/data/interim/2021_tochno/data_allsettlements_anon_156_v20251217.parquet',columns=['object_name','population','oktmo','mun_upper','mun_lower'])
for pair in ctx['hits'][0]['pairs']:
 for z in pair:
  xx=check(z[2]);assert xx['literal_label_population_passed'];ns.append(xx)
 aid=pair[1][2];group=f[f.root==b.loc[aid,'root']];cur=group[group.census_year==2021];assert len(cur)==1;cid=cur.iloc[0].source_record_id;cx=check(cid);rr=raw21.iloc[int(cx['source_row'])-1].to_dict();assert str(rr['oktmo']).startswith('225070002');coded.append({'own_primary2021_leaf':cx,'literal_own_code':rr,'native_component':group.source_record_id.tolist()})
v=c[(c.source_record_id==oldid)&(c.feature_id=='way/190109913')].iloc[0].to_dict();q=Path(v['source_file']);pins[str(q)]=sha(q);bundle=json.load(gzip.open(q,'rt'));req=next(z for z in bundle if z['source_record_id']==oldid and z['response_sha256']==v['source_response_sha256']);feat=next(a for a in req['response'] if f"{a['osm_type']}/{a['osm_id']}"==v['feature_id']);assert '22507000241' in v['extratags_json'];assert v['own_name']=='Ушаково';cp={'latitude':float(v['latitude']),'longitude':float(v['longitude']),'coordinate_source_record_id':oldid,'point_origin_file':str(q),'point_origin_sha256':sha(q),'point_origin_locator':v['source_locator'],'point_origin_kind':'direct_captured_OSM_own_settlement_place_feature_representative'}
rule='Original2002 counted деревняУшаково565 explicitly Шварихинский nativecouncil, independently separate Каменский oldminor20. Own2010 row uniquely bound by FOUR distinct rawreopened signed adjacent native names Тетерюгино/Трестьяны/Ченцово/Шопово. Allfour independent accepted ownnative components bind distinct primary2021 owncoded neighbouring leaves of branch225070002, whose independently named ownOSMУшаково fullcode22507000241 identifies separate residential site; rival ownOSM22507000511 belongs other branch/site. Explicit historicalownsite continuity inference from independently sourcebound namedbranch, no legalcouncilchange/date or sourcecode backfill. Private2021 population/code discrepancies and ownWiki historicalcode contradiction NOT resolved or transferred; no2021identityedge. Directownplace representative, providerpopulation ignored; sourcecounts/quality/types preserved.'
extra={'native2002_parent':parent,'native2002_separate_homonym':rx,'native2002_separate_parent':rp,'unique_4_native_sourcepair':ctx,'all_reopened_native_names':ns,'four_independently_sourcebound_current_coded_named_neighbour_leaves':coded,'direct_own_feature':feat,'all_own_provider_rivals':c[c.source_record_id==oldid].to_dict('records'),'current_private2021_identity_not_asserted':True}
for target in [oldid,sid]:
 xx=check(target);assert xx['literal_label_population_passed'];addpoint(target,cp,rule,xx,extra)
edge(oldid,sid,rule);pd.DataFrame(rows).to_csv(O/'accepted_point_use_delta_09.csv',index=False);pd.DataFrame(edges).to_csv(O/'accepted_identity_edges_09.csv',index=False)
with gzip.GzipFile(filename=str(O/'point_witnesses_09.json.gz'),mode='wb',mtime=0) as z:z.write(json.dumps(proof,ensure_ascii=False,default=str).encode())
(O/'manifest_09.json').write_text(json.dumps({'status':'frozen_two_historical_ownpoints_no2021identityclaim','points':2,'identity_edges':1,'sourcecounts_or_quality_modified':False,'input_pins':pins,'output_pins':{str(q):sha(q) for q in [O/'accepted_point_use_delta_09.csv',O/'accepted_identity_edges_09.csv',O/'point_witnesses_09.json.gz']}},ensure_ascii=False,indent=2)+'\n');print('09accepted2points,1edge')
