from pathlib import Path
import pandas as pd,json,hashlib,ast,re,sys,xlrd,gzip
R=Path('/workspace/russian-settlements-research');O=Path(__file__).parent;N=R/'research_rebuild/evidence/over500_north_20261009';S=Path('/dev/shm/settlements-stage71-20261009');sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from current_chain_state_20261007 import normalize,distance_km
from apply_unique_county_name_bridge_20261007 import county_key
from stage_rural_native_okato_points_20261004 import raw_dbf_rows
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();f=pd.read_parquet(S/'applied_state_observations.parquet').fillna('');b=f.set_index('source_record_id');sel=Path('/workspace/settlements-delivery/continuation-consolidated-20261003/selected_observations.parquet');m=pd.read_parquet(sel).fillna('').set_index('source_record_id');ps=S/'applied_point_snapshot.parquet';p=pd.read_parquet(ps,columns=['target_source_record_id','latitude','longitude','coordinate_source_record_id','point_origin_file','point_origin_sha256','point_origin_locator','point_origin_kind','coordinate_admission_status']).fillna('').drop_duplicates('target_source_record_id').set_index('target_source_record_id').to_dict('index');pins={str(q):sha(q) for q in [S/'applied_state_observations.parquet',sel,ps,N/'direct_native_witnesses.csv.gz']};books={};checks={};rawpar={};fn=ast.unparse(next(x for x in ast.parse((N/'build_packet.py').read_text()).body if isinstance(x,ast.FunctionDef) and x.name=='check')).replace("actual = re.sub('ского$', 'ский', actual)","actual = re.sub('ского$', 'ский', actual); actual = re.sub('цкого$', 'цкий', actual)");exec(fn);w=pd.read_csv(N/'direct_native_witnesses.csv.gz').fillna('').set_index('source_record_id');diag=pd.read_csv('/dev/shm/over500-20261009/north_expanded_anchor_diagnostic.csv.gz').fillna('').set_index('source_record_id');rawpath=Path('/workspace/settlements-raw/data/interim/2021_tochno/data_allsettlements_anon_156_v20251217.parquet');raw=pd.read_parquet(rawpath,columns=['object_name','population','oktmo','mun_upper','mun_lower']);pins[str(rawpath)]=sha(rawpath);rows=[];proof=[]
specs=[('2002:018_25c6f5e960_02c_Karelia.xls:Sheet1:229',30881,'Новое Машозеро','Новое Машезеро','single_o_e_spelling_in_qualified_new_own_settlement'),('2002:024_2d3f550c6f_02c_Leningradskaja_obl_new.xls:!!!!!!:428',55860,'Ушевицы','Ущевицы','single_sh_shch_spelling'),('2002:1_TOM_01_04.xls:0:2063',151802,'ст. Скуратово','Станция Скуратово','qualified_station_locality_designator_expansion'),('2002:1_TOM_01_04.xls:0:6170',75200,'Керженец','Керженец','literal_catalog_ownname_printed_county_modern_rural_role')]
for sid,rn,oldname,newname,variant in specs:
 x=w.loc[sid].to_dict();assert x['literal_label_population_passed'];q=Path(x['source_file']);assert sha(q)==x['source_sha256'];pins[str(q)]=sha(q);dsid=f'2021:data_allsettlements_anon_156_v20251217.parquet:parquet:{rn}';assert dsid in p and p[dsid]['coordinate_admission_status'] in ['reviewed_rule_accepted','reviewed_extension_rule_accepted'];cw=check(dsid);assert cw['literal_label_population_passed'];assert normalize(b.loc[dsid,'settlement_name'])==normalize(newname) and normalize(x['native_name'])==normalize(oldname);currentraw=raw.iloc[rn-1];assert str(currentraw.oktmo)==str(b.loc[dsid,'oktmo']);ctx={}
 if variant in ['single_o_e_spelling_in_qualified_new_own_settlement','single_sh_shch_spelling']:
  z=diag.loc[sid].to_dict();lo=ast.literal_eval(z['lower_anchor']);hi=ast.literal_eval(z['upper_anchor']);sr=int(x['source_row']);assert lo['source_row']<sr<hi['source_row'] and max(sr-lo['source_row'],hi['source_row']-sr)<=20 and lo['name']!=hi['name'];assert normalize(currentraw.mun_lower)==normalize(z['native_mun_lower']) and normalize(currentraw.mun_upper)==normalize(z['native_mun_upper']);ctx={'direct_named_flanking_own_native_anchors':z,'reopened_anchor_sources':[check(v) for a in [lo,hi] for v in [a['source_record_id'],a['current_source_record_id']]]};assert all(a['literal_label_population_passed'] for a in ctx['reopened_anchor_sources']);pool=f[(f.census_year==2021)&(f.region_norm==x['native_region'])&(f.name_norm==b.loc[dsid,'name_norm'])];assert len(pool)==1
 else:
  assert 'Чернский' in x['actual_printed_county'] if rn==151802 else 'Борский' in x['actual_printed_county'];assert 'Чернский' in currentraw.mun_upper if rn==151802 else 'Бор' in currentraw.mun_upper;ctx={'primary_catalog_literal_own_native_county':x['actual_printed_county'],'primary_catalog_literal_native_county_locator':x['actual_county_locator']};oldcheck=check(sid);assert oldcheck['literal_label_population_passed'];ctx['reopened_raw_catalog_ownleaf']=oldcheck
 rule='Reopened original historical counted ownNP full literalname/type/count and owncounty/native hierarchy; independently accepted exact own2021 fullcoded native leaf/name/type and rawpoint reopened. '+variant+'. '
 rule+=('Two distinct actually sourcebound full3 named anchors strictly flank originalrowwithin20 and actual primary2021 publisher upper/lower hierarchy of both matches owncarrier, unique whole-region literal current propername. Explicit controlled spelling only, no automatic fuzzy rule.' if 'spelling' in variant else 'Literal printed native catalog county, ownqualifiedname/designator and unique exactowncurrent name in same actualcounty distinguish othercounty/otherqualifiedrole namesakes. Oldurban/rural type interpretation preserved; no legaltypechange inferred.')
 cp=p[dsid];row={k:cp[k] for k in ['latitude','longitude','point_origin_file','point_origin_sha256','point_origin_locator','point_origin_kind']};row.update(target_source_record_id=sid,coordinate_source_record_id=dsid,coordinate_admission_status='reviewed_extension_rule_accepted',decision_status='checked_rule_accepted',admission_allowed=True,own_locality_point=True,recipient_point_assigned_to_child=False,source_sha256=x['source_sha256'],source_locator=f"{x['source_sheet']}:{x['source_row']}",donor_native_own_OKTMO=b.loc[dsid,'oktmo'],admission_rule=rule,point_temporal_interpretation='Modern ownNP representative reused historically by explicit continuity inference, no exact censusday geometry or boundary equivalence.',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,native_population_quality_preserved=True);rows.append(row);proof.append({'source_record_id':sid,'native_source':x,'own_current_native_leaf':cw,'own_current_raw':currentraw.to_dict(),'explicit_variant':variant,'source_context':ctx,'own_point_donor':cp})
# Sourcebound historical code for big Pogranichnoe, not samecounty Chapayev namesake.
sid='2002:023_38d853be37_02c_Kaliningrad.xls:Sheet1:110';x=w.loc[sid].to_dict();assert x['literal_label_population_passed'] and 'Пограничный' in x['primary_native_parent_header'];q=Path(x['source_file']);assert sha(q)==x['source_sha256'];pins[str(q)]=sha(q);SQL=Path('/workspace/settlements-raw/data/raw/historical_classifiers/okato_142_2009/dump-142_2009.sql');DBF=Path('/workspace/settlements-raw/data/raw/historical_geography/geokladr_okato_2011/okato.dbf');G=Path('/workspace/settlements-work/sources/geokladr_raw_verification/geokladr_okato_2011_raw_parsed.parquet');codes={'27203000','27203819000','27203819014','27203828000','27203828003'};sq=[]
for rn,line in enumerate(SQL.open(),1):
 if line.split('\t')[0] in codes:sq.append({'line1based':rn,'raw':line.strip(),'cells':line.strip().split('\t')})
sr={z['cells'][0]:z for z in sq};assert len(sr)==5 and 'Пограничного сельсовета' in sr['27203819000']['raw'] and 'Чапаевского' in sr['27203828000']['raw'];assert sr['27203819014']['cells'][2]=='Пограничное' and sr['27203819014']['cells'][-1]=='t';gd=pd.read_parquet(G).fillna('');a=gd[gd.historical_okato=='27203819014'];assert len(a)==1;rr=list(raw_dbf_rows(DBF,a).values())[0];assert rr['code']=='27203819014' and normalize(rr['name_raw'])=='п пограничное' and rr['deleted_marker']==' ';coord=(float(rr['lat_raw']),float(rr['lon_raw']));dsid='2021:data_allsettlements_anon_156_v20251217.parquet:parquet:25743';cp=p[dsid];dist=distance_km(coord,(float(cp['latitude']),float(cp['longitude'])));assert dist<1;assert check(dsid)['literal_label_population_passed'];small='2021:data_allsettlements_anon_156_v20251217.parquet:parquet:25709';small_dist=distance_km(coord,(float(p[small]['latitude']),float(p[small]['longitude'])));assert small_dist>10
for q in [SQL,DBF,G]:pins[str(q)]=sha(q)
rule='Primary2002 own counted Pogranichnoe602 under explicitly printed Pogranichny ruralcouncil; original alltyped samecounty named rival64 under Chapayev council is separate. Independently reopened2009 ownNP classifier27203819014 with exactnative name/type and namedPogranichny parent/Bagration county; exactowncode/name/type in2011GeoKLADR rawDBF. Coordinate independently agrees<1km with admitted ownnativecurrent Pogranichny fullcoded carrier and lies>10km from actualsamecounty smallPogranichnoe. Nameending variant/sourcecalendar interpretation retained; ownhistoricalcode not backfilled as nativecensus identifier. No identityedge/legalrename/boundary claim.'
rows.append(dict(target_source_record_id=sid,latitude=coord[0],longitude=coord[1],coordinate_source_record_id=sid,coordinate_admission_status='reviewed_extension_rule_accepted',decision_status='checked_rule_accepted',admission_allowed=True,own_locality_point=True,recipient_point_assigned_to_child=False,source_sha256=x['source_sha256'],source_locator=f"{x['source_sheet']}:{x['source_row']}",point_origin_file=str(DBF),point_origin_sha256=sha(DBF),point_origin_locator=f"DBF record1based={rr['record_no']};byte_offset0based={rr['byte_offset']};ownhistoricalOKATO27203819014",point_origin_kind='independently_native_parish_bound_own_historical_GeoKLADR_point',historical_classifier_own_code='27203819014',native_census_code_unknown_not_backfilled=True,admission_rule=rule,point_temporal_interpretation='2011ownplace representative reused in2002 by explicit continuity inference; no censusday measured geometry/boundary equivalence.',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,native_population_quality_preserved=True));proof.append({'source_record_id':sid,'native_source':x,'official_independent_2009_owncode_and_rival_rows':sq,'rawDBFreplay':rr,'current_independently_owncode_bound_carrier':check(dsid),'current_ownpoint':cp,'ownpoint_distance_km':dist,'other_actual_namesake_distance_km':small_dist,'samecounty_small_native_rival_row':135,'samecounty_small_native_rival_council':'Чапаевский','minorGeoKLADR_samecoordinate_artifact_not_used':True})
assert len(rows)==5;pd.DataFrame(rows).to_csv(O/'accepted_point_use_delta_04.csv',index=False)
with gzip.GzipFile(filename=str(O/'point_witnesses_04.json.gz'),mode='wb',mtime=0) as z:z.write(json.dumps(proof,ensure_ascii=False,default=str).encode())
(O/'manifest_04.json').write_text(json.dumps({'status':'frozen_accepted_ownpoints_only','points':5,'identity_edges':0,'sourcecounts_or_quality_modified':False,'input_pins':pins,'output_pins':{str(q):sha(q) for q in [O/'accepted_point_use_delta_04.csv',O/'point_witnesses_04.json.gz']}},ensure_ascii=False,indent=2)+'\n');print('accepted5')
