from pathlib import Path
import pandas as pd,json,gzip,hashlib,re,xlrd
R=Path('/workspace/russian-settlements-research/research_rebuild/evidence');O=Path(__file__).parent;A=R/'over500_north_alternative_point_sources_20261009';N=R/'over500_north_20261009';sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
t=pd.read_csv(A/'exact49_targets.csv.gz').fillna('');w=pd.concat([pd.read_csv(N/'direct_native_witnesses.csv.gz'),pd.read_csv(R/'over500_north_supplemental_native_20261009/recovered_direct_native_witnesses.csv')]).fillna('').drop_duplicates('source_record_id',keep='last').set_index('source_record_id');c=pd.concat([pd.read_csv(A/f) for f in ['nominatim_own_feature_candidates.csv.gz','nominatim_fallback_candidates.csv.gz']]).fillna('').drop_duplicates(['source_record_id','feature_id']);obs=pd.read_parquet('/dev/shm/settlements-stage71-20261009/applied_state_observations.parquet').fillna('');norm=lambda s:re.sub('[^а-яa-z0-9]','',str(s).lower().replace('ё','е'))
# Explicit reviewed source bindings; provider population plays no role.
specs=[('2002:013_2dd2afccd6_02c_Smolenskaja.xls:Sheet1:227','relation/3772910','Ермолинский','Ермолинское','NativeErmolinsky parish distinguishes samecounty namesake under another parish; own OSM feature carries parish-specific Wikipedia ownplace title.'),('2002:013_2dd2afccd6_02c_Smolenskaja.xls:Sheet1:2992','way/253489723','Остер','Остёрское','Nativeposelok under Oster administration distinct from samecounty oldvillage Pavlovka; own OSM place feature has Oster ownplace title. Modern village status retained as provider statement, no oldtype edit.'),('2002:023_38d853be37_02c_Kaliningrad.xls:Sheet1:370','relation/19899040','Ново-Московский','Новомосковское','NativeNovoMoskovsky parish directly matches explicit ownplace title; Nizovskoye samecounty namesake rejected.'),('2002:023_38d853be37_02c_Kaliningrad.xls:Sheet1:4','way/1318350804','Балтийска','Балтийск','Explicit native subordination to Baltiysk and ownplace provider address Baltiysk distinguish othercounty namesakes.'),('2002:027_25f0f7433c_02c_Pskovskaja.xls:!!:5770','way/1342846762','Запольская','Запольская','Literal native parish and ownplace provider title agree; samecounty Plyussa parish namesake rejected.'),('2002:015_90ef69f659_02c_Tver_obl.xls:!!!:2583','way/599637816','Кулицкий','Кулицкая','Native counted railway-station locality977; unique samecounty proper-name locality across all native types/years after literalquote stripping. OSM ownplace village separated from bus/rail POIs.'),('ARK2010:archive20131022:html_table1_tr2548','way/1341315095','Шалакуш','Лепша','Native full forest settlement LepshaNovy under Shalakusha; OSM ownplace explicitly official_status лесной посёлок and literal ownpropername Лепша-Новый, distinct railway NP Лепша.')]
rows=[];proof=[];pins={str(q):sha(q) for q in [A/'exact49_targets.csv.gz',N/'direct_native_witnesses.csv.gz',R/'over500_north_supplemental_native_20261009/recovered_direct_native_witnesses.csv',A/'nominatim_own_feature_candidates.csv.gz',A/'nominatim_fallback_candidates.csv.gz','/dev/shm/settlements-stage71-20261009/applied_state_observations.parquet']};books={}
def native_reopen(sid):
 x=w.loc[sid].to_dict();assert x['literal_label_population_passed'];q=Path(x['source_file']);assert sha(q)==x['source_sha256'];pins[str(q)]=sha(q)
 if q.suffix=='.xls':
  if str(q) not in books:books[str(q)]=xlrd.open_workbook(q)
  b=books[str(q)];sheet=b.sheet_by_name(str(x['source_sheet'])) if str(x['source_sheet']) in b.sheet_names() else b.sheet_by_index(int(x['source_sheet']));cells=sheet.row_values(int(float(x['source_row']))-1);assert any(norm(x['native_name']) in norm(v) for v in cells if isinstance(v,str));assert any(str(v).replace('.','',1).isdigit() and float(v)==float(x['native_population']) for v in cells);x['reopened_raw_cells_json']=json.dumps(cells,ensure_ascii=False)
 return x
for sid,fid,pstem,ostem,reason in specs:
 x=native_reopen(sid);z=t[t.source_record_id==sid].iloc[0];v=c[(c.source_record_id==sid)&(c.feature_id==fid)].iloc[0].to_dict();e=json.loads(v['extratags_json'] or '{}');address=json.loads(v['address_json']);assert v['feature_category']=='place' and v['feature_type'] in ['village','hamlet'];assert norm(pstem) in norm(x['primary_native_parent_header']);assert norm(ostem) in norm(e.get('wikipedia','')+v['own_name']+v['display_name']);assert float(v['latitude'])>0 and float(v['longitude'])>0
 q=Path(v['source_file']);pins[str(q)]=sha(q);bundle=json.load(gzip.open(q,'rt'));response=next(r for r in bundle if r['source_record_id']==sid and r['response_sha256']==v['source_response_sha256']);own=next(r for r in response['response'] if f"{r['osm_type']}/{r['osm_id']}"==fid);assert float(own['lat'])==float(v['latitude']) and float(own['lon'])==float(v['longitude']);assert norm(own.get('name',''))==norm(v['own_name']);
 if 'Lepsha' in reason:assert e.get('official_status')=='ru:лесной посёлок'
 region_names=obs[(obs.region_norm==z.region_norm)&(obs.name_norm.map(norm)==norm(z.settlement_name))];rivals=region_names[['source_record_id','census_year','settlement_name','settlement_type','district_raw','population']].to_dict('records')
 if sid=='2002:015_90ef69f659_02c_Tver_obl.xls:!!!:2583':assert set(region_names.district_raw.map(lambda x:norm(x).replace('муниципальный','').replace('район','')))=={'калининский'}
 rule='Direct reopened historical counted own NP leaf/name/type and literal native county/parish hierarchy; independently captured own OSM place feature/name/address/subcounty context, with explicit reviewed rival separation. '+reason+' Provider population never used for binding. Historical use is explicit continuity inference; no identity edge or censusday/boundary assertion.'
 rows.append(dict(target_source_record_id=sid,latitude=float(v['latitude']),longitude=float(v['longitude']),coordinate_source_record_id=sid,coordinate_admission_status='reviewed_extension_rule_accepted',decision_status='checked_rule_accepted',admission_allowed=True,own_locality_point=True,recipient_point_assigned_to_child=False,source_sha256=x['source_sha256'],source_locator=x.get('source_locator') or f"{x['source_sheet']}:{x['source_row']}",point_origin_file=str(q),point_origin_sha256=sha(q),point_origin_locator=v['source_locator'],point_origin_kind='direct_captured_OSM_own_settlement_place_feature_representative',external_own_feature_id=fid,admission_rule=rule,point_temporal_interpretation='Modern own locality representative reused historically by explicit continuity inference; exact censusday geometry and boundary equivalence unknown.',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,native_population_quality_preserved=True));proof.append(dict(source_record_id=sid,native_source_json=json.dumps(x,ensure_ascii=False),own_feature_json=json.dumps(own,ensure_ascii=False),native_all_type_same_region_name_rivals_json=json.dumps(rivals,ensure_ascii=False),provider_same_query_rivals_json=c[c.source_record_id==sid].to_json(orient='records',force_ascii=False),explicit_rival_disposition=reason))
# Own fullforest source2002 label directly binds the already reviewed ownforest article point, not the railway NP.
sid='2002:020_e4f979c6c7_02c_Arxang-new.xls:Sheet1:2405';x=native_reopen(sid);donor=pd.read_csv(N/'supplemental_accepted_point_use_delta_v2.csv').fillna('');donor=donor[donor.target_source_record_id=='ARK2010:archive20131022:html_table1_tr2547'].iloc[0].to_dict();assert norm(x['native_name'])==norm('Лесной Посёлок Ивакша') and 'Шалакуш' in x['primary_native_parent_header'];pins[str(N/'supplemental_accepted_point_use_delta_v2.csv')]=sha(N/'supplemental_accepted_point_use_delta_v2.csv');row={k:donor[k] for k in ['latitude','longitude','point_origin_file','point_origin_sha256','point_origin_locator','point_origin_kind']};row.update(target_source_record_id=sid,coordinate_source_record_id=donor['target_source_record_id'],coordinate_admission_status='reviewed_extension_rule_accepted',decision_status='checked_rule_accepted',admission_allowed=True,own_locality_point=True,recipient_point_assigned_to_child=False,source_sha256=x['source_sha256'],source_locator=f"{x['source_sheet']}:{x['source_row']}",admission_rule='Reopened original2002 full ownforest settlement label737 under literalShalakusha/Nyandoma hierarchy; identical fullnamed ownforest source2010 previously explicitly source-bound to ownforest article point. ForestNP and railwayNP separated by full native name/type. Ownforest representative reused by explicit continuity, no identity edge/count/day-boundary claim.',point_temporal_interpretation='Modern ownforest NP representative reused retrospectively by explicit continuity inference.',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,native_population_quality_preserved=True);rows.append(row);proof.append(dict(source_record_id=sid,native_source_json=json.dumps(x,ensure_ascii=False),accepted_ownforest_donor_json=json.dumps(donor,ensure_ascii=False)))
assert len(rows)==8 and len({r['target_source_record_id'] for r in rows})==8
pd.DataFrame(rows).to_csv(O/'accepted_point_use_delta_01.csv',index=False);pd.DataFrame(proof).to_csv(O/'point_witnesses_01.csv.gz',index=False,compression={'method':'gzip','mtime':0});disp=t[['source_record_id','settlement_name','population','population_value_quality']].copy();disp=disp[~disp.source_record_id.str.endswith(':2288')];disp['disposition']=disp.source_record_id.map(lambda x:'accepted_ownpoint_packet01' if x in {r['target_source_record_id'] for r in rows} else 'held_pending_ownpoint_review');disp['sourcecounts_or_quality_modified']=False;disp.to_csv(O/'per_record_dispositions_01.csv',index=False)
manifest={'status':'frozen_accepted_ownpoints_only','accepted_points':8,'identity_edges':0,'remaining_whole_assigned_rows':len(disp)-8,'sourcecounts_or_quality_modified':False,'input_pins':pins,'output_pins':{str(q):sha(q) for q in [O/'accepted_point_use_delta_01.csv',O/'point_witnesses_01.csv.gz',O/'per_record_dispositions_01.csv']}};(O/'manifest_01.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n');print('accepted8, remaining',len(disp)-8)
