from pathlib import Path
import pandas as pd,json,gzip,hashlib,ast,re,xlrd,sys,shutil
from bs4 import BeautifulSoup
R=Path('/workspace/russian-settlements-research');O=Path(__file__).parent;N=R/'research_rebuild/evidence/over500_north_20261009';A=R/'research_rebuild/evidence/over500_north_alternative_point_sources_20261009';S=Path('/dev/shm/settlements-stage71-20261009');sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from current_chain_state_20261007 import normalize,distance_km
from apply_unique_county_name_bridge_20261007 import county_key
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();f=pd.read_parquet(S/'applied_state_observations.parquet').fillna('');b=f.set_index('source_record_id');sel=Path('/workspace/settlements-delivery/continuation-consolidated-20261003/selected_observations.parquet');m=pd.read_parquet(sel).fillna('').set_index('source_record_id');ps=S/'applied_point_snapshot.parquet';p=pd.read_parquet(ps,columns=['target_source_record_id','latitude','longitude','coordinate_source_record_id','point_origin_file','point_origin_sha256','point_origin_locator','point_origin_kind','coordinate_admission_status','point_ledger_path']).fillna('').drop_duplicates('target_source_record_id').set_index('target_source_record_id').to_dict('index');pins={str(q):sha(q) for q in [S/'applied_state_observations.parquet',sel,ps]};books={};checks={};rawpar={};fn=ast.unparse(next(x for x in ast.parse((N/'build_packet.py').read_text()).body if isinstance(x,ast.FunctionDef) and x.name=='check')).replace("actual = re.sub('ского$', 'ский', actual)","actual = re.sub('ского$', 'ский', actual); actual = re.sub('цкого$', 'цкий', actual)");exec(fn);c=pd.concat([pd.read_csv(A/f) for f in ['nominatim_own_feature_candidates.csv.gz','nominatim_fallback_candidates.csv.gz']]).fillna('').drop_duplicates(['source_record_id','feature_id']);rows=[];edges=[];proof=[]
def addpoint(sid,cp,rule,old,extra):
 row={k:cp[k] for k in ['latitude','longitude','point_origin_file','point_origin_sha256','point_origin_locator','point_origin_kind']};row.update(target_source_record_id=sid,coordinate_source_record_id=cp.get('coordinate_source_record_id',sid),coordinate_admission_status='reviewed_extension_rule_accepted',decision_status='checked_rule_accepted',admission_allowed=True,own_locality_point=True,recipient_point_assigned_to_child=False,source_sha256=old['source_sha256'],source_locator=old.get('source_locator') or f"{old['source_sheet']}:{old['source_row']}",admission_rule=rule,point_temporal_interpretation='Source-bound ownplace representative reused for historical NP by explicit continuity inference; exact censusday geometry and population boundary equivalence unknown.',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,native_population_quality_preserved=True);rows.append(row);proof.append({'source_record_id':sid,'native_source':old,'ownpoint_donor':cp,'source_binding':extra})
def edge(sid,oid,rule):
 groups=f[f.root.isin([b.loc[sid,'root'],b.loc[oid,'root']])];assert not groups.census_year.duplicated().any();edges.append(dict(from_source_record_id=sid,to_source_record_id=oid,relation='same_place',decision_status='checked_rule_accepted',admission_rule=rule,source_context_witness_file=str(O/'point_witnesses_08.json.gz'),source_counts_changed=False,boundary_comparability_asserted=False))
def rawparent(sid,stem):
 x=check(sid);assert x['literal_label_population_passed'];bk=books[x['source_file']];sh=bk.sheet_by_name(str(x['source_sheet'])) if str(x['source_sheet']) in bk.sheet_names() else bk.sheet_by_index(int(x['source_sheet']));r=int(x['source_row']);
 for rn in range(r-1,max(0,r-500),-1):
  v=sh.row_values(rn-1)
  if any('сельсовет' in normalize(z) or 'сельский округ' in normalize(z) or 'волость' in normalize(z) for z in v if isinstance(z,str)):
   assert any(stem in str(z) for z in v);return {'row1based':rn,'rawcells':v}
 raise AssertionError('No native parish')

raw2021=pd.read_parquet('/workspace/settlements-raw/data/interim/2021_tochno/data_allsettlements_anon_156_v20251217.parquet',columns=['object_name','population','oktmo','mun_upper','mun_lower'])
rejections=[]
for rn,cur,anchors,marker in [(10254,152894,[10256,10257],10253),(11755,151361,[11756,11758],11750),(12455,152001,[12453,12454],None)]:
 sid=next(i for i in b.index if i.startswith('2010:011_') and i.endswith(':'+str(rn)));cid='2021:data_allsettlements_anon_156_v20251217.parquet:parquet:'+str(cur);x=check(sid);cx=check(cid);assert x['literal_label_population_passed'] and cx['literal_label_population_passed'];sh=books[x['source_file']].sheet_by_name(x['source_sheet']);an=[]
 for ar in anchors:
  aid=next(i for i in b.index if i.startswith('2010:011_') and i.endswith(':'+str(ar)));ax=check(aid);assert ax['literal_label_population_passed'];members=f[f.root==b.loc[aid,'root']];assert set(members.census_year)=={2002,2010,2021};a21=members[members.census_year==2021].iloc[0].source_record_id;ac=check(a21);raw=raw2021.iloc[int(ac['source_row'])-1].to_dict();assert raw['mun_upper']==raw2021.iloc[int(cx['source_row'])-1]['mun_upper'];an.append({'native_anchor':ax,'accepted_component_members':members.source_record_id.tolist(),'owncoded_current_anchor':raw})
 cp=p[cid];ownraw=raw2021.iloc[int(cx['source_row'])-1].to_dict();extra={'own_current_native':cx,'own_current_raw_hierarchy':ownraw,'two_distinct_reopened_native_component_anchors':an,'actual_source_local_block':[{ 'row1based':r,'rawcells':sh.row_values(r-1)[:5]} for r in range(rn-6,rn+4)],'same_region_name_rivals':f[(f.census_year==2010)&(f.region_norm==b.loc[sid,'region_norm'])&(f.name_norm==b.loc[sid,'name_norm'])].to_dict('records')}
 if marker:
  extra['literal_urban_source_block_marker']={'row1based':marker,'rawcells':sh.row_values(marker-1)[:5]};assert ('Ефремов' if rn==10254 else 'Чекалин') in str(extra['literal_urban_source_block_marker']);rule='Literal own2010 counted settlement reopened; first own rural source block after explicit urban '+('Ефремов' if rn==10254 else 'Чекалин/Агеево')+' marker, independently two distinct immediately following accepted native ownleaves both bind same primary2021 county. Exact ownname/settlementrole and independently admitted owncoded currentNP; all source2010 same-name rivals separated by nativecounty block. Urban marker is not called a countycaption. Ownpoint retrospective continuity explicit; nativecounts/quality unchanged.'
 else:
  v=c[(c.source_record_id==sid)&(c.feature_id=='way/169546023')].iloc[0].to_dict();q=Path(v['source_file']);pins[str(q)]=sha(q);bundle=json.load(gzip.open(q,'rt'));req=next(z for z in bundle if z['source_record_id']==sid and z['response_sha256']==v['source_response_sha256']);feat=next(a for a in req['response'] if f"{a['osm_type']}/{a['osm_id']}"==v['feature_id']);assert 'Огарёвское' in v['address_json'] and 'Огаревское' in ownraw['mun_lower'];cp={'latitude':float(v['latitude']),'longitude':float(v['longitude']),'coordinate_source_record_id':cid,'point_origin_file':str(q),'point_origin_sha256':sha(q),'point_origin_locator':v['source_locator'],'point_origin_kind':'direct_captured_OSM_own_settlement_place_feature_representative'};extra['own_feature']=feat;extra['all_distinct_parish_provider_rivals']=c[c.source_record_id==sid].to_dict('records');minor=next(i for i in b.index if i.startswith('2010:011_') and i.endswith(':12404'));extra['separately_admitted_Yasnopolyansky_minor']=f[f.root==b.loc[minor,'root']].to_dict('records');rule='Own2010 Майский at end of Огаревский ownleaf source sequence; two distinct immediately preceding independently accepted full3 nativeleaves both primary2021 Огаревское, same ownname/poselok and owncoded current major ОКТМО70648412176. Separate2010minor12404 already independently linked to owncurrent Яснополянское ОКТМО70648408161, excludes homonym. Direct own OSM Майский residential hamlet explicitly Огарёвское supplies ownsite; reject recipient/retail/currentminorpoint. Baselinecurrentmajor Dadata coordinates erroneously at separate minor site; only coordinateclaim corrected, rawimport/counts/code unchanged.'
  oldp=p[cid];ledge=Path(oldp['point_ledger_path']);pins[str(ledge)]=sha(ledge);rejections.append(dict(target_source_record_id=cid,rejection_status='reviewed_rejected_coordinate_claim_only',old_latitude=oldp['latitude'],old_longitude=oldp['longitude'],origin_ledger=str(ledge),origin_ledger_sha256=sha(ledge),reason=rule,native_identity_or_population_rejected=False));extra['rejected_major_old_coordinate_claim']=oldp;addpoint(cid,cp,rule,cx,extra)
 addpoint(sid,cp,rule,x,extra);edge(sid,cid,rule)
assert len(rows)==4 and len(edges)==3 and len(rejections)==1
pd.DataFrame(rows).to_csv(O/'accepted_point_use_delta_08.csv',index=False);pd.DataFrame(edges).to_csv(O/'accepted_identity_edges_08.csv',index=False);pd.DataFrame(rejections).to_csv(O/'accepted_point_rejection_delta_08.csv',index=False)
with gzip.GzipFile(filename=str(O/'point_witnesses_08.json.gz'),mode='wb',mtime=0) as z:z.write(json.dumps(proof,ensure_ascii=False,default=str).encode())
(O/'manifest_08.json').write_text(json.dumps({'status':'frozen_three_own2010_points_plus_corrected_major_site','points':4,'assignment_missingpoints':3,'identity_edges':3,'coordinate_claim_rejections':1,'sourcecounts_or_quality_modified':False,'input_pins':pins,'output_pins':{str(q):sha(q) for q in [O/'accepted_point_use_delta_08.csv',O/'accepted_identity_edges_08.csv',O/'accepted_point_rejection_delta_08.csv',O/'point_witnesses_08.json.gz']}},ensure_ascii=False,indent=2)+'\n')
print('08 frozen:3newhistoricalpoints+1currentpointcorrection,3edges')
