from pathlib import Path
import pandas as pd,json,ast,hashlib,xlrd,re,sys,gzip
R=Path('/workspace/russian-settlements-research');O=Path(__file__).parent;N=R/'research_rebuild/evidence/over500_north_20261009';H=R/'research_rebuild/evidence/over500_north_last_historical_point_sources_20261009';S=Path('/dev/shm/settlements-stage71-20261009');sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from current_chain_state_20261007 import normalize,distance_km
from apply_unique_county_name_bridge_20261007 import county_key
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();f=pd.read_parquet(S/'applied_state_observations.parquet').fillna('');b=f.set_index('source_record_id');sel=Path('/workspace/settlements-delivery/continuation-consolidated-20261003/selected_observations.parquet');m=pd.read_parquet(sel).fillna('').set_index('source_record_id');ps=S/'applied_point_snapshot.parquet';p=pd.read_parquet(ps,columns=['target_source_record_id','latitude','longitude','coordinate_source_record_id','point_origin_file','point_origin_sha256','point_origin_locator','point_origin_kind','coordinate_admission_status']).fillna('').drop_duplicates('target_source_record_id').set_index('target_source_record_id').to_dict('index');pins={str(q):sha(q) for q in [S/'applied_state_observations.parquet',sel,ps]};books={};checks={};rawpar={};fn=ast.unparse(next(x for x in ast.parse((N/'build_packet.py').read_text()).body if isinstance(x,ast.FunctionDef) and x.name=='check')).replace("actual = re.sub('ского$', 'ский', actual)","actual = re.sub('ского$', 'ский', actual); actual = re.sub('цкого$', 'цкий', actual)");exec(fn);rows=[];edges=[];proof=[]
def parent(sid,stem):
 x=check(sid);assert x['literal_label_population_passed'];bk=books[x['source_file']];s=bk.sheet_by_name(str(x['source_sheet']));r=int(x['source_row']);
 for rn in range(r-1,max(0,r-300),-1):
  v=s.row_values(rn-1)
  if any(('сельсовет' in str(a) or 'сельский округ' in str(a)) for a in v):assert any(stem in str(a) for a in v);return {'row1based':rn,'rawcells':v}
 raise AssertionError('no nativeparent')
for filename in ['golovino_n-37-009.jpg','golovino_ownlabel_crop.png','golovino_dated_caption_crop.png','kuznetsy_o-39-051.jpg','kuznetsy_ownlabel_crop.png','kuznetsy_dated_caption_crop.png','source_capture_receipt.json','four_source_reviews.json']:pins[str(H/filename)]=sha(H/filename)
# Independent frame refinement: representative pixel in own village footprint, not poselok footprint.
sid='2002:003_308406b0ed_02c_Vladimirskaja.xls:Sheet1:2280';x=check(sid);par=parent(sid,'Головинский');assert 'Судогод' in x['actual_printed_county'];q=H/'golovino_n-37-009.jpg';pixel=(2315,440);frame={'northwest_pixel':[134,104],'northeast_pixel':[2680,104],'southwest_pixel':[128,3142],'southeast_pixel':[2690,3145],'north_lat_native':56.0,'south_lat_native':55+40/60,'west_lon_native':40.0,'east_lon_native':40.5};lat=round(56.0-(pixel[1]-104)/(3145-104)/3,4);lon=round(40.0+(pixel[0]-134)/(2680-134)/2,4);assert (lat,lon)==(55.9632,40.4283);rule='Original2002 counted деревняГоловино727 explicitly Sudogodsky/Golovinsky native hierarchy; actual dated1:100000N37-009 map1979 separately labels northern own village Головино and southern п.Головино residential footprint. Direct ownvillage residential-site pixel digitized from labelled northern footprint using printedgeographicframe; municipality/currentposelok centroid rejected. Map populationannotation not a census count and not transferred; approximategeodetic representative with300m uncertainty absorbs sourcePulkovo42/WGS84 datum/localprojection/digitization uncertainty. No inclusiondate or censusday/boundary assertion.';rows.append(dict(target_source_record_id=sid,latitude=lat,longitude=lon,coordinate_source_record_id=sid,coordinate_admission_status='reviewed_extension_rule_accepted',decision_status='checked_rule_accepted',admission_allowed=True,own_locality_point=True,recipient_point_assigned_to_child=False,source_sha256=x['source_sha256'],source_locator=f"{x['source_sheet']}:{x['source_row']}",point_origin_file=str(q),point_origin_sha256=sha(q),point_origin_locator='topographicN37-009 edition1979;ownvillagepixel=[2315,440];ownlabelcrop=[2150,150,2700,650]',point_origin_kind='independently_reviewed_labelled_historical_own_village_map_digitization',coordinate_uncertainty_m=300,native_map_geodetic_datum='SovietmapPulkovo1942 expected;approxWGS84representative withdatumdifference inside300m uncertainty',admission_rule=rule,point_temporal_interpretation='1979labelled ownvillage-site representative reused in2002 by explicitcontinuity, no censusdaymeasured coordinate or populationboundary equivalence.',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,native_population_quality_preserved=True));proof.append({'source_record_id':sid,'native_source':x,'native_parent':par,'actual_historical_map':str(q),'independently_reviewed_ownlabel_crop':str(H/'golovino_ownlabel_crop.png'),'dated_edition_crop':str(H/'golovino_dated_caption_crop.png'),'frame_control':frame,'own_footprint_pixel':pixel,'digitization_lat_lon':[lat,lon],'uncertainty_m':300,'distinct_named_poselok_rejected':True,'map_numeric_annotation_not_used_as_census_count':True})
# Kuznetsy own labelled historic village and own native neighbours bind major site; minorGeoKLADR identifier is wrong for same coordinate.
old='2002:047_9960082a3e_02c_Kirovskaja_new.xls:Sheet1:4682';mid='2010:014_5ca759eea0_5._20Nizheg_Kirov_202010.xls:Data Sheet:8468';cur='2021:data_allsettlements_anon_156_v20251217.parquet:parquet:37198';rivalold='2002:047_9960082a3e_02c_Kirovskaja_new.xls:Sheet1:4848';rivalmid='2010:014_5ca759eea0_5._20Nizheg_Kirov_202010.xls:Data Sheet:8594';ox=check(old);mx=check(mid);cx=check(cur);rx=check(rivalold);rm=check(rivalmid);assert all(a['literal_label_population_passed'] for a in [ox,mx,cx,rx,rm]);par=parent(old,'Кузнецовский');rpar=parent(rivalold,'Чудиновский');assert 'Орлов' in ox['actual_printed_county'];seq=next(a for a in json.load(open('/dev/shm/over500-20261009/north_native_sequence_diag.json')) if a['source_record_id']==mid);assert len(seq['hits'])==1 and seq['hits'][0]['old_source_record_id']==old;neigh=[check(a[0][2]) for a in seq['hits'][0]['pairs']]+[check(a[1][2]) for a in seq['hits'][0]['pairs']];assert all(a['literal_label_population_passed'] for a in neigh);cp=p[cur];assert cp['coordinate_admission_status'] in ['reviewed_rule_accepted','reviewed_extension_rule_accepted'];frame={'northwest_pixel':[98,90],'northeast_pixel':[2360,90],'southwest_pixel':[98,2977],'southeast_pixel':[2360,2977],'north_lat_native':58+40/60,'south_lat_native':58+20/60,'west_lon_native':49.0,'east_lon_native':49.5};pixel=(235,135);mapcoord=(58+40/60-(135-90)/(2977-90)/3,49+(235-98)/(2360-98)/2);dist=distance_km(mapcoord,(float(cp['latitude']),float(cp['longitude'])));assert dist<0.3;rule='Source2002 ownvillageKuznetsy731 under explicitly printedKuznetsovsky council/Orlovsky county, distinct ownminor10 underChudinovsky council. Original2010 ownvillage680 uniquely matches major2002 through2 distinct rawreopened signedphysicalownneighbours, while samecounty2010minor9 separate. Actual historicalO39-051 terrain1988/edition1994 labels own village residentialfootprint near same source-native BolDychi/MalyeZhdanovy context; direct published ownlabel separates majorphysicalsite from wrongcode/coordinate assumptions. Reopened actualprimary2021 owncodedvillage568 and independently admitted owncurrentWGS84 point agrees<300m with independently refined historical labelledfootprint. Historicalmap populationannotation not transferred or used as census equality; minorGeoKLADR samecoordinate is rejected externalidentifier binding artifact. Nativepopulation/type/quality untouched; no censusdaygeometry/boundary/lifecycle claim.'
for sid,x in [(old,ox),(mid,mx)]:
 row={k:cp[k] for k in ['latitude','longitude','point_origin_file','point_origin_sha256','point_origin_locator','point_origin_kind']};row.update(target_source_record_id=sid,coordinate_source_record_id=cur,coordinate_admission_status='reviewed_extension_rule_accepted',decision_status='checked_rule_accepted',admission_allowed=True,own_locality_point=True,recipient_point_assigned_to_child=False,source_sha256=x['source_sha256'],source_locator=f"{x['source_sheet']}:{x['source_row']}",admission_rule=rule,point_temporal_interpretation='Independently labelled own historical village/site bounds actual own current coded NP representative reusedhistorically by explicit continuity inference.',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,native_population_quality_preserved=True);rows.append(row)
for sid,oid in [(old,mid),(mid,cur)]:
 g=f[f.root.isin([b.loc[sid,'root'],b.loc[oid,'root']])];assert not g.census_year.duplicated().any();assert b.loc[sid,'type_norm']==b.loc[oid,'type_norm'];edges.append(dict(from_source_record_id=sid,to_source_record_id=oid,relation='same_place',decision_status='checked_rule_accepted',admission_rule=rule+' Actual own typedsourceyear roles/physicalsite agree and union has no repeated censusyear.',source_context_witness_file=str(O/'point_witnesses_06.json.gz'),source_counts_changed=False,boundary_comparability_asserted=False))
proof.append({'source_record_ids':[old,mid,cur],'major_native2002':ox,'major_native2010':mx,'own_native2021':cx,'major_native2002_parish':par,'minor_native2002':rx,'minor_native2010':rm,'minor_native2002_parish':rpar,'primary_source_sequence':seq,'all_native_reopened_sequence_neighbours':neigh,'actual_historical_map':str(H/'kuznetsy_o-39-051.jpg'),'actual_ownlabel_crop':str(H/'kuznetsy_ownlabel_crop.png'),'actual_dated_caption_crop':str(H/'kuznetsy_dated_caption_crop.png'),'independently_refined_map_frame':frame,'own_footprint_pixel':pixel,'map_native_lat_lon':mapcoord,'accepted_current_ownpoint':cp,'independent_map_current_point_distance_km':dist,'minorGeoKLADR_identifier_coordinate_artifact_rejected':True,'map_populationannotation_not_transferred':True})
assert len(rows)==3 and len(edges)==2;pd.DataFrame(rows).to_csv(O/'accepted_point_use_delta_06.csv',index=False);pd.DataFrame(edges).to_csv(O/'accepted_identity_edges_06.csv',index=False)
with gzip.GzipFile(filename=str(O/'point_witnesses_06.json.gz'),mode='wb',mtime=0) as z:z.write(json.dumps(proof,ensure_ascii=False,default=str).encode())
(O/'manifest_06.json').write_text(json.dumps({'status':'frozen_accepted_source_labelled_ownpoints_and_real_typed_identity_edges','points':3,'identity_edges':2,'sourcecounts_or_quality_modified':False,'input_pins':pins,'output_pins':{str(q):sha(q) for q in [O/'accepted_point_use_delta_06.csv',O/'accepted_identity_edges_06.csv',O/'point_witnesses_06.json.gz']}},ensure_ascii=False,indent=2)+'\n');print('accepted3points,2edges, map/currentKuzdistkm',dist)
