from pathlib import Path
import pandas as pd,json,hashlib,ast,re,xlrd,sys,gzip
R=Path('/workspace/russian-settlements-research');O=Path(__file__).parent;N=R/'research_rebuild/evidence/over500_north_20261009';S=Path('/dev/shm/settlements-stage71-20261009');sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from current_chain_state_20261007 import normalize,distance_km
from apply_unique_county_name_bridge_20261007 import county_key
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();f=pd.read_parquet(S/'applied_state_observations.parquet').fillna('');b=f.set_index('source_record_id');sel=Path('/workspace/settlements-delivery/continuation-consolidated-20261003/selected_observations.parquet');m=pd.read_parquet(sel).fillna('').set_index('source_record_id');ps=S/'applied_point_snapshot.parquet';p=pd.read_parquet(ps,columns=['target_source_record_id','latitude','longitude','coordinate_source_record_id','point_origin_file','point_origin_sha256','point_origin_locator','point_origin_kind','coordinate_admission_status','point_ledger_path']).fillna('').drop_duplicates('target_source_record_id').set_index('target_source_record_id').to_dict('index');pins={str(q):sha(q) for q in [S/'applied_state_observations.parquet',S/'applied_component_snapshot.csv.gz',sel,ps]};books={};checks={};rawpar={};fn=ast.unparse(next(x for x in ast.parse((N/'build_packet.py').read_text()).body if isinstance(x,ast.FunctionDef) and x.name=='check')).replace("actual = re.sub('ского$', 'ский', actual)","actual = re.sub('ского$', 'ский', actual); actual = re.sub('цкого$', 'цкий', actual)");exec(fn)
major='2002:048_4f024587eb_02c_Nizhegorod_obl_new.xls:11:3967';minor='2002:048_4f024587eb_02c_Nizhegorod_obl_new.xls:11:4094';mid='2010:014_5ca759eea0_5._20Nizheg_Kirov_202010.xls:Data Sheet:3224';cur='2021:data_allsettlements_anon_156_v20251217.parquet:parquet:75861';assert float(b.loc[minor,'population'])==0 and float(b.loc[major,'population'])==545;ox=check(major);rx=check(minor);mx=check(mid);cx=check(cur);assert all(x['literal_label_population_passed'] for x in [ox,rx,mx,cx]);bk=books[ox['source_file']];sh=bk.sheet_by_name('11');parmajor=sh.row_values(3965);parminor=sh.row_values(4087);assert 'Зименковский' in parmajor[0] and 'Успенский' in parminor[0]
# Two distinct immediate successors bind2010major to printed2002Zimenki centre; no population equality used.
pairs=[('2010:014_5ca759eea0_5._20Nizheg_Kirov_202010.xls:Data Sheet:3225','2002:048_4f024587eb_02c_Nizhegorod_obl_new.xls:11:3968'),('2010:014_5ca759eea0_5._20Nizheg_Kirov_202010.xls:Data Sheet:3226','2002:048_4f024587eb_02c_Nizhegorod_obl_new.xls:11:3969')];neigh=[]
for x,y in pairs:
 assert b.loc[x,'name_norm']==b.loc[y,'name_norm'];assert check(x)['literal_label_population_passed'] and check(y)['literal_label_population_passed'];neigh.extend([check(x),check(y)])
assert b.loc[pairs[0][0],'name_norm']!=b.loc[pairs[1][0],'name_norm'];before=sorted(f[f.root==b.loc[minor,'root']].source_record_id.tolist());assert before==sorted([minor,mid,cur]);assert b.loc[major,'root']!=b.loc[minor,'root'];after=[[minor],sorted([mid,cur])]
# Direct ownarticle publishedidentity/currentpoint is the major centre; duplicatedprivate2021OKATO field is NOT identityproof.
wiki=Path('/workspace/settlements-raw/data/raw/wikipedia_articles/batch_00824.json.gz');doc=json.load(gzip.open(wiki,'rt'));pgs=doc.get('payload',doc)['query']['pages'];pgs=list(pgs.values()) if isinstance(pgs,dict) else pgs;pg=next(x for x in pgs if x['title']=='Зименки (Шалдежский сельсовет)');tx=pg['revisions'][0]['slots']['main']['content'];assert '22437844008' in tx and 'Шалдежский сельсовет' in tx;cp=p[cur];assert cp['coordinate_admission_status'] in ['reviewed_rule_accepted','reviewed_extension_rule_accepted'];assert distance_km((float(cp['latitude']),float(cp['longitude'])),(56+49/60+54/3600,44+36/60+21/3600))<0.3;pins[str(wiki)]=sha(wiki)
reason='Wrong baseline71homonym links2002minor деревняЗименки0 under independently printedУспенский ruralcouncil to2010/2021 major site. Original2002major селоЗименки545 is separately printedЗименковский council centre; its two distinct immediate ownsuccessors Взвоз/Гавриловка exactly match original2010major ownrow3224 localsource sequence, while zero minor belongs separate sourceblock. Detach only wrong2002minor; retain independentadmitted2010→2021major pair. Reported2002selo→2010derevnya rolevariant explicit and unchanged, exact legaltypechange date unknown, not silently corrected. Native0 remains0. Private2021 duplicatedwrongOKATO ignored, not backfilled. Ownnamedcurrent article confirms independently own major-site coordinate.'
proof={'baseline_stage71_source_hash':sha(S/'applied_state_observations.parquet'),'expected_before_members':before,'after_partition':after,'native_major2002':ox,'native_minor2002':rx,'native_major2010':mx,'own_native_current2021':cx,'actual_raw_major_parish':{'row1based':3966,'rawcells':parmajor},'actual_raw_minor_parish':{'row1based':4088,'rawcells':parminor},'all_reopened_distinct_native_source_successors':neigh,'preserved_reported_roles':{'2002_major':b.loc[major,'settlement_type'],'2010_major':b.loc[mid,'settlement_type'],'2021_major':b.loc[cur,'settlement_type']},'old_minor_zero_preserved':True,'own_current_article':{'title':pg['title'],'pageid':pg['pageid'],'revid':pg['revisions'][0]['revid'],'source':str(wiki),'source_sha256':sha(wiki),'own_text':tx},'current_ownpoint':cp,'false_old_minor_point':p[minor],'reason':reason};proofpath=O/'Zimenki_false_homonym_sourceproof_07.json.gz'
with gzip.GzipFile(filename=str(proofpath),mode='wb',mtime=0) as z:z.write(json.dumps(proof,ensure_ascii=False,default=str).encode())
pd.DataFrame([dict(case='Zimenki_Uspensky_zero_minor_false_major_component',expected_before_members_JSON=json.dumps(before,ensure_ascii=False),after_partition_JSON=json.dumps(after,ensure_ascii=False),admission_status='reviewed_wrong_identity_component_partition_correction',source_binding_proof=str(proofpath),source_binding_proof_sha256=sha(proofpath),reason=reason,correction_phase='baseline71_before_all_North_batches')]).to_csv(O/'component_partition_correction_07.csv',index=False)
oldp=p[minor];ledge=Path(oldp['point_ledger_path']);assert ledge.is_file();pins[str(ledge)]=sha(ledge);pd.DataFrame([dict(target_source_record_id=minor,rejection_status='reviewed_rejected_coordinate_claim_only',old_latitude=oldp['latitude'],old_longitude=oldp['longitude'],origin_ledger=str(ledge),origin_ledger_sha256=sha(ledge),reason=reason,native_identity_or_population_rejected=False)]).to_csv(O/'accepted_point_rejection_delta_07.csv',index=False)
row={k:cp[k] for k in ['latitude','longitude','point_origin_file','point_origin_sha256','point_origin_locator','point_origin_kind']};row.update(target_source_record_id=major,coordinate_source_record_id=cur,coordinate_admission_status='reviewed_extension_rule_accepted',decision_status='checked_rule_accepted',admission_allowed=True,own_locality_point=True,recipient_point_assigned_to_child=False,source_sha256=ox['source_sha256'],source_locator=f"{ox['source_sheet']}:{ox['source_row']}",admission_rule=reason,point_temporal_interpretation='Independently sourcebound actual ownmajor point reused retrospectively by explicit continuity inference; no censusdaymeasurement or boundary equivalence.',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,native_population_quality_preserved=True);pd.DataFrame([row]).to_csv(O/'accepted_point_use_delta_07.csv',index=False)
pd.DataFrame([dict(from_source_record_id=major,to_source_record_id=mid,relation='same_place',decision_status='checked_rule_accepted',admission_rule=reason+' Checkedphysicalownsite continuity with explicit native reportedtypevariant; apply only AFTERexactbaseline partition, then no repeatedyear.',source_context_witness_file=str(proofpath),source_counts_changed=False,boundary_comparability_asserted=False)]).to_csv(O/'accepted_identity_edges_07.csv',index=False)
(O/'manifest_07.json').write_text(json.dumps({'status':'frozen_positive_source_homonym_partition_correction_and_ownpoint','component_partitions':1,'wrong_point_rejections':1,'points':1,'identity_edges':1,'sourcecounts_or_quality_modified':False,'zero_changed':False,'application_order':'baseline71partition BEFOREallnewedges; rejectwrongminorpoint; admitownmajorpoint/newedge','input_pins':pins,'output_pins':{str(q):sha(q) for q in [proofpath,O/'component_partition_correction_07.csv',O/'accepted_point_rejection_delta_07.csv',O/'accepted_point_use_delta_07.csv',O/'accepted_identity_edges_07.csv']}},ensure_ascii=False,indent=2)+'\n');print('partition1,rejection1,point1,edge1;0unchanged')
