from pathlib import Path
import pandas as pd,json,duckdb,gzip,hashlib
O=Path(__file__).parent;W=Path('/workspace/settlements-work/annual_physical_class_extension_20261008');raw=Path('/workspace/settlements-raw/data/interim/2021_tochno/data_allsettlements_anon_156_v20251217.parquet');obs=pd.read_csv(W/'observations.csv.gz',keep_default_na=False);bind=pd.read_csv(W/'current_bindings.csv.gz',keep_default_na=False);db=duckdb.connect(config={'threads':1});f=db.execute('select row_number() over() rn,object_level,object_name,oktmo,mun_upper,mun_lower,population from read_parquet(?)',[str(raw)]).fetchdf();db.close();f=f.set_index('rn');w=[]
for z in bind.to_dict('records'):
 sid=z['current_source_record_id'];own=f.loc[int(sid.rsplit(':',1)[1])];assert own.object_level=='Населенный пункт',sid;assert int(own.oktmo)==int(z['current_native_oktmo']);samecode=f[f.oktmo.astype(str).eq(str(own.oktmo))&f.object_level.eq('Населенный пункт')];assert len(samecode)==1
 # Preserve all original fullraw namesakes within the actual county, not selected-only rivals.
 name=str(own.object_name).split(' ',1)[-1].lower().replace('ё','е');rivals=f[f.mun_upper.eq(own.mun_upper)&f.object_name.astype(str).str.lower().str.replace('ё','е',regex=False).str.endswith(' '+name)&f.object_level.eq('Населенный пункт')]
 w.append({'QID':z['wikidata_qid'],'current_source_record_id':sid,'actual_native_2021_row_json':json.dumps(own.to_dict(),ensure_ascii=False),'all_actual_samecounty_literal_name_rivals_json':rivals.reset_index().to_json(orient='records',force_ascii=False),'binding_rule':'literal current own code unique in full original native roster; current typed NP retained; namesakes preserved; independent own point checked; no historical-boundary claim'})
assert obs.statement_guid.is_unique
for p in ['/workspace/settlements-work/annual_cached_own_native_history_20261008/v3/observations.csv.gz','/workspace/settlements-work/annual_cached_own_native_history_20261008/v4_2/observations.csv.gz']:assert not set(obs.statement_guid)&set(pd.read_csv(p).statement_guid)
for z in obs.to_dict('records'):
 p=Path(z['raw_file_path']);assert hashlib.sha256(p.read_bytes()).hexdigest()==z['raw_file_sha256'];d=json.loads(gzip.decompress(p.read_bytes()) if p.name.endswith('.gz') else p.read_bytes());st=next(a for a in d['entities'][z['wikidata_qid']]['claims']['P1082'] if a['id']==z['statement_guid']);assert st==json.loads(z['raw_statement_json']);assert z['observed_year'] not in [2002,2010,2021]
pd.DataFrame(w).to_csv(O/'actual_native_rival_witnesses.csv.gz',index=False,compression={'method':'gzip','mtime':0});r={'status':'PASS literal raw statements, unique GUIDs, prior exclusion, actual original native physical grain/current codes and full county rivals','observations':len(obs),'current_entities':len(bind),'raw_native_pin':{str(raw):hashlib.sha256(raw.read_bytes()).hexdigest()},'no_census_or_full3_credit':True};(O/'validation_receipt.json').write_text(json.dumps(r,indent=2)+'\n');print(json.dumps(r))
