from pathlib import Path
import sys,json,gzip,re
import duckdb,pandas as pd
O=Path(__file__).parent;E=O.parent;R=E.parent.parent;sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from current_chain_state_20261007 import sha,distance_km
A=O/'top4_all_resolved_article_revision_source.json.gz';Q=O/'top4_own_article_entities_source.json.gz';F=E/'main_axis_residual_registry_20261008/current2021_missing_ownpoints.csv.gz';RAW=Path('/workspace/settlements-raw/data/interim/2021_tochno/data_allsettlements_anon_156_v20251217.parquet');P=E/'temporal_residual_mass_20261008/SHARED_points_compact_stage61.parquet';a=json.loads(gzip.open(A,'rt').read());q=json.loads(gzip.open(Q,'rt').read());f=pd.read_csv(F,keep_default_na=False);c=duckdb.connect();r=c.execute('select row_number() over() rn,object_level,object_name,oktmo,region,mun_upper,mun_lower,population from read_parquet(?)',[str(RAW)]).fetchdf().set_index('rn');pp=c.execute('select * from read_parquet(?)',[str(P)]).fetchdf().set_index('source_record_id');c.close();cases=[(46904,'Барановка (Хостинский район)','Q3326723','currentP764_exactnative11digits_disambiguates_Lazarevsky_samecity_homonym'),(84701,'Михайловка (Михайловский сельсовет, Бугурусланский район)','Q18790595','exactnative_printed_Mikhailovsky_council_distinguishes_Polibinsky_samecounty_homonym'),(152489,'Мыза (Привокзальный территориальный округ)','Q23976550','ownliteral_infobox_identifier2_70701000478_disambiguates_otherMyza70701000523')];points=[];evidence=[]
for rn,title,qid,rule in cases:
 page=next(p for p in a['query']['pages'] if p['title']==title);rev=page['revisions'][0];text=rev['slots']['main']['content'];own=r.loc[rn].to_dict();z=f[f.source_record_id.str.endswith(':'+str(rn))].iloc[0].to_dict();assert own['object_level']=='Населенный пункт';assert own['object_name'].strip()==z['settlement_type']+' '+z['settlement_name'] or rn in [46904,84701]
 def num(key):
  v=re.findall(r'\|\s*'+key+r'\s*=\s*([+-]?[\d.]+)',text);assert len(v)<=1,(key,v);return float(v[0]) if v else 0
 lat=num('lat_deg')+num('lat_min')/60+num('lat_sec')/3600;lon=num('lon_deg')+num('lon_min')/60+num('lon_sec')/3600
 assert 41<=lat<=82 and 19<=lon<=180
 if rn==46904:assert '03726000126' in [v['mainsnak']['datavalue']['value'] for v in q['entities'][qid]['claims']['P764']];assert 'Хостинском районе' in text and 'Барановский сельский округ' in text
 if rn==84701:assert 'Михайловский сельсовет' in own['mun_lower'] and 'Михайловский сельсовет' in text and 'Бугурусланский район' in text and 'Оренбургская область' in text
 if rn==152489:assert re.search(r'цифровой идентификатор 2\s*=\s*70701000478',text)
 for sid in str(z['component_source_ids']).split('|'):
  if sid in pp.index:assert distance_km((lat,lon),(float(pp.loc[sid].latitude),float(pp.loc[sid].longitude)))<=5
 assert not ((pp.index.str.startswith('2021:')) & pd.to_numeric(pp.latitude).eq(lat) & pd.to_numeric(pp.longitude).eq(lon)).any()
 loc=f"pageid={page['pageid']};revisionid={rev['revid']};slots.main.content;NP+Russia_infobox.lat_deg/min/sec,lon_deg/min/sec";points.append({'target_source_record_id':z['source_record_id'],'latitude':lat,'longitude':lon,'coordinate_admission_status':'reviewed_extension_rule_accepted','coordinate_source_record_id':f"ruwiki:{page['pageid']}:{rev['revid']}",'point_origin_file':str(A),'point_origin_sha256':sha(A),'point_origin_locator':loc,'point_origin_kind':'own_named_physicalNP_ruWikipedia_revision_infobox_representative_point','coordinate_binding_rule':rule+';ownNP_status_name_region_county_and_explicit_rival_checked;own_infobox_coord_not_admin_map','point_use_inference':'modern_own_locality_representative_point;coordinate_measurement_date_unknown','historical_census_coordinate_asserted':False,'external_provider_ID_binding_asserted':False,'native2021_own_oktmo':str(own['oktmo'])})
 evidence.append({**z,'article_title':title,'article_url':'https://ru.wikipedia.org/wiki/'+title.replace(' ','_'),'article_pageid':page['pageid'],'article_revision_id':rev['revid'],'article_revision_timestamp':rev['timestamp'],'article_coordinate_literal_json':json.dumps({key:re.findall(r'\|\s*'+key+r'\s*=\s*([^|\n]+)',text) for key in ['lat_deg','lat_min','lat_sec','lon_deg','lon_min','lon_sec']},ensure_ascii=False),'article_infobox_excerpt':text[:text.find("'''",100)],'article_own_geography_excerpt':text[text.find("'''"):text.find('== История ==')],'native_primary_ownNP_context_json':json.dumps(own,ensure_ascii=False,default=str),'own_named_object_binding_rule':rule,'raw_native_source_file':str(RAW),'raw_native_source_sha256':sha(RAW),'raw_native_source_locator':'row1based='+str(rn),'latitude':lat,'longitude':lon,'point_origin_locator':loc,'excluded_rival_context':'Барановка Лазаревский03726000131 / Михайловка Полибинский53611446136 / Мыза Пролетарский70701000523; source bound own article distinguishes these','population_values_unchanged':True})
for n,d in [('accepted_top3_article_point_use_delta',points),('accepted_top3_article_source_bound_evidence',evidence)]:pd.DataFrame(d).to_csv(O/(n+'.csv.gz'),index=False,compression={'method':'gzip','mtime':0,'compresslevel':9})
r={'baseline_stage':61,'accepted_current_ownpoints':3,'known_population2021':sum(float(z['population']) for z in evidence),'source_population_and_graph_unchanged':True,'input_pins':{str(p):sha(p) for p in [A,Q,F,RAW,P,O/'accept_top3_articles.py']}};(O/'top3_article_acceptance_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n');print(json.dumps({k:v for k,v in r.items() if k!='input_pins'},ensure_ascii=False))
