from pathlib import Path
import sys,json,collections,ast
import pandas as pd
R=Path('/workspace/russian-settlements-research');sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from working_state_20261007 import load
from current_chain_state_20261007 import normalize,sha
from apply_unique_county_name_bridge_20261007 import county_key
O=Path(__file__).parent;E=O.parent;s=load(34);f=pd.read_csv(O/'disjoint_cached_claim_inventory.csv.gz',keep_default_na=False);old=s.obs[s.obs.census_year.eq(2002)&s.obs.is_additive_settlement_record.fillna(False)].copy();old['n']=old.name_norm.map(normalize);idx={k:g for k,g in old.groupby(['n','region_norm'])};cached=pd.read_csv(O/'cached_alias_or_code_native2002_candidates.csv.gz',keep_default_na=False);existing={sid:set(g.native2002_source_record_id) for sid,g in cached.groupby('current_source_record_id')};bind=pd.read_csv(E/'native_alias_remaining_mass_20261008/native_missing2002_alias_bindings/native_alias_potential.csv',keep_default_na=False);excluded=set(bind.trajectory_current_source_record_id)
source=E/'cross_county_independent_point_bridge_20261007/build_neutral_subset.py';tree=ast.parse(source.read_text());pairs=ast.literal_eval(next(x.value for x in tree.body if isinstance(x,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='pairs' for t in x.targets)));neutral={frozenset([county_key(a),county_key(b)]) for a,b in pairs.items()};rivals=[];routes=[]
for a in f.to_dict('records'):
 sid=a['current_source_record_id'];cur=s.by_id.loc[sid];cc=county_key(cur.district_raw);ids=set(existing.get(sid,set()))
 for name in [a['name'],a['native2010_name']]:ids.update(idx.get((normalize(name),a['region']),pd.DataFrame()).get('source_record_id',[]))
 allmatches=[]
 for oid in ids:
  b=s.by_id.loc[oid];bc=county_key(b.district_raw);years=s.years[s.uf.find(oid)];countyok=bool(bc) and (cc==bc or frozenset([cc,bc]) in neutral);exact=normalize(b.name_norm) in [normalize(cur.name_norm),normalize(a['native2010_name'])];ownpoint=oid in s.point_rows;proof='exact_native2010_or2021_label' if exact else 'cached_own_alias_or_code';z={'current_source_record_id':sid,'name':a['name'],'region':a['region'],'maximum_observed_population_weight':a['maximum_observed_population_weight'],'excluded_nativealias_owned':sid in excluded,'candidate_native2002_source_record_id':oid,'native2002_name':b.settlement_name,'native2002_type':b.settlement_type,'native2002_county':b.district_raw,'native2002_population':b.population,'native2002_source_file':b.source_file,'native2002_source_locator':b.source_locator,'native2002_component_years':json.dumps(sorted(years)),'native2002_unclaimed_by2021':2021 not in years,'native2002_missing2002_pair_graph_compatible':not ({2010,2021}&years),'native2002_has_own_point':ownpoint,'printed_county_same_or_neutral':countyok,'candidate_route':proof,'candidate_only':True};allmatches.append(z);rivals.append(z)
 compatible=[z for z in allmatches if z['native2002_missing2002_pair_graph_compatible']];countypositive=[z for z in compatible if z['printed_county_same_or_neutral']]
 route='native_alias_agent_owned_excluded' if sid in excluded else 'unique_unclaimed_native2002_printed_county_candidate' if len(countypositive)==1 else 'unclaimed_native2002_county_or_competitor_resolution' if compatible else 'native2002_namesakes_attached_elsewhere' if allmatches else 'no_native2002_literal_alias_or_code_candidate'
 routes.append({**a,'excluded_nativealias_owned':sid in excluded,'all_native2002_candidates':len(allmatches),'graph_compatible_native2002_candidates':len(compatible),'county_positive_native2002_candidates':len(countypositive),'native_source_route':route,'native2002_source_IDs_json':json.dumps(sorted(ids))})
x=pd.DataFrame(routes);m=pd.DataFrame(rivals);x.to_csv(O/'disjoint_native_source_routes.csv.gz',index=False,compression={'method':'gzip','mtime':0});m.to_csv(O/'all_native2002_label_alias_code_competitors.csv.gz',index=False,compression={'method':'gzip','mtime':0});x[~x.excluded_nativealias_owned].head(100).to_csv(O/'final_disjoint_top100.csv',index=False);summary=x.groupby('native_source_route').agg(components=('current_source_record_id','size'),population2010=('population2010','sum'),population2021=('population2021','sum'),max_weight=('maximum_observed_population_weight','sum')).sort_values('max_weight',ascending=False);summary.to_csv(O/'native_source_routes_summary.csv');r=json.load(open(O/'receipt.json'));r['native_route_classification']=summary.reset_index().to_dict('records');r['nativealias_owned_excluded_currentIDs']=int(x.excluded_nativealias_owned.sum());r['final_disjoint_components_after_nativealias_owner_exclusion']=int((~x.excluded_nativealias_owned).sum());r['final_disjoint_population2010']=int(x.loc[~x.excluded_nativealias_owned,'population2010'].sum());r['final_disjoint_population2021']=int(x.loc[~x.excluded_nativealias_owned,'population2021'].sum());r['source_context_candidates_no_admission_asserted']=True;(O/'receipt.json').write_text(json.dumps(r,indent=2,ensure_ascii=False));print(summary.to_string())
