from pathlib import Path
import pandas as pd,json,gzip,hashlib,xlrd
O=Path(__file__).parent;sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();d=pd.read_parquet('/dev/shm/over500-moscow-complete-batch2.parquet');sid='2002:1_TOM_01_04.xls:0:1207';r=d[d.source_record_id.eq(sid)].iloc[0];receiver=d[d.source_record_id.str.endswith(':68258')].iloc[0];f=O/'remaining_own_articles.json.gz';pg=json.load(gzip.open(f,'rt'))['query']['pages']['8776154'];txt=pg['revisions'][0]['slots']['main']['*'];assert'22.07.2004 N 145-ПГ'in txt and'западную часть'in txt;co=pg['coordinates'][0];scope='over500_moscow_event_8776154';loc=f'pageid=8776154;revision={pg["revisions"][0]["revid"]}';date='2004-07-22';raw=Path('/workspace/settlements-raw/data/raw/2002_official_tom1/1_TOM_01_04.xls');sh=xlrd.open_workbook(str(raw)).sheet_by_index(0);vals=sh.row_values(1206);assert any(str(x).replace('.0','')=='617'for x in vals)
p=dict(scope_id=scope,target_source_record_id=sid,source_record_id=sid,latitude=co['lat'],longitude=co['lon'],coordinate_admission_status='reviewed_extension_rule_accepted',decision_status='reviewed_rule_accepted',coordinate_source_record_id='Wikipedia:page8776154',source_sha256=sha(f),source_locator=loc+':coordinates[0]',point_origin_file=str(f),point_origin_sha256=sha(f),point_origin_locator=loc+':coordinates[0]',point_origin_kind='own_named_former_NP_Wikipedia_physical_reference_point',own_locality_point=True,recipient_point_assigned_to_child=False,point_temporal_interpretation='Ownformer dachaPGT westernAlabino physicalreferencepoint retrospectively; not receivingwholevillage centroid',direct_historical_coordinate_measurement=False,provider_binding_asserted=False,boundary_comparability_asserted=False)
pts=pd.read_csv(O/'accepted_point_use_delta.csv');pd.concat([pts,pd.DataFrame([p])],ignore_index=True).to_csv(O/'accepted_point_use_delta.csv',index=False);pd.DataFrame([p]).to_csv(O/'accepted_former_locality_own_points.csv',index=False)
pd.DataFrame([dict(scope_id=scope,former_locality=pg['title'],recipient_city='Алабино',receiving_NP_type='деревня',event_date=date,date_precision='day',relation='merged_into',same_place=False,event_source_file=str(f),event_source_sha256=sha(f),event_source_locator=loc,event_source_quality='secondary_literal_dated_former_NP_inclusion_own_article',event_date_role='Cited act date; exact operative-date not asserted',decision_status='accepted_secondary_article_included_in',primary_law_source_reopened=False,boundary_comparability='UNKNOWN',roster_closed=False,sum_city_equals_children_asserted=False)]).to_csv(O/'accepted_inclusion_events.csv',index=False)
pd.DataFrame([dict(scope_id=scope,from_source_record_id=sid,to_source_record_id=receiver.source_record_id,relation='merged_into',event_date=date,date_precision='day',event_source_file=str(f),event_source_sha256=sha(f),event_source_locator=loc,same_place=False,graph_union_allowed=False,whole_city_roster_closure_asserted=False)]).to_csv(O/'accepted_included_in_event_edges.csv',index=False)
pd.DataFrame([dict(scope_id=scope,place='Алабино (дачный посёлок)',year=2002,source_record_id=sid,native_population=617,native_population_quality=r.population_value_quality,latitude=co['lat'],longitude=co['lon'],own_point=True,recipient_city='Алабино',receiving_NP_actual_type='деревня',event_date=date,event_date_precision='day',event_relation='merged_into',same_place_identity_asserted=False,receiving_city_2021_source_record_id=receiver.source_record_id,receiving_city_2021_count_context_only=receiver.population,child_2021_population_assigned=False,is_additive_to_original_final_mixed_census_axis=False,ordinary_three_census_same_place_claim=False,native_values_quality_preserved=True)]).to_csv(O/'accepted_historical_observations.csv',index=False)
pd.DataFrame([dict(scope_id=scope,source_record_id=sid,year=2002,source_population=617,new_population_on_separate_transformation_path_axis=617,own_historical_point_verified=True,receiving_city_actual_available_census_context_verified=True,is_additive_to_original_final_mixed_census_axis=False,ordinary_three_census_same_place_claim=False)]).to_csv(O/'accepted_direct_event_native_credit_union.csv',index=False)
pd.DataFrame([dict(scope_id=scope,place=pg['title'],year=y,status='actual_separate_own_published_observation'if y==2002 else'ceased_as_separate_locality_merged_into_receiver_before_census',own_population=617 if y==2002 else'',unknown_is_zero=False,recipient_population_assigned_to_child=False,boundary_comparability='UNKNOWN')for y in [2002,2010,2021]]).to_csv(O/'accepted_available_year_statuses.csv',index=False)
proof=dict(scope_id=scope,source_record_id=sid,literal_native_row=vals,native_source_path=str(raw),native_source_sha256=sha(raw),native_locator=sh.name+':row1207',literal_own_article=txt,own_article_path=str(f),own_article_sha256=sha(f),receiver_actual_observations=d[d.after_root.eq(receiver.after_root)][['source_record_id','census_year','population','population_value_quality']].to_dict('records'),new_ordinary_union=False);(O/'Alabino_ownformer_point_and_event_sourceproof.json').write_text(json.dumps(proof,ensure_ascii=False,indent=2,default=str));print('ownformerpoint1 datedmerger1 actualhistoricalleaf1; noUFunion')
