from pathlib import Path
import pandas as pd,json,gzip,hashlib,xlrd,duckdb
O=Path(__file__).parent;B=O.parent;sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();d=pd.read_parquet('/dev/shm/over500-moscow-complete-batch2.parquet');sel=[]
for y,n in[(2002,4920),(2010,12416)]:
 z=d[d.census_year.eq(y)&d.source_record_id.str.endswith(':'+str(n))];assert len(z)==1;sel.append(z.iloc[0])
a,b=sel;assert a.population==329 and b.population==628;assert a.derived_oldcounty==b.derived_oldcounty=='Раменский район';rivals=d[d.census_year.eq(2010)&d.name_norm.eq('захарово')&d.derived_oldcounty.eq('Раменский район')];assert len(rivals)==2 and set(rivals.population)=={628,69};pgs={}
for f in list(B.glob('own_wikipedia_batch*.json.gz'))+list((B/'batch2_lifecycle_homonyms').glob('own_wikipedia_batch*.json.gz')):
 for p in json.load(gzip.open(f,'rt'))['query']['pages'].values():
  if 'revisions'in p:pgs[p['title']]=(p,f)
p,f=pgs['Захарово (деревня, Раменский городской округ)'];q,qf=pgs['Захарово (село, Раменский городской округ)'];txt=p['revisions'][0]['slots']['main']['*'];qt=q['revisions'][0]['slots']['main']['*'];assert'Дементьевского сельского округа'in txt and'46248816004'in txt;assert'Рыболовского сельского округа'in qt and'46248870023'in qt;raw=Path('/workspace/settlements-raw/data/raw/2002/010_3e630cc803_02c_Moskovskaya-oblast.xls');sh=xlrd.open_workbook(str(raw)).sheet_by_index(0);assert'Дементьевский'in str(sh.cell_value(4915,1));c=duckdb.connect();cf=Path('/workspace/settlements-work/sources/raw_okato_2009_verification_v1/raw_classifier.parquet');cl=c.execute('select *from read_parquet(?)where historical_okato in(?,?,?,?)',[str(cf),'46248816','46248816004','46248870','46248870023']).fetchdf();assert len(cl)==4
proof=dict(case='Zakharovo_Dementyevsky_Kratovo_native2002_2010_only',own_2002_UID=a.source_record_id,own_2010_UID=b.source_record_id,own_article_path=str(f),own_article_sha256=sha(f),own_article_literal=txt,counterpart_article_path=str(qf),counterpart_article_sha256=sha(qf),counterpart_article_literal=qt,own_population_template_path=str(O/'population_3.json.gz'),own_population_template_sha256=sha(O/'population_3.json.gz'),counterpart_population_template_path=str(O/'population_2.json.gz'),counterpart_population_template_sha256=sha(O/'population_2.json.gz'),own_template_counts={'2002':329,'2010':628},counterpart_template_counts={'2002':51,'2010':66},actual_counterpart_native2010=69,secondary_exact_count_equality_claimed=False,source2002_file=str(raw),source2002_sha256=sha(raw),literal_own_row=sh.row_values(4919),literal_own_subcounty_heading=sh.row_values(4915),all_county2010_rivals=rivals[['source_record_id','population','population_value_quality']].to_dict('records'),classifier_path=str(cf),classifier_sha256=sha(cf),classifier_records=cl.to_dict('records'),modern2021_link_deliberately_unasserted_reason='Both2021nativehomonyms have duplicateDadataFIAS and point; independent actualnativecode/geography binding is unresolved; oldpair accepted independently',all_native_values_and_quality_preserved=True)
proofpath=O/'Zakharovo_positive_two_article_oldpair_sourceproof.json';proofpath.write_text(json.dumps(proof,ensure_ascii=False,indent=2,default=str));loc=f'pageid={p["pageid"]};revision={p["revisions"][0]["revid"]}';co=p['coordinates'][0];edges=pd.read_csv(O/'accepted_identity_edge_delta.csv');new=dict(from_source_record_id=a.source_record_id,to_source_record_id=b.source_record_id,relation='same_place',decision_status='checked_rule_accepted',case=proof['case'],admission_rule='Literal original2002subcounty and ownhistoricalcode plus ownqualified article; BOTH countyhomonym ownarticles distinguishDementyevsky329/628 versusRybolovsky51/66; rawsecondary2010rivals628/69 kept unchanged; no modern2021 binding asserted',source_binding_proof=str(proofpath),population_boundary_comparability_asserted=False,municipal_event_date='UNKNOWN');pd.concat([edges,pd.DataFrame([new])],ignore_index=True).to_csv(O/'accepted_identity_edge_delta.csv',index=False)
pts=pd.read_csv(O/'accepted_point_use_delta.csv');newpts=[dict(target_source_record_id=r.source_record_id,latitude=co['lat'],longitude=co['lon'],coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_source_record_id='Wikipedia:page'+str(p['pageid']),source_sha256=sha(f),source_locator=loc+':coordinates[0]',point_origin_file=str(f),point_origin_sha256=sha(f),point_origin_locator=loc+':coordinates[0]',point_origin_kind='own_Wikipedia_qualified_native_locality_representative_point',case=proof['case'],coordinate_binding_rule='OriginalnativeDemetyevskysubcounty ownhistoricalcode+twoownhomonymarticles; modernproviderduplicatepoint/codebinding notused',point_use_inference='own_modern_representative_point_on_source_bound_native_identity',population_boundary_comparability_asserted=False,historical_census_coordinate_asserted=False)for r in sel];pd.concat([pts,pd.DataFrame(newpts)],ignore_index=True).to_csv(O/'accepted_point_use_delta.csv',index=False);print('oldpair identity1 ownpoints2; modern2021 notjoined')
