from pathlib import Path
import pandas as pd,json,gzip,hashlib,xlrd
O=Path(__file__).parent;B=O.parent;sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();d=pd.read_parquet('/dev/shm/over500-moscow-complete-batch2.parquet');p=pd.read_parquet('/dev/shm/over500-moscow-points.parquet').set_index('target_source_record_id')
def sid(y,n):
 z=d[d.census_year.eq(y)&d.source_record_id.str.endswith(':'+str(n))];assert len(z)==1;return z.iloc[0]
a,b,c=sid(2002,370),sid(2010,8375),sid(2021,65719);wrong=sid(2021,68495);root=a.after_root;members=d[d.after_root.eq(root)];assert len(members)==3 and set(members.census_year)=={2002,2010,2021};nog=members[members.census_year.ne(2002)];assert nog.derived_oldcounty.eq('Ногинский район').all();assert all(z.derived_oldcounty=='Воскресенский район'for z in[a,b,c]);f=B/'own_wikipedia_batch2.json.gz';pg=next(x for x in json.load(gzip.open(f,'rt'))['query']['pages'].values()if x.get('title')=='Исаково (городской округ Воскресенск)');txt=pg['revisions'][0]['slots']['main']['*'];assert'Виноградовского сельского округа'in txt and'46206810004'in txt and'398 человек'in txt;co=pg['coordinates'][0];loc=f'pageid={pg["pageid"]};revision={pg["revisions"][0]["revid"]}'
raw=Path('/workspace/settlements-raw/data/raw/2002/010_3e630cc803_02c_Moskovskaya-oblast.xls');sh=xlrd.open_workbook(str(raw)).sheet_by_index(0);head=next((i+1,sh.cell_value(i,1))for i in range(368,-1,-1)if'сельский округ'in str(sh.cell_value(i,1)));assert'Виноградовский'in head[1];assert str(sh.cell_value(369,2))=="398"
proof=dict(case='Isakovo_Voskresensk_false_Noginsk_component',actual_before_members=members[['source_record_id','census_year','derived_oldcounty','population']].to_dict('records'),own_article_path=str(f),own_article_sha256=sha(f),own_article_locator=loc,own_article_literal=txt,original2002_source_path=str(raw),original2002_source_sha256=sha(raw),literal_row370=sh.row_values(369),literal_original_subcounty_heading=head,independent_county_inventory=str(B.parent/'over1000_moscow_20261009/native_all_with_independent_county.csv.gz'),independent_county_inventory_sha256=sha(B.parent/'over1000_moscow_20261009/native_all_with_independent_county.csv.gz'),native_counts_unchanged=True,prior_valid_Noginsk2010_2021_pair_retained=True,before_snapshot_scope='working_stage71_after_frozen_Moscow_batch1_and_batch2',Noginsk2010_2021_pair_source=str(B/'accepted_identity_edge_delta.csv'),Noginsk2010_2021_pair_source_sha256=sha(B/'accepted_identity_edge_delta.csv'),Noginsk2010_2021_pair_case='moscow_exact_county_68495',required_integration_order='Apply batch1 and batch2, then exact3UID partition, then batch3 edges')
pf=O/'Isakovo_false_crosscounty_sourceproof.json';pf.write_text(json.dumps(proof,ensure_ascii=False,indent=2,default=str));reason='Literal original2002 Voskresensk/Vinogradovsky sourcehierarchy and ownqualified article historicalcode46206810004 bind native398 row370 to Voskresensk; old Noginsk point and sourceidentity are wrong homonym. Preserve independentNoginsk2010→2021 component, then connect actualVoskresensk02→10→21.'
ef=B.parent/'main_axis_residual_application63_20261008/accepted_identity_edge_delta.csv.gz';e=pd.read_csv(ef);hit=e[e.from_source_record_id.eq(a.source_record_id)&e.to_source_record_id.eq(wrong.source_record_id)];assert len(hit)==1;hit.to_csv(O/'Isakovo_actual_false_baseline_edge_claim.csv',index=False)
pd.DataFrame([dict(from_source_record_id=a.source_record_id,to_source_record_id=wrong.source_record_id,relation='same_place',rejection_status='reviewed_rejected_false_homonym_native_identity_edge',origin_edge_ledger=str(ef),origin_edge_ledger_sha256=sha(ef),reason=reason,requires_remove_accepted_pair_from_earlier_stage_ledger=True,native_population_values_retained=True)]).to_csv(O/'accepted_identity_edge_rejection_delta.csv',index=False)
pd.DataFrame([dict(case=proof['case'],expected_before_members_JSON=json.dumps(sorted(members.source_record_id),ensure_ascii=False),after_partition_JSON=json.dumps([[a.source_record_id],sorted(nog.source_record_id)],ensure_ascii=False),admission_status='reviewed_wrong_identity_component_partition_correction',source_binding_proof=str(pf),source_binding_proof_sha256=sha(pf),reason=reason)]).to_csv(O/'component_partition_correction.csv',index=False)
cp=p.loc[a.source_record_id];origin=Path(cp.point_ledger_path);pd.DataFrame([dict(target_source_record_id=a.source_record_id,rejection_status='reviewed_rejected_coordinate_claim_only',old_latitude=cp.latitude,old_longitude=cp.longitude,origin_ledger=str(origin),origin_ledger_sha256=sha(origin),reason=reason,native_identity_or_population_rejected=False)]).to_csv(O/'accepted_point_rejection_delta.csv',index=False)
pts=[];edges=[]
for z in[a,b]:
 pts.append(dict(target_source_record_id=z.source_record_id,latitude=co['lat'],longitude=co['lon'],coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_source_record_id='Wikipedia:page'+str(pg['pageid']),source_sha256=sha(f),source_locator=loc+':coordinates[0]',point_origin_file=str(f),point_origin_sha256=sha(f),point_origin_locator=loc+':coordinates[0]',point_origin_kind='own_Wikipedia_qualified_native_locality_representative_point',case=proof['case'],coordinate_binding_rule=reason,point_use_inference='own_modern_representative_point_on_source_bound_native_identity',population_boundary_comparability_asserted=False,historical_census_coordinate_asserted=False))
 edges.append(dict(from_source_record_id=z.source_record_id,to_source_record_id=c.source_record_id,relation='same_place',decision_status='checked_rule_accepted',case=proof['case'],admission_rule='Exact ownnative name/type independently sourcecounty unique peryear, original2002ownsubcounty and ownarticle historicalcode; correction must precede new joins',source_binding_proof=str(pf),population_boundary_comparability_asserted=False,municipal_event_date='UNKNOWN'))
pd.DataFrame(pts).to_csv(O/'accepted_point_use_delta.csv',index=False);pd.DataFrame(edges).to_csv(O/'accepted_identity_edge_delta.csv',index=False);print('exactpartition1, falsepair1, pointreject1, ownpoints2, identityedges2')
