from pathlib import Path
import pandas as pd,json,re,hashlib,xlrd,ast,subprocess
E=Path(__file__).resolve().parent;B=E.parents[1];P=E/'build_corrected_cell_role_claims.py';tree=ast.parse(P.read_text());nodes=[n for n in tree.body if isinstance(n,ast.FunctionDef)and n.name in ['norm','key','classify','county']or isinstance(n,ast.Assign)and any(isinstance(t,ast.Name)and t.id in ['T','pat']for t in n.targets)];ns={'re':re};exec(compile(ast.Module(body=nodes,type_ignores=[]),str(P),'exec'),ns);norm,key,classify,county=[ns[n]for n in ['norm','key','classify','county']];sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();raw=Path('/workspace/settlements-raw/data/raw/2010/005_888282bccc_13._20Краснодарский_край_2010.xls');sh=xlrd.open_workbook(raw).sheet_by_name('КК');A=E/'329_new_all_hierarchy_heading_candidates_unreviewed.json';candidates=[r for r in json.load(open(A))if r['name']!='Южный'];assert len(candidates)==8;S=B/'main_axis_residual_application65_20261008/applied_state_observations.parquet';s=pd.read_parquet(S,columns=['source_record_id','census_year','settlement_name','settlement_type','region_norm','population','population_value_quality']);sd=s.set_index('source_record_id');REF=Path('/workspace/settlements-work/continuation_20261003/population2010/tom1_table5_extraction/official_2010_table5_reference.parquet');f=pd.read_parquet(REF);f=f[f.row_kind.eq('settlement')].copy();f['key']=f.apply(lambda r:key(r.settlement_type,r.settlement_name),axis=1);fd=f.set_index('reference_id');PDF=Path('/workspace/settlements-raw/data/raw/2010_official_tom1/tom-1-chislennost-i-razmeshchenie-naseleniya.pdf');pages=subprocess.check_output(['pdftotext','-layout',str(PDF),'-']).decode().split('\f');C=B/'main_axis_residual_application65_20261008/applied_primary_credited_UID_roster.csv.gz';cr=pd.read_csv(C,usecols=['source_record_id','entity_uid'],keep_default_na=False).set_index('source_record_id').to_dict('index');ready=[];witness=[]
for r in candidates:
 sid=r['source_record_id'];old=sd.loc[sid];p=fd.loc[r['official']['reference_id']];rn=int(sid.split(':')[-1]);v=sh.row_values(rn-1);k=key(old.settlement_type,old.settlement_name);q=[x for x in classify(v)if x['key']==k];assert len(q)==1;q=q[0];pc=county(p.district_raw);assert county(v[2])==pc;assert v[4]==old.population;assert q['caption_col']==3;competitors=[]
 for z in r['new_rival_headings']:
  zr=int(z['source_record_id'].split(':')[-1]);vv=sh.row_values(zr-1);a=z['new_all_actual_hierarchy_header'];assert a['source_row']==zr and a['source_column_zero_based']==2;assert county(vv[2])==a['normalized_county'];competitors.append(dict(source_record_id=z['source_record_id'],source_row=zr,literal_county=vv[2],raw_prefix_cells=vv[:9]))
 rawmatches=[]
 for i in range(sh.nrows):
  vv=sh.row_values(i)
  if len(vv)>3 and isinstance(vv[2],str)and county(vv[2])==pc:
   if any(z['key']==k for z in classify(vv)):rawmatches.append(i+1)
 assert rawmatches==[rn];ff=f[f.region_key.eq('краснодарский')&f.key.map(lambda x:x==k)&f.district_raw.map(lambda x:county(x)if pd.notna(x)else '').eq(pc)];assert len(ff)==1;assert sid in cr
 page=int(p.pdf_page);ns3=[str(int(p[x]))for x in ['population','men','women']];lines=pages[page-1].splitlines();hits=[]
 for i,line in enumerate(lines):
  nn=re.findall(r'\d+',line)
  if any(nn[j:j+3]==ns3 for j in range(len(nn)-2))and norm(p.settlement_name)in norm(' '.join(lines[max(0,i-2):i+1])):hits.append(' | '.join(lines[max(0,i-2):i+1]))
 assert hits and p.population==p.men+p.women
 ready.append(dict(old_source_record_id=sid,region='краснодарский',old_population=int(old.population),old_quality=old.population_value_quality,old_source_file='data/raw/2010/'+raw.name,old_source_sheet='КК',old_source_row=rn,raw_old_NP_caption=q['caption'],raw_type_cell_or_prefix=q['type_raw'],raw_name_cell_or_caption=q['name_raw'],raw_population_cell_column_zero_based=4,raw_population_cell=v[4],old_source_sha256=sha(raw),actual_printed_county_cells_json=json.dumps([dict(source_row=rn,column_zero_based=2,literal_county=v[2])],ensure_ascii=False),official_source_record_id=p.name,official_population=int(p.population),official_men=int(p.men),official_women=int(p.women),official_name=p.settlement_name,official_type=p.settlement_type,official_district=p.district_raw,official_source_path=str(PDF),official_source_sha256=sha(PDF),official_page=page,official_line_start=int(p.text_line_start),official_line_end=int(p.text_line_end),delta=int(p.population-old.population),status='ready_positive_literal_county_roster_context',context_method='county_printed_directly_in_same_rawrow_column2_for_target_and_ALL_regional_typed_rivals_fullrawcountykey_and_officialcountykey_unique',regional_rivals_json=json.dumps(competitors,ensure_ascii=False),raw_full_county_NP_competitors=1,official_full_county_typed_competitors=1,selected_full_region_competitors=len(competitors),already_primary_UID_credited_post65=True,existing_entity_uid_post65=cr[sid]['entity_uid'],old_population_effective_prior=int(old.population),independent_count_readback=True,independent_poppler_lines=hits[0],population_used_for_binding_context=False,source_grade='direct_official_primary_2010_census_Table5',census_year=2010,census_reference_date='2010-10-14',official_publication_date='',new_identity_or_point_assertions=False,selection_applied=False));witness.append(dict(source_record_id=sid,all_typed_rival_direct_county_rows=competitors,fullraw_countytyped_competitor_rows=rawmatches,raw_target=v[:12]))
d=pd.DataFrame(ready);assert d.old_source_record_id.is_unique and len(d)==8 and d.delta.sum()==5;prior=set()
for path in [B/'next_overlay_application_20261008/normalized_cumulative_claims.csv.gz',B/'residual_source_followup_20261008/accepted_county_bound_primary2010_addon_8.csv.gz',B/'residual_source_followup_20261008/accepted_all_regions_county_bound_primary2010_addon_127.csv.gz',E/'corrected_cell_role_ready_primary2010_claims.csv.gz']:prior.update(pd.read_csv(path,usecols=['old_source_record_id']).old_source_record_id)
assert len(prior)==1953 and not set(d.old_source_record_id)&prior;out=E/'accepted_direct_county_Krasnodar8_primary2010_addon.csv.gz';assert not out.exists();d.to_csv(out,index=False);w=E/'direct_county_Krasnodar8_raw_readback.json';w.write_text(json.dumps(witness,ensure_ascii=False,indent=2));receipt={'status':'root_reviewed_direct_on_row_county_source8_frozen_not_applied','claims':8,'population_delta':5,'old_protected_population_sum':int(d.old_population.sum()),'new_official_primary_population_sum':int(d.official_population.sum()),'all8_actual65_primaryUID_credited':True,'no_prior1953_SID_or_official_count_reassignment':True,'no_county_forwardfill_used_any_target_or_rival':True,'all_counts_P_equals_MplusF_and_Poppler_independent_readback':True,'raw_scope':'single_region_Krasnodar workbook ALL NP rows, sourceactualcountycol2/typecaptioncol3/countcol4','South_Yuzhny_plus3_held_unbounded_cityward_rivals':True,'cumulative_if1961_applied':{'claims':1961,'delta':173992,'selected_ordinary2010population':142537016,'national_control':142856536,'source_control_deficit':319520},'input_pins':{str(p):sha(p)for p in [S,C,REF,PDF,raw,A]},'output_pins':{out.name:sha(out),w.name:sha(w)},'code_sha256':sha(Path(__file__))};rp=E/'direct_county_Krasnodar8_frozen_receipt.json';rp.write_text(json.dumps(receipt,ensure_ascii=False,indent=2));print(json.dumps({'claim_sha':sha(out),'receipt_sha':sha(rp),'old_pop':int(d.old_population.sum()),'new_pop':int(d.official_population.sum())},indent=2))
