from pathlib import Path
import pandas as pd,xlrd,re,json,hashlib,ast,collections
E=Path(__file__).resolve().parent;B=E.parents[1];P=E/'build_corrected_cell_role_claims.py';tree=ast.parse(P.read_text());nodes=[n for n in tree.body if isinstance(n,ast.FunctionDef)and n.name in ['norm','key','classify','county']or isinstance(n,ast.Assign)and any(isinstance(t,ast.Name)and t.id in ['T','pat']for t in n.targets)];ns={'re':re};exec(compile(ast.Module(body=nodes,type_ignores=[]),str(P),'exec'),ns);norm,key,classify,county=[ns[n]for n in ['norm','key','classify','county']];sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();audit=pd.read_csv(E/'audited430_exclusive_official_binding_and_actual_county.csv.gz',keep_default_na=False);h=audit[audit.status.eq('held_eligible_unbound_official_county_needs_unique_raw_county_context')];s=pd.read_parquet(B/'main_axis_residual_application65_20261008/applied_state_observations.parquet',columns=['source_record_id','census_year','region_norm','settlement_name','settlement_type']);s=s[s.census_year.eq(2010)];o=pd.read_parquet('/workspace/settlements-delivery/continuation-consolidated-20261003/selected_observations.parquet',columns=['source_record_id','source_file','source_sheet','source_row']);s=s.merge(o,on='source_record_id',validate='one_to_one');target=s[s.source_record_id.isin(h.source_record_id)];F=Path('/workspace/settlements-work/continuation_20261003/population2010/tom1_table5_extraction/official_2010_table5_reference.parquet');f=pd.read_parquet(F);out=[];witness=[];pins={str(F):sha(F)}
for file,fg in target.groupby('source_file'):
 p=Path('/workspace/settlements-raw')/file;pins[str(p)]=sha(p);book=xlrd.open_workbook(p,on_demand=True)
 for (sheet,reg),tg in fg.groupby(['source_sheet','region_norm']):
  sh=book.sheet_by_name(sheet);allregional=s[s.source_file.eq(file)&s.source_sheet.eq(sheet)&s.region_norm.eq(reg)];tokens={sh.row_values(int(i)-1)[2]for i in allregional.source_row};known={county(x)for x in f[f.region_key.eq(reg)].district_raw if pd.notna(x)};known|={county(x)for x in f[f.region_key.eq(reg)].label_raw if pd.notna(x)and re.search(r'район|округ|улус|кожуун',str(x),re.I)};headers=[];seen=set()
  for i in range(sh.nrows):
   v=sh.row_values(i)
   if len(v)<3 or v[2]not in tokens:continue
   labels=classify(v);limit=min([q['type_col']for q in labels],default=8)
   for j,x in enumerate(v[:limit]):
    if not isinstance(x,str)or not x.strip()or classify([x]):continue
    n=county(x);explicit=bool(re.search(r'\b(?:район|округ|кожуун|улус|волость|участок)\b',x,re.I));proper=n in known and n and j>=3
    if (proper or explicit) and n and (i+1,j,x)not in seen:
     headers.append({'source_row':i+1,'source_column_zero_based':j,'literal_caption':x,'normalized_county':n,'recognized_from_all_official_hierarchy_rows':proper,'explicit_admin_role':explicit,'raw_prefix_cells':v[:10]});seen.add((i+1,j,x))
  out.append({'source_file':file,'sheet':sheet,'region':reg,'target_rows':len(tg),'full_selected_region_rows':len(allregional),'actual_distinct_heading_captions':len(set(q['literal_caption']for q in headers)),'actual_heading_rows':len(set(q['source_row']for q in headers)),'earliest_target_row':int(tg.source_row.min()),'latest_target_row':int(tg.source_row.max()),'heading_captions_json':json.dumps(sorted(set(q['literal_caption']for q in headers)),ensure_ascii=False)})
  witness.append({'source_file':file,'sheet':sheet,'region':reg,'source_sha256':pins[str(p)],'target_source_ids':tg.source_record_id.tolist(),'all_actual_printed_heading_rows':headers})
 book.release_resources()
d=pd.DataFrame(out);d.to_csv(E/'329_raw_printed_district_heading_availability.csv',index=False);(E/'329_raw_printed_district_heading_witnesses.json.gz').write_bytes(__import__('gzip').compress(json.dumps(witness,ensure_ascii=False,indent=2).encode()));r={'status':'actual329_source_heading_inventory_no_admission','input_pins':pins,'target_rows':len(target),'region_source_groups':len(d),'groups_with_no_printed_headings':int(d.actual_heading_rows.eq(0).sum()),'groups_with_only_one_distinct_heading':int(d.actual_distinct_heading_captions.eq(1).sum()),'all_official_hierarchy_rowkind_counties_used_not_only_largeNPcounties':True,'no_blind_header_carry_claim_admitted':True,'output_pins':{p.name:sha(p)for p in [E/'329_raw_printed_district_heading_availability.csv',E/'329_raw_printed_district_heading_witnesses.json.gz']}};(E/'329_heading_inventory_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2));print(d.to_string(index=False));print(json.dumps({k:v for k,v in r.items()if k not in ['input_pins','output_pins']},indent=2))
