from pathlib import Path
import pandas as pd,gzip,json,hashlib
O=Path(__file__).parent;d=pd.read_csv(O/'moscow_native_all_years_stage68.csv.gz');p=pd.read_csv(O/'moscow_ownpoint_snapshot68.csv.gz').drop_duplicates('target_source_record_id',keep='last').set_index('target_source_record_id');e=pd.read_csv(O/'accepted_identity_edge_delta.csv').to_dict('records');pt=pd.read_csv(O/'accepted_point_use_delta.csv').to_dict('records');pr=pd.read_csv(O/'literal_ordinary_lifecycle_bridges.csv').to_dict('records');sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest()
for case,oldn,curn,title in [('rename_Maslovsky_2003',1663,66746,'Масловский сельский округ (Московская область)'),('explicit_lexical_expansion_TourPansion',3415,68122,None)]:
 old=d[d.census_year.eq(2002)&d.source_record_id.str.endswith(':'+str(oldn))&d.source_record_id.str.contains('010_3e')].iloc[0];cur=d[d.census_year.eq(2021)&d.source_record_id.str.endswith(':'+str(curn))].iloc[0];cp=p.loc[cur.source_record_id];assert set(d[d.root.eq(cur.root)].census_year)=={2010,2021};source=O/'own_wikipedia_batch5.json.gz'if title else Path('/workspace/settlements-raw/data/raw/historical_geography/geokladr_okato_2011/okato.dbf');loc='rawDBF record74011 NAME1=п Турпансионата Клязьминское Водохранилище;owncode46234804013;current68122pointdistance<0.1km';excerpt='Original2002 word Турпансионат is literal abbreviation for Туристический Пансионат in actual2010/21 properNP names; printed fullquoted feature preserved, exact nativecountyМытищи + validowncodedGeo2011 record74011 and owncurrentpoint agree, no samecountytypedrival'
 if title:
  pages=json.load(gzip.open(source,'rt'))['query']['pages'];pg=next(x for x in pages.values()if x['title']==title);txt=pg['revisions'][0]['slots']['main']['*'];loc=f'page{pg["pageid"]}:revision{pg["revisions"][0]["revid"]}';excerpt='\n'.join(l for l in txt.splitlines()if'2003'in l or'Маслово'in l);assert'27 января 2003'in excerpt
 date='2003-01-27'if title else'UNKNOWN';e.append(dict(from_source_record_id=old.source_record_id,to_source_record_id=cur.source_record_id,relation='same_place',decision_status='checked_rule_accepted',case=case,admission_rule='Dated actual oldNP ownrename plus printedsubcountyowncenter alias, or exact lexical abbreviation and independentowncodedpoint; actual2010/21continuation; historicalvalues retained',source_binding_proof='literal_ordinary_lifecycle_bridges.csv;own_wikidata_entity_claims.json.gz;raw2011_geo_all_ownname_candidates.csv',population_boundary_comparability_asserted=False,municipal_event_date=date));pt.append(dict(target_source_record_id=old.source_record_id,latitude=cp.latitude,longitude=cp.longitude,coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_source_record_id=cur.source_record_id,source_sha256=cp.point_origin_sha256,source_locator=cp.point_origin_locator,point_origin_file=cp.point_origin_file,point_origin_sha256=cp.point_origin_sha256,point_origin_locator=cp.point_origin_locator,point_origin_kind=cp.point_origin_kind,case=case,coordinate_binding_rule='Own representative point on literal originaloldNP alias+county-bound continuation',point_use_inference='own_modern_representative_point_not_direct_historical_measurement',population_boundary_comparability_asserted=False,historical_census_coordinate_asserted=False,secondary_population_not_substituted_for_native=True));pr.append(dict(case=case,own2002_UID=old.source_record_id,own2021_UID=cur.source_record_id,event_date=date,source_path=str(source),source_sha256=sha(source),source_locator=loc,literal_ownsource_excerpt=excerpt,boundary_comparability='UNKNOWN',own_dated_secondary_count_confirmation='Maslovsky ownQ19669357 P1082 year2002 1133 agrees with originalnative1133'if title else'',no_native_population_edits=True))
pd.DataFrame(e).drop_duplicates(['from_source_record_id','to_source_record_id']).to_csv(O/'accepted_identity_edge_delta.csv',index=False);pd.DataFrame(pt).drop_duplicates('target_source_record_id',keep='last').to_csv(O/'accepted_point_use_delta.csv',index=False);pd.DataFrame(pr).to_csv(O/'literal_ordinary_lifecycle_bridges.csv',index=False)
