from pathlib import Path
import pandas as pd,gzip,json,hashlib,xlrd
O=Path(__file__).parent;sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();d=pd.read_csv(O/'moscow_native_all_years_stage68.csv.gz');p=pd.read_csv(O/'moscow_ownpoint_snapshot68.csv.gz').drop_duplicates('target_source_record_id',keep='last').set_index('target_source_record_id');e=pd.read_csv(O/'accepted_identity_edge_delta.csv').to_dict('records');pt=pd.read_csv(O/'accepted_point_use_delta.csv').to_dict('records');rej=pd.read_csv(O/'accepted_point_rejection_delta.csv').to_dict('records');pr=pd.read_csv(O/'literal_ordinary_lifecycle_bridges.csv').to_dict('records');f=O/'own_wikipedia_batch2.json.gz';pg=next(x for x in json.load(gzip.open(f,'rt'))['query']['pages'].values()if x['title']=='Гришенки');co=pg['coordinates'][0];loc=f'page{pg["pageid"]}:revision{pg["revisions"][0]["revid"]}:coordinates[0]';sid2='2002:010_3e630cc803_02c_Moskovskaya-oblast.xls:Sheet1:6381';cur='2021:data_allsettlements_anon_156_v20251217.parquet:parquet:70691';ten='2010:010_711691e352_2._20Kostrom_Kur_Lip_Moscow_MoscObl_Orlov_2010.xls:Data Sheet:13796';rawfile=Path('/workspace/settlements-raw/data/raw/2002/010_3e630cc803_02c_Moskovskaya-oblast.xls');sh=xlrd.open_workbook(str(rawfile)).sheet_by_index(0);source=f;case='Grishenki_printed_subcounty_and_named_rival_rename'
# Current native publisher own physical point and own article coordinate agree; old provider coordinate equals proper rival Grishino's point.
cr=d[d.source_record_id.eq(cur)].iloc[0];assert abs(cr.latitude-co['lat'])<.01 and abs(cr.longitude-co['lon'])<.01
for sid in [ten,cur]:
 old=p.loc[sid];assert abs(old.latitude-55.188066)<.001;rej.append(dict(target_source_record_id=sid,rejection_status='reviewed_rejected_coordinate_claim_only',old_latitude=old.latitude,old_longitude=old.longitude,origin_ledger=old.point_ledger_path,reason='Own rawGeo claim maps physical renamedrival Grishino at55.188/37.183. Nativecurrent publisher Grishenki ownpoint and exactownWiki physicalcoordinates agree55.096/37.430. Providerhistoricalcode/Qdated2002population claims kept separate and not used to assign oldnative1098.',old_point_json=old.to_json(force_ascii=False),native_identity_or_population_rejected=False))
for sid in [sid2,ten,cur]:pt.append(dict(target_source_record_id=sid,latitude=co['lat'],longitude=co['lon'],coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_source_record_id=loc,source_sha256=sha(f),source_locator=loc,point_origin_file=str(f),point_origin_sha256=sha(f),point_origin_locator=loc,point_origin_kind='own_Wikipedia_physical_NP_point_independently_corroborated_by_native_current_publisher',case=case,coordinate_binding_rule='NativeoldKulaковский ownnamedvillage vs dated renamed oldStremilovsky rival; owncurrent physicalWiki point agrees currentnativepublisher; do not bind conflictedhistoricalQcodedcounts',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,provider_identifier_binding_asserted=False,secondary_population_not_substituted_for_native=True))
e.append(dict(from_source_record_id=sid2,to_source_record_id=cur,relation='same_place',decision_status='checked_rule_accepted',case=case,admission_rule='Originalnative2002 ownname/type withliteralKulaковский subcounty, own historicalKulaковский article explicitlylinks survivingGrishenki; oldStremilovsky same-name rival separately renamedGrishino before2010. Native2010/21survivor unique, ownphysicalpoint agrees nativepublisher; secondary historicalownQcount12 remains rejectedfor old1098',source_binding_proof='Grishenki_two_native_rivals_source_proof.json',population_boundary_comparability_asserted=False,municipal_event_date='UNKNOWN'))
# Explicit dated renamed secondformerNP remains its own separate three-native-year chain, no same-year join of the twoOldGrishenki.
old2='2002:010_3e630cc803_02c_Moskovskaya-oblast.xls:Sheet1:6462';t2='2010:010_711691e352_2._20Kostrom_Kur_Lip_Moscow_MoscObl_Orlov_2010.xls:Data Sheet:13797';c2='2021:data_allsettlements_anon_156_v20251217.parquet:parquet:70692';cp=p.loc[c2]
for sid in [old2,t2]:
 e.append(dict(from_source_record_id=sid,to_source_record_id=c2,relation='same_place',decision_status='checked_rule_accepted',case='dated_rename_rival_Grishino',admission_rule='Literal oldСтремиловский same-name village and documented2004/2005rename toGrishino distinguish it from retainedKulaковskyGrishenki; realnative2010/21samecountytypedNP; all actualcounts unchanged',source_binding_proof='Grishenki_two_native_rivals_source_proof.json',population_boundary_comparability_asserted=False,municipal_event_date='2005-06-24'))
 if sid not in p.index:pt.append(dict(target_source_record_id=sid,latitude=cp.latitude,longitude=cp.longitude,coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_source_record_id=c2,source_sha256=cp.point_origin_sha256,source_locator=cp.point_origin_locator,point_origin_file=cp.point_origin_file,point_origin_sha256=cp.point_origin_sha256,point_origin_locator=cp.point_origin_locator,point_origin_kind=cp.point_origin_kind,case='dated_rename_rival_Grishino',coordinate_binding_rule='Distinct formerStremilovskyGrishenki→Grishino ownnamed representativepoint; not survivingKulaковskyGrishenki',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,secondary_population_not_substituted_for_native=True))
proof=dict(original_native2002_large_1098=dict(UID=sid2,literal_cells=sh.row_values(6381-1)[:5],printed_parent_row6377=sh.row_values(6377-1)[:5]),original_native2002_small_12=dict(UID=old2,literal_cells=sh.row_values(6462-1)[:5]),surviving_large_native_IDs=[sid2,ten,cur],renamed_small_native_IDs=[old2,t2,c2],source_quality_note='OwnQ18773713P1082year2002=12 is a knownsecondaryhistpop homonym binding collision; not promotedto native1098identity or nativecounts. Modernphysicalarticlepoint independentlyagrees currentnativepublisher; historicalpointmeasurement not asserted.',conflicted_secondary_own_code_binding_not_asserted=True,raw_current_publisher_coordinate=[cr.latitude,cr.longitude],raw_current_publisher_own_UID=cur,modern_physical_own_Wiki=[co['lat'],co['lon']],native2002_population_values_protected=True,boundary_comparability='UNKNOWN',source_witnesses=[])
for fn,title,terms in [('own_wikipedia_batch6.json.gz','Стремиловский сельский округ',['Гришенки','2004']),('own_wikipedia_batch7.json.gz','Гришино (муниципальный округ Чехов)',['Гришенки','24 июня 2005']),('own_wikipedia_batch7.json.gz','Кулаковский сельский округ (Московская область)',['Гришенки'])]:
 ff=O/fn;pg2=next(z for z in json.load(gzip.open(ff,'rt'))['query']['pages'].values()if z['title']==title);txt=pg2['revisions'][0]['slots']['main']['*'];proof['source_witnesses'].append(dict(source_path=str(ff),sha256=sha(ff),pageid=pg2['pageid'],revid=pg2['revisions'][0]['revid'],literal_lines=[dict(line=i,text=l)for i,l in enumerate(txt.splitlines(),1)if any(z in l for z in terms)]))
(O/'Grishenki_two_native_rivals_source_proof.json').write_text(json.dumps(proof,ensure_ascii=False,indent=2));pd.DataFrame(e).drop_duplicates(['from_source_record_id','to_source_record_id']).to_csv(O/'accepted_identity_edge_delta.csv',index=False);pd.DataFrame(pt).drop_duplicates('target_source_record_id',keep='last').to_csv(O/'accepted_point_use_delta.csv',index=False);pd.DataFrame(rej).drop_duplicates('target_source_record_id').to_csv(O/'accepted_point_rejection_delta.csv',index=False);print('twoGrish chains reviewed separately, inheritedwrongpointclaims rejected')
