from pathlib import Path
import pandas as pd,json,gzip,hashlib
O=Path(__file__).parent;d=pd.read_csv(O/'moscow_native_all_years_stage68.csv.gz');p=pd.read_csv(O/'moscow_ownpoint_snapshot68.csv.gz').drop_duplicates('target_source_record_id',keep='last').set_index('target_source_record_id');f=O/'own_wikipedia_batch1.json.gz';pages={};pagefiles={}
for ff in O.glob('own_wikipedia_batch*.json.gz'):
 for pp in json.load(gzip.open(ff,'rt'))['query']['pages'].values():
  if 'missing'not in pp:pages[pp['title']]=pp;pagefiles[pp['title']]=ff
credits=[];events=[];obs=[];status=[];absence=[]
for name,curid,title,date,relation,term in [('Успенский',70212,'Успенский (Московская область)','2003','new_NP_formed_by_merger','Поселок образовался в 2003'),('Молодёжный',69300,'Молодёжный (городской округ Подольск)','2005-12-05','administrative_creation_of_formally_named_NP_with_earlier_military_predecessor','официальный статус и наименование'),('Юдино',68897,'Юдинский сельский округ (Одинцовский район)','2004-08-09','new_formal_selo_NP_by_merger_of_separately_printed_derevnya_and_poselok','9 августа 2004')]:
 pg=pages[title];f=pagefiles[title];sourcehash=hashlib.sha256(f.read_bytes()).hexdigest();txt=pg['revisions'][0]['slots']['main']['*'];lines=[dict(line=i,text=l)for i,l in enumerate(txt.splitlines(),1)if term in l or'1952'in l or'722'in l];assert lines;loc=f'page{pg["pageid"]}:revision{pg["revisions"][0]["revid"]}';cur=d[d.census_year.eq(2021)&d.source_record_id.str.endswith(':'+str(curid))].iloc[0];g=d[d.root.eq(cur.root)];assert set(g.census_year)=={2010,2021}and len(g)==2 and all(s in p.index for s in g.source_record_id);n=name.lower().replace('ё','е');old=d[d.census_year.eq(2002)&d.name_norm.eq(n)];proper=old[old.district_raw.str.contains('Серебряно-Пруд'if name=='Успенский'else'Одинцов'if name=='Юдино'else'Подольск',na=False)];proper=proper[proper.settlement_type.eq(cur.settlement_type)]if name=='Юдино'else proper;assert len(proper)==0;scope='over1000_moscow_birth_'+str(curid)
 events.append(dict(scope_id=scope,place=name,event_date=date,date_precision='year'if date=='2003'else'day',relation=relation,decision_status='accepted_secondary_literal_own_NP_formation_available_year_path',event_source_file=str(f),event_source_sha256=sourcehash,event_source_locator=loc,literal_ownsource_excerpt=json.dumps(lines,ensure_ascii=False),source_year_scope='actual_native2010_and2021_only',missing_2002_successor_count_assigned=False,physical_predecessor_absence_asserted=False,predecessor_2002_population='UNKNOWN',no_2002_zero_imputation=True,own_point_from_actual_native_NP=True,population_boundary_comparability='UNKNOWN',old_predecessor_native_observations_merged_into_successor_2002=False))
 status.append(dict(scope_id=scope,place=name,census_year=2002,status='no_preformation_separate_sourceyear_observation_of_new_successor_NP'if name!='Молодёжный'else'formally_named_NP_created2005_earlier_military_predecessor1952_status_and_2002_count_UNKNOWN',own_population='',calendar_zero_imputed=False,physical_population_absence_asserted=False,predecessor_source_year_value='UNKNOWN',selected_exact_ownnamed_2002_record_absent=True))
 for r in g.itertuples():
  cp=p.loc[r.source_record_id];credits.append(dict(scope_id=scope,source_record_id=r.source_record_id,year=r.census_year,source_population=r.population,new_population_on_available_year_formation_path_axis=r.population,all_actual_native_observation_years='2010,2021',birth_or_formal_creation_date=date,native2002_population_not_imputed=True,predecessor_unknown_retained=True,own_point_verified=True,source_values_quality_preserved=True));obs.append(dict(scope_id=scope,source_record_id=r.source_record_id,census_year=r.census_year,settlement_name=r.settlement_name,population=r.population,population_value_quality=r.population_value_quality,latitude=cp.latitude,longitude=cp.longitude,coordinate_source_record_id=cp.coordinate_source_record_id,point_origin_file=cp.point_origin_file,point_origin_sha256=cp.point_origin_sha256,point_origin_locator=cp.point_origin_locator,point_ledger_path=cp.point_ledger_path,own_point=True,formation_date=date,all_available_native_years_continuity=True,boundary_comparability='UNKNOWN'));status.append(dict(scope_id=scope,place=name,census_year=r.census_year,status='actual_separate_own_published_observation',own_population=r.population,calendar_zero_imputed=False,predecessor_source_year_value='UNKNOWN'))
 absence.append(dict(scope_id=scope,exact_owned_2002_namesake_rows_regionwide_json=old[['source_record_id','settlement_name','settlement_type','district_raw','population']].to_json(orient='records',force_ascii=False),proper_native2002_county='Серебряно-Прудский район'if name=='Успенский'else'Одинцовский район'if name=='Юдино'else'Подольский район',exact_ownnamed_2002_matches_within_proper_county=0,all_actual_native2002_roster_path=str(O/'moscow_native_all_years_stage68.csv.gz'),all_actual_native2002_roster_sha256=hashlib.sha256((O/'moscow_native_all_years_stage68.csv.gz').read_bytes()).hexdigest(),physical_predecessor_counts_unknown_not_zero=True))
for n,rows in [('accepted_newly_formed_lifecycle_events.csv',events),('accepted_newly_formed_native_credit_union.csv',credits),('accepted_newly_formed_native_observations.csv',obs),('accepted_newly_formed_available_year_statuses.csv',status),('selected_2002_ownnamed_absence_witnesses.csv',absence)]:pd.DataFrame(rows).to_csv(O/n,index=False)
print('accepted_birthcases',len(events),'native_UIDs',len(credits),'native_population',sum(r['source_population']for r in credits))
