from pathlib import Path
import pandas as pd,json,gzip,hashlib,xlrd
O=Path(__file__).parent;E=O.parent;sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();d=pd.read_csv(O/'moscow_native_all_years_stage68.csv.gz');p=pd.read_csv(O/'moscow_ownpoint_snapshot68.csv.gz').drop_duplicates('target_source_record_id',keep='last').set_index('target_source_record_id');credited=set(pd.read_csv(E/'main_axis_residual_application68_20261008/applied_primary_credited_UID_roster.csv.gz').source_record_id);pgs={}
for f in O.glob('own_wikipedia_batch*.json.gz'):
 for pg in json.load(gzip.open(f,'rt'))['query']['pages'].values():
  if 'missing'not in pg:pgs[pg['title']]=(pg,f)
configs=[('Агрогород','2002:010_3e630cc803_02c_Moskovskaya-oblast.xls:Sheet1:994','Растуново','Растуново','2009-03-11','day','Агрогород',None),('Хлюпинского Завода Стройполимер','2002:010_3e630cc803_02c_Moskovskaya-oblast.xls:Sheet1:4021','Хлюпино','Хлюпино (Московская область)','2006','year','Стройполимер',74528),('Вишняковские Дачи','2002:1_TOM_01_04.xls:0:1221','Электроугли','Вишняковские Дачи','2005-02-15','day','15 февраля 2005',None),('Звягино','2002:010_3e630cc803_02c_Moskovskaya-oblast.xls:Sheet1:4757','Пушкино','Звягино (Пушкинский район)','2003-07-31','day','31 июля 2003',None),('Петелинской Птицефабрики','2002:010_3e630cc803_02c_Moskovskaya-oblast.xls:Sheet1:4151','Часцы','Часцы','2009-02','month','феврале 2009',None)]
obs=[];points=[];events=[];edges=[];credits=[];contexts=[];raws=[];excerpts=[];statuses=[];geo=pd.read_csv(O/'raw2011_geo_all_ownname_candidates.csv',dtype=str);rawfile=Path('/workspace/settlements-raw/data/raw/2002/010_3e630cc803_02c_Moskovskaya-oblast.xls');rawfederal=Path('/workspace/settlements-raw/data/raw/2002_official_tom1/1_TOM_01_04.xls');geoDBF=Path('/workspace/settlements-raw/data/raw/historical_geography/geokladr_okato_2011/okato.dbf');sh2=xlrd.open_workbook(str(rawfile)).sheet_by_index(0);shfed=xlrd.open_workbook(str(rawfederal)).sheet_by_index(0)
for name,sid,recipient,title,date,precision,term,georec in configs:
 old=d[d.source_record_id.eq(sid)].iloc[0];assert sid not in credited;pg,f=pgs[title];txt=pg['revisions'][0]['slots']['main']['*'];lines=[dict(line=i,text=l)for i,l in enumerate(txt.splitlines(),1)if term in l];assert lines;loc=f'pageid={pg["pageid"]};revision={pg["revisions"][0]["revid"]}';source=sha(f)
 cg=d[d.name_norm.eq(recipient.lower().replace('ё','е'))];cg=cg[cg.settlement_type.eq('город')]if recipient in ['Пушкино','Электроугли']else cg[cg.settlement_type.isin(['село','деревня','посёлок'])];cur=cg[cg.census_year.eq(2021)];assert len(cur)==1,(name,'receivercurrent',len(cur));cur=cur.iloc[0];cg=d[d.root.eq(cur.root)];assert len(cg)==3 and set(cg.census_year)=={2002,2010,2021};assert set(cg.source_record_id)<=credited and all(s in p.index for s in cg.source_record_id),(name,'receiver');scope='over1000_moscow_included_'+str(sid.rsplit(':',1)[1]);pop=int(old.population)
 if sid in p.index:
  cp=p.loc[sid];lat,lon=cp.latitude,cp.longitude;pf=cp.point_origin_file;ph=cp.point_origin_sha256;pl=cp.point_origin_locator;pk=cp.point_origin_kind;pcs=cp.coordinate_source_record_id
 elif georec:
  g=geo[geo.record_number_1based.eq(str(georec))].iloc[0];assert 'Стройполимер'in g.NAME1 and g.TER=='46';lat,lon=float(g.LAT),float(g.LONG);pf=str(geoDBF);ph=sha(geoDBF);pl=f'raw_record_1based={georec};byte_offset={g.byte_offset_0based};NAME1={g.NAME1};TER/KOD1/KOD2/KOD3=46/241/825/006;fields=LAT,LONG';pk='own_named_former_NP_raw_GeoKLADR2011_retained_historical_locality_point';pcs='GeoKLADR2011:OKATO:46241825006'
 else:
  co=pg['coordinates'][0];lat,lon=co['lat'],co['lon'];pf=str(f);ph=source;pl=loc+':coordinates[0]';pk='own_named_former_NP_Wikipedia_physical_reference_point';pcs=pl
 obs.append(dict(scope_id=scope,place=name,year=2002,source_record_id=sid,native_population=pop,native_population_quality=old.population_value_quality,latitude=lat,longitude=lon,own_point=True,recipient_city=recipient,receiving_NP_actual_type=cur.settlement_type,event_date=date,event_date_precision=precision,event_relation='included_in',same_place_identity_asserted=False,receiving_city_2021_source_record_id=cur.source_record_id,receiving_city_2021_count_context_only=int(cur.population),child_2021_population_assigned=False,is_additive_to_original_final_mixed_census_axis=False,already_in_baseline68_primary_native_ID_union=False,new_native_population_if_event_admitted=pop,whole_city_roster_closure_asserted=False,population_boundary_comparability_asserted=False,native_values_quality_preserved=True))
 points.append(dict(scope_id=scope,target_source_record_id=sid,source_record_id=sid,latitude=lat,longitude=lon,coordinate_admission_status='reviewed_rule_accepted',decision_status='reviewed_rule_accepted',coordinate_source_record_id=pcs,source_sha256=ph,source_locator=pl,point_origin_file=pf,point_origin_sha256=ph,point_origin_locator=pl,point_origin_kind=pk,own_locality_point=True,recipient_point_assigned_to_child=False,new_ordinary_point_use_proposed=sid not in p.index,point_temporal_interpretation='Independent modern retained ownformerNP physical reference point used retrospectively for native2002; no censusday directcoordinate claim',direct_historical_coordinate_measurement=False,provider_binding_asserted=False,boundary_comparability_asserted=False))
 events.append(dict(scope_id=scope,former_locality=name,recipient_city=recipient,receiving_NP_type=cur.settlement_type,event_date=date,date_precision=precision,relation='included_in',same_place=False,event_source_file=str(f),event_source_sha256=source,event_source_locator=loc,event_source_quality='secondary_literal_dated_former_NP_inclusion_own_or_receiver_article',event_date_role='Literal dated inclusion wording; cited actdate not independently promoted to operative day',decision_status='accepted_secondary_article_included_in',primary_law_source_reopened=False,boundary_comparability='UNKNOWN',roster_closed=False,sum_city_equals_children_asserted=False))
 edges.append(dict(scope_id=scope,from_source_record_id=sid,to_source_record_id=cur.source_record_id,relation='included_in',event_date=date,date_precision=precision,event_source_file=str(f),event_source_sha256=source,event_source_locator=loc,same_place=False,graph_union_allowed=False,whole_city_roster_closure_asserted=False,modern_boundary_reconstruction=False))
 credits.append(dict(scope_id=scope,source_record_id=sid,year=2002,source_population=pop,new_population_on_separate_transformation_path_axis=pop,own_historical_point_verified=True,receiving_city_actual_2002_2010_2021_context_verified=True,is_additive_to_original_final_mixed_census_axis=False,ordinary_three_census_same_place_claim=False))
 rowno=int(sid.rsplit(':',1)[1]);sf=rawfederal if'1_TOM'in sid else rawfile;ss=shfed if'1_TOM'in sid else sh2;vals=ss.row_values(rowno-1);assert any(str(v).replace('.0','')==str(pop)for v in vals);raws.append(dict(source_record_id=sid,year=2002,native_population=pop,native_quality=old.population_value_quality,source_path=str(sf),source_sha256=sha(sf),source_locator=f'{ss.name}:row{rowno}',raw_cells_json=json.dumps(vals[:8],ensure_ascii=False),matches_native_population=True));excerpts.append(dict(scope_id=scope,source_path=str(f),source_sha256=source,source_locator=loc,literal_excerpts_json=json.dumps(lines,ensure_ascii=False)))
 for y in [2002,2010,2021]:statuses.append(dict(scope_id=scope,place=name,year=y,status='actual_separate_own_published_observation'if y==2002 else'ceased_as_separate_locality_included_in_recipient_before_census',own_population=pop if y==2002 else'',unknown_is_zero=False,recipient_population_assigned_to_child=False,boundary_comparability='UNKNOWN'))
 for r in cg.itertuples():
  cp=p.loc[r.source_record_id];contexts.append(dict(scope_id=scope,recipient_city=recipient,receiving_NP_actual_type=r.settlement_type,census_year=r.census_year,source_record_id=r.source_record_id,population=r.population,population_value_quality=r.population_value_quality,latitude=cp.latitude,longitude=cp.longitude,point_ledger_path=cp.point_ledger_path,is_receiving_city_context_only=True,new_national_credit_population=0,child_count_substituted=False,already_in_baseline68_primary_credit=True))
for n,rows in [('accepted_historical_observations.csv',obs),('accepted_former_locality_own_points.csv',points),('accepted_inclusion_events.csv',events),('accepted_included_in_event_edges.csv',edges),('accepted_direct_event_native_credit_union.csv',credits),('actual_receiving_city_three_census_context.csv',contexts),('event_native_raw_row_witnesses.csv',raws),('literal_own_inclusion_source_excerpts.csv',excerpts),('accepted_available_year_statuses.csv',statuses)]:pd.DataFrame(rows).to_csv(O/n,index=False)
print('events',len(events),'old02credit',sum(r['source_population']for r in credits),'contexts',len(contexts))
