from pathlib import Path
import pandas as pd,json,gzip,hashlib,xlrd,duckdb
O=Path(__file__).parent;sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();d=pd.read_csv(O/'moscow_native_all_years_stage68.csv.gz');p=pd.read_csv(O/'moscow_ownpoint_snapshot68.csv.gz').drop_duplicates('target_source_record_id',keep='last').set_index('target_source_record_id');edges=pd.read_csv(O/'accepted_identity_edge_delta.csv').to_dict('records');pts=pd.read_csv(O/'accepted_point_use_delta.csv').to_dict('records');proof=[];rivals=[]
pgs={}
for f in O.glob('own_wikipedia_batch*.json.gz'):
 for pg in json.load(gzip.open(f,'rt')).get('query',{}).get('pages',{}).values():
  if 'missing'not in pg:pgs[pg['title']]=(pg,f)
def sid(y,n):
 q=d[d.census_year.eq(y)&d.source_record_id.str.endswith(':'+str(n))];q=q[q.source_record_id.str.contains('1_TOM_01_04'if n==1321 else'010_3e630cc803')]if y==2002 else q;assert len(q)==1,(y,n,len(q));return q.iloc[0]
configs=[('rename_КрасныйПуть',932,8877,65599,'Красный Путь (Московская область)','2005-06-24','совхоза'),('rename_Майдарово',5703,13253,70029,'Майдарово','2005-02-25','совхоза Майдарово'),('rename_Индустрия',2524,None,67481,'Индустрия (Московская область)','2004','племхоза'),('rename_Проводник',2493,10308,67555,'Проводник (Московская область)','2004-11-10','совхоза'),('literal_abbreviation_Ермолино',456,8562,66024,'Посёлок опытного хозяйства «Ермолино»','UNKNOWN','Ермолино'),('type_conversion_Абрамцево',1321,9203,66391,'Абрамцево','2004','дачный посёлок'),('owncoded_rival_Чашниково',5713,13266,70121,'Чашниково (городской округ Солнечногорск)','UNKNOWN','Чашниково'),('literal_sourcegroup_Шарапово',6457,13852,70801,None,'UNKNOWN',None)]
for case,n2,n10,n21,title,date,term in configs:
 cur=sid(2021,n21);old=sid(2002,n2);ten=sid(2010,n10)if n10 else d[d.root.eq(cur.root)&d.census_year.eq(2010)].iloc[0];cand=pd.DataFrame([old,ten,cur]);roots=set(cand.root);full=d[d.root.isin(roots)];assert not full.census_year.duplicated().any(),case;assert cur.source_record_id in p.index;cp=p.loc[cur.source_record_id];source='';loc='';ex=''
 if title:
  pg,f=pgs[title];txt=pg['revisions'][0]['slots']['main']['*'];assert term in txt;source=str(f);loc=f'pageid={pg["pageid"]};revision={pg["revisions"][0]["revid"]}';ex='\n'.join(l for l in txt.splitlines()if term in l or 'прежние имена'in l or 'цифровой идентификатор'in l)
 # Chashnikovo two countyhomonyms disambiguated by independently owncoded oldGeo56.034241/37.165243 + exact current ownpoint56.029722/37.169166. Native2010 flanks Хоругвино/Шелепаново occur in literal2002sameKirovsubcounty; otherChashnikovo old02row5689 differs.
 if case=='owncoded_rival_Чашниково':
  z=pd.read_csv(O/'prior_own_classifier_context_holds.csv');z=z[z.source_record_id.eq(old.source_record_id)].iloc[0];assert abs(z.own_geokladr_latitude-cp.latitude)<.02 and abs(z.own_geokladr_longitude-cp.longitude)<.02;ex+='\n'+z.to_json(force_ascii=False);rivals.extend(d[d.name_norm.eq('чашниково')].assign(case=case).to_dict('records'))
 if case=='literal_sourcegroup_Шарапово':
  f=Path('/workspace/settlements-raw/data/raw/2010/010_711691e352_2._20Kostrom_Kur_Lip_Moscow_MoscObl_Orlov_2010.xls');sh=xlrd.open_workbook(str(f)).sheet_by_name('Data Sheet');vals=[(n,sh.row_values(n-1)[:6])for n in range(13849,13855)];assert vals[-1][1][3]=='г. Шатура'and vals[1][1][3]=='деревня Чепелёво';source=str(f);loc='Data Sheet:rows13849-13854;targetrow13852;nextliteralcityheader13854';ex=json.dumps(vals,ensure_ascii=False)+'; immediately prior admitted nativecounty anchor2010row13850 Чепелёво maps original2002 Чеховский район; follows sortedownvillage block, next cityШатура is explicit boundary; unique seloШарапово withincounty'
 proof.append(dict(case=case,own2002_UID=old.source_record_id,own2010_UID=ten.source_record_id,own2021_UID=cur.source_record_id,event_date=date,event_precision='day'if len(date)==10 else'year'if date!='UNKNOWN'else'UNKNOWN',source_path=source,source_sha256=sha(source),source_locator=loc,literal_ownsource_excerpt=ex,all_actual_component_years_json='[2002,2010,2021]',no_native_population_edits=True,boundary_comparability='UNKNOWN'))
 for r in [old,ten]:
  if r.root!=cur.root:edges.append(dict(from_source_record_id=r.source_record_id,to_source_record_id=cur.source_record_id,relation='same_place',decision_status='checked_rule_accepted',case=case,admission_rule='Explicit own literal former-name/type continuity or owncoded rival disambiguation with literal native sourcecounty context; actual distinct nativeyears, owncurrentpoint',source_binding_proof='literal_ordinary_lifecycle_bridges.csv;native_all_with_independent_county.csv.gz',population_boundary_comparability_asserted=False,municipal_event_date=date))
  if r.source_record_id not in p.index:pts.append(dict(target_source_record_id=r.source_record_id,latitude=cp.latitude,longitude=cp.longitude,coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_source_record_id=cur.source_record_id,source_sha256=cp.point_origin_sha256,source_locator=cp.point_origin_locator,point_origin_file=cp.point_origin_file,point_origin_sha256=cp.point_origin_sha256,point_origin_locator=cp.point_origin_locator,point_origin_kind=cp.point_origin_kind,case=case,coordinate_binding_rule='Own modern locality representative point on literal oldname/type/nativecounty-bound same_place continuation',point_use_inference='own_modern_representative_point_on_source_bound_native_identity',population_boundary_comparability_asserted=False,historical_census_coordinate_asserted=False,secondary_population_not_substituted_for_native=True))
# Wrong current Kara homonympoint: component68 current singleton only; no existing native02/10 inheritedpoint claims.
cur=sid(2021,68500);pg,f=pgs['Караваево (Богородский городской округ)'];co=pg['coordinates'][0];cp=p.loc[cur.source_record_id];loc=f'pageid={pg["pageid"]};revision={pg["revisions"][0]["revid"]};coordinates[0]';assert len(d[d.root.eq(cur.root)])==1;txt=pg['revisions'][0]['slots']['main']['*'];assert '46239807002'in txt and 'Богородск'in txt;rejections=[dict(target_source_record_id=cur.source_record_id,rejection_status='reviewed_rejected_coordinate_claim_only',old_latitude=cp.latitude,old_longitude=cp.longitude,origin_ledger=cp.point_ledger_path,reason='Wrong Dmitrov same-name village coordinate; independent own Bogorodsky Wiki coordinates plus own2009code46239807002 and nativecurrentOKTMO46751000286 establish local identity; old claim matches Dmitrov Kara65908 rawpoint',old_point_json=cp.to_json(force_ascii=False),native_identity_or_population_rejected=False)]
for y,n in [(2002,3855),(2010,11529),(2021,68500)]:
 r=sid(y,n);pts=[z for z in pts if z['target_source_record_id']!=r.source_record_id];pts.append(dict(target_source_record_id=r.source_record_id,latitude=co['lat'],longitude=co['lon'],coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_source_record_id=f'Wikipedia:page{pg["pageid"]}:revision{pg["revisions"][0]["revid"]}',source_sha256=sha(f),source_locator=loc,point_origin_file=str(f),point_origin_sha256=sha(f),point_origin_locator=loc,point_origin_kind='own_Wikipedia_qualified_Bogorodsky_native_locality_point',case='correct_false_homonym_Karavaevo',coordinate_binding_rule='Own exactcounty/code Wikipedia point replaces wrongly assigned Dmitrov homonym; oldnativecounty and unique literalname/type retained',point_use_inference='own_current_physical_representative_point_not_censusday_measurement',population_boundary_comparability_asserted=False,historical_census_coordinate_asserted=False,secondary_population_not_substituted_for_native=True))
proof.append(dict(case='correct_false_homonym_Karavaevo',own2021_UID=cur.source_record_id,source_path=str(f),source_sha256=sha(f),source_locator=loc,literal_ownsource_excerpt='\n'.join(l for l in txt.splitlines()if 'Караваево'in l or 'Богород'in l or 'идентификатор'in l),own_classifier_2009='46239807002;raw_classifier line99175;county46239Ногинский;nameКараваево;typeдеревня',native_current_own_OKTMO='46751000286',stage68_actual_component_members=cur.source_record_id,old_homonym_dmitrov_native_UID='2021:data_allsettlements_anon_156_v20251217.parquet:parquet:65908'))
pd.DataFrame(edges).drop_duplicates(['from_source_record_id','to_source_record_id']).to_csv(O/'accepted_identity_edge_delta.csv',index=False);pd.DataFrame(pts).drop_duplicates('target_source_record_id',keep='last').to_csv(O/'accepted_point_use_delta.csv',index=False);pd.DataFrame(rejections).to_csv(O/'accepted_point_rejection_delta.csv',index=False);pd.DataFrame(proof).to_csv(O/'literal_ordinary_lifecycle_bridges.csv',index=False);pd.DataFrame(rivals).to_csv(O/'explicit_rival_disambiguation_inventory.csv.gz',index=False);print('totaledges',len(pd.DataFrame(edges).drop_duplicates(['from_source_record_id','to_source_record_id'])),'points',len(pts),'extensions',len(configs))
