from pathlib import Path
import pandas as pd,json,gzip,urllib.parse,urllib.request,ssl,hashlib,datetime
O=Path(__file__).parent;f=pd.read_csv(O/'actual46_priority_component_absence.csv.gz',dtype=str,keep_default_na=False)
# Discovery titles only. Returned pages must independently bind actual NP/type/region/county/code/point.
known={'завода Мосрентген':'Мосрентген','Кокошкино':'Кокошкино (Москва)','Киевский':'Киевский (Москва)','Колпна':'Колпны','Звездный городок':'Звёздный городок','Иласхан-Юрт':'Илсхан-Юрт','Пригородное':'Пригородное (Чечня)','Ферзиково':'Ферзиково (посёлок)','Берёзовка':'Берёзовка (Первомайский район Алтайского края)','Центральный':'Центральный (Суворовский район)','Выползово':'Выползово (Калужская область)','Метлино':'Метлино (Челябинская область)','Зональный':'Зональный (Краснодарский край)','Энергетик':'Энергетик (Башкортостан)','Новое':'Новое (Северная Осетия)','Куровской':'Куровской','Каменномост':'Каменномост','Кузнечиха':'Кузнечиха (Ярославский район)','Березовка':'Березовка (Амурская область)','Мочище':'Мочище (станционный посёлок)','посёлок Чайковская':'Чайковская (посёлок)','донское':'Донское (Калининградская область)','свх. Агроном':'Агроном (Липецкая область)','Ново-Писцово п.':'Ново-Писцово','Заклинье':'Заклинье (Лужский район)','Михайловка':'Михайловка (Оренбургский район)','Крюково':'Крюково (Чеховский район)','Первомайский':'Первомайский (Приморско-Ахтарский район)','Успенский':'Успенский (посёлок)','двинской':'Двинской','Заречный':'Заречный (Кореновский район)','Рахманово':'Рахманово (Павлово-Посадский район)','Георгиевское':'Георгиевское (Костромская область)','Селекционной станции':'Селекционной станции (Нижегородская область)','Солидарность':'Солидарность (Липецкая область)','Лазо':'Лазо (Лазовский район)','Покровское':'Покровское (Артёмовский городской округ)','Темкино':'Тёмкино','Архангельское':'Архангельское (Каменский район Тульской области)','27 км железной дороги мончегорск- оленья':'27 километр (Мурманская область)','Чашниково':'Чашниково (Солнечногорский район)','Молодежный':'Молодёжный (Московская область)','Майский':'Майский (Щёкинский район)','Ракиты':'Ракиты (Михайловский район)','им. Калинина':'Имени Калинина (Ветлужский район)','Барановка':'Барановка (Сочи)','Летно-Хвалынское':'Лётно-Хвалынское','Алексеевка':'Алексеевка (Яковлевский район)','Александровка':'Александровка (Кинельский район)','Озерки':'Озерки (Конаковский район)','Левинцы':'Лёвинцы','Авангард':'Авангард (Приморский край)','Первое Мая':'Первое Мая (Балахнинский район)','Первомайское':'Первомайское (Первомайский район Тамбовской области)','Старая Меловая':'Старая Меловая','Савино':'Савино (Пермский район)','Семёновское':'Семёновское (Ступинский район)'}
f['discovery_article_title']=f.settlement_name.map(lambda x:known.get(x,x));f[['source_record_id','settlement_name','region_norm','discovery_article_title']].to_csv(O/'own_article_discovery_title_requests.csv',index=False);titles=list(dict.fromkeys(f.discovery_article_title));receipts=[]
for start in range(0,len(titles),50):
 batch=titles[start:start+50];query={'action':'query','format':'json','prop':'revisions','rvprop':'ids|timestamp|content','rvslots':'main','redirects':1,'titles':'|'.join(batch)};url='https://ru.wikipedia.org/w/api.php?'+urllib.parse.urlencode(query);req=urllib.request.Request(url,headers={'User-Agent':'RussianSettlementResearch/1.0 source-verification','Accept-Encoding':'gzip'});dest=O/f'own_wikipedia_articles_batch_{start//50+1:02d}.json.gz'
 with urllib.request.urlopen(req,context=ssl.create_default_context(),timeout=45) as h:
  data=h.read(3*1024*1024+1);assert len(data)<=3*1024*1024,'Response exceeds bounded compressed size';encoding=h.headers.get('Content-Encoding','');decoded=gzip.decompress(data) if encoding=='gzip' else data;z=json.loads(decoded);assert 'error' not in z,z.get('error');compressed=data if encoding=='gzip' else gzip.compress(data,mtime=0);assert len(compressed)<=3*1024*1024;dest.write_bytes(compressed);receipts.append({'source':'RussianWikipedia own article revisions discovery','requested_titles':batch,'url':url,'http_status':h.status,'normal_TLS_certificate_validation':True,'response_content_encoding':encoding,'compressed_bytes':len(compressed),'decompressed_bytes':len(decoded),'sha256':hashlib.sha256(compressed).hexdigest(),'local_file':str(dest),'retrieved_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'returned_pages':len(z.get('query',{}).get('pages',{}))});print(json.dumps({'batch':start//50+1,'requested':len(batch),'pages':receipts[-1]['returned_pages'],'compressed_bytes':len(compressed)},ensure_ascii=False),flush=True)
(O/'wikipedia_network_receipt.json').write_text(json.dumps(receipts,ensure_ascii=False,indent=2))
