import json,hashlib
from pathlib import Path
import pandas as pd
import sys
Z=Path(__file__).resolve().parent;E=Z.parent;sys.path.insert(0,str(E.parent/'mass_linkage'))
from current_chain_state_20261007 import distance_km
sha=lambda p:hashlib.file_digest(Path(p).open('rb'),'sha256').hexdigest();P=json.loads((Z/'active_extreme_point_claims.json').read_text());d=pd.read_csv(Z/'all377_extreme_histories.csv',keep_default_na=False).set_index('source_record_id_2021');held=pd.read_csv(Z/'held_candidates.csv.gz',keep_default_na=False);out=[]
for r in held.to_dict('records'):
 sid=r['carrier_source_record_id'];component=d.loc[sid];current=(float(P[sid]['latitude']),float(P[sid]['longitude']));oldids=[component.source_record_id_2002,component.source_record_id_2010];geoids=[t for t in oldids if 'geokladr' in str(P[t].get('point_origin_file','')).lower() and distance_km((float(P[t]['latitude']),float(P[t]['longitude'])),current)>100];badcoords={(float(P[t]['latitude']),float(P[t]['longitude'])) for t in geoids}
 affected=[t for t in oldids if (float(P[t]['latitude']),float(P[t]['longitude'])) in badcoords]
 assert affected
 for target in affected:
  p=P[target];ledger=Path(p['point_ledger_path']);out.append(dict(target_source_record_id=target,rejection_status='reviewed_rejected_coordinate_claim_only',old_latitude=p['latitude'],old_longitude=p['longitude'],origin_ledger=str(ledger),origin_ledger_sha256=sha(ledger),old_point_origin_file=p.get('point_origin_file',''),old_point_origin_sha256=p.get('point_origin_sha256',''),old_point_origin_locator=p.get('point_origin_locator',''),carrier_source_record_id=sid,rejection_reason='coordinate_conflict_unresolved: extreme old/current representative geometry inconsistent; historical Geo default suspended from reliable point coverage, both source coordinates and accepted identity/count preserved; which physical coordinate is accurate remains UNKNOWN. '+r['reason'],coordinate_quality_status='coordinate_conflict_unresolved',replacement_admitted=False,identity_rejected=False,source_population_modified=False))
resolved=pd.read_csv(Z/'point_use_rejections.csv.gz',keep_default_na=False);resolved.to_csv(Z/'resolved_representative_supersessions.csv.gz',index=False,compression={'method':'gzip','mtime':0});pd.DataFrame(out).to_csv(Z/'unresolved_old_Geo_point_quarantine.csv.gz',index=False,compression={'method':'gzip','mtime':0});allrows=pd.concat([resolved,pd.DataFrame(out)],ignore_index=True);assert allrows.target_source_record_id.is_unique;allrows.to_csv(Z/'point_use_rejections.csv.gz',index=False,compression={'method':'gzip','mtime':0});summary=dict(status='all_unresolved_extreme_old_Geo_default_claims_quarantined_without_new_points',held_histories=len(held),unresolved_old_point_uses=len(out),held_gross_population_by_year={str(y):int(held['population_'+str(y)].sum()) for y in [2002,2010,2021]},resolved_representative_supersession_uses=len(resolved),total_rejection_or_supersession_rows=len(allrows),raw_source_and_identity_unchanged=True,implementation_sha256=sha(Path(__file__)));(Z/'unresolved_quarantine_receipt.json').write_text(json.dumps(summary,indent=2)+'\n');print(json.dumps(summary,indent=2))
