from pathlib import Path
import json,pandas as pd,xlrd,pyarrow.parquet as pq,re,hashlib,shutil
E=Path('/workspace/russian-settlements-research/research_rebuild/evidence');O=E/'large_absorbed_city_closed_scope_mass_20261008';d=pd.read_csv(O/'candidate_constituent_credit_union.csv');books={};out=[];ctrl=[]
for r in d[d.census_year.eq(2002)].itertuples():
 p=r.source_file
 if p not in books:books[p]=xlrd.open_workbook(p)
 sn,n=r.source_row_locator.split('!row_1based=');n=int(float(n));b=books[p];s=b.sheet_by_index(0) if sn=='0' else b.sheet_by_name(sn);rr=s.row_values(n-1);labels=[(i,z) for i,z in enumerate(rr) if isinstance(z,str) and r.settlement_name.replace('ё','е').lower() in z.replace('ё','е').lower()]
 assert len(labels)==1,(r.source_record_id,labels);idx,lab=labels[0];value=int(float(rr[idx+1]));assert value==r.population,(r.source_record_id,value,r.population)
 out.append({'source_record_id':r.source_record_id,'year':2002,'raw_original_file':p,'raw_original_sha256':r.source_file_sha256,'raw_locator':r.source_row_locator,'raw_row_json':json.dumps(rr,ensure_ascii=False),'named_atomic_leaf_literal':lab,'raw_population_value':value,'selected_population_value':r.population,'selected_unmodified':True})
for nm,start,end,group in [('039_1d4b1f6286_02c_Volgograd.xls',4,32,'Волгоград'),('061_e177b0a77d_Chel_abinskaja1.xls',3,13,'Челябинск'),('040_95a4475637_02c_Rostov_obl.xls',36,41,'Шахты')]:
 p='/workspace/settlements-raw/data/raw/2002/'+nm;s=books[p].sheet_by_index(0);members=d[d.source_file.eq(p)].copy();members['row_n']=members.source_row_locator.map(lambda z:int(float(z.split('=')[-1])));pending=None
 for n in range(start,end+1):
  rr=s.row_values(n-1);labelidx=1 if isinstance(rr[0],(int,float)) else 0;label=str(rr[labelidx]);val=rr[labelidx+1]
  if re.match(r'\s*(село|деревня|посёлок|поселок|хутор|станица|станция)\s+',label,re.I):continue
  if str(val).strip() and not label.startswith(' '):continue
  if str(val).strip():
   expected=int(float(val));j=n+1
   while j<=end:
    rj=s.row_values(j-1);lj=str(rj[labelidx]);vj=rj[labelidx+1]
    if not re.match(r'\s*(село|деревня|посёлок|поселок|хутор|станица|станция)\s+',lj,re.I):break
    j+=1
   g=members[members.row_n.between(n+1,j-1)];assert int(g.population.sum())==expected,(label,expected,int(g.population.sum()))
   ctrl.append({'city':group,'control_raw_file':p,'control_raw_row_1based':n,'control_raw_label':label,'printed_control':expected,'atomic_selected_members':len(g),'atomic_selected_sum':int(g.population.sum()),'difference':0,'control_never_NP_member':True})
 # First row outsideclosedcityruralblock retained as explicitboundary witness.
 rr=s.row_values(end);ctrl.append({'city':group,'control_raw_file':p,'outside_closed_rural_block_row_1based':end+1,'outside_raw_row_json':json.dumps(rr,ensure_ascii=False),'control_never_NP_member':True})
pd.DataFrame(out).to_csv(O/'original2002_atomic_raw_row_verification.csv',index=False);pd.DataFrame(ctrl).to_csv(O/'original2002_rural_subgroup_control_conservation.csv',index=False)
receipt=json.loads((O/'candidate_receipt.json').read_text());receipt.update(all_51_native2002_atomic_rows_original_reopened_and_values_equal_selected=len(out),raw_rural_subgroup_controls_all_exact=True,donsoy_scope_corrected='Донской13648 belongs Новочеркасск publishedscope, not Шахты',chely2010_repeat_context='Table5PDFpage160 solecity1130132; later municipalitytablePDFpage812 explicitly Челябинскийгородскойокруг–городскоенаселение1130132; identical repeat not conflict',source_ID_union_credited_population_not_citysum=True);receipt['outputs']={p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in O.glob('*.csv')};(O/'candidate_receipt.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n')
for nm in ['scan.py','build.py','verify.py']:shutil.copy(Path('/workspace/settlements-work/large_absorbed_city_closed_scope_mass_20261008')/nm,O/nm)
(O/'README.md').write_text('''# Six complete published city hierarchy scopes, candidate only\n\nAction-ready candidate:6 scopes,18 actual2002/2010/2021 observations,63 distinct native atomicNP members. Against the currentfinite ordinary all3points + parts12 + qualified1919 + named10 source-ID union, only44 old2002IDs are new:145,289 population. No new2010/2021 population is claimed; existingcitymillions are reuse, not gain.\n\nScopes: Каменск-Шахтинский+22,600; Волгоград+32,939; Челябинск+27,474; Шахты+32,070; Новочеркасск+13,648; Новошахтинск+16,558. Донской belongs Новочеркасск, not Шахты.\n\nOriginal2002 federalpublished citywithallsubordinates controls reconcile allurbanNP leaves andallregionalrural atomicblocks. Ruralblocksclose22 leaves6393 Волгоград;5 leaves8543 Челябинск;3 leaves3417 Шахты. Others explicitlyurbanonly. Everyoldatomic source row reopened with exactnativevalue; everyrural subgroup reconciled, controlheadings neverNPmembers.\n\n2010federalTable5 prints each completeassociated scope as a solecity line, with no subsidiary ruralcontrol. Its nativeprimaryselectedcity count agrees. Челябинск has an identical municipality urbanonlycontrol repeat laterin samePDF. Raw2021publication has exactlyoneNP undereachcityparent; parent/ownNP count agrees. Allthree sourcecontrols close withoutallocation/overwriting.\n\nThis is a changing published territorial/source-hierarchy scope, not an exact namedannexation roster or constantmodernboundary estimate. Boundarycomparability UNKNOWN. Existingownreceivingcity point represents the whole scope only; nochildcoordinates or missingyearchildcounts invented, noordinarysameplaceedges. Legalact roster notclaimed. \n\nCandidateonly; noaccepted,helper,loader,report orGit mutations. Files usecandidate prefixes; raworiginal witnesses/hashmanifest and sourceIDnet are preserved. Reproduce scan.py, build.py, verify.py with frozen reportexclusion inputs. Remaining8 targetedcity scopes have proven2021 closure but need bounded2010/2002atomic closure work; none added here.\n''');print('raw oldrows',len(out),'regionalcontrols',len(ctrl),'bytes',sum(p.stat().st_size for p in O.iterdir() if p.is_file()))
