from pathlib import Path
import json,gzip,re,sys,hashlib
import pandas as pd
R=Path('/workspace/russian-settlements-research');E=R/'research_rebuild/evidence';O=Path(__file__).parent;sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from working_state_20261007 import load
from current_chain_state_20261007 import sha
s=load(34);pins={str(p):sha(p) for p in s.inputs};credit=set()
for _,g in s.obs.groupby('root',sort=False):
 if set(g.census_year)=={2002,2010,2021} and g.population.notna().all() and all(x in s.point_rows for x in g.source_record_id):credit.update(g.source_record_id)
for fn in ['qualified_scope_source_id_credit_union.csv','named_merger_lineage_constituents.csv','complete_publisher_partition_members.csv']:
 p=E/'working_full_chain_20261007'/fn;credit.update(pd.read_csv(p,dtype=str).source_record_id);pins[str(p)]=sha(p)
raw02=Path('/workspace/settlements-raw/data/raw/2002_official_tom1/1_TOM_01_04.xls');f02=pd.read_excel(raw02,header=None);pins[str(raw02)]=sha(raw02)
vsource=E/'top_large_missing_year_sources_20261007/wikipedia_live_revision_response.json.gz';vpages=json.load(gzip.open(vsource,'rt'))['query']['pages'];vp=next(x for x in vpages if 'Востряково' in x['title']);vt=vp['revisions'][0]['slots']['main']['content'];pins[str(vsource)]=sha(vsource)
olsource=Path('/workspace/settlements-work/continuation_20261004/regions/large2010_residual20_v1/raw_wikipedia/ozheryelye_kashira.json');op=next(iter(json.load(olsource.open())['query']['pages'].values()));ot=op['revisions'][0]['slots']['main']['*'];pins[str(olsource)]=sha(olsource)
lsource=Path('/workspace/settlements-work/continuation_20261004/federal_and_history/large_old_inclusion_batch20_20261004/raw_entities/Q4266660.json');le=json.load(lsource.open())['entities']['Q4266660'];pins[str(lsource)]=sha(lsource)
assert '19 июля 2004' in vt and 'присоединён к городу [[Домодедово' in vt
assert '16 ноября 2015' in ot and 'включения в состав Каширы' in ot
assert le['descriptions']['ru']['value']=='микрорайон Воскресенска Московской области, рабочий посёлок в 1963—2004 годах'
assert any(x['mainsnak']['datavalue']['value']['id']=='Q133825' for x in le['claims']['P131'])
vcoords=vp['coordinates'][0];lp=le['claims']['P625'][0];lv=lp['mainsnak']['datavalue']['value']
cfg=[('vostryakovo_domodedovo','Востряково','Домодедово',1103,'Q37955079','2004-07-19','day','secondary_own_Wikipedia_literal_annexation_date_and_receiver',vsource,f'page{vp["pageid"]}:revision{vp["revisions"][0]["revid"]}',vcoords['lat'],vcoords['lon'],vt),('lopatinsky_voskresensk','Лопатинский','Воскресенск',1078,'Q4266660','2004','year','secondary_own_Wikidata_description_former_pgt_until2004_and_current_receiver_P131_no_exact_legal_date',lsource,'entities.Q4266660.descriptions.ru + claims.P131',lv['latitude'],lv['longitude'],json.dumps({'description':le['descriptions']['ru'],'P131':le['claims']['P131'],'P625':lp},ensure_ascii=False)),('ozherele_kashira','Ожерелье','Кашира',1133,'Q175752','2015-11-16','day','secondary_own_Wikipedia_literal_annexation_date_and_receiver',olsource,f'page{op["pageid"]}:revision{op["revisions"][0]["revid"]}',None,None,ot)]
children=[];cores=[];edges=[];ownpoints=[];events=[];rawchecks=[];excerpts=[]
for key,name,city,row,q,eventdate,dateprec,eventquality,evsource,evloc,lat,lon,text in cfg:
 scope='moscow_direct_inclusion_'+key;child=s.obs[(s.obs.settlement_name==name)&(s.obs.region_norm=='московская')&s.obs.census_year.isin([2002,2010])];assert len(child)==(2 if name=='Ожерелье' else 1)
 cityg=s.obs[(s.obs.settlement_name==city)&(s.obs.region_norm=='московская')&s.obs.settlement_type.eq('город')];assert set(cityg.census_year)=={2002,2010,2021} and len(cityg)==3
 receiver21=cityg[cityg.census_year.eq(2021)].iloc[0];assert all(sid in s.point_rows for sid in cityg.source_record_id)
 for cr in cityg.itertuples():
  cp=s.point_rows[cr.source_record_id];cores.append(dict(scope_id=scope,recipient_city=city,census_year=cr.census_year,source_record_id=cr.source_record_id,population=cr.population,population_value_quality=cr.population_value_quality,latitude=cp['latitude'],longitude=cp['longitude'],point_ledger_path=cp['point_ledger_path'],is_independent_selected_actual_count=True,is_receiving_city_context_only=True,new_national_credit_population=0,boundary_comparability='unknown',child_count_substituted=False))
 for cr in child.itertuples():
  if cr.census_year==2002:
   assert cr.source_record_id==f'2002:1_TOM_01_04.xls:0:{row}';assert float(f02.iloc[row-1,1])==float(cr.population);rawlabel=f02.iloc[row-1,0];rawchecks.append(dict(source_record_id=cr.source_record_id,census_year=2002,source_path=str(raw02),source_sha256=pins[str(raw02)],sheet=0,row_1based=row,raw_label=rawlabel,raw_population_cell='B',raw_population=float(f02.iloc[row-1,1]),matches_selected_population=True))
  point=s.point_rows.get(cr.source_record_id)
  if point:
   clat,clon=float(point['latitude']),float(point['longitude']);pointfile=Path(point['point_ledger_path']);ploc=cr.source_record_id;kind='existing_accepted_own_historical_locality_point_replayed';pins[str(pointfile)]=sha(pointfile);pointdetails=json.dumps(point,ensure_ascii=False,default=str)
  else:
   clat,clon=lat,lon;pointfile=evsource;ploc=(lp['id'] if name=='Лопатинский' else evloc+':coordinates[0]');kind='cached_own_former_locality_Wikidata_P625' if name=='Лопатинский' else 'cached_own_former_locality_Wikipedia_coordinate';pointdetails=json.dumps(lp if name=='Лопатинский' else vcoords,ensure_ascii=False)
  assert clat is not None and clon is not None
  ownpoints.append(dict(scope_id=scope,target_source_record_id=cr.source_record_id,latitude=clat,longitude=clon,point_origin_file=str(pointfile),point_origin_sha256=sha(pointfile),point_origin_locator=ploc,point_origin_kind=kind,own_locality_point=True,recipient_point_assigned_to_child=False,point_temporal_interpretation='Representative of the independently identified former locality; not measured census-date coordinate',point_witness_json=pointdetails,new_ordinary_point_use_proposed=False))
  net=0 if cr.source_record_id in credit else float(cr.population);children.append(dict(scope_id=scope,place=name,year=cr.census_year,source_record_id=cr.source_record_id,native_population=cr.population,native_population_quality=cr.population_value_quality,latitude=clat,longitude=clon,own_point=True,recipient_city=city,event_date=eventdate,event_date_precision=dateprec,event_relation='included_in',same_place_identity_asserted=False,whole_city_roster_closure_asserted=False,population_boundary_comparability_asserted=False,modern_boundary_harmonized=False,receiving_city_2021_source_record_id=receiver21.source_record_id,receiving_city_2021_count_context_only=receiver21.population,child_2021_population_assigned=False,already_in_stage34_mixed_native_ID_union=cr.source_record_id in credit,new_native_population_if_event_admitted=net,is_additive_to_ordinary_selected_denominator=False,native_values_quality_preserved=True,event_source_quality=eventquality))
  edges.append(dict(scope_id=scope,from_source_record_id=cr.source_record_id,to_source_record_id=receiver21.source_record_id,relation='included_in',event_date=eventdate,date_precision=dateprec,recipient_city=city,event_source_file=str(evsource),event_source_sha256=sha(evsource),event_source_locator=evloc,event_source_quality=eventquality,same_place=False,graph_union_allowed=False,whole_city_roster_closure_asserted=False,modern_boundary_reconstruction=False))
 events.append(dict(scope_id=scope,former_locality=name,recipient_city=city,event_date=eventdate,date_precision=dateprec,relation='included_in',same_place=False,event_source_file=str(evsource),event_source_sha256=sha(evsource),event_source_locator=evloc,event_source_quality=eventquality,primary_law_source_reopened=False,roster_closed=False,sum_city_equals_children_asserted=False,scope_interpretation='Direct documented inclusion lineage; independent old counts and own points with receiving city actual3year context; not a reconstructed/harmonized whole city territory'))
 if name=='Лопатинский':excerpt=text
 else:excerpt='\n'.join(l for l in text.splitlines() if any(x in l for x in ['2004','2015','включ','присоедин','упразд','Координаты','Город =']))
 excerpts.append(name+' → '+city+'\nSource '+str(evsource)+' '+evloc+'\n'+excerpt)
# Reopen official2010urbanPDF for the actual oldOzherele count; no auxiliary citycount substitutions.
pdf=Path('/workspace/settlements-raw/data/raw/2010_official_tom11/pub-11-1-4.pdf');pins[str(pdf)]=sha(pdf);pt=(E/'moscow_complete_scope_mass_20261008/official2010_urban_reopened.txt').read_text();line=next(l for l in pt.splitlines() if 'Ожерелье' in l);assert re.search(r'11113\s+10469',line);(O/'official2010_ozherele_reopened_excerpt.txt').write_text('Cached actualpdftotext reopening of '+str(pdf)+'\n'+line+'\n');rawchecks.append(dict(source_record_id=child[child.census_year.eq(2010)].source_record_id.iloc[0],census_year=2010,source_path=str(pdf),source_sha256=sha(pdf),sheet='PDF',row_1based='exacturbannameОжерелье',raw_label=line,raw_population_cell='2010column',raw_population=10469,matches_selected_population=True))
for fn,rows in [('candidate_historical_observations.csv',children),('actual_receiving_city_three_census_context.csv',cores),('candidate_included_in_event_edges.csv',edges),('candidate_former_locality_own_points.csv',ownpoints),('candidate_inclusion_events.csv',events),('actual_native_raw_reopenings.csv',rawchecks)]:pd.DataFrame(rows).to_csv(O/fn,index=False)
(O/'literal_cached_inclusion_source_excerpts.txt').write_text('\n\n'.join(excerpts),encoding='utf8');(O/'source_manifest.json').write_text(json.dumps(pins,ensure_ascii=False,indent=2));m=pd.DataFrame(children);net={str(y):int(g.new_native_population_if_event_admitted.sum()) for y,g in m.groupby('year')};net['2021']=0;receipt=dict(status='candidate_secondary_direct_included_in_event_path_root_review_pending',baseline_stage=34,events=3,historical_observations=len(children),receiving_context_observations=9,conditional_new_native_ID_population=net,own_historical_points=4,ordinary_identity_edges=0,ordinary_point_uses=0,child2021_observations=0,receiving2021_extra_credit=0,whole_city_roster_closure_asserted=False,city_children_sum_conservation_asserted=False,boundary_harmonization=False,weak_source_limit='Lopatinskyeventyear2004fromcachedownentityliteralrudescription+P131receivingcity, noexactdayorprimarylawclaimed',source_manifest_sha256=sha(O/'source_manifest.json'));(O/'receipt.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2));print(json.dumps(receipt))
