from pathlib import Path
import json,gzip,pandas as pd,re,hashlib
D=Path(__file__).parent;E=D.parent.parent
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
ef=E/'moscow_large_residual_actionable_20261008/municipal_entities.json.gz';pf=E/'moscow_large_residual_actionable_20261008/municipal_pages.json.gz';q='Q4373595';e=json.load(gzip.open(ef,'rt'))['entities'][q];p=next(p for p in json.load(gzip.open(pf,'rt'))['query']['pages'].values() if p.get('pageprops',{}).get('wikibase_item')==q);t=p['revisions'][0]['slots']['main']['*'];formation=next(z for z in t.splitlines() if 'создано в 2005' in z);assert 'Сосенского сельского округа' in formation and 'Московского сельского округа' in formation
predfile=E/'moscow_complete_scope_mass_application_20261008/accepted_transferred_municipal_scope_observations.csv';pred=pd.read_csv(predfile,keep_default_na=False);pred=pred[pred.scope_id.isin(['moscow_sourceyear_sosenskoye','moscow_sourceyear_moskovsky'])&pred.census_year.eq(2002)];assert len(pred)==2
pred[['scope_id','observation_id','census_year','population','population_source_file','population_source_sha256','population_source_locator']].assign(role='existing_shared_predecessor_reference_only_no_new_observation_no_new_UID_credit').to_csv(D/'existing_predecessor_node_references.csv',index=False)
st=e['claims']['P625'][0];v=st['mainsnak']['datavalue']['value'];obs=[]
for stp in e['claims']['P1082']:
 for dt in stp.get('qualifiers',{}).get('P585',[]):
  dv=dt.get('datavalue',{}).get('value',{});year=int(dv.get('time','+0000')[1:5])
  if year not in [2010,2021]:continue
  assert stp.get('references');obs.append(dict(scope_id='moscow_formation_branch_mosrentgen',observation_id='moscow_formation_branch_mosrentgen:'+str(year),census_year=year,population=float(stp['mainsnak']['datavalue']['value']['amount']),population_quality='secondary_explicit_census_referenced_whole_municipal_total',source_file=str(ef),source_sha256=sha(ef),source_locator=stp['id'],population_date=dv['time'],references_json=json.dumps(stp['references'],ensure_ascii=False),municipal_entity=q,point_role='representative_scope',latitude=v['latitude'],longitude=v['longitude'],point_source_file=str(ef),point_source_sha256=sha(ef),point_source_locator=st['id'],ordinary_same_place=False,own_2002_observation_created=False,national2021_native_credit=0,candidate_only=True))
assert {z['census_year'] for z in obs}=={2010,2021};pd.DataFrame(obs).to_csv(D/'candidate_branch_whole_municipal_observations.csv',index=False)
import pyarrow.parquet as pq
raw=Path('/workspace/settlements-raw/data/raw/2010/010_711691e352_2._20Kostrom_Kur_Lip_Moscow_MoscObl_Orlov_2010.xls');f=pd.read_excel(raw,header=None);selected=Path('/workspace/settlements-delivery/continuation-consolidated-20261003/selected_observations.parquet');m=pq.read_table(selected,columns=['source_record_id','census_year','settlement_name','settlement_type','population','population_value_quality']).to_pandas().set_index('source_record_id');members=[]
for n in range(10440,10443):
 sid='2010:'+raw.name+':Data Sheet:'+str(n);r=m.loc[sid];rr=f.iloc[n-1].tolist();assert r.population==rr[4];members.append(dict(scope_id='moscow_formation_branch_mosrentgen',year=2010,source_record_id=sid,native_name=r.settlement_name,native_type=r.settlement_type,native_population=r.population,native_quality=r.population_value_quality,raw_file=str(raw),raw_sha256=sha(raw),raw_sheet='Data Sheet',raw_row_1based=n,raw_original_row_json=json.dumps([None if pd.isna(z) else z for z in rr[:6]],ensure_ascii=False),source_values_modified=False,individual_NP_point_assigned=False,candidate_only=True))
pd.DataFrame(members).to_csv(D/'candidate_branch_native2010_roster.csv',index=False);assert sum(z['native_population'] for z in members)==12350
edges=[dict(from_existing_observation_id=r.observation_id,to_observation_id='moscow_formation_branch_mosrentgen:2010',relation='documented_municipal_formation_from_shared_predecessor_territories',effective_year=2005,ordinary_same_place=False,predecessor_population_copied_as_own2002=False,predecessor_UID_credit_added=False,boundary_comparability='UNKNOWN',candidate_only=True) for r in pred.itertuples()];edges.append(dict(from_existing_observation_id='moscow_formation_branch_mosrentgen:2010',to_observation_id='moscow_formation_branch_mosrentgen:2021',relation='published_whole_municipal_sourceyear_territorial_trace',effective_year='UNKNOWN',ordinary_same_place=False,predecessor_population_copied_as_own2002=False,predecessor_UID_credit_added=False,boundary_comparability='UNKNOWN',candidate_only=True));pd.DataFrame(edges).to_csv(D/'candidate_formation_branch_edges.csv',index=False)
(D/'cached_formation_excerpt.txt').write_text(f'{q} {p["title"]} revision{p["revisions"][0]["revid"]}\n{formation}\n');r=dict(status='separate_formation_branch_candidate_not_complete3ownscope',own_observed_years=[2010,2021],own2002_observation_created=False,existing_shared2002_predecessor_observation_count=2,whole2010_population=17004,native2010_all3_leaf_population_sum=12350,protected_or_scope_control_difference_unallocated=4654,no_2002_modern_subset_sum=True,national2021_native_credit=0,ordinary_edges=0,individual_point_assignments=0,root_separate_eventaxis_adapter_pending=True,source_manifest={str(z):sha(z) for z in [ef,pf,raw,selected,predfile]},outputs={p.name:sha(p) for p in D.glob('*.csv')});(D/'candidate_branch_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n');print('branch candidate frozen')
