from pathlib import Path
import json,hashlib,datetime,gzip
import pandas as pd
O=Path(__file__).parent
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
f=pd.read_csv(O/'accepted_source_bound_ownpoint_evidence.csv.gz',dtype=str,keep_default_na=False);r=json.loads((O/'nominatim_source_receipt.json').read_text());rq={x['source_record_id']:x for x in r['requests']};controls=[]
for z in f.to_dict('records'):
 q=json.loads(z['chosen_raw_source_json']);p=q.get('raw',q.get('raw_ownplace_result'));n=json.loads(z['native_primary_row_json']);orig=Path(z['point_origin_file']);live='raw_ownplace_result' in q
 controls.append({'source_record_id':z['source_record_id'],'physical_object_type':p['osm_type'],'physical_object_id':p['osm_id'],'physical_settlement_class':p['type'],'ownname':p['name'],'source_URL':rq[z['source_record_id']]['url'] if live else '', 'object_URL_pointer_not_new_fetch':f"https://www.openstreetmap.org/{p['osm_type']}/{p['osm_id']}",'source_response_status':'normalTLS_successful_response_saved' if live else 'existing_cached_literal_raw_object_reopened_equal','source_HTTP_status':200 if live else '', 'source_time_UTC':datetime.datetime.fromtimestamp(orig.stat().st_mtime,datetime.timezone.utc).isoformat(),'source_time_kind':'saved_response_filesystem_mtime_observation_not_publication_or_HTTP_Date' if live else 'cached_archive_filesystem_mtime_not_object_edit_time','source_object_publication_edit_time':'unknown','source_file':str(orig),'source_file_sha256':sha(orig),'source_locator':z['point_origin_locator'],'native_own_specific_parish':n['mun_lower'],'published_own_parish':p.get('address',{}).get('municipality',''),'source_positive_parish_control':z['point_origin_kind']=='cached_physical_OSM_place_exact_native_specific_parish','native_all_samecounty_namesakes_retained':True,'raw_object_and_native_primary_literal_reopened':True,'published_status_tags_json':json.dumps(p.get('extratags') or {},ensure_ascii=False),'physical_ownNP_boundary_representative_not_census_measurement':p['osm_type'] in ['way','relation'],'external_provider_ID_binding_asserted':False})
pd.DataFrame(controls).to_csv(O/'accepted_source_controls.csv.gz',index=False,compression={'method':'gzip','mtime':0})
rec=json.loads((O/'joint65_point_admission_receipt.json').read_text());rec.update(source_control_file=str(O/'accepted_source_controls.csv.gz'),source_literal_verification_file=str(O/'source_literal_verification.json'),admission_stage_status='immutable replay-ready candidate packet; canonical stage65 admission not claimed',priority_source_holds=59,source_positive_points=30,source_rule_summary={'exact_current_specific_parish_cached_physical_place':20,'literal_full_owncode_and_type_live_physical_place':8,'explicit_station_settlement_role_excludes_all_plain_namesakes':2},source_records_and_population_values_unchanged=True,network_summary='50 bounded paced verified-TLS requests succeeded; no403/429 or TLS bypass',no_new_State_load=True,pending13_packet_unchanged=True)
rec['output_pins'][str(O/'accepted_source_controls.csv.gz')]=sha(O/'accepted_source_controls.csv.gz');rec['output_pins'][str(O/'source_literal_verification.json')]=sha(O/'source_literal_verification.json');(O/'final_packet_receipt.json').write_text(json.dumps(rec,ensure_ascii=False,indent=2)+'\n')
(O/'README.md').write_text('Replay-ready current ownpoint candidate packet: 30 NPs, 6,539 known 2021 people, all >=100. Actual64 baseline plus frozen pending13 and joint30 point compatibility passed with zero spatial holds. 59 priority targets remain source held. Native source counts, populations, quality and identity edges unchanged. Main-axis gains require actual canonical replay.\n\n20 physical OSM places match the exact current native specific parish and have no samecounty native namesake in that parish; eight live physical places carry literal own full current OKTMO and type; two published station settlements explicitly match native station-settlement role and exclude every plain namesake. No administrative parent/road/infrastructure point and no municipal reform code bridge used. Raw native rows, complete cached raw lines/live results and coordinates reopened equal. Provider ID binding remains unasserted.\n\nSource URLs/status/hash/object IDs and source time limitations are explicit in accepted_source_controls.csv.gz. Cached object URLs are pointers, not claimed new downloads. Saved-file times are filesystem observations, not source edit/publication times. Modern physical locality boundaries produce representative own-locality points only.\n')
files=[p for p in O.iterdir() if p.is_file() and p.name!='frozen_asset_manifest.json'];manifest={'packet':'current_geographic_residual_grounding_20261008','frozen_at_UTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'files':{str(p):{'sha256':sha(p),'bytes':p.stat().st_size} for p in sorted(files)},'total_bytes':sum(p.stat().st_size for p in files),'immutable_point_count':30,'known_population2021':6539,'canonical_applied':False};(O/'frozen_asset_manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n');print('manifest',sha(O/'frozen_asset_manifest.json'));print('delta',sha(O/'accepted_point_use_delta.csv.gz'));print('bytes',manifest['total_bytes'])
