from pathlib import Path
import json,hashlib,zipfile,re,ast,sys,unicodedata,collections
import pandas as pd
O=Path(__file__).parent;E=O.parent;R=E.parent.parent;sys.path.insert(0,str(R/'research_rebuild/mass_linkage'));from current_chain_state_20261007 import normalize,sha
RULE=E/'current_positive_residual_point_sources_20261008/review_articles.py';tree=ast.parse(RULE.read_text());exec(compile(ast.Module(body=[n for n in tree.body if isinstance(n,ast.FunctionDef) and n.name in ['bare','regionkey']],type_ignores=[]),str(RULE),'exec'))
GN=Path('/workspace/settlements-raw/data/raw/coordinate_candidates/geonames_RU_20260907.zip');proof={};gnsha=sha(GN)
with zipfile.ZipFile(GN) as zf:
 with zf.open('RU.txt') as stream:
  for ln,line in enumerate(stream,1):
   p=line.decode().rstrip('\n').split('\t')
   if len(p)>=19 and p[7]=='ADM1':proof[p[10]]={'origin_file':str(GN),'origin_sha256':gnsha,'origin_locator':f'RU.txt:line:{ln}:geonameid:{p[0]}','literal_ADM1_source_line':line.decode().rstrip(),'literal_Russian_region_keys':sorted({regionkey(n) for n in [p[1]]+p[3].split(',') if re.search('[а-я]',normalize(n))})}
W=O/'accepted_source_bound_ownpoint_evidence.csv.gz';w=pd.read_csv(W,dtype=str,keep_default_na=False);adproof=[];objectclass=[]
for z in w.to_dict('records'):
 if 'GeoNames' in z['point_origin_kind']:
  gid=z['coordinate_source_record_id'].split(':')[-1];hits=[q for q in json.loads(z['cached_GeoNames_same_region_name_witnesses_json']) if q['geonameid']==gid];assert hits;pr=proof[hits[0]['admin1']];assert regionkey(z['region_norm']) in pr['literal_Russian_region_keys'];assert float(z['latitude'])==float(hits[0]['latitude']) and float(z['longitude'])==float(hits[0]['longitude']);adproof.append(json.dumps(pr,ensure_ascii=False));objectclass.append('GeoNames '+hits[0]['feature_class']+'/'+hits[0]['feature_code'])
 elif 'OSM' in z['point_origin_kind']:
  _,typ,oid=z['coordinate_source_record_id'].split(':');hits=[q['raw'] for q in json.loads(z['cached_named_OSM_matches_json']) if q['raw']['osm_type']==typ and str(q['raw']['osm_id'])==oid];assert hits and hits[0]['type'] in ['hamlet','village'];assert float(z['latitude'])==float(hits[0]['location'][1]) and float(z['longitude'])==float(hits[0]['location'][0]);adproof.append('');objectclass.append('OSM place='+hits[0]['type']+';osm_type='+typ)
 else:adproof.append('');objectclass.append('literal own physical NP article infobox')
w['independent_GeoNames_literal_ADM1_region_witness_json']=adproof;w['positive_physical_source_object_class']=objectclass;w.to_csv(W,index=False,compression={'method':'gzip','mtime':0,'compresslevel':9})
rp=O/'joint63_point_admission_receipt.json';r=json.loads(rp.read_text());r['output_pins'][str(W)]=sha(W);r['input_pins'][str(O/'finalize_packet.py')]=sha(O/'finalize_packet.py');r['literal_point_coordinates_source_object_and_GeoNames_ADM1_aliases_reopened_for_each_accepted_point']=True;rp.write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n')
f=pd.read_csv(E/'current_positive_residual_point_sources_20261008/prioritized_unresolved_after_round2.csv.gz',dtype=str,keep_default_na=False);rem=f[~f.source_record_id.isin(w.source_record_id)].copy();h=pd.read_csv(O/'cached_named_source_holds.csv.gz',dtype=str,keep_default_na=False);sh=pd.read_csv(O/'joint63_point_admission_holds.csv.gz',dtype=str,keep_default_na=False);reason=h.set_index('source_record_id').source_binding_holds.to_dict();reason.update(sh.set_index('source_record_id').joint63_admission_hold_reasons.to_dict());rem['cached_named_round_hold_reasons']=rem.source_record_id.map(reason).fillna('');rem.to_csv(O/'prioritized_unresolved_after_cached_named.csv.gz',index=False,compression={'method':'gzip','mtime':0,'compresslevel':9})
r.update(unresolved_after_cached_named_rows=len(rem),unresolved_after_cached_named_known_population2021=float(pd.to_numeric(rem.population,errors='coerce').sum()),remaining_positive100_NPs=int((pd.to_numeric(rem.population,errors='coerce')>=100).sum()),source_population_unknown_not_imputed=True,generated_pack_status='frozen_ready_root_joint63_canonical_replay_pending');(O/'final_handoff_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n')
(O/'README.md').write_text('''# Remaining cached named ownpoint sources

Frozen packet: **604 current settlement ownpoints /25,595 known 2021 residents**, including 52 settlements with at least 100 residents. Root authorized combining this packet with the frozen 133-point ownarticle packet in working stage 63. Admission screening uses actual stage 62 snapshots plus those planned current points and every new point together; the composer remains responsible for actual final stage 63 replay.

`accepted_point_use_delta.csv.gz` is the canonical point-use delta. `accepted_source_bound_ownpoint_evidence.csv.gz` retains literal source object, native own NP row and code, regional/county labels, all samecounty native name rivals, RCSI raw CSV records/line numbers, cached OSM member/line and full raw object, GeoNames raw lines and literal ADM1 Russian alias witnesses, and exact source hashes/locators.

532 points come from explicitly typed cached OSM hamlet/village place objects. Exact own name, region and county plus native samecounty name uniqueness establish association; when namesakes exist, one literal owncode/name/type/region/county RCSI row must independently agree within 1 km with one named physical source object, and other source name alternatives must lie beyond 5 km. Both node points and explicitly named physical settlement way/relation representative points are allowed; administrative objects embedded in a border field are never extracted.

71 points use the same literal owncoded RCSI identity proof and one independent GeoNames P-class locality with exact Russian own name and literal ADM1 regional alias, agreeing within 1 km, with other same-region named physical alternatives beyond 5 km. A provider quality score or proximity alone never binds a target. Source point correctness and external provider identifier binding remain separate: no external provider ID is asserted by this packet.

One point reopens a previously held own article for Ушаково (Алешковский сельсовет), 535 residents. Cached classifier mirror literal native owncode 22507000241 explicitly names the former parish under change 456 dated 29 December 2020, effective 1 February 2021, resolving the other samecounty Ушаково alternative. The mirror is not claimed an original official publication; no replacement-code bridge is invented. The own article revision supplies the literal physical village coordinates.

All 604 accepted points pass current point occupation within 1 m, joint newpoint distinctness, and component 5 km compatibility against actual62 plus the planned 133 current ownpoints. Seven source-positive points /124 residents remain held with complete conflict witnesses. Existing old points are neither superseded nor silently disregarded. Modern representative geography does not assert census-date measurement or population boundary comparability. Four accepted rows /489 residents already have primary-axis credit; actual main-axis gain requires canonical replay.

All 2,868 initial residual current NPs were scanned in one cached-source pass, prioritization retained, without a State reload, fresh large download, canonical code/ledger mutation, graph edge, population or quality change. Unknown populations remain unknown. Existing large sources are hash-pinned and referenced instead of copied. The frozen asset manifest pins this packet; root owns integration and commits.
''')
files=[p for p in O.iterdir() if p.is_file() and p.name!='frozen_asset_manifest.json'];m={'packet_status':'frozen_ready_root_joint63_canonical_replay_pending','accepted_new_current_ownpoints':len(w),'accepted_known_population2021':r['accepted_known_population2021'],'assets':{str(p):{'sha256':sha(p),'bytes':p.stat().st_size} for p in sorted(files)},'generated_total_bytes':sum(p.stat().st_size for p in files),'budget_bytes':20_000_000,'upstream_pins':r['input_pins']};assert m['generated_total_bytes']<m['budget_bytes'];(O/'frozen_asset_manifest.json').write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n');print(json.dumps({k:v for k,v in r.items() if k not in ['input_pins','output_pins']},ensure_ascii=False));print('manifest_sha256',sha(O/'frozen_asset_manifest.json'));print('bytes',m['generated_total_bytes'])
