from pathlib import Path
import sys,json,collections,math
import pandas as pd,duckdb,numpy as np
from scipy.spatial import cKDTree
O=Path(__file__).parent;E=O.parent;R=E.parent.parent;sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from current_chain_state_20261007 import sha,distance_km
from build_long_table import ACCEPTED_COORDINATE_STATUSES
B=E/'primary_residual_mass_application_20261008';P=B/'applied_point_snapshot.parquet';C=B/'applied_component_snapshot.csv.gz';A=B/'application_receipt.json';CRE=B/'applied_primary_credited_UID_roster.csv.gz';J=E/'current_positive_residual_point_sources_20261008/accepted_point_use_delta.csv.gz';JR=J.parent/'final_handoff_receipt.json';F=O/'source_positive_cached_named_point_candidates.csv.gz';f=pd.read_csv(F,keep_default_na=False,float_precision='round_trip',dtype={'native_current_fullcode':str});joint=pd.read_csv(J,dtype=str,keep_default_na=False);assert len(joint)==133 and joint.coordinate_admission_status.isin(ACCEPTED_COORDINATE_STATUSES).all()
c=duckdb.connect();comp=c.execute('select source_record_id,root,has_own_point from read_csv_auto(?)',[str(C)]).fetchdf();points=c.execute('select source_record_id,latitude,longitude,coordinate_admission_status,coordinate_source_record_id,point_origin_file,point_origin_locator from read_parquet(?)',[str(P)]).fetchdf();assert set(points.coordinate_admission_status)<=ACCEPTED_COORDINATE_STATUSES;c.register('targets',f[['source_record_id']]);credited=set(c.execute('select c.source_record_id from read_csv_auto(?) c join targets using(source_record_id)',[str(CRE)]).fetchdf().source_record_id);c.close();roots=comp.set_index('source_record_id').root.to_dict();memberpoints=collections.defaultdict(list)
pdjoint=joint.rename(columns={'target_source_record_id':'source_record_id'})[list(points.columns)];points=pd.concat([points,pdjoint],ignore_index=True);assert points.source_record_id.is_unique
for z in points.to_dict('records'):
 z['latitude']=float(z['latitude']);z['longitude']=float(z['longitude']);memberpoints[roots[z['source_record_id']]].append(z)
current=points[points.source_record_id.str.startswith('2021:')].copy();current.latitude=current.latitude.astype(float);current.longitude=current.longitude.astype(float)
def xyz(lat,lon):
 lat,lon=np.radians(np.asarray(lat,float)),np.radians(np.asarray(lon,float));return np.column_stack((np.cos(lat)*np.cos(lon),np.cos(lat)*np.sin(lon),np.sin(lat)))
tree=cKDTree(xyz(current.latitude,current.longitude));ntree=cKDTree(xyz(f.latitude,f.longitude));existing=current.to_dict('records');new=f.to_dict('records');pointids=set(points.source_record_id);accepted=[];witness=[];holds=[]
for i,z in enumerate(new):
 sid=z['source_record_id'];assert sid in roots;root=roots[sid];xy=(float(z['latitude']),float(z['longitude']));reasons=[];far=[];occupants=[];othernew=[];v=xyz([xy[0]],[xy[1]])[0]
 if sid in pointids:reasons.append('already_has_actual62_or_planned133_ownpoint')
 for j in tree.query_ball_point(v,1e-3/6371.009):
  if existing[j]['source_record_id']!=sid:occupants.append(existing[j])
 if occupants:reasons.append('distinct_current_actual62_or_planned133_ownpoint_within1m')
 for j in ntree.query_ball_point(v,1e-3/6371.009):
  if i!=j:othernew.append(new[j]['source_record_id'])
 if othernew:reasons.append('joint_new_point_within1m_multiple_current_NPs')
 for p in memberpoints[root]:
  d=distance_km(xy,(p['latitude'],p['longitude']))
  if d>5:far.append({**p,'distance_km':d})
 if far:reasons.append('positive_current_ownpoint_incompatible_existing_component_old_or_current_point_over5km_no_supersession')
 z.update(actual62_component_root=root,actual62_primary_axis_already_credited=sid in credited,actual62_plus_planned133_other_component_ownpoints=len(memberpoints[root]),joint63_component_conflict_witnesses_json=json.dumps(far,ensure_ascii=False),joint63_distinct_current_occupants_within1m_json=json.dumps(occupants,ensure_ascii=False),joint_new_distinct_current_points_within1m_json=json.dumps(othernew,ensure_ascii=False))
 if reasons:holds.append({**z,'joint63_admission_hold_reasons':';'.join(reasons)});continue
 accepted.append({'target_source_record_id':sid,'latitude':xy[0],'longitude':xy[1],'coordinate_admission_status':'reviewed_extension_rule_accepted','coordinate_source_record_id':z['coordinate_source_record_id'],'point_origin_file':z['point_origin_file'],'point_origin_sha256':z['point_origin_sha256'],'point_origin_locator':z['point_origin_locator'],'point_origin_kind':z['point_origin_kind'],'coordinate_binding_rule':z['source_binding_proof']+'; actual62 plus frozen133 plannedjoint63 points and allnewpoints checked: ownpoint present/physical current occupation<=1m/component5km; actualjoint63 canonical replay remains composer responsibility','point_use_inference':'modern explicitly sourcebound own settlement representative geography; census-date coordinate measurement and population boundary comparability unasserted','historical_census_coordinate_asserted':False,'population_boundary_comparability_asserted':False,'external_provider_ID_binding_asserted':False,'native2021_own_oktmo':z['native_current_fullcode'],'actual62_primary_axis_already_credited':sid in credited});witness.append(z)
for n,d in [('accepted_point_use_delta',accepted),('accepted_source_bound_ownpoint_evidence',witness),('joint63_point_admission_holds',holds)]:pd.DataFrame(d).to_csv(O/(n+'.csv.gz'),index=False,compression={'method':'gzip','mtime':0,'compresslevel':9})
pop=lambda zs:sum(float(z['population']) for z in zs if str(z['population']).strip())
r={'baseline_stage':62,'planned_working_stage':63,'screen_basis':'actual62 baseline accepted point/component snapshots plus immutable133 ownarticle current-point pack and joint newcachednamed points; actualjoint63 replay validates finaladmission','source_positive_current_candidates':len(f),'accepted_new_current_ownpoints':len(accepted),'accepted_known_population2021':pop(witness),'accepted_positive100_NPs':sum(float(z['population'] or 0)>=100 for z in witness),'point_claim_kind_counts':dict(collections.Counter(z['point_origin_kind'] for z in accepted)),'already_primary_axis_credited_accepted_rows':sum(z['actual62_primary_axis_already_credited'] for z in witness),'already_primary_axis_credited_accepted_population2021':sum(float(z['population']) for z in witness if z['actual62_primary_axis_already_credited'] and z['population']),'uncredited_source_positive_population2021_not_a_gain_claim':sum(float(z['population']) for z in witness if not z['actual62_primary_axis_already_credited'] and z['population']),'spatial_or_duplicate_holds':len(holds),'spatial_or_duplicate_held_population':pop(holds),'source_positive_conflicting_component_claims_preserved_not_superseded':True,'source_counts_population_qualities_identity_graph_unchanged':True,'main_axis_or_finite_gain':'root actualjoint63 replay required; no main-axis gain inferred from ownpoint count/population','input_pins':{str(p):sha(p) for p in [P,C,A,CRE,J,JR,F,O/'screen_joint63.py',O/'cached_named_source_sweep_receipt.json',O/'cached_article_coded_parish_bridge_receipt.json']},'output_pins':{str(O/(n+'.csv.gz')):sha(O/(n+'.csv.gz')) for n in ['accepted_point_use_delta','accepted_source_bound_ownpoint_evidence','joint63_point_admission_holds']}};(O/'joint63_point_admission_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n');print(json.dumps({k:v for k,v in r.items() if k not in ['input_pins','output_pins']},ensure_ascii=False))
