from pathlib import Path
import pandas as pd,json,hashlib,zipfile
Z=Path(__file__).parent;B=Z/'batch3_lower_kamennomost_own_historical_object';B.mkdir(exist_ok=True)
uid='2002:033_e221266b42_02c_KCR.xls:нпп:126';gn=Path('/workspace/settlements-raw/data/raw/coordinate_candidates/geonames_RU_20260907.zip');rows=json.loads((Z/'cached_GN_kamennomost_rivals.json').read_text());sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest()
with zipfile.ZipFile(gn) as zz:
 txt=zz.read('RU.txt').decode();lines=txt.splitlines();assert lines[92616]+'\n'==rows[0]['raw'];assert lines[354356]+'\n'==rows[1]['raw']
rule='Existingtypedhistoricalroute retained. Native2002samecounty prints two distinctauls Lower126 andUpper127. PremergerGeneralStaffK-37-12 terrain1990 edition1995 prints two separate ownphysicalsettlements Каменномостский andВерхнекаменномостский. ExactUppername bindsUpper; otherlower/northernsettlement uniquelybindsLower in thepublishedpair, no thirdcompetingKamennomostlocality. GN553515 P/PPL ownКаменномостский coordinates lie in thatownhistoricalmapsettlement; GN11972093 exactUpperdistinctpoint retainedasrival. CurrentmergedwholeNPcenter andmunicipalitypoint explicitlyexcluded. Physicalcoordinateuse retrospectivelyinferred, notexactcensusdate measurement.'
a=dict(target_source_record_id=uid,latitude=43.75017,longitude=41.91152,coordinate_admission_status='reviewed_rule_accepted',decision_status='reviewed_rule_accepted',coordinate_source_record_id='GeoNames:553515',point_origin_file=str(Z/'cached_GN_kamennomost_rivals.json'),point_origin_sha256=sha(Z/'cached_GN_kamennomost_rivals.json'),point_origin_locator='record[0]; upstreamRU.txt:line92617; geonameid553515; P/PPL; Каменномостский',point_origin_kind='own_former_lower_locality_GeoNames_point_bound_by_distinct_premerger_historical_map_pair',own_locality_point=True,recipient_point_assigned_to_child=False,retrospective_point_use_is_continuity_inference=True,direct_historical_coordinate_measurement=False,historical_census_coordinate_asserted=False,provider_identifier_binding_asserted=True,coordinate_time_interpretation='modernpoint oftheownformerLowerphysicalNP; retrospectivephysicalcontinuityinference',admission_rule=rule,identity_changes=False,temporal_route_changes=False,population_values_modified=False,source_count_or_quality_modified=False)
pd.DataFrame([a]).to_csv(B/'accepted_point_use_delta.csv',index=False)
(B/'reviewed_source_binding.md').write_text('Native target: '+uid+'; Lower Kamennomost aul, Karachayevsky district, literal1601.\n\n'+rule+'\n\nMap source https://maps.vlasenko.net/smtm100/k-37-012.jpg; General Staff Карачаевск K-37-12; terrain1990, published1995, 1:100000. Map photograph crop is derivative for name inspection only. Point coordinates copied literally from GN553515; no map-coordinate interpolation or receivercentroid calculation. Upper rivalGN11972093:43.72616,41.927. Historicalmapname pair is thebinding witness. Current merged Wiki43.73222,41.91861 and OSM whole relation3874352 were excluded as former-child pointdonors.\n')
inputs=[gn,Z/'cached_GN_kamennomost_rivals.json',Z/'own_kamennomost_native_context.csv',Z/'bounded_literal_native_witnesses.csv',Z/'map_vlasenko.jpg',Z/'map_lower_upper_own_names_crop.png'];pins=lambda fs:{str(f):dict(sha256=sha(f),bytes=f.stat().st_size) for f in fs}
(B/'FINAL_manifest.json').write_text(json.dumps(dict(status='FINAL_FROZEN_SOURCE_READY',ownpoint_UIDs=1,existing_typed_routes_unchanged=True,input_pins=pins(inputs),output_pins=pins([B/'accepted_point_use_delta.csv',B/'reviewed_source_binding.md'])),ensure_ascii=False,indent=2));print('FINALlowerownphysicalpoint')
