from pathlib import Path
import pandas as pd,json,hashlib,math
Z=Path(__file__).parent;B=Z/'batch1_fortythree_ownpoint_uses';B.mkdir(exist_ok=True);r=pd.read_csv(Z/'assigned_roster.csv');pages={}
for f in Z.glob('wiki*.json'):
 for p in json.loads(f.read_text()).get('query',{}).get('pages',[]):
  if p.get('coordinates'):pages[p['title']]=(f,p)
W={('воронежская','масловка'):'Масловка (Воронеж)',('воронежская','подгорное'):'Подгорное (Воронеж)',('воронежская','краснолесный'):'Краснолесный',('воронежская','придонской'):'Придонской',('воронежская','сомово'):'Сомово (Воронеж)',('воронежская','шилово'):'Шилово (Воронежская область)',('воронежская','троицкое'):'Троицкое (Новохопёрский район)',('волгоградская','водстрой'):'Водстрой',('волгоградская','горьковский'):'Горьковский (Волгоградская область)',('волгоградская','горный'):'Горный (Волгоградская область)',('волгоградская','южный'):'Южный (Волгоградская область)',('волгоградская','краснооктябрьский'):'Краснооктябрьский (Волгоградская область)',('волгоградская','гумрак'):'Гумрак (Волгоград)',('волгоградская','соляной'):'Соляной (Волгоградская область)',('краснодарский','калинино'):'Калинино (Краснодар)',('краснодарский','пашковский'):'Пашковский (посёлок)',('кабардино балкарская','дугулубгей'):'Дыгулыбгей',('северная осетия алания','кора урсдон'):'Кора-Урсдон',('ростовская','сидорово кадамовский'):'Сидорово-Кадамовский',('ростовская','заводской'):'Заводской (Ростовская область)',('ростовская','лиховской'):'Лиховской',('ростовская','донской'):'Донской (Новочеркасск)',('ростовская','красный'):'Красный (Ростовская область)',('ростовская','самбек'):'Самбек (Новошахтинск)',('ростовская','соколово кундрюченский'):'Соколово-Кундрюченский',('ростовская','аютинский'):'Аютинский',('ростовская','майский'):'Майский (Шахты)',('ростовская','таловый'):'Таловый'}
# Only place-class objects in independently source-bound owncity/parent; other candidates retained as rivals.
O={('воронежская','никольское'):0,('воронежская','репное'):1,('воронежская','1 е мая'):2,('воронежская','первое мая'):2,('воронежская','подклетное'):3,('карачаево черкесская','верхний каменномост'):8}
sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();points=[];w=[]
for a in r.itertuples():
 key=(a.region_norm,a.name_norm)
 if 'часть' in a.name_norm or a.name_norm=='нижний каменномост':continue
 if key in W:
  f,p=pages[W[key]];c=p['coordinates'][0];lat=c['lat'];lon=c['lon'];loc='page'+str(p['pageid'])+':revision'+str(p['revisions'][0]['revid'])+':coordinates[0]; ownNP='+p['title'];kind='own_named_former_or_current_NP_Wikipedia_physical_reference_point';cid='Wikipedia:'+p['pageprops']['wikibase_item']+':revision'+str(p['revisions'][0]['revid']);ownname=p['title'];proof='Ownqualifiedarticle name/type and historicalowncity/county matches alreadyacceptedtargetroute; lead/infobox confirmed ownNP physical point. Existingidentityandtemporalroutes retained; no receivercitypoint reused.'
 else:
  assert key in O,key;f=Z/f'osm_own_{O[key]}.json';vals=json.loads(f.read_text());city='Воронеж' if a.region_norm=='воронежская' else 'Карачаевский район';q=[(i,d) for i,d in enumerate(vals) if d['category']=='place' and d['type']=='suburb' and city in d['display_name']];assert len(q)==1,key;i,d=q[0];lat=float(d['lat']);lon=float(d['lon']);loc=f'response[{i}];OSM:{d["osm_type"]}:{d["osm_id"]};name={d["name"]};place=suburb;ownparent={d["display_name"]}';cid=f'OSM:{d["osm_type"]}:{d["osm_id"]}';kind='own_former_locality_OSM_suburb_published_geocoder_representative_point';ownname=d['name'];proof='ExactownformerNPname + explicitplace=suburb underownhistoricalcity/county, notstation/POIorwholeparentpoint; competing regionalobjects retainedandexcludedbydifferentparent/objecttype. 1-еМая/ПервоеМая andownUpperKamennomost are printedaliases underexistingacceptedtemporalroute. Publishedgeocoderlatlonused, no polygoncentroidrecalculated.'
 assert math.isfinite(lat) and math.isfinite(lon)
 points.append(dict(target_source_record_id=a.source_record_id,latitude=lat,longitude=lon,coordinate_admission_status='reviewed_rule_accepted',decision_status='reviewed_rule_accepted',coordinate_source_record_id=cid,point_origin_file=str(f),point_origin_sha256=sha(f),point_origin_locator=loc,point_origin_kind=kind,own_locality_point=True,recipient_point_assigned_to_child=False,retrospective_point_use_is_continuity_inference=True,direct_historical_coordinate_measurement=False,historical_census_coordinate_asserted=False,provider_identifier_binding_asserted=False,coordinate_time_interpretation='modernownNPphysicalpoint retrospectivelyinferredcontinuousplace; exactcensusdaypointunknown',admission_rule=proof,identity_changes=False,temporal_route_changes=False,population_values_modified=False,source_count_or_quality_modified=False))
 w.append(dict(source_record_id=a.source_record_id,target_name=a.settlement_name,target_type=a.settlement_type,target_region=a.region_norm,target_county=a.district_raw,own_source_name=ownname,point_origin_locator=loc,source_file=str(f),source_sha256=sha(f),rule=proof))
assert len(points)==43,len(points)
pd.DataFrame(points).to_csv(B/'accepted_point_use_delta.csv',index=False);pd.DataFrame(w).to_csv(B/'reviewed_ownphysical_point_binding.csv',index=False);r[r.source_record_id.isin([x['target_source_record_id'] for x in points])].to_csv(B/'source_ready_roster.csv',index=False)
inputs=[Z/'assigned_roster.csv',Z/'bounded_literal_native_witnesses.csv']+list({Path(x['point_origin_file']) for x in points});pins=lambda fs:{str(f):dict(sha256=sha(f),bytes=f.stat().st_size) for f in fs};(B/'FINAL_manifest.json').write_text(json.dumps(dict(status='FINAL_FROZEN_SOURCE_READY',assigned_ownpoint_UIDs=43,identity_or_temporal_routes_changed=False,population_or_quality_modified=False,parent_points_projected=False,input_pins=pins(inputs),output_pins=pins(list(B.glob('*.csv')))),ensure_ascii=False,indent=2));print('FINAL43 ownpointuses')
