import sys,json,gzip,re
from pathlib import Path
import pandas as pd,xlrd
sys.path.insert(0,str(Path(__file__).resolve().parents[2]/'mass_linkage'))
from current_chain_state_20261007 import normalize,sha
OUT=Path(__file__).resolve().parent;CACHE=Path('/dev/shm/settlements-stage71-20261009');WIKI=OUT.parent/'over500_south_wiki_sources_20261009'
def main():
 obs=pd.read_parquet(CACHE/'applied_state_observations.parquet');by=obs.set_index('source_record_id');pts=pd.read_csv(OUT/'accepted_point_use_delta.csv').to_dict('records');edges=pd.read_csv(OUT/'accepted_identity_edge_delta.csv');d=pd.read_csv(OUT/'dispositions.csv');manifest=json.loads((OUT/'manifest.json').read_text());wiki=pd.read_csv(WIKI/'article_coordinate_candidates.csv.gz');w=[];events=[];eventedges=[];credits=[];statuses=[];context=[]
 manual={'Водный (Волгоградская область)':('Водный','волгоградская','Волгоград'),'Винтай':('Винтай','самарская','Самара'),'Даниловка (Ростовская область)':('Даниловка','ростовская','Шахты')}
 for title,(name,region,parent) in manual.items():
  q=wiki[wiki.article_title.eq(title)].iloc[0];sid=q.source_record_id;r=by.loc[sid];path=Path('/workspace/settlements-raw')/r.source_file;b=xlrd.open_workbook(path);sheet=sid.rsplit(':',2)[-2];no=int(sid.rsplit(':',1)[-1]);s=b.sheet_by_name(sheet);cells=s.row_values(no-1);headers=[(n+1,s.row_values(n)) for n in range(max(0,no-20),no-1)];literal=' '.join(str(c) for _,row in headers for c in row);valid=normalize(name) in normalize(' '.join(map(str,cells))) and any(str(c).strip().isdigit() and int(str(c).strip())==int(r.population) for c in cells)
  # Printed administration parent is reviewed in the literal nearby source header.
  token={'Волгоград':'волгоград','Самара':'самар','Шахты':'шахты'}[parent]
  if not valid or token not in normalize(literal):raise ValueError('manual native source header failed '+sid)
  file=Path(q.capture);actual=sha(file)
  if actual!=q.capture_sha256:raise ValueError('own wiki hash differs')
  cap=json.load(gzip.open(file,'rt'));page=cap['query']['pages'][str(int(q.pageid))];rev=page['revisions'][0];text=rev.get('*',rev.get('slots',{}).get('main',{}).get('*',''));lead=' '.join(l for l in text.splitlines() if l.startswith("'''") and ('упраздн' in l or 'посёлок' in l or 'хутор' in l));nt=normalize(lead)
  if normalize(name) not in nt or token not in nt or 'упраздн' not in nt:raise ValueError('own former locality article/header differs')
  manifest['inputs_sha256'][str(file)]=actual;manifest['inputs_sha256'][str(path)]=sha(path)
  if sid not in {p['target_source_record_id'] for p in pts}:
   pts.append(dict(target_source_record_id=sid,latitude=q.latitude,longitude=q.longitude,coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_source_record_id='ruwiki:pageid='+str(int(q.pageid)),point_origin_file=str(file),point_origin_sha256=actual,point_origin_locator='pageid='+str(int(q.pageid))+';revid='+str(int(q.revid))+';prop=coordinates;primary=earth',point_origin_kind='former_locality_own_Wikipedia_primary_point',admission_rule='native_physical_source_administrative_parent_and_exact_former_own_article',point_temporal_interpretation='Former locality own representative; no receiving-city point projection',direct_historical_coordinate_measurement=False,native_code_binding_asserted=False,boundary_comparability_asserted=False))
  w.append(dict(source_record_id=sid,source_file=str(path),source_sha256=sha(path),source_locator=sheet+':row1based='+str(no),source_row_literal=json.dumps(cells,ensure_ascii=False),header_witness=json.dumps(headers,ensure_ascii=False),own_article_title=title,own_article_capture=str(file),own_article_sha256=actual,own_article_literal=lead))
 for title,city,year in [('Колос (Ростовская область)','Шахты',2004),('Даниловка (Ростовская область)','Шахты',2004),('Винтай','Самара',2005)]:
  q=wiki[wiki.article_title.eq(title)].iloc[0];sid=q.source_record_id;r=by.loc[sid];file=Path(q.capture);actual=sha(file);cap=json.load(gzip.open(file,'rt'));rev=cap['query']['pages'][str(int(q.pageid))]['revisions'][0];text=rev.get('*',rev.get('slots',{}).get('main',{}).get('*',''));lead=' '.join(l for l in text.splitlines() if l.startswith("'''") and 'включен' in l)
  if str(year) not in lead or normalize(city) not in normalize(lead) or sid not in {p['target_source_record_id'] for p in pts}:raise ValueError('event literal or ownpoint missing')
  receivers=obs[obs.name_norm.eq(normalize(city))&obs.type_norm.eq('город')&obs.region_norm.eq(r.region_norm)]
  if set(receivers.census_year)!={2002,2010,2021} or receivers.census_year.duplicated().any() or receivers.root.nunique()!=1:raise ValueError('receiving city actual census context not complete')
  rid=receivers[receivers.census_year.eq(2021)].iloc[0].source_record_id;scope='over500_south_included_'+normalize(r.settlement_name);loc='page'+str(int(q.pageid))+':revision'+str(int(q.revid));manifest['inputs_sha256'][str(file)]=actual
  events.append(dict(scope_id=scope,former_locality=r.settlement_name,recipient_city=city,event_date=year,date_precision='year',relation='included_in',same_place=False,event_source_file=str(file),event_source_sha256=actual,event_source_locator=loc,event_source_quality='secondary_own_Wikipedia_literal_dated_inclusion',event_date_role='literal own locality inclusion year; cited act date not promoted to operative day',decision_status='accepted_secondary_own_article_included_in',primary_law_source_reopened=False,boundary_comparability='UNKNOWN',roster_closed=False,sum_city_equals_children_asserted=False))
  eventedges.append(dict(scope_id=scope,from_source_record_id=sid,to_source_record_id=rid,relation='included_in',event_date=year,date_precision='year',event_source_file=str(file),event_source_sha256=actual,event_source_locator=loc,same_place=False,graph_union_allowed=False,whole_city_roster_closure_asserted=False,modern_boundary_reconstruction=False))
  credits.append(dict(scope_id=scope,source_record_id=sid,year=int(r.census_year),source_population=r.population,new_population_on_separate_transformation_path_axis=r.population,own_historical_point_verified=True,receiving_city_actual_2002_2010_2021_context_verified=True,is_additive_to_original_final_mixed_census_axis=False,ordinary_three_census_same_place_claim=False))
  for cy in [2002,2010,2021]:statuses.append(dict(scope_id=scope,place=r.settlement_name,year=cy,status='actual_separate_own_published_observation' if cy==2002 else 'included_in_recipient_city_separate_own_count_UNKNOWN',own_population=r.population if cy==2002 else 'UNKNOWN',unknown_is_zero=False,recipient_population_assigned_to_child=False,boundary_comparability='UNKNOWN'))
  for cr in receivers.to_dict('records'):context.append(dict(scope_id=scope,source_record_id=cr['source_record_id'],census_year=cr['census_year'],city=city,population=cr['population'],context_only=True,child_population_assigned=False,source_file=cr['source_file']))
 pd.DataFrame(pts).to_csv(OUT/'accepted_point_use_delta.csv',index=False);pd.DataFrame(w).to_csv(OUT/'former_locality_own_point_witnesses.csv.gz',index=False,compression={'method':'gzip','mtime':0})
 for name,rows in [('accepted_inclusion_events.csv',events),('accepted_included_in_event_edges.csv',eventedges),('accepted_direct_event_native_credit_union.csv',credits),('accepted_available_year_statuses.csv',statuses),('receiving_city_context.csv',context)]:pd.DataFrame(rows).to_csv(OUT/name,index=False)
 changed={p['target_source_record_id'] for p in pts}|set(edges.from_source_record_id)|set(edges.to_source_record_id)|{c['source_record_id'] for c in credits}
 for i,z in d.iterrows():
  sid=z.source_record_id;d.loc[i,'decision']='accepted_delta' if sid in changed else 'held';d.loc[i,'reason']='accepted_own_point_or_source_verified_native_identity' if sid in changed else ('typed_literal_part_no_whole_NP_ownpoint_projection' if '(часть' in normalize(z['name']) else 'unresolved_source_identity_or_ownpoint_requires_further_source');d.loc[i,'has_ownpoint_after']=bool(z.has_ownpoint_after) or sid in {p['target_source_record_id'] for p in pts}
  if sid in {c['source_record_id'] for c in credits}:d.loc[i,'reason']='accepted_own_point_and_typed_source_dated_inclusion_route'
 d.to_csv(OUT/'dispositions.csv',index=False);manifest.update(accepted_point_uses=len(pts),accepted_inclusion_events=len(events),changed_residual_rows=int(d.decision.eq('accepted_delta').sum()),outputs_sha256={f.name:sha(f) for f in OUT.iterdir() if f.suffix in ['.csv','.gz']},builder_sha256={f.name:sha(f) for f in OUT.glob('*.py')});(OUT/'manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n');print(json.dumps({k:manifest[k] for k in ['accepted_identity_edges','accepted_point_uses','accepted_inclusion_events','changed_residual_rows']}))
if __name__=='__main__':main()
