from pathlib import Path
import sys,json,hashlib,pandas as pd
R=Path('/workspace/russian-settlements-research');E=R/'research_rebuild/evidence';I=E/'old_native_from_existing_secondary_binding_20261007';O=E/'old_native_from_existing_secondary_binding_application_20261007';sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from working_state_20261007 import load
from current_chain_state_20261007 import sha
# Stage22 is an explicitly frozen parentbaseline. Execute onlyafter rootnotifies readiness.
s=load(22);before=s.metrics();assert [before[str(y)]['covered_population'] for y in [2002,2010,2021]]==[126262285,123488665,124086298];assert [before[str(y)]['covered_rows'] for y in [2002,2010,2021]]==[137049,137077,137081];d=pd.read_csv(I/'combined_candidate_native_old_bindings.csv',keep_default_na=False);assert len(d)==7
before_full={sid for sid in s.obs.source_record_id if s.years[s.uf.find(sid)]=={2002,2010,2021}};edges=[];points=[];witness=I/'combined_candidate_native_old_bindings.csv';wsha=sha(witness);currents={}
for r in d.to_dict('records'):
 old=r['old_source_record_id'];cur=r['current_source_record_id'];a=s.by_id.loc[old];c=s.by_id.loc[cur]
 assert int(a.population)==int(float(r['old_native_population']));assert a.name_norm==c.name_norm and a.type_norm==c.type_norm and a.region_norm==c.region_norm
 if s.uf.find(old)==s.uf.find(cur):continue
 assert not s.years[s.uf.find(old)]&s.years[s.uf.find(cur)]
 assert cur in s.point_rows
 edges.append({'from_source_record_id':old,'to_source_record_id':cur,'relation':'same_place','decision_status':'checked_rule_accepted','rule':'own_secondary_census_reference_to_native_exact_source_with_direct_county_or_accepted_flanking_anchors','historical_county_raw':r.get('old_county','') or 'UNKNOWN','historical_county_directly_printed':r['proof_tier']=='direct_printed_historical_county','administrative_context_quality':r['proof_tier'],'anchor_inferred_admin_context':r.get('anchor_admin_context','') or 'UNKNOWN','administrative_event_date':'UNKNOWN','population_boundary_comparability_asserted':False,'source_population_values_modified':False,'historical_source_binding_witness_file':str(witness),'historical_source_binding_witness_sha256':wsha})
 s.union(old,cur);currents[cur]=r
# Preserve every existingpoint; transfer accepted currentownrepresentative context only to missingpoints in positivelybound components.
for cur,r in currents.items():
 root=s.uf.find(cur);origin=s.point_rows[cur];ledger=Path(origin['point_ledger_path']);lsha=sha(ledger)
 for sid in s.obs.loc[s.obs.source_record_id.map(s.uf.find).eq(root),'source_record_id']:
  if sid in s.point_rows or any(p['target_source_record_id']==sid for p in points):continue
  point={k:origin.get(k,'') for k in ['latitude','longitude','source_sha256','source_locator','point_origin_file','point_origin_sha256','point_origin_locator','point_origin_kind']}
  point.update(target_source_record_id=sid,coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_source_record_id=cur,target_year=int(s.by_id.loc[sid].census_year),coordinate_origin_ledger=str(ledger),coordinate_origin_ledger_sha256=lsha,coordinate_origin_ledger_locator='target_source_record_id='+cur,continuity_inference='retrospective_ownrepresentative_context_after_sourcepositive_native_census_identity_binding_and_existing_accepted_component',historical_source_binding_witness_file=str(witness),historical_source_binding_witness_sha256=wsha,direct_historical_measurement=False,population_boundary_comparability_asserted=False,administrative_event_date='UNKNOWN');points.append(point)
O.mkdir(exist_ok=True);edgepath=O/'accepted_identity_edge_delta.csv';pointpath=O/'accepted_point_use_delta.csv';pd.DataFrame(edges).to_csv(edgepath,index=False);pd.DataFrame(points).to_csv(pointpath,index=False)
# Edges already appliedin memory; addonly pointdelta withoutremerging.
if points:s.add_deltas(point_paths=[pointpath])
after=s.metrics();new_full={sid for sid in s.obs.source_record_id if s.years[s.uf.find(sid)]=={2002,2010,2021}};affected=d.old_source_record_id.tolist()+d.current_source_record_id.tolist();roots={s.uf.find(sid) for sid in affected};obs=s.obs[s.obs.source_record_id.map(s.uf.find).isin(roots)].copy();obs['accepted_point']=obs.source_record_id.isin(s.point_rows);obs['full3']=obs.source_record_id.map(lambda sid:s.years[s.uf.find(sid)]=={2002,2010,2021});obs.to_csv(O/'accepted_bound_component_observations.csv',index=False)
u=d[['qid','year','old_source_record_id','old_native_population','proof_tier']].rename(columns={'old_source_record_id':'source_record_id','old_native_population':'population_source_value'});u['scope']='existing_accepted_temporal892_reuse';u['trajectory_id']=u.qid;u['source_population_values_modified']=False;u['accepted_native_reference_to_existing_qualified_full3']=True;u.to_csv(O/'accepted_native_reference_credit_union.csv',index=False)
receipt={'accepted_native_reference_credit_by_year':{int(y):int(g.population_source_value.sum()) for y,g in u.groupby('year')},'baseline22_expected_populations_and_rows_verified':True,'native_reference_credit_note':'All7 native IDs bind previouslyadmitted398 physicalfull3; finalqualifiedsource-IDunion deduplicates ordinarygains.','status':'applied_exact_own_census_native_source_bindings_direct_county_and_accepted_flanking_anchors','stage_before':22,'stage_after_proposed':23,'before':before,'after':after,'net_ordinary_weak_population_by_year':{y:after[y]['covered_population']-before[y]['covered_population'] for y in before},'new_edges':len(edges),'new_point_uses':len(points),'new_full3_entities':len({s.uf.find(sid) for sid in new_full-before_full}),'existing_points_overridden':0,'native_values_modified':False,'historical_county':'UNKNOWN where nativecaptionmissing; acceptedflankinganchorcontext keptseparate','administrative_event_date':'UNKNOWN','population_boundary_comparability_asserted':False,'root_authorization':'Root explicitlyapproved all7 positiveboundedcases; application waited for parentbaseline22 freeze','inputs':{str(p):sha(p) for p in [witness,I/'candidate_receipt.json',R/'research_rebuild/mass_linkage/working_state_20261007.py']},'outputs':{p.name:sha(p) for p in O.glob('*.csv')}};(O/'application_receipt.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n');print(json.dumps({k:v for k,v in receipt.items() if k not in ['inputs','outputs','before','after']},ensure_ascii=False))
