from pathlib import Path
import sys,json,collections
import pandas as pd,duckdb
O=Path(__file__).parent;E=O.parent;R=E.parent.parent;sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from current_chain_state_20261007 import sha,distance_km
from build_long_table import ACCEPTED_COORDINATE_STATUSES
P=E/'primary_residual_mass_application_20261008/applied_point_snapshot.parquet';C=E/'primary_residual_mass_application_20261008/applied_component_snapshot.csv.gz';A=E/'primary_residual_mass_application_20261008/application_receipt.json';CRE=E/'primary_residual_mass_application_20261008/applied_primary_credited_UID_roster.csv.gz';F=O/'source_positive_article_ownpoint_candidates.csv.gz';c=duckdb.connect();f=pd.read_csv(F,keep_default_na=False);comp=c.execute('select source_record_id,root,has_own_point from read_csv_auto(?)',[str(C)]).fetchdf();points=c.execute('select source_record_id,latitude,longitude,coordinate_admission_status,coordinate_source_record_id,point_origin_file,point_origin_locator from read_parquet(?)',[str(P)]).fetchdf();unknown=set(points.coordinate_admission_status)-ACCEPTED_COORDINATE_STATUSES;assert not unknown,unknown;c.register('targets',f[['source_record_id']]);credited=set(c.execute('select c.source_record_id from read_csv_auto(?) c join targets using(source_record_id)',[str(CRE)]).fetchdf().source_record_id);c.close();roots=comp.set_index('source_record_id').root.to_dict();memberpoints=collections.defaultdict(list);occupied=collections.defaultdict(set);newcoords=collections.Counter(zip(f.latitude,f.longitude))
for z in points.to_dict('records'):
 sid=z['source_record_id'];z['latitude']=float(z['latitude']);z['longitude']=float(z['longitude']);memberpoints[roots[sid]].append(z)
 if sid.startswith('2021:'):occupied[(z['latitude'],z['longitude'])].add(sid)
pointids=set(points.source_record_id);accepted=[];witness=[];holds=[]
for z in f.to_dict('records'):
 sid=z['source_record_id'];assert sid in roots;root=roots[sid];xy=(float(z['latitude']),float(z['longitude']));reasons=[];far=[]
 if sid in pointids:reasons.append('already_has_actual_stage62_ownpoint')
 if occupied[xy]-{sid}:reasons.append('same_coordinate_other_actual_stage62_current_NP')
 if newcoords[xy]>1:reasons.append('same_new_representative_point_multiple_current_NP')
 for p in memberpoints[root]:
  d=distance_km(xy,(p['latitude'],p['longitude']))
  if d>5:far.append({**p,'distance_km':d})
 if far:reasons.append('other_actual_stage62_component_ownpoint_over5km')
 z.update(actual_stage62_component_root=root,actual_stage62_primary_axis_already_credited=sid in credited,actual_stage62_other_component_ownpoints=len(memberpoints[root]),actual_stage62_component_spatial_conflict_witnesses_json=json.dumps(far,ensure_ascii=False),actual_stage62_other_current_exact_coordinate_occupants_json=json.dumps(sorted(occupied[xy]-{sid})))
 if reasons:holds.append({**z,'stage62_point_admission_hold_reasons':';'.join(reasons)});continue
 provider=bool(z.get('external_provider_ID_binding_asserted',False));cid=json.loads(z['native_primary_row_json']).get('fias_id_dadata','') if provider else f"ruwiki:{z['article_pageid']}:{z['article_revision_id']}";rule='Proper own NP article/revision infobox or identity-supported unique owncoded FIAS6 point; exact closed own name or reopened full native P764/own literal NPcode; physical subtype/region/printed county; native samecounty rivals retained and owncode/specificparish required; actualStage62 component5km and distinct current point checked; supplierIDbinding independent from coordinate correctness'
 accepted.append({'target_source_record_id':sid,'latitude':xy[0],'longitude':xy[1],'coordinate_admission_status':'reviewed_extension_rule_accepted','coordinate_source_record_id':cid,'point_origin_file':z['point_origin_file'],'point_origin_sha256':z['point_origin_sha256'],'point_origin_locator':z['point_origin_locator'],'point_origin_kind':z.get('point_origin_kind','own_physicalNP_article_revision_infobox'),'coordinate_binding_rule':rule,'point_use_inference':'modern own representative geography associated to explicitly source-bound2021 ownNP; census-date coordinate measurement and boundary comparability not asserted','historical_census_coordinate_asserted':False,'population_boundary_comparability_asserted':False,'external_provider_ID_binding_asserted':provider,'native2021_own_oktmo':str(json.loads(z['native_primary_row_json'])['oktmo']),'actual_stage62_primary_axis_already_credited':sid in credited})
 witness.append(z)
for n,d in [('accepted_point_use_delta',accepted),('accepted_source_bound_ownpoint_evidence',witness),('stage62_point_admission_holds',holds)]:pd.DataFrame(d).to_csv(O/(n+'.csv.gz'),index=False,compression={'method':'gzip','mtime':0,'compresslevel':9})
r={'baseline_stage':62,'actual_stage62_component_snapshot_source_IDs':len(comp),'actual_stage62_accepted_ownpoint_claims':len(points),'source_positive_current_candidates':len(f),'accepted_new_current_ownpoints':len(accepted),'accepted_known_population2021':sum(float(z['population']) for z in witness),'point_claim_kind_counts':dict(collections.Counter(z['point_origin_kind'] for z in accepted)),'already_primary_axis_credited_accepted_rows':sum(z['actual_stage62_primary_axis_already_credited'] for z in witness),'already_primary_axis_credited_accepted_population2021':sum(float(z['population']) for z in witness if z['actual_stage62_primary_axis_already_credited']),'uncredited_source_positive_population2021_not_a_gain_claim':sum(float(z['population']) for z in witness if not z['actual_stage62_primary_axis_already_credited']),'spatial_or_duplicate_holds':len(holds),'source_counts_population_qualities_identity_graph_unchanged':True,'main_axis_or_finite_gain':'root actualStage63 replay required; no main-axis gain inferred from ownpoint count/population','input_pins':{str(p):sha(p) for p in [P,C,A,CRE,F,O/'screen_stage62.py',O/'article_source_review_receipt.json']},'output_pins':{str(O/(n+'.csv.gz')):sha(O/(n+'.csv.gz')) for n in ['accepted_point_use_delta','accepted_source_bound_ownpoint_evidence','stage62_point_admission_holds']}};(O/'stage62_point_admission_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n');print(json.dumps({k:v for k,v in r.items() if k not in ['input_pins','output_pins']},ensure_ascii=False))
