from pathlib import Path
import json,hashlib,math
import pandas as pd
R=Path('/workspace/russian-settlements-research');O=Path(__file__).parent;S=Path('/dev/shm/over500-20261009/thirteenth-application');B=Path('/dev/shm/settlements-stage71-20261009');recipe=Path('/dev/shm/over500-20261009/thirteenth_recipe.json');sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();pins={};f=pd.read_parquet(S/'applied_state_observations.parquet').fillna('');base=pd.read_parquet(B/'applied_state_observations.parquet',columns=['source_record_id','root']).set_index('source_record_id');overlaypath=B/'applied_primary_population_source_overlay_2010.csv.gz';ov=pd.read_csv(overlaypath,low_memory=False).set_index('original_source_record_id');f['effective_population']=pd.to_numeric(f.population,errors='coerce');mask=f.census_year.eq(2010)&f.source_record_id.isin(ov.index);f.loc[mask,'effective_population']=f.loc[mask,'source_record_id'].map(ov.population);b=f.set_index('source_record_id');status=pd.read_csv(S/'all_whole_NP_over500_record_status.csv.gz',low_memory=False);whole500=set(status.source_record_id);rows=[];seen=set();skippedbase=0;inputedges=0
assert (S/'application_receipt.json').is_file(),'Require completed actualapplication receipt'
for p in [S/'application_receipt.json',recipe,S/'applied_state_observations.parquet',B/'applied_state_observations.parquet',overlaypath,S/'all_whole_NP_over500_record_status.csv.gz']:pins[str(p)]=sha(p)
for rel in json.loads(recipe.read_text())['edges']:
 q=R/rel;pins[str(q)]=sha(q);d=pd.read_csv(q).fillna('')
 for z in d.to_dict('records'):
  inputedges+=1;a=z['from_source_record_id'];c=z['to_source_record_id'];pair=tuple(sorted([a,c]))
  if pair in seen:continue
  seen.add(pair)
  if a in base.index and c in base.index and base.loc[a,'root']==base.loc[c,'root']:skippedbase+=1;continue
  assert a in b.index and c in b.index
  if a not in whole500 and c not in whole500:continue
  assert b.loc[a,'root']==b.loc[c,'root'],'Recipeedge not actually admitted in appliedsnapshot'
  if int(b.loc[a,'census_year'])>int(b.loc[c,'census_year']):a,c=c,a
  assert int(b.loc[a,'census_year'])<int(b.loc[c,'census_year'])
  row=dict(earlier_source_record_id=a,later_source_record_id=c,earlier_year=int(b.loc[a,'census_year']),later_year=int(b.loc[c,'census_year']),earlier_name=b.loc[a,'settlement_name'],later_name=b.loc[c,'settlement_name'],region=b.loc[a,'region_norm'],earlier_population_quality=b.loc[a,'population_value_quality'],later_population_quality=b.loc[c,'population_value_quality'],edge_ledger=str(q),edge_admission_rule=z.get('admission_rule',''),earlier_wholeNP_over500=a in whole500,later_wholeNP_over500=c in whole500)
  for axis in ['population','effective_population']:
   lo=float(b.loc[a,axis]);hi=float(b.loc[c,axis]);prefix='raw' if axis=='population' else 'effective_overlay';row[prefix+'_earlier']=lo;row[prefix+'_later']=hi;finite=math.isfinite(lo) and math.isfinite(hi);ratio=hi/lo if finite and lo>0 else None;reverse=lo/hi if finite and hi>0 else None;row[prefix+'_forward_ratio']=ratio;row[prefix+'_reverse_ratio']=reverse;row[prefix+'_forward_gt21']=ratio is not None and ratio>21;row[prefix+'_reverse_gt21']=reverse is not None and reverse>21;row[prefix+'_zero_nonzero_transition']=finite and ((lo==0 and hi>0) or (hi==0 and lo>0))
  rows.append(row)
out=pd.DataFrame(rows);flag=out[[x for x in out if x.endswith('_gt21') or x.endswith('_zero_nonzero_transition')]].any(axis=1);anom=out[flag].copy();anom['disposition']='numerical_sourcebinding_review_trigger_only; realgrowth/notfalseidentity_by_ratio';anom.to_csv(O/'new_identity_population_ratio_anomalies.csv',index=False);out.drop(columns=['edge_admission_rule']).to_csv(O/'all_screened_new_identity_edges.csv.gz',index=False)
receipt={'status':'readonly_actual_thirteenth_new_edge_growth_screen','scope':'Recipe direct sameplace edgepairs minus baseline71 connectedpairs; at least one actual wholeNP raw/effective population>500 endpoint. Native and officialprimary2010overlay separately.','strict_ratio_threshold':21,'growth_percent_threshold':2000,'zero_denominators':'Separate zero/nonzero flag, not finite >21ratio claim','recipe_input_edges':inputedges,'deduplicated_pairs':len(seen),'baselineconnected_pairs_excluded':skippedbase,'screened_wholeNP_pairs':len(out),'flagged_pairs':len(anom),'raw_gt21_pairs':int(out.raw_forward_gt21.sum()+out.raw_reverse_gt21.sum()),'effective_overlay_gt21_pairs':int(out.effective_overlay_forward_gt21.sum()+out.effective_overlay_reverse_gt21.sum()),'zero_transition_pairs':int((out.raw_zero_nonzero_transition|out.effective_overlay_zero_nonzero_transition).sum()),'population_counts_changed':False,'identity_edges_removed':False,'input_pins':pins,'output_pins':{str(q):sha(q) for q in [O/'new_identity_population_ratio_anomalies.csv',O/'all_screened_new_identity_edges.csv.gz']}};(O/'receipt.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n');print({k:v for k,v in receipt.items() if k.endswith('_pairs')})
