from pathlib import Path
import pandas as pd,json,gzip,sys,re
O=Path(__file__).parent;ROOT=O.parents[2];sys.path.insert(0,str(ROOT/'research_rebuild/mass_linkage'))
from working_state_20261007 import load
from current_chain_state_20261007 import sha,normalize,distance_km
s=load(24);f=pd.read_csv(O/'candidate_series.csv').fillna('');assert f.sid.nunique()==len(f) and f.qid.nunique()==len(f);samples=set(f.sort_values('qid').iloc[[round(i*(len(f)-1)/14) for i in range(min(15,len(f)))]].qid)|set(f.nlargest(5,'population').qid);cache={};checks=[];secondary=0;native=0;credit=[];errors=[]
for t in f.to_dict('records'):
 path=Path(t['entity_source_path']);assert sha(path)==t['entity_source_sha256']
 if str(path) not in cache:
  raw=path.read_bytes();e=json.loads(gzip.decompress(raw) if path.name.endswith('.gz') else raw);cache[str(path)]=e.get('entities',e.get('payload',{}).get('entities',{})) if 'claims' not in e else {e['id']:e}
 e=cache[str(path)][t['qid']];cs=e['claims'];q=t['qid'];sid=t['sid'];cur=s.by_id.loc[sid];assert cur.population==t['population'];ownlabel=e.get('labels',{}).get('ru',{}).get('value','');aliases=[v.get('value','') for v in e.get('aliases',{}).get('ru',[])];namebound=normalize(cur.settlement_name) in {normalize(v) for v in [ownlabel]+aliases};assert namebound or (t['own_code_positive'] and t['admin_source_positive'])
 p31=[z['mainsnak'].get('datavalue',{}).get('value',{}).get('id') for z in cs.get('P31',[])];assert not set(p31)&{'Q15284','Q1849719'};assert not cs.get('P576');assert not re.match(r'^(муниципаль|район\b|городской округ|сельсовет|сельское поселение|микрорайон|часть города|квартал)',t['own_description'].lower())
 witness=[]
 for v in json.loads(t['years']):
  if v['source_record_id']:
   n=s.by_id.loc[v['source_record_id']];assert s.uf.find(v['source_record_id'])==s.uf.find(sid) and n.population==v['population'] and n.population_value_quality==v['native_quality'] and n.is_additive_settlement_record;native+=1
   witness.append({'year':v['year'],'kind':'existing_native_component_census','source_record_id':v['source_record_id'],'population':float(n.population),'name':n.settlement_name,'type':n.settlement_type,'region':n.region_norm,'county':str(n.district_raw),'source_file':str(n.source_file),'source_quality':n.population_value_quality,'legacy_scope_null':pd.isna(n.population_scope)})
  else:
   st=next(z for z in cs['P1082'] if z['id']==v['statement_id']);assert float(st['mainsnak']['datavalue']['value']['amount'])==v['population'];assert st.get('rank')!='deprecated' and not st.get('qualifiers',{}).get('P518');assert any(d.get('datavalue',{}).get('value',{}).get('time')==v['declared_date'] and d['datavalue']['value']['precision']==v['date_precision'] for d in st['qualifiers']['P585']);assert v['census_proof'];secondary+=1;witness.append(v)
 for oldid in json.loads(t['native_old_net_IDs']):
  n=s.by_id.loc[oldid];credit.append({'source_record_id':oldid,'year':int(n.census_year),'source_population':float(n.population),'current_source_record_id':sid,'wikidata_id':q,'binding':'existing_accepted_same_place_component','candidate_only':True})
 credit.append({'source_record_id':sid,'year':2021,'source_population':float(cur.population),'current_source_record_id':sid,'wikidata_id':q,'binding':'current_native_own_point','candidate_only':True})
 if q in samples:checks.append({'qid':q,'current_source_record_id':sid,'current_name':cur.settlement_name,'current_type':cur.settlement_type,'current_region':cur.region_norm,'current_county':str(cur.district_raw),'current_population':float(cur.population),'own_label':ownlabel,'own_description':t['own_description'],'P31_ids':json.dumps(p31),'code_admin_source_witnesses':t['source_code_witnesses'],'population_and_scope_witnesses_json':json.dumps(witness,ensure_ascii=False),'source_path':str(path),'source_sha256':sha(path),'status':'pass; own physical locality; secondary actual census only; native counts/qualities retained; unknown boundaries'})
pd.DataFrame(checks).to_csv(O/'fixed15_and_largest5_source_checks.csv',index=False);cr=pd.DataFrame(credit).drop_duplicates('source_record_id');cr.to_csv(O/'unique_native_source_id_net_potential.csv',index=False)
network=json.loads((O/'network_receipt.json').read_text());receipt={'status':'candidate_only_verified_not_applied','baseline_stage':24,'candidate_series':len(f),'observations':len(f)*3,'secondary_historical_actual_GUID_date_value_checks':secondary,'native_existing_component_historical_checks':native,'fixed15_plus_largest5_sample_cases':len(checks),'native_source_ID_net_potential':{str(y):{'rows':len(g),'population':int(g.source_population.sum())} for y,g in cr.groupby('year')},'API_requests':network['requests_made'],'network_status':network['status'],'compressed_raw_cache_bytes':network['compressed_cache_bytes'],'Retry_After_exact_last_response':network['records'][-1].get('Retry_After_exact'),'coordinate_bounds':'UNKNOWN','error_rate':'uncalibrated','secondary_values_nonadditive_national_credit':0,'ordinary_graph_modified':False,'outputs':{p.name:sha(p)for p in [O/'candidate_series.csv',O/'holds.csv',O/'source_manifest.json',O/'unique_native_source_id_net_potential.csv',O/'fixed15_and_largest5_source_checks.csv',O/'network_receipt.json']}};(O/'verification_receipt.json').write_text(json.dumps(receipt,indent=2,ensure_ascii=False));print(json.dumps(receipt,ensure_ascii=False))
