from pathlib import Path
import json,hashlib,re,gzip
import pandas as pd
O=Path(__file__).parent;E=O.parent;sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();W=O/'accepted_source_bound_ownpoint_evidence.csv.gz';w=pd.read_csv(W,dtype=str,keep_default_na=False);entities=json.loads(gzip.open(O/'own_article_entities_index.json.gz','rt').read());proof=[]
for z in w.to_dict('records'):
 if z['point_origin_kind']=='own_physicalNP_article_revision_infobox':
  lit=json.loads(z['coordinate_literal_json']);xy=[]
  for axis in ['lat','lon']:
   p=[float(lit.get(axis+'_'+a,'').replace(',','.')) if lit.get(axis+'_'+a,'') else 0 for a in ['deg','min','sec']];v=p[0]+p[1]/60+p[2]/3600
   if lit.get(axis+'_dir','').upper() in ['W','S','З','Ю']:v=-abs(v)
   xy.append(v)
  assert xy==[float(z['latitude']),float(z['longitude'])];proof.append('literal ownNP infobox DMS/decimal coordinate reopened and exact computed float checked')
 else:
  q=z['live_own_article_QID'];e=entities[q];vals=[]
  for claim in e['entity'].get('claims',{}).get('P625',[]):
   v=claim.get('mainsnak',{}).get('datavalue',{}).get('value',{})
   if claim.get('rank')!='deprecated' and isinstance(v,dict) and v.get('globe','').endswith('/Q2') and 41<=float(v.get('latitude',0))<=82 and -180<=float(v.get('longitude',999))<=180:vals.append((float(v['latitude']),float(v['longitude'])))
  assert len(set(vals))==1 and next(iter(set(vals)))==(float(z['latitude']),float(z['longitude']));assert e['origin_file']==z['point_origin_file'] and sha(Path(e['origin_file']))==z['point_origin_sha256'];proof.append('single ownarticle-linked QID nondeprecated Earth P625 literal value reopened, complete rawclaims retained, no first coordinate selected')
 assert sha(Path(z['point_origin_file']))==z['point_origin_sha256'];assert sha(Path(z['article_identity_source_file']))==z['article_identity_source_sha256']
w['literal_admitted_point_source_reopened_validation']=proof;w.to_csv(W,index=False,compression={'method':'gzip','mtime':0,'compresslevel':9})
rp=O/'joint64_point_admission_receipt.json';r=json.loads(rp.read_text());r['output_pins'][str(W)]=sha(W);r['input_pins'][str(O/'finalize_packet.py')]=sha(O/'finalize_packet.py');r['all_admitted_point_literals_and_article_identity_bytes_reopened']=True;rp.write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n')
f=pd.read_csv(E/'current_remaining_cached_named_sources_20261008/prioritized_unresolved_after_cached_named.csv.gz',dtype=str,keep_default_na=False);rem=f[~f.source_record_id.isin(w.source_record_id)].copy();h=pd.read_csv(O/'article_binding_holds.csv.gz',dtype=str,keep_default_na=False);h=h[~h.source_record_id.isin(w.source_record_id)];reason=h.groupby('source_record_id').hold_reasons.agg(lambda s:';'.join(sorted(set(';'.join(s).split(';'))))).to_dict();rem['live_own_article_hold_reasons']=rem.source_record_id.map(reason).fillna('');reviewed=set(pd.read_csv(O/'all_article_binding_checks.csv.gz',dtype=str,keep_default_na=False).source_record_id);rem['live_source_status']=rem.source_record_id.map(lambda s:'reviewed_own_article_source_binding_held' if s in reason else 'no_reviewed_source_positive_own_article');rem.to_csv(O/'prioritized_unresolved_after_live_sources.csv.gz',index=False,compression={'method':'gzip','mtime':0,'compresslevel':9});h.to_csv(O/'unresolved_article_source_binding_holds.csv.gz',index=False,compression={'method':'gzip','mtime':0,'compresslevel':9})
fetch=json.loads((O/'live_source_fetch_receipt.json').read_text());saved=[x for x in fetch['search_raw_response_pins'] if x.get('source_file')];r.update(unresolved_current_missing_ownpoint_rows=len(rem),unresolved_current_known_population2021=float(pd.to_numeric(rem.population,errors='coerce').sum()),remaining_positive100_NPs=int((pd.to_numeric(rem.population,errors='coerce')>=100).sum()),unresolved_reviewed_article_binding_held_NPs=h.source_record_id.nunique(),unresolved_reviewed_article_comparison_holds=len(h),live_search_attempted_queries=256,live_search_saved_raw_responses=len(saved),live_search_queries_without_saved_source_response=256-len(saved),live_search_unavailable_is_hold_not_negative_evidence=True,source_population_unknown_not_imputed=True,generated_pack_status='frozen_ready_future64_root_replay_pending');(O/'final_handoff_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n')
(O/'README.md').write_text('''# Live named positive current residual sources, stage 63 → 64

Frozen delta: **28 current settlement ownpoints /8,823 known 2021 residents**, all with at least 100 residents. All pass actual final stage 63 component 5 km consistency, existing current point occupation within 1 m, and joint newpoint distinctness. Zero compatibility holds and zero already-primary-axis-credited rows. Actual coverage gain requires root's future stage 64 replay.

`accepted_point_use_delta.csv.gz` is replay-ready. `accepted_source_bound_ownpoint_evidence.csv.gz` retains the raw native NP row, every samecounty native rival, proper article name/type/region/county/parish, own full native code evidence, full infobox and lead/geography excerpts, pinned page/revision IDs, literal coordinate fields, source hashes and locators, and explicit provider-binding limits.

25 points are literal proper ownNP article infobox coordinates. Three blank-infobox articles use one unique nondeprecated Earth P625 value from the article-linked own QID only after independently checking the physical ownNP article's native association. Complete Wikidata claims are retained; multiple distinct P625 values without a selection witness are held. No point is selected by first hit, similarity, provider quality score, or proximity alone.

Direct reopened literal own full native P764 or own infobox NP code can resolve source spelling variants and an explicit physical NP subtype difference, when the native full code belongs to one NP and both source and article positively describe a physical settlement. This is representative-geography association, without a historical legal-type-change or population-boundary claim. Specific native parishes can resolve county homonyms. Explicit native station-settlement wording and the published own NP infobox status `посёлок при станции` can distinguish that physical NP from every plain samecounty namesake; pure railway infrastructure pages are held. Station Егозово (993 residents) uses this positive rule, not the wrong original provider code or a first homonym.

Every admitted point literal and source hash was reopened during freezing. Original external provider identifier bindings remain unasserted. Coordinates represent modern own settlement geography, not exact census-day measurements. No old point, code, population, quality, identity edge, or canonical file was changed.

The bounded live sweep covered 128 missing-ownpoint NPs with at least 100 residents, using name+county and name+region searches. Normal TLS was used. 70 search responses were saved out of 256 attempted queries; API HTTP429 rate limiting left 186 queries without a saved response. Requests were then paced and backed off, and successful responses reused without retrying the unavailable search cohort. Missing responses are explicit source gaps, never absence-of-locality evidence. All 215 plausible closed-name target/article pairs were reviewed: 153 new articles were fetched in 11 revision batches, 61 existing cached articles reused, and article-linked own QIDs fetched in batches of 40. All source witnesses are retained.

`unresolved_article_source_binding_holds.csv.gz` contains only held NPs still unresolved after the admitted packet; rejected alternatives for admitted NPs remain in the complete review ledger. `prioritized_unresolved_after_live_sources.csv.gz` preserves the complete remaining current cohort with unknown populations unmodified. Existing large final stage 63 snapshots are referenced by frozen hashes; State was not reloaded. Earlier stage 63 point packets remain untouched. Root owns integration and commits.
''')
files=[p for p in O.iterdir() if p.is_file() and p.name!='frozen_asset_manifest.json'];m={'packet_status':'frozen_ready_future64_root_replay_pending','accepted_new_current_ownpoints':len(w),'accepted_known_population2021':8823,'assets':{str(p):{'sha256':sha(p),'bytes':p.stat().st_size} for p in sorted(files)},'generated_total_bytes':sum(p.stat().st_size for p in files),'budget_bytes':20_000_000,'upstream_pins':r['input_pins']};assert m['generated_total_bytes']<m['budget_bytes'];(O/'frozen_asset_manifest.json').write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n');print(json.dumps({k:v for k,v in r.items() if k not in ['input_pins','output_pins']},ensure_ascii=False));print('manifest_sha256',sha(O/'frozen_asset_manifest.json'));print('bytes',m['generated_total_bytes'])
