from pathlib import Path
import sys,json,collections,math
import pandas as pd,duckdb,numpy as np
from scipy.spatial import cKDTree
O=Path(__file__).parent;E=O.parent;R=E.parent.parent;sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from current_chain_state_20261007 import sha,distance_km
from build_long_table import ACCEPTED_COORDINATE_STATUSES
B=E/'main_axis_residual_application63_20261008';P=B/'applied_point_snapshot.parquet';C=B/'applied_component_snapshot.csv.gz';A=B/'application_receipt.json';CRE=B/'applied_primary_credited_UID_roster.csv.gz';F=O/'source_positive_article_ownpoint_candidates.csv.gz';f=pd.read_csv(F,keep_default_na=False,float_precision='round_trip')
c=duckdb.connect();comp=c.execute('select source_record_id,root,has_own_point from read_csv_auto(?)',[str(C)]).fetchdf();points=c.execute('select source_record_id,latitude,longitude,coordinate_admission_status,coordinate_source_record_id,point_origin_file,point_origin_locator from read_parquet(?)',[str(P)]).fetchdf();assert points.source_record_id.ne('').all() and points.source_record_id.is_unique;assert set(points.source_record_id)==set(comp.loc[comp.has_own_point,'source_record_id']);assert set(points.coordinate_admission_status)<=ACCEPTED_COORDINATE_STATUSES;c.register('targets',f[['source_record_id']]);credited=set(c.execute('select c.source_record_id from read_csv_auto(?) c join targets using(source_record_id)',[str(CRE)]).fetchdf().source_record_id);c.close();roots=comp.set_index('source_record_id').root.to_dict();memberpoints=collections.defaultdict(list)
for z in points.to_dict('records'):
 z['latitude']=float(z['latitude']);z['longitude']=float(z['longitude']);memberpoints[roots[z['source_record_id']]].append(z)
current=points[points.source_record_id.str.startswith('2021:')].copy();current.latitude=current.latitude.astype(float);current.longitude=current.longitude.astype(float)
def xyz(lat,lon):
 lat,lon=np.radians(np.asarray(lat,float)),np.radians(np.asarray(lon,float));return np.column_stack((np.cos(lat)*np.cos(lon),np.cos(lat)*np.sin(lon),np.sin(lat)))
tree=cKDTree(xyz(current.latitude,current.longitude));ntree=cKDTree(xyz(f.latitude,f.longitude));existing=current.to_dict('records');new=f.to_dict('records');pointids=set(points.source_record_id);accepted=[];witness=[];holds=[]
for i,z in enumerate(new):
 sid=z['source_record_id'];assert sid in roots;root=roots[sid];xy=(float(z['latitude']),float(z['longitude']));reasons=[];far=[];occupants=[];othernew=[];v=xyz([xy[0]],[xy[1]])[0]
 if sid in pointids:reasons.append('already_has_actual63_ownpoint')
 for j in tree.query_ball_point(v,1e-3/6371.009):
  if existing[j]['source_record_id']!=sid:occupants.append(existing[j])
 if occupants:reasons.append('distinct_current_actual63_ownpoint_within1m')
 for j in ntree.query_ball_point(v,1e-3/6371.009):
  if i!=j:othernew.append(new[j]['source_record_id'])
 if othernew:reasons.append('joint_new_point_within1m_multiple_current_NPs')
 for p in memberpoints[root]:
  d=distance_km(xy,(p['latitude'],p['longitude']))
  if d>5:far.append({**p,'distance_km':d})
 if far:reasons.append('positive_current_ownpoint_incompatible_existing_component_old_or_current_point_over5km_no_supersession')
 z.update(actual63_component_root=root,actual63_primary_axis_already_credited=sid in credited,actual63_other_component_ownpoints=len(memberpoints[root]),joint64_component_conflict_witnesses_json=json.dumps(far,ensure_ascii=False),joint64_distinct_current_occupants_within1m_json=json.dumps(occupants,ensure_ascii=False),joint_new_distinct_current_points_within1m_json=json.dumps(othernew,ensure_ascii=False))
 if reasons:holds.append({**z,'joint64_admission_hold_reasons':';'.join(reasons)});continue
 accepted.append({'target_source_record_id':sid,'latitude':xy[0],'longitude':xy[1],'coordinate_admission_status':'reviewed_extension_rule_accepted','coordinate_source_record_id':f"ruwiki:{z['article_pageid']}:{z['article_revision_id']}" if z['point_origin_kind']=='own_physicalNP_article_revision_infobox' else z['live_own_article_QID'],'point_origin_file':z['point_origin_file'],'point_origin_sha256':z['point_origin_sha256'],'point_origin_locator':z['point_origin_locator'],'point_origin_kind':z['point_origin_kind'],'coordinate_binding_rule':'physical own NP article/revision positive name/type/region/county and all native samecounty name rivals; exact own native fullcode or specific parish or explicit published physical station-settlement role excluding every plain namesake when needed; single proper ownQID Earth P625 only with independent source-bound ownarticle identity if infobox coordinates absent; subtype difference permitted only with direct fullowncode and unique native NP code' +'; actual63 baseline activepoints and allnewpoints checked: ownpoint present/physical current occupation<=1m/component5km; actualfuture64 canonical replay remains composer responsibility','point_use_inference':'modern explicitly sourcebound own settlement representative geography; census-date coordinate measurement and population boundary comparability unasserted','historical_census_coordinate_asserted':False,'population_boundary_comparability_asserted':False,'external_provider_ID_binding_asserted':False,'native2021_own_oktmo':str(json.loads(z['native_primary_row_json'])['oktmo']),'actual63_primary_axis_already_credited':sid in credited});witness.append(z)
for n,d in [('accepted_point_use_delta',accepted),('accepted_source_bound_ownpoint_evidence',witness),('joint64_point_admission_holds',holds)]:pd.DataFrame(d).to_csv(O/(n+'.csv.gz'),index=False,compression={'method':'gzip','mtime':0,'compresslevel':9})
pop=lambda zs:sum(float(z['population']) for z in zs if str(z['population']).strip())
r={'baseline_stage':63,'planned_working_stage':64,'screen_basis':'actual63 baseline accepted point/component snapshots and all joint new live source points; actualfuture64 replay validates finaladmission','source_positive_current_candidates':len(f),'accepted_new_current_ownpoints':len(accepted),'accepted_known_population2021':pop(witness),'accepted_positive100_NPs':sum(float(z['population'] or 0)>=100 for z in witness),'point_claim_kind_counts':dict(collections.Counter(z['point_origin_kind'] for z in accepted)),'already_primary_axis_credited_accepted_rows':sum(z['actual63_primary_axis_already_credited'] for z in witness),'already_primary_axis_credited_accepted_population2021':sum(float(z['population']) for z in witness if z['actual63_primary_axis_already_credited'] and z['population']),'uncredited_source_positive_population2021_not_a_gain_claim':sum(float(z['population']) for z in witness if not z['actual63_primary_axis_already_credited'] and z['population']),'spatial_or_duplicate_holds':len(holds),'spatial_or_duplicate_held_population':pop(holds),'source_positive_conflicting_component_claims_preserved_not_superseded':True,'source_counts_population_qualities_identity_graph_unchanged':True,'main_axis_or_finite_gain':'root actualfuture64 replay required; no main-axis gain inferred from ownpoint count/population','input_pins':{str(p):sha(p) for p in [P,C,A,CRE,F,O/'screen_actual63.py',O/'article_source_review_receipt.json',O/'live_source_fetch_receipt.json']},'output_pins':{str(O/(n+'.csv.gz')):sha(O/(n+'.csv.gz')) for n in ['accepted_point_use_delta','accepted_source_bound_ownpoint_evidence','joint64_point_admission_holds']}};(O/'joint64_point_admission_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n');print(json.dumps({k:v for k,v in r.items() if k not in ['input_pins','output_pins']},ensure_ascii=False))
