from pathlib import Path
import pandas as pd,json,gzip,hashlib,xlrd,math
O=Path(__file__).parent.resolve();E=O.parent;B=E/'main_axis_residual_application68_20261008';sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();d=pd.read_csv(O/'all_native_perm_primorye_baseline68.csv.gz');p=pd.read_csv(O/'all_ownpoint_perm_primorye_baseline68.csv.gz',dtype=str,keep_default_na=False).set_index('target_source_record_id');assigned=pd.read_csv(E/'over1000_root_20261009/handoff_perm_primorye_actual101_roster.csv');wf=O/'own_wikipedia_batch1.json.gz';pgs={x['title']:x for x in json.load(gzip.open(wf,'rt'))['query']['pages'].values()};ids=lambda y,suf:next(s for s in d.source_record_id if s.startswith(str(y)+':')and s.endswith(':'+str(suf))and (y==2021 or ('051_'in s if y==2002 else '016_'in s)))
P02=lambda r:ids(2002,r);P10=lambda r:ids(2010,r);CUR=lambda r:'2021:data_allsettlements_anon_156_v20251217.parquet:parquet:'+str(r);PR02=lambda r:f'2002:079_983a1a85f7_Primor_krai_1.xls:Sheet1:{r}';PR10=lambda r:f'2010:009_81f8a0e73c_17._20ДВ_ФО_2010.xls:ДВ:{r}'
groups=[('Ergach_station_NP',[P02(2022),P10(6258),CUR(97024)],'exact_station_qualifier_printed_population_NP_vs_distinct_Ergach_village'),('Krasnoyar_I',[P02(633),P10(5225),CUR(95755)],'printedArabic1_to_RomanI_sameproperBarda_county'),('Krasnoyar_II',[P02(635),P10(5226),CUR(95756)],'printedArabic2_to_RomanII_sameproperBarda_county'),('Bardabashka_I',[P02(605),P10(5212),CUR(95770)],'printedArabic1_to_RomanI_sameproperBarda_county'),('Bardabashka_II',[P02(607),P10(5213),CUR(95771)],'printedArabic2_to_RomanII_sameproperBarda_county'),('Vilva_Dobryanka',[P02(88),P10(7862),CUR(98080)],'primaryprintedDobryanka_subordinateVilvensky_and2010ownDobrsourceorder_then_independentproperownarticle'),('Shumnoye_Shumny',[PR02(878),PR10(514),CUR(99591)],'actualproperChuguyevsky_sourcecounty_and_documentedownShumnoye_Shumny_nameforms')]
special=[('Letno_Khvalynskoye',[PR10(361),CUR(99920)],'Лётно-Хвалынское','2004-10-11','formal_separate_rural_NP_created_on_preexisting_military_town11_named2007;physicalmilitarypredecessor1932/1948_2002populationUNKNOWN'),('Avangard',[PR10(614),CUR(100138)],'Авангард (Приморский край)','2003','separate_NP_split2003_from_Uglekamensk_then_ruralstatus11Oct2004;pre2003ownpopulation_within_Uglekamensk_grainUNKNOWN')]
edges=[];points=[];rejs=[];credits=[];raws=[];proofs=[];status=[];avail=[];dispositions=[];ctx=[];rawbooks={}
def native_witness(sid):
 r=d[d.source_record_id.eq(sid)].iloc[0]
 if r.census_year==2021:
  f=Path('/workspace/settlements-raw')/r.source_file;loc='parquet:physicalrow1based='+sid.rsplit(':',1)[1];vals={'native_name':r.settlement_name,'native_type':r.settlement_type,'native_count':r.population,'native_own_OKTMO':str(r.oktmo),'native_county':r.district_raw}
 else:
  f=Path('/workspace/settlements-raw')/r.source_file;sn=sid.rsplit(':',2)[1];row=int(sid.rsplit(':',1)[1]);key=(str(f),sn)
  if key not in rawbooks:rawbooks[key]=xlrd.open_workbook(str(f)).sheet_by_name(sn)
  vals=rawbooks[key].row_values(row-1);loc=f'{sn}:physicalrow{row}';assert any(str(x).replace('.0','')==str(int(r.population))for x in vals)
 raws.append(dict(source_record_id=sid,census_year=r.census_year,native_population=r.population,native_population_quality=r.population_value_quality,source_path=str(f),source_sha256=sha(f),source_locator=loc,literal_cells_json=json.dumps(vals,ensure_ascii=False)))
 return r
minimal=['latitude','longitude','coordinate_source_record_id','point_origin_file','point_origin_sha256','point_origin_locator','point_origin_kind','source_sha256','source_locator']
for group,sids,rule in groups:
 rr=[native_witness(s)for s in sids];assert len(set(x.census_year for x in rr))==3
 donor=p.loc[sids[-1]].to_dict();donor={k:donor.get(k,'')for k in minimal};pg=None
 if group=='Vilva_Dobryanka':
  old=p.loc[sids[-1]];ledger=Path(old.point_ledger_path);rejs.append(dict(target_source_record_id=sids[-1],rejection_status='reviewed_rejected_coordinate_claim_only',old_latitude=old.latitude,old_longitude=old.longitude,origin_ledger=str(ledger),origin_ledger_sha256=sha(ledger),reason='OwnDobrVilva currentpointincorrectlybindsGornoVilva73kmE; preserveGornoownNPpointuses; nooldDob02/10acceptedpoint'))
  pg=pgs['Вильва (Добрянский район)'];co=pg['coordinates'][0];loc=f'pageid{pg["pageid"]}:revision{pg["revisions"][0]["revid"]}:coordinates[0]';donor=dict(latitude=co['lat'],longitude=co['lon'],coordinate_source_record_id=loc,point_origin_file=str(wf),point_origin_sha256=sha(wf),point_origin_locator=loc,point_origin_kind='independent_own_Wikipedia_Dobryanka_Vilva_physical_NP_representative_point',source_sha256=sha(wf),source_locator=loc)
  share=p[p.latitude.eq(old.latitude)&p.longitude.eq(old.longitude)][['latitude','longitude','point_ledger_path']].reset_index();share.to_csv(O/'all_baseline_members_sharing_Vilva_wrong_current_point.csv',index=False)
 for a,b in [(sids[0],sids[1]),(sids[1],sids[2])]:
  ra,rb=d[d.source_record_id.eq(a)].iloc[0],d[d.source_record_id.eq(b)].iloc[0]
  if ra.root==rb.root:continue
  edges.append(dict(decision_id=group+'_'+str(ra.census_year)+'_'+str(rb.census_year),from_source_record_id=a,to_source_record_id=b,relation='same_place',from_year=ra.census_year,to_year=rb.census_year,decision_status='checked_rule_accepted',decision_class=rule,decision_rule=rule,evidence_uri=str(O/'group_identity_and_ownpoint_proofs.json'),boundary_comparability='UNKNOWN',native_population_quality_unchanged=True))
 for r in rr:
  sid=r.source_record_id
  if sid not in p.index or group=='Vilva_Dobryanka':
   points.append(dict(donor,target_source_record_id=sid,coordinate_admission_status='reviewed_rule_accepted',decision_status='reviewed_rule_accepted',donor_target_source_record_id=sids[-1],own_locality_point=True,recipient_point_assigned_to_child=False,admission_rule=rule,point_temporal_interpretation='OwnsamephysicalNPmodernrepresentativepointusedretrospectively; directcensusdaycoordinates/boundarycomparabilityUNKNOWN',direct_historical_coordinate_measurement=False,provider_binding_asserted=False,native_population_quality_unchanged=True,point_binding_proof=str(O/'group_identity_and_ownpoint_proofs.json')))
  cp=donor if sid not in p.index or group=='Vilva_Dobryanka'else p.loc[sid].to_dict();credits.append(dict(source_record_id=sid,census_year=r.census_year,settlement_name=r.settlement_name,native_population=r.population,population_value_quality=r.population_value_quality,scope_id=group,temporal_path='ordinary_actual_three_census_native_identity',own_point=True,latitude=cp['latitude'],longitude=cp['longitude'],actual_handoff_UID=sid in set(assigned.source_record_id),native_source_counts_quality_unchanged=True,boundary_comparability='UNKNOWN'))
 proofs.append(dict(scope_id=group,native_UIDs=sids,identity_rule=rule,all_relevant_rivals_file=str(O/'expanded9group_all_rival_inventory.csv'),all_rivals_sha256=sha(O/'expanded9group_all_rival_inventory.csv'),own_current_point=donor,current_snapshot_source=str(B/'applied_point_snapshot.parquet'),current_snapshot_sha256=sha(B/'applied_point_snapshot.parquet'),native_fields_and_counts_preserved=True,boundary_comparability='UNKNOWN'))
for group,sids,title,date,reason in special:
 pg=pgs[title];t=pg['revisions'][0]['slots']['main']['*'];loc=f'pageid{pg["pageid"]}:revision{pg["revisions"][0]["revid"]}';rr=[native_witness(s)for s in sids];assert rr[0].root==rr[1].root and set(x.census_year for x in rr)=={2010,2021}and all(x in p.index for x in sids)
 aliases='летно|лётно|хвалын|военн|городок|гарниз'if group=='Letno_Khvalynskoye'else'авангард|углекамен';rivals=d[(d.census_year==2002)&d.region_norm.eq('приморский')&d.name_norm.str.contains(aliases,case=False,regex=True,na=False)];rivals.to_csv(O/(group+'_actual2002_predecessor_and_name_rivals.csv'),index=False)
 status.append(dict(scope_id=group,place=title,census_year=2002,source_record_id='',status='UNKNOWN_predecessor_population_and_sourceyear_publication_grain_before_formal_separate_NP_record',population='',unknown_is_zero=False,physical_absence_asserted=False,independent_separate_2002_NP_absence_vs_physical_predecessor_distinguished=True,sourcegrain_change=reason,event_date=date,event_date_precision='day'if'-'in date else'year',source_path=str(wf),source_sha256=sha(wf),source_locator=loc,literal_source=t,parent_population_assigned_to_child=False))
 for r in rr:
  cp=p.loc[r.source_record_id];cr=dict(source_record_id=r.source_record_id,census_year=r.census_year,settlement_name=r.settlement_name,native_population=r.population,population_value_quality=r.population_value_quality,scope_id=group,temporal_path='actual_available_year_2010_2021_after_explicit_formal_separate_NP_creation_or_split',own_point=True,latitude=cp.latitude,longitude=cp.longitude,actual_handoff_UID=True,native_source_counts_quality_unchanged=True,boundary_comparability='UNKNOWN',no_2002_population_imputed=True,sourcegrain_change=reason,event_date=date,event_source_path=str(wf),event_source_sha256=sha(wf),event_source_locator=loc);credits.append(cr);avail.append(cr);status.append(dict(scope_id=group,place=title,census_year=r.census_year,source_record_id=r.source_record_id,status='actual_published_separate_NP_native_observation',population=r.population,unknown_is_zero=False,physical_absence_asserted=False,parent_population_assigned_to_child=False,boundary_comparability='UNKNOWN'))
 proofs.append(dict(scope_id=group,native_UIDs=sids,temporal_path=reason,event_date=date,event_source_file=str(wf),event_source_sha256=sha(wf),event_source_locator=loc,literal_source=t,own_points={s:p.loc[s][minimal].to_dict()for s in sids},unknown2002_not_zero=True,physical_predecessor_not_invented_as_absent=True,parent_counts_not_allocated=True,boundary_comparability='UNKNOWN'))
# Additional literal primary source-context pins separate from imported district fields.
context_specs=[('/workspace/settlements-raw/data/raw/2002/051_46e3ecb0a0_02c_Permskaja_obl.xls','Sheet1',[80,81,82,83,84,85,86,87,88,633,635,2020,2021,2022,2099]),('/workspace/settlements-raw/data/raw/2010/016_802d308e41_8._20Or_Penz_Perm_Samar_Saratov_Uly_2010.xls','!!!',[5200,5212,5213,5224,5225,5226,6257,6258,6259,6324,7845,7859,7861,7862,7863,7957]),('/workspace/settlements-raw/data/raw/2010/009_81f8a0e73c_17._20ДВ_ФО_2010.xls','ДВ',[322,353,354,361,503,511,513,514,515,613,614]),('/workspace/settlements-raw/data/raw/2002_official_tom1/1_TOM_01_04.xls',0,[9961,9962,9963,9964,9965])]
for f,sn,rows in context_specs:
 book=xlrd.open_workbook(f);sh=book.sheet_by_index(sn)if isinstance(sn,int)else book.sheet_by_name(sn)
 for row in rows:ctx.append(dict(source_path=f,source_sha256=sha(f),source_locator=f'sheet{sh.name}:physicalrow{row}',literal_cells_json=json.dumps(sh.row_values(row-1)[:9],ensure_ascii=False),sourcecontext_only=True,imported_metadata_overwritten=False,native_counts_overwritten=False))
for r in assigned.itertuples():
 cc=next(x for x in credits if x['source_record_id']==r.source_record_id);dispositions.append(dict(source_record_id=r.source_record_id,census_year=r.census_year,native_population=r.population,scope_id=cc['scope_id'],disposition='ready_verified_ordinary_actual_three_census_path'if cc['temporal_path'].startswith('ordinary')else'ready_verified_available_year_separate_NP_path_2002_unknown_grain',population_quality_unchanged=True,own_point=True))
for n,rows in [('accepted_identity_edge_delta.csv',edges),('accepted_point_use_delta.csv',points),('reviewed_point_use_rejections.csv',rejs),('accepted_native_UID_credits.csv',credits),('accepted_available_year_native_credit_union.csv',avail),('accepted_available_year_statuses.csv',status),('literal_native_source_row_witnesses.csv',raws),('literal_primary_context_witnesses.csv',ctx),('all13_handoff_UID_dispositions.csv',dispositions)]:pd.DataFrame(rows).to_csv(O/n,index=False)
(O/'group_identity_and_ownpoint_proofs.json').write_text(json.dumps(proofs,ensure_ascii=False,indent=2,default=str)+'\n')
# bounded State-compatible region UF replay, native year collision guard and point completeness.
rt=dict(zip(d.source_record_id,d.root));parent={x:x for x in d.root.unique()};yrs={r:set(g.census_year)for r,g in d.groupby('root')}
def find(a):
 while parent[a]!=a:a=parent[a]
 return a
for e in edges:
 a,b=find(rt[e['from_source_record_id']]),find(rt[e['to_source_record_id']]);assert a!=b and not yrs[a]&yrs[b];parent[a]=b;yrs[b]|=yrs[a]
pointids=set(p.index)|{r['target_source_record_id']for r in points};assert all(set(x for x in sids)<=pointids and len({find(rt[s])for s in sids})==1 and yrs[find(rt[sids[0]])]=={2002,2010,2021}for _,sids,_ in groups)
assert len(dispositions)==13 and set(x['source_record_id']for x in dispositions)==set(assigned.source_record_id)
receipt=dict(status='READY_FROZEN',baseline68_with_actual101_remaining_roster=True,ordinary_three_census_groups=7,available_year_separate_NP_groups=2,groups=9,ordinary_edges=len(edges),own_point_uses=len(points),explicit_wrong_point_rejections=len(rejs),assigned13_ready=13,assigned13_native_population=sum(x['native_population']for x in dispositions),new_native_credit_UID_count=len(credits),new_native_population_by_year={str(k):float(v)for k,v in pd.DataFrame(credits).groupby('census_year').native_population.sum().items()},bounded_region_State_compatible_replay_passed=True,native_count_edits=0,raw_imported_county_labels_edited=False,missing2002_for_Letno_and_Avangard_unknown_not_zero=True,remaining_assigned_UIDs=0,population_boundary_comparability='UNKNOWN',current_point_Vilva_wrong_Gorno_rejected=True)
(O/'FINAL_packet_receipt.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n');mf=dict(status='FINAL_FROZEN',files=[dict(path=f.name,bytes=f.stat().st_size,sha256=sha(f))for f in sorted(O.iterdir())if f.is_file()and not f.name.startswith('FINAL_manifest')]);(O/'FINAL_manifest.json').write_text(json.dumps(mf,ensure_ascii=False,indent=2)+'\n');h=sha(O/'FINAL_manifest.json');(O/'FINAL_manifest.sha256').write_text(h+'  FINAL_manifest.json\n');print(receipt);print(h)
