from pathlib import Path
import pandas as pd,json,gzip,hashlib,xlrd,re
from bs4 import BeautifulSoup
from urllib.parse import urlparse,parse_qs
O=Path(__file__).parent;A=Path('research_rebuild/evidence/over500_east_last_source_followup_20261009');D=pd.read_pickle('/dev/shm/over500-20261009/east_enriched.pkl');sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();W=[];P=[];raw=[]
S=[('2002:081_6a22d6b5c5_Amur.xls:Sheet1:523',1,'Дмитриевка (Ивановский район)','10228810001')]
for sid,n,title,code in S:
 t=D[D.source_record_id.eq(sid)].iloc[0];F=Path('research_rebuild/evidence/over500_east_final_five_sources_20261009/amur_rendered_2.json.gz');J=json.load(gzip.open(F));assert J['parse']['title']==title;soup=BeautifulSoup(J['parse']['text']['*'],'html.parser');txt=soup.get_text(' ',strip=True);assert code in txt;href=next(a['href']for a in soup.find_all('a',href=True)if 'geohack' in a['href']);parts=parse_qs(urlparse(href).query)['params'][0].split('_');assert parts[3]=='N'and parts[7]=='E';lat=float(parts[0])+float(parts[1])/60+float(parts[2])/3600;lon=float(parts[4])+float(parts[5])/60+float(parts[6])/3600
 nf=Path('/workspace/settlements-raw')/t.source_file;sh=xlrd.open_workbook(str(nf)).sheet_by_name('Sheet1');rn=int(sid.rsplit(':',1)[1])-1;cells=sh.row_values(rn);context=[]
 assert t.population==864 and 'Дмитриевка' in str(cells) and '864' in txt and 'Ивановский' in txt;anchors=[];context=[]
 rule='NativeoldселоДмитриевка864 withblankcounty uniquely matches qualified ownИвановский article code10228810001/10628410101 exactsamephysicaltype and actualrendered2002count864 as scope corroboration, not countonly matching. DistinctoldДмитриевка439 and214/nativeMazanovsky andcurrentSvobodnensky rivals retained and excluded. IndependentnamedOSMownresidentialrelation12994591 corroborates correctcounty/site. Sourcearticle2010count1020 differs native2010value966 and neither transferred; no ordinaryidentityedge/full3claim. Ownarticle representativepoint retrospective inference only.'

 raw.append(dict(source_record_id=sid,native_file=str(nf),sha256=sha(nf),raw_row0=rn,raw_cells=cells,source_context=context));wi=len(W);W.append(dict(target_source_record_id=sid,native_observation=t.fillna('').to_dict(),rendered_source_file=str(F),rendered_source_sha256=sha(F),pageid=J['parse']['pageid'],revid=J['parse']['revid'],retained_actual_rendered_ownsource_html=J['parse']['text']['*'],actual_geohack_coordinate_href=href,owncode=code,rule=rule,context_accepted_peers=anchors,census_count_preserved=True,sourcepoint_positional_accuracy_unknown=True))
 P.append(dict(target_source_record_id=sid,latitude=lat,longitude=lon,coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_source_record_id=f'wikipedia:ru:pageid={J["parse"]["pageid"]}',point_origin_file=str(F),point_origin_sha256=sha(F),point_origin_locator='parse.text.*;infoboxGeohackhrefparams',point_origin_kind='direct_source_bound_own_article_rendered_infobox_coordinate',coordinate_binding_rule=rule,point_use_inference='Explicit ownlocality representative point inference; censusday measurement and population boundaries unknown.',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,external_provider_ID_binding_asserted=True,evidence_file=str(O/'point_binding_witnesses.json.gz'),evidence_locator=f'[{wi}]'))
pd.DataFrame(P).to_csv(O/'accepted_point_use_delta.csv',index=False);pd.DataFrame(columns=['from_source_record_id','to_source_record_id','relation','decision_status','admission_method','admission_rule','evidence_file','evidence_locator']).to_csv(O/'accepted_identity_edge_delta.csv',index=False);pd.DataFrame([dict(source_record_id=p['target_source_record_id'],disposition='accepted_owncoded_rendered_article_point_with_native_scope_witness',ordinary_identity_edges_added=False,missing_year_population_assigned=False)for p in P]).to_csv(O/'record_dispositions.csv',index=False)
for n,v in [('point_binding_witnesses.json.gz',W),('native_source_row_witnesses.json.gz',raw)]:
 with gzip.open(O/n,'wt')as f:json.dump(v,f,ensure_ascii=False)
m=dict(baseline_stage=71,accepted_own_point_uses=1,identity_edges_added=0,population_values_modified=False,validation=dict(actual_rendered_infobox_coordinates_reparsed=True,native_raw_scope_rows_reopened=True,explicit_owncodes_verified=True,census_values_independent_corroboration_not_countonly_identity=True),frozen_files=[dict(name=f.name,sha256=sha(f),bytes=f.stat().st_size)for f in sorted(O.iterdir())if f.is_file()]);(O/'freeze_manifest.json').write_text(json.dumps(m,ensure_ascii=False,indent=2));print(1)
