from pathlib import Path
import gzip,json,hashlib,pandas as pd
O=Path(__file__).parent;sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();src=O/'all_regional_homonym_sourcecounty_competitors.csv';dst=O/'all_regional_homonym_sourcecounty_competitors.csv.gz'
if src.exists():
 with gzip.open(dst,'wb',compresslevel=9) as f:f.write(src.read_bytes())
 src.unlink()
p=O/'candidate_receipt.json';r=json.loads(p.read_text());r['source_manifest'].pop(str(src),None);r['source_manifest'].pop(str(src.resolve()),None);r['outputs']={p.name:sha(p) for p in O.glob('*.csv')}|{dst.name:sha(dst)}
t=pd.read_csv(O/'individual_unique_three_year_candidates.csv');e=pd.read_csv(O/'candidate_identity_edge_delta.csv');q=pd.read_csv(O/'candidate_point_use_delta.csv');b=pd.read_csv(O/'individual_triplet_source_bindings.csv');c=pd.read_csv(dst)
assert len(t)==48 and len(e)==90 and len(q)==90 and len(b)==144 and c.point_filter_applied.eq(False).all();assert q.coordinate_source_record_id.isin(t.id2021).all() and q.county_receiving_point_projected_to_children.eq(False).all();assert all(t['id'+str(y)].is_unique for y in [2002,2010,2021]);assert b.source_values_unmodified.all()
for row in q.itertuples():assert sha(row.point_origin_file)==row.point_origin_sha256
r['frozen_review_packet']=True;r['administrative_scope_rows_are_research_context_only_no_credit']=True;r['compressed_complete_competitor_enumeration']=dst.name;r['outputs'][dst.name]=sha(dst);r['code_sha256']={p.name:sha(p) for p in O.glob('*.py')};p.write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n')
(O/'README.md').write_text('FROZEN candidate48 individual NP three-census bindings,90same-place edge proposals and90 individual ownpoint-use proposals, after baselineworkingstate30. No accepted/helper/report/Git edits. Potential exclusive native-ID population gain3770/3931/6039. Each candidate uses its own existing2021NPpoint, never a county/city representative point. Every same-region typed-name competitor is enumerated before pointfilter (compressedCSV), then all2010homonym sourcecounties are independently resolved by an existing accepted individual2002/2010component and literal2002rawheader, or two nearest independently accepted native2010anchors agreeing on printed sourcecounty within5rawrows eachside. Only unique2002printedcounty/2010boundsourcecounty/2021ownmunicip names/types remain. Unknown/conflicting competitors and missingownpoint cases stay held. Original02/10source rows reopened and nativequality/population unchanged. Existing component ID union must equal exact3candidateIDs; no silent multi-NP merges. Administrative scope ranking files are INPUTADMIN research context only, never population credit or ownpoint projection.\n')
print('frozen',len(t),'triplets','bytes',sum(p.stat().st_size for p in O.rglob('*') if p.is_file()))
