from pathlib import Path
import sys,json,re,pandas as pd,pyarrow.parquet as pq,xlrd,math
R=Path('/workspace/russian-settlements-research');E=R/'research_rebuild/evidence';O=Path(__file__).parent;sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from working_state_20261007 import load
s=load(stage=30);meta=pq.read_table(s.inputs[0],columns=['source_record_id','source_sheet','source_row','source_name_raw']).to_pandas();o=s.obs.merge(meta,on='source_record_id');print('loaded30',flush=True)
f=o.assign(root=o.source_record_id.map(s.uf.find),point=o.source_record_id.isin(s.point_rows),finite=o.population.notna());ag=f.groupby('root').agg(years=('census_year','nunique'),point=('point','all'),finite=('finite','all'));roots=set(ag.index[(ag.years==3)&ag.point&ag.finite]);prior=set(f.loc[f.root.isin(roots),'source_record_id'])
for filename in ['complete_publisher_partition_members.csv','qualified_scope_source_id_credit_union.csv','named_merger_lineage_constituents.csv']:prior.update(pd.read_csv(E/'working_full_chain_20261007'/filename).source_record_id)
for folder in ['large_absorbed_city_closed_scope_application_20261008','remaining_absorbed_city_published_closures_application_20261008','nakhoda_complete_published_scope_aux5_application_20261008','city_territory_mass_followup_application_20261008','city_territory_mass_final_two_application_20261008']:prior.update(pd.read_csv(E/folder/'accepted_constituent_credit_union.csv').source_record_id)
for folder in ['complete_transferred_municipal_scope_application_20261008','moscow_complete_scope_mass_application_20261008']:prior.update(pd.read_csv(E/folder/'accepted_native_scope_constituents.csv').source_record_id)
remaining=o[o.census_year.eq(2010)&~o.source_record_id.isin(prior)].copy();rr=remaining.groupby('region_norm').agg(uncredited2010population=('population','sum'),native_rows=('source_record_id','count')).sort_values('uncredited2010population',ascending=False);rr.head(10).to_csv(O/'top10_native_uncredited2010_regions.csv');remaining.nlargest(100,'population')[['source_record_id','settlement_name','settlement_type','region_norm','population','source_file','source_sheet','source_row']].to_csv(O/'top100_native_uncredited2010.csv',index=False)
rawpath=Path('/workspace/settlements-raw/data/interim/2021_tochno/data_allsettlements_anon_156_v20251217.parquet');raw=pq.read_table(rawpath,columns=['object_level','object_name','region','mun_upper','population']).to_pandas();cur=o[o.census_year.eq(2021)].copy();cur['mun_upper']=[raw.iloc[int(n)-1].mun_upper for n in cur.source_row];cur['raw_region']=[raw.iloc[int(n)-1].region for n in cur.source_row]
city=o[o.census_year.eq(2021)&o.type_norm.eq('город')&o.source_record_id.isin(s.point_rows)].copy();ranks=[];selected={}
for c in city.itertuples():
 if c.source_record_id in prior and c.name_norm in {'екатеринбург','киров','якутск','владимир','барнаул','находка','копейск','артем','каменск шахтинский','шахты','челябинск','волгоград'}:continue
 rs=raw.iloc[int(c.source_row)-1];scope=cur[cur.raw_region.eq(rs.region)&cur.mun_upper.eq(rs.mun_upper)];keys=set(zip(scope.name_norm,scope.type_norm));possible=remaining[remaining.region_norm.eq(c.region_norm)&pd.Series([(n,t) in keys for n,t in zip(remaining.name_norm,remaining.type_norm)],index=remaining.index)];pop=int(possible.population.sum())
 if pop>0:ranks.append({'city':c.settlement_name,'region_norm':c.region_norm,'current_scope':rs.mun_upper,'attributed_uncredited2010_population':pop,'attributed_native2010_rows':len(possible),'attribution':'native same region/type/name within current published complete territory; sourceyear roster closure still required','current_city_id':c.source_record_id,'current_point_available':True});selected[c.source_record_id]=possible
ranks=pd.DataFrame(ranks).sort_values('attributed_uncredited2010_population',ascending=False);ranks.head(20).to_csv(O/'top20_city_scope_residual_attribution.csv',index=False);print(rr.head(10).to_string());print(ranks.head(20).drop(columns=['attribution','current_city_id']).to_string(index=False),flush=True)
# Compact exact native atoms for top potential scopes; no allRF re-export.
frames=[]
for z in ranks.head(15).itertuples():frames.append(selected[z.current_city_id].assign(candidate_city=z.city))
pd.concat(frames)[['candidate_city','source_record_id','settlement_name','settlement_type','region_norm','population','population_value_quality','source_file','source_sheet','source_row','source_name_raw']].to_csv(O/'ranked_scope_residual_atoms.csv',index=False)
# Cache only the small intended-candidate native rosters/own points for the followup source closures.
regions=set(ranks.head(15).region_norm);focus=o[o.region_norm.isin(regions)&o.census_year.eq(2010)]
# Avoid a bulky regional export; retain only candidates' year owncities and residual atoms.
citynames=set(ranks.head(15).city.str.lower().str.replace('ё','е'));o[o.name_norm.isin(citynames)&o.type_norm.eq('город')][['source_record_id','census_year','settlement_name','settlement_type','region_norm','population','population_value_quality','source_file','source_sheet','source_row']].to_csv(O/'candidate_owncity_three_years.csv',index=False)
points={z.current_city_id:s.point_rows[z.current_city_id] for z in ranks.head(15).itertuples()};(O/'candidate_existing_owncity_points.json').write_text(json.dumps(points,ensure_ascii=False,indent=2));print('bytes',sum(p.stat().st_size for p in O.iterdir() if p.is_file()),flush=True)
