import json,sys,importlib.util,gzip
from pathlib import Path
import pandas as pd
O=Path(__file__).parent;R=Path('/workspace/russian-settlements-research');sys.path.insert(0,str(O));sys.path.insert(0,str(R/'research_rebuild/mass_linkage'));sys.path.insert(0,str(R/'research_rebuild/evidence/working_full_chain_20261007'))
from frozen_working_state58 import load
from current_chain_state_20261007 import sha,distance_km
from replay_additional_native_20261008 import finite
s=load(58);before=finite(s);assert before=={'histories':141106,'populations_by_year':{'2002':126915601,'2010':124056022,'2021':124679751}}
r=json.loads((O/'application_receipt.json').read_text())
for p,h in r['input_pins'].items():assert sha(Path(p))==h,p
for p,h in r['output_pins'].items():assert sha(O/p)==h,p
cols=['source_record_id','population','population_value_quality','settlement_name','settlement_type','oktmo','okato','root'];protected=s.obs[cols].copy();metrics_before=s.metrics();points=pd.read_csv(O/'accepted_point_use_delta.csv.gz',keep_default_na=False);reject=pd.read_csv(O/'point_use_rejections.csv.gz',keep_default_na=False);assert set(points.target_source_record_id)==set(reject.target_source_record_id);assert reject.rejection_status.eq('reviewed_superseded_representative_point_only').all();assert s.by_id.loc[points.target_source_record_id,'census_year'].isin([2002,2010]).all();candidates=pd.read_csv(O/'candidate_moderate_histories.csv.gz');moderate_ids=set(candidates.source_record_id_2002)|set(candidates.source_record_id_2010);assert set(points.target_source_record_id)<=moderate_ids
s.reject_point_uses(O/'point_use_rejections.csv.gz');s.add_deltas(point_paths=[O/'accepted_point_use_delta.csv.gz']);after=finite(s);assert before==after;assert metrics_before==s.metrics();pd.testing.assert_frame_equal(protected,s.obs[cols]);g=[]
for a in candidates.to_dict('records'):
 ids=[a['source_record_id_'+str(y)] for y in [2002,2010,2021]];coords=[(s.point_rows[i]['latitude'],s.point_rows[i]['longitude']) for i in ids];d=max(distance_km(coords[i],coords[j]) for i,j in [(0,1),(0,2),(1,2)]);g.append({'component_root':a['component_root'],'current_native_source_record_id':ids[2],'current_name':a['settlement_name_2021'],'population_2021':a['population_2021'],'max_pair_km_before':a['max_interyear_distance_km'],'max_pair_km_after':d,'any_representative_point_superseded':any(i in set(points.target_source_record_id) for i in ids)})
f=pd.DataFrame(g);f.to_csv(O/'moderate_geometry_before_after.csv.gz',index=False,compression={'method':'gzip','mtime':0});r.update(status='FROZEN independent actual58 State API representative-point supersession replay passed',State_API_replay_passed=True,before_finite=before,after_finite=after,finite_population_gain={str(y):0 for y in [2002,2010,2021]},all_population_quality_names_types_native_codes_and_accepted_identity_unchanged=True,geometry_before_gt5_histories=len(candidates),geometry_after_gt5_histories=int(f.max_pair_km_after.gt(5).sum()),geometry_resolved_to_within5_histories=int(f.max_pair_km_after.le(5).sum()),current_native2021_points_changed=False,historical_coordinate_alternatives_preserved=True,coordinate_time_interpretation='Current own locality representative point reused retrospectively by already accepted same-place continuity; Geo2011 coordinate is not a census-date measurement; valid old coordinate alternatives remain in the pinned immutable ledger',core_API_sha256_at_replay=sha(R/'research_rebuild/mass_linkage/current_chain_state_20261007.py'));r['input_pins'].update({str(p):sha(Path(p)) for p in s.inputs if str(p) not in [str(O/'point_use_rejections.csv.gz'),str(O/'accepted_point_use_delta.csv.gz')]});r['output_pins']['moderate_geometry_before_after.csv.gz']=sha(O/'moderate_geometry_before_after.csv.gz');(O/'application_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2));print(json.dumps({k:v for k,v in r.items() if k not in ['input_pins','output_pins']},ensure_ascii=False))
