from pathlib import Path
import sys,json,hashlib,pandas as pd
sys.path.insert(0,'/workspace/russian-settlements-research/research_rebuild/mass_linkage')
from working_state_20261007 import load,E
from current_chain_state_20261007 import sha
O=Path(__file__).parent;s=load(15);before=s.metrics();edges=[];points=[];review=[]
for name,old,cur,proof in [('Лопатино','2010:010_711691e352_2._20Kostrom_Kur_Lip_Moscow_MoscObl_Orlov_2010.xls:Data Sheet:10407','2021:data_allsettlements_anon_156_v20251217.parquet:parquet:65226','Historical2002 ownrow2594 деревняЛопатино108 underLeninsky; source2002neighborroster Боброво2593/Суханово2595/Дрожжино2592/Леспаркхоз2596 matches native2010roster rows10398/10409/10402/10406 around ownrow10407. Owncurrentarticle Q4266644 independently states108in2002/222in2010 andLeninskyBulаtnikovsky continuity until2019. Protected2010220 remains sourcevalue.'),('Малиновка','2010:008_342f3c208b_16._20Сиб_ФО_2010.xls:Sib:6073','2021:data_allsettlements_anon_156_v20251217.parquet:parquet:33254','Historical2002 ownpgtMalinovka row9143 betweenOsinniki9142/Taizhina9144; native2010 ownsettlementrow6073 underOsinniki6070 withTaizhina6074, Sarbala6075, VerhTesh6071 andNovyPunkt6072; ownarticle Q1647878 explicitly ownMalinovka oncepgt1958-2004, located17kmKalтан andadjacentNovyPunkt/VerhTesh historicallyposсовет; currentacceptedpoint carries ownQ1647878. Typechange explicit; protected20108416 remains sourcevalue.')]:
 assert s.years[s.uf.find(old)]=={2010};assert s.years[s.uf.find(cur)]=={2002,2021}
 p=s.point_rows[cur];a=s.by_id.loc[old];assert a.settlement_name==name
 edges.append({'from_source_record_id':old,'to_source_record_id':cur,'relation':'same_place','decision_status':'case_specific_independent_review_accepted','admission_rule':'same_named_own_locality_printed_historical_source_roster_and_own_article_type_continuity','evidence_path':str(O/'native2010_context_cells.json'),'evidence_sha256':sha(O/'native2010_context_cells.json'),'source_context_proof':proof})
 pp=dict(p);pp.update(target_source_record_id=old,coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_origin_ledger=p['point_ledger_path'],coordinate_origin_ledger_sha256=sha(Path(p['point_ledger_path'])),coordinate_origin_ledger_target_source_record_id=cur,coordinate_binding_rule='accepted_sameplace_ownNP_with_directcurrentownpoint_origin_retrospectivecontinuity_inference',population_boundary_comparability_asserted=False,modern_boundary_harmonized=False);pp.pop('point_ledger_path',None);points.append(pp)
 review.append({'name':name,'native2010_id':old,'native2010_population':int(a.population),'native2010_quality':a.population_value_quality,'current2021_id':cur,'own_point_origin':p.get('point_origin_file'),'own_point_binding':p.get('coordinate_source_record_id'),'proof':proof})
pd.DataFrame(edges).to_csv(O/'candidate_ordinary_identity_edges.csv',index=False);pd.DataFrame(points).to_csv(O/'candidate_ordinary_point_uses.csv',index=False);pd.DataFrame(review).to_csv(O/'ordinary_candidate_review.csv',index=False)
s.add_deltas([O/'candidate_ordinary_identity_edges.csv'],[O/'candidate_ordinary_point_uses.csv']);after=s.metrics();g={y:after[y]['covered_population']-before[y]['covered_population'] for y in before}
(O/'ordinary_simulation_receipt.json').write_text(json.dumps({'status':'candidate_only_simulated_not_loaded_in_currentstage','baseline_stage':15,'before':before,'after_if_admitted':after,'strict_ordinary_population_gain_if_admitted':g,'new_identity_edges':len(edges),'new_point_uses':len(points),'actual_native_source_values_preserved':True,'secondary222_8835_not_replacement':True,'inputs':{str(p):sha(p) for p in [O/'native2010_context_cells.json',O/'native2002_context_cells.json',O/'own_pages.json.gz']},'outputs':{p.name:sha(p) for p in [O/'candidate_ordinary_identity_edges.csv',O/'candidate_ordinary_point_uses.csv',O/'ordinary_candidate_review.csv']}},ensure_ascii=False,indent=2));print(g)
