import json,gzip,hashlib,re
from pathlib import Path
import pandas as pd
O=Path(__file__).parent;E=O.parent
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
rows=pd.read_csv(O/'selected_own_name_rows.csv',keep_default_na=False);comp=pd.read_csv(O/'current_components_points.csv',keep_default_na=False);ent=json.load(gzip.open(O/'entities.json.gz','rt'))['entities'];ent.update(json.load(gzip.open(O/'additional_entities.json.gz','rt'))['entities'])
aux=pd.read_csv(E/'auxiliary_observed_years_application_20261007/accepted_qualified_physical_observations.csv');partition=pd.read_csv(E/'complete_numbered_partition_batch_20261007/accepted_three_census_whole_place_series.csv')
covered=set(aux.source_record_id)
for j in partition.member_source_record_ids_json:covered.update(json.loads(j))
records=[];cases=[]
for name,q,year,pop,grain,nativealt in [('Лопатино','Q4266644',2010,222,'own named settlement census secondary statement','2010:010_711691e352_2._20Kostrom_Kur_Lip_Moscow_MoscObl_Orlov_2010.xls:Data Sheet:10407'),('Малиновка','Q1647878',2010,8835,'own named settlement census secondary statement','2010:008_342f3c208b_16._20Сиб_ФО_2010.xls:Sib:6073'),('Лежнево','Q640989',2010,8034,'own named settlement census secondary statement',''),('Плиево','Q4365077',2002,13892,'named Plievsky administrative district of Nazran; actual 2002 census ownquarter count',''),('Барсуки','Q4078592',2002,10189,'named Barsukinsky administrative district of Nazran; actual 2002 census ownquarter count','')]:
 c=comp[comp.name.eq(name)].iloc[0];ids=json.loads(c.component_ids);p=json.loads(c.point_json);efile=O/('additional_entities.json.gz' if q=='Q640989' else 'entities.json.gz');stat=[v for v in ent[q]['claims']['P1082'] if str(year) in v.get('qualifiers',{}).get('P585',[{}])[0].get('datavalue',{}).get('value',{}).get('time','')]
 assert len(stat)==1;v=stat[0];assert int(float(v['mainsnak']['datavalue']['value']['amount']))==pop
 event=year==2002;series='large_ownyear:'+q;status='candidate_qualified_actual_observed_year_series_with_selected2010_alternative_unlinked' if nativealt else ('candidate_event_scope_series_primary_disaggregation_law_unverified' if event else 'candidate_qualified_actual_observed_year_series')
 for sid in ids:
  r=rows[rows.source_record_id.eq(sid)].iloc[0];records.append({'trajectory_id':series,'year':int(r.census_year),'population_source_value':int(r.population),'source_record_id':sid,'settlement_name':name,'region_norm':c.region,'county_context':c.county,'latitude':p['latitude'],'longitude':p['longitude'],'population_quality':r.population_value_quality,'grain':'existing selected settlement observation','nonadditive_observation':False,'source_path':str(Path('/workspace/settlements-raw')/r.source_file),'source_sha256':r.source_sha256,'source_locator':r.source_locator,'decision_status':status,'ordinary_NP3_asserted':False,'boundary_comparability_asserted':False,'point_origin_file':p.get('point_origin_file',''),'point_origin_sha256':p.get('point_origin_sha256',''),'point_origin_locator':p.get('point_origin_locator',''),'point_binding_json':json.dumps(p,ensure_ascii=False),'retrospective_point_use_is_continuity_inference':True,'selected_credit_previously_present':sid in covered})
 source=efile;locator=f"entities.{q}.claims.P1082[id={v['id']}]";quality='dated_secondary_census_value_original_publication_unverified';sid='WD:'+v['id']
 if event:
  source=Path('/workspace/settlements-raw/data/raw/2002_official_tom1/1_TOM_01_04.xls');locator='01-04!A3686:B3686' if name=='Плиево' else '01-04!A3683:B3683';quality='direct_published_census_value_named_intraurban_district_scope';sid=f'PRIMARY2002:01-04:row{3686 if name=="Плиево" else 3683}'
 records.append({'trajectory_id':series,'year':year,'population_source_value':pop,'source_record_id':sid,'settlement_name':name,'region_norm':c.region,'county_context':c.county,'latitude':p['latitude'],'longitude':p['longitude'],'population_quality':quality,'grain':grain,'nonadditive_observation':True,'source_path':str(source),'source_sha256':sha(source),'source_locator':locator,'decision_status':status,'ordinary_NP3_asserted':False,'boundary_comparability_asserted':False,'point_origin_file':p.get('point_origin_file',''),'point_origin_sha256':p.get('point_origin_sha256',''),'point_origin_locator':p.get('point_origin_locator',''),'point_binding_json':json.dumps(p,ensure_ascii=False),'retrospective_point_use_is_continuity_inference':True,'selected_credit_previously_present':False})
 cases.append({'name':name,'qid':q,'missing_year':year,'actual_population':pop,'component_ids_json':json.dumps(ids),'native_selected2010_alternative_id':nativealt,'native_selected2010_alternative_population':int(rows.loc[rows.source_record_id.eq(nativealt),'population'].iloc[0]) if nativealt else None,'secondary_statement_id':v['id'],'secondary_source_path':str(efile),'secondary_source_sha256':sha(efile),'secondary_locator':f'entities.{q}.claims.P1082[id={v["id"]}]','statement_references_json':json.dumps(v.get('references',[]),ensure_ascii=False),'status':status,'own_point_native_source_binding_present':bool(p.get('coordinate_source_record_id')),'event_witness':'own_pages.json.gz query.pages[title='+('Плиево' if name=='Плиево' else 'Барсуки (Ингушетия)')+'].revisions[0].slots.main.content paragraph beginning В 1995 году; explicitly reinstated2009 based on abolished ownnamed administrative district' if event else '', 'no_2002_ordinary_NP_credit':event})
f=pd.DataFrame(records);assert len(f)==15 and not f[['trajectory_id','year']].duplicated().any();f.to_csv(O/'candidate_qualified_actual_observations.csv',index=False);pd.DataFrame(cases).to_csv(O/'case_dispositions.csv',index=False)
net={str(y):int(g.loc[~g.nonadditive_observation & ~g.selected_credit_previously_present,'population_source_value'].sum()) for y,g in f.groupby('year')}
(O/'package_receipt.json').write_text(json.dumps({'status':'candidate_only_not_applied','baseline_stage':15,'new_series_candidates':5,'native2010_alternatives_require_identity_review':2,'qualified_ownsettlement_secondary_series':3,'event_scope_series_held_primary_disaggregation_law_unverified':2,'auxiliary_values_nonadditive':True,'ordinary_selected_population_gain':0,'conditional_net_selected_endpoint_population_references_unique_after_prior_aux_and_partition':net,'prior_scope_source_id_count':len(covered),'disk_bytes':sum(p.stat().st_size for p in O.iterdir() if p.is_file()),'outputs':{p.name:sha(p) for p in [O/'candidate_qualified_actual_observations.csv',O/'case_dispositions.csv']},'limitations':['Lopatino actual official reported222 differs protected selected220; both preserved, no overwrite','Malinovka actual official reported8835 differs protected selected8416; both preserved, no overwrite','Event2002grain is ownnamed quarter, never parentNazran total; ordinary2002NP assertion prohibited','Modern ownpoints are continuityinference for historical years, constant boundaries not asserted','Kushchevskaya/KinelCherkassy/Sergievsk primary2002 controls already covered by prior partition series: zero net gain']},ensure_ascii=False,indent=2))
print(json.dumps(net));print(pd.DataFrame(cases)[['name','actual_population','native_selected2010_alternative_population','status']].to_string(index=False))
