from pathlib import Path
import sys,json,gzip,re,collections,math
import pandas as pd,xlrd
R=Path('/workspace/russian-settlements-research');E=R/'research_rebuild/evidence';O=Path(__file__).parent;sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from working_state_20261007 import load
from current_chain_state_20261007 import normalize,distance_km,sha
from apply_unique_county_name_bridge_20261007 import county_key
s=load(46);before=s.metrics();pins=json.load(open(O/'inventory_receipt.json'))['input_pins'];pins.update(json.load(open(O/'native_route_inventory_receipt.json'))['input_pins']);qf=pd.read_csv(O/'positive_bound_census2010_candidates.csv.gz',dtype={'current_okato':str,'current_oktmo':str},keep_default_na=False);nf=pd.read_csv(O/'source_positive_native2010_alias_candidates.csv.gz',keep_default_na=False);books={};edges=[];points=[];nativeproof=[];nativeholds=[];nativeaccepted=set();rows=[];credits=[];qholds=[];witness=[];usedq=set();occupied=collections.defaultdict(set)
for sid,p in s.point_rows.items():occupied[(int(s.by_id.loc[sid,'census_year']),p['latitude'],p['longitude'])].add(sid)
for a in nf.to_dict('records'):
 sid,cid=a['native2010_source_record_id'],a['current_source_record_id'];rr=s.by_id.loc[sid];cp=s.point_rows[cid];ra,rc=s.uf.find(sid),s.uf.find(cid);reason='';path=Path('/workspace/settlements-raw')/a['native2010_source_file'];literal=None
 if path.suffix=='.xls' and path.exists():
  if path not in books:books[path]=xlrd.open_workbook(str(path),on_demand=True);pins[str(path)]=sha(path)
  sh=books[path].sheet_by_name(str(a['native2010_source_sheet']));values=sh.row_values(int(a['native2010_source_row'])-1);nameokay=any(isinstance(v,str) and normalize(v)==normalize(a['native2010_source_name_raw']) for v in values);populationokay=any(isinstance(v,(int,float)) and float(v)==float(rr.population) for v in values);literal={'raw_row_values':values,'sheet':sh.name,'row1based':int(a['native2010_source_row']),'raw_sha256':pins[str(path)],'source_path':str(path),'name_literal_pass':nameokay,'native_population_literal_pass':populationokay}
 if not literal or not literal['name_literal_pass'] or not literal['native_population_literal_pass']:reason='native_original_raw_label_population_not_verified'
 if s.years[ra]&s.years[rc] or s.years[rc]!={2002,2021}:reason='actual_census_year_graph_collision'
 if any(x in s.conflicting_point_targets for x in [sid,cid]):reason='active_point_alternative'
 if sid in s.point_rows and distance_km((s.point_rows[sid]['latitude'],s.point_rows[sid]['longitude']),(cp['latitude'],cp['longitude']))>5:reason='independent_native2010_point_contradiction'
 if occupied[(2010,cp['latitude'],cp['longitude'])]-{sid}:reason='distinct_native2010_point_already_occupies_current_ownpoint'
 if reason:nativeholds.append(a|{'reason':reason});continue
 proof=a|{'raw_native_literal_row_witness':literal,'native_source_count_unmodified':rr.population,'population_equality_not_admission_gate':True};nativeproof.append(proof);edges.append({'from_source_record_id':sid,'to_source_record_id':cid,'relation':'same_place','decision_status':'checked_rule_accepted','admission_rule':'Cached ownitem literal alias/name plus source-own type and printed/frozen county or actual native owncode; all native2010 namesakes before graph; original raw leaf label/value preserved; existing02/21 ownpoint continuity','source_binding_proof':json.dumps(proof,ensure_ascii=False),'boundary_comparability_asserted':False,'population_values_and_quality':'unchanged_selected_native_sources'});s.union(sid,cid);nativeaccepted.add(cid)
 if sid not in s.point_rows:
  p=dict(cp);p.pop('point_ledger_path',None);p.update(target_source_record_id=sid,coordinate_admission_status='reviewed_extension_rule_accepted',boundary_comparability_asserted=False,native_old_printed_code_asserted=False,point_temporal_interpretation='Modern own representative, not a measured census-date coordinate');points.append(p);s.point_rows[sid]=dict(p,point_ledger_path=str(O/'accepted_point_use_delta.csv'));occupied[(2010,p['latitude'],p['longitude'])].add(sid)
# Existing reference/method labels are literal cached witnesses; all inputs remain pinned from the inventory.
labels={};entities={}
for path in pins:
 p=Path(path)
 if not(path.endswith('.json.gz') or path.endswith('.json')):continue
 try:b=p.read_bytes();d=json.loads(gzip.decompress(b) if path.endswith('.gz') else b)
 except:continue
 es=d.get('entities',d.get('payload',{}).get('entities',{})) if isinstance(d,dict) else {}
 if isinstance(es,dict):
  for q,e in es.items():
   if isinstance(e,dict) and e.get('labels',{}).get('ru'):labels[q]=e['labels']['ru']['value']
priorq=set()
p=E/'working_full_chain_20261007/qualified_physical_observations.csv'
if p.exists():
 f=pd.read_csv(p,dtype=str,keep_default_na=False);pins[str(p)]=sha(p)
 for col in ['wikidata_id','trajectory_id']:
  if col in f:
   for v in f[col]:priorq.update(re.findall(r'Q[0-9]+',v))
for cid,g in qf.groupby('current_source_record_id',sort=False):
 if cid in nativeaccepted:continue
 if len(set(g.qid))!=1 or len(set(g.population2010))!=1:qholds.append({'sid':cid,'reason':'multiple_own_QIDs_or_conflicting2010_values'});continue
 a=g.sort_values('precision',ascending=False).iloc[0].to_dict();q=a['qid'];oid=a['native2002_source_record_id'];cp=s.point_rows[cid]
 if q in priorq or q in usedq:qholds.append({'sid':cid,'reason':'own_QID_previous_qualified_or_duplicate'});continue
 if s.years[s.uf.find(cid)]!={2002,2021}:qholds.append({'sid':cid,'reason':'no_longer_missing2010'});continue
 if distance_km((s.point_rows[oid]['latitude'],s.point_rows[oid]['longitude']),(cp['latitude'],cp['longitude']))>5:qholds.append({'sid':cid,'reason':'native2002_current_ownpoint_contradiction'});continue
 dateexact=a['date'].startswith('+2010-10-14') and a['precision']>=11;methodproof=any(labels.get(m)=='перепись населения' for m in json.loads(a['P459_ids_json']));texts=json.loads(a['reference_titles_json'])+json.loads(a['reference_urls_json'])+json.loads(a['reference_labels_json']);refproof=any(re.search('перепис|census|впн|vpn2010',t,re.I) and '2010' in t for t in texts)
 if not(dateexact or methodproof or refproof):qholds.append({'sid':cid,'reason':'generic2010date_without_literal_census_method_reference_or_precise_date'});continue
 path=Path(a['raw_entity_path']);assert sha(path)==a['raw_entity_sha256'];pins[str(path)]=sha(path);pointpath=Path(cp['point_origin_file']);assert sha(pointpath)==cp['point_origin_sha256'];pins[str(pointpath)]=sha(pointpath);tid='uncached_missing2010_secondary:'+q;usedq.add(q);proofclass='actual2010year_with_literal_census_method' if methodproof else 'precise2010_census_date' if dateexact else 'literal2010_census_reference_title_label_or_URL';common={'trajectory_id':tid,'settlement_name':a['name'],'region_norm':a['region'],'county_context':a['current_county'],'latitude':cp['latitude'],'longitude':cp['longitude'],'wikidata_id':q,'scope':'uncached_missing2010_dated_source_mass_20261008','decision_status':'qualified_accepted_secondary_census_referenced_own_item','ordinary_NP3_asserted':False,'boundary_comparability_asserted':False,'boundary_comparability':'UNKNOWN','accepted_physical_three_observed_census_year_path':True,'accepted_scoped_representative_point':True,'population_primary_reference_verified':False,'own_item_binding':'direct admitted ownpointQID OR own current nativecode + cached ownP625<=1km; literal own name/alias and explicit physical P31; all current5km namesakes before graph filter','own_code_positive':a['own_native_code_positive'],'own_name_or_alias_positive':True,'own_physical_description':a.get('own_physical_description',''),'physical_type_proof_class':a.get('physical_type_proof_class','explicit_physical_P31'),'optional_Wiki_coordinates_imported':False,'native_current_source_record_id':cid,'point_binding_json':json.dumps(cp,ensure_ascii=False),'point_origin_file':cp['point_origin_file'],'point_origin_sha256':cp['point_origin_sha256'],'point_origin_locator':cp['point_origin_locator'],'historical_point_direct_measurement_asserted':False,'native_current_5km_name_competitors_json':a['all_current_5km_name_candidates_json'],'source_foundation_dates_json':a['foundation_dates_json']}
 for year,sid,pop in [(2002,oid,a['population2002']),(2010,'',a['population2010']),(2021,cid,a['population2021'])]:
  native=bool(sid);rr=s.by_id.loc[sid] if native else None;source=Path('/workspace/settlements-raw')/rr.source_file if native else path;sourcehash=sha(source) if source.exists() else str(rr.source_sha256);pins[str(source)]=sourcehash if source.exists() else pins.get(str(source),'');sourcequality=rr.population_value_quality if native else 'secondary_explicit_census_reference_or_method_primary_unverified';source_locator=str(rr.source_locator) if native and pd.notna(rr.source_locator) else 'selected native source_record_id='+sid if native else f'entities.{q}.claims.P1082[{a["statement_id"]}]';row=common|{'year':year,'population_source_value':pop,'source_record_id':sid,'population_quality':sourcequality,'grain':'own physical locality selected native census observation' if native else 'own physical locality dated secondary2010 census observation','nonadditive_observation':not native,'source_path':str(source),'source_sha256':sourcehash,'source_locator':source_locator,'declared_date':'' if native else a['date'],'date_precision':9 if native else a['precision'],'source_date_precision':9 if native else a['precision'],'source_population_is_census_known':True,'census_proof_class':'existing_native_census_row_in_accepted_02_21_own_component' if native else proofclass,'P459_ids_json':'[]' if native else a['P459_ids_json'],'P459_labels_json':'[]' if native else a['P459_labels_json'],'P248_ids_json':'[]' if native else a['reference_ids_json'],'P248_labels_json':'[]' if native else a['reference_labels_json'],'census_reference_titles_json':'[]' if native else a['reference_titles_json'],'reference_urls_json':'[]' if native else a['reference_urls_json'],'statement_id':'' if native else a['statement_id'],'historical_native_selected_source_ID_binding_asserted':native and year==2002,'native_existing_component_binding':native,'retrospective_point_use_is_continuity_inference':year!=2021,'native_raw_source_missing_flag':native and not source.exists()};rows.append(row)
  if native:credits.append({'source_record_id':sid,'year':year,'population_source_value':pop,'population_quality':sourcequality,'native_current_source_record_id':cid,'trajectory_id':tid})
 witness.append(a|{'trajectory_id':tid,'proof_class':proofclass,'native2010_selected_ID_binding_asserted':False,'native2010_raw_source_bindings_unresolved':True,'population_secondary2010_nonadditive':True})
# Remove missing legacy raw paths from byte pins; preserved selected provenance remains explicit.
pins={p:h for p,h in pins.items() if Path(p).exists()};pd.DataFrame(edges,columns=['from_source_record_id','to_source_record_id','relation','decision_status','admission_rule','source_binding_proof','boundary_comparability_asserted','population_values_and_quality']).to_csv(O/'accepted_identity_edge_delta.csv',index=False);pd.DataFrame(points).to_csv(O/'accepted_point_use_delta.csv',index=False);pd.DataFrame(nativeproof).to_csv(O/'accepted_native_source_binding_witnesses.csv.gz',index=False,compression={'method':'gzip','mtime':0});pd.DataFrame(nativeholds).to_csv(O/'native_binding_holds.csv',index=False);pd.DataFrame(rows).to_csv(O/'accepted_qualified_physical_observations.csv',index=False);pd.DataFrame(credits).to_csv(O/'accepted_qualified_native_source_ID_credit_union.csv',index=False);pd.DataFrame(witness).to_csv(O/'qualified_own_source_binding_witnesses.csv.gz',index=False,compression={'method':'gzip','mtime':0});pd.DataFrame(qholds).to_csv(O/'qualified_holds.csv',index=False);after=s.metrics();cr=pd.DataFrame(credits);rec={'baseline_stage':46,'status':'accepted_uncached2010_native_route_and_disjoint_secondary_census_fallback','native_accepted_edges':len(edges),'native_accepted_point_uses':len(points),'native_holds':len(nativeholds),'native_net_ordinary_gain':{str(y):{'rows':after[y]['covered_rows']-before[y]['covered_rows'],'population':after[y]['covered_population']-before[y]['covered_population']} for y in before},'qualified_series':len(usedq),'qualified_observations':len(rows),'qualified_native_ID_union_net':{str(y):{'rows':len(g),'population':int(g.population_source_value.sum())}for y,g in cr.groupby('year')},'secondary2010_nonadditive_population':int(sum(x['population_source_value']for x in rows if x['year']==2010)),'secondary2010_literal_zero_rows':sum(x['year']==2010 and x['population_source_value']==0 for x in rows),'native2010_ID_credit_from_secondary':0,'qualified_holds':len(qholds),'no_new_network':False,'network_requests':len(json.load(open(O/'network_receipt.json'))['records']),'requested_entity_QIDs':len(json.load(open(O/'request_QIDs.json'))),'network_gzip_bytes':json.load(open(O/'network_receipt.json'))['compressed_cache_bytes'],'original_population_and_quality_preserved':True,'no_secondary_ordinary_NP3_claim':True,'input_pins':pins,'output_pins':{p.name:sha(p) for p in O.glob('*.csv*')}};(O/'application_receipt.json').write_text(json.dumps(rec,ensure_ascii=False,indent=2));print(json.dumps({k:v for k,v in rec.items() if k not in ['input_pins','output_pins']},ensure_ascii=False))
