from pathlib import Path
import pandas as pd,duckdb,json,hashlib,math,re,unicodedata,ast,time,resource,xlrd
O=Path(__file__).resolve().parent;R=O.parents[2];E=R/'research_rebuild/evidence';B=E/'main_axis_residual_application66_20261008';S=E/'current_residual_next65_20261008/history_scope_revision';START=time.monotonic();PINS={}
def sha(p):
 h=hashlib.sha256()
 with Path(p).open('rb') as f:
  for z in iter(lambda:f.read(1048576),b''):h.update(z)
 return h.hexdigest()
def pin(p,want=None):
 p=Path(p);k=str(p)
 if k not in PINS:PINS[k]={'sha256':sha(p),'bytes':p.stat().st_size}
 if want:assert PINS[k]['sha256']==want,(k,want,PINS[k])
 return p
def normalize(v):return re.sub(r'\s+',' ',str(v or '').lower().replace('ё','е')).strip()
RULE=pin(E/'current_cached_ownarticle_residual_expansion_20261008/review_articles.py');tree=ast.parse(RULE.read_text());exec(compile(ast.Module(body=[n for n in tree.body if isinstance(n,ast.FunctionDef) and n.name in ['bare','namekey','typekey','regionkey','county','fullcode','splitname']],type_ignores=[]),str(RULE),'exec'))
def distance(a,b):
 la,lo,lb,lob=map(math.radians,[float(a['latitude']),float(a['longitude']),float(b['latitude']),float(b['longitude'])]);h=math.sin((lb-la)/2)**2+math.cos(la)*math.cos(lb)*math.sin((lob-lo)/2)**2;return 6371*2*math.asin(min(1,math.sqrt(h)))
def pubname(v):
 m=re.match(r'^\s*(с|д|п|н\.?п|пгт|рп)\.\s*(.+)$',str(v),re.I)
 if m:return m.group(2),{'с':'село','д':'деревня','п':'поселок','нп':'населенный пункт','пгт':'пгт','рп':'рабочий поселок'}[m.group(1).lower().replace('.','')]
 return splitname(v)
manifest=json.loads(pin(S/'frozen_scope_asset_manifest.json','70cb2772d7b915a413d1e9e1f093467ef850715c6baa7e31516f0f132f41dc13').read_text())
for p,h in manifest.items():pin(p,h)
sr=json.loads((S/'scope_revision_receipt.json').read_text())
for p,h in sr['input_pins'].items():pin(p,h)
f=pd.read_csv(S/'scope_verified_five_history_counterpart_proposals.csv.gz',dtype=str,keep_default_na=False);assert len(f)==5 and f.current_source_record_id.is_unique
br=json.loads(pin(B/'application_receipt.json','50a87e60252b36bb820771a6efd4afb027ee5d640d0550f7890ad99a394da40d').read_text())
for n in ['applied_state_observations.parquet','applied_component_snapshot.csv.gz','applied_point_snapshot.parquet','applied_primary_credited_UID_roster.csv.gz']:pin(B/n,br['output_pins'][n]['sha256'])
c=duckdb.connect();c.execute("SET memory_limit='128MB'");c.execute('SET threads=1')
ids=f.current_source_record_id.tolist()+f.historic_source_record_id.tolist();direct=c.execute('select * from read_parquet(?) where source_record_id in (select unnest(?))',[str(B/'applied_state_observations.parquet'),ids]).fetchdf();assert len(direct)==10;roots=direct.root.unique().tolist();members=c.execute('select * from read_parquet(?) where root in (select unnest(?))',[str(B/'applied_state_observations.parquet'),roots]).fetchdf();assert len(members)==11
pts=c.execute('select * from read_parquet(?) where source_record_id in (select unnest(?))',[str(B/'applied_point_snapshot.parquet'),members.source_record_id.tolist()]).fetchdf();pr={q['source_record_id']:q for q in pts.to_dict('records')};native=members.set_index('source_record_id');years={root:set(map(int,h.census_year)) for root,h in members.groupby('root')};assert all(len(h)==len(set(h.census_year)) for _,h in members.groupby('root'))
regions=direct.region_norm.unique().tolist();rivals=c.execute('select source_record_id,census_year,settlement_name,settlement_type,region_norm,district_raw,population_scope,is_additive_settlement_record,oktmo from read_parquet(?) where region_norm in (select unnest(?))',[str(B/'applied_state_observations.parquet'),regions]).fetchdf();rivals['key_name']=rivals.settlement_name.map(namekey);rivals['key_region']=rivals.region_norm.map(regionkey);rivals['key_county']=rivals.district_raw.fillna('').map(county)
credit=c.execute('select source_record_id,explicit_appearance_publication_absence_credit,explicit_inclusion_credit,explicit_available_year_lifecycle_round2_credit,explicit_gorodok17_inclusion_credit from read_csv_auto(?) where source_record_id in (select unnest(?))',[str(B/'applied_primary_credited_UID_roster.csv.gz'),members.source_record_id.tolist()]).fetchdf();assert not len(credit),'All five counterparts should remain primary-uncredited at66'
books={};checks=[];edges=[];pointuses=[];holds=[];usednew=set();newgain={2002:0,2010:0,2021:0};firstcount_checks=0
for z in f.to_dict('records'):
 sid=z['current_source_record_id'];old=z['historic_source_record_id'];now=native.loc[sid];prior=native.loc[old];a,b=now.root,prior.root;assert years[a].isdisjoint(years[b]),'sameyear component overlap';assert int(now.census_year)==2021 and int(prior.census_year)==2010 and now.is_additive_settlement_record and prior.is_additive_settlement_record
 carrier=pr[sid];want=json.loads(z['current_independently_admitted_or_planned_ownpoint_json'])
 for k in ['coordinate_source_record_id','point_origin_file','point_origin_sha256','point_origin_locator']:assert str(carrier[k])==str(want[k]),(sid,k)
 assert (float(carrier['latitude']),float(carrier['longitude']))==(float(want['latitude']),float(want['longitude'])) and carrier['coordinate_admission_status'] in ['reviewed_rule_accepted','reviewed_extension_rule_accepted']
 pin(carrier['point_origin_file'],carrier['point_origin_sha256']);pin(carrier['point_ledger_path'])
 distances=[{'source_record_id':oid,'distance_km':distance(carrier,p)} for oid,p in pr.items() if oid in set(members.loc[members.root.isin([a,b]),'source_record_id'])];assert all(q['distance_km']<=5 for q in distances),'existing ownpoint contradiction'
 assert namekey(now.settlement_name)==namekey(prior.settlement_name) and typekey(now.settlement_type)==typekey(prior.settlement_type) and regionkey(now.region_norm)==regionkey(prior.region_norm)
 key=json.loads(z['exact_normalized_name_region_county_key_json']);assert key==[namekey(now.settlement_name),regionkey(now.region_norm),county(now.district_raw)]
 same=rivals[rivals.key_name.eq(key[0])&rivals.key_region.eq(key[1])];native_rival_rows=same[['source_record_id','census_year','settlement_name','settlement_type','district_raw','is_additive_settlement_record']].to_dict('records')
 currentnames=same[same.census_year.eq(2021)&same.key_county.eq(key[2])];oldnames=same[same.census_year.eq(2010)&same.key_county.eq(key[2])];assert len(currentnames)==1 and currentnames.source_record_id.iloc[0]==sid and len(oldnames)==1 and oldnames.source_record_id.iloc[0]==old;assert not same[same.census_year.isin([2010,2021])&same.key_county.eq('')].shape[0],'unplaced sameyear native name rival'
 rawpath=pin(z['historical_raw_origin_file'],z['historical_raw_origin_sha256']);sheet=old.rsplit(':',2)[1];rn=int(old.rsplit(':',1)[1]);bkkey=(str(rawpath),sheet)
 if bkkey not in books:books[bkkey]=xlrd.open_workbook(str(rawpath),on_demand=True)
 sh=books[bkkey].sheet_by_name(sheet);rawrow=sh.row_values(rn-1);assert rawrow==json.loads(z['historical_raw_row_json']);rawname,rawtype=pubname(rawrow[4]);assert namekey(rawname)==namekey(prior.settlement_name) and typekey(rawtype)==typekey(prior.settlement_type);assert float(rawrow[5])==float(prior.population);firstcount_checks+=1
 endpoint=old;scopeproof={}
 if z['historical_county_positive_member_source_record_id']:
  endpoint=z['historical_county_positive_member_source_record_id'];anchor=native.loc[endpoint];assert anchor.root==b and int(anchor.census_year)==2002 and z['historical_raw_source_county_2010_binding_asserted']=='False';assert county(anchor.district_raw)==key[2] and namekey(anchor.settlement_name)==key[0] and typekey(anchor.settlement_type)==typekey(now.settlement_type)
  p=pin(z['historical_county_positive_raw_origin_file'],z['historical_county_positive_raw_origin_sha256']);bk=xlrd.open_workbook(str(p),on_demand=True);ss=bk.sheet_by_name('Sheet1');assert ss.row_values(2)==json.loads(z['historical_county_positive_raw_county_row_json']) and ss.row_values(38)==json.loads(z['historical_county_positive_raw_parish_row_json']) and ss.row_values(39)==json.loads(z['historical_county_positive_raw_NP_row_json']);assert float(ss.cell_value(39,1))==float(anchor.population);firstcount_checks+=1;assert 'Бай-Тайгинский' in ss.cell_value(2,0) and 'Хемчикский сумон' in ss.cell_value(38,0)
  proper=json.loads(z['current_primary_native_row_reopened_json']);assert proper['mun_lower']=='Сельское поселение Хемчикский' and county(proper['mun_upper'])==key[2];assert namekey(splitname(proper['object_name'])[0])==key[0]
  matches=[i+1 for i in range(2,int(float(z['historical_2002_county_block_end_exclusive_onebased']))-1) if namekey(pubname(ss.cell_value(i,0))[0])==key[0]];assert matches==[40];bk.release_resources();scopeproof={'kind':'positive2002owncountyandliteralХемчикскийparish_with_existingaccepted2002_2010UF','county_anchor':endpoint,'2010_county_carry_asserted':False,'raw2002_parish':'Хемчикский сумон','current_parish':proper['mun_lower']}
 else:
  begin=int(float(z['source_county_block_start_onebased']));end=int(float(z['source_county_block_end_exclusive_onebased']));assert begin<=rn<end and county(sh.cell_value(begin-1,3))==key[2] and sh.cell_value(begin-1,2)==sh.cell_value(end-1,2);assert sh.row_values(end-1)==json.loads(z['source_county_block_end_header_row_json']);assert all(not str(sh.cell_value(i,3)).strip() for i in range(begin,end-1));assert county(sh.cell_value(end-1,3))!=key[2]
  matches=[i+1 for i in range(begin-1,end-1) if namekey(pubname(sh.cell_value(i,4))[0])==key[0]];assert matches==[rn];scopeproof={'kind':'2010printedcountyblockboundedbynextprintedtransition','start':begin,'end_exclusive':end,'matching_physical_name_rows':matches}
 edges.append({'from_source_record_id':endpoint,'to_source_record_id':sid,'from_year':int(native.loc[endpoint].census_year),'to_year':2021,'relation':'same_place','decision_status':'checked_rule_accepted','selection_projection_status':'active_endpoints_selected','admission_rule':'literal typed physical NP name plus independently bounded published owncounty; fullnative alltype samecounty rivals unique; accepted current physical ownpoint and no component year overlap or acceptedpoint contradiction; existing2002parishUF anchor for Хемчик','historical_population_comparability_asserted':False,'population_source_value_quality_unchanged':True,'source_scope_revision':z['scope_revision'],'source_proof_record':f'{S}/scope_verified_five_history_counterpart_proposals.csv.gz#current_source_record_id={sid}','historical_county_positive_anchor_source_record_id':endpoint,'existing_accepted_2010_component_member_source_record_id':old})
 newmembers=members[members.root.isin([a,b])]
 for _,target in newmembers[newmembers.census_year.lt(2021)].iterrows():
  oid=target.source_record_id
  if oid in pr:continue
  assert oid not in usednew;usednew.add(oid);row={k:v for k,v in carrier.items() if v not in ['',None] and k not in ['source_record_id','target_source_record_id','point_ledger_path','integration_input_path','integration_packet_kind']};row.update(target_source_record_id=oid,target_year=int(target.census_year),coordinate_admission_status='reviewed_extension_rule_accepted',latitude=float(carrier['latitude']),longitude=float(carrier['longitude']),historical_census_coordinate_asserted=False,external_provider_ID_binding_asserted=False,point_use_inference='explicit retrospective current own-physical-NP representative point reuse after source-bound stable identity admission; not historical census-day measurement',coordinate_binding_rule='same literal typed NP and positive bounded owncounty/parish; current physical source carrier accepted66; no accepted historical point superseded; fullnative rivals unique',current_carrier_source_record_id=sid,accepted_current_carrier_ledger=carrier['point_ledger_path']);pointuses.append(row)
 if years[a]|years[b]=={2002,2010,2021}:
  for y,h in newmembers.groupby('census_year'):newgain[int(y)]+=int(h.population.sum())
 checks.append({'current_source_record_id':sid,'historic_source_record_id':old,'positive_edge_anchor_source_record_id':endpoint,'current_component_years':sorted(years[a]),'historic_component_years':sorted(years[b]),'source_scope_proof':scopeproof,'alltype_same_region_native_name_rivals':native_rival_rows,'accepted_point_distances':distances,'current_carrier_coordinate_source_record_id':carrier['coordinate_source_record_id'],'current_carrier_coords':[float(carrier['latitude']),float(carrier['longitude'])],'combined_years':sorted(years[a]|years[b]),'newly_complete3year_component':years[a]|years[b]=={2002,2010,2021}})
# Narrow actual point/observation joins check exact coordinate occupation in target year.
for row in pointuses:
 collision=c.execute('select p.source_record_id,o.root from read_parquet(?) p join read_parquet(?) o using(source_record_id) where o.census_year=? and cast(p.latitude as double)=? and cast(p.longitude as double)=?',[str(B/'applied_point_snapshot.parquet'),str(B/'applied_state_observations.parquet'),row['target_year'],row['latitude'],row['longitude']]).fetchall();allowed={native.loc[row['target_source_record_id']].root,native.loc[row['current_carrier_source_record_id']].root};assert all(root in allowed for _,root in collision),'sameyear physical coordinate occupied by different identity'
for bk in books.values():bk.release_resources()
c.close();assert len(edges)==5 and len(pointuses)==4 and newgain=={2002:859,2010:800,2021:892}
pd.DataFrame(edges).to_csv(O/'accepted_identity_edge_delta.csv.gz',index=False,compression={'method':'gzip','mtime':0});pd.DataFrame(pointuses).to_csv(O/'accepted_point_use_delta.csv.gz',index=False,compression={'method':'gzip','mtime':0});(O/'source_bound_admission_checks.json').write_text(json.dumps(checks,ensure_ascii=False,indent=2,default=str)+'\n');members.to_csv(O/'actual66_component_native_observations.csv.gz',index=False,compression={'method':'gzip','mtime':0});pts.to_parquet(O/'actual66_accepted_component_point_references.parquet',index=False,compression='zstd');pin(O/'admit.py')
result={'status':'immutable_source_bound_stable_identity_and_retrospective_point_packet_not_applied','baseline_stage':66,'intended_working_stage':67,'accepted_edges':5,'accepted_point_uses':4,'accepted_current_carriers':5,'point_replacements':0,'admission_holds':0,'full3_new_components':1,'partial2_new_components':4,'conditional_unique_native_primary_gain':{str(y):v for y,v in newgain.items()},'all_current_native_population922_is_not_main_gain':True,'current_carrier_source_provenance_exact_actual66':True,'historical_2010_Hemchik_county_carry_not_asserted':True,'historical_independent_accepted_point_preserved':True,'raw_first_published_population_readbacks':firstcount_checks,'population_and_source_grade_unchanged':True,'unknown_absence_imputation_or_context_credit':False,'actual_State_loads':0,'API_applications':0,'source_downloads':0,'input_pins':PINS,'output_pins':{p.name:{'sha256':sha(p),'bytes':p.stat().st_size} for p in O.iterdir() if p.is_file() and p.name not in ['admission_receipt.json','FINAL_manifest.json']},'seconds':round(time.monotonic()-START,3),'peak_RSS_MB':resource.getrusage(resource.RUSAGE_SELF).ru_maxrss/1024}
(O/'admission_receipt.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n');(O/'FINAL_manifest.json').write_text(json.dumps({p.name:{'sha256':sha(p),'bytes':p.stat().st_size} for p in O.iterdir() if p.is_file() and p.name!='FINAL_manifest.json'},ensure_ascii=False,indent=2)+'\n');print(json.dumps({'receipt_sha256':sha(O/'admission_receipt.json'),'edges':5,'point_uses':4,'conditional_gain':newgain,'peak_RSS_MB':result['peak_RSS_MB'],'seconds':result['seconds']}))
