from pathlib import Path
import pandas as pd,json,gzip,hashlib,urllib.parse,re
O=Path(__file__).parent;sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();A=pd.read_parquet('/dev/shm/over500-moscow-observations.parquet');A=A[A.name_norm.eq('старая руза')];P=pd.read_parquet('/dev/shm/over500-moscow-points.parquet');P=P[P.target_source_record_id.isin(A.source_record_id)];assert len(A)==len(P)==6
pts=[];rejects=[];proof=[]
for typ,fn,code,lat,lon in [('поселок','poselok.raw.gz','46249831026',55+38/60+20/3600,36+19/60+45/3600),('деревня','derevnya.raw.gz','46249831011',55+38/60+55/3600,36+19/60+20/3600)]:
 sf=O/fn;txt=gzip.decompress(sf.read_bytes()).decode();assert code in re.sub(r'\s','',txt);assert 'противоположном берегу' in txt
 obs=A[A.type_norm.eq(typ)];assert len(obs)==3 and obs.root.nunique()==1
 title='Старая Руза ('+('посёлок'if typ=='поселок'else typ)+')';url='https://ru.wikipedia.org/w/index.php?'+urllib.parse.urlencode({'title':title,'action':'raw'})
 for _,x in obs.iterrows():
  p=P[P.target_source_record_id.eq(x.source_record_id)].iloc[0];origin=Path(p.point_ledger_path);assert float(p.latitude)==55.643259 and float(p.longitude)==36.327279
  rejects.append(dict(target_source_record_id=x.source_record_id,rejection_status='reviewed_rejected_coordinate_claim_only',old_latitude=p.latitude,old_longitude=p.longitude,origin_ledger=str(origin),origin_ledger_sha256=sha(origin),reason='Two independent exact-name/type/county/code own articles explicitly opposite river banks and distinct coordinates. Shared Geo classifier default point cannot represent both distinct locality scopes.',native_identity_or_population_rejected=False))
  pts.append(dict(target_source_record_id=x.source_record_id,source_record_id=x.source_record_id,latitude=lat,longitude=lon,coordinate_admission_status='reviewed_extension_rule_accepted',decision_status='reviewed_rule_accepted',coordinate_source_record_id='Wikipedia:'+title,source_sha256=sha(sf),source_locator='Own NP+Россия template lat/lon; exact own OKATO'+code+'; explicit opposite riverbank rival',point_origin_file=str(sf.resolve()),point_origin_sha256=sha(sf),point_origin_locator='Own NP+Россия coordinate template',point_origin_kind='qualified_own_settlement_article',coordinate_binding_rule='Existing correct separate full3 components; native exactname/type/county and independentlyqualified article exact Geo ownOKATO; BOTH articles explicitly separate opposite-bank homonyms, rival positivelyidentified. Own point retrospectively reused by existing accepted same-place continuity; no shared classifier default or population substitution.',own_locality_point=True,provider_binding_asserted=False,direct_historical_coordinate_measurement=False,boundary_comparability_asserted=False,point_temporal_interpretation='Modern ownarticle point reused retrospectively by accepted separate full3 identity continuity',point_supersession_kind='reviewed_wrong_shared_homonym_default_coordinate'))
 proof.append(dict(native_members=obs[['source_record_id','census_year','settlement_name','settlement_type','population','root']].to_dict('records'),ownarticle=title,source_url=url,source_file=str(sf.resolve()),sha256=sha(sf),own_OKATO=code,latitude=lat,longitude=lon,both_articles_explicit_opposite_bank_rivals=True,existing_correct_identity_components_preserved=True,native_values_quality_modified=False,direct_census_point_measurement=False))
pd.DataFrame(pts).to_csv(O/'accepted_point_use_delta.csv',index=False);pd.DataFrame(rejects).to_csv(O/'accepted_point_rejection_delta.csv',index=False);(O/'qualified_opposite_bank_homonym_coordinate_correction_proof.json').write_text(json.dumps(proof,ensure_ascii=False,indent=2))
(O/'README.md').write_text('Bounded coordinate-only correction for two separately coded opposite-bank Старая Руза localities. Both own articles exact type/county/ownGeoOKATO independently bind distinct points; shared Geo default is rejected for all six existing full3 member claims. Correct identity components and native values/qualities untouched. No coverage gain, new identity edge, exact census-time measurement or provider-current-ID claim. Content-hash pins own article raw source; revision metadata unavailable.\n')
receipt=dict(status='frozen_source_bound_coordinate_only_correction',rejected_point_claims=6,replacement_points=6,identity_changes=0,coverage_gain=0,population_or_quality_modified=0,unknown_as_zero=0);(O/'BATCH11_receipt.json').write_text(json.dumps(receipt,indent=2));files=[p for p in O.iterdir()if p.is_file()and not p.name.startswith('BATCH11_manifest')];(O/'BATCH11_manifest.json').write_text(json.dumps([dict(path=str(p.resolve()),sha256=sha(p),bytes=p.stat().st_size)for p in sorted(files)],indent=2));(O/'BATCH11_manifest.sha256').write_text(sha(O/'BATCH11_manifest.json')+'\n');print(receipt)
