from pathlib import Path
import pandas as pd,json,gzip,hashlib,re,xlrd
O=Path(__file__).parent;R=pd.read_csv(O.parent/'remaining81_native_point_targets.csv').fillna('');D=pd.read_pickle('/dev/shm/over500-20261009/east_enriched.pkl');sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();W=[];P=[];raw=[]
S=[('Маракса 1-я','Маракса','batch_01414.json.gz','Колпашевский','Maraksa Pervaya','Ownarticle explicitly cites ownGeoNames1537960 titledMaraksa Pervaya, matching native ordinal1-я, exactдеревня/Колпашевский and nativeНовоселовский subcounty matchingarticleНовосёловское. Native2002Russian88 independently publishedinarticle/sourcecitation corroborates scope; no generic ordinalstrip, no secondMaraksa substitute. 1987Oвощесовхоз merger predates2002 and is not ordinaryidentity/eventcredit.') ]
for name,title,batch,county,needle,rule in S:
 t=R[R.settlement_name.eq(name)].iloc[0];d=D[D.source_record_id.eq(t.source_record_id)].iloc[0];assert county.lower() in t.district_raw.lower();F=Path('/workspace/settlements-raw/data/raw/wikipedia_articles')/batch;J=json.load(gzip.open(F));pi=next(i for i,p in enumerate(J['payload']['query']['pages'])if p['title']==title);page=J['payload']['query']['pages'][pi];text=page['revisions'][0]['slots']['main']['content'];assert needle in text and county in text and 'Новосёловское' in text and '88' in text
 def coord(axis):
  vals={k:float(v.replace(',','.')) for k,v in re.findall(r'\|\s*'+axis+r'_(deg|min|sec)\s*=\s*([0-9.,]+)',text)};assert 'deg'in vals;return vals['deg']+vals.get('min',0)/60+vals.get('sec',0)/3600
 lat,lon=coord('lat'),coord('lon');idx=len(W);W.append(dict(target_source_record_id=t.source_record_id,native_name=name,native_type=t.settlement_type,native_county=t.district_raw,population_preserved=t.population,raw_article_page=page,source_file=str(F),source_sha256=sha(F),rule=rule,explicit_retrospective_point_inference=True,historical_censusday_accuracy_unknown=True))
 P.append(dict(target_source_record_id=t.source_record_id,latitude=lat,longitude=lon,coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_source_record_id=f'wikipedia:ru:pageid={page["pageid"]}',point_origin_file=str(F),point_origin_sha256=sha(F),point_origin_locator=f'payload.query.pages[{pi}].revisions[0].slots.main.content;lat_deg/min/sec,lon_deg/min/sec',point_origin_kind='direct_own_article_infobox_point_explicit_native_name_alias',coordinate_binding_rule=rule,point_use_inference='Explicit retrospective own-locality representative point inference; exact censusday coordinate and population boundaries unknown.',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,external_provider_ID_binding_asserted=True,evidence_file=str(O/'point_binding_witnesses.json.gz'),evidence_locator=f'[{idx}]'))
 f=Path('/workspace/settlements-raw')/d.source_file;b=xlrd.open_workbook(str(f));sh=b.sheet_by_name(t.source_record_id.rsplit(':',2)[1]);row=int(t.source_record_id.rsplit(':',1)[1])-1;assert 'Новоселовский' in str(sh.row_values(306)) and sh.row_values(row)[4]==88;raw.append(dict(source_record_id=t.source_record_id,source_file=str(f),sha256=sha(f),raw_row0=row,raw_cells=sh.row_values(row),parent_row0=306,parent_cells=sh.row_values(306)))
pd.DataFrame(P).to_csv(O/'accepted_point_use_delta.csv',index=False);pd.DataFrame(columns=['from_source_record_id','to_source_record_id','relation','decision_status','admission_method','admission_rule','evidence_file','evidence_locator']).to_csv(O/'accepted_identity_edge_delta.csv',index=False);pd.DataFrame([dict(source_record_id=p['target_source_record_id'],disposition='accepted_independently_bound_own_article_point',ordinary_identity_edges_added=False,missing_year_population_assigned=False)for p in P]).to_csv(O/'record_dispositions.csv',index=False)
for n,v in [('point_binding_witnesses.json.gz',W),('native_source_row_witnesses.json.gz',raw)]:
 with gzip.open(O/n,'wt')as f:json.dump(v,f,ensure_ascii=False)
m=dict(baseline_stage=71,accepted_own_point_uses=len(P),identity_edges_added=0,population_values_modified=False,validation=dict(actual_cached_revision_reopened=True,native_raw_rows_reopened=True,county_and_explicit_own_alias_bound=True),frozen_files=[dict(name=f.name,sha256=sha(f),bytes=f.stat().st_size)for f in sorted(O.iterdir())if f.is_file()]);(O/'freeze_manifest.json').write_text(json.dumps(m,ensure_ascii=False,indent=2));print(len(P))
