import csv,gzip,json,re,hashlib,sys
from pathlib import Path
from collections import Counter
import pandas as pd
Z=Path(__file__).resolve().parent;OLD=Z.parent;E=OLD.parent;sys.path.insert(0,str(E.parent/'mass_linkage'))
from current_chain_state_20261007 import normalize,distance_km
sha=lambda p:hashlib.file_digest(Path(p).open('rb'),'sha256').hexdigest()
def core(v):
 v=normalize(str(v).replace('@ru','').strip('"'));v=re.sub(r'[«»"“”]','',v);v=re.sub(r'\b(?:муниципальное образование|муниципальный округ|городской округ|городское поселение|сельское поселение|муниципальный район|рабочий поселок)\b','',v);return ' '.join(v.split())
def code(v):return str(int(float(v))) if pd.notna(v) and str(v).strip() else ''
P=json.loads((OLD/'active_extreme_point_claims.json').read_text());O=pd.read_csv(OLD/'native_extreme_observations.csv.gz',keep_default_na=False).set_index('source_record_id');D=pd.read_csv(OLD/'all377_extreme_histories.csv',keep_default_na=False).set_index('source_record_id_2021');H=pd.read_csv(OLD/'held_candidates.csv.gz',keep_default_na=False);Q=json.loads((Z/'cached_Q_TSV_bindings.json').read_text());props=json.loads((Z/'cached_truthy_properties.json').read_text());quarantine=pd.read_csv(OLD/'unresolved_old_Geo_point_quarantine.csv.gz',keep_default_na=False)
RAW=Path('/workspace/settlements-raw/data/interim/2021_tochno/data_allsettlements_anon_156_v20251217.parquet');TSV=Path('/workspace/settlements-raw/data/raw/wikimedia/wikidata_oktmo_entities.tsv');SQL=Path('/workspace/settlements-raw/data/raw/historical_classifiers/okato_142_2009/dump-142_2009.sql');GEO=Path('/workspace/settlements-raw/data/raw/historical_geography/geokladr_okato_2011/okato.dbf');raw=pd.read_parquet(RAW,columns=['object_level','object_name','oktmo','region','mun_upper','mun_lower','population']);raw['row_1based']=range(1,len(raw)+1);raw['code']=raw.oktmo.map(code);typed=raw[raw.object_level.eq('Населенный пункт')&~raw.object_name.str.contains(r'\(часть\s*\d+\)',case=False,regex=True,na=False)];counts=Counter(typed.code);cl=pd.read_parquet('/workspace/settlements-work/sources/raw_okato_2009_verification_v1/raw_classifier.parquet').set_index('historical_okato');geo=pd.read_parquet('/workspace/settlements-work/sources/geokladr_raw_verification/geokladr_okato_2011_raw_parsed.parquet').set_index('record_number_1based');sql=SQL.read_text().splitlines();pins={str(p):sha(p) for p in [RAW,TSV,SQL,GEO,OLD/'active_extreme_point_claims.json',OLD/'native_extreme_observations.csv.gz',OLD/'held_candidates.csv.gz',OLD/'unresolved_old_Geo_point_quarantine.csv.gz',OLD/'frozen_asset_manifest.json',Z/'cached_Q_TSV_bindings.json',Z/'cached_truthy_properties.json']};physical={'Q5084','Q532','Q486972','Q2514025','Q15078955','Q20019082','Q2989453'};out=[];witness=[];holds=[];rivals=[];accepted=[]
for h in H.to_dict('records'):
 sid=h['carrier_source_record_id'];own=raw.iloc[int(sid.rsplit(':',1)[1])-1];current=O.loc[sid];p=P[sid];qid=p.get('coordinate_source_record_id','');why='';t=None
 if qid not in Q['qids']:why='No independently sourcebound cached own Wiki entity; rawcurrent provider point lacks independent ownbinding.'
 else:
  candidates=Q['tsv'][qid];coords=(float(p['latitude']),float(p['longitude']));bound=[]
  for candidate in candidates:
   row=candidate['row'];m=re.search(r'POINT\(([-\d.]+) ([-\d.]+)\)',row['?coord']);label=normalize(row['?label'].replace('@ru','').strip('"'));c=row['?okato'].strip('"');c=c.zfill(11) if c else '';classifier=cl.loc[c] if c in cl.index else None
   if classifier is not None and classifier.is_settlement_raw!='t' and c.endswith('000') and c[:-3] in cl.index:c=c[:-3];classifier=cl.loc[c]
   if m and label==normalize(current.settlement_name) and code(row['?oktmo'])==own.code and (float(m[2]),float(m[1]))==coords and core(row['?adminLabel']) in {core(own.mun_lower),core(own.mun_upper)}:bound.append((candidate,c,classifier))
  if not bound:why='Cached Q label/code/P131 literal subordinate context not resolved without ambiguity.'
  elif counts[own.code]!=1:why='Current native code has published NP competitors.'
  else:
   t,c,classifier=bound[0];properties=props[qid];values={prop:{v['row']['value'].rsplit('/',1)[-1] for v in properties if v['row']['property'].endswith('/'+prop)} for prop in ['P31','P131','P721','P764','P625']};parent=t['row']['?admin'].strip('<>').rsplit('/',1)[-1]
   if not values['P31']&physical or parent not in values['P131'] or own.code not in values['P764'] or t['row']['?coord'] not in values['P625']:why='Actual raw P31/P131/P764/P625 properties do not corroborate own physical NP.'
   elif classifier is not None and (classifier.is_settlement_raw!='t' or normalize(classifier['name'])!=normalize(current.settlement_name)):why='Own Wikidata P721 does not identify a typed proper locality.'
 if why:holds.append(dict(carrier_source_record_id=sid,name=current.settlement_name,population_2002=h['population_2002'],population_2010=h['population_2010'],population_2021=h['population_2021'],reason=why));continue
 affected=quarantine[quarantine.carrier_source_record_id.eq(sid)];assert len(affected)>0;oldproof=[]
 for rejection in affected.to_dict('records'):
  target=rejection['target_source_record_id'];old=P[target];assert (float(rejection['old_latitude']),float(rejection['old_longitude']))==(float(old['latitude']),float(old['longitude']));assert old['point_ledger_path']==rejection['origin_ledger'] and sha(Path(rejection['origin_ledger']))==rejection['origin_ledger_sha256'];pins[rejection['origin_ledger']]=rejection['origin_ledger_sha256']
  loc=str(old.get('point_origin_locator',''));m=re.search(r'(?:raw_dbf_record_number_1based|DBF_record_1based|DBFrecord)\s*=\s*(\d+)',loc)
  if m:
   g=geo.loc[int(m[1])];gc=str(g.historical_okato);cc=gc if gc in cl.index else gc[:-3] if gc.endswith('000') else '';oldclass=cl.loc[cc]
   if oldclass.is_settlement_raw!='t' and gc.endswith('000') and gc[:-3] in cl.index:cc=gc[:-3];oldclass=cl.loc[cc]
   assert oldclass.is_settlement_raw=='t' and normalize(oldclass['name'])==normalize(O.loc[target].settlement_name);line=sql[int(oldclass.source_line_1based)-1];assert cc in line and oldclass.name_raw in line;oldproof.append(dict(source_record_id=target,proper_NP_classifier_code=cc,original_Geo_code=gc,classifier_literal=line,classifier_line_1based=int(oldclass.source_line_1based),classifier_status=oldclass.status,bridge='Geo physical NP11digit suffix000 to dated true-PGT8digit classifier' if gc!=cc else 'exact ownNP classifier code',original_native_count=float(O.loc[target].population),original_native_quality=O.loc[target].population_value_quality,original_native_type=O.loc[target].settlement_type,original_native_count_reverified_here=False,accepted_native_observation_from_frozen58=True))
  out.append(dict(target_source_record_id=target,latitude=p['latitude'],longitude=p['longitude'],coordinate_admission_status='reviewed_extension_rule_accepted',point_origin_file=p['point_origin_file'],point_origin_sha256=p['point_origin_sha256'],point_origin_locator=p['point_origin_locator'],point_origin_kind='explicit_retrospective_continuity_from_cached_own_P764_P721_physicalNP_P31_P131_P625',coordinate_source_record_id=sid,wikidata_qid=qid,native_own_code=own.code,typed_classification_proof='P31 physicalNP; dated true ownNP classifier; optional8digitPGT/suffix000 format bridge',current_county=own.mun_upper,current_subordinate=own.mun_lower,P131_actual_parent_qid=parent,historical_coordinate_accuracy='UNKNOWN',historical_point_grade='retrospective representative continuity on already accepted identity; no censusday measurement',source_count_or_quality_modified=False,identity_changed=False))
 for rival in typed[typed.region.eq(own.region)&typed.object_name.eq(own.object_name)].to_dict('records'):rivals.append(dict(carrier_source_record_id=sid,raw_row_1based=rival['row_1based'],native_code=rival['code'],literal_typed_label=rival['object_name'],actual_region=rival['region'],actual_county=rival['mun_upper'],actual_subordinate=rival['mun_lower'],actual_population=rival['population'],is_own_row=rival['row_1based']==own.row_1based))
 origin=Path(p['point_origin_file']);pins[str(origin)]=sha(origin);assert pins[str(origin)]==p['point_origin_sha256'];witness.append(dict(carrier_source_record_id=sid,qid=qid,typed_own_raw2021=own.drop(labels=['code']).to_dict(),own_native_code=own.code,own_native_code_unique_across_all_published_NP_types=True,literal_TSV=t,actual_truthy_properties=properties,source_truthy_file=str(origin),source_truthy_sha256=pins[str(origin)],own_P31_values=sorted(values['P31']),own_P131_values=sorted(values['P131']),P131_descriptor_interpretation='Only administrative form words/quotes/order removed for place-name core; literal labels retained. No county ID/date fabricated.',old_proper_NP_classifier_proofs=oldproof,existing_current_point_unchanged=True,new_primary_count_verification_claim=False));accepted.append(h)
pd.DataFrame(out).to_csv(Z/'accepted_point_use_delta.csv.gz',index=False,compression={'method':'gzip','mtime':0});pd.DataFrame(holds).to_csv(Z/'held_candidates.csv',index=False);pd.DataFrame(rivals).to_csv(Z/'actual_fullraw_name_region_rivals.csv.gz',index=False,compression={'method':'gzip','mtime':0});(Z/'own_current_anchor_witnesses.json').write_text(json.dumps(witness,ensure_ascii=False,default=str,indent=2)+'\n')
# Independently reopen every selected raw truthy line and source TSV row rather than trust the witness projection.
with TSV.open() as stream:
 for linenumber,row in enumerate(csv.DictReader(stream,delimiter='\t'),2):
  for case in witness:
   if linenumber==case['literal_TSV']['line']:assert row==case['literal_TSV']['row']
for case in witness:
 requested={v['line']:v['row'] for v in case['actual_truthy_properties']}
 with gzip.open(case['source_truthy_file'],'rt') as stream:
  for linenumber,line in enumerate(stream,1):
   if linenumber in requested:assert json.loads(line)==requested[linenumber]
assert all(sha(path)==h for path,h in pins.items());assert len(out)==pd.DataFrame(out).target_source_record_id.nunique();summary=dict(status='frozen_verified_cached_ownpoint_restoration_after_original_extreme_quarantine',current_carriers_recovered=len(accepted),historical_point_uses_restored=len(out),remaining_held_carriers=len(holds),restored_native_component_population_by_year={str(y):int(sum(h['population_'+str(y)] for h in accepted)) for y in [2002,2010,2021]},remaining_held_native_component_population_by_year={str(y):int(sum(h['population_'+str(y)] for h in holds)) for y in [2002,2010,2021]},new_identity_edges=0,current_points_changed=0,native_counts_types_quality_metadata_preserved=True,new_primary_population_credit_or_verification_claim=False,no_network_used=True,source_state='frozen58 active claim/native observation witnesses; canonical parent59+extreme quarantine then restore admitted old uses; root60 compositor independently computes actual union',raw_own_TSV_code_properties_and_subordinate_context_independently_reopened=True,input_pins=pins,output_pins={p.name:sha(p) for p in [Z/'accepted_point_use_delta.csv.gz',Z/'held_candidates.csv',Z/'own_current_anchor_witnesses.json',Z/'actual_fullraw_name_region_rivals.csv.gz']},executed_builder_verifier_sha256=sha(Path(__file__)))
(Z/'application_receipt.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2)+'\n');(Z/'verification_receipt.json').write_text(json.dumps({k:summary[k] for k in ['status','current_carriers_recovered','historical_point_uses_restored','restored_native_component_population_by_year','remaining_held_carriers','new_identity_edges','current_points_changed','native_counts_types_quality_metadata_preserved','raw_own_TSV_code_properties_and_subordinate_context_independently_reopened','output_pins','executed_builder_verifier_sha256']},indent=2)+'\n');print(json.dumps({k:summary[k] for k in ['status','current_carriers_recovered','historical_point_uses_restored','restored_native_component_population_by_year','remaining_held_carriers','remaining_held_native_component_population_by_year']},indent=2))
