"""Review six named old-NP absorption events against exact stage62 residual IDs."""
from pathlib import Path
import hashlib,json,gzip,subprocess,re
import pandas as pd,xlrd
ROOT=Path(__file__).resolve().parents[3];E=ROOT/'research_rebuild/evidence';OUT=Path(__file__).resolve().parent;BASE=E/'primary_residual_mass_application_20261008';SEL=Path('/workspace/settlements-delivery/continuation-consolidated-20261003/selected_observations.parquet')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(n,r):pd.DataFrame(r).to_csv(OUT/n,index=False)
def main():
 inputs=[SEL,BASE/'applied_remaining_primary.csv.gz',BASE/'applied_primary_credited_UID_roster.csv.gz',BASE/'applied_component_snapshot.csv.gz',BASE/'applied_point_snapshot.parquet',BASE/'application_receipt.json',BASE/'output_validation_receipt.json',E/'moscow_large_residual_actionable_20261008/own_pages.json.gz',OUT/'bounded_own_articles.json.gz',OUT/'qualified_own_articles.json.gz'];pins={str(p):sha(p) for p in inputs}
 d=pd.read_parquet(SEL);r=pd.read_csv(inputs[1],keep_default_na=False,low_memory=False);r['population']=pd.to_numeric(r.population,errors='coerce');credited=pd.read_csv(inputs[2],keep_default_na=False);snap=pd.read_csv(inputs[3],keep_default_na=False);pt=pd.read_parquet(inputs[4]);idx=d.set_index('source_record_id',drop=False);snap=snap.set_index('source_record_id');pt=pt.set_index('target_source_record_id',drop=False)
 assert r.source_record_id.is_unique and credited.source_record_id.is_unique and not set(r.source_record_id)&set(credited.source_record_id)
 pages=[]
 for p in inputs[-3:]:
  z=json.load(gzip.open(p,'rt'))['query']['pages'];z=z.values() if isinstance(z,dict) else z
  pages.extend((page,p) for page in z)
 cases=[('Коренево','Коренёво (Московская область)','Красково','московская','пгт','2004-07-20','day','Постановлением Губернатора',7380),('Приокск','Приокск','Ступино','московская','город','2004','year','В 2004 году включен в состав города',6183),('Гундоровский','Гундоровский (бывший посёлок)','Донецк','ростовская','город','2004','year','В 2004\u00a0году был включён',5218),('Октябрьский','Октябрьский (Скопин)','Скопин','рязанская','город','2004','year','В 2004\u00a0году включен',4936),('Клязьма','Клязьма (Пушкинский район)','Пушкино','московская','город','2003','year','В 2003\u00a0году включён',3468),('Кречевицы','Кречевицы','Великий Новгород','новгородская','город','2004','year','В 2004\u00a0году включен',3363)]
 events=[];obs=[];points=[];edges=[];credits=[];contexts=[];raws=[];ex=[];states=[]
 raw21=Path('/workspace/settlements-raw/data/interim/2021_tochno/data_allsettlements_anon_156_v20251217.parquet');pins[str(raw21)]=sha(raw21);fr=pd.read_parquet(raw21,columns=['object_level','object_name','population','oktmo'])
 def raw(row):
  p=Path('/workspace/settlements-raw')/row.source_file;pins[str(p)]=sha(p)
  if row.census_year==2021:
   vals=fr.iloc[int(row.source_row)-1];assert vals.object_level=='Населенный пункт' and vals.population==row.population;loc=f'parquet physical row0based={int(row.source_row)-1}; selected1based={int(row.source_row)}';lit=vals.to_json(force_ascii=False)
  elif p.suffix=='.xls':
   sh=xlrd.open_workbook(str(p)).sheet_by_name(str(row.source_sheet)) if str(row.source_sheet)!='0' else xlrd.open_workbook(str(p)).sheet_by_index(0);vals=sh.row_values(int(row.source_row)-1);loc=f'{row.source_sheet}!row1based={int(row.source_row)}';lit=json.dumps(vals[:8],ensure_ascii=False)
   if 'official_tom1' in str(p):assert vals[1]==row.population
   elif row.census_year==2010:assert vals[4]==row.population
   else:assert str(int(row.population)) in [str(z) for z in vals] and any('Корен' in str(z) for z in vals)
  else:
   page=int(row.source_sheet.rsplit('_',1)[1]);t=subprocess.check_output(['pdftotext','-layout','-f',str(page),'-l',str(page),str(p),'-']).decode();lines=[z for z in t.splitlines() if row.settlement_name in z];assert len(lines)==1 and str(int(row.population)) in lines[0].replace(' ','');lit=lines[0];loc=f'PDFpage={page}; actual exact named census row'
  return dict(source_record_id=row.source_record_id,census_year=int(row.census_year),source_path=str(p),source_sha256=sha(p),source_locator=loc,exact_raw_excerpt=lit,native_population=row.population,native_quality=row.population_value_quality,raw_population_matches_selected=True)
 for name,title,parent,region,parenttype,date,precision,needle,pop in cases:
  page,source=next((p,f) for p,f in pages if p['title']==title);rev=page['revisions'][0];t=rev['slots']['main'].get('content',rev['slots']['main'].get('*',''));start=t.index(needle);a=t.rfind('\n',0,start)+1;b=t.find('\n',start);b=len(t) if b<0 else b;locator=f'page{page["pageid"]}:revision{rev["revid"]}';scope='direct_old_NP_'+name.lower();co=page.get('coordinates',[]);coordloc='coordinates[0]'
  if not co:
   coords=[]
   for axis in ['lat','lon']:
    vals=[]
    for suffix in ['deg','min','sec']:
     match=re.search(r'\|\s*'+axis+'_'+suffix+r'\s*=\s*([0-9.]+)',t);vals.append(float(match.group(1)) if match else 0)
    assert vals[0]>0;coords.append(vals[0]+vals[1]/60+vals[2]/3600)
   co=[dict(lat=coords[0],lon=coords[1],globe='earth')];coordloc='typed_own_NP_infobox_lat_deg_min_sec_lon_deg_min_sec'
  assert len(co)==1 and co[0].get('globe')=='earth'
  own=r[r.census_year.eq(2002)&r.region_norm.eq(region)&r.settlement_name.eq(name)];assert len(own)==1 and own.iloc[0].population==pop;sid=own.iloc[0].source_record_id;row=idx.loc[sid];assert sid not in set(credited.source_record_id);assert row.is_additive_settlement_record
  receivers=d[d.region_norm.eq(region)&d.name_norm.eq(parent.lower().replace('ё','е'))&d.settlement_type.eq(parenttype)];assert len(receivers)==3 and set(receivers.census_year)=={2002,2010,2021};assert snap.loc[receivers.source_record_id,'root'].nunique()==1;assert set(receivers.source_record_id)<=set(credited.source_record_id)
  current=receivers[receivers.census_year.eq(2021)].iloc[0];assert current.source_record_id in pt.index
  ex.append(dict(scope_id=scope,source_file=str(source),source_sha256=sha(source),source_locator=locator,revision_timestamp=rev.get('timestamp','not_returned_in_cached_source'),literal_needle=needle,wikitext_char_start=a,wikitext_char_end=b,exact_excerpt=t[a:b]))
  events.append(dict(scope_id=scope,former_locality=name,recipient_city=parent,event_date=date,date_precision=precision,relation='included_in',same_place=False,event_source_file=str(source),event_source_sha256=sha(source),event_source_locator=locator,primary_law_source_reopened=False,roster_closed=False,native_historical_observations=1,receiving_city_actual3year_context=True,event_date_role='Literal secondary own-NP inclusion chronology; year retained where cited act dates are not independently reopened',decision_status='accepted_secondary_own_article_included_in',boundary_comparability='UNKNOWN'))
  raws.append(raw(row));lat,lon=co[0]['lat'],co[0]['lon'];assert -90<lat<90 and -180<lon<180
  points.append(dict(scope_id=scope,target_source_record_id=sid,source_record_id=sid,latitude=lat,longitude=lon,coordinate_admission_status='reviewed_rule_accepted',decision_status='reviewed_rule_accepted',coordinate_source_record_id=locator+':'+coordloc,source_sha256=sha(source),source_locator=locator+':'+coordloc,point_origin_file=str(source),point_origin_sha256=sha(source),point_origin_locator=locator+':'+coordloc,point_origin_kind='own_named_former_NP_Wikipedia_physical_reference_point',own_locality_point=True,recipient_point_assigned_to_child=False,new_ordinary_point_use_proposed=True,point_temporal_interpretation='Modern physical point of named former NP reused for own2002 as explicit retrospective continuity inference; not direct censusday measurement',direct_historical_coordinate_measurement=False,provider_binding_asserted=False,boundary_comparability_asserted=False))
  obs.append(dict(scope_id=scope,place=name,year=2002,source_record_id=sid,native_population=pop,native_population_quality=row.population_value_quality,latitude=lat,longitude=lon,own_point=True,recipient_city=parent,event_date=date,event_date_precision=precision,event_relation='included_in',same_place_identity_asserted=False,receiving_city_2021_source_record_id=current.source_record_id,child_2021_population_assigned=False,is_additive_to_original_final_mixed_census_axis=False,already_in_baseline62_direct_plus_formation_native_ID_union=False,new_native_population_if_event_admitted=pop,whole_city_roster_closure_asserted=False,population_boundary_comparability_asserted=False,native_values_quality_preserved=True))
  edges.append(dict(scope_id=scope,from_source_record_id=sid,to_source_record_id=current.source_record_id,relation='included_in',event_date=date,date_precision=precision,event_source_file=str(source),event_source_sha256=sha(source),event_source_locator=locator,same_place=False,graph_union_allowed=False,whole_city_roster_closure_asserted=False,modern_boundary_reconstruction=False))
  credits.append(dict(scope_id=scope,source_record_id=sid,year=2002,source_population=pop,new_population_on_separate_transformation_path_axis=pop,own_historical_point_verified=True,receiving_city_actual_2002_2010_2021_context_verified=True,is_additive_to_original_final_mixed_census_axis=False,ordinary_three_census_same_place_claim=False))
  for y in [2002,2010,2021]:states.append(dict(scope_id=scope,place=name,year=y,status='actual_separate_own_published_observation' if y==2002 else 'ceased_as_separate_locality_included_in_recipient_before_census',own_population=pop if y==2002 else '',unknown_is_zero=False,recipient_population_assigned_to_child=False,boundary_comparability='UNKNOWN'))
  for q in receivers.itertuples():
   rw=raw(q);pr=pt.loc[q.source_record_id];assert isinstance(pr,pd.Series)
   contexts.append(dict(scope_id=scope,recipient_city=parent,census_year=q.census_year,source_record_id=q.source_record_id,population=q.population,population_value_quality=q.population_value_quality,latitude=pr.latitude,longitude=pr.longitude,point_ledger_path=str(BASE/'applied_point_snapshot.parquet'),is_receiving_city_context_only=True,new_national_credit_population=0,child_count_substituted=False,already_in_baseline62_primary_credit=True,**{k:rw[k] for k in ['source_path','source_sha256','source_locator','exact_raw_excerpt']}))
 for n,rr in [('accepted_inclusion_events.csv',events),('accepted_historical_observations.csv',obs),('accepted_former_locality_own_points.csv',points),('accepted_included_in_event_edges.csv',edges),('accepted_direct_event_native_credit_union.csv',credits),('actual_receiving_city_three_census_context.csv',contexts),('literal_own_inclusion_source_excerpts.csv',ex),('native_raw_row_witnesses.csv',raws),('accepted_available_year_statuses.csv',states)]:write(n,rr)
 holds=[dict(place='Городок-17',reason='Own article dates merger2001 before2002 but native2002 still separately printed; published receiver2002 oldvillage5667/urbanwhole possible duplicate alternatives. No closed sum proof; held.'),dict(place='Субханкулово',reason='2002 same-name native rural386 and urban5663; typechange2006 alone does not establish fate of oldvillage; held multiobject alternative.'),dict(place='Манаскент',reason='2002 rural4275 and urban4872 separately selected; article discusses2005split stationManas and says census2002 already separate; no unique oldsame-place allocation; held.'),dict(place='Немчиновка',reason='Requested generic title disambiguation; no bound own former scientific institute settlement narrative'),dict(place='Агрогород',reason='Qualified requestmissing; no dated event proof')];write('held_targets.csv',holds)
 output={p.name:dict(sha256=sha(p),bytes=p.stat().st_size) for p in OUT.glob('*.csv')};rec=dict(status='reviewed_six_old_NP_included_in_root_replay_pending',baseline_stage=62,input_pins=pins,output_pins=output,accepted_event_cases=len(events),distinct_remaining_native_UIDs=len(credits),conditional_new_UID_population_by_year={'2002':sum(x['source_population'] for x in credits),'2010':0,'2021':0},receiving_city_context_UIDs=len(contexts),receiving_city_new_credit=0,new_retrospective_own_points=len(points),ordinary_same_place_edges_added=0,unknown_population_imputed=False,primary_acts_reopened=False,boundary_comparability='UNKNOWN',packet_capacity_bytes=2000000)
 (OUT/'packet_receipt.json').write_text(json.dumps(rec,ensure_ascii=False,indent=2));assert sum(p.stat().st_size for p in OUT.iterdir() if p.is_file())<2000000;print(json.dumps({'conditional_gain2002':rec['conditional_new_UID_population_by_year']['2002'],'UIDs':len(credits),'context_only':len(contexts)},ensure_ascii=False))
if __name__=='__main__':main()
