from pathlib import Path
import pandas as pd,json,hashlib
E=Path('/workspace/russian-settlements-research/research_rebuild/evidence');I=E/'existing_event_scope_reserve_20261007';O=E/'existing_event_scope_application_20261007';O.mkdir(exist_ok=True)
s=pd.read_csv(I/'candidate_series.csv',keep_default_na=False);x=pd.read_csv(I/'candidate_observations.csv',keep_default_na=False);v=json.load(open('/workspace/settlements-work/continuation_20261004/root/accepted_combined_temporal892_scope/accepted_scoped_trajectories.json'));ts={t['subject_qid']:t for t in v}
rows=[];points=[]
for q,g in x.groupby('qid'):
 assert set(g.year)=={2002,2010,2021} and len(g)==3
 t=ts[q];p=s[s.qid==q].iloc[0];orig=t['current_point_origin'];assert p.point_origin_sha256==orig['sha256'];assert [float(p.latitude),float(p.longitude)]==t['current_point']
 points.append({'trajectory_id':q,'current_source_record_id':t['current_source_record_id'],'latitude':p.latitude,'longitude':p.longitude,'point_origin_file':orig['file'],'point_origin_sha256':orig['sha256'],'point_origin_locator':orig['locator'],'point_ledger_path':p.point_ledger,'point_scope':'accepted current ownrepresentative point; retrospective physical-place context'})
 for r in g.to_dict('records'):
  rows.append({'scope':'existing_accepted_temporal892_reuse','trajectory_id':q,'year':r['year'],'population_source_value':r['population'],'source_record_id':r['source_record_id'],'population_quality':r['quality'],'grain':'own named physical locality, dated source scope','nonadditive_observation':r['nonadditive'],'ordinary_NP3_asserted':False,'accepted_physical_three_observed_census_year_path':True,'accepted_scoped_representative_point':True,'boundary_comparability_asserted':False,'raw_source_file':r['raw_file'],'raw_source_sha256':r['sha256'],'raw_source_locator':r['locator']})
pd.DataFrame(rows).to_csv(O/'accepted_qualified_physical_observations.csv',index=False);pd.DataFrame(points).to_csv(O/'point_provenance.csv',index=False)
credit=pd.read_csv(I/'unique_source_id_net_potential.csv');credit.to_csv(O/'accepted_selected_source_id_credit_union.csv',index=False)
rec=json.load(open(I/'candidate_receipt.json'));rec.update(status='applied_reviewed_secondary_physical_three_census_scopes',root_authorization='Root approved actual own secondary censusreference cohorts and reuse of existing accepted ownpoints; no ordinary loader/report edits.',accepted_series=len(s),accepted_observations=len(x),actual_new_selected_credit_requires_national_union_recomputation=True,decision_status='applied_reviewed_secondary_physical_three_census_scopes',input_hashes={str(p):hashlib.sha256(p.read_bytes()).hexdigest() for p in [I/'candidate_series.csv',I/'candidate_observations.csv',I/'unique_source_id_net_potential.csv']},output_hashes={p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in O.glob('*.csv')});rec['missingyear_rule']='Explicit censusP248/referenceURL/title or censusmethod plus references; estimateQ29051383 held; year-only precision retained'
(O/'application_receipt.json').write_text(json.dumps(rec,ensure_ascii=False,indent=2)+'\n');print('Application bytes',sum(p.stat().st_size for p in O.iterdir() if p.is_file()))
