import json,re,math,hashlib
from pathlib import Path
import pandas as pd,duckdb,xlrd
Z=Path(__file__).resolve().parent;S=Z.parent/'native_singleton_rural_mass_20261008';sam=pd.read_csv(Z/'fixed_sample40.csv',keep_default_na=False);ledger=pd.read_csv(Z/'independent_sample_ledger.csv',keep_default_na=False);C=duckdb.connect();raw=Path('/workspace/settlements-raw/data/interim/2021_tochno/data_allsettlements_anon_156_v20251217.parquet');rawrows=C.execute('select row_number() over() as raw_row_1based,object_level,object_name,oktmo,region,mun_upper,mun_lower,population,fias_id_dadata,fias_level_dadata,oktmo_dadata,settlement_dadata,settlement_type_full_dadata,latitude_dadata,longitude_dadata from read_parquet(?)',[str(raw)]).fetchdf();norm=lambda x:' '.join(str(x).lower().replace('ё','е').split());code=lambda x:str(int(float(x))) if str(x) not in ['None','nan',''] else '';prefix=re.compile(r'^\s*(?:село|деревня|пос[её]лок|хутор|станица|аул|город|станция)\s+',re.I);intervals=pd.read_csv(Z/'independently_reopened_bilateral_native_source_intervals.csv');literal=pd.read_csv(Z/'literal_raw_and_rival_witnesses.csv.gz');allraw=[];conflicts=[];notes=[];providerrows=[]
for case in sam.to_dict('records'):
 sid=case['native2010_source_record_id'];idx=ledger.index[ledger.native2010_source_record_id.eq(sid)][0];holds=json.loads(ledger.loc[idx,'holds_json']);ownrow=int(case['native2021_source_record_id'].rsplit(':',1)[1]);own=rawrows[rawrows.raw_row_1based.eq(ownrow)].iloc[0];point=json.loads(case['source_positive_point_origin_json']);providerrows.append(dict(target2010=sid,source2021=case['native2021_source_record_id'],name=case['name'],**own.to_dict()));rivals=rawrows[rawrows.region.eq(own.region)&rawrows.object_name.map(lambda v:bool(prefix.match(str(v))) and norm(prefix.sub('',str(v)))==norm(case['name']))]
 for rv in rivals.to_dict('records'):
  allraw.append(dict(target2010=sid,selected_target_rawrow=ownrow,raw_ownNP_row=rv['raw_row_1based'],raw_selected_target=rv['raw_row_1based']==ownrow,**rv))
 # Each year needs a namesake interval only when that year has an actual samecounty native competitor.
 srivals=json.loads(literal[(literal.target2010.eq(sid))&literal.kind.eq('allregional_crossclass_literalname_rivals')].iloc[0].witness_json);required={v['year'] for v in srivals if v['same_old_county'] and not v['selected'] and v['year'] in [2002,2021]};verified=set(intervals[(intervals.target2010.eq(sid))&intervals.verified].year)
 if required<=verified:holds=[v for v in holds if v=='external pointorigin requires literalownbinding inspection' or v not in ['samecounty literalname rival needs grain/type exclusion']]
 # Literal municipal captions explicitly retaining the oldcounty name or its named administrative centre.
 if case['name']=='Усохи' and case['region']=='калужская' and norm(own.mun_upper)=='муниципальный район "город киров и кировский район"' and case['old_county_raw']=='Кировский район':
  holds=[v for v in holds if v not in ['actual02/21county captions require explicitcountychange review','independent rawneighbour countybinding unresolved']];notes.append(dict(target2010=sid,note='actual source explicitly names Кировский район in contemporary municipalcaption; county-level continuity inference, no subordinatecouncil or boundary equivalence asserted'))
 if case['name']=='Полушкино' and case['region']=='московская' and norm(own.mun_upper)=='городской округ ступино' and case['old_county_raw']=='Ступинский район':
  holds=[v for v in holds if v not in ['actual02/21county captions require explicitcountychange review','independent rawneighbour countybinding unresolved']];notes.append(dict(target2010=sid,note='Ступинскийрайон / ГородскойокругСтупино neutral municipalcentre caption; sample source/point/code/name and sourcecounty neighbours agree, no historicalboundary equivalence asserted'))
 pointconflict=False
 if point['point_origin_file']==str(raw):
  for rv in rawrows[rawrows.oktmo.map(code).eq(code(own.oktmo_dadata)) & rawrows.object_name.map(lambda v:bool(prefix.match(str(v))))].to_dict('records'):
   if rv['raw_row_1based']==ownrow:continue
   explicit_other=code(own.oktmo_dadata)==code(rv['oktmo']) and code(rv['oktmo'])!=code(own.oktmo)
   if explicit_other:
    pointconflict=True;conflicts.append(dict(target2010=sid,native2002_source_record_id=case['native2002_source_record_id'],native2021_source_record_id=case['native2021_source_record_id'],competing2021_raw_source_record_id='2021:data_allsettlements_anon_156_v20251217.parquet:parquet:'+str(rv['raw_row_1based']),name=case['name'],own_raw_type=own.object_name,other_raw_type=rv['object_name'],own_object_level=own.object_level,other_object_level=rv['object_level'],point_origin_file=point['point_origin_file'],point_origin_locator=point['point_origin_locator'],point_origin_kind=point['point_origin_kind'],point_ledger_path=point['point_ledger_path'],own_population_present=pd.notna(own.population),other_population_present=pd.notna(rv['population']),own_raw2021_row=ownrow,own_native_oktmo=own.oktmo,own_published_population=int(own.population),own_municipal_context=own.mun_lower,provider_code_points_to_other_raw_ownNP=own.oktmo_dadata,other_raw2021_row=rv['raw_row_1based'],other_native_oktmo=rv['oktmo'],other_published_population=int(rv['population']),other_municipal_context=rv['mun_lower'],own_fias_id=own.fias_id_dadata,other_fias_id=rv['fias_id_dadata'],own_latitude=own.latitude_dadata,own_longitude=own.longitude_dadata,other_latitude=rv['latitude_dadata'],other_longitude=rv['longitude_dadata'],same_FIAS=own.fias_id_dadata==rv['fias_id_dadata'],source_identity_invalidated=False,ownpoint_binding_status='hold: rawprovider code explicitly binds anotherpublished ownNP; independent correct ownpoint needed'))
  if pointconflict:
   errors=json.loads(ledger.loc[idx,'errors_json']);errors.append('materialownpointbinding error: rawprovider code explicitly binds anotherpublishedsameyearownNP');ledger.loc[idx,'errors_json']=json.dumps(sorted(set(errors)))
 ledger.loc[idx,'holds_json']=json.dumps(sorted(set(holds)));ledger.loc[idx,'classification']='error' if json.loads(ledger.loc[idx,'errors_json']) else 'hold' if holds else 'pass';ledger.loc[idx,'source_leaf_count_and_county_check']='pass';ledger.loc[idx,'ownpoint_binding_check']='error' if pointconflict else 'pass';ledger.loc[idx,'current_original_allgrain_roster_checked']=True
pd.DataFrame(providerrows).to_csv(Z/'actual_raw2021_provider_ownname_code_fields.csv',index=False);pd.DataFrame(allraw).to_csv(Z/'actual_original2021_all_ownname_crossclass_roster.csv',index=False);pd.DataFrame(conflicts).to_csv(Z/'confirmed_provider_other_published_ownNP_binding_conflicts.csv',index=False);pd.DataFrame(notes).to_csv(Z/'neutral_county_caption_interpretations.csv',index=False);ledger.to_csv(Z/'independent_sample_ledger.csv',index=False);print(ledger[ledger.classification.ne('pass')][['name','region','stratum','classification','holds_json']].to_string(index=False));print(ledger.classification.value_counts().to_dict())
