import json,hashlib
from pathlib import Path
import pandas as pd
Z=Path(__file__).resolve().parent;S=Z.parent/'native_singleton_rural_mass_20261008';sha=lambda p:hashlib.file_digest(Path(p).open('rb'),'sha256').hexdigest();selection=json.loads((Z/'selection_receipt.json').read_text())
for p,h in selection['input_pins'].items():assert sha(p)==h,('frozen singleton source changed',p)
ledger=pd.read_csv(Z/'independent_sample_ledger.csv',keep_default_na=False);sample=pd.read_csv(Z/'fixed_sample40.csv',keep_default_na=False);providers=pd.read_csv(Z/'actual_raw2021_provider_ownname_code_fields.csv',dtype=str,keep_default_na=False);conflicts=pd.read_csv(Z/'confirmed_provider_other_published_ownNP_binding_conflicts.csv',dtype=str,keep_default_na=False);flags=[];pins=json.loads((Z/'independent_raw_input_pins.json').read_text())
for r in ledger.to_dict('records'):
 case=sample[sample.native2010_source_record_id.eq(r['native2010_source_record_id'])].iloc[0];p=json.loads(case.source_positive_point_origin_json);native=providers[providers.target2010.eq(r['native2010_source_record_id'])].iloc[0];c=conflicts[conflicts.target2010.eq(r['native2010_source_record_id'])]
 flags.append(dict(**r,own_native2021_oktmo=native.oktmo,raw2021_provider_oktmo=native.oktmo_dadata,own_native2021_raw_row=native.raw_row_1based,raw_fias_level=native.fias_level_dadata,raw_provider_locality_name=native.settlement_dadata,raw_provider_type=native.settlement_type_full_dadata,point_origin_file=p['point_origin_file'],point_origin_sha256=p['point_origin_sha256'],point_origin_locator=p['point_origin_locator'],point_origin_kind=p['point_origin_kind'],latitude=p['latitude'],longitude=p['longitude'],competing_other_published_ownNP_rows_json=json.dumps(c.to_dict('records'),ensure_ascii=False)))
 pins[p['point_ledger_path']]=sha(p['point_ledger_path'])
pd.DataFrame(flags).to_csv(Z/'all40_flags.csv',index=False)
assert len(ledger)==40 and ledger.native2010_source_record_id.is_unique and ledger.classification.value_counts().to_dict()=={'pass':37,'error':3};assert len(conflicts)==3 and all(conflicts.own_population_present.eq('True')) and all(conflicts.other_population_present.eq('True'))
receipt=dict(status='bounded_independent_fixed_sample_found_material_ownpoint_binding_errors',sample_size=40,source_accepted_histories=2326,sampling_rule=json.loads((Z/'sampling_rule.json').read_text()),stratum_counts=ledger.stratum.value_counts().to_dict(),classification_counts=ledger.classification.value_counts().to_dict(),native_source_leaf_population_type_grain_checks=dict(pass_count=40,errors=0),county_hierarchy_checks=dict(pass_count=40,subordinate_ruralcouncil_changes_not_county_errors=True,neutral_actual_source_municipal_captions_retained=True),ownpoint_binding_checks=dict(pass_count=37,material_errors=3,exact_bad_source_ids=conflicts.target2010.tolist(),failure='Inherited currentDadata codes/FIAS/coordinates bind another actual published2021 NP with distinct native owncode and publishedpopulation; canonical selected observations omit some original raw rivals',not_merely_dated_classifier_code_change=True,geographic_true_coordinate_measurement_not_claimed=True),independence='Sampling fixed before inspection. No source53 acceptance code or predicate imported. Original02/10 leaf rows/counts/type/hierarchy and original21 code/point/roster reopened; cited raw interval anchors independently reopened; every original21 ownname/type rival and exact provider-code row reviewed. Cached raw Wikidata P764/P31/P625 reopened for20 inheritedexternal ownpoints.',source_population_values_modified=False,source_accepted_assets_modified=False,accepted_graph_or_point_ledgers_modified=False,historical_coordinate_use='explicit retrospective continuity inference; no historical coordinate measurement, polygon or boundary harmonization required/asserted',statistical_limit='40 fixed strata are a bounded error check. No population accuracy estimate, CI, Student confidence, or 99percent correctness claim.',source_frozen_manifest_file=str(S/'frozen_asset_manifest.json'),source_frozen_manifest_sha256=sha(S/'frozen_asset_manifest.json'),selection_receipt_sha256=sha(Z/'selection_receipt.json'),raw_and_point_ledger_input_pins=pins,replay=['select_sample.py','audit_sample.py','review_bindings.py','final_assess.py','seal.py'],output_and_code_pins={p.name:sha(p) for p in Z.iterdir() if p.is_file() and p.name!='independent_sample_receipt.json'})
(Z/'independent_sample_receipt.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n');print(json.dumps(dict(classification=receipt['classification_counts'],input_original_source_immutable=True,ownpoint_material_errors=3,packet_bytes=sum(p.stat().st_size for p in Z.iterdir() if p.is_file())),ensure_ascii=False))
