from pathlib import Path
import json,hashlib,shutil
import pandas as pd
C=Path(__file__).parent;O=C.parent/'moscow_complete_scope_mass_application_20261008';O.mkdir(exist_ok=True)
def sha(p):return hashlib.file_digest(p.open('rb'),'sha256').hexdigest()
m=pd.read_csv(C/'candidate_native_scope_constituents.csv').fillna('');m['is_additive_to_ordinary_selected_denominator']=False;m['decision_status']='qualified_accepted_complete_sourceyear_municipal_scope_constituent';m['same_place_edge_created']=False;m['point_assigned_to_individual_NP']=False;m.to_csv(O/'accepted_native_scope_constituents.csv',index=False)
o=pd.read_csv(C/'candidate_scope_observations.csv').fillna('');o['decision_status']='qualified_accepted_complete_sourceyear_municipal_scope_secondary_sources';o['same_place_identity_asserted']=False;o['modern_boundary_series_asserted']=False;o['historical_representative_is_territorial_inference_only']=True;o['scope_year_link_relation']='sourceyear_territorial_composition_change_or_legal_transformation_boundary_unknown';o.to_csv(O/'accepted_transferred_municipal_scope_observations.csv',index=False)
p=pd.read_csv(C/'candidate_municipal_representative_points.csv').fillna('');p['coordinate_admission_status']='reviewed_secondary_own_municipal_representative_accepted';p['historical_representative_is_territorial_inference_only']=True;p['historical_census_date_geography_measured']=False;p['point_temporal_interpretation']='Own modern municipal representative used at territorial grain only; historical representation is an inference, not measured historical geography';p.to_csv(O/'accepted_municipal_representative_points.csv',index=False)
c=pd.read_csv(C/'sourceyear_scope_changes.csv').fillna('');c['scope_year_link_relation']='sourceyear_territorial_composition_change_or_legal_transformation_boundary_unknown';c['same_place_identity_asserted']=False;c['full_modern_boundary_series_asserted']=False;c['later_other_municipal_scopes_in_predecessor']=c.scope_id.map({'moscow_sourceyear_moskovsky':'2002wholeparentincludesDudkino45,laterMosrentgen; preservecomplete10parent,notmodern9projection','moscow_sourceyear_sosenskoye':'2002wholeparentincludesZavodaMosrentgen10336,Mamyri413,Yazovo17,laterdifferentmunicipalscopes; preservecomplete14parent,notmodern11projection'}).fillna('');c.to_csv(O/'accepted_sourceyear_composition_change_qualifiers.csv',index=False)
for fn in ['source_controls.csv','actual_raw_reopened_rows.csv','official_urban_override_witness.csv','legal_literal_rosters_and_scope_changes.txt','official2010_urban_reopened.txt']:shutil.copyfile(C/fn,O/fn)
pins=json.load((C/'source_manifest.json').open());pins.update({str(x):sha(x) for x in C.iterdir() if x.is_file() and x.name!='freeze_application.py'});(O/'source_manifest.json').write_text(json.dumps(pins,ensure_ascii=False,indent=2))
(O/'README.md').write_text('Accepted four complete SOURCEYEAR municipal/predecessor territorial scopes: Moskovsky, Vnukovskoye, Sosenskoye, Schapovskoye. Root approved these positive scopes. Three census-year observations each are linked by explicit territorial composition/legal transformation qualifiers with boundary comparability unknown. They are not ordinary same-place NP identities or full modern-boundary series.\n\nComplete2002parents preserve their complete printed rosters, including laterothermunicipalitymembers in Moskovsky and Sosensky. Ownmodernmunicipal representatives apply only at wholeterritorial grain; historical geography is representative territorial inference only. No point is assigned to a constituent. Actualrawsourcecontrols andprotectedselectedvalues were checked beforeacceptance andremainunchanged; officialMoskovsky2010urbanoverride17366 versus secondary17363 is explicitly pinned. Whole2010municipalclaims andnativechildren discrepancies remainseparate, neverallocated.\n\nNetoldselectedIDunion gains2002=45495,2010=40891; alreadycreditedProkshino32 excluded.2021nationalextra=0 because Moscowcity alreadyhasfederalcontextcredit. Twelve wholeterritorial observations,110nativechildren,4ownmunicipal representatives; zeroordinaryedges/ownNP3/individualpointuses. No fixedmodernboundaryreconstruction.\n')
receipt=json.load((C/'receipt.json').open());receipt.update(status='applied_complete_sourceyear_municipal_scope_secondary_sources',decision_authority='root_explicit_approval_20261008',source_controls_raw_checked=True,composition_changes_preserved=True,same_place_identity_asserted=False,full_modern_boundary_series_asserted=False,historical_representative_is_territorial_inference_only=True,is_additive_to_ordinary_selected_denominator=False,source_manifest_sha256=sha(O/'source_manifest.json'),output_sha256={x.name:sha(x) for x in O.iterdir() if x.is_file() and x.name!='application_receipt.json'});(O/'application_receipt.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2));print(json.dumps(receipt))
