"""Four own-NP lifecycle paths: two formations, temporary absorption, old-NP merger."""
from pathlib import Path
import gzip,json,hashlib,subprocess,math
import pandas as pd,xlrd
ROOT=Path(__file__).resolve().parents[3];E=ROOT/'research_rebuild/evidence';OUT=Path(__file__).resolve().parent;BASE=E/'primary_residual_mass_application_20261008';SEL=Path('/workspace/settlements-delivery/continuation-consolidated-20261003/selected_observations.parquet')
_hash={}
def sha(p):
 p=Path(p)
 if str(p) not in _hash:_hash[str(p)]=hashlib.sha256(p.read_bytes()).hexdigest()
 return _hash[str(p)]
def write(n,r):pd.DataFrame(r).to_csv(OUT/n,index=False)
def dist(a,b):
 x,y,z,w=map(math.radians,[*a,*b]);return 6371.0088*2*math.asin(min(1,math.sqrt(math.sin((z-x)/2)**2+math.cos(x)*math.cos(z)*math.sin((w-y)/2)**2)))
def main():
 files=[SEL,BASE/'applied_remaining_primary.csv.gz',BASE/'applied_primary_credited_UID_roster.csv.gz',BASE/'applied_component_snapshot.csv.gz',BASE/'applied_point_snapshot.parquet',BASE/'application_receipt.json',OUT/'bounded_own_articles.json.gz',OUT/'nemchinovka_NII_article.json.gz',OUT/'novoivanovskoye_article.json.gz',E/'absorbed_residual_direct_events_next_20261008/own_wikipedia_qualified_batch.json.gz'];pins={str(p):sha(p) for p in files}
 d=pd.read_parquet(SEL);idx=d.set_index('source_record_id',drop=False);r=pd.read_csv(files[1],keep_default_na=False,low_memory=False);r['population']=pd.to_numeric(r.population,errors='coerce');credited=pd.read_csv(files[2]);pt=pd.read_parquet(files[4]).set_index('target_source_record_id',drop=False);snapshot=pd.read_csv(files[3]).set_index('source_record_id');assert r.source_record_id.is_unique and not set(r.source_record_id)&set(credited.source_record_id)
 pages=[]
 for p in files[6:]:
  ps=json.load(gzip.open(p,'rt'))['query']['pages'];ps=ps.values() if isinstance(ps,dict) else ps;pages.extend((q,p) for q in ps)
 raw21=Path('/workspace/settlements-raw/data/interim/2021_tochno/data_allsettlements_anon_156_v20251217.parquet');pins[str(raw21)]=sha(raw21);rawfr=pd.read_parquet(raw21,columns=['object_level','object_name','population','oktmo']);books={}
 def raw(q):
  p=Path('/workspace/settlements-raw')/q.source_file;pins[str(p)]=sha(p)
  if q.census_year==2021:
   z=rawfr.iloc[int(q.source_row)-1];assert z.object_level=='Населенный пункт' and z.population==q.population;loc=f'parquet physical0based={int(q.source_row)-1}; selected1based={int(q.source_row)}';lit=z.to_json(force_ascii=False)
  elif p.suffix=='.xls':
   if str(p) not in books:books[str(p)]=xlrd.open_workbook(str(p))
   w=books[str(p)];sh=w.sheet_by_index(0) if str(q.source_sheet)=='0' else w.sheet_by_name(str(q.source_sheet));z=sh.row_values(int(q.source_row)-1);assert any(str(v) in [str(int(q.population)),str(float(q.population))] for v in z);loc=f'{q.source_sheet}!row1based={int(q.source_row)}';lit=json.dumps(z[:8],ensure_ascii=False)
  else:
   page=int(q.source_sheet.rsplit('_',1)[1]);s=subprocess.check_output(['pdftotext','-layout','-f',str(page),'-l',str(page),str(p),'-']).decode();z=[x for x in s.splitlines() if q.settlement_name in x];assert len(z)==1 and str(int(q.population)) in z[0].replace(' ','');loc=f'PDFpage={page}';lit=z[0]
  return dict(source_record_id=q.source_record_id,census_year=int(q.census_year),source_path=str(p),source_sha256=sha(p),source_locator=loc,exact_raw_excerpt=lit,native_population=q.population,native_quality=q.population_value_quality,matches_selected_population=True)
 specs=[dict(scope='upper_temernik2008',name='Верхнетемерницкий',title='Верхнетемерницкий',region='ростовская',years=[2010,2021],needles=['Был выделен в отдельный населённый пункт в 2008 году'],dates=[('2008','year','appeared_from_parent_settlement_territory')],parent='Щепкин',ptype='посёлок',earlier={2002:'outside_own_NP_publication_before2008_split_from_parent'}),dict(scope='anichkovo2012',name='Аничково',title='Аничково (Московская область)',region='московская',years=[2021],needles=['20 апреля 2012','Посёлок образован в апреле 2012'],dates=[('2012-04-20','day','appeared_new_settlement')],parent=None,ptype=None,earlier={2002:'outside_own_NP_coverage_before2012_formation',2010:'outside_own_NP_coverage_before2012_formation'}),dict(scope='phosphoritny2004_2019',name='Фосфоритный',title='Фосфоритный',region='московская',years=[2002,2021],needles=['В 2004 году включён в черту','В апреле 2019 года восстановлен'],dates=[('2004','year','included_in'),('2019-04','month','restored_separate_locality_after_temporary_inclusion')],parent='Хорлово',ptype='пгт',earlier={2010:'not_separately_published_during_documented2004_2019_inclusion'}),dict(scope='nemchinovka_NII2004',name='НИИ Сельского Хозяйства "Немчиновка"',title='Поселок НИИ сельского хозяйства «Немчиновка»',region='московская',years=[2002],needles=['В 2004 году включен в состав деревни','В 2004 году посёлок был включен'],dates=[('2004','year','included_in_and_recipient_converted_to_PGT')],parent='Новоивановское',ptype='пгт',earlier={2010:'ceased_as_separate_NP_before_census_after2004_merger',2021:'ceased_as_separate_NP_before_census_after2004_merger'})]
 events=[];own=[];pointrefs=[];pointdelta=[];credit=[];contexts=[];edges=[];states=[];excerpts=[];rawchecks=[]
 for sp in specs:
  scope='direct_lifecycle_'+sp['scope'];page,path=next((p,f) for p,f in pages if p['title']==sp['title']);rv=page['revisions'][0];t=rv['slots']['main'].get('content',rv['slots']['main'].get('*',''));co=page.get('coordinates');assert co and len(co)==1;loc=f'page{page["pageid"]}:revision{rv["revid"]}';articlelat,articlelon=co[0]['lat'],co[0]['lon']
  for needle in sp['needles']:
   i=t.index(needle);a=t.rfind('\n',0,i)+1;b=t.find('\n',i);b=len(t) if b<0 else b;excerpts.append(dict(scope_id=scope,source_file=str(path),source_sha256=sha(path),source_locator=loc,revision_timestamp=rv.get('timestamp','not_returned_in_cached_source'),needle=needle,wikitext_char_start=a,wikitext_char_end=b,exact_excerpt=t[a:b]))
  selected=r[r.settlement_name.eq(sp['name'])&r.region_norm.eq(sp['region'])&r.census_year.isin(sp['years'])];assert len(selected)==len(sp['years']) and set(selected.census_year)==set(sp['years'])
  for date,precision,rel in sp['dates']:events.append(dict(scope_id=scope,place=sp['name'],relation=rel,event_date=date,date_precision=precision,decision_status='accepted_secondary_literal_own_NP_lifecycle',event_source_file=str(path),event_source_sha256=sha(path),event_source_locator=loc,primary_act_reopened=False,ordinary_same_place=False,graph_union_allowed=False,boundary_comparability='UNKNOWN',physical_creation_asserted=sp['scope']=='anichkovo2012',own_actual_observed_years=','.join(map(str,sp['years']))))
  for q in selected.itertuples():
   s=idx.loc[q.source_record_id];assert s.is_additive_settlement_record and q.source_record_id not in set(credited.source_record_id);rawchecks.append(raw(s));sid=q.source_record_id
   if sid in pt.index:
    existing=pt.loc[sid];assert isinstance(existing,pd.Series);lat,lon=float(existing.latitude),float(existing.longitude);assert dist((lat,lon),(articlelat,articlelon))<5
    pref=dict(scope_id=scope,target_source_record_id=sid,latitude=lat,longitude=lon,existing_accepted_own_point=True,new_point_admission=False,point_origin_file=str(BASE/'applied_point_snapshot.parquet'),point_origin_sha256=sha(BASE/'applied_point_snapshot.parquet'),point_origin_locator=sid,independent_article_point_file=str(path),independent_article_point_sha256=sha(path),independent_article_point_locator=loc+':coordinates[0]',article_latitude=articlelat,article_longitude=articlelon,article_distance_km=dist((lat,lon),(articlelat,articlelon)))
   else:
    assert sp['scope']=='nemchinovka_NII2004';lat,lon=articlelat,articlelon;pref=dict(scope_id=scope,target_source_record_id=sid,latitude=lat,longitude=lon,existing_accepted_own_point=False,new_point_admission=True,point_origin_file=str(path),point_origin_sha256=sha(path),point_origin_locator=loc+':coordinates[0]');pointdelta.append(dict(scope_id=scope,target_source_record_id=sid,latitude=lat,longitude=lon,coordinate_admission_status='reviewed_rule_accepted',coordinate_source_record_id=loc+':coordinates[0]',source_sha256=sha(path),source_locator=loc+':coordinates[0]',point_origin_file=str(path),point_origin_sha256=sha(path),point_origin_locator=loc+':coordinates[0]',point_origin_kind='own_named_former_NP_Wikipedia_physical_reference_point',own_locality_point=True,recipient_point_assigned_to_child=False,point_temporal_interpretation='Modern ownformerNP point reusedfor2002 byexplicit retrospective continuity inference; no directcensusdaymeasurement',direct_historical_coordinate_measurement=False,boundary_comparability_asserted=False))
   pointrefs.append(pref);own.append(dict(scope_id=scope,source_record_id=sid,year=int(q.census_year),place=sp['name'],native_population=s.population,native_population_quality=s.population_value_quality,latitude=lat,longitude=lon,own_actual_observation=True,boundary_comparability='UNKNOWN',ordinary_three_census_same_place_claim=False))
   credit.append(dict(scope_id=scope,source_record_id=sid,year=int(q.census_year),source_population=s.population,new_population_on_separate_transformation_path_axis=s.population,own_historical_point_verified=True,already_in_stage62_primary_axis=False,is_additive_to_original_final_mixed_census_axis=False,ordinary_three_census_same_place_claim=False))
  for y in [2002,2010,2021]:states.append(dict(scope_id=scope,place=sp['name'],year=y,status='actual_own_published_observation' if y in sp['years'] else sp['earlier'][y],own_population=next((v['native_population'] for v in own if v['scope_id']==scope and v['year']==y),''),unknown_is_zero=False,parent_count_assigned_to_child=False,boundary_comparability='UNKNOWN'))
  if sp['parent']:
   receiv=d[d.name_norm.eq(sp['parent'].lower().replace('ё','е'))&d.region_norm.eq(sp['region'])];receiv=receiv[receiv.settlement_type.eq(sp['ptype'])|((receiv.census_year==2002)&(sp['scope']=='nemchinovka_NII2004')&receiv.settlement_type.eq('деревня')&receiv.district_raw.str.contains('Одинцов',na=False))];assert len(receiv)==3 and set(receiv.census_year)=={2002,2010,2021};assert set(receiv.source_record_id)<=set(credited.source_record_id)
   for q in receiv.itertuples():
    rw=raw(q);pp=pt.loc[q.source_record_id];contexts.append(dict(scope_id=scope,parent_locality=sp['parent'],census_year=q.census_year,source_record_id=q.source_record_id,population=q.population,settlement_type=q.settlement_type,population_quality=q.population_value_quality,latitude=pp.latitude,longitude=pp.longitude,context_only=True,new_UID_credit=0,child_count_substituted=False,**{k:rw[k] for k in ['source_path','source_sha256','source_locator','exact_raw_excerpt']}))
   if sp['scope']=='upper_temernik2008':edges.append(dict(scope_id=scope,from_source_record_id=receiv[receiv.census_year==2002].iloc[0].source_record_id,to_source_record_id=selected[selected.census_year==2010].iloc[0].source_record_id,relation='formed_from_parent_NP_territory',event_date='2008',graph_union_allowed=False,parent_UID_credit=0,boundary_comparability='UNKNOWN'))
   elif sp['scope']=='phosphoritny2004_2019':
    parent10=receiv[receiv.census_year==2010].iloc[0].source_record_id
    for y,rel,date in [(2002,'included_in','2004'),(2021,'restored_separate_from','2019-04')]:edges.append(dict(scope_id=scope,from_source_record_id=selected[selected.census_year==y].iloc[0].source_record_id,to_source_record_id=parent10,relation=rel,event_date=date,graph_union_allowed=False,parent_UID_credit=0,boundary_comparability='UNKNOWN'))
   else:edges.append(dict(scope_id=scope,from_source_record_id=selected.iloc[0].source_record_id,to_source_record_id=receiv[receiv.census_year==2021].iloc[0].source_record_id,relation='included_in_and_recipient_formed_PGT',event_date='2004',graph_union_allowed=False,parent_UID_credit=0,boundary_comparability='UNKNOWN'))
 for n,rows in [('accepted_lifecycle_events.csv',events),('accepted_own_sourceyear_observations.csv',own),('accepted_own_point_references.csv',pointrefs),('accepted_point_use_delta.csv',pointdelta),('accepted_source_UID_credit_union.csv',credit),('accepted_available_year_statuses.csv',states),('accepted_typed_context_edges.csv',edges),('actual_parent_three_year_context_only.csv',contexts),('literal_source_excerpts.csv',excerpts),('native_raw_row_witnesses.csv',rawchecks)]:write(n,rows)
 holds=[dict(place=n,reason=reason) for n,reason in [('Сингапай','Own article founded1980, no literal census2002 absence/event proof; hold missingoldcount'),('Казачьи Лагери','Own article ancientcamp narrative, no post2002birth or publicationabsence proven'),('Круглое Поле','Founded1953, published2002ethnicity context exists; no trueabsence proof; temporalnativeidentity review needed'),('Метлино','Ownarticle secondary2010 population3684table/3694text vs protectedselected3696; no2002publicationabsence proved. Do notfake2002zero')]];write('held_targets.csv',holds)
 outputs={p.name:dict(sha256=sha(p),bytes=p.stat().st_size) for p in OUT.glob('*.csv')};rec=dict(status='reviewed_four_lifecycle_available_year_paths_root_replay_pending',baseline_stage=62,input_pins=pins,output_pins=outputs,lifecycle_paths=4,event_rows=len(events),native_UIDs=len(credit),conditional_new_UID_population_by_year={str(y):int(sum(z['source_population'] for z in credit if z['year']==y)) for y in [2002,2010,2021]},parent_context_UIDs=len(contexts),parent_new_credit=0,new_own_retrospective_points=len(pointdelta),existing_own_point_references=len(pointrefs)-len(pointdelta),ordinary_graph_edges_added=0,old_unknown_values_imputed=False,primary_acts_reopened=False,boundary_comparability='UNKNOWN');(OUT/'packet_receipt.json').write_text(json.dumps(rec,ensure_ascii=False,indent=2));assert sum(p.stat().st_size for p in OUT.iterdir())<2000000;print(json.dumps(rec['conditional_new_UID_population_by_year']))
if __name__=='__main__':main()
