from pathlib import Path
import json,gzip,re,unicodedata,ast,collections
import pandas as pd,duckdb
O=Path(__file__).parent;E=O.parent;RULE=O/'review_articles.py';normalize=lambda v:str(v).lower().replace('ё','е');tree=ast.parse(RULE.read_text());exec(compile(ast.Module(body=[n for n in tree.body if isinstance(n,ast.FunctionDef) and n.name in ['bare','namekey','fullcode','infobox','val','clean']],type_ignores=[]),str(RULE),'exec'));f=pd.read_csv(E/'current_live_named_residual_sources_20261008/prioritized_unresolved_after_live_sources.csv.gz',dtype=str,keep_default_na=False);p=pd.read_csv(E/'grounded_current_carrier_expansion_20261008/accepted_current_point_delta.csv.gz',dtype=str,keep_default_na=False);f=f[~f.source_record_id.isin(p.target_source_record_id)];t=pd.read_csv(O/'searched_own_article_title_candidates_filtered.csv.gz',dtype=str,keep_default_na=False);ix=json.loads(gzip.open(O/'searched_own_article_sources_index.json.gz','rt').read());entities=json.loads(gzip.open(O/'own_article_entities_index.json.gz','rt').read());names=collections.defaultdict(list);codes=collections.defaultdict(list)
for z in ix:
 page=z['page'];revs=page.get('revisions',[])
 if not revs:continue
 text=revs[0].get('slots',{}).get('main',{}).get('content','');box=infobox(text);aname=clean(val(box,'русское название'));names[namekey(aname)].append(z['article_title']);qid=page.get('pageprops',{}).get('wikibase_item','');ec=entities.get(qid,{}).get('entity',{}).get('claims',{}).get('P764',[]);cs=[str(q.get('mainsnak',{}).get('datavalue',{}).get('value','')) for q in ec if q.get('rank')!='deprecated']+[re.sub(r'\D','',val(box,k)) for k in ['цифровой идентификатор','цифровой идентификатор 2']]
 for code in set(cs):
  if len(code)==11 and code.isdigit():codes[code].append(z['article_title'])
rows=t[['source_record_id','article_title']].to_dict('records')
for z in f.to_dict('records'):
 for title in set(names.get(namekey(z['settlement_name']),[])+codes.get(fullcode(z['oktmo']),[])):rows.append({'source_record_id':z['source_record_id'],'article_title':title,'discovery_kind':'existing complete ownarticle cache closedname or direct literalfullowncode; no newrequest'})
t=pd.DataFrame(rows).fillna('').drop_duplicates(['source_record_id','article_title']);t=t[t.source_record_id.isin(f.source_record_id)];t.to_csv(O/'searched_own_article_title_candidates_filtered.csv.gz',index=False,compression={'method':'gzip','mtime':0});f.to_csv(O/'positive100_priority_roster.csv.gz',index=False,compression={'method':'gzip','mtime':0});c=duckdb.connect();c.register('targets',f[['source_record_id']]);w=c.execute('select w.* from read_parquet(?) w join targets using(source_record_id)',['/workspace/settlements-work/wikidata/wide_v5/wide_point_bindings.parquet']).fetchdf();w.to_csv(O/'cached_Wikidata_positive100_bindings.csv.gz',index=False,compression={'method':'gzip','mtime':0});c.close();print('allremainingtargetscachedjoin',len(f),'articlepairs',len(t),'uniqueNPs',t.source_record_id.nunique())
