from pathlib import Path
import json,hashlib,re,gzip
import pandas as pd
O=Path(__file__).parent;E=O.parent;sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();W=O/'accepted_source_bound_ownpoint_evidence.csv.gz';w=pd.read_csv(W,dtype=str,keep_default_na=False);entities=json.loads(gzip.open(O/'own_article_entities_index.json.gz','rt').read());proof=[]
for z in w.to_dict('records'):
 if z['point_origin_kind']=='own_physicalNP_article_revision_infobox':
  lit=json.loads(z['coordinate_literal_json']);xy=[]
  for axis in ['lat','lon']:
   p=[float(lit.get(axis+'_'+a,'').replace(',','.')) if lit.get(axis+'_'+a,'') else 0 for a in ['deg','min','sec']];v=p[0]+p[1]/60+p[2]/3600
   if lit.get(axis+'_dir','').upper() in ['W','S','З','Ю']:v=-abs(v)
   xy.append(v)
  assert xy==[float(z['latitude']),float(z['longitude'])];proof.append('literal ownNP infobox DMS/decimal coordinate reopened and exact computed float checked')
 else:
  q=z['live_own_article_QID'];e=entities[q];vals=[]
  for claim in e['entity'].get('claims',{}).get('P625',[]):
   v=claim.get('mainsnak',{}).get('datavalue',{}).get('value',{})
   if claim.get('rank')!='deprecated' and isinstance(v,dict) and v.get('globe','').endswith('/Q2') and 41<=float(v.get('latitude',0))<=82 and -180<=float(v.get('longitude',999))<=180:vals.append((float(v['latitude']),float(v['longitude'])))
  assert len(set(vals))==1 and next(iter(set(vals)))==(float(z['latitude']),float(z['longitude']));assert e['origin_file']==z['point_origin_file'] and sha(Path(e['origin_file']))==z['point_origin_sha256'];proof.append('single ownarticle-linked QID nondeprecated Earth P625 literal value reopened, complete rawclaims retained, no first coordinate selected')
 assert sha(Path(z['point_origin_file']))==z['point_origin_sha256'];assert sha(Path(z['article_identity_source_file']))==z['article_identity_source_sha256']
w['literal_admitted_point_source_reopened_validation']=proof;w.to_csv(W,index=False,compression={'method':'gzip','mtime':0,'compresslevel':9})
rp=O/'joint64_point_admission_receipt.json';r=json.loads(rp.read_text());r['output_pins'][str(W)]=sha(W);r['input_pins'][str(O/'finalize_packet.py')]=sha(O/'finalize_packet.py');r['input_pins'][str(O/'expand_all_cached_article_targets.py')]=sha(O/'expand_all_cached_article_targets.py');r['all_admitted_point_literals_and_article_identity_bytes_reopened']=True;rp.write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n')
f=pd.read_csv(O/'positive100_priority_roster.csv.gz',dtype=str,keep_default_na=False);rem=f[~f.source_record_id.isin(w.source_record_id)].copy();h=pd.read_csv(O/'article_binding_holds.csv.gz',dtype=str,keep_default_na=False);h=h[~h.source_record_id.isin(w.source_record_id)];reason=h.groupby('source_record_id').hold_reasons.agg(lambda s:';'.join(sorted(set(';'.join(s).split(';'))))).to_dict();rem['live_own_article_hold_reasons']=rem.source_record_id.map(reason).fillna('');reviewed=set(pd.read_csv(O/'all_article_binding_checks.csv.gz',dtype=str,keep_default_na=False).source_record_id);rem['live_source_status']=rem.source_record_id.map(lambda s:'reviewed_own_article_source_binding_held' if s in reason else 'no_reviewed_source_positive_own_article');rem.to_csv(O/'prioritized_unresolved_after_live_sources.csv.gz',index=False,compression={'method':'gzip','mtime':0,'compresslevel':9});h.to_csv(O/'unresolved_article_source_binding_holds.csv.gz',index=False,compression={'method':'gzip','mtime':0,'compresslevel':9})
fetch=json.loads((O/'live_source_fetch_receipt.json').read_text());r.update(unresolved_current_missing_ownpoint_rows=len(rem),unresolved_current_known_population2021=float(pd.to_numeric(rem.population,errors='coerce').sum()),remaining_positive100_NPs=int((pd.to_numeric(rem.population,errors='coerce')>=100).sum()),unresolved_reviewed_article_binding_held_NPs=h.source_record_id.nunique(),unresolved_reviewed_article_comparison_holds=len(h),closed_title_source_requests=len(fetch['article_source_response_pins']),closed_title_variants_queried=fetch['new_closed_title_candidates_queried'],prior186rate_limited_searches_not_retried=True,source_population_unknown_not_imputed=True,generated_pack_status='frozen_ready_future64_root_replay_pending');(O/'final_handoff_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n')
(O/'README.md').write_text("""# Cached ownarticle residual expansion, future stage 64

Frozen delta: **13 current NP ownpoints /2,537 known 2021 residents**, including nine with at least 100 residents. All are literal proper ownNP infobox coordinates, reopened and checked against raw source bytes. Original external provider IDs, census-day coordinate measurements, historical legal-type changes and population boundary comparability remain unasserted.

The pass prioritized 98 larger current missing-ownpoint NPs after excluding the frozen 28-point live packet and temporal worker's 53 current points. Existing complete article/entity caches were reused first. 734 closed literal ownname/type/region/county title variants were retrieved in 21 bounded batches with normal TLS, six-second request pacing and rate-limit backoff. The previous 186 unavailable search queries were not retried. All returned plausible physical NP pages and competing alternatives were reviewed, without selecting a first homonym. Then the entire 2,183-row remaining cohort was joined to the enlarged cached named/article-code witness pool without new requests; 509 target/article pairs were checked.

Ordinary admission requires positive physical ownNP article typing, proper ownname or explicit own full native code, region/county association, and coded or specific-parish distinction when native namesakes exist. Explicit native railway settlement descriptors can disambiguate the published station-settlement subtype. Unknown printed native subtype may be completed by an explicitly code-bound physical NP article when native object level is NP and the own full code is unique. Source label spelling defects are preserved. Region alias Чечня = Чеченская Республика, administrative term кожуун = район and abbreviation им. = имени are explicit closed semantic equivalences. A complete literal native municipal wikilink inside the ownNP definition paragraph can prove actual municipal context when the infobox uses a different grammatical name; this admits Северный401 through its own physical village article, without borrowing a Cheboksary city point.

`accepted_point_use_delta.csv.gz` is replay-ready. `accepted_source_bound_ownpoint_evidence.csv.gz` retains native own rows, every native rival, full owncode claims, source revisions, complete infobox/lead excerpts and exact hashes/locators. `joint64_point_admission_holds.csv.gz` preserves four source-positive conflicts /7 residents. The final screen uses actual final stage 63 point/component snapshots, the immutable planned 28+53 current-point packets, and every new point together; root's final future stage 64 replay remains required. All accepted points pass current occupation within 1 m and component 5 km consistency. No existing point is superseded. Zero admitted rows already have primary-axis credit, but ownpoint population is not an actual coverage-gain claim.

Remaining names without a distinguishing code/parish stay held, including the larger Popovka and Nikolskoye alternatives. Current counts, population qualities, graph edges, canonical files and earlier frozen packets remain unchanged. Unknown populations remain unknown. The frozen manifest pins all assets; existing large original sources and snapshots are referenced instead of copied. Root owns integration and commits.
""")
files=[p for p in O.iterdir() if p.is_file() and p.name!='frozen_asset_manifest.json'];m={'packet_status':'frozen_ready_future64_root_replay_pending','accepted_new_current_ownpoints':len(w),'accepted_known_population2021':r['accepted_known_population2021'],'assets':{str(p):{'sha256':sha(p),'bytes':p.stat().st_size} for p in sorted(files)},'generated_total_bytes':sum(p.stat().st_size for p in files),'budget_bytes':20_000_000,'upstream_pins':r['input_pins']};assert m['generated_total_bytes']<m['budget_bytes'];(O/'frozen_asset_manifest.json').write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n');print(json.dumps({k:v for k,v in r.items() if k not in ['input_pins','output_pins']},ensure_ascii=False));print('manifest_sha256',sha(O/'frozen_asset_manifest.json'));print('bytes',m['generated_total_bytes'])
