from pathlib import Path
import pandas as pd,json,gzip,hashlib,xlrd,pyarrow.parquet as pq,re
D=Path(__file__).parent;B=D.parent;E=B.parent;sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();P=B/'urban_point_resolution';pr=json.loads((P/'physical_point_receipt.json').read_text());assert pr['physical_PGT_points']==2 and pr['network_requests']==0
for fn,h in pr['outputs'].items():assert sha(P/fn)==h
for path,h in pr['source_manifest'].items():assert sha(path)==h
points=pd.read_csv(P/'raw2011_own_physical_PGT_points.csv',keep_default_na=False);sel=Path('/workspace/settlements-delivery/continuation-consolidated-20261003/selected_observations.parquet');m=pq.read_table(sel,columns=['source_record_id','census_year','settlement_name','settlement_type','population','population_value_quality','source_file','source_sheet','source_row','region_norm']).to_pandas().set_index('source_record_id');ef=E/'moscow_large_residual_actionable_20261008/municipal_entities.json.gz';pf=E/'moscow_large_residual_actionable_20261008/municipal_pages.json.gz';ents=json.load(gzip.open(ef,'rt'))['entities'];pages={p.get('pageprops',{}).get('wikibase_item'):p for p in json.load(gzip.open(pf,'rt'))['query']['pages'].values()};raw02=Path('/workspace/settlements-raw/data/raw/2002_official_tom1/1_TOM_01_04.xls');raw10=Path('/workspace/settlements-raw/data/raw/2010/010_711691e352_2._20Kostrom_Kur_Lip_Moscow_MoscObl_Orlov_2010.xls');s02=xlrd.open_workbook(str(raw02)).sheet_by_index(0);s10=xlrd.open_workbook(str(raw10)).sheet_by_name('Data Sheet');hist=[];municip=[];roster=[];edges=[];evidence=[];pin={str(p):sha(p) for p in [sel,ef,pf,raw02,raw10]}|pr['source_manifest']
for name,q,n02,n10,code,rr in [('Киевский','Q4373601',1208,11246,'46238558000',range(11246,11251)),('Кокошкино','Q4373603',1209,11251,'46238560000',range(11251,11254))]:
 case='urban_formation_'+name;pp=points[points.historical_okato.astype(str).eq(code)].iloc[0];e=ents[q];pg=pages[q];t=pg['revisions'][0]['slots']['main']['*'];formation='\n'.join(z for z in t.splitlines() if '2005' in z and ('образован' in z or 'создан' in z or 'Дата образования' in z));assert formation,(name,'missingdocumented2005formation')
 excerpt='\n'.join(z for z in t.splitlines() if any(w in z for w in ['2005','2012','включило','включили']))
 evidence.append(dict(case_id=case,municipal_entity=q,article_revision=pg['revisions'][0]['revid'],source_file=str(pf),source_sha256=sha(pf),cached_formation_and_transfer_excerpt=excerpt,source_grain_policy='2002properPGT is authentic individualNP predecessorcontext;2010properPGT andwholemunicipal observations distinct;2021wholemunicipal only, neverNPchildcount',sourceyear_roster_change='Kokoshkino2010threeleaves versus laterarticlefour; Kiev2010fiveleaves,articleMachikhinooutsideMoscowbutadministrativelysubordinated; boundaryUNKNOWN'))
 ids={}
 for y,n,src,sheet in [(2002,n02,raw02,'0'),(2010,n10,raw10,'Data Sheet')]:
  sid='2002:1_TOM_01_04.xls:0:'+str(n) if y==2002 else '2010:'+raw10.name+':Data Sheet:'+str(n);r=m.loc[sid];assert r.settlement_type=='пгт' and r.settlement_name==name and r.region_norm=='московская';raw=(s02 if y==2002 else s10).row_values(n-1);count=raw[1] if y==2002 else raw[4];assert count==r.population
  ids[y]=sid;hist.append(dict(case_id=case,observation_id=sid,source_record_id=sid,census_year=y,settlement_name=name,settlement_type='пгт',authentic_observation_grain='individual_proper_PGT_NATIVE_NP_not_municipality',population=r.population,population_quality=r.population_value_quality,source_file=str(src),source_sha256=sha(src),source_locator=sheet+'!row_1based='+str(n),original_raw_row_json=json.dumps(raw[:8],ensure_ascii=False),latitude=pp.latitude,longitude=pp.longitude,point_grain='own_physical_PGT',point_source_file=pp.physical_source_file,point_source_sha256=pp.physical_source_sha256,point_source_locator='DBFrecord='+str(pp.raw_record_number_1based)+';byte='+str(pp.raw_record_byte_offset_0based),point_source_date=pp.physical_source_updated_at,point_origin_kind='cached_raw_geokladr2011_typed_ownphysical_PGT_with2009actualNPclassifier',historical_point_grade=pp.temporal_grade,censusday_point_measured_exactly=False,municipal_P625_projected_to_NP=False,source_values_modified=False,ownNP2021_count_created=False,candidate_only=True,ordinary_graph_changed=False))
  # All originalregional typednamesake candidates before nativecontext filter, keptcompact.
  rivals=m[(m.census_year==y)&m.settlement_name.eq(name)];evidence.append(dict(case_id=case,census_year=y,all_exact_literal_name_native_competitors_json=json.dumps([dict(source_record_id=k,census_year=int(v.census_year),type=v.settlement_type,region=v.region_norm) for k,v in rivals.iterrows()],ensure_ascii=False),selected_actual_native_ID=sid,identity_context_rule='UniqueownPGTtypednameinMoscowoblast, federal2002NaroFominsk urbanroster/original2010KievKokmunicipalrawblock,2009trueNPpgtclassificationand2011livephysicalrecord; notglobalalltypenamesakeclaim'))
 claims={}
 for st in e['claims']['P1082']:
  for dt in st.get('qualifiers',{}).get('P585',[]):
   val=dt.get('datavalue',{}).get('value',{});year=int(val.get('time','+0000')[1:5])
   if year in [2010,2021]:claims[year]=(st,val)
 assert set(claims)=={2010,2021};munpoint=e['claims']['P625'][0];mv=munpoint['mainsnak']['datavalue']['value']
 for y in [2010,2021]:
  st,val=claims[y];assert st.get('references');municip.append(dict(case_id=case,observation_id=case+':municipal:'+str(y),census_year=y,municipal_entity=q,population=float(st['mainsnak']['datavalue']['value']['amount']),population_quality='secondary_explicit_census_referenced_whole_sourceyear_municipal_total',authentic_observation_grain='whole_sourceyear_municipal_territory_not_properPGT',source_file=str(ef),source_sha256=sha(ef),source_locator=st['id'],population_date=val['time'],references_json=json.dumps(st['references'],ensure_ascii=False),latitude=mv['latitude'],longitude=mv['longitude'],point_role='representative_scope',point_source_file=str(ef),point_source_sha256=sha(ef),point_source_locator=munpoint['id'],own2002_municipal_observation_created=False,complete3ownmunicipalseries_asserted=False,individual_child2021_population_asserted=False,national2021_native_population_credit=0,boundary_comparability='UNKNOWN',ordinary_same_place=False,candidate_only=True))
 for n in rr:
  sid='2010:'+raw10.name+':Data Sheet:'+str(n);raw=s10.row_values(n-1);selected=sid in m.index
  assert selected or raw[4]==''
  roster.append(dict(case_id=case,year=2010,raw_row_1based=n,raw_label=raw[3],source_record_id=sid if selected else '',native_population=m.loc[sid].population if selected else '',native_quality=m.loc[sid].population_value_quality if selected else 'raw_count_blank_unknown_not_zero',raw_population=raw[4],raw_original_row_json=json.dumps(raw[:6],ensure_ascii=False),raw_file=str(raw10),raw_sha256=sha(raw10),own_PGT_eventcredit_candidate_only=sid==ids[2010],nonPGT_sibling_ID_eventcredit_proposed=False,nonPGT_point_assigned=False,unknown_count_imputed=False))
 edges.extend([dict(case_id=case,from_observation_id=ids[2002],to_observation_id=ids[2010],relation='historical_own_PGT_native_continuity_context_only',effective_date='UNKNOWN',identity_axis='separate_urban_formation_event_path',ordinary_graph_changed=False,candidate_only=True),dict(case_id=case,from_observation_id=ids[2002],to_observation_id=case+':municipal:2010',relation='documented2005_municipal_formation_with_existing_properPGT_as_constituent',effective_date='2005',identity_axis='separate_urban_formation_event_path',ordinary_graph_changed=False,candidate_only=True),dict(case_id=case,from_observation_id=ids[2010],to_observation_id=case+':municipal:2010',relation='contained_in_actual_complete_published2010municipal_roster',effective_date='2010 census',identity_axis='separate_urban_formation_event_path',ordinary_graph_changed=False,candidate_only=True),dict(case_id=case,from_observation_id=case+':municipal:2010',to_observation_id=case+':municipal:2021',relation='published_whole_sourceyear_municipal_trace_with_documented2012Moscowtransfer',effective_date='2012-07-01 transfer;sourceyearboundarycomparabilityUNKNOWN',identity_axis='separate_urban_formation_event_path',ordinary_graph_changed=False,candidate_only=True)])
for fn,data in [('candidate_historical_own_PGT_observations',hist),('candidate_whole_municipal_observations',municip),('actual_complete2010_municipal_roster_context_only',roster),('candidate_separate_formation_event_edges',edges),('cached_native_context_and_formation_proofs',evidence)]:pd.DataFrame(data).to_csv(D/(fn+'.csv'),index=False)
pd.DataFrame([dict(year=year,properPGTnative_population=sum(h['population'] for h in hist if h['census_year']==year),properPGTnative_ID_count=sum(h['census_year']==year for h in hist),baseline44_existing_point_count=0,new_native_population_claimed_asordinary_orcomplete3ownmunicipal=0,conditional_separate_event_axis_population_pending_root_union_and_adapter=True) for year in [2002,2010]]).to_csv(D/'conditional_own_PGT_event_native_population.csv',index=False)
for p in P.glob('*.csv'):pin[str(p)]=sha(p)
r=dict(status='frozen_positive_two_ownphysical_PGT_formation_event_candidates',cases=2,historical_ownPGT_native_observations=4,whole_municipal_observations=4,independent_ownphysical_PGT_point_sources=2,own2002_municipal_observations=0,complete3ownmunicipal_scopes=0,ownNP2021_childcounts=0,ordinary_edges_applied=0,ordinary_pointuses_applied=0,properPGT_population_by_year={2002:18156,2010:19694},all2010_municipal_leaf_knownpopulation_context_only={"Киевский":8317,"Кокошкино":11880},published2010_municipal_controls={"Киевский":8318,"Кокошкино":11880},unknown2010Machikhino_count_preserved=True,protected_or_unknown_control_difference_unallocated=True,nonPGT_sibling_ID_credit_proposed=False,source_values_quality_unmodified=True,synthetic9907_whole_created=False,network_requests=0,root_separate_event_axis_acceptance_and_adapter_pending=True,source_manifest=pin,outputs={p.name:sha(p) for p in D.glob('*.csv')},code_sha256={'build.py':sha(D/'build.py')});(D/'candidate_event_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n');print(json.dumps({k:r[k] for k in ['status','cases','properPGT_population_by_year','network_requests']},ensure_ascii=False))
