from pathlib import Path
import pandas as pd,json,sys,hashlib,collections,ast,re,xlrd
R=Path('/workspace/russian-settlements-research');O=Path(__file__).parent;S=Path('/dev/shm/settlements-stage71-20261009');sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from current_chain_state_20261007 import normalize,distance_km
from apply_unique_county_name_bridge_20261007 import county_key
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
f=pd.read_parquet(S/'applied_state_observations.parquet').fillna('');b=f.set_index('source_record_id');meta=Path('/workspace/settlements-delivery/continuation-consolidated-20261003/selected_observations.parquet');m=pd.read_parquet(meta).fillna('').set_index('source_record_id');P=S/'applied_point_snapshot.parquet';p=pd.read_parquet(P,columns=['target_source_record_id','latitude','longitude','coordinate_source_record_id','point_origin_file','point_origin_sha256','point_origin_locator','point_origin_kind','point_ledger_path']).fillna('').drop_duplicates('target_source_record_id').set_index('target_source_record_id').to_dict('index');rp=Path('/workspace/settlements-raw/data/interim/2021_tochno/data_allsettlements_anon_156_v20251217.parquet');rf=pd.read_parquet(rp,columns=['object_name','population','oktmo','mun_upper','mun_lower']);groups={root:g.source_record_id.tolist() for root,g in f.groupby('root')};gvalid={root:len(ids)==3 and {str(b.loc[i,'census_year']) for i in ids}=={'2002','2010','2021'} for root,ids in groups.items()};rawpar={};books={};checks={};pins={str(q):sha(q) for q in [S/'applied_state_observations.parquet',S/'applied_component_snapshot.csv.gz',P,meta,rp,O/'direct_native_witnesses.csv.gz']};t=ast.parse((O/'build_packet.py').read_text());fn=ast.unparse(next(x for x in t.body if isinstance(x,ast.FunctionDef) and x.name=='check')).replace("actual = re.sub('ского$', 'ский', actual)","actual = re.sub('ского$', 'ский', actual); actual = re.sub('цкого$', 'цкий', actual)");exec(fn);oldw=pd.read_csv(O/'direct_native_witnesses.csv.gz').fillna('').set_index('source_record_id').to_dict('index');existing=set()
for n in ['accepted_point_use_delta.csv','supplemental_accepted_point_use_delta.csv','supplemental_accepted_point_use_delta_v2.csv','current_carrier_accepted_point_use_delta.csv','dated_subcounty_accepted_point_use_delta.csv','sosnovka_classifier_accepted_point_use_delta.csv']:existing.update(pd.read_csv(O/n).target_source_record_id)
a=pd.read_csv(O/'assignment.csv').fillna('');old=f[f.census_year.isin([2002,2010])].copy();old['meta_sheet']=old.source_record_id.map(m.source_sheet);old['meta_row']=pd.to_numeric(old.source_record_id.map(m.source_row),errors='coerce');cur=f[f.census_year==2021].copy();cur['raw_mun_lower']=cur.source_record_id.map(lambda sid:str(rf.iloc[int(m.loc[sid,'source_row'])-1].mun_lower) if sid in m.index and str(m.loc[sid,'source_row']).replace('.','').isdigit() else '');cur['raw_mun_upper']=cur.source_record_id.map(lambda sid:str(rf.iloc[int(m.loc[sid,'source_row'])-1].mun_upper) if sid in m.index and str(m.loc[sid,'source_row']).replace('.','').isdigit() else '');pub=cur.set_index('source_record_id').to_dict('index');bindingcache={};rows=[];reviews=[];proof=[]
def binding(sid):
 if sid in bindingcache:return bindingcache[sid]
 out={'source_record_id':sid,'status':'no_two_sided_same_publisher_subcounty_bind'}
 if sid not in m.index or not str(m.loc[sid,'source_row']).replace('.','').isdigit():bindingcache[sid]=out;return out
 v=m.loc[sid];rn=int(v.source_row);near=old[(old.source_file==b.loc[sid,'source_file'])&(old.meta_sheet==v.source_sheet)&(old.meta_row.between(rn-20,rn+20))&(old.source_record_id!=sid)];aa=[]
 for z in near.itertuples():
  ids=groups[z.root]
  if not gvalid[z.root] or any(i not in p for i in ids) or len({b.loc[i,'name_norm'] for i in ids})!=1:continue
  ci=next(i for i in ids if int(b.loc[i,'census_year'])==2021)
  if ci not in pub or not pub[ci]['raw_mun_lower']:continue
  if max(distance_km((float(p[i]['latitude']),float(p[i]['longitude'])),(float(p[ci]['latitude']),float(p[ci]['longitude']))) for i in ids)>5:continue
  if not check(z.source_record_id)['literal_label_population_passed'] or not check(ci)['literal_label_population_passed']:continue
  aa.append({'source_record_id':z.source_record_id,'source_row':int(z.meta_row),'name':z.name_norm,'current_source_record_id':ci,'current_native_mun_lower':pub[ci]['raw_mun_lower'],'current_native_mun_upper':pub[ci]['raw_mun_upper']})
 lo=sorted([x for x in aa if x['source_row']<rn],key=lambda x:x['source_row'],reverse=True);hi=sorted([x for x in aa if x['source_row']>rn],key=lambda x:x['source_row'])
 if lo and hi and lo[0]['name']!=hi[0]['name'] and lo[0]['current_native_mun_lower']==hi[0]['current_native_mun_lower'] and lo[0]['current_native_mun_upper']==hi[0]['current_native_mun_upper']:out.update(status='two_sided_distinct_named_native_full3_anchors_same_actual_current_publisher_subcounty',native_mun_lower=lo[0]['current_native_mun_lower'],native_mun_upper=lo[0]['current_native_mun_upper'],lower_anchor=lo[0],upper_anchor=hi[0])
 bindingcache[sid]=out;return out
for z in a[a.has_ownpoint==False].to_dict('records'):
 sid=z['source_record_id']
 if sid in existing or sid not in oldw:continue
 if not oldw[sid]['literal_label_population_passed']:continue
 ctx=binding(sid);why=[]
 if ctx['status'].startswith('no_'):continue
 pool=cur[(cur.region_norm==z['region_norm'])&(cur.name_norm==z['name_norm'])&(cur.type_norm==z['type_norm'])&(cur.raw_mun_lower==ctx['native_mun_lower'])&(cur.raw_mun_upper==ctx['native_mun_upper'])];target_ids=pool.source_record_id.tolist();dsid=target_ids[0] if len(target_ids)==1 else ''
 if len(target_ids)!=1:why.append('current exact own name/type/subcounty not unique')
 if dsid and dsid not in p:why.append('current own fullcoded leaf has no independently accepted ownpoint')
 source_r=old[(old.census_year==z['census_year'])&(old.region_norm==z['region_norm'])&(old.name_norm==z['name_norm'])&(old.type_norm==z['type_norm'])];rivals=[]
 for rr in source_r.itertuples():
  if rr.source_record_id==sid:continue
  cc=binding(rr.source_record_id)
  if cc.get('native_mun_lower')==ctx['native_mun_lower'] and cc.get('native_mun_upper')==ctx['native_mun_upper']:rivals.append(rr.source_record_id)
  elif cc['status'].startswith('no_') and (not county_key(rr.district_raw) or county_key(rr.district_raw)==county_key(z['district_raw'])):rivals.append(rr.source_record_id)
 if rivals:why.append('same sourceyear typed namesake in matching/unknown ownsubcounty')
 if dsid and not check(dsid)['literal_label_population_passed']:why.append('reopened original2021 coded ownleaf name/count fails')
 reviews.append({'source_record_id':sid,'name':z['settlement_name'],'binding_json':json.dumps(ctx,ensure_ascii=False),'current_owncoded_candidates_json':json.dumps(target_ids),'rivals_json':json.dumps(rivals),'disposition':'hold:'+';'.join(why) if why else 'accepted_point_only'})
 if why:continue
 cp=p[dsid];cw=check(dsid);nw=oldw[sid];rawcurrent=rf.iloc[int(m.loc[dsid,'source_row'])-1];assert str(rawcurrent.oktmo)==str(b.loc[dsid,'oktmo']);row={k:cp[k] for k in ['latitude','longitude','point_origin_file','point_origin_sha256','point_origin_locator','point_origin_kind']};row.update(target_source_record_id=sid,coordinate_source_record_id=dsid,coordinate_admission_status='reviewed_extension_rule_accepted',decision_status='checked_rule_accepted',admission_allowed=True,own_locality_point=True,recipient_point_assigned_to_child=False,source_sha256=nw['source_sha256'],source_locator=str(nw['source_sheet'])+':'+str(nw['source_row']),current_ownpoint_carrier_source_record_id=dsid,donor_native_own_OKTMO=b.loc[dsid,'oktmo'],admission_rule='Reopened historical native ownleaf name/type/count; two distinct actual full3 owncoded named anchors strictly flank physical native source row within20, and both actual primary2021 publisher upper/lower ownsource hierarchy agrees. Sourceyear all typed namesake rivals independently screened through same hierarchy; unique native2021 exact name/type and actual publisher subcounty ownleaf/fullcode; independently accepted current ownpoint reused explicitly by continuity. No ordinary identity edge or boundary/censusday geometry claim.',point_temporal_interpretation='Modern physical ownNP representative reused historically by explicit continuity inference; exact censusday geometry and population boundary equivalence unknown.',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,native_population_quality_preserved=True,source_context_witness_file=str(O/'subcounty_anchor_point_witnesses.csv.gz'));rows.append(row);proof.append({'source_record_id':sid,'native_source_witness_json':json.dumps(nw,ensure_ascii=False),'source_scope_binding_json':json.dumps(ctx,ensure_ascii=False),'current_native_original_row_json':json.dumps(rawcurrent.to_dict(),ensure_ascii=False,default=str),'independently_source_reopened_anchor_source_witnesses_json':json.dumps([check(v) for x in [ctx['lower_anchor'],ctx['upper_anchor']] for v in [x['source_record_id'],x['current_source_record_id']]],ensure_ascii=False),'native_typed_rivals_json':json.dumps(rivals)})
for n,data,cols in [('subcounty_anchor_accepted_point_use_delta.csv',rows,['target_source_record_id','latitude','longitude','coordinate_admission_status']),('subcounty_anchor_point_witnesses.csv.gz',proof,['source_record_id']),('subcounty_anchor_point_reviews.csv.gz',reviews,['source_record_id']),('subcounty_anchor_all_bound_source_rivals.csv.gz',list(bindingcache.values()),['source_record_id'])]:pd.DataFrame(data,columns=None if data else cols).to_csv(O/n,index=False,compression={'method':'gzip','mtime':0} if n.endswith('.gz') else None)
(O/'subcounty_anchor_point_manifest.json').write_text(json.dumps({'status':'accepted_ownpoint_only_source_hierarchy_packet','points':len(rows),'identity_edges':0,'sourcecounts_quality_modified':False,'input_pins':pins,'output_pins':{str(O/n):sha(O/n) for n in ['subcounty_anchor_accepted_point_use_delta.csv','subcounty_anchor_point_witnesses.csv.gz','subcounty_anchor_point_reviews.csv.gz','subcounty_anchor_all_bound_source_rivals.csv.gz']}},ensure_ascii=False,indent=2));print('points',len(rows),[(b.loc[x['target_source_record_id'],'settlement_name'],b.loc[x['target_source_record_id'],'region_norm']) for x in rows])
