from pathlib import Path
import pandas as pd,json,sys,hashlib,re,openpyxl
R=Path('/workspace/russian-settlements-research');O=Path(__file__).parent;sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from stage_rural_native_okato_points_20261004 import raw_dbf_rows
from current_chain_state_20261007 import distance_km,normalize
from apply_unique_county_name_bridge_20261007 import county_key
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
SQL=Path('/workspace/settlements-raw/data/raw/historical_classifiers/okato_142_2009/dump-142_2009.sql');DBF=Path('/workspace/settlements-raw/data/raw/historical_geography/geokladr_okato_2011/okato.dbf');P=Path('/workspace/settlements-work/sources/geokladr_raw_verification/geokladr_okato_2011_raw_parsed.parquet');K=Path('/workspace/settlements-work/sources/r2-missing/kaliningrad_tom1.xlsx');N=R/'research_rebuild/evidence/over500_north_supplemental_native_20261009/recovered_direct_native_witnesses.csv';PS=Path('/dev/shm/settlements-stage71-20261009/applied_point_snapshot.parquet');sid='KAL2010:TOM1:S4:R0391';w=pd.read_csv(N).fillna('').set_index('source_record_id').to_dict('index')[sid];assert w['literal_label_population_passed'];assert 'Храбровский' in w['primary_native_parent_header'];assert float(w['raw_population_value'])==527
sq=[];codes={'27000000','27209000','27209828000','27209828012'}
for rn,line in enumerate(SQL.open(),1):
 if line.split('\t')[0] in codes:sq.append({'line1based':rn,'raw':line.rstrip('\n'),'cells':line.rstrip('\n').split('\t')})
assert len(sq)==4;sr={x['cells'][0]:x for x in sq};assert sr['27209828012']['cells'][2]=='Сосновка' and sr['27209828012']['cells'][3]=='поселок сельского типа' and sr['27209828012']['cells'][-1]=='t';assert 'Храбровского сельсовета' in sr['27209828000']['raw'];assert 'Гурьевский район' in sr['27209000']['raw'];assert 'Калининградская область' in sr['27000000']['raw']
d=pd.read_parquet(P).fillna('');candidate=d[d.historical_okato=='27209828012'];assert len(candidate)==1;raw=list(raw_dbf_rows(DBF,candidate).values())[0];assert raw['code']=='27209828012' and normalize(raw['name_raw'])=='п сосновка' and raw['type_raw']=='п';assert raw['deleted_marker']==' ';coord=(float(raw['lat_raw']),float(raw['lon_raw']));assert 54<coord[0]<55 and 20<coord[1]<21
# Full source hierarchy confirms the historical own name/type unique under this named parish.
sh=openpyxl.load_workbook(K,data_only=True,read_only=True)['4'];county='';parent='';entries=[]
for rn,vals in enumerate(sh.iter_rows(values_only=True),1):
 ss=[str(x).strip() for x in vals if isinstance(x,str) and x.strip()]
 for x in ss:
  if 'район' in normalize(x) or 'городской округ' in normalize(x):
   county=county_key(x).removeprefix('сельские ');county=re.sub('ского$','ский',county);parent=''
  if 'сельский округ' in normalize(x):parent=x
  if normalize(x)=='поселок сосновка':entries.append({'source_row1based':rn,'name_raw':x,'county':county,'parent':parent})
target=[x for x in entries if x['county']=='гурьевский' and 'Храбров' in x['parent']];assert len(target)==1 and target[0]['source_row1based']==391,target
modernsid='2021:data_allsettlements_anon_156_v20251217.parquet:parquet:25957';mp=pd.read_parquet(PS,columns=['target_source_record_id','latitude','longitude','point_origin_file','point_origin_locator']);modern=mp[mp.target_source_record_id==modernsid].iloc[0];dist=distance_km(coord,(float(modern.latitude),float(modern.longitude)));assert dist<1
assert sha(DBF)==candidate.iloc[0].source_sha256;assert sha(K)==w['source_sha256'];rule='Own original2010 poselok Sosnovka527 under explicit Khрабровский сельский округ/Guryev county; full physical primary source hierarchy excludes samecounty Lugovskoye namesake. Independently reopened2009 official classifier own NP leaf27209828012, name/type, namedKhрабровский parent and county/region; exact own code/name/type reopened in2011GeoKLADR DBF own-point record, and own coordinate agrees within1km with separately accepted current ownpoint carrier. Native census code not printed/unknown, not backfilled. GeoKLADR identifier binding and coordinate correctness checked separately. Representative2011point reused for2010 by continuity inference, no censusdaymeasurement/boundary equivalence or ordinary edge.'
row={'target_source_record_id':sid,'latitude':coord[0],'longitude':coord[1],'coordinate_admission_status':'reviewed_extension_rule_accepted','decision_status':'checked_rule_accepted','admission_allowed':True,'own_locality_point':True,'recipient_point_assigned_to_child':False,'coordinate_source_record_id':sid,'source_sha256':w['source_sha256'],'source_locator':w['source_locator'],'point_origin_file':str(DBF),'point_origin_sha256':sha(DBF),'point_origin_locator':f"DBF record1based={raw['record_no']};byte_offset0based={raw['byte_offset']};ownhistoricalOKATO27209828012",'point_origin_kind':'independently_name_type_county_subcounty_bound_own_historical_GeoKLADR_point','admission_rule':rule,'point_temporal_interpretation':'2011representative own physical locality point reused in2010 by explicit continuity inference; no exact censusday measured coordinates or population boundary equivalence.','historical_classifier_own_code':'27209828012','historical_census_native_code_binding_asserted':False,'native_census_code_unknown_not_backfilled':True,'independent_current_ownpoint_target':modernsid,'independent_current_ownpoint_distance_km':dist,'historical_census_coordinate_asserted':False,'population_boundary_comparability_asserted':False}
pd.DataFrame([row]).to_csv(O/'sosnovka_classifier_accepted_point_use_delta.csv',index=False);proof={'native2010':w,'official2009_independent_classifier_rows':sq,'raw2011_geo_provider_replay':raw,'all_primary2010_Sosnovka_own_parish_rivals':entries,'independent_current_point':modern.to_dict(),'distance_km':dist};(O/'sosnovka_classifier_point_witness.json').write_text(json.dumps(proof,ensure_ascii=False,indent=2));receipt={'status':'accepted_own_historical_point_only','points':1,'identity_edges':0,'source_native_codes_not_backfilled':True,'input_pins':{str(q):sha(q) for q in [SQL,DBF,P,K,N,PS]},'output_pins':{str(q):sha(q) for q in [O/'sosnovka_classifier_accepted_point_use_delta.csv',O/'sosnovka_classifier_point_witness.json']}};(O/'sosnovka_classifier_point_manifest.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2));print('accepted',coord,'independentdistance',dist)
