from pathlib import Path
import pandas as pd,json,gzip,re,hashlib,sys
R=Path('/workspace/russian-settlements-research');O=Path(__file__).parent;A=R/'research_rebuild/evidence/over500_north_wiki_sources_20261009';sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from apply_unique_county_name_bridge_20261007 import county_key
from current_chain_state_20261007 import normalize
sha=lambda q:hashlib.sha256(Path(q).read_bytes()).hexdigest()
wfile=R/'research_rebuild/evidence/over500_north_supplemental_native_20261009/recovered_direct_native_witnesses.csv';w=pd.read_csv(wfile).fillna('').set_index('source_record_id').to_dict('index');cf=A/'additional_kaliningrad_v5_article_candidates.csv.gz';cand=pd.read_csv(cf).fillna('');mapping={'Ушаково (Новомосковское сельское поселение)':'KAL2010:TOM1:S4:R0355','Садовое (Илюшинское сельское поселение)':'KAL2010:TOM1:S4:R0704','Садовое (Красноярское сельское поселение)':'KAL2010:TOM1:S4:R0815'};books={};pins={str(x):sha(x) for x in [wfile,cf]};rows=[];proof=[]
def fld(txt,key):
 m=re.search(r'\|\s*'+key+r'\s*=\s*([^\n|]+)',txt,re.I);return (m.group(1) if m else '').strip()
for z in cand.to_dict('records'):
 if z['article_title'] not in mapping:continue
 sid=mapping[z['article_title']];nw=w[sid];q=Path(z['capture']);pins[str(q)]=sha(q);bl=json.loads(gzip.decompress(q.read_bytes()));pages=bl.get('payload',bl).get('query',{}).get('pages',[]);pages=list(pages.values()) if isinstance(pages,dict) else pages;pp=next(x for x in pages if x['title']==z['article_title']);rev=pp['revisions'][0];txt=rev.get('slots',{}).get('main',{}).get('content',rev.get('slots',{}).get('main',{}).get('*',rev.get('*','')));region=fld(txt,'регион').replace('[[','').replace(']]','');countylit=fld(txt,'район').replace('[[','').replace(']]','');ck=county_key(nw['actual_printed_county']);articleck=county_key(re.sub(r'\([^)]*\)','',countylit));assert 'калининград' in normalize(region),region;assert ck==articleck,(ck,articleck);assert normalize(fld(txt,'статус'))=='поселок';assert normalize(fld(txt,'русское название') or z['article_title'].split(' (')[0])==nw['native_name'];assert nw['literal_label_population_passed'];assert float(nw['native_population'])==float(nw['raw_population_value']);par=nw['primary_native_parent_header'];stem=normalize(par).split()[0];stem=re.sub(r'(?:ий|ое|ая|ого)$','',stem);stem=stem.replace('ильюшин','илюшин');hist=[l for l in txt.splitlines() if '2008' in l and ('2014' in l or '2018' in l) and stem in normalize(l).replace('ильюшин','илюшин')];
 if not hist and stem in normalize(fld(txt,'поселение')):hist=['Explicit own infobox subcounty '+fld(txt,'поселение')+'; matching source native parent. Membership date not asserted.']
 assert len(hist)==1,(z['article_title'],stem,hist)
 nativepath=Path(nw['source_file']);assert sha(nativepath)==nw['source_sha256'];pins[str(nativepath)]=nw['source_sha256'];rule='Original own2010 native named poselok leaf/type/count and explicit county/subcounty hierarchy reopened; own settlement article name/type/region/county plus explicit dated2008–2014/2018 membership or own infobox membership in independently matching source subcounty disambiguates samecounty same-name rivals. Native labels/counts/quality unchanged; independent own settlement coordinate used retrospectively; no ordinary identity edge, censusday coordinate measurement or population boundary equivalence.'
 rows.append({'target_source_record_id':sid,'latitude':z['latitude'],'longitude':z['longitude'],'coordinate_admission_status':'reviewed_extension_rule_accepted','decision_status':'checked_rule_accepted','admission_allowed':True,'own_locality_point':True,'recipient_point_assigned_to_child':False,'coordinate_source_record_id':sid,'source_sha256':nw['source_sha256'],'source_locator':nw['source_locator'],'point_origin_file':z['capture'],'point_origin_sha256':pins[str(q)],'point_origin_locator':f"pageid={z['pageid']};revid={z['revid']};own primary settlement page coordinate",'point_origin_kind':'own_locality_Wikipedia_coordinate_with_dated_own_subcounty_binding','point_source_qid':z['qid'],'point_source_revision':z['revid'],'admission_rule':rule,'point_temporal_interpretation':'Modern own physical locality representative reused by explicit retrospective continuity inference; no censusday measured geometry or population boundary equivalence.','historical_census_coordinate_asserted':False,'population_boundary_comparability_asserted':False,'native_population_quality_preserved':True,'source_context_witness_file':str(wfile),'own2010_native_subcounty':par,'dated_own_article_subcounty_witness':hist[0]})
 proof.append({'source_record_id':sid,'own_article_title':z['article_title'],'original_native_witness_json':json.dumps(nw,ensure_ascii=False),'dated_own_source_subcounty_witness':hist[0],'own_coordinate_witness_json':json.dumps(z,ensure_ascii=False),'samecounty_namesake_alternative':'other native primary parish; separately named retained no geometry shared'})
pd.DataFrame(rows).to_csv(O/'dated_subcounty_accepted_point_use_delta.csv',index=False);pd.DataFrame(proof).to_csv(O/'dated_subcounty_point_witnesses.csv.gz',index=False,compression={'method':'gzip','mtime':0});manifest={'status':'accepted_direct_own_NP_points_with_source_subcounty_disambiguation_2_dated_1_explicit_undated','points':len(rows),'ordinary_identity_edges':0,'counts_quality_boundaries_modified':False,'input_pins':pins,'output_pins':{str(q):sha(q) for q in [O/'dated_subcounty_accepted_point_use_delta.csv',O/'dated_subcounty_point_witnesses.csv.gz']}};(O/'dated_subcounty_point_manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2));print('admitted',len(rows))
