from pathlib import Path
import pandas as pd,json,hashlib,sys
R=Path('/workspace/russian-settlements-research');O=Path(__file__).parent;S=Path('/dev/shm/settlements-stage71-20261009');sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from current_chain_state_20261007 import distance_km
from apply_unique_county_name_bridge_20261007 import county_key
sha=lambda q:hashlib.sha256(Path(q).read_bytes()).hexdigest()
f=pd.read_parquet(S/'applied_state_observations.parquet').fillna('');b=f.set_index('source_record_id');p=pd.read_parquet(S/'applied_point_snapshot.parquet',columns=['target_source_record_id','latitude','longitude']).drop_duplicates('target_source_record_id').set_index('target_source_record_id').to_dict('index');pointsfile=O/'current_carrier_accepted_point_use_delta.csv';points=pd.read_csv(pointsfile).fillna('');wfile=R/'research_rebuild/evidence/over500_north_supplemental_native_20261009/recovered_direct_native_witnesses.csv';w=pd.read_csv(wfile).fillna('').set_index('source_record_id').to_dict('index');re=pd.read_csv(O/'current_carrier_point_review.csv.gz').fillna('').set_index('target_source_record_id').to_dict('index');groups={root:g.source_record_id.tolist() for root,g in f.groupby('root')};edges=[];series=[];wits=[]
for pp in points.to_dict('records'):
 sid=pp['target_source_record_id'];cur=pp['current_ownpoint_carrier_source_record_id'];ids=list(dict.fromkeys(groups[b.loc[sid,'root']]+groups[b.loc[cur,'root']]));years=[int(b.loc[i,'census_year']) for i in ids];assert len(ids)==len(set(years));assert int(b.loc[sid,'census_year'])==2010;assert w[sid]['literal_label_population_passed'];assert re[sid]['disposition']=='accepted_current_ownpoint_continuity_only';assert len(json.loads(re[sid]['typed_current_namesake_ids_json']))==1
 typ=w[sid]['raw_source_type'].replace('ё','е');assert typ==b.loc[cur,'type_norm'];assert county_key(w[sid]['actual_printed_county'])==county_key(b.loc[cur,'district_raw']);assert all(b.loc[i,'name_norm']==b.loc[cur,'name_norm'] for i in ids);assert all(bool(b.loc[i,'is_additive_settlement_record']) for i in ids)
 dists={i:distance_km((float(pp['latitude']),float(pp['longitude'])),(float(p[i]['latitude']),float(p[i]['longitude']))) for i in ids if i in p};assert max(dists.values(),default=0)<=5
 edges.append({'from_source_record_id':sid,'to_source_record_id':cur,'relation':'same_place','decision_status':'checked_rule_accepted','admission_rule':'Direct original2010 own native leaf/type/count and explicit county hierarchy reopened; full official2010 typed namesake screen and unique current literal own native name/raw type/county with independently source-admitted own point and native fullcode reopened. Actual raw2010 poselok role, including Sorovo/Samkovo where imported selectedtype erroneously says selo, matches own2002/current physical locality. Import type discrepancy preserved as witness, no table edit or legal type change. No repeated censusyear or existing ownpoint conflict >5km; censusday measured geometry/population boundary comparability not asserted.','source_context_witness_file':str(wfile),'raw_source_type':w[sid]['raw_source_type'],'selected_import_type':b.loc[sid,'settlement_type'],'selected_import_type_preserved':True,'source_count_quality_preserved':True,'boundary_comparability_asserted':False,'historical_census_coordinate_asserted':False})
 series.append({'scope_id':'north_source_direct_'+b.loc[cur,'name_norm'],'component_source_ids_json':json.dumps(ids),'available_connected_years':','.join(map(str,sorted(years))),'missing_census_year_status':'none' if len(years)==3 else '2002_UNKNOWN_NOT_ZERO_NOT_ADJUDICATED','all_available_native_source_records_found':False,'three_census_complete':len(years)==3,'decision_status':'checked_rule_accepted','quality_axis':'ordinary_full3' if len(years)==3 else 'accepted_connected_incomplete_available_year_series','source_counts_changed':False})
 wits.append({'source_record_id':sid,'raw_source_witness_json':json.dumps(w[sid],ensure_ascii=False),'native2021_donor_source_record_id':cur,'native2021_original_owncode_name_count_json':re[sid]['donor_native_primary_row_json'],'existing_component_source_ids_json':json.dumps(ids),'current_carrier_active_point_distance_json':json.dumps(dists),'raw_vs_imported_type_interpretation':pp.get('type_discrepancy_retained','')})
for n,rows in [('supplemental_six_accepted_identity_edges.csv',edges),('supplemental_six_connected_series.csv',series),('supplemental_six_identity_source_witnesses.csv.gz',wits)]:pd.DataFrame(rows).to_csv(O/n,index=False,compression={'method':'gzip','mtime':0} if n.endswith('.gz') else None)
inputs=[pointsfile,wfile,O/'current_carrier_point_review.csv.gz',O/'current_carrier_point_manifest.json',S/'applied_state_observations.parquet',S/'applied_point_snapshot.parquet',S/'applied_component_snapshot.csv.gz'];receipt={'status':'accepted_direct_source_bound_identity_packet_for_root_replay','edges':len(edges),'ordinary_full3_source_components':sum(x['three_census_complete'] for x in series),'incomplete_connected_series':sum(not x['three_census_complete'] for x in series),'sourcecounts_quality_importtypes_modified':False,'source_discrepancies_explicit_preserved':True,'input_pins':{str(q):sha(q) for q in inputs},'output_pins':{str(O/n):sha(O/n) for n in ['supplemental_six_accepted_identity_edges.csv','supplemental_six_connected_series.csv','supplemental_six_identity_source_witnesses.csv.gz']}};(O/'supplemental_six_identity_manifest.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2));print(receipt['edges'],receipt['ordinary_full3_source_components'],receipt['incomplete_connected_series'])
