from pathlib import Path
import json,gzip,pandas as pd,hashlib,xlrd,pyarrow.parquet as pq
D=Path(__file__).parent;E=D.parent.parent;sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
ef=E/'moscow_large_residual_actionable_20261008/municipal_entities.json.gz';pf=E/'moscow_large_residual_actionable_20261008/municipal_pages.json.gz';ents=json.load(gzip.open(ef,'rt'))['entities'];pages={p.get('pageprops',{}).get('wikibase_item'):p for p in json.load(gzip.open(pf,'rt'))['query']['pages'].values()}
p02=Path('/workspace/settlements-raw/data/raw/2002_official_tom1/1_TOM_01_04.xls');s=xlrd.open_workbook(str(p02)).sheet_by_index(0);p10=Path('/workspace/settlements-raw/data/raw/2010/010_711691e352_2._20Kostrom_Kur_Lip_Moscow_MoscObl_Orlov_2010.xls');s10=xlrd.open_workbook(str(p10)).sheet_by_name('Data Sheet');sel=Path('/workspace/settlements-delivery/continuation-consolidated-20261003/selected_observations.parquet');m=pq.read_table(sel,columns=['source_record_id','population','population_value_quality']).to_pandas().set_index('source_record_id');obs=[];roster=[];proof=[]
for name,q,n,rr in [('Киевский','Q4373601',1208,list(range(11246,11251))),('Кокошкино','Q4373603',1209,list(range(11251,11254)))]:
 row=s.row_values(n-1);sid='2002:1_TOM_01_04.xls:0:'+str(n);native=m.loc[sid];assert row[1]==native.population
 obs.append(dict(context_key=q,census_year=2002,observation_id=sid,authentic_source_grain='proper_pgt_individual_NP_observation_NOT_municipality_NOT_complete_pgtjurisdiction',population=native.population,population_quality=native.population_value_quality,population_source_file=str(p02),population_source_sha256=sha(p02),population_source_locator='0!row_1based='+str(n),own_physical_PGT_point_source='',latitude='',longitude='',source_values_modified=False,own2002_municipal_observation_asserted=False,event_path_credit_admitted=False))
 proof.append(dict(context_key=q,census_year=2002,raw_locator='0!row_1based='+str(n),raw_original_row_json=json.dumps(row,ensure_ascii=False)))
 for z in ents[q]['claims']['P1082']:
  for dt in z.get('qualifiers',{}).get('P585',[]):
   year=int(dt.get('datavalue',{}).get('value',{}).get('time','+0000')[1:5])
   if year in [2010,2021]:
    assert z.get('references');point=ents[q]['claims']['P625'][0]['mainsnak']['datavalue']['value'];obs.append(dict(context_key=q,census_year=year,observation_id=q+':municipal:'+str(year),authentic_source_grain='whole_sourceyear_municipal_territory_NOT_properPGT',population=float(z['mainsnak']['datavalue']['value']['amount']),population_quality='secondary_explicit_census_referenced_whole_municipal_total',population_source_file=str(ef),population_source_sha256=sha(ef),population_source_locator=z['id'],own_physical_PGT_point_source='',latitude=point['latitude'],longitude=point['longitude'],point_role='municipal_representative_scope_only_NOT_PGT_point',population_references_json=json.dumps(z['references'],ensure_ascii=False),source_values_modified=False,own2002_municipal_observation_asserted=False,event_path_credit_admitted=False))
 for k in rr:
  raw=s10.row_values(k-1);sid10='2010:'+p10.name+':Data Sheet:'+str(k);selected=sid10 in m.index
  assert selected or raw[4]==''
  roster.append(dict(context_key=q,census_year=2010,source_record_id=sid10 if selected else '',raw_row_1based=k,raw_label=raw[3],native_population=m.loc[sid10].population if selected else '',native_quality=m.loc[sid10].population_value_quality if selected else 'raw_count_blank_unknown_not_zero',raw_population=raw[4],raw_original_row_json=json.dumps(raw[:6],ensure_ascii=False),source_values_modified=False,individual_point_assigned=False))
 t=pages[q]['revisions'][0]['slots']['main']['*'];lines=[line for line in t.splitlines() if any(w in line for w in ['2005','Дата образования МО','включило'])];(D/(q+'_cached_formation_excerpt.txt')).write_text('\n'.join(lines)+'\n')
pd.DataFrame(obs).to_csv(D/'authentic_urban_predecessor_and_municipal_observations.csv',index=False);pd.DataFrame(roster).to_csv(D/'complete2010_raw_municipal_rosters.csv',index=False);pd.DataFrame(proof).to_csv(D/'primary2002_properPGT_raw_witness.csv',index=False)
receipt=dict(status='held_optional_urban_predecessor_formation_context_no_ownphysicalPGTpoint',own2002_municipal_observation_created=False,complete3ownmunicipal_scope_asserted=False,synthetic9907_total_created=False,physical_PGT_point_replaced_by_municipal_P625=False,ordinary_sameplace_edges=0,admitted_native_population_gain=0,source_manifest={str(p):sha(p) for p in [ef,pf,p02,p10,sel]},outputs={p.name:sha(p) for p in D.glob('*.csv')});(D/'context_hold_receipt.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n');print('Authentic contexts preserved; ownPGTpoint hold')
