from pathlib import Path
import pandas as pd,json,hashlib,xlrd,shutil
E=Path('/workspace/russian-settlements-research/research_rebuild/evidence');O=E/'old_native_from_existing_secondary_binding_20261007';A=E/'existing_event_scope_application_20261007';d=pd.read_csv(O/'candidate_native_old_bindings.csv',keep_default_na=False);out=[]
for r in d.to_dict('records'):
 p=Path('/workspace/settlements-raw')/r['old_source_file'];parts=r['old_source_record_id'].split(':');sh=xlrd.open_workbook(str(p)).sheet_by_name(parts[-2]);n=int(parts[-1]);r.update(raw_old_source_file=str(p),raw_old_source_sha256=hashlib.sha256(p.read_bytes()).hexdigest(),raw_old_source_locator='sheet='+sh.name+';row_1based='+str(n),raw_old_row_json=json.dumps(sh.row_values(n-1),ensure_ascii=False),proof_tier='direct_printed_historical_county');out.append(r)
d=pd.DataFrame(out);d.to_csv(O/'candidate_native_old_bindings.csv',index=False);a=pd.read_csv(O/'flanking_accepted_anchor_binding_candidates.csv',keep_default_na=False);a['proof_tier']='inferred_admin_context_two_accepted_flanking_anchors';z=pd.concat([d,a],ignore_index=True);pt=pd.read_csv(A/'point_provenance.csv',keep_default_na=False).set_index('current_source_record_id')
for k in ['latitude','longitude','point_origin_file','point_origin_sha256','point_origin_locator']:z['accepted_current_own_'+k]=z.current_source_record_id.map(pt[k])
z['old_native_population_quality']='selected native source value preserved; primary2002 and secondary2010 source classifications retained at application';z['source_zero_status']='source_value_zero_does_not_assert_true_empty_locality';z.to_csv(O/'combined_candidate_native_old_bindings.csv',index=False)
u=z[['qid','year','old_source_record_id','old_native_population','proof_tier']].drop_duplicates('old_source_record_id');u.to_csv(O/'unique_native_source_id_net_potential.csv',index=False)
r=json.loads((O/'scan_receipt.json').read_text());r.update(status='candidate_only_no_admission',direct_printed_county_candidates=2,anchor_inferred_candidates=5,total_candidates=len(z),unique_native_source_id_net_by_year={int(y):int(g.old_native_population.astype(float).sum()) for y,g in u.groupby('year')},all_raw_native_candidate_rows_reopened=True,raw_secondary_proof_reuse='Own398 censusclaims GUID/hash validated by existing_event_scope application; this task reused those proofs without repeating cohortaudit.',historical_county_proof_quality='2 nativeprintedcounty exact;5 explicitly inferred from acceptedtwo flanking rawsource anchors; none invented directcountylabels',all_old_existing_points_agree_with_own_current_within_5km=True,population_values_modified=False,loader_report_or_accepted_files_modified=False,remaining_scope_held_series_not_reopened='110 not qualifying final398 full3 cohort remain outside bounded candidatepool',input_hashes={str(p):hashlib.sha256(p.read_bytes()).hexdigest() for p in [A/'application_receipt.json',A/'point_provenance.csv']},output_hashes={p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in O.glob('*.csv')});(O/'candidate_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n')
(O/'README.md').write_text('''# Native historical source binding from existing secondary censusproofs\n\nCandidate only; no acceptededge/point/loader/report edits. All310,386 selectedhistorical and155,414 selectedcurrent competitors scanned stage21. The398 admitted ownphysicalseries supplied actualcensus secondaryclaims; no duplicatecohort audit.\n\nTwo2002 candidates178population have exactprinted ownNP/censuscount/name/type/region plus matchingnativeprintedcounty/currentcounty and uniquephysicalcompetitors. Originalxls rows reopened and hashed: Буляк23 and Новоселовка155.\n\nFive2010 candidates1,136population require review of inferred administrativecontext. Native2010ethnic XLS source does not printcounty. Both nearest flanking acceptedsourcecomponents independently point to sameowncurrentcounty within25rawrows, and each candidate has uniqueexact owncensuscount/name/type/region. Ownraw row and bothanchorraw rows reopened; oldexistingpoint, whenpresent, agrees within5km. These are labeled anchor-inferred, not directhistoricalcounty observations.\n\nNo approximatecount candidate passed; nativevalues remain unchanged. Zero sourcevalue in Марково preserves its selectedsourcequality and does not assert a trueemptyplace. Holdfile retains439 missed/displaced/conflictingcounty/count cases. No credit admitted; proposed selectedID net178(2002),1,136(2010) must be reviewed and recomputed through currentexclusive union.\n\nReproduce: scan.py, reopen.py, anchors.py, finalize.py (requires sameworkspace paths).\n''');print('totalbytes',sum(p.stat().st_size for p in O.iterdir() if p.is_file()))
