from pathlib import Path
import pandas as pd,json,gzip,hashlib,xlrd
O=Path(__file__).parent;D=pd.read_pickle('/dev/shm/over500-20261009/east_enriched.pkl');P=pd.read_parquet('/dev/shm/over500-20261009/points_compact.parquet').set_index('target_source_record_id');by=D.set_index('source_record_id');sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();W=[];points=[];edges=[];raw=[]
for targetord,left,right,oldord,county in [(443,442,444,772,'хорольский'),(497,496,498,853,'чугуевский')]:
 sid=f'2010:009_81f8a0e73c_17._20ДВ_ФО_2010.xls:ДВ:{targetord}';oid=f'2002:079_983a1a85f7_Primor_krai_1.xls:Sheet1:{oldord}';t=by.loc[sid];d=by.loc[oid];assert t.settlement_name==d.settlement_name and t.type_norm==d.type_norm=='село' and d.county==county;anchors=[]
 for k in [left,right]:
  aid=f'2010:009_81f8a0e73c_17._20ДВ_ФО_2010.xls:ДВ:{k}';a=by.loc[aid];peer=D[D.root.eq(a.root)&D.census_year.eq(2002)];assert len(peer)==1 and peer.iloc[0].county==county;anchors.append(dict(source2010=aid,native2002_accepted_peer=peer.iloc[0].fillna('').to_dict()))
 lo,hi=[int(a['native2002_accepted_peer']['source_record_id'].rsplit(':',1)[1])for a in anchors];assert lo<oldord<hi and hi-lo<=4;within=D[D.census_year.eq(2002)&D.region_norm.eq(t.region_norm)&D.ord.gt(lo)&D.ord.lt(hi)&D.name_norm.eq(t.name_norm)&D.type_norm.eq(t.type_norm)];assert len(within)==1
 q=P.loc[oid];assert sha(q.point_origin_file)==q.point_origin_sha256;wid=len(W);rule='Narrow two-sided existing accepted native source-order anchors: exact own name/type is unique between independently accepted old2002neighbors in same actualcounty; raw2010 owncountycell blank despite importeddistrict_rawХасанский. Imported field preserved and explicitly diagnosed, not treated as published contradiction. Direct accepted ownpoint of exactoldleaf transferred; all native aliases/homonyms remain separate.'
 for record in [t,d]:
  f=Path('/workspace/settlements-raw')/record.source_file;b=xlrd.open_workbook(str(f));sh=b.sheet_by_name(record.name.rsplit(':',2)[1]);rn=int(record.name.rsplit(':',1)[1])-1;cells=sh.row_values(rn);assert record.settlement_name in str(cells)
  if record.census_year==2010:assert cells[3]==''
  raw.append(dict(source_record_id=record.name,file=str(f),sha256=sha(f),raw_row0=rn,raw_cells=cells,adjacent_rows=[dict(row0=i,cells=sh.row_values(i))for i in range(rn-1,rn+2)]))
 W.append(dict(target_source_record_id=sid,own2002_record=d.fillna('').to_dict(),target2010_record=t.fillna('').to_dict(),anchors=anchors,unique_between_anchors=within.fillna('').to_dict('records'),true_county_inferred=county,imported_county_field_preserved=t.district_raw,actual_raw_2010_county_cell='',accepted_point_donor=q.to_dict(),rule=rule))
 p=q.to_dict();p.update(target_source_record_id=sid,coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_binding_rule=rule,point_use_inference='Explicit retrospective ownlocality representative point inference; actual censusday coordinate and boundaries unknown.',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,external_provider_ID_binding_asserted=True,evidence_file=str(O/'point_binding_witnesses.json.gz'),evidence_locator=f'[{wid}]');points.append(p);edges.append(dict(from_source_record_id=oid,to_source_record_id=sid,relation='same_place',decision_status='checked_rule_accepted',admission_method='two_sided_existing_accepted_native_source_order_anchors_unique_own_name_type',admission_rule=rule,population_boundary_comparability_asserted=False,evidence_file=str(O/'point_binding_witnesses.json.gz'),evidence_locator=f'[{wid}]'))
pd.DataFrame(points).to_csv(O/'accepted_point_use_delta.csv',index=False);pd.DataFrame(edges).to_csv(O/'accepted_identity_edge_delta.csv',index=False);pd.DataFrame([dict(source_record_id=p['target_source_record_id'],disposition='accepted_source_order_bound_ownpoint_and_same_place_edge',imported_county_preserved=True,missing_year_population_assigned=False)for p in points]).to_csv(O/'record_dispositions.csv',index=False)
for name,items in [('point_binding_witnesses.json.gz',W),('native_source_row_witnesses.json.gz',raw)]:
 with gzip.open(O/name,'wt')as f:json.dump(items,f,ensure_ascii=False)
manifest=dict(baseline_stage=71,accepted_own_point_uses=2,identity_edges_added=2,population_values_modified=False,validation=dict(two_sided_existing_accepted_source_order_anchors=True,counterpart_span_maximum4=True,raw2010_countycell_blank_not_importedХасанский=True,exactnative_name_and_type_unique_between_anchors=True,accepted_donor_origin_hash_checked=True),frozen_files=[dict(name=f.name,sha256=sha(f),bytes=f.stat().st_size)for f in sorted(O.iterdir())if f.is_file()]);(O/'freeze_manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2));print(2)
