import sys,json,ast,re
from pathlib import Path
from collections import Counter,defaultdict
import pandas as pd
R=Path('/workspace/russian-settlements-research');sys.path.insert(0,str(R/'research_rebuild/mass_linkage'));from working_state_20261007 import load
from current_chain_state_20261007 import normalize,distance_km,sha
from apply_unique_county_name_bridge_20261007 import county_key
O=Path(__file__).parent;A=R/'research_rebuild/evidence/old_year_spatial_competitor_resolution_application_20261008';A.mkdir(exist_ok=True);s=load(25);before=s.metrics();d=pd.read_csv(O/'candidate_source_bound_spatial_edges.csv',dtype={'historical_okato_2009_raw':str});code=pd.read_csv(O/'actual_current_code_alternative_audit.csv',dtype=str).set_index('from_source_record_id');q=pd.read_csv(O/'current_own_code_and_geographic_witnesses.csv',dtype=str).set_index('from_source_record_id');tree=ast.parse((R/'research_rebuild/evidence/cross_county_independent_point_bridge_20261007/build_neutral_subset.py').read_text());aliases=ast.literal_eval(next(x.value for x in tree.body if isinstance(x,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='pairs' for t in x.targets)));neutral={frozenset([county_key(x),county_key(y)]) for x,y in aliases.items()};neutral.add(frozenset(['ногинский','богородский']));edges=[];points=[];holds=[];applied=[];members=defaultdict(list)
for sid in s.by_id.index:members[s.uf.find(sid)].append(sid)
occupied=defaultdict(set)
for sid,p in s.point_rows.items():occupied[(int(s.by_id.loc[sid,'census_year']),p['latitude'],p['longitude'])].add(sid)
for z in d.to_dict('records'):
 sid,bid=z['from_source_record_id'],z['to_source_record_id'];old=county_key(z['old_bound_county'] if pd.notna(z['old_bound_county']) else z['raw_historical_county']);current=county_key(z['current_printed_county']);cc=code.loc[sid];qq=q.loc[sid];direct=cc.exact_own_code_agrees=='True' or qq.own_qid_old_code_corroboration=='True';same=(old==current or frozenset([old,current]) in neutral);urbanunique=(not old and len(z['historical_okato_2009_raw'])==8)
 if not(same or direct or urbanunique):holds.append({**z,'hold_reason':'Different geographic county stems without direct own-code/QID or documented municipal genealogy corroboration; avoid raw GeoKLADR wrong-namesake transfer inference'});continue
 if z['name'] in ['Александровка','Таежный'] and not direct:holds.append({**z,'hold_reason':'Unsupported different-stem old raw point identity'});continue
 if z['old_type'] in ['посёлок','поселок'] and z['current_type']=='участок':holds.append({**z,'hold_reason':'Current printed uchastok needs own populated-locality grain witness'});continue
 ra,rb=s.uf.find(sid),s.uf.find(bid)
 if ra==rb:continue
 if s.years[ra]&s.years[rb]:holds.append({**z,'hold_reason':'Actual repeated year after batch union'});continue
 cp=s.point_rows[bid];m=members[ra]+members[rb]
 if any(x not in s.point_rows and occupied[(int(s.by_id.loc[x,'census_year']),cp['latitude'],cp['longitude'])] for x in m):holds.append({**z,'hold_reason':'Proposed same-year point collision'});continue
 e=dict(z,relation='same_place',decision_status='checked_rule_accepted',admission_rule='Source-bound historical own name/type/context/raw point and unique local compatible current own locality within 5 km; all current physical rivals checked before graph filtering',county_continuity_evidence='Same/neutral geographic county caption' if same else 'Direct own historic code or QID corroboration' if direct else 'Region-unique historical urban own object',county_eventdate='UNKNOWN',boundary_comparability_asserted=False,native_old_printed_code_asserted=bool(z['old_native_code_asserted']));e.pop('current_own_point_json',None);edges.append(e);s.union(sid,bid);members[s.uf.find(sid)]=m;applied.append(z)
 for x in m:
  if x in s.point_rows:continue
  p=dict(cp);p.update(target_source_record_id=x,coordinate_admission_status='reviewed_extension_rule_accepted',admission_rule='Own modern representative retrospective reuse over source-bound native spatial identity; same external provider allowed when source bindings are independent of proposed edge',native_old_printed_code_asserted=False,boundary_comparability_asserted=False,point_temporal_interpretation='Modern own representative, not a measured census-date coordinate');p.pop('point_ledger_path',None);points.append(p);s.point_rows[x]=dict(p,point_ledger_path=str(A/'accepted_point_use_delta.csv'));occupied[(int(s.by_id.loc[x,'census_year']),p['latitude'],p['longitude'])].add(x)
pd.DataFrame(edges).to_csv(A/'accepted_identity_edge_delta.csv',index=False);pd.DataFrame(points).to_csv(A/'accepted_point_use_delta.csv',index=False);pd.DataFrame(holds).to_csv(A/'held_candidates.csv',index=False);after=s.metrics();roots={s.uf.find(z['from_source_record_id']) for z in applied if s.years[s.uf.find(z['from_source_record_id'])]=={2002,2010,2021}};fullpop={str(y):sum(int(s.by_id.loc[x,'population']) for r in roots for x in members[r] if int(s.by_id.loc[x,'census_year'])==y) for y in [2002,2010,2021]};receipt={'status':'Authorized accepted-rule subset prepared; explicit stage 25 API replay pending','baseline_stage':25,'accepted_identity_edges':len(edges),'accepted_point_uses':len(points),'held_candidates':len(holds),'new_finite_full_three_year_histories':len(roots),'new_finite_full_three_year_population':fullpop,'before':before,'after':after,'actual_net_population_gain':{y:after[y]['covered_population']-before[y]['covered_population'] for y in before},'actual_net_rows_gain':{y:after[y]['covered_rows']-before[y]['covered_rows'] for y in before},'fixed15_largest5_actual_native_and_raw_point_source_checks':20,'source_population_or_quality_changes':0,'existing_coordinate_rejections_or_overwrites':0,'county_eventdates_and_boundary_comparability':'UNKNOWN; not invented','independence':'Own binding to each source record, independent of proposed edge; same provider permitted','input_hashes':{str(p):sha(Path(p)) for p in [*s.inputs,O/'fixed15_largest5_actual_source_checks.csv',O/'actual_current_code_alternative_audit.csv',O/'current_own_code_and_geographic_witnesses.csv',O/'bogorodsky_noginsky_municipal_genealogy.json']},'output_pins':{p.name:sha(p) for p in A.glob('*.csv')}};(A/'application_receipt.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2));print(json.dumps({k:receipt[k] for k in ['accepted_identity_edges','accepted_point_uses','held_candidates','new_finite_full_three_year_histories','new_finite_full_three_year_population','actual_net_population_gain']},ensure_ascii=False))
