from pathlib import Path
import pandas as pd,json,gzip,hashlib,duckdb
O=Path(__file__).parent;sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();d=pd.read_parquet('/dev/shm/over500-moscow-after-sourcebound.parquet');p=pd.read_parquet('/dev/shm/over500-moscow-points.parquet').set_index('target_source_record_id');f=O/'own_wikipedia_batch1.json.gz';pg=next(p for p in json.load(gzip.open(f,'rt'))['query']['pages'].values()if p['title']=='Возрождение (городской округ Коломна)');txt=pg['revisions'][0]['slots']['main']['*'];co=pg['coordinates'][0];assert '46222819020'in txt and'Непецин'in txt and'8 км к северо-западу'in txt
sf=Path('/workspace/settlements-raw/data/raw/historical_classifiers/okato_142_2009/dump-142_2009.sql');line=sf.read_text(errors='replace').splitlines()[97709];assert '46222819020'in line and'Возрождение'in line
c=duckdb.connect();cl=c.execute("select * from read_parquet('/workspace/settlements-work/sources/raw_okato_2009_verification_v1/raw_classifier.parquet')where historical_okato like '46222%' and name='Возрождение'").fetchdf();assert len(cl)==1 and cl.iloc[0].historical_okato=='46222819020';cl.to_csv(O/'Vozrozhdenie_all_county_classifier_rivals.csv',index=False)
ids=[d[d.census_year.eq(2002)&d.name_norm.eq('отделения возрождение')].source_record_id.iloc[0],d[d.census_year.eq(2010)&d.name_norm.eq('возрождение')&d.derived_oldcounty.eq('Коломенский район')].source_record_id.iloc[0],'2021:data_allsettlements_anon_156_v20251217.parquet:parquet:67448'];assert d[d.source_record_id.eq(ids[-1])].oktmo.iloc[0]=='46738000206';rejs=[];pts=pd.read_csv(O/'accepted_point_use_delta.csv').to_dict('records');ed=pd.read_csv(O/'accepted_identity_edge_delta.csv').to_dict('records');case='moscow_Vozrozhdenie_correct_false_modern_coordinate';loc=f'pageid={pg["pageid"]};revision={pg["revisions"][0]["revid"]};coordinates[0]'
for sid in ids:
 if sid in p.index:
  cp=p.loc[sid];origin=Path(cp.point_ledger_path);assert origin.is_file();rejs.append(dict(target_source_record_id=sid,rejection_status='reviewed_rejected_coordinate_claim_only',old_latitude=cp.latitude,old_longitude=cp.longitude,origin_ledger=str(origin),origin_ledger_sha256=sha(origin),reason='Own exact Kolomna/Nepetsino locality article coordinates and explicit geography8kmNWofKolomna contradict inherited DaData point 15.443km displaced from qualified ownarticle; own historical classifier46222819020 unique in native county; original native observations and same-place identity retained',native_identity_or_population_rejected=False))
 pts.append(dict(target_source_record_id=sid,latitude=co['lat'],longitude=co['lon'],coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_source_record_id='Wikipedia:page'+str(pg['pageid']),source_sha256=sha(f),source_locator=loc,point_origin_file=str(f),point_origin_sha256=sha(f),point_origin_locator=loc,point_origin_kind='own_Wikipedia_qualified_native_locality_representative_point',case=case,coordinate_binding_rule='Own historical classifier46222819020 uniquely matches explicit own Kolomna/Nepetsino native poselok; own exact article geography and coordinates replace contradicted raw current inherited claims; historical ownership-designator continuation uses explicit ownsourcecounty',point_use_inference='own_modern_representative_point_on_source_bound_native_identity',population_boundary_comparability_asserted=False,historical_census_coordinate_asserted=False,secondary_population_not_substituted_for_native=True))
ed.append(dict(from_source_record_id=ids[0],to_source_record_id=ids[-1],relation='same_place',decision_status='checked_rule_accepted',case=case,admission_rule='Literal own settlement name with ownership-designator extension, unique native original Kolomna county; independent ownarticle and unique ownhistorical code; accepted2010-2021 component preserved and ownpoint corrected',source_binding_proof=str(O/'Vozrozhdenie_coordinate_correction_sourceproof.json'),population_boundary_comparability_asserted=False,municipal_event_date='UNKNOWN'))
oldroot=d[d.source_record_id.eq(ids[0])].after_root.iloc[0];newroot=d[d.source_record_id.eq(ids[-1])].after_root.iloc[0];assert not d[d.after_root.isin([oldroot,newroot])].census_year.duplicated().any();d.loc[d.after_root.eq(oldroot),'after_root']=newroot;d.to_parquet('/dev/shm/over500-moscow-after-correction.parquet',index=False)
pd.DataFrame(rejs).to_csv(O/'accepted_point_rejection_delta.csv',index=False);pd.DataFrame(pts).drop_duplicates('target_source_record_id',keep='last').to_csv(O/'accepted_point_use_delta.csv',index=False);pd.DataFrame(ed).to_csv(O/'accepted_identity_edge_delta.csv',index=False);(O/'Vozrozhdenie_coordinate_correction_sourceproof.json').write_text(json.dumps(dict(case=case,UIDs=ids,own_article_source=str(f),own_article_sha256=sha(f),own_article_locator=loc,own_article_literal=txt,classifier_source=str(sf),classifier_sha256=sha(sf),classifier_locator='line97710;historicalOKATO46222819020',classifier_literal=line,source_population_modified=False,old_provider_ID_binding_asserted=False),ensure_ascii=False,indent=2));print('correctedpoints',len(ids),'rejectedoldclaims',len(rejs),'identityedge1')
