from pathlib import Path
import gzip,json,urllib.request,urllib.parse,datetime,hashlib
O=Path(__file__).parent
names=['Порохово','Ильинское (Волоколамский район)','Детского Дома МООСО','Зарайский (посёлок)','Ледово (Каширский район)','Шеметово (Коломенский район)','Возрождение (Коломенский район)','Минвнешторга','ДСК «Мичуринец»','Яковлево (Москва)','Холмогорка (посёлок)','Орешково (Луховицкий район)','Нижне-Маслово','Шохово (Можайский район)','Абрамцево (Балашиха)','Данилково (Мытищинский район)','Толстопальцево (посёлок)','Кузнецово (Москва)','Новая (Балашиха)','Караваевской фабрики','Участка № 2','Тимохово (Ногинский район)','Кобяково (Одинцовский район)','Новая Деревня (Пушкино)','Раменской агрохимстанции','Тучковского автодорожного техникума','Никольское (Рузский район)','Пустоши (Шатурский район)','Луч (Щёлковский район)','Санаторий «Звенигород» (посёлок)','Алабино (рабочий посёлок)','Мешково (Москва)','Румянцево (Москва)','Десна (Москва)','Сосенки','Дорожно-ремонтного пункта-3','Захарово (Раменский район)','Старотеряево','Северная Грива','Ивановское (Волоколамский район)','Стеблево','Слободка Алёшино','Исаково (Воскресенский район)','Агафониха','Щурово (деревня)','Пограничный (Серпуховский район)','Пешково (Чеховский район)','Зелёноград','Восточный (район Москвы)','Внуково (район Москвы)','Некрасовка (район Москвы)','Александровка (Наро-Фоминский район)']
for i in range(0,len(names),40):
 u='https://ru.wikipedia.org/w/api.php?'+urllib.parse.urlencode(dict(action='query',titles='|'.join(names[i:i+40]),prop='revisions|pageprops|coordinates',rvprop='ids|content|timestamp',rvslots='main',format='json',redirects=1,colimit='max'))
 try:
  with urllib.request.urlopen(urllib.request.Request(u,headers={'User-Agent':'SettlementResearch/1.0'}),timeout=40)as r:b=r.read(12000000);status=r.status
  f=O/f'own_wikipedia_batch{i//40+1}.json.gz';f.write_bytes(gzip.compress(b));j=json.loads(b); rows=[dict(title=p['title'],missing='missing'in p,pageid=p.get('pageid'),revid=p.get('revisions',[{}])[0].get('revid'),point=p.get('coordinates'))for p in j.get('query',{}).get('pages',{}).values()];(O/f'fetch_batch{i//40+1}_receipt.json').write_text(json.dumps(dict(utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),request_url=u,normal_TLS=True,status=status,sha256=hashlib.sha256(f.read_bytes()).hexdigest(),pages=rows),ensure_ascii=False,indent=2));print(json.dumps(rows,ensure_ascii=False))
 except Exception as e:print(type(e).__name__,str(e))
