from pathlib import Path
import pandas as pd,json,hashlib,xlrd
O=Path(__file__).parent;sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();d=pd.read_parquet('/dev/shm/over500-moscow-after-correction.parquet');p=pd.read_parquet('/dev/shm/over500-moscow-points.parquet');pts=pd.read_csv(O/'accepted_point_use_delta.csv');edges=pd.read_csv(O/'accepted_identity_edge_delta.csv');a=pd.read_csv(O/'assigned111.csv');own=set(p.target_source_record_id)|set(pts.target_source_record_id);g={x:z for x,z in d.groupby('after_root')};a['after_root']=a.source_record_id.map(d.set_index('source_record_id').after_root);a['after_years']=a.after_root.map(lambda x:','.join(map(str,sorted(set(g[x].census_year)))));a['after_ownpoint']=a.source_record_id.isin(own);a['component_all_ownpoints']=a.after_root.map(lambda x:set(g[x].source_record_id)<=own);a['component_member_UIDs']=a.after_root.map(lambda x:'|'.join(g[x].source_record_id));a['disposition']=a.apply(lambda x:'accepted_ordinary_full3_route'if x.after_years=='2002,2010,2021'and x.component_all_ownpoints else'accepted_available_two_year_series_missing_year_UNKNOWN'if ','in x.after_years and x.component_all_ownpoints else'held_ownpoint_or_temporal_route_needs_independent_source',axis=1);a.to_csv(O/'all111_dispositions.csv',index=False)
statuses=[];observations=[]
for root in set(a[a.disposition.eq('accepted_available_two_year_series_missing_year_UNKNOWN')].after_root):
 z=g[root];scope='over500_moscow_available_'+root;years=set(z.census_year)
 for y in [2002,2010,2021]:
  rows=z[z.census_year.eq(y)];statuses.append(dict(scope_id=scope,year=y,status='actual_own_published_observation_on_source_bound_same_place_component'if y in years else'UNKNOWN_missing_native_year_no_birth_or_disappearance_inferred',own_population=int(rows.population.iloc[0])if y in years else'',unknown_is_zero=False,recipient_population_assigned_to_child=False,boundary_comparability='UNKNOWN',component_member_UIDs='|'.join(z.source_record_id)))
 for r in z.itertuples():observations.append(dict(scope_id=scope,source_record_id=r.source_record_id,year=r.census_year,native_population=r.population,native_population_quality=r.population_value_quality,own_point=True,ordinary_three_census_same_place_claim=False,is_additive_to_original_final_mixed_census_axis=False,missing_year_population_fabricated=False))
pd.DataFrame(statuses).to_csv(O/'accepted_available_year_statuses.csv',index=False);pd.DataFrame(observations).to_csv(O/'accepted_available_year_observations.csv',index=False)
raw2=Path('/workspace/settlements-raw/data/raw/2002/010_3e630cc803_02c_Moskovskaya-oblast.xls');raw10=Path('/workspace/settlements-raw/data/raw/2010/010_711691e352_2._20Kostrom_Kur_Lip_Moscow_MoscObl_Orlov_2010.xls');b={2002:xlrd.open_workbook(str(raw2)).sheet_by_index(0),2010:xlrd.open_workbook(str(raw10)).sheet_by_name('Data Sheet')};raws=[];uids=set(edges.from_source_record_id)|set(edges.to_source_record_id)|set(pts.target_source_record_id)
for r in d[d.source_record_id.isin(uids)&d.census_year.isin([2002,2010])].itertuples():
 if '010_3e630'in r.source_record_id or'010_711691'in r.source_record_id:
  n=int(r.source_record_id.rsplit(':',1)[-1]);row=b[r.census_year].row_values(n-1);assert any(str(v).replace('.0','')==str(int(r.population))for v in row),(r.source_record_id,row,r.population);f=raw2 if r.census_year==2002 else raw10;raws.append(dict(source_record_id=r.source_record_id,census_year=r.census_year,native_population=r.population,native_population_quality=r.population_value_quality,source_path=str(f),source_sha256=sha(f),source_locator=f'{b[r.census_year].name}:row{n}',raw_cells_json=json.dumps(row[:8],ensure_ascii=False),original_district_raw=r.district_raw,derived_sourcecounty=r.derived_oldcounty,population_values_modified=False))
pd.DataFrame(raws).to_csv(O/'native_raw_row_witnesses.csv.gz',index=False)
# Replay checks are bounded to Moscow; national gain and national denominators belong to root.
assert not pts.target_source_record_id.duplicated().any();assert not d.groupby('after_root').census_year.apply(lambda x:x.duplicated().any()).any();assert set(pts.target_source_record_id)<=set(d.source_record_id)
receipt=dict(status='batch1_frozen_reviewed_delta_ready_for_root_replay',assigned_records=len(a),accepted_identity_edges=len(edges),accepted_point_rows=len(pts),rejected_coordinate_claims=2,assigned_dispositions=a.disposition.value_counts().to_dict(),all_new_ordinary_components_no_sameyear_collision=True,native_raw_rows_verified=len(raws),native_counts_or_quality_modified=0,missing_year_zeros_or_counts_fabricated=0,national_credit_gain_not_claimed=True,point_correction_review='research_rebuild/evidence/over500_vozrozhdenie_review_20261009/review_receipt.json');(O/'BATCH1_receipt.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2));files=[f for f in O.iterdir()if f.is_file()and f.name not in ['BATCH1_manifest.json','BATCH1_manifest.sha256']];manifest=[dict(path=str(f),sha256=sha(f),bytes=f.stat().st_size)for f in sorted(files)];(O/'BATCH1_manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2));(O/'BATCH1_manifest.sha256').write_text(sha(O/'BATCH1_manifest.json')+'\n');print(json.dumps(receipt,ensure_ascii=False))
