from pathlib import Path
import json,gzip,hashlib,re,pandas as pd
from bs4 import BeautifulSoup
O=Path(__file__).parent
p=Path('/workspace/settlements-raw/data/interim/2021_tochno/data_allsettlements_anon_156_v20251217.parquet');native=pd.read_parquet(p,columns=['object_name','object_level','oktmo','okato_dadata','oktmo_dadata','fias_id_dadata','fias_level_dadata','latitude_dadata','longitude_dadata','population','mun_upper','mun_lower'])
targets=[(69461,'46766000517','46566000517',756,'osm_query_1.json.gz'),(69633,'46768000323','46568000323',881,'osm_query_2.json.gz'),(69634,'46768000326','46568000326',95,'zakharovo_small_bounded_osm.json.gz')]
rows=[]
for rn,old,new,pop,source in targets:
 n=native.iloc[rn-1];assert str(n.oktmo)==old and int(n.population)==pop and n.object_level=='Населенный пункт'
 f=O/source;a=json.loads(gzip.decompress(f.read_bytes()));v=[x for x in a if x.get('extratags',{}).get('oktmo:user')==new];assert len(v)==1;v=v[0]
 cw=O/f'classifier_explicit_crosswalk_{old}.html.gz';t=BeautifulSoup(gzip.decompress(cw.read_bytes()),'html.parser').get_text(' ',strip=True);literal=f'Аннулированному коду ОКТМО {old} соответствует новый код - {new}';assert literal in t
 old_page=O/f'code_lookup_{1 if rn==69461 else 2 if rn==69633 else 3}.html.gz';op=BeautifulSoup(gzip.decompress(old_page.read_bytes()),'html.parser').get_text(' ',strip=True);expected='с Никольское'if rn==69461 else 'с Захарово'if rn==69633 else 'д Захарово';assert expected in op
 featurekind=v['extratags'].get('official_status');assert featurekind==('ru:деревня'if rn==69634 else 'ru:село')
 rows.append(dict(source_record_id=f'2021:data_allsettlements_anon_156_v20251217.parquet:parquet:{rn}',native_population=pop,native_name_raw=n.object_name,native_kind_verified_from_classifier_mirror=expected,native_county=n.mun_upper,native_published_oktmo=old,modern_oktmo=new,source_current_code_field='OSM oktmo:user',crosswalk_literal=literal,crosswalk_source=str(cw),crosswalk_sha256=hashlib.sha256(cw.read_bytes()).hexdigest(),crosswalk_source_role='secondary mirror explicitly claiming Rosstat recoding tables; original official amendment not independently downloaded',own_source_file=str(f),own_source_sha256=hashlib.sha256(f.read_bytes()).hexdigest(),own_source_locator=f"osm_type={v['osm_type']};osm_id={v['osm_id']};lat,lon;extratags.oktmo:user",latitude=v['lat'],longitude=v['lon'],own_osm_kind=featurekind,own_osm_category=v.get('category'),own_osm_type=v.get('type'),own_osm_address_type=v.get('addresstype'),own_osm_name=v.get('name'),own_osm_address_json=json.dumps(v.get('address',{}),ensure_ascii=False),own_osm_extra_json=json.dumps(v.get('extratags',{}),ensure_ascii=False),raw_dadata_latitude=n.latitude_dadata,raw_dadata_longitude=n.longitude_dadata,raw_dadata_fias=n.fias_id_dadata,raw_dadata_oktmo=n.oktmo_dadata,modern_only=True,population_transferred=False,identity_edge_admitted=False,coordinate_admitted=False,candidate_only=True,coordinate_measurement_date='unknown',boundary_comparability_asserted=False))
pd.DataFrame(rows).to_csv(O/'three_modern_own_code_point_candidates.csv',index=False)
(O/'source_pins.json').write_text(json.dumps({str(p):dict(sha256=hashlib.sha256(p.read_bytes()).hexdigest(),bytes=p.stat().st_size)},indent=2));print(pd.DataFrame(rows)[['source_record_id','native_published_oktmo','modern_oktmo','latitude','longitude','own_osm_kind']].to_string(index=False))
