import pandas as pd,json,re,pathlib,hashlib
P=pathlib.Path('/workspace/russian-settlements-research/research_rebuild/evidence/over500_south_remaining_points_20261009');obs=pd.read_parquet('/dev/shm/settlements-stage71-20261009/applied_state_observations.parquet');n=pd.read_parquet('/dev/shm/over500-20261009/south_native_current.parquet').reset_index();z=obs[obs.census_year==2021].merge(n,on='source_record_id',suffixes=('','_native'));c=pd.read_csv(P/'source_order_current_context.csv');r=pd.read_csv('/dev/shm/over500-20261009/south_remaining.csv');snap='/dev/shm/settlements-stage71-20261009/applied_point_snapshot.parquet';pts=pd.read_parquet(snap);accepted=pd.read_csv(P/'accepted_point_use_delta.csv');adds=[];inventory=[]
def norm(t):return re.sub('[^а-я0-9 ]',' ',str(t).lower().replace('ё','е')).strip()
for _,t in c.merge(r,on='source_record_id').iterrows():
 q=z[(z.region_norm==t.region_norm)&(z.name_norm==t.name_norm)];alts=json.loads(t.bounded_county_alternatives);mask=q.mun_upper.map(lambda m:any(a in norm(m) for a in alts)).astype(bool);q=q.loc[mask];inventory.append(dict(source_record_id=t.source_record_id,bounded_counties=t.bounded_county_alternatives,all_type_native_candidates=json.dumps(q[['source_record_id','settlement_name','settlement_type','mun_upper','mun_lower','oktmo_native'] if 'oktmo_native' in q else ['source_record_id','settlement_name','settlement_type','mun_upper','mun_lower']].to_dict('records'),ensure_ascii=False)))
 if len(q)!=1:continue
 donor=q.iloc[0];b=pts[pts.target_source_record_id==donor.source_record_id]
 if len(b)!=1:continue
 b=b.iloc[0]
 if pd.isna(b.latitude) or pd.isna(b.longitude):continue
 if donor.type_norm!=t.type_norm:continue
 adds.append(dict(target_source_record_id=t.source_record_id,coordinate_source_record_id=donor.source_record_id,latitude=b.latitude,longitude=b.longitude,coordinate_admission_status='reviewed_extension_rule_accepted',admission_rule='unique_all_type_native_name_in_both_physical_flank_counties_with_accepted_ownpoint',coordinate_origin_ledger=snap,coordinate_origin_ledger_sha256=hashlib.sha256(pathlib.Path(snap).read_bytes()).hexdigest(),coordinate_origin_ledger_locator='target_source_record_id='+donor.source_record_id,point_origin_file=b.point_origin_file,point_origin_sha256=b.point_origin_sha256,point_origin_locator=b.point_origin_locator,point_origin_kind=b.point_origin_kind,point_temporal_interpretation='Own locality representative retrospectively reused; source NULL county preserved, bounded county alternatives explicit',direct_historical_coordinate_measurement=False,boundary_comparability_asserted=False,native_code_binding_asserted=False,source_binding_note='Two independently accepted physical workbook flanks; exact native name/type unique across all types in union of both native current counties; source witness+all rivals retained',source_context_witness_file=str(P/'source_order_current_context.csv')))
pd.DataFrame(inventory).to_csv(P/'bounded_native_all_type_inventory.csv.gz',index=False,compression={'method':'gzip','mtime':0});pd.concat([accepted,pd.DataFrame(adds)],ignore_index=True).drop_duplicates('target_source_record_id').to_csv(P/'accepted_point_use_delta.csv',index=False);print('added',len(adds));print(pd.DataFrame(adds)[['target_source_record_id','coordinate_source_record_id']].to_string(index=False))
