import sys,pathlib,pandas as pd,hashlib
sys.path.insert(0,'research_rebuild/mass_linkage');from verify_geokladr_snapshot import parse_dbf_header
P=pathlib.Path('research_rebuild/evidence/over500_south_remaining_points_20261009');DBF=pathlib.Path('/workspace/settlements-raw/data/raw/historical_geography/geokladr_okato_2011/okato.dbf');SQL='/workspace/settlements-raw/data/raw/historical_classifiers/okato_142_2009/dump-142_2009.sql';x=pd.read_parquet('/dev/shm/over500-20261009/raw_classifier.parquet');r=pd.read_csv('/dev/shm/over500-20261009/south_remaining.csv');wanted={'42242844001':('совхоза Пальна-Михайловский','Printed estate designation, own 2009 code/council/county; distinct Пальна-Михайловка selo excluded'),'56245810001':('Плес','Native Плес underПлесский council/Mokshansky; 2009 own Плесс, doubled consonant explicit'),'18258816001':('Верхнегнутовский','NativeЧернышковский/Верхнегнутовский council; 2009 own хуторВерхнегнутов, adjective variation explicit'),'68246890001':('Центральное Отделение Совхоза Сулакский','Native ownСулакский council/Umet; own2009 estate label; distinct селоСулак excluded')};found=[];raws=[]
with DBF.open('rb') as f:
 h=f.read(32);hl=int.from_bytes(h[8:10],'little');f.seek(0);header=f.read(hl);n,hl,rl,fields=parse_dbf_header(header);fields={v['name']:v for v in fields}
 for no in range(1,n+1):
  raw=f.read(rl)
  def field(k):s=fields[k];return raw[s['offset']:s['offset']+s['width']].decode('cp1251').strip()
  code=''.join(field(k) for k in ['TER','KOD1','KOD2','KOD3'])
  if code not in wanted:continue
  name,note=wanted[code];t=r[r.settlement_name==name].iloc[0];lat=field('LAT');lon=field('LONG');print(code,name,field('NAME1'),lat,lon)
  if not lat or not lon:continue
  lat=float(lat.replace(',','.'));lon=float(lon.replace(',','.'));assert 30<lat<80 and 15<lon<180
  loc=f'raw_dbf_record_number_1based={no};byte_offset_0based={hl+(no-1)*rl}';cl=x[x.historical_okato==code].iloc[0];raws.append(dict(target_source_record_id=t.source_record_id,historical_okato=code,geo_name=field('NAME1'),geo_type=field('SCOKATO'),geo_status=field('STATUS'),deleted_marker=raw[:1].decode(),classifier_name_raw=cl.name_raw,classifier_source_line=cl.source_line_1based,raw_locator=loc))
  found.append(dict(target_source_record_id=t.source_record_id,coordinate_source_record_id='GeoKLADR2011:OKATO:'+code,latitude=lat,longitude=lon,coordinate_admission_status='reviewed_extension_rule_accepted',admission_rule='qualified_native_estate_or_literal_spelling_county_and_sourcecouncil_2009_owncode_to_GeoKLADR_ownrecord',point_origin_file=str(DBF),point_origin_sha256=hashlib.sha256(DBF.read_bytes()).hexdigest(),point_origin_locator=loc,point_origin_kind='geokladr_2011_raw_dbf_coordinate',point_temporal_interpretation='Own source point representative; census date coordinate measurement/boundary equivalence not asserted',direct_historical_coordinate_measurement=False,boundary_comparability_asserted=False,native_code_binding_asserted=False,source_binding_note=note,classifier_origin_file=SQL,classifier_origin_sha256=hashlib.sha256(pathlib.Path(SQL).read_bytes()).hexdigest(),classifier_origin_locator='source_line_1based='+str(cl.source_line_1based)))
a=pd.read_csv(P/'accepted_point_use_delta.csv');pd.concat([a,pd.DataFrame(found)],ignore_index=True).drop_duplicates('target_source_record_id').to_csv(P/'accepted_point_use_delta.csv',index=False);pd.DataFrame(raws).to_csv(P/'historical_owncode_point_witnesses.csv',index=False)
