import pandas as pd,pathlib,hashlib,json
P=pathlib.Path('/workspace/russian-settlements-research/research_rebuild/evidence/over500_south_remaining_points_20261009');snapshot='/dev/shm/settlements-stage71-20261009/applied_point_snapshot.parquet';x=pd.read_parquet(snapshot);old='2010:018_8eadc2d6b9_7._20Dag_2010.xls:2010:118';new='2021:data_allsettlements_anon_156_v20251217.parquet:parquet:16284';a=x[x.target_source_record_id==old].iloc[0];b=x[x.target_source_record_id==new].iloc[0];h=lambda p:hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
rej=dict(target_source_record_id=old,rejection_status='reviewed_rejected_coordinate_claim_only',old_latitude=a.latitude,old_longitude=a.longitude,coordinate_source_record_id=a.coordinate_source_record_id,point_origin_file=a.point_origin_file,point_origin_sha256=a.point_origin_sha256,point_origin_locator=a.point_origin_locator,origin_ledger=a.point_ledger_path,origin_ledger_sha256=h(a.point_ledger_path),rejection_reason='Own plain Инхело, corroborated by source2002 physical Khasav note and accepted2010–2021 identity; former admitted GeoKLADR point is97.190km away in mountain cluster. Preserve native counts, raw B118:C118 enrichment and original provider claim; reject only own representative use. Independent review evidence/over500_inkhelo_review_20261009/review_receipt.json')
pd.DataFrame([rej]).to_csv(P/'accepted_point_rejections.csv',index=False)
q=dict(target_source_record_id=old,coordinate_source_record_id=b.coordinate_source_record_id,latitude=b.latitude,longitude=b.longitude,coordinate_admission_status='reviewed_extension_rule_accepted',admission_rule='accepted_identity_continuity_after_independently_reviewed_wrong_point_rejection',coordinate_origin_ledger=snapshot,coordinate_origin_ledger_sha256=h(snapshot),coordinate_origin_ledger_locator='target_source_record_id='+new,point_origin_file=b.point_origin_file,point_origin_sha256=b.point_origin_sha256,point_origin_locator=b.point_origin_locator,point_origin_kind=b.point_origin_kind,point_temporal_interpretation='Accepted current own plain locality representative reused retrospectively; no census date measurement or provider identifier binding',direct_historical_coordinate_measurement=False,boundary_comparability_asserted=False,native_code_binding_asserted=False)
f=P/'accepted_point_use_delta.csv';z=pd.read_csv(f);z=z[z.target_source_record_id!=old];pd.concat([z,pd.DataFrame([q])],ignore_index=True).to_csv(f,index=False)
e=dict(from_source_record_id='2002:029_fe8710371d_02c_Dagestan.xls:2002:210',to_source_record_id=new,relation='same_place',decision_status='checked_rule_accepted',admission_rule='source_literal_Инхело_Новое_Инхело_and_physical_Khasav_note_with_accepted_current_plain_locality',source_context_witness_file='/workspace/russian-settlements-research/research_rebuild/evidence/over500_inkhelo_review_20261009/review_receipt.json',population_boundary_comparability_asserted=False,legal_type_change_date_asserted=False)
pd.DataFrame([e]).to_csv(P/'accepted_identity_edge_delta.csv',index=False)
print('rejected',a.latitude,a.longitude,'replacement',b.latitude,b.longitude)
