from pathlib import Path
import pandas as pd,duckdb,json,hashlib,gzip,xlrd,sys,ast,re,unicodedata,collections,datetime
O=Path(__file__).parent;PACK=O.parent;E=PACK.parent;R=E.parent.parent;B=E/'main_axis_residual_application67_20261008';sys.path.insert(0,str(R/'research_rebuild/mass_linkage'));from current_chain_state_20261007 import distance_km
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();S=B/'applied_state_observations.parquet';P=B/'applied_point_snapshot.parquet';sid='2021:data_allsettlements_anon_156_v20251217.parquet:parquet:133281';oid='2002:044_42b3ed3cfc_Tataria.xls:Sheet1:12';c=duckdb.connect();c.execute("SET memory_limit='512MB'");c.execute('SET threads=1');c.register('ee',pd.DataFrame({'source_record_id':[sid,oid]}));end=c.execute('select * from read_parquet(?) join ee using(source_record_id)',[str(S)]).fetchdf();roots=end.root.tolist();c.register('rr',pd.DataFrame({'root':roots}));mem=c.execute('select s.* from read_parquet(?) s join rr using(root)',[str(S)]).fetchdf();c.register('mm',mem[['source_record_id']]);pts=c.execute('select p.* from read_parquet(?) p join mm using(source_record_id)',[str(P)]).fetchdf();carrier=pts[pts.source_record_id.eq(sid)].iloc[0].to_dict();years={rt:set(mem[mem.root.eq(rt)].census_year.astype(int)) for rt in roots};assert not years[roots[0]]&years[roots[1]]
assert all(distance_km((float(carrier['latitude']),float(carrier['longitude'])),(float(p['latitude']),float(p['longitude'])))<=5 for p in pts.to_dict('records'))
old=end[end.source_record_id.eq(oid)].iloc[0].to_dict();cur=end[end.source_record_id.eq(sid)].iloc[0].to_dict();raw=Path('/workspace/settlements-raw/data/raw/2002/044_42b3ed3cfc_Tataria.xls');book=xlrd.open_workbook(str(raw),on_demand=True);sheet=book.sheet_by_name('Sheet1');rows=[{'sheet':'Sheet1','row':i,'literal_fields':sheet.row_values(i-1)[:8]} for i in [10,11,12]];assert rows[2]['literal_fields'][0].strip()=='посёлок Новый Биклянь' and float(rows[2]['literal_fields'][1])==float(old['population']);assert 'Круглопольский сельсовет' in rows[1]['literal_fields'][0];book.release_resources()
article=E/'largest_available_year_lifecycle_round2_20261008/bounded_own_articles.json.gz';d=json.load(gzip.open(article,'rt'));pages=d['query']['pages'];pages=pages.values() if isinstance(pages,dict) else pages;page=next(q for q in pages if q.get('title')=='Круглое Поле (посёлок)');rev=page['revisions'][0];sl=rev['slots']['main'];txt=sl.get('*',sl.get('content',''));assert rev['revid']==154719654 and 'Прежнее название\xa0— Новый Биклянь' in txt and 'Круглопольское сельское поселение' in txt
rivals=c.execute("select source_record_id,census_year,settlement_name,settlement_type,district_raw,population,root from read_parquet(?) where region_norm='татарстан' and settlement_name in ('Новый Биклянь','Круглое Поле')",[str(S)]).fetchdf();assert len(rivals[rivals.census_year.eq(2002)&rivals.settlement_name.eq('Новый Биклянь')])==1
RAW=Path('/workspace/settlements-raw/data/interim/2021_tochno/data_allsettlements_anon_156_v20251217.parquet');native=c.execute('select * from (select row_number() over() rn,object_name,object_level,region,mun_upper,mun_lower,oktmo from read_parquet(?)) where rn=133281 or object_name ilike ?', [str(RAW),'%Круглое Поле%']).fetchdf();n=native[native.rn.eq(133281)].iloc[0].to_dict();assert n['oktmo']=='92657433101' and 'Круглопольское' in n['mun_lower']
q=lambda x:json.dumps(x,ensure_ascii=False,default=str);wit={'current_source_record_id':sid,'historic_source_record_id':oid,'current_name':cur['settlement_name'],'current_population2021':cur['population'],'historic_year':2002,'region':cur['region_norm'],'current_native_owncode':n['oktmo'],'current_raw_primary_row_json':q(n),'historic_native_observation_json':q(old),'current_accepted_physical_point_json':q(carrier),'historic_raw_source_evidence_json':q({'source_file':str(raw),'source_sha256':sha(raw),'literal_rows':rows,'raw_row_scope':'proper named settlement under printed Kруглопольский сельсовет; historical parent municipal context explicitly differs from currentcounty, no invented immutable boundary'}),'cached_own_article_source_evidence_json':q({'source_file':str(article),'source_sha256':sha(article),'title':page['title'],'pageid':page['pageid'],'revision':rev['revid'],'timestamp':rev.get('timestamp'),'url':'https://ru.wikipedia.org/w/index.php?oldid=154719654','excerpt_lines':[s for s in txt.splitlines() if any(k in s for k in ['русское название','район ','поселение ','Прежнее название','прежние имена','единственный населённый пункт'])]}),'all_same_region_exact_current_or_former_name_alltype_rivals_json':q(rivals.to_dict('records')),'current_raw_literal_namesake_native_parishes_json':q(native.to_dict('records')),'component_members_actual67_json':q(mem.to_dict('records')),'observed_name_change_date_status':'UNKNOWN_no_legaldate_inferred','identity_inference':'explicit ownarticle formername plus literal oldtypedNP under specific printed parish matching current proper named parish; distinct village namesake preserved; population not identity matchfeature','external_provider_identifier_transfer_asserted':False,'historical_date_coordinate_measurement_asserted':False,'population_boundary_comparability_asserted':False}
edge={'from_source_record_id':oid,'to_source_record_id':sid,'relation':'same_place','decision_status':'checked_rule_accepted','admission_method':'cached_ownarticle_formername_and_literal_old_specific_parish_closed_rivals','admission_rule':wit['identity_inference'],'population_boundary_comparability_asserted':False};newpoints=[]
for z in mem.to_dict('records'):
 if z['source_record_id'] in set(pts.source_record_id):continue
 newpoints.append({'target_source_record_id':z['source_record_id'],'latitude':float(carrier['latitude']),'longitude':float(carrier['longitude']),'coordinate_admission_status':'reviewed_extension_rule_accepted','coordinate_source_record_id':carrier['coordinate_source_record_id'],'point_origin_file':carrier['point_origin_file'],'point_origin_sha256':carrier['point_origin_sha256'],'point_origin_locator':carrier['point_origin_locator'],'point_origin_kind':'retrospective_representative_ownNP_point_through_sourcebound_formername_identity','coordinate_binding_rule':wit['identity_inference'],'historical_census_coordinate_asserted':False,'population_boundary_comparability_asserted':False,'external_provider_ID_binding_asserted':False,'current_carrier_source_record_id':sid})
# Keep first-pass diagnostics intact and freeze the combined packet under final/.
F=O/'final';F.mkdir(exist_ok=True);efs=[pd.read_csv(O/'accepted_identity_edge_delta.csv.gz',dtype=str,keep_default_na=False),pd.read_csv(O/'county/accepted_identity_edge_delta.csv.gz',dtype=str,keep_default_na=False),pd.DataFrame([edge])];ps=[pd.read_csv(O/'accepted_point_use_delta.csv.gz',dtype=str,keep_default_na=False),pd.read_csv(O/'county/accepted_point_use_delta.csv.gz',dtype=str,keep_default_na=False),pd.DataFrame(newpoints)];ef=pd.concat(efs,ignore_index=True);pe=pd.concat(ps,ignore_index=True);assert len(ef)==len(ef.drop_duplicates(['from_source_record_id','to_source_record_id']));assert len(pe)==len(pe.drop_duplicates('target_source_record_id'))
w1=pd.read_csv(O/'accepted_regional_unique_source_evidence.csv.gz',dtype=str,keep_default_na=False);w2=pd.read_csv(O/'county/accepted_county_or_parish_source_evidence.csv.gz',dtype=str,keep_default_na=False)
# Reopen actual67 carrier source and normalize common fields for guard and bounded review.
carriers={z['source_record_id']:z for z in c.execute('select * from read_parquet(?) where source_record_id in (select to_source_record_id from ef)',[str(P)]).fetchdf().to_dict('records')} if False else {}
c.register('targets',pd.DataFrame({'source_record_id':ef.to_source_record_id.unique()}));cp=c.execute('select p.* from read_parquet(?) p join targets using(source_record_id)',[str(P)]).fetchdf();carriers={z['source_record_id']:z for z in cp.to_dict('records')}
for i,z in w2.iterrows():w2.loc[i,'current_accepted_physical_point_json']=q(carriers[z['current_source_record_id']]);w2.loc[i,'historic_year']='2002';w2.loc[i,'region']=z.get('region','');w2.loc[i,'current_population2021']=z['current_population2021']
wf=pd.concat([w1,w2,pd.DataFrame([wit])],ignore_index=True).fillna('')
for name,data in [('accepted_identity_edge_delta',ef),('accepted_point_use_delta',pe),('accepted_source_evidence',wf)]:data.to_csv(F/(name+'.csv.gz'),index=False,compression={'method':'gzip','mtime':0})
# Actual67 scoped union projection: complete3 finite ownpoint-bearing observations only.
c.register('ends',pd.DataFrame({'source_record_id':list(set(ef.from_source_record_id)|set(ef.to_source_record_id))}));rr=c.execute('select distinct s.root from read_parquet(?) s join ends using(source_record_id)',[str(S)]).fetchdf();c.register('roots',rr);ms=c.execute('select s.source_record_id,s.root,s.census_year,s.population,p.has_own_point from read_parquet(?) s join roots using(root) join read_csv_auto(?) p using(source_record_id)',[str(S),str(B/'applied_component_snapshot.csv.gz')]).fetchdf();c.close();parent={x:x for x in rr.root};sidroot=ms.set_index('source_record_id').root.to_dict()
def find(x):
 while parent[x]!=x:parent[x]=parent[parent[x]];x=parent[x]
 return x
for z in ef.to_dict('records'):parent[find(sidroot[z['from_source_record_id']])]=find(sidroot[z['to_source_record_id']])
groups=collections.defaultdict(list)
for z in ms.to_dict('records'):groups[find(z['root'])].append(z)
gain=collections.Counter();uid=collections.Counter();new=set(pe.target_source_record_id);partial=[]
for rt,mm in groups.items():
 yy=[int(z['census_year']) for z in mm];assert len(yy)==len(set(yy))
 if set(yy)=={2002,2010,2021} and all(pd.notnull(z['population']) for z in mm) and all(z['has_own_point'] or z['source_record_id'] in new for z in mm):
  for z in mm:gain[int(z['census_year'])]+=float(z['population']);uid[int(z['census_year'])]+=1
 else:partial.append({'root':rt,'years':yy})
projection={'status':'conditional_actual67_scoped_UF_projection_not_applied','known_finite_full3_ownpoint_population_gain_by_year':dict(gain),'new_primary_UIDs_by_year':dict(uid),'partial_groups':partial,'canonical_replay_required':True};(F/'conditional_main_population_projection.json').write_text(json.dumps(projection,indent=2));print('finaledges',len(ef),'points',len(pe),'conditionalgain',dict(gain))
