from pathlib import Path
import sys,json,gzip,hashlib,time,re
import pandas as pd
O=Path(__file__).parent;E=O.parent;ROOT=E.parents[1];sys.path.insert(0,str(ROOT/'research_rebuild/mass_linkage'))
from working_state_20261007 import load,PARTITION_MEMBERS
from current_chain_state_20261007 import sha
T=time.monotonic();s=load(18);c=pd.read_csv(O/'native2021_census_history_candidates.csv').fillna('');p=pd.read_csv(O/'candidate_qualified_physical_observations.csv').fillna('');previousq=set(pd.read_csv(E/'wikidata_actual_full3_mass_reserve_20261007/targets.csv').qid);credited={sid for sid in s.point_rows if s.years[s.uf.find(sid)]=={2002,2010,2021}};pins={};exclusions={}
paths=[PARTITION_MEMBERS,E/'working_full_chain_20261007/qualified_scope_source_id_credit_union.csv',E/'wikidata_secondary_full3_application_20261007/accepted_current_source_id_credit_union.csv',E/'current_unpointed_own_wiki_mass_application_20261007/accepted_qualified_physical_observations.csv']+[E/d/'accepted_constituent_credit_union.csv' for d in ['named_urban_merger_application_20261007','next_named_urban_merger_application_20261007','further_urban_merger_application_20261007']]
for path in paths:
 if not path.exists():continue
 f=pd.read_csv(path,dtype=str).fillna('');ids=set()
 for col in f.columns:
  if 'source_record_id' in col:ids.update(f[col])
 ids.discard('');credited.update(ids);exclusions[str(path)]={'sha256':sha(path),'source_ids':sorted(ids)}
otherfile=Path('/workspace/settlements-work/existing_event_scope_reserve_20261007/residual.json');otherids={r['sid'] for r in json.loads(otherfile.read_text())};credited.update(otherids);held=[];qualified=[];selected=[];credit=[]
for t in c.itertuples():
 if t.qid in previousq:held.append({'qid':t.qid,'sid':t.sid,'name':t.name,'population2021':t.population_2021_selected,'hold_reason':'QID_reused_by_different_native_NP_in_previous300; current_binding_ambiguous'});continue
 if t.sid in credited:held.append({'qid':t.qid,'sid':t.sid,'name':t.name,'population2021':t.population_2021_selected,'hold_reason':'already_credited_or_owned_by_other508_route'});continue
 native=s.by_id.loc[t.sid];point=s.point_rows[t.sid];assert native.is_additive_settlement_record and native.population>0;assert int(native.census_year)==2021;g=p[p.qid==t.qid];assert set(g.year)=={2002,2010,2021}
 for r in g.itertuples():
  hist=r.year!=2021
  if hist:
   st=json.loads(r.raw_statement_json);assert float(st['mainsnak']['datavalue']['value']['amount'])==r.population;assert any(x['datavalue']['value']['time']==r.declared_date for x in st['qualifiers']['P585']);assert 'P518' not in st.get('qualifiers',{});assert int(r.date_precision)==9 or r.date_class=='exact_census_date_secondary';assert r.census_proof_class
  qualified.append({'trajectory_id':'wikidata_secondary_expansion:'+t.qid,'year':int(r.year),'population_source_value':float(r.population) if hist else float(native.population),'source_record_id':'' if hist else t.sid,'settlement_name':native.settlement_name,'region_norm':native.region_norm,'county_context':native.district_raw,'latitude':float(point['latitude']),'longitude':float(point['longitude']),'population_quality':'secondary_explicit_census_reference_date_or_title_primary_not_independently_verified' if hist else native.population_value_quality,'grain':'own physical locality actual dated secondary census observation' if hist else 'existing selected native2021 census settlement observation','nonadditive_observation':hist,'source_path':r.source_path if hist else ('/workspace/settlements-raw/'+str(native.source_file)),'source_sha256':r.source_sha256 if hist else (str(native.source_sha256) if pd.notna(native.source_sha256) else ''),'source_locator':r.locator if hist else 'selected source_record_id='+t.sid,'decision_status':'candidate_only_actual_secondary_census_history_native2021','ordinary_NP3_asserted':False,'boundary_comparability_asserted':False,'point_origin_file':point.get('point_origin_file',''),'point_origin_sha256':point.get('point_origin_sha256',''),'point_origin_locator':point.get('point_origin_locator',''),'point_binding_json':json.dumps(point,ensure_ascii=False),'retrospective_point_use_is_continuity_inference':hist,'selected_credit_previously_present':False,'selected_source_sha256_as_loaded':str(native.source_sha256) if not hist and pd.notna(native.source_sha256) else '', 'scope':'secondary_census_referenced_own_physical_locality_expansion','boundary_comparability':'UNKNOWN','wikidata_id':t.qid,'declared_date':r.declared_date if hist else '+2021-10-01T00:00:00Z','date_precision':int(r.date_precision) if hist else 11,'census_proof_class':r.census_proof_class,'census_reference_titles_json':r.raw_reference_titles_json if hist else '[]','P248_ids_json':r.raw_P248_ids_json if hist else '[]','P248_labels_json':r.P248_labels_json if hist else '[]','P459_method_ids_json':r.raw_P459_method_ids_json if hist else '[]','reference_urls_json':r.raw_reference_urls_json if hist else '[]','statement_id':r.statement_id if hist else '', 'own_item_binding':t.identity_binding,'own_physical_description':t.description,'optional_Wiki_P625_count':t.optional_Wiki_P625_count,'optional_Wiki_coordinates_imported':False,'coordinate_bounds':'UNKNOWN','error_rate':'uncalibrated'})
 selected.append(t._asdict());credit.append({'source_record_id':t.sid,'year':2021,'population':float(native.population),'trajectory_id':'wikidata_secondary_expansion:'+t.qid,'credit_status':'candidate_only_native_selected_ID_uncredited','actual_admitted_gain':0})
f=pd.DataFrame(qualified);cs=pd.DataFrame(selected);pd.DataFrame(held).to_csv(O/'final_credit_or_identity_holds.csv',index=False);f.to_csv(O/'review_ready_qualified_physical_observations.csv',index=False);pd.DataFrame(credit).to_csv(O/'unique_native2021_source_ID_net_potential.csv',index=False);cs.to_csv(O/'review_ready_series.csv',index=False)
# One final deterministic15 plus largest5 concrete source checks, after net exclusions.
largest=set(cs.sort_values('population_2021_selected',ascending=False).head(5).qid);fixed=set(cs.assign(k=cs.qid.map(lambda q:hashlib.sha256(('fixed15-expansion-20261007'+q).encode()).hexdigest())).sort_values('k').head(15).qid);checks=[]
for t in cs[cs.qid.isin(largest|fixed)].itertuples():
 g=f[f.wikidata_id==t.qid];n=s.by_id.loc[t.sid];hist=g[g.year!=2021];checks.append({'qid':t.qid,'name':t.name,'largest5':t.qid in largest,'fixed15':t.qid in fixed,'own_item_binding':t.identity_binding,'native_source_record_id':t.sid,'native_current_code':n.oktmo,'native_type':n.settlement_type,'native_geography_json':json.dumps({'region':n.region_norm,'district':n.district_raw},ensure_ascii=False),'own_physical_description':t.description,'optional_Wiki_P625_count':t.optional_Wiki_P625_count,'current_native_population':n.population,'native_population_quality':n.population_value_quality,'histories_raw_source_hashes_rechecked':all(sha(Path(r.source_path))==r.source_sha256 for r in hist.itertuples()),'historical_values_dates_census_reference_witnesses_json':hist[['year','population_source_value','declared_date','date_precision','statement_id','source_path','source_sha256','source_locator','census_proof_class','census_reference_titles_json','P248_ids_json','P248_labels_json','P459_method_ids_json','reference_urls_json']].to_json(orient='records',force_ascii=False),'point_rule':'admitted own current NP point retained; Wiki coordinates not imported','known_scope_result':'no P518 subset qualifier; non-census dates/annual references excluded; former/dissolved/post2002 founding held; previous-QID and other-route IDs held','status':'checked_candidate_only'})
pd.DataFrame(checks).to_csv(O/'fixed15_and_largest5_source_checks.csv',index=False)
for path in dict.fromkeys(s.inputs+[otherfile,O/'targets.csv',O/'census_history_proof_rows.csv',E/'wikidata_actual_full3_mass_reserve_20261007/targets.csv',ROOT/'research_rebuild/mass_linkage/working_state_20261007.py']+[Path(p) for p in f[f.year!=2021].source_path.unique()]+list(Path('/workspace/settlements-work/wikidata_secondary_full3_expansion_20261007').glob('*.gz'))):pins[str(path)]={'sha256':sha(path),'bytes':path.stat().st_size}
(O/'source_manifest.json').write_text(json.dumps(pins,indent=2));(O/'preexisting_credit_exclusions_frozen.json').write_text(json.dumps(exclusions,ensure_ascii=False));rc=json.loads((O/'receipt.json').read_text());rc.update({'final_candidate_series':len(cs),'final_candidate_observations':len(f),'historical_nonadditive_rows':int(f.nonadditive_observation.sum()),'net_current_native_source_ids':len(credit),'net_current_native_population_potential':sum(r['population'] for r in credit),'net_historical_selected_ID_gain':0,'actual_admitted_gain':0,'final_source_sample_fixed15':len(fixed),'final_source_sample_largest5':len(largest),'source_checks_union_rows':len(checks),'all_history_GUID_value_date_checks':int(f.nonadditive_observation.sum()),'final_proof_classes':f[f.year!=2021].census_proof_class.value_counts().to_dict(),'largest5':[{'qid':t.qid,'name':t.name,'native_population':t.population_2021_selected} for t in cs.sort_values('population_2021_selected',ascending=False).head(5).itertuples()],'finalize_seconds':time.monotonic()-T});(O/'receipt.json').write_text(json.dumps(rc,indent=2,ensure_ascii=False));print(json.dumps({k:rc[k] for k in ['final_candidate_series','net_current_native_population_potential','historical_nonadditive_rows','all_history_GUID_value_date_checks','largest5']},ensure_ascii=False))
