from pathlib import Path
import pandas as pd,json,hashlib,math
R=Path('/workspace/russian-settlements-research');E=R/'research_rebuild/evidence';B=E/'main_axis_residual_application65_20261008';O=E/'current_carrier_missing_retrospective65_20261008';O.mkdir(exist_ok=True)
def sha(p):
 h=hashlib.sha256()
 with Path(p).open('rb') as f:
  for c in iter(lambda:f.read(1048576),b''):h.update(c)
 return h.hexdigest()
def dist(a,b):
 la,lo,lb,lob=map(math.radians,[float(a['latitude']),float(a['longitude']),float(b['latitude']),float(b['longitude'])]);h=math.sin((lb-la)/2)**2+math.cos(la)*math.cos(lb)*math.sin((lob-lo)/2)**2;return 6371*2*math.asin(min(1,math.sqrt(h)))
diag=json.loads((E/'main_axis_residual_registry_20261008/stage65_next_mass_diagnostic.json').read_text());roots={x['component_root'] for x in diag['immediate_current_carrier_reuse_review']['observations']};obs=pd.read_parquet(B/'applied_state_observations.parquet');g=obs[obs.root.isin(roots)].copy();assert len(g)==21
points=pd.read_parquet(B/'applied_point_snapshot.parquet',filters=[('source_record_id','in',g.source_record_id.tolist())]);by={r['source_record_id']:r for r in points.to_dict('records')};targetids=set(g.source_record_id)-set(by);assert len(targetids)==12
accepted=[];held=[];refs=[];admittedroots=set();pins={}
for root,h in g.groupby('root'):
 assert set(h.census_year)=={2002,2010,2021} and h.census_year.is_unique
 current=h[h.census_year.eq(2021)].iloc[0];carrier=by[current.source_record_id];assert carrier['coordinate_admission_status'] in ['reviewed_rule_accepted','reviewed_extension_rule_accepted'];assert carrier['point_origin_file'] and carrier['point_origin_sha256'] and carrier['coordinate_source_record_id']
 contradictions=[{'source_record_id':sid,'distance_km':dist(carrier,pt),'historical_coordinate_source_record_id':pt['coordinate_source_record_id']} for sid,pt in by.items() if sid in set(h.source_record_id) and dist(carrier,pt)>5]
 if contradictions:
  held.append({'component_root':root,'current_carrier':current.source_record_id,'reason':'accepted independent historical point contradicts current carrier >5km; no supersession authorized','contradictions':contradictions,'potential_population_by_year':{str(int(y)):int(v.population.sum()) for y,v in h.groupby('census_year')}});continue
 admittedroots.add(root)
 for _,native in h[h.source_record_id.isin(targetids)].iterrows():
  row={k:v for k,v in carrier.items() if v!='' and k not in ['source_record_id','point_ledger_path','target_source_record_id','integration_input_path','integration_packet_kind']};row.update(target_source_record_id=native.source_record_id,latitude=float(carrier['latitude']),longitude=float(carrier['longitude']),coordinate_admission_status='reviewed_extension_rule_accepted',historical_census_coordinate_asserted=False,external_provider_ID_binding_asserted=False,point_use_inference='retrospective representative own-point reuse through existing accepted stable three-year identity; not census-day measurement',coordinate_binding_rule='Existing accepted three-year same-place UF; admitted current own physical locality carrier; target lacks accepted ownpoint; no existing historical accepted point >5km; no new identity edge or provider identifier transfer',current_carrier_source_record_id=current.source_record_id,accepted_current_carrier_ledger=carrier['point_ledger_path'],actual_baseline_component_root=root,earlier_point_use_known=True,earlier_point_used_retrospectively=True,source_population_value_preserved=True,asserted_target_census_year=int(native.census_year));accepted.append(row)
  refs.append({'target_source_record_id':native.source_record_id,'current_carrier_source_record_id':current.source_record_id,'component_root':root,'target_year':int(native.census_year),'target_native_name':native.settlement_name,'target_population':int(native.population),'coordinate_source_record_id':carrier['coordinate_source_record_id'],'latitude':float(carrier['latitude']),'longitude':float(carrier['longitude']),'point_origin_file':carrier['point_origin_file'],'point_origin_sha256':carrier['point_origin_sha256'],'point_origin_locator':carrier['point_origin_locator'],'current_carrier_ledger':carrier['point_ledger_path'],'source_grade_preserved':native.population_value_quality})
 for path,expected in [(carrier['point_origin_file'],carrier['point_origin_sha256'])]:
  if path not in pins:pins[path]={'sha256':sha(path),'bytes':Path(path).stat().st_size}
  assert pins[path]['sha256']==expected
# Exact historical occupancy guard on authoritative active point keys, without loading wide metadata.
minimal=pd.read_parquet(B/'applied_point_snapshot.parquet',columns=['source_record_id','latitude','longitude']);minimal=minimal.merge(obs[['source_record_id','root','census_year']],on='source_record_id',validate='one_to_one');occupancy={}
for r in minimal.itertuples(index=False):occupancy.setdefault((int(r.census_year),float(r.latitude),float(r.longitude)),set()).add(r.root)
for row in accepted:assert not(occupancy.get((row['asserted_target_census_year'],row['latitude'],row['longitude']),set())-{row['actual_baseline_component_root']}),'existing sameyear active ownpoint occupied by distinct component'
assert len(accepted)==10 and len(admittedroots)==5 and len(held)==2
pd.DataFrame(accepted).to_csv(O/'accepted_point_use_delta.csv.gz',index=False,compression={'method':'gzip','mtime':0});pd.DataFrame(refs).to_csv(O/'accepted_source_bound_current_carrier_references.csv.gz',index=False,compression={'method':'gzip','mtime':0});(O/'held_existing_historical_point_contradictions.json').write_text(json.dumps(held,ensure_ascii=False,indent=2)+'\n');g.to_csv(O/'reviewed_seven_existing_components.csv.gz',index=False,compression={'method':'gzip','mtime':0})
for p in [B/'application_receipt.json',B/'applied_state_observations.parquet',B/'applied_component_snapshot.csv.gz',B/'applied_point_snapshot.parquet']:pins[str(p)]={'sha256':sha(p),'bytes':p.stat().st_size}
result={'status':'frozen_reviewed_existing_accepted_current_carrier_retrospective_uses_not_applied','baseline_stage':65,'intended_working_stage':66,'root_authorized_existing_stable_UF_reuse':True,'accepted_edges':0,'accepted_point_uses':10,'existing_accepted_components':5,'held_components':2,'point_replacements':0,'no_historical_accepted_point_erased':True,'State_loads':0,'API_applications':0,'new_downloads':0,'native_population_source_quality_codes_and_UF_unchanged':True,'conditional_complete_component_native_population_gain':{str(int(y)):int(h.population.sum()) for y,h in g[g.root.isin(admittedroots)].groupby('census_year')},'source_grade_policy':'Retain exact original native source grade/value; modern ownpoint reuse is explicit inference, no historical provider ID binding asserted','input_pins':pins,'output_pins':{p.name:{'sha256':sha(p),'bytes':p.stat().st_size} for p in O.iterdir() if p.is_file() and p.name not in ['admission_receipt.json','FINAL_manifest.json']}}
(O/'admission_receipt.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n');manifest={'status':'immutable_packet_reviewed_not_applied','files':{p.name:{'sha256':sha(p),'bytes':p.stat().st_size} for p in O.iterdir() if p.is_file() and p.name!='FINAL_manifest.json'}};(O/'FINAL_manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'receipt_sha256':sha(O/'admission_receipt.json'),'accepted_point_uses':10,'held_components':2,'conditional_gain':result['conditional_complete_component_native_population_gain']},ensure_ascii=False))
