from pathlib import Path
import sys,json,hashlib,time,math
import pandas as pd
O=Path(__file__).parent;E=O.parent;ROOT=E.parents[1];C=E/'native_from_secondary_census_binding_20261007';A=E/'wikidata_secondary_full3_expansion_application_20261007';sys.path.insert(0,str(ROOT/'research_rebuild/mass_linkage'))
from working_state_20261007 import load,PARTITION_MEMBERS
from current_chain_state_20261007 import sha,distance_km
T=time.monotonic();s=load(21);cand=pd.read_csv(C/'strong_uncredited_existing_component_native_IDs.csv').fillna('');base=pd.read_csv(A/'accepted_qualified_physical_observations.csv').fillna('');assert len(cand)==201 and cand.history_year.eq(2002).sum()==79 and cand.history_year.eq(2010).sum()==122
credited={sid for sid in s.point_rows if s.years[s.uf.find(sid)]=={2002,2010,2021}};inputpaths=[PARTITION_MEMBERS,E/'wikidata_secondary_full3_application_20261007/preapplication_qualified_credit_ids_frozen.csv',E/'wikidata_secondary_full3_application_20261007/accepted_qualified_physical_observations.csv',E/'current_unpointed_own_wiki_mass_application_20261007/accepted_qualified_physical_observations.csv',E/'existing_event_scope_application_20261007/accepted_selected_source_id_credit_union.csv',A/'accepted_current_source_id_credit_union.csv']+[E/d/'accepted_constituent_credit_union.csv' for d in ['named_urban_merger_application_20261007','next_named_urban_merger_application_20261007','further_urban_merger_application_20261007']]
for p in inputpaths:
 d=pd.read_csv(p,dtype=str).fillna('')
 for col in d.columns:
  if 'source_record_id'in col:credited.update(d[col])
rows=[];alt=[];holds=[];credit=[];sourcepins={};rawpaths=set()
for t in cand.itertuples():
 sid=t.old_native_source_record_id;cur=t.current_native_source_record_id;old=s.by_id.loc[sid];current=s.by_id.loc[cur];root=s.uf.find(cur);assert s.uf.find(sid)==root;assert old.census_year==t.history_year;assert bool(old.is_additive_settlement_record);assert pd.notna(old.population);assert float(old.population)==float(t.native_old_population);donor=s.point_rows[cur]
 members=s.obs[s.obs.root.eq(root)];pts=[(r.source_record_id,s.point_rows[r.source_record_id]) for r in members.itertuples() if r.source_record_id in s.point_rows];maximum=0
 for i,(_,p) in enumerate(pts):
  for _,q in pts[i+1:]:maximum=max(maximum,distance_km((p['latitude'],p['longitude']),(q['latitude'],q['longitude'])))
 if maximum>5 or any(sid in s.conflicting_point_targets for sid,_ in pts):holds.append({'old_native_source_record_id':sid,'current_native_source_record_id':cur,'year':t.history_year,'hold_reason':'component_point_disagreement_over5km_or_hard_conflict','max_component_point_distance_km':maximum});continue
 original=base[(base.wikidata_id==t.wikidata_id)&(base.year==t.history_year)];assert len(original)==1 and original.nonadditive_observation.iloc[0] and not original.source_record_id.iloc[0];r=original.iloc[0].to_dict();secondary=float(r['population_source_value']);r.update({'source_record_id':sid,'population_source_value':float(old.population),'population_quality':old.population_value_quality,'grain':'existing selected native census own-NP observation in accepted same-place component','nonadditive_observation':False,'settlement_name':old.settlement_name,'county_context':old.district_raw,'source_path':'/workspace/settlements-raw/'+str(old.source_file),'source_sha256':'' if pd.isna(old.source_sha256) else str(old.source_sha256),'source_locator':'selected own census source_record_id='+sid,'selected_source_sha256_as_loaded':'' if pd.isna(old.source_sha256) else str(old.source_sha256),'decision_status':'qualified_accepted_native_history_existing_component_binding','historical_native_selected_source_ID_binding_asserted':True,'population_primary_reference_verified':False,'latitude':float(donor['latitude']),'longitude':float(donor['longitude']),'point_binding_json':json.dumps(donor,ensure_ascii=False),'point_origin_file':donor.get('point_origin_file',''),'point_origin_sha256':donor.get('point_origin_sha256',''),'point_origin_locator':donor.get('point_origin_locator',''),'retrospective_point_use_is_continuity_inference':True,'selected_credit_previously_present':sid in credited,'bound_current_native_source_record_id':cur,'native_source_context_json':json.dumps({'source_record_id':sid,'name':old.settlement_name,'type':old.settlement_type,'region':old.region_norm,'printed_county':old.district_raw,'population_scope':None if pd.isna(old.population_scope) else old.population_scope,'population_quality':old.population_value_quality,'source_file':old.source_file,'source_sha256_as_loaded':None if pd.isna(old.source_sha256) else old.source_sha256,'source_locator_as_loaded':None if pd.isna(old.source_locator) else old.source_locator},ensure_ascii=False),'binding_basis':'already_accepted_same_place_component_to_own_current_native_NP; all accepted component points agree≤5km','native_population_scope_missing_legacy_flag':pd.isna(old.population_scope),'native_scope_grade':'legacy_scope_detail_missing_explicit; additive_typed_own_NP_in_accepted_component' if pd.isna(old.population_scope) else 'native_own_NP_source_scope_retained','secondary_population_alternative':secondary,'native_minus_secondary_population':float(old.population)-secondary,'population_difference_flag':float(old.population)!=secondary,'max_component_point_distance_km':maximum,'historical_point_direct_measurement_asserted':False,'ordinary_graph_modified':False,'ordinary_point_ledger_modified':False,'native_census_date_assignment':'existing selected native census-year row; exact secondary declared precision retained separately; no new date inference','native_code_querylog_unknown_flag':True})
 # Secondary corroboration is namespaced; it never claims the native protected value.
 for k in ['statement_id','census_proof_class','census_reference_titles_json','P248_ids_json','P248_labels_json','P459_method_ids_json','reference_urls_json','declared_date','date_precision']:
  r['secondary_original_'+k]=r.get(k,'')
 r['statement_id']='';r['census_proof_class']='existing_selected_native_census_row_in_accepted_own_NP_component'
 for k in ['census_reference_titles_json','P248_ids_json','P248_labels_json','P459_method_ids_json','reference_urls_json']:r[k]='[]'
 r['declared_date']='+'+str(int(old.census_year))+'-00-00T00:00:00Z';r['date_precision']=9
 sourcepath=Path(r['source_path'])
 if sourcepath.exists():rawpaths.add(sourcepath);r['native_raw_file_sha256_checked']=sha(sourcepath)
 else:r['native_raw_file_sha256_checked']='';r['native_raw_file_unavailable_grade_flag']=True
 a=original.iloc[0].to_dict();a.update({'secondary_alternative_retained_nonadditive':True,'preferred_native_source_record_id':sid,'preferred_native_population':float(old.population),'preferred_native_population_quality':old.population_value_quality,'native_minus_secondary_population':float(old.population)-secondary,'population_difference_flag':float(old.population)!=secondary,'ordinary_NP3_asserted':False});alt.append(a);rows.append(r);credit.append({'source_record_id':sid,'year':int(old.census_year),'source_population':float(old.population),'trajectory_id':r['trajectory_id'],'scope':r['scope'],'bound_current_native_source_record_id':cur,'already_credited_latest21_union':sid in credited,'net_new_selected_ID_credit':sid not in credited,'population_quality':old.population_value_quality})
f=pd.DataFrame(rows);al=pd.DataFrame(alt);cr=pd.DataFrame(credit);assert not f[['trajectory_id','year']].duplicated().any();assert not f.nonadditive_observation.any();assert al.nonadditive_observation.all() and al.source_record_id.eq('').all();f.to_csv(O/'accepted_qualified_historical_replacements.csv',index=False);al.to_csv(O/'retained_secondary_historical_alternatives.csv',index=False);cr.to_csv(O/'accepted_native_source_id_credit_union.csv',index=False);pd.DataFrame(holds).to_csv(O/'component_point_conflict_holds.csv',index=False)
# A bounded final source/context check; no per-locality legal dossiers.
fixed=set(f.assign(k=f.source_record_id.map(lambda q:hashlib.sha256(('native-history-fixed15-20261007'+q).encode()).hexdigest())).sort_values('k').head(15).source_record_id);largest=set(f.sort_values('population_source_value',ascending=False).head(5).source_record_id);checks=[]
for r in f[f.source_record_id.isin(fixed|largest)].itertuples():
 checks.append({'source_record_id':r.source_record_id,'year':r.year,'name':r.settlement_name,'largest5':r.source_record_id in largest,'fixed15':r.source_record_id in fixed,'native_population':r.population_source_value,'protected_quality_preserved':r.population_quality,'secondary_alternative_population':r.secondary_population_alternative,'population_difference_flag':r.population_difference_flag,'existing_accepted_component_binding':True,'native_source_context_json':r.native_source_context_json,'native_raw_file_sha256_checked':r.native_raw_file_sha256_checked,'source_locator':r.source_locator,'component_points_max_distance_km':r.max_component_point_distance_km,'point_rule':'current representative own point; retrospective continuity inference only','status':'native_selected_count_quality_component_source_context_verified'})
pd.DataFrame(checks).to_csv(O/'fixed15_and_largest5_source_checks.csv',index=False)
for p in dict.fromkeys(s.inputs+inputpaths+[C/'strong_uncredited_existing_component_native_IDs.csv',C/'native_history_binding_candidates.csv',A/'accepted_qualified_physical_observations.csv',ROOT/'research_rebuild/mass_linkage/working_state_20261007.py',Path(__file__)]+list(rawpaths)):sourcepins[str(p)]={'sha256':sha(p),'bytes':p.stat().st_size}
net={}
for y,g in cr.groupby('year'):d=g[g.net_new_selected_ID_credit].drop_duplicates('source_record_id');net[str(int(y))]={'rows':len(d),'population':int(d.source_population.sum())}
receipt={'status':'applied_native_history_qualified_sidecar_accepted_component_binding','baseline_stage':21,'replaces_packet':str(A/'accepted_qualified_physical_observations.csv'),'historical_replacements':len(f),'retained_nonadditive_secondary_alternatives':len(al),'qualified_native_year_rows_additive_for_selected_ID_union_only':True,'net_selected_source_id_credit_by_year':net,'component_point_conflict_holds':holds,'population_difference_rows':int(f.population_difference_flag.sum()),'native_source_scope_missing_legacy_flag_rows':int(f.native_population_scope_missing_legacy_flag.sum()),'all_native_counts_and_protected_quality_preserved':True,'no_new_identity_edges':True,'ordinary_point_ledger_modified':False,'historical_direct_point_measurement_asserted':False,'point_rule':'accepted current own representative point with retrospective continuity inference; all existing component points≤5km and no hard conflict','sourcecode_P625_querylog_unknowns':'explicit flags; not gate on already-bound native identity','fixed15_checks':len(fixed),'largest5_checks':len(largest),'boundary_comparability':'UNKNOWN','error_rate':'uncalibrated','inputs':sourcepins,'outputs':{p.name:sha(p) for p in [O/'accepted_qualified_historical_replacements.csv',O/'retained_secondary_historical_alternatives.csv',O/'accepted_native_source_id_credit_union.csv',O/'fixed15_and_largest5_source_checks.csv']},'wall_seconds':time.monotonic()-T}
tmp=O/'application_receipt.tmp';tmp.write_text(json.dumps(receipt,indent=2,ensure_ascii=False));tmp.replace(O/'application_receipt.json');print(json.dumps({k:v for k,v in receipt.items() if k not in ['inputs','outputs']},ensure_ascii=False))
