from pathlib import Path
import pandas as pd,json,hashlib,gzip,xlrd,math
z=Path(__file__).parent.resolve();base=z.parent/'main_axis_residual_application68_20261008';r=pd.read_parquet(base/'applied_state_observations.parquet');p=pd.read_parquet(base/'applied_point_snapshot.parquet').set_index('target_source_record_id');sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();k='2002:1_TOM_01_04.xls:0:8229';c='2021:data_allsettlements_anon_156_v20251217.parquet:parquet:598';v=r[r.source_record_id==k].iloc[0];cur=r[r.source_record_id==c].iloc[0];ctx=r[r.root==cur.root];assert set(ctx.census_year)=={2010,2021} and len(ctx)==2;assert ctx[ctx.census_year==2010].iloc[0].source_record_id.endswith('Sib:10769');donor=p.loc[c].to_dict();rawfile=Path('/workspace/settlements-raw/data/interim/2021_tochno/data_allsettlements_anon_156_v20251217.parquet');raw=pd.read_parquet(rawfile).iloc[597];norm=lambda x:str(x).split('.')[0];assert norm(raw.oktmo)==norm(raw.oktmo_dadata)=='81621401101';assert norm(raw.okato_dadata)=='81221801001' and raw.fias_level_dadata=='6' and raw.object_level=='Населенный пункт' and raw.settlement_type_full_dadata=='село';assert sha(donor['point_origin_file'])==donor['point_origin_sha256'];assert float(donor['latitude'])==raw.latitude_dadata and float(donor['longitude'])==raw.longitude_dadata
wiki=z/'own_bayangol_articles.json.gz';pg=next(x for x in json.load(gzip.open(wiki))['query']['pages'].values()if x['title']=='Баянгол (Закаменский район)');text=pg['revisions'][0]['slots']['main']['*'];assert '81221801001'in text and '2003'in text;geo={'lat':50+41/60+58/3600,'lon':103+28/60+17/3600};distance=6371*2*math.asin(math.sqrt(math.sin(math.radians(raw.latitude_dadata-geo['lat'])/2)**2+math.cos(math.radians(raw.latitude_dadata))*math.cos(math.radians(geo['lat']))*math.sin(math.radians(raw.longitude_dadata-geo['lon'])/2)**2));assert distance<1
urban=Path('/workspace/settlements-raw/data/raw/2002_official_tom1/1_TOM_01_04.xls');s=xlrd.open_workbook(urban).sheet_by_index(0);source=[]
for i in range(8225,8232):source.append(dict(year=2002,path=str(urban),sha256=sha(urban),source_locator=f'sheetindex0:physicalrow{i+1}',literal=json.dumps(s.row_values(i),ensure_ascii=False)))
y=ctx[ctx.census_year==2010].iloc[0];pf=Path('/workspace/settlements-raw')/y.source_file;s=xlrd.open_workbook(pf).sheet_by_name('Sib');source.append(dict(year=2010,path=str(pf),sha256=sha(pf),source_locator='Sib:physicalrow10769',literal=json.dumps(s.row_values(10768)[:8],ensure_ascii=False)));pd.DataFrame(source).to_csv(z/'literal_primary_source_witnesses.csv',index=False)
proof=dict(old_source_id=k,proper2002='PGTБаянгол1459 underprintedЗакаменский',modern2010_source_id=y.source_record_id,modern2021_source_id=c,typed_change='PGT1949–2003→samephysicalSelo; ownarticle only year precision; noformation/merger/relocation asserted',native_type_fields_preserved=True,own_wikipedia_file=str(wiki),own_wikipedia_sha256=sha(wiki),own_wikipedia_locator=f"page{pg['pageid']}:revision{pg['revisions'][0]['revid']}",own_wikipedia_literal=text,own_article_point=geo,own_OKATO='81221801001',actual_raw_current_properties=raw.to_dict(),raw_current_file=str(rawfile),raw_current_sha256=sha(rawfile),raw_current_locator='parquet_row_1based=598',current_donor_point=donor,donor_snapshot_file=str(base/'applied_point_snapshot.parquet'),donor_snapshot_sha256=sha(base/'applied_point_snapshot.parquet'),article_current_point_distance_km=distance,all_Buryatia_same_name_type_rivals=r[(r.region_norm=='бурятия')&r.settlement_name.str.contains('Баянгол',case=False)].to_dict('records'))
(z/'own_identity_point_proof.json').write_text(json.dumps(proof,ensure_ascii=False,indent=2,default=str));pd.DataFrame([dict(decision_id='EAST_BAYANGOL_PGT2002_OWNZAKAMENSKY',relation='same_place',from_source_record_id=k,to_source_record_id=c,from_year=2002,to_year=2021,decision_status='checked_rule_accepted',decision_class='primary_printed_owncounty_and_article_urban_to_rural_status',decision_rule='primaryurban2002 printedЗакаменскийPGT +typedownarticlePGT1949–2003→samephysicalSelo + exactnativecurrentOKTMO/Dadata/ownarticleOKATO; distinctБаргузинскийулусrival excluded',evidence_uri=str(z/'own_identity_point_proof.json'),population_scope_interpretation='nativecountquality/type unchanged; populationboundarycomparabilityUNKNOWN')]).to_csv(z/'accepted_identity_edge_delta.csv',index=False)
point=[]
for _,n in pd.concat([pd.DataFrame([v.to_dict()]),ctx]).iterrows():
 if n.source_record_id in p.index:continue
 a=dict(donor);a.update(target_source_record_id=n.source_record_id,coordinate_admission_status='reviewed_rule_accepted',coordinate_source_record_id=c,point_ledger_path=str(z/'accepted_point_use_delta.csv.gz'),own_locality_point=True,donor_target_source_record_id=c,coordinate_origin_ledger=donor['point_ledger_path'],coordinate_origin_ledger_sha256=sha(donor['point_ledger_path']),coordinate_origin_ledger_locator=c,admission_rule='exact sourcebound samephysicalБаянголЗакаменский PGT→Selo verified owncurrentcodedNPpoint; retrospectivecontinuity',direct_historical_coordinate_measurement=False,coordinate_temporal_interpretation='modernOWNrepresentative physicalNP inferredretrospectively; historicalmeasurement/censusday/boundariesUNKNOWN',source_binding_proof=str(z/'own_identity_point_proof.json'),provider_binding_asserted=True,native_population_quality_unchanged=True);point.append(a)
pd.DataFrame(point).to_csv(z/'accepted_point_use_delta.csv.gz',index=False);credits=[]
for _,n in pd.concat([pd.DataFrame([v.to_dict()]),ctx]).iterrows():credits.append(dict(source_record_id=n.source_record_id,census_year=int(n.census_year),settlement_name=n.settlement_name,native_population=n.population,population_value_quality=n.population_value_quality,scope_id='east_bayangol_zakamensky_stablephysical3',source_identity_rule='PGT_to_selo_status_change_same_physical_place',own_point=True,latitude=donor['latitude'],longitude=donor['longitude'],point_json=json.dumps(donor,ensure_ascii=False),point_input_snapshot_sha256=sha(base/'applied_point_snapshot.parquet'),native_source_counts_quality_unchanged=True,actual_handoff_UID=n.source_record_id==k,source_boundary_comparability='UNKNOWN'))
pd.DataFrame(credits).to_csv(z/'accepted_native_UID_credits.csv',index=False)
B=z.parent/'over1000_rest_B_20261009/version28_dormidontovka_pgt_three_year_chain';receipt=json.loads((B/'review_receipt.json').read_text());assert receipt['application_approved']
for fn,pin in receipt['output_pins'].items():assert sha(B/fn)==pin['sha256']
assigned=pd.read_csv(z.parent/'over1000_root_20261009/handoff_five_agent_regional269_roster.csv');D=[]
for _,n in assigned.iterrows():D.append(dict(source_record_id=n.source_record_id,census_year=int(n.census_year),native_population=n.population,status='reused_frozen_Bv28_ordinary3_sourcebound_owncurrentpoint' if n.settlement_name=='Дормидонтовка' else 'new_sourcebound_ordinary3_Bayangol_PGT_to_selo',packet=str(B)if n.settlement_name=='Дормидонтовка' else str(z),native_counts_quality_unchanged=True))
pd.DataFrame(D).to_csv(z/'all4_handoff_UID_dispositions.csv',index=False);(z/'verification_receipt.json').write_text(json.dumps(dict(status='FROZEN_COMPLETE_4_HANDOFF_UIDS',new_identity_edges=1,new_missing_point_uses=len(point),new_Bayangol_actual_native3_population=[1459,1118,968],handoff_assigned_UIDs=4,reusedDormiUIDs=3,reused_v28_outputs_hashes_verified=True,ordinary3only_noavailableunknownscope=True,newsourceID_count=0,sourcecountquality_changes=0,point_accuracy='modernOWNrepresentative explicit retrospective continuity;censusdayUNKNOWN',full_rivals_checked=True,noState_load=True,root_actual_application_pending=True,article_current_owncoded_point_distance_km=distance),indent=2));(z/'manifest.json').write_text(json.dumps({f.name:dict(sha256=sha(f),bytes=f.stat().st_size)for f in z.iterdir()if f.name!='manifest.json'},indent=2));print(sha(z/'manifest.json'),len(point))
