from pathlib import Path
import pandas as pd,json,hashlib,xlrd,xml.etree.ElementTree as ET,math
Z=Path(__file__).parent;E=Z.parent.parent;A=E/'main_axis_residual_application68_20261008';sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();ids=['2002:040_95a4475637_02c_Rostov_obl.xls:Sheet1:33','2010:004_486e984bdc_12._20Астр_Волгог_Ростов.xls:Южный:2946','2021:data_allsettlements_anon_156_v20251217.parquet:parquet:109835'];o=pd.read_parquet(A/'applied_state_observations.parquet').set_index('source_record_id',drop=False);p=pd.read_parquet(A/'applied_point_snapshot.parquet').set_index('target_source_record_id',drop=False);mm=o[o.root.isin(o.loc[ids,'root'])];assert len(mm)==3 and set(mm.census_year)=={2002,2010,2021};donor=p.loc[ids[-1]].to_dict();lat,lon=float(donor['latitude']),float(donor['longitude']);ef=Z/'own_Dolotinsky_point_entity.json';e=json.loads(ef.read_text())['entities']['Q4349340'];val=lambda k:[c['mainsnak'].get('datavalue',{}).get('value') for c in e['claims'].get(k,[])];assert val('P764')==['60626420121'];assert any(c['mainsnak']['datavalue']['value']['amount']=='+1291' and c.get('qualifiers',{}).get('P585',[{}])[0].get('datavalue',{}).get('value',{}).get('time','').startswith('+2002') for c in e['claims']['P1082']);xroot=ET.parse(Z/'OSM_exact_GN_point_area.xml').getroot();node=next(x for x in xroot.findall('node') if x.get('id')=='1334494130');tags={t.get('k'):t.get('v') for t in node.findall('tag')};assert tags['place']=='village' and tags['official_status']=='ru:посёлок' and tags['okato:user']=='60226820005' and tags['wikidata']=='Q4349340';assert abs(float(node.get('lat'))-lat)<0.002 and abs(float(node.get('lon'))-lon)<0.002
rawfile=Path('/workspace/settlements-raw/data/interim/2021_tochno/data_allsettlements_anon_156_v20251217.parquet');raw=pd.read_parquet(rawfile);r=raw.iloc[109834];assert str(r.oktmo)==str(r.oktmo_dadata)=='60626420121' and str(r.fias_level_dadata)=='6';assert r.object_level=='Населенный пункт' and r.settlement_dadata=='Первомайский' and r.mun_lower=='Долотинское сельское поселение';assert (raw.object_level.eq('Населенный пункт')&raw.oktmo.eq('60626420121')).sum()==1
cols=['object_level','object_name','oktmo','region','mun_upper','mun_lower','population','settlement_dadata','settlement_type_full_dadata','fias_level_dadata','fias_id_dadata','oktmo_dadata','okato_dadata','latitude_dadata','longitude_dadata'];d=raw[raw.object_level.eq('Населенный пункт')&raw.region.eq('Ростовская область')&raw.object_name.str.contains('Первомай',na=False)][cols].copy();d['native_source_row_1based']=d.index+1;d.to_json(Z/'all_current_native_typed_name_rivals_raw.json',orient='records',force_ascii=False);o[o.region_norm.eq('ростовская')&o.settlement_name.str.contains('Первомай',na=False)].reset_index(drop=True).to_csv(Z/'all_native2002_2010_2021_typed_name_rivals.csv.gz',index=False,compression={'method':'gzip','mtime':0})
sourcew=[]
for i in ids[:2]:
 x=o.loc[i];f=Path('/workspace/settlements-raw')/x.source_file;parts=i.split(':');row=int(parts[-1]);s=xlrd.open_workbook(f).sheet_by_name(parts[-2]);sourcew.append(dict(source_record_id=i,source_file=str(f),source_sha256=sha(f),sheet=s.name,row_1based=row,literal_cells_json=json.dumps(s.row_values(row-1),ensure_ascii=False),native_population=x.population,native_population_quality=x.population_value_quality,source_row_context_json=json.dumps([dict(row_1based=j+1,cells=s.row_values(j)) for j in range(max(0,row-12),min(s.nrows,row+6))],ensure_ascii=False),native_county_raw=x.district_raw,source_printed_old_city_context='Сельские населенные пункты, подчиненные администрации г.Зверево' if x.census_year==2002 else 'Красносулинский'))
pd.DataFrame(sourcew).to_csv(Z/'literal_native_primary_source_rows.csv',index=False)
sql=Path('/workspace/settlements-raw/data/raw/historical_classifiers/okato_142_2009/dump-142_2009.sql');lit=[]
with sql.open() as f:
 for n,line in enumerate(f,1):
  if line.startswith('60226820005\t') or line.startswith('604180') or (line.startswith('60') and 'Первомайский' in line):lit.append(dict(source_file=str(sql),source_sha256=sha(sql),line_1based=n,literal_line=line.rstrip()))
pd.DataFrame(lit).to_csv(Z/'classifier2009_owncode_and_all_regional_name_rivals.csv',index=False)
gj=json.loads((Z.parent/'own_Geo2011_name_rivals_raw.json').read_text());gr=[x for x in gj if x['TER']=='60' and (x['TER']+x['KOD1']+x['KOD2']+x['KOD3']=='60226820005')];assert len(gr)==1;(Z/'Geo2011_owncode_raw_witness.json').write_text(json.dumps({'source_file':'/workspace/settlements-raw/data/raw/historical_geography/geokladr_okato_2011/okato.dbf','source_sha256':'d1c8b983f2489724a940bd2a64dedda73b602f6c491d5c09391deaf362fe2650','rows':gr,'role':'own literal classifier code/name/type support only; Geo coordinate not accuracy guarantee'},ensure_ascii=False,indent=2))
basis='own physical Q4349340 exactcurrentpublishedP76460626420121 + OWNdated2002census1291withrefs; literal2002properposelok subordinateZverevo, literal2010properposelok Krasnosulinsky, sameproperNP type/name; independent OSMown60226820005 physicalvillage+historic2009/2011 owncode and exactfullraw2021 Dadata code/name/type/FIAS6 currentDolotinsky parish. Sourceadministrativeparenting changed; exactdate/boundarycomparability UNKNOWN. No population equality or proximity alone.'
edges=[dict(decision_id='SOUTH-PERV-'+hashlib.sha256((i+ids[-1]).encode()).hexdigest()[:20],relation='same_place',from_source_record_id=i,to_source_record_id=ids[-1],from_year=int(o.loc[i,'census_year']),to_year=2021,decision_status='checked_rule_accepted',decision_class='own_coded_physical_place_dated_prior_census_and_literal_native_sources',decision_rule=basis,evidence_uri=str(Z/'own_physical_identity_witness.json'),population_scope_interpretation='identity only; native populationquality unchanged; boundarycomparability UNKNOWN') for i in ids[:2]]
pd.DataFrame(edges).to_csv(Z/'accepted_identity_edge_delta.csv.gz',index=False,compression={'method':'gzip','mtime':0});points=[]
for i in ids[:2]:
 assert i not in p.index
 rec=donor.copy();rec.update(target_source_record_id=i,coordinate_admission_status='reviewed_extension_rule_accepted',donor_target_source_record_id=ids[-1],donor_point_snapshot_sha256=sha(A/'applied_point_snapshot.parquet'),donor_active_point_ledger_sha256=sha(donor['point_ledger_path']),admission_rule='own source-positive stable physical NP continuity, modernOWNcodedrepresentative point retrospectively reused; historicalmeasurement/date/boundaries UNKNOWN',coordinate_provenance='explicit retrospective own physical NP continuity inference');points.append(rec)
pd.DataFrame(points).to_csv(Z/'accepted_point_use_delta.csv.gz',index=False,compression={'method':'gzip','mtime':0})
witness=dict(identity_basis=basis,old_published_source_ids=ids[:2],current_native_source_record_id=ids[-1],qid='Q4349340',wikidata_raw_source_file=str(ef),wikidata_raw_sha256=sha(ef),all_published_census_P1082_claims=e['claims']['P1082'],own_QP764_literal=val('P764'),own_QP31_literal=val('P31'),own_QP131_literal=val('P131'),own_QP625_literal=val('P625'),OSM_source_file=str(Z/'OSM_exact_GN_point_area.xml'),OSM_source_sha256=sha(Z/'OSM_exact_GN_point_area.xml'),OSM_own_physical_node_id=node.get('id'),OSM_node_version=node.get('version'),OSM_node_timestamp=node.get('timestamp'),OSM_own_physical_tags=tags,GN_candidate7439531_resolved_to_coded_Dolotinsky_OWNNP=True,alternative_GN11765007_distinct_other_native_hutor=True,current_native_code='60626420121',current_own_native_provider_code='60626420121',current_native_NPtype='посёлок',current_parish='Долотинское сельское поселение',current_provider_name=r.settlement_dadata,current_provider_FIASlevel='6',current_provider_FIASid=r.fias_id_dadata,current_raw_file=str(rawfile),current_raw_sha256=sha(rawfile),current_raw_row_1based=109835,current_accepted_point=donor,administrative_parent_change='2002publishedZverevo subordinate →2009classifier Krasnosulinsky/Dolotinsky; dateUNKNOWN, not physical relocation',census2002_population1291_corrob_only=True,native2010_population923_preserved_despite_Wiki922=True,all_native_count_quality_unchanged=True,child_counts_or_receiver_counts_assigned=False,known_merger_or_physical_relocation_asserted=False);(Z/'own_physical_identity_witness.json').write_text(json.dumps(witness,ensure_ascii=False,indent=2))
remain=set(pd.read_csv(A/'applied_remaining_primary.csv.gz',usecols=['source_record_id']).source_record_id);assert set(ids)<=remain;pd.DataFrame([dict(source_record_id=i,census_year=int(o.loc[i,'census_year']),population=o.loc[i,'population']) for i in ids]).to_csv(Z/'projected_incremental_native_finite_UID.csv',index=False)
receipt=dict(status='FROZEN_PENDING_ROOT_INDEPENDENT_REVIEW',baseline='actual68; V1+V2 disjoint with this specific final Pervomaysky group',source_count_quality_unchanged=True,new_identity_edges=2,new_point_uses=2,projected_finite_increment_population={'2002':1291,'2010':923,'2021':760},projected_native_UIDs_by_year={'2002':1,'2010':1,'2021':1},remaining_original_south58_unresolved_cohort_UIDs_after_V1V2_this=0,available_year_scope_not_needed_for_this_case=True,ceased_NP_or_inclusion_not_asserted=True,administrative_transfer_date='UNKNOWN',boundarycomparability='UNKNOWN',source_primary_quality_upgrade=False,no_State_core_Git_change=True,input_pins={str(f):{'sha256':sha(f),'bytes':f.stat().st_size} for f in [A/'applied_state_observations.parquet',A/'applied_point_snapshot.parquet',Z.parent/'manifest.json',Z.parent/'version2/manifest.json']});(Z/'application_receipt.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2))
for v in [Z.parent,Z.parent/'version2']:
 for fn,pin in json.loads((v/'manifest.json').read_text())['files'].items():assert sha(v/fn)==pin['sha256'],fn
assert sha(donor['point_origin_file'])==donor['point_origin_sha256'];(Z/'verification_receipt.json').write_text(json.dumps(dict(status='FROZEN_PENDING_ROOT_INDEPENDENT_REVIEW',priorV1V2manifest_bytes_unchanged=True,actual68three_singleton_native_component_members=True,point_origin_pin_passed=True,properNative_current_fullraw_code_NPtype_name_FIAS_and_unique_sourcecode=True,independent_OSMproperNP_code_tags_and_point_agreement=True,own_dated2002_count_claim_refs_captured=True,all_name_type_rivals_preserved=True,no_pop_equality_alone=True,modern_point_retro_continuity_explicit=True,administrative_parent_date_UNKNOWN=True),ensure_ascii=False,indent=2))
files={f.name:{'sha256':sha(f),'bytes':f.stat().st_size} for f in sorted(Z.iterdir()) if f.is_file() and f.name!='manifest.json'};(Z/'manifest.json').write_text(json.dumps({'status':'FROZEN','files':files},ensure_ascii=False,indent=2));print('FROZEN',sha(Z/'manifest.json'),'BYTES',sum(v['bytes'] for v in files.values()))
