import sys,json,re,math,importlib.util
from pathlib import Path
import pandas as pd,duckdb,xlrd
R=Path('/workspace/russian-settlements-research');sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from working_state_20261007 import load
from current_chain_state_20261007 import normalize,sha,distance_km
O=Path(__file__).parent
sp=importlib.util.spec_from_file_location('parent_app',O.parent/'apply.py');pa=importlib.util.module_from_spec(sp);sp.loader.exec_module(pa);s=pa.apply(load(27));before=s.metrics();assert before==json.loads((O.parent/'application_receipt.json').read_text())['after']
sp=importlib.util.spec_from_file_location('fm',R/'research_rebuild/evidence/large_native_suffix_and_former_name_application_20261008/apply.py');fm=importlib.util.module_from_spec(sp);sp.loader.exec_module(fm);bf=fm.finite_metrics(s)
bind=pd.read_csv(O/'bounded_context_bindings.csv',dtype=str,keep_default_na=False);hist=pd.read_csv(O/'bounded_historical_own_code_candidates.csv',dtype=str);meta=duckdb.connect().execute("select source_record_id,source_sheet,source_row,entity_grain_status from read_parquet('/workspace/settlements-delivery/continuation-consolidated-20261003/selected_observations.parquet')").fetchdf().set_index('source_record_id');edges=[];points=[];rejects=[];proof=[];comps=[];holds=[];pins={};books={}
rawtsv=Path('/workspace/settlements-raw/data/raw/wikimedia/wikidata_oktmo_entities.tsv');pins[str(rawtsv)]=sha(rawtsv);tsv={};qids={'Q4126586','Q15648683','Q16022411','Q3933954','Q4333103','Q23976583'}
for i,line in enumerate(rawtsv.open(),1):
 qs=re.findall(r'Q\d+',line.split('\t')[0]);q=qs[0] if qs else ''
 if q in qids:tsv.setdefault(q,[]).append({'line_1based':i,'literal':line.rstrip()})
(O/'positive_own_qid_raw_code_rows.json').write_text(json.dumps(tsv,ensure_ascii=False,indent=2))
for z in bind.to_dict('records'):
 case=z['case'];ids=[z['source2002'],z['source2010'],z['source2021']];a,b,n=[s.by_id.loc[x] for x in ids];sid10=ids[1]
 if case=='приупский тульская':holds.append({'case':case,'reason':'No independent two-sided native2010 source block binding recovered in bounded window; original source own-name/code remains candidate'});continue
 if case=='ревякино тульская':
  txt=(O/'revyakino_primary2010_p52.txt').read_text();assert 'Ясногорский район' in txt and 'Ревякино' in txt and '2970' in txt
 else:assert z['two_sided_current_county'] and z['two_sided_anchors']!='null',case
 assert n.source_record_id in s.point_rows;donor=s.point_rows[n.source_record_id];dp=(donor['latitude'],donor['longitude']);q=donor.get('coordinate_source_record_id','')
 if case in ['восточный свердловская','красногвардейский свердловская']:
  ownq='Q4126586' if case.startswith('восточный') else 'Q15648683';assert q==ownq;assert any(str(n.oktmo) in x['literal'] and n.settlement_name.replace('ё','е').lower() in x['literal'].replace('ё','е').lower() for x in tsv[ownq]);pins[donor['point_origin_file']]=sha(Path(donor['point_origin_file']))
  if case.startswith('восточный'):assert any('65238000001' in x['literal'] for x in tsv[ownq])
 # Revyakino current is independently code/name-bound to own Q3933954; urban2002/2010 versus rural current type is native printed source identity in Yasnogorsk.
 if case=='ревякино тульская':assert any(str(n.okato) in x['literal'] and 'Ясногорский' in x['literal'] for x in tsv['Q3933954'])
 for name in ['point_origin_file']:
  if donor.get(name):pins[donor[name]]=sha(Path(donor[name]))
 for x in [a,b,n]:
  assert x.is_additive_settlement_record and math.isfinite(x.population);assert x.source_record_id not in s.conflicting_point_targets
  if x.source_record_id in s.point_rows:assert distance_km(dp,(s.point_rows[x.source_record_id]['latitude'],s.point_rows[x.source_record_id]['longitude']))<=5
  path=Path('/workspace/settlements-raw')/x.source_file;pins[str(path)]=sha(path);mm=meta.loc[x.source_record_id];pr={'case':case,'source_record_id':x.source_record_id,'year':int(x.census_year),'source_path':str(path),'source_sha256':pins[str(path)],'source_sheet':mm.source_sheet,'source_row_1based':mm.source_row,'protected_population':x.population,'protected_quality':x.population_value_quality,'source_name':x.settlement_name,'source_type':x.settlement_type,'source_county':x.district_raw,'own_okato':x.okato,'own_oktmo':x.oktmo,'entity_grain_status':mm.entity_grain_status,'sourcepoint_donor':n.source_record_id}
  if path.suffix=='.xls':
   bk=books.setdefault(str(path),xlrd.open_workbook(path));sh=bk.sheet_by_name(str(mm.source_sheet)) if str(mm.source_sheet) in bk.sheet_names() else bk.sheet_by_index(int(mm.source_sheet));rv=sh.row_values(int(mm.source_row)-1);assert any(normalize(x.settlement_name) in normalize(v) for v in rv);pr['raw_original_row_json']=json.dumps(rv,ensure_ascii=False);pr['raw_protected_value_present']=any(str(v).strip()==str(int(x.population)) or (isinstance(v,(int,float)) and float(v)==x.population) for v in rv);assert pr['raw_protected_value_present']
  proof.append(pr)
 # Enumerate every same-name regional homonym. Nearby distinct objects may coexist; own codes/type/printed parent, never just proximity, select the donor.
 for _,peer in s.obs[s.obs.name_norm.eq(n.name_norm)&s.obs.region_norm.eq(n.region_norm)].iterrows():
  p=s.point_rows.get(peer.source_record_id);dd=distance_km(dp,(p['latitude'],p['longitude'])) if p else None;comps.append({'case':case,'source_record_id':peer.source_record_id,'year':peer.census_year,'name':peer.settlement_name,'type':peer.settlement_type,'county':peer.district_raw,'okato':peer.okato,'oktmo':peer.oktmo,'population':peer.population,'distance_km':dd,'within5km':dd is not None and dd<=5,'bound_triplet_member':peer.source_record_id in ids,'disambiguation':'Positive own code/name/type/source parent; nearby distinct village/station rows remain separate'})
 roots={s.uf.find(x) for x in ids};years=[y for r in roots for y in s.years[r]];assert len(years)==len(set(years)) and set(years)=={2002,2010,2021},case
 for target in ids[:-1]:
  if s.uf.find(target)!=s.uf.find(ids[-1]):edges.append({'from_source_record_id':target,'to_source_record_id':ids[-1],'relation':'same_place','decision_status':'checked_rule_accepted','case':case,'admission_rule':'Native own type/name/2002 printed parent and independent2010 accepted source block or primary printed county; current own-code/name/admin point; protected counts and grain preserved','source_binding_proof':'actual_raw_source_checks.csv;bounded_context_bindings.csv;independent_two_sided_county_anchors.csv;positive_own_qid_raw_code_rows.json','population_boundary_comparability_asserted':False,'municipal_event_date':'UNKNOWN'})
  if target not in s.point_rows:
   p=dict(donor);p.update(target_source_record_id=target,coordinate_admission_status='reviewed_extension_rule_accepted',case=case,coordinate_binding_rule='Independently admitted current own coded/name/admin point; native printed2002 parent and2010 source block bind own historical settlement; nearby homonyms compared',point_use_inference='modern_own_representative_point_on_source_bound_same_locality',population_boundary_comparability_asserted=False);points.append(p)
# Shafranovo: preserve receiving core identity despite explicitly known2005 annexation; reject only contradicted current Dadata point.
sgpath=R/'research_rebuild/evidence/remaining_large_current_component_point_conflicts_20261008/Shafranovo_receiving_core_source_grain_check.json';sg=json.loads(sgpath.read_text());pins[str(sgpath)]=sha(sgpath)
for p,h in sg['source_pins'].items():assert sha(Path(p))==h;pins[p]=h
ids=[sg['native2002_source_record_id'],sg['native2010_source_record_id'],'2021:data_allsettlements_anon_156_v20251217.parquet:parquet:144261'];assert [int(s.by_id.loc[x].population) for x in ids]==[2606,2362,1888];assert sg['same_receiving_core_NP_identity_survives_expansion'] and sg['boundary_change_known'];donor=s.point_rows[ids[1]];dp=(donor['latitude'],donor['longitude']);assert distance_km(dp,(53.983263,54.768152))<.001;old=s.point_rows[ids[2]];dist=distance_km(dp,(old['latitude'],old['longitude']));assert dist>5
rejects.append({'target_source_record_id':ids[2],'rejection_status':'reviewed_rejected_coordinate_claim_only','old_latitude':old['latitude'],'old_longitude':old['longitude'],'origin_ledger':old['point_ledger_path'],'origin_ledger_sha256':sha(Path(old['point_ledger_path'])),'reason':'Shafranovo native current Dadata point5.76km from independently same-own-code Geo2011 and ownWiki receivingcorepoint; historical core/source grain verified;2005 annexation retained as boundary flag','old_point_json':json.dumps(old,ensure_ascii=False),'provider_identifier_binding_status':'Own code correct; representative coordinate contradicted separately','candidate_only':False})
for target in [ids[0],ids[2]]:
 p=dict(donor);p.update(target_source_record_id=target,coordinate_admission_status='reviewed_extension_rule_accepted',case='шафраново receiving core',coordinate_binding_rule='Raw Geo2011 same own80202870001 name/type/current native code and ownWiki agree0.47km; native02/10/21 receivingcore source rows; known2005 annexation boundary flag',point_use_inference='modern_own_representative_point_on_receiving_core_identity',population_boundary_comparability_asserted=False,boundary_change_known=True,municipal_event_date='2005-07-20');points.append(p)
roots={s.uf.find(x) for x in ids};years=[y for r in roots for y in s.years[r]];assert len(years)==len(set(years)) and set(years)=={2002,2010,2021}
for target in ids[:-1]:
 if s.uf.find(target)!=s.uf.find(ids[-1]):edges.append({'from_source_record_id':target,'to_source_record_id':ids[-1],'relation':'same_place','decision_status':'checked_rule_accepted','case':'шафраново receiving core','admission_rule':'Native2002 typed own receivingcore and native2010/2021 samecode ownNP;2005 annexation does not erase receivingcore identity, boundarycomparability unasserted','source_binding_proof':str(sgpath),'population_boundary_comparability_asserted':False,'municipal_event_date':'2005-07-20','boundary_change_known':True})
for fn,f in [('accepted_identity_edge_delta.csv',edges),('accepted_point_use_delta.csv',points),('accepted_point_rejection_delta.csv',rejects),('actual_raw_source_checks.csv',proof),('all_nearby_homonym_comparison.csv',comps),('held_cases.csv',holds)]:pd.DataFrame(f).to_csv(O/fn,index=False)
s.reject_point_uses(O/'accepted_point_rejection_delta.csv');s.add_deltas([O/'accepted_identity_edge_delta.csv'],[O/'accepted_point_use_delta.csv']);after=s.metrics();af=fm.finite_metrics(s)
outs=['accepted_identity_edge_delta.csv','accepted_point_use_delta.csv','accepted_point_rejection_delta.csv','actual_raw_source_checks.csv','all_nearby_homonym_comparison.csv','held_cases.csv','bounded_context_bindings.csv','independent_two_sided_county_anchors.csv','bounded_historical_own_code_candidates.csv','own_qid_name_code_point_context.json','positive_own_qid_raw_code_rows.json','revyakino_primary2010_p52.txt'];pins[str(O.parent/'application_receipt.json')]=sha(O.parent/'application_receipt.json')
for row in json.loads((O/'own_qid_name_code_point_context.json').read_text()):pins[row['source_file']]=row['sha256']
r={'baseline_stage':28,'baseline_replay':'Actual integrated27 plus pinned accepted3 application; exact parentafter asserted','before':before,'after':after,'before_finite_all3_all_points':bf,'after_finite_all3_all_points':af,'net_finite_all3_all_points':{'histories':af['histories']-bf['histories'],'populations_by_year':{y:af['populations_by_year'][y]-bf['populations_by_year'][y] for y in bf['populations_by_year']}},'edges':len(edges),'point_uses':len(points),'point_rejections':len(rejects),'input_pins':pins,'output_pins':{n:sha(O/n) for n in outs},'protected_populations_quality_and_grain_unchanged':True,'status':'In-memory actual28 State API replay passed; independent pin replay pending','contradicted_optional_Geo2011_points_excluded':'Красногвардейский owncode point105km and TulaОктябрьский52km from independently coded owncurrent/Qpoints; those rawhistorical point claims do not supply transferred coordinates.'}
(O/'application_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2));print(json.dumps({'edges':len(edges),'points':len(points),'rejections':len(rejects),'net_finite':r['net_finite_all3_all_points']},ensure_ascii=False))
