from pathlib import Path
import pandas as pd,json,hashlib,math
Z=Path(__file__).parent; B=Z/'batch1_fourteen_groups';B.mkdir(exist_ok=True);A=Z.parent/'main_axis_residual_application68_20261008';o=pd.read_parquet(A/'applied_state_observations.parquet');p=pd.read_csv(Z/'bounded_accepted_donors.csv');r=pd.read_csv(Z.parent/'over1000_root_20261009/handoff_south_other_actual101_roster.csv')
# Exact reviewed record locators; population never used to select identities.
def find(s):
 q=o[o.source_record_id.str.endswith(s)];assert len(q)==1,(s,len(q));return q.iloc[0].to_dict()
def now(i):return find('parquet:'+str(i))
G=[('Новый',find('Adygea.xls:Sheet1:223'),find('Адыгея.xls:адыг:149'),now(183),'Тахтамукайский 2002 ownNP;2010 own row follows Яблоновский and Перекатный and precedes Афипсип. Imported Майкопский is stale carried header, no raw edit; separate Гиагинский Новый row7 excluded.'),
('Красносельское',find('KBR.xls:Sheet1:119'),find('202010.xls:СК:956'),now(31937),'Зерносовхозский council and Граничный/Придорожный/Степной neighbors; own article explicitly names1962Красносельский,2010 and2021Красносельское; same whole NP type grammar variant.'),
('Учебное',find('KBR.xls:Sheet1:167'),find('202010.xls:СК:986'),now(31980),'Учебнинский council; Лесной subordinate next row, own article stable Прохладненский Учебное. No competing same stem NP.'),
('Янтарное',find('KBR.xls:Sheet1:173'),find('202010.xls:СК:990'),now(31987),'Янтарненский council; Комсомольский subordinate next row, unique ownname stem county and wholeNP.'),
('Березичский стеклозавод',find('Kaluzhskaja.xls:Sheet1:1302'),find('Kalug_20L1_ethn_2010.xls:Data Sheet:12692'),now(28353),'Березичский council; Дмитровский/Березичская школа-интернат/Отрада neighbors. Exclude separate Березичи and school NP. Native genitive versus nominative name and printed type variants.'),
('Северное',find('kalmyk.xls:Sheet1:106'),find('калмыкия:58'),now(26866),'Own article explicit Северное akaМангут; unique Лаганский wholeNP, printed2010parentheticalias.'),
('Арыг-Узю',find('Tyva.xls:Sheet1:479'),find('Sib:11572'),now(153322),'Own article explicitly Арыг-Узю akaАрыг-Узуу, Улуг-Хемский county; no same alias competitor. Imported2010district р retained uninterpreted.'),
('Лондоко-завод',find('0:10525'),find('ДВ:2913'),now(18617),'2002/10pgt whole NP versus separate сельскоеЛондоко rows91/2922/18618; ownarticle explicit Лондоко-завод akaЛондоко; current code and acceptedownpoint distinguish.'),
('Козловка',find('Ryazanskaja.xls:Sheet1:1150'),find('Jaroslavl_20L1_20ethn_2010.xls:Data Sheet:931'),now(112491),'2010 row follows г.Михайлов and precedes10-йгодОктября; ownarticle place borders same neighbors and current Михайловский county. Рыбновский/same-name villages excluded by county and sourceorder.'),
('Червлённая-Узловая',find('Chechnya.xls:Sheet1:534'),find('202010.xls:СК:1782'),now(162026),'Ownarticle historical railwaystation locality explicitly binds earlier railway поселок and modernстаница inШелковской; ownalias Червлённо-Узловая. SeparateЧервленная excluded.'),
('Терский',find('Stavrolpski.xls:Sheet1:205'),find('202010.xls:СК:102'),now(126892),'2010СК102 neighborsТерек→Терский→Кудрявый→Луговой match2002Терскийcouncil. RivalСК110 followsАлександрийская/имКирова thenБалковский, matching2002ГеоргиевскийАлександрийскийcouncil.2010literal staleБудённовский preserved; no mass selection.'),
('Сятракасы Лапсарское',find('Chuvashia_1.xls:Sheet1:1695'),find('!!!:13890'),now(163658),'2002Лапсарскийcouncil and2010neighborsequenceЛапсары/Асакасы/БольшиеКарачуры/Вурманкасы/Ойкасы/Синьялы/ХирлеСир/Чергаши. Rival2002row1708/2010row13893 belongsСарабакасинский withМокшино/Пикшик/Самуково. Currentcode97644444131/OKATO97244844006 and ownarticle distinctЛапсарское point. Raw shared point never used.'),
('Озёрское',find('0:10443'),find('ДВ:1976'),now(118473),'Unique2002pgtОзерский and laterселоОзерское, Корсаковский county; ownarticle explicit status transition; no same-stem wholeNP competitor.'),
('Третий Северный Североуральск',find('0:7555'),find('Урал:4716'),now(120985),'2002officialurbanpgt row7555 inСевероуральск block; separateИвдельский rural zero row159 excluded. Currentacceptedpoint correct60.80922659.915673 rather than rawsharedИвдельpoint. Ownarticle distinctСевероуральский title.')]
edges=[];points=[];obs=[];scopes=[];w=[]
for title,*rest in G:
 proof=rest.pop();rows=rest;donor=rows[-1];d=p[p.target_source_record_id.eq(donor['source_record_id'])];assert len(d)==1;d=d.iloc[0].to_dict()
 for a,b in zip(rows,rows[1:]):edges.append(dict(from_source_record_id=a['source_record_id'],to_source_record_id=b['source_record_id'],from_year=a['census_year'],to_year=b['census_year'],relation='same_place',decision_status='checked_rule_accepted',admission_rule=proof,source_context_witness_file=str(Z/'literal_source_witnesses.csv'),population_boundary_comparability_asserted=False))
 for a in rows:
  assert math.isfinite(float(a['population']));obs.append(dict(a,scope_id=title,decision_status='checked_rule_accepted',population_values_modified=False))
  if a['source_record_id']!=donor['source_record_id']:
   v={k:d.get(k) for k in ['latitude','longitude','point_origin_file','point_origin_sha256','point_origin_locator','point_origin_kind','source_sha256','source_locator']};v.update(target_source_record_id=a['source_record_id'],coordinate_admission_status='reviewed_rule_accepted',coordinate_source_record_id=donor['source_record_id'],donor_source_record_id=donor['source_record_id'],coordinate_origin_ledger=str(A/'applied_point_snapshot.parquet'),coordinate_origin_ledger_sha256=hashlib.sha256((A/'applied_point_snapshot.parquet').read_bytes()).hexdigest(),coordinate_origin_ledger_target_source_record_id=donor['source_record_id'],admission_rule=proof,retrospective_point_use_is_continuity_inference=True,coordinate_time_interpretation='inferred_physical_continuity; not exact census-date measurement',direct_historical_coordinate_measurement=False,population_values_modified=False);points.append(v)
  scopes.append(dict(scope_id=title,census_year=a['census_year'],source_record_id=a['source_record_id'],available_year_status='native_finite_observation_identity_point_route_accepted',decision_status='checked_rule_accepted',rule=proof))
 w.append(dict(scope_id=title,proof=proof,source_record_ids=json.dumps([a['source_record_id'] for a in rows]),current_official_oktmo=donor['oktmo'],donor_point_latitude=d['latitude'],donor_point_longitude=d['longitude']))
for name,arr in [('accepted_identity_edge_delta.csv',edges),('accepted_point_use_delta.csv',points),('accepted_actual_available_year_observations.csv',obs),('accepted_actual_available_year_scopes.csv',scopes),('reviewed_group_binding.csv',w)]:pd.DataFrame(arr).to_csv(B/name,index=False)
credited=set(a['source_record_id'] for a in obs);r[r.source_record_id.isin(credited)].to_csv(B/'assigned_roster_source_ready.csv',index=False)
inputs=[A/'applied_state_observations.parquet',A/'applied_point_snapshot.parquet',Z/'literal_source_witnesses.csv',Z/'name_candidates.csv',Z/'bounded_accepted_donors.csv']+list(Z.glob('wiki*.json'))
pins=lambda fs:{str(f):dict(sha256=hashlib.sha256(f.read_bytes()).hexdigest(),bytes=f.stat().st_size) for f in fs}
(B/'FINAL_manifest.json').write_text(json.dumps(dict(status='FINAL_FROZEN_SOURCE_READY',groups=len(G),assigned_roster_uids=len(r[r.source_record_id.isin(credited)]),native_observations=len(obs),edges=len(edges),point_uses=len(points),population_and_quality_modified=False,input_pins=pins(inputs),output_pins=pins(list(B.glob('*.csv')))),ensure_ascii=False,indent=2))
print('FINAL',len(G),'groups',len(r[r.source_record_id.isin(credited)]),'assignedUID')
