from pathlib import Path
import pandas as pd,json,hashlib,math
Z=Path(__file__).parent; B=Z/'batch2_seven_np_and_typed_scopes';B.mkdir(exist_ok=True);A=Z.parent/'main_axis_residual_application68_20261008';o=pd.read_parquet(A/'applied_state_observations.parquet');p=pd.read_csv(Z/'bounded_accepted_donors.csv');p=pd.concat([p,pd.read_csv(Z/'centora_accepted_donor.csv')],ignore_index=True);r=pd.read_csv(Z.parent/'over1000_root_20261009/handoff_south_other_actual101_roster.csv')
# Exact reviewed record locators; population never used to select identities.
def find(s):
 q=o[o.source_record_id.str.endswith(s)];assert len(q)==1,(s,len(q));return q.iloc[0].to_dict()
def now(i):return find('parquet:'+str(i))
G=[
('Синезерки',find('Bryanskaja.xls:Sheet1:1803'),find('Kalug_20L1_ethn_2010.xls:Data Sheet:3097'),now(175038),'UniqueNavlinskyplace, native2002and2021Синезерский;2010Синезерки. OwnarticleСинезерки sharesСинезёрскийpopulationtemplate and ownСинезёрскоеmunicipality administrativecenter title; railstation origin distinguishes separatevillageПриволье.'),
('Центора-Юрт',find('Chechnya.xls:Sheet1:160'),find('202010.xls:СК:1548'),now(161624),'Ownarticle explicitНово-Центорой akaЦентора-Юрт, founded1989Грозненский county. SeparateНовыйБенойГудермесplace andКурчалоевский/Ножай-ЮртовскийЦенторойexcluded. Source2010nativeownrow1548andaccepted2021ownpoint.'),
('Берд-Юрт',find('202010.xls:СК:877'),now(23185),'Uniqueexactownname innative2010/2021Ingushetia, ownarticleСунженский municipality andformation1999;2002selectedpublication fullknownalias/neighbor scope screened noownpublishedrow,countunknownnotzero.'),
('Южное',find('202010.xls:СК:856'),now(23198),'Uniqueexactownname native2010/2021Ingushetia ownarticleМалгобекский. Ownarticle1959Южный alias and1963alternativeformation retained.2002complete selectednativepublication/Южн/МТС/usadba aliases screened noownrow,countunknownnotzero.'),
('Новый Бельтир',find('Sib:11204'),now(23321),'Ownarticledated2003newvillageconstruction afterearthquake;stable2010/2021 ownNP.2002Бельтир is separate survivingoldNP with2021row23322 and ownoldpoint; nevermerge orallocate oldcount1211 to newvillage.'),
('Новый Беной',now(161663),'Owncurrentfinite2021observation andacceptedownpoint. Completeselected2002/2010nativeandprintedknownaliasrivalcheck;ownarticle2015newmunicipality fromГудермес urbanterritory,2016namingdecree. Earlierseparatevillagecountunavailable,unknownnotzero. НовыйЦенторой=Центора-Юрт excluded explicitly.')]

edges=[];points=[];obs=[];scopes=[];w=[]
for title,*rest in G:
 proof=rest.pop();rows=rest;donor=rows[-1];d=p[p.target_source_record_id.eq(donor['source_record_id'])];assert len(d)==1;d=d.iloc[0].to_dict()
 for a,b in zip(rows,rows[1:]):edges.append(dict(from_source_record_id=a['source_record_id'],to_source_record_id=b['source_record_id'],from_year=a['census_year'],to_year=b['census_year'],relation='same_place',decision_status='checked_rule_accepted',admission_rule=proof,source_context_witness_file=str(Z/'literal_source_witnesses.csv'),population_boundary_comparability_asserted=False))
 for a in rows:
  assert math.isfinite(float(a['population']));obs.append(dict(a,scope_id=title,decision_status='checked_rule_accepted',population_values_modified=False))
  if a['source_record_id']!=donor['source_record_id']:
   v={k:d.get(k) for k in ['latitude','longitude','point_origin_file','point_origin_sha256','point_origin_locator','point_origin_kind','source_sha256','source_locator']};v.update(target_source_record_id=a['source_record_id'],coordinate_admission_status='reviewed_rule_accepted',coordinate_source_record_id=donor['source_record_id'],donor_source_record_id=donor['source_record_id'],coordinate_origin_ledger=str(A/'applied_point_snapshot.parquet'),coordinate_origin_ledger_sha256=hashlib.sha256((A/'applied_point_snapshot.parquet').read_bytes()).hexdigest(),coordinate_origin_ledger_target_source_record_id=donor['source_record_id'],admission_rule=proof,retrospective_point_use_is_continuity_inference=True,coordinate_time_interpretation='inferred_physical_continuity; not exact census-date measurement',direct_historical_coordinate_measurement=False,population_values_modified=False);points.append(v)
  scopes.append(dict(scope_id=title,census_year=a['census_year'],source_record_id=a['source_record_id'],available_year_status='native_finite_observation_identity_point_route_accepted',decision_status='checked_rule_accepted',rule=proof))
 w.append(dict(scope_id=title,proof=proof,source_record_ids=json.dumps([a['source_record_id'] for a in rows]),current_official_oktmo=donor['oktmo'],donor_point_latitude=d['latitude'],donor_point_longitude=d['longitude']))

a=find('Kaluzhskaja.xls:Sheet1:6');uid=a['source_record_id'];title='Резвань';proof='Literal2002Резвань underПлетеневский council subordinateЛенинскийокругКалуга. ExactownOSMsuburbРезвань addr:cityКалуга node3992047079version3 bindshistoricalownplace, not citypoint. Regionownaliassearch no rival. Complete2010/2021selectedpublication knownaliasрезван hasnoindividualownrow;latercountunknownnotzero. No datedlegalinclusion asserted.'
obs.append(dict(a,scope_id=title,decision_status='checked_rule_accepted',population_values_modified=False));f=Z/'rezvan_own_osm_node.xml';points.append(dict(target_source_record_id=uid,latitude=54.530928,longitude=36.1116178,coordinate_admission_status='reviewed_rule_accepted',coordinate_source_record_id='OSM:node:3992047079:version:3',point_origin_file=str(f),point_origin_sha256=hashlib.sha256(f.read_bytes()).hexdigest(),point_origin_locator='node3992047079version3timestamp2026-03-16T09:31:35Z;nameРезвань;addr:cityКалуга;place=suburb',point_origin_kind='own_former_locality_OSM_node',admission_rule=proof,retrospective_point_use_is_continuity_inference=True,direct_historical_coordinate_measurement=False,coordinate_time_interpretation='modernownformerplace point retrospectivephysicalcontinuity inference; notlegalboundary or censusdaymeasurement'))
scopes.append(dict(scope_id=title,census_year=2002,source_record_id=uid,available_year_status='native_finite_observation_identity_point_route_accepted',decision_status='checked_rule_accepted',rule=proof));w.append(dict(scope_id=title,proof=proof,source_record_ids=json.dumps([uid]),donor_point_latitude=54.530928,donor_point_longitude=36.1116178))
for title,years in [('Берд-Юрт',[2002]),('Южное',[2002]),('Новый Бельтир',[2002]),('Новый Беной',[2002,2010]),('Резвань',[2010,2021])]:
 for year in years:scopes.append(dict(scope_id=title,census_year=year,source_record_id='',available_year_status='individual_native_published_count_unavailable_in_complete_selected_scope; unknown_not_zero',decision_status='checked_rule_accepted',rule='Fullselectedregion-nativeandprintedknownalias/rival check in complete_selected_publication_scans.csv and complete_printed_source_alias_scans.csv; datedhistoryin ownarticle retained separately; no substitutezero/partialcount'))
for name,arr in [('accepted_identity_edge_delta.csv',edges),('accepted_point_use_delta.csv',points),('accepted_actual_available_year_observations.csv',obs),('accepted_actual_available_year_scopes.csv',scopes),('reviewed_group_binding.csv',w)]:pd.DataFrame(arr).to_csv(B/name,index=False)
credited=set(a['source_record_id'] for a in obs);r[r.source_record_id.isin(credited)].to_csv(B/'assigned_roster_source_ready.csv',index=False)
inputs=[A/'applied_state_observations.parquet',A/'applied_point_snapshot.parquet',Z/'literal_source_witnesses.csv',Z/'name_candidates.csv',Z/'bounded_accepted_donors.csv']+list(Z.glob('wiki*.json'))+[Z/'centora_literal2010.json',Z/'complete_selected_publication_scans.csv',Z/'complete_printed_source_alias_scans.csv',Z/'rezvan_own_osm_node.xml',Z/'rezvan_osm.json',Z/'centora_accepted_donor.csv']
pins=lambda fs:{str(f):dict(sha256=hashlib.sha256(f.read_bytes()).hexdigest(),bytes=f.stat().st_size) for f in fs}
(B/'FINAL_manifest.json').write_text(json.dumps(dict(status='FINAL_FROZEN_SOURCE_READY',groups=len(G)+1,assigned_roster_uids=len(r[r.source_record_id.isin(credited)]),native_observations=len(obs),edges=len(edges),point_uses=len(points),population_and_quality_modified=False,input_pins=pins(inputs),output_pins=pins(list(B.glob('*.csv')))),ensure_ascii=False,indent=2))
print('FINAL',len(G)+1,'groups',len(r[r.source_record_id.isin(credited)]),'assignedUID')
