from pathlib import Path
import pandas as pd,json,hashlib,gzip,math
O=Path(__file__).parent;B=O.parent;C=B.parent/'over500_moscow_current_point_sources_20261009';sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();rows=pd.read_csv(C/'three_modern_own_code_point_candidates.csv');d=pd.read_parquet('/dev/shm/over500-moscow-complete-batch3.parquet');p=pd.read_parquet('/dev/shm/over500-moscow-points.parquet').set_index('target_source_record_id');pts=pd.read_csv(O/'accepted_point_use_delta.csv').to_dict('records');edges=pd.read_csv(O/'accepted_identity_edge_delta.csv').to_dict('records');proof=[];reviews=[]
for r in rows.itertuples():
 nf=Path(r.own_source_file);xf=Path(r.crosswalk_source);assert sha(nf)==r.own_source_sha256 and sha(xf)==r.crosswalk_sha256;z=d[d.source_record_id.eq(r.source_record_id)].iloc[0];assert z.population==r.native_population;tags=json.loads(r.own_osm_extra_json);assert int(tags['oktmo:user'])==r.modern_oktmo and tags['official_status']==r.own_osm_kind;assert r.own_osm_category=='place';case='moscow_current_native_owncode_'+str(r.native_published_oktmo);rule='Exactpublishednative ownOKTMO/name/kind/county; secondaryexplicitRosstatrecodingmirror links467→465 owncode; independentlycapturedownOSMplace feature hasliteralnewowncode/name/officialstatus/county. Bothsamecounty homonyms separatelysourcecoded. DuplicateDadataFIAS/coordinates and OSMpopulation notbinding/population sources. Originalofficialamendmentnotdownloaded, limitationretained.'
 if r.source_record_id in p.index:
  cp=p.loc[r.source_record_id];distance=111*math.hypot(float(cp.latitude)-r.latitude,(float(cp.longitude)-r.longitude)*math.cos(math.radians(r.latitude)));assert distance<.3;reviews.append(dict(target_source_record_id=r.source_record_id,existing_latitude=cp.latitude,existing_longitude=cp.longitude,existing_point_ledger=cp.point_ledger_path,existing_point_ledger_sha256=sha(cp.point_ledger_path),qualified_ownpoint_latitude=r.latitude,qualified_ownpoint_longitude=r.longitude,displacement_km=distance,review_status='existing_correct_ownobject_point_confirmed_by_independent_current_owncode',owncode_binding_rule=rule,new_replacement_not_required=True))
 else:pts.append(dict(target_source_record_id=r.source_record_id,latitude=r.latitude,longitude=r.longitude,coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_source_record_id='OSM:'+r.own_source_locator.split(';lat')[0],source_sha256=r.own_source_sha256,source_locator=r.own_source_locator,point_origin_file=str(nf),point_origin_sha256=r.own_source_sha256,point_origin_locator=r.own_source_locator,point_origin_kind='own_native_code_qualified_OSM_place_representative_point',case=case,coordinate_binding_rule=rule,source_binding_proof=str(C/'three_modern_own_code_point_candidates.csv')+';'+str(C/'README.md'),point_use_inference='own_current_representative_point_for_actual_native2021_locality',population_boundary_comparability_asserted=False,historical_census_coordinate_asserted=False))
 # No historical joins by article title kind: binding uses BOTH fullownarticles historicalsourcehierarchy and owncodequalified currentfeature's exactownarticle/Wikidata reference.
 if r.source_record_id.endswith(':69461'):older=5278;hf=B/'batch2_lifecycle_homonyms/two_article_homonym_binding_witnesses.csv';h=pd.read_csv(hf);w=h[h.own_2002_UID.str.endswith(':5278')].iloc[0];article='Никольское (деревня, Рузский муниципальный округ)';qid='Q16022183'
 elif r.source_record_id.endswith(':69633'):older=4920;hf=B/'batch3_remaining/Zakharovo_positive_two_article_oldpair_sourceproof.json';w=json.loads(hf.read_text());article='Захарово (деревня, Раменский городской округ)';qid='Q18777747'
 else:continue
 old=d[d.census_year.eq(2002)&d.source_record_id.str.endswith(':'+str(older))].iloc[0];assert old.name_norm==z.name_norm and old.derived_oldcounty==z.derived_oldcounty;assert tags['wikidata']==qid;pgs={}
 for dr in[B,B/'batch2_lifecycle_homonyms']:
  for f in dr.glob('own_wikipedia_batch*.json.gz'):
   for pg in json.load(gzip.open(f,'rt'))['query']['pages'].values():
    if'revisions'in pg:pgs[pg['title']]=(pg,f)
 pg,f=pgs[article];assert pg['pageprops']['wikibase_item']==qid;ownco=pg['coordinates'][0];dist=111*math.hypot(ownco['lat']-r.latitude,(ownco['lon']-r.longitude)*math.cos(math.radians(r.latitude)));assert dist<.5;component=d[d.after_root.eq(old.after_root)];curcomp=d[d.after_root.eq(z.after_root)];assert not set(component.census_year)&set(curcomp.census_year);proof.append(dict(case=case,own_native2021_UID=r.source_record_id,own_native2002_UID=old.source_record_id,own_historical_component_UIDs='|'.join(component.source_record_id),historical_binding_proof=str(hf),historical_binding_proof_sha256=sha(hf),qualified_ownarticle_title=article,qualified_ownarticle_file=str(f),qualified_ownarticle_sha256=sha(f),qualified_ownarticle_QID=qid,current_ownfeature_QID=tags['wikidata'],current_ownfeature_code=r.modern_oktmo,current_native_code=r.native_published_oktmo,codecrosswalk_source=str(xf),codecrosswalk_sha256=sha(xf),raw_current_kind=z.type_norm,historical_native_kinds='|'.join(sorted(set(component.type_norm))),article_title_type_conflict_retained=True,article_current_typed_kind_not_used_as_historical_join_key=True,point_proximity_corrobation_only_km=dist,population_or_quality_changed=False,boundary_comparability='UNKNOWN'))
 edges.append(dict(from_source_record_id=old.source_record_id,to_source_record_id=z.source_record_id,relation='same_place',decision_status='checked_rule_accepted',case=case,admission_rule='Independentlysourcebound oldnativeownsubcounty/code and positiveBOTHqualifiedhomonymarticles; currentliteralnativeowncode/kind/county maps explicitly to separateownOSMfeaturecode and identicalownarticle/Wikidataobject. Historic/currentownarticlephysicalobjectcontinuity explicit; titlekindcontradiction retained, not used as joinkey; count/proximity/providerduplicateID notidentityalone',source_binding_proof=str(O/'current_owncode_to_historical_sourceobject_continuity.csv')+';'+str(hf)+';'+str(C/'three_modern_own_code_point_candidates.csv'),population_boundary_comparability_asserted=False,municipal_event_date='UNKNOWN'))
pd.DataFrame(pts).to_csv(O/'accepted_point_use_delta.csv',index=False);pd.DataFrame(edges).to_csv(O/'accepted_identity_edge_delta.csv',index=False);pd.DataFrame(proof).to_csv(O/'current_owncode_to_historical_sourceobject_continuity.csv',index=False);pd.DataFrame(reviews).to_csv(O/'accepted_existing_point_binding_review.csv',index=False);print('newcurrentownpoints2(existingcorrectlargeZakconfirmed1), historicalsourceobjectcontinuityedges2; provider/titleconflictsretained')
