from pathlib import Path
import pandas as pd,json,gzip,hashlib,xlrd
O=Path(__file__).parent;B=O.parent;sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();d=pd.read_parquet('/dev/shm/over500-moscow-observations.parquet');p=pd.read_parquet('/dev/shm/over500-moscow-points.parquet').set_index('target_source_record_id')
def sid(y,n):
 z=d[d.census_year.eq(y)&d.source_record_id.str.endswith(':'+str(n))];assert len(z)==1;return z.iloc[0]
old,cur,wrong,small,large=sid(2002,270),sid(2021,65353),sid(2010,8169),sid(2002,130),sid(2010,8075);members=d[d.root.eq(old.root)];assert set(members.source_record_id)=={old.source_record_id,cur.source_record_id,wrong.source_record_id};assert old.type_norm==cur.type_norm==large.type_norm=='село';assert wrong.type_norm==small.type_norm=='деревня';f=O/'own_wikipedia_batch6.json.gz';pgs=json.load(gzip.open(f,'rt'))['query']['pages'];big=next(z for z in pgs.values()if z.get('title')=='Ивановское (село, Волоколамский муниципальный округ)');little=next(z for z in pgs.values()if z.get('title')=='Ивановское (деревня, Волоколамский муниципальный округ)');bt=big['revisions'][0]['slots']['main']['*'];lt=little['revisions'][0]['slots']['main']['*'];assert'Ченецкого'in bt and'Кармановского'in lt;raw2=Path('/workspace/settlements-raw/data/raw/2002/010_3e630cc803_02c_Moskovskaya-oblast.xls');raw10=Path('/workspace/settlements-raw/data/raw/2010/010_711691e352_2._20Kostrom_Kur_Lip_Moscow_MoscObl_Orlov_2010.xls');s2=xlrd.open_workbook(str(raw2)).sheet_by_index(0);s10=xlrd.open_workbook(str(raw10)).sheet_by_name('Data Sheet');heads={n:next((i+1,s2.row_values(i))for i in range(n-2,-1,-1)if'сельский округ'in str(s2.cell_value(i,1)))for n in[270,130]};assert'Ченецкий'in heads[270][1][1]and'Кармановский'in heads[130][1][1];ef=B.parent/'current_component_name_alias_mass_20261008/accepted_identity_edge_delta.csv.gz';e=pd.read_csv(ef);hit=e[e.from_source_record_id.eq(wrong.source_record_id)&e.to_source_record_id.eq(old.source_record_id)];assert len(hit)==1;hit.to_csv(O/'Ivanovskoye_actual_false_type_alias_baseline_edge.csv',index=False);case='Ivanovskoye_Volokolamsk_false_derevnya_selo_identity';reason='Literalnative types distinguish exactly2samecounty homonyms: villageKarмановский02row130→2010row8169; seloChenecky02row270→2010row8075→2021row65353. Bothqualifiedownarticles confirm distinctownphysicalobjects/subcounties. Baselinegenericderevnya→selo aliasjoinedwrongobject; rejectonlyfalsepair and preserve independentlyvalidselo02→21.'
proof=dict(case=case,before_scope='baseline71',exact_before_members=members[['source_record_id','census_year','type_norm','population','derived_oldcounty']].to_dict('records'),true_selo2010_UID=large.source_record_id,true_village2002_UID=small.source_record_id,own_articles_path=str(f),own_articles_sha256=sha(f),selo_own_article=big,village_own_article=little,source2002_path=str(raw2),source2002_sha256=sha(raw2),source2010_path=str(raw10),source2010_sha256=sha(raw10),literal_original2002_subcounty_headings=heads,literal2002_rows={n:s2.row_values(n-1)for n in[270,130]},literal2010_rows={n:s10.row_values(n-1)for n in[8075,8169]},whole_samecounty_named_rivals=d[d.name_norm.eq('ивановское')&d.derived_oldcounty.eq('Волоколамский район')][['source_record_id','census_year','type_norm','population']].to_dict('records'),native_values_or_quality_modified=False)
pf=O/'Ivanovskoye_false_type_alias_sourceproof.json';pf.write_text(json.dumps(proof,ensure_ascii=False,indent=2,default=str));pd.DataFrame([dict(case=case,expected_before_members_JSON=json.dumps(sorted(members.source_record_id)),after_partition_JSON=json.dumps([[old.source_record_id,cur.source_record_id],[wrong.source_record_id]]),admission_status='reviewed_wrong_identity_component_partition_correction',source_binding_proof=str(pf),source_binding_proof_sha256=sha(pf),reason=reason)]).to_csv(O/'component_partition_correction.csv',index=False)
pd.DataFrame([dict(from_source_record_id=wrong.source_record_id,to_source_record_id=old.source_record_id,relation='same_place',rejection_status='reviewed_rejected_false_homonym_native_identity_edge',origin_edge_ledger=str(ef),origin_edge_ledger_sha256=sha(ef),reason=reason,requires_remove_accepted_pair_from_earlier_stage_ledger=True,native_population_values_retained=True)]).to_csv(O/'accepted_identity_edge_rejection_delta.csv',index=False);cp=p.loc[wrong.source_record_id];origin=Path(cp.point_ledger_path);pd.DataFrame([dict(target_source_record_id=wrong.source_record_id,rejection_status='reviewed_rejected_coordinate_claim_only',old_latitude=cp.latitude,old_longitude=cp.longitude,origin_ledger=str(origin),origin_ledger_sha256=sha(origin),reason=reason,native_identity_or_population_rejected=False)]).to_csv(O/'accepted_point_rejection_delta.csv',index=False)
pts=[];edges=[]
for r,pg,target in[(large,big,cur),(wrong,little,small)]:
 co=pg['coordinates'][0];loc=f'pageid={pg["pageid"]};revision={pg["revisions"][0]["revid"]}';pts.append(dict(target_source_record_id=r.source_record_id,latitude=co['lat'],longitude=co['lon'],coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_source_record_id='Wikipedia:page'+str(pg['pageid']),source_sha256=sha(f),source_locator=loc+':coordinates[0]',point_origin_file=str(f),point_origin_sha256=sha(f),point_origin_locator=loc+':coordinates[0]',point_origin_kind='own_Wikipedia_qualified_native_locality_representative_point',case=case,coordinate_binding_rule=reason,point_use_inference='own_modern_representative_point_on_source_bound_native_identity',population_boundary_comparability_asserted=False,historical_census_coordinate_asserted=False));edges.append(dict(from_source_record_id=r.source_record_id,to_source_record_id=target.source_record_id,relation='same_place',decision_status='checked_rule_accepted',case=case,admission_rule='Exactnative name/type and sourcecounty uniquely distinguishsamecounty village/selo, literaloriginalsubcounty and both qualifiedownarticles corroborate; baselinewrongalias partition must precede correctedjoins',source_binding_proof=str(pf),population_boundary_comparability_asserted=False,municipal_event_date='UNKNOWN'))
pd.DataFrame(pts).to_csv(O/'accepted_point_use_delta.csv',index=False);pd.DataFrame(edges).to_csv(O/'accepted_identity_edge_delta.csv',index=False);print('baselinepartition1, falsepair1, pointreject1, ownpoints2, correcttypededges2')
