from pathlib import Path
import pandas as pd,json,hashlib,xlrd,zipfile,re,math
Z=Path(__file__).parent;V1=Z.parent;E=V1.parent;A=E/'main_axis_residual_application68_20261008';sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();cur=lambda i:f'2021:data_allsettlements_anon_156_v20251217.parquet:parquet:{i}'
o=pd.read_parquet(A/'applied_state_observations.parquet').set_index('source_record_id',drop=False);p=pd.read_parquet(A/'applied_point_snapshot.parquet').set_index('target_source_record_id',drop=False);remaining=set(pd.read_csv(A/'applied_remaining_primary.csv.gz',usecols=['source_record_id']).source_record_id)
K02='2002:036_81b258bc42_02c_Krasnodarski-krai.xls:11:';K10='2010:005_888282bccc_13._20Краснодарский_край_2010.xls:КК:';R02='2002:040_95a4475637_02c_Rostov_obl.xls:Sheet1:';R10='2010:004_486e984bdc_12._20Астр_Волгог_Ростов.xls:Южный:'
rrawfile=Path('/workspace/settlements-raw/data/raw/2002/040_95a4475637_02c_Rostov_obl.xls');krawfile=Path('/workspace/settlements-raw/data/raw/2002/036_81b258bc42_02c_Krasnodarski-krai.xls');urbanfile=Path('/workspace/settlements-raw/data/raw/2002_official_tom1/1_TOM_01_04.xls');scan=[];county=[]
# Whole selected regional rural primary roster, whole urban publication, all native types. Aliases are literal documented ownarticle forms.
patterns=['Темерниц','Откормоч','Казачьи Лагери','Казачьи лагер','Юнкерск','Персианов','Щепкин']
for f in [rrawfile,urbanfile]:
 bk=xlrd.open_workbook(f)
 for s in bk.sheets():
  for pat in patterns:
   hits=[{'row_1based':i+1,'literal_cells':s.row_values(i)} for i in range(s.nrows) if pat.lower() in str(s.row_values(i)).lower()]
   scan.append(dict(source_file=str(f),source_sha256=sha(f),sheet=s.name,full_sheet_rows_scanned=s.nrows,literal_search=pat,match_count=len(hits),literal_matches_json=json.dumps(hits,ensure_ascii=False),interpretation='absence in searched cached publication only; not zero/not global proof no other2002publication exists'))
rs=xlrd.open_workbook(rrawfile).sheet_by_index(0)
for i in range(rs.nrows):
 if any(x in str(rs.row_values(i)) for x in ['Аксайский район','Октябрьский район']):
  start=i;end=next((j for j in range(i+1,rs.nrows) if re.search(r'^\s{0,4}\S.*район',str(rs.cell_value(j,1)))),rs.nrows);county.extend([dict(source_file=str(rrawfile),source_sha256=sha(rrawfile),sheet=rs.name,row_1based=j+1,literal_cells_json=json.dumps(rs.row_values(j),ensure_ascii=False)) for j in range(start,end)])
pd.DataFrame(scan).to_csv(Z/'full2002_source_publication_name_alias_scan.csv',index=False);pd.DataFrame(county).drop_duplicates(['sheet','row_1based']).to_csv(Z/'full2002_actual_county_source_rows.csv.gz',index=False,compression={'method':'gzip','mtime':0});o[o.census_year.eq(2002)&o.region_norm.eq('ростовская')].reset_index(drop=True).to_csv(Z/'all2002_selected_Rostov_native_typed_rivals.csv.gz',index=False,compression={'method':'gzip','mtime':0})
# Two source-form bridges independently anchored in printed old parish and the adjacent accepted source rows. No population match admission.
groups=[dict(label='Садовый Кеслеровский',old=K02+'1112',new=K10+'606',current=cur(45517),anchor_old=[K02+'1111',K02+'1113',K02+'1114'],anchor_new=[K10+'605',K10+'607',K10+'608'],competing_old=K02+'1125',competing_new=K10+'618',competing_current=cur(45532),qid='Q4404821',basis='actual printed Keslerovsky parish; exact Sadovy hutor; three surrounding accepted physical source anchors in unchanged order; actual current Keslerovskoye own coded article03225807002, distinct Kievsky source rival preserved'),dict(label='Николаевский source form→Николаевский2-й',old=R02+'2388',new=R10+'3732',current=cur(110762),anchor_old=[R02+'2386',R02+'2389',R02+'2390',R02+'2391'],anchor_new=[R10+'3731',R10+'3733',R10+'3734',R10+'3735'],competing_old='',competing_new='',competing_current='',qid='Q4320468',basis='actual printed Nikolaevsky parish; sole proper Nikolaevsky hutor across alltypes owncounty; four accepted immediate source flanks in unchanged order; source2002 omits ordinal2 while typed current owns exactNikolaevsky parish/currentcode60645425101 and historic2009/2011code60245825001; no rename date asserted')]
edges=[];points=[];w=[];sr=[];gain=[]
for g in groups:
 for a,b in zip(g['anchor_old'],g['anchor_new']):assert o.loc[a,'root']==o.loc[b,'root'],(a,b,'sourceflank not already accepted')
 roots=set(o.loc[[g['old'],g['new'],g['current']],'root']);m=o[o.root.isin(roots)];assert len(m)==3 and set(m.census_year)=={2002,2010,2021};donor=p.loc[g['current']].to_dict();lat,lon=float(donor['latitude']),float(donor['longitude']);target=g['new'] if o.loc[g['old'],'root']==o.loc[g['current'],'root'] else g['old']
 edges.append(dict(decision_id='SOUTH69V2-'+hashlib.sha256((target+g['current']).encode()).hexdigest()[:20],relation='same_place',from_source_record_id=target,to_source_record_id=g['current'],decision_status='checked_rule_accepted',decision_class='literal_published_parish_and_accepted_source_flanks',decision_rule=g['basis'],evidence_uri=str(Z/'literal_source_flank_identity_witnesses.csv.gz'),population_scope_interpretation='identity only; native counts/quality unchanged; boundary comparability UNKNOWN'))
 for i in m.index:
  if i not in p.index:
   rec=donor.copy();rec.update(target_source_record_id=i,latitude=lat,longitude=lon,coordinate_admission_status='reviewed_extension_rule_accepted',donor_target_source_record_id=g['current'],donor_point_snapshot_sha256=sha(A/'applied_point_snapshot.parquet'),admission_rule='actual own current physical NP point reused retrospectively on literal source parish + accepted-flank positive identity; no censusday accuracy claim',coordinate_provenance='explicit retrospective continuity; historic measurements UNKNOWN');points.append(rec)
  if i in remaining:gain.append(dict(source_record_id=i,census_year=int(o.loc[i,'census_year']),population=o.loc[i,'population'],scope_id=g['label']))
 ids=[g['old'],g['new']]+g['anchor_old']+g['anchor_new']+[x for x in [g['competing_old'],g['competing_new']] if x]
 for i in ids:
  x=o.loc[i];f=Path('/workspace/settlements-raw')/x.source_file;part=i.split(':');row=int(part[-1]);b=xlrd.open_workbook(f);s=b.sheet_by_name(part[-2]);sr.append(dict(group=g['label'],source_record_id=i,source_file=str(f),source_sha256=sha(f),sheet=s.name,row_1based=row,literal_cells_json=json.dumps(s.row_values(row-1),ensure_ascii=False),literal_neighbor_context_json=json.dumps([dict(row_1based=j+1,cells=s.row_values(j)) for j in range(max(0,row-5),min(s.nrows,row+3))],ensure_ascii=False),literal_source_headers_json=json.dumps([dict(row_1based=j+1,cells=s.row_values(j)) for j in range(row-1) if any(v in str(s.row_values(j)) for v in ['сельсовет','сельский округ','район'])][-5:],ensure_ascii=False),native_population=x.population,native_population_quality=x.population_value_quality,actual68_root=x.root))
 w.append(dict(**g,anchor_pairs_json=json.dumps([dict(old=a,new=b,actual68_root=o.loc[a,'root']) for a,b in zip(g['anchor_old'],g['anchor_new'])],ensure_ascii=False),all_same_county_name_type_rivals_file=str(V1/'all_native_name_type_county_rivals.csv.gz'),rivals_sha256=sha(V1/'all_native_name_type_county_rivals.csv.gz'),own_current_accepted_point_json=json.dumps(donor,ensure_ascii=False),physical_birth_date='UNKNOWN',boundary_comparability='UNKNOWN',source_countquality_unchanged=True))
pd.DataFrame(edges).to_csv(Z/'accepted_identity_edge_delta.csv.gz',index=False,compression={'method':'gzip','mtime':0});pd.DataFrame(points).to_csv(Z/'accepted_point_use_delta.csv.gz',index=False,compression={'method':'gzip','mtime':0});pd.DataFrame(w).to_csv(Z/'source_flank_positive_identity_rules.csv',index=False);pd.DataFrame(sr).to_csv(Z/'literal_source_flank_identity_witnesses.csv.gz',index=False,compression={'method':'gzip','mtime':0});pd.DataFrame(gain).to_csv(Z/'projected_incremental_native_finite_UID.csv',index=False)
# Actual available-year entity calendar (not strict NF3). Missing02 is UNKNOWN. Formation is statistical designation, not physical birth.
articles={}
for f in [V1/'wiki_articles_03.json',V1/'wiki_followup_01.json',V1/'wiki_followup_exact_02.json',Z/'own_held_articles.json']:
 for page in json.loads(f.read_text()).get('query',{}).get('pages',[]):
  q=page.get('pageprops',{}).get('wikibase_item')
  if q:articles[q]=(f,page)
avobs=[];avscope=[]
for q,current,kind,year in [('Q4454424',cur(108879),'separate_statistical_NP_designation_from_Schepkin',2008),('Q4318950',cur(108877),'separate_statistical_NP_designation_from_Schepkin',2008),('Q4208229',cur(110632),'existing_own_NP_missing_selected2002_publication',None)]:
 f,page=articles[q];t=page['revisions'][0]['slots']['main']['content'];mm=o[o.root.eq(o.loc[current,'root'])];assert set(mm.census_year)=={2010,2021};assert all(i in p.index for i in mm.index)
 scope='south69v2_available_'+q;lines=[l for l in t.splitlines() if any(v in l for v in ['2008','1880','военным городком','1982','Щепкин'])];avscope.append(dict(scope_id=scope,kind=kind,statistical_designation_year=year if year else 'UNKNOWN',physical_birth_year='UNKNOWN',missing_2002_population='UNKNOWN_NOT_ZERO',missing_2002_reason='own NP not located in explicitly full scanned cached source regional native rural+urban publications and documented aliases; no claim allpossible2002primaryarchives exhausted',source_file=str(f),source_sha256=sha(f),source_locator=f"page{page['pageid']}:revision{page['revisions'][0]['revid']}",source_literal_excerpt='\n'.join(lines),source_quality='secondary_own_article_literal_history; primarylaw_not_reopened',strict_NP3_credit=False,earlier_whole_Schepkin_population_assigned=False,baseline68_existing_ordinary2010_2021_component=True))
 for i,x in mm.iterrows():avobs.append(dict(scope_id=scope,source_record_id=i,census_year=int(x.census_year),native_population=x.population,native_population_quality=x.population_value_quality,own_point_json=json.dumps(p.loc[i].to_dict(),ensure_ascii=False),point_input_snapshot_sha256=sha(A/'applied_point_snapshot.parquet'),native02_count='UNKNOWN',strict_NP3_credit=False,new_finite_native_NP3_population=0,actual68_remaining_UID=i in remaining))
pd.DataFrame(avscope).to_csv(Z/'accepted_actual_available_year_scopes.csv',index=False);pd.DataFrame(avobs).to_csv(Z/'accepted_actual_available_year_observations.csv.gz',index=False,compression={'method':'gzip','mtime':0})
# Railway hutor own physical GeoNames point. Own article geographic NE-adjacency distinguishes other named parts/stations; feature is PPL, not RSTN.
gnfile=Path('/workspace/settlements-raw/data/raw/coordinate_candidates/geonames_RU_20260907.zip');gnrows=json.loads((Z/'geonames_exact_held_rivals.json').read_text());gv=next(v for v in gnrows if v[0]=='7434602');assert gv[7]=='PPL' and gv[10]=='61' and 'Железнодорожный' in gv[3];sid=R02+'897';# locate exact published hutor, not by population
matches=o[o.census_year.eq(2002)&o.region_norm.eq('ростовская')&o.name_norm.eq('железнодорожный')&o.district_raw.str.contains('Зерноград',na=False)];assert len(matches)==1;sid=matches.index[0];receiver=cur(109422);mm=o[o.root.eq(o.loc[receiver,'root'])];assert len(mm)==3 and all(i in p.index for i in mm.index)
f=V1/'wiki_articles_03.json';pages=json.loads(f.read_text())['query']['pages'];page=next(x for x in pages if x.get('pageprops',{}).get('wikibase_item')=='Q134971609');tt=page['revisions'][0]['slots']['main']['content'];assert 'В 2004' in tt and 'северо-востока' in tt;scope='south69v2_included_Железнодорожный';lat,lon=float(gv[4]),float(gv[5]);x=o.loc[sid]
event=dict(scope_id=scope,former_locality='Железнодорожный',recipient_city='Мечетинская',event_date=2004,date_precision='year',relation='included_in',same_place=False,event_source_file=str(f),event_source_sha256=sha(f),event_source_locator=f"page{page['pageid']}:revision{page['revisions'][0]['revid']}",event_source_quality='secondary_own_Wikipedia_literal_dated_inclusion',decision_status='accepted_secondary_own_article_included_in',primary_law_source_reopened=False,boundary_comparability='UNKNOWN',roster_closed=False,sum_city_equals_children_asserted=False)
pd.DataFrame([event]).to_csv(Z/'accepted_inclusion_events.csv',index=False)
fp=dict(scope_id=scope,target_source_record_id=sid,source_record_id=sid,latitude=lat,longitude=lon,coordinate_admission_status='reviewed_extension_rule_accepted',decision_status='reviewed_rule_accepted',point_origin_file=str(gnfile),point_origin_sha256=sha(gnfile),point_origin_locator='RU.txt geonameid=7434602',point_origin_kind='own_named_GeoNames_PPL_former_properNP',own_locality_point=True,recipient_point_assigned_to_child=False,direct_historical_coordinate_measurement=False,point_temporal_interpretation='explicit retrospective own former physical hutor point; historic measurement and boundaries UNKNOWN',binding_rule='actualGeoNames PPL Cyrillic name+RUADM1 Rostov61, location northeast of Mechetinskaya matches literalownarticle county/parish and NEadjacency; wholeRostov namesakes/type rivals retained; actualnamed formerNP, not station feature',GN_admin2='UNKNOWN',GN_raw_record_json=json.dumps(gv,ensure_ascii=False),wrong_Wikipedia_point_held='47.409865,42.252044; contradictoryowncounty/geography notused')
pd.DataFrame([fp]).to_csv(Z/'accepted_former_locality_own_points.csv',index=False);pd.DataFrame([dict(scope_id=scope,place='Железнодорожный',year=2002,source_record_id=sid,native_population=x.population,native_population_quality=x.population_value_quality,latitude=lat,longitude=lon,own_point=True,recipient_city='Мечетинская',receiving_city_2021_source_record_id=receiver,receiving_city_2021_count_context_only=o.loc[receiver,'population'],child_2021_population_assigned=False,event_date=2004,event_relation='included_in',same_place_identity_asserted=False,native_values_quality_preserved=True,is_additive_to_original_final_mixed_census_axis=False)]).to_csv(Z/'accepted_historical_observations.csv',index=False);pd.DataFrame([dict(scope_id=scope,source_record_id=sid,year=2002,source_population=x.population,new_population_on_separate_transformation_path_axis=x.population,own_historical_point_verified=True,receiving_city_actual_2002_2010_2021_context_verified=True,is_additive_to_original_final_mixed_census_axis=False,ordinary_three_census_same_place_claim=False)]).to_csv(Z/'accepted_direct_event_native_credit_union.csv',index=False);mm.reset_index(drop=True).to_csv(Z/'receiving_Mechetinskaya_actual68_context.csv',index=False)
# Every originalheld UID gets a concrete bounded disposition; unknownPrimomaysky date remains a hold, exactGN candidates preserved.
d=pd.read_csv(V1/'all58_UID_disposition.csv');d=d[d.disposition.str.startswith('HOLD')].copy();d['version2_disposition']='';d['version2_reason']='';ordinary={g['old'] for g in groups}|{g['new'] for g in groups};ava={x['source_record_id'] for x in avobs}
for j,y in d.iterrows():
 i=y.source_record_id
 if i in ordinary:st='accepted_ordinary_source_flank_bridge';why=next(g['basis'] for g in groups if i in [g['old'],g['new']])
 elif i==sid:st='accepted_separate_included_in_2004';why='own named GeoNames PPL; own datedarticle/geography; exactproper sourceparish; primarylaw503 notupgraded'
 elif i in ava:st='accepted_separate_actual_available_year_scope';why='native2010+21 ownpointed acceptedidentity;02 statisticsUNKNOWN afterfullcachedsource+alias scan; actualstatisticaldesignation2008 whereexplicit, neverphysicalbirth'
 else:st='HOLD_EVENT_DATE_AND_OWN_NP_POINT_BINDING_UNRESOLVED';why='actual2002Zverevo properNP Первомайский1291; modern regional rawfullroster lacks ownpublishedNP; multiple exactWiki title queries missing; actualGN2physicalPPL candidatesnearcity (7439531/11765007) but no owncounty/admin2, no datedinclusion source. Cityarticle has no transition; moderncitypoint/nearpoint cannot resolve. Officialsite request attempted; no invented event or zero.'
 d.loc[j,['version2_disposition','version2_reason']]=[st,why]
d.to_csv(Z/'all9_UID_disposition.csv',index=False)
receipt=dict(status='FROZEN_PENDING_ROOT_INDEPENDENT_REVIEW',baseline='actual68; V1frozen untouched',all9_originalheld_UIDs_disposed=True,dispositions=d.version2_disposition.value_counts().to_dict(),new_edges=len(edges),new_ordinary_point_uses=len(points),projected_native_finite_increment={str(y):{'UIDs':sum(x['census_year']==y for x in gain),'population':sum(x['population'] for x in gain if x['census_year']==y)} for y in [2002,2010,2021]},separate_DIRECT_increment_native2002_population=x.population,actual_available_year_scope_increment={str(y):{'UIDs':sum(x['census_year']==y and x['actual68_remaining_UID'] for x in avobs),'population':sum(x['native_population'] for x in avobs if x['census_year']==y and x['actual68_remaining_UID'])} for y in [2010,2021]},strict_NP3_increment_from_available_scopes=0,missing02_not_zero=True,physical_birth_not_inferred=True,source_counts_quality_changed=False,source_primary_population_upgrade=False,no_State_rerun=True,input_pins={str(f):{'sha256':sha(f),'bytes':f.stat().st_size} for f in [A/'applied_state_observations.parquet',A/'applied_point_snapshot.parquet',V1/'manifest.json',gnfile]})
(Z/'application_receipt.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2));print(json.dumps(receipt,ensure_ascii=False)[:1800])
