from pathlib import Path
import pandas as pd,json,gzip,hashlib
O=Path(__file__).parent;M=O.parent/'over1000_moscow_20261009';sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();d=pd.read_csv(M/'moscow_native_all_years_stage68.csv.gz');p=pd.read_csv(M/'moscow_ownpoint_snapshot68.csv.gz').drop_duplicates('target_source_record_id',keep='last').set_index('target_source_record_id');pages={}
for f in M.glob('own_wikipedia_batch*.json.gz'):
 for g in json.load(gzip.open(f,'rt'))['query']['pages'].values():
  if 'missing'not in g:pages[g['title']]=(g,f)
title='Петровское (Ленинский городской округ)';g,f=pages[title];lines=[dict(line=i,text=l)for i,l in enumerate(g['revisions'][0]['slots']['main']['*'].splitlines(),1)if'2020'in l or'1953'in l];assert any('официально образован' in l['text']for l in lines);sid='2021:data_allsettlements_anon_156_v20251217.parquet:parquet:65263';r=d[d.source_record_id.eq(sid)].iloc[0];assert r.population==1102;assert len(d[d.root.eq(r.root)])==1;cp=p.loc[sid];old=d[d.census_year.isin([2002,2010])&d.name_norm.eq('петровское')];proper=old[old.district_raw.str.contains('Ленинский',na=False)];assert len(proper)==0;scope='over1000_moscow_birth_65263';loc=f'pageid={g["pageid"]};revision={g["revisions"][0]["revid"]}'
ev=dict(scope_id=scope,place='Петровское',event_date='2020-05-16',date_precision='day',relation='administrative_creation_of_formally_named_NP_with_earlier_military_predecessor',decision_status='accepted_secondary_literal_own_NP_formation_available_year_path',event_source_file=str(f),event_source_sha256=sha(f),event_source_locator=loc,literal_ownsource_excerpt=json.dumps(lines,ensure_ascii=False),source_year_scope='actual_native2021_only',missing_2002_successor_count_assigned=False,missing_2010_successor_count_assigned=False,physical_predecessor_absence_asserted=False,predecessor_2002_population='UNKNOWN',predecessor_2010_population='UNKNOWN',no_calendar_zero_imputation=True,own_point_from_actual_native_NP=True,population_boundary_comparability='UNKNOWN',legal_date_role='Federal naming/formation order1298 date16May2020 quoted in ownarticle; regionalorder391-PG31Aug2020 retained independently in excerpt')
cr=dict(scope_id=scope,source_record_id=sid,year=2021,source_population=1102,new_population_on_available_year_formation_path_axis=1102,all_actual_native_observation_years='2021',birth_or_formal_creation_date='2020-05-16',native2002_population_not_imputed=True,native2010_population_not_imputed=True,predecessor_unknown_retained=True,own_point_verified=True,source_values_quality_preserved=True)
ob=dict(scope_id=scope,source_record_id=sid,census_year=2021,settlement_name=r.settlement_name,population=r.population,population_value_quality=r.population_value_quality,latitude=cp.latitude,longitude=cp.longitude,coordinate_source_record_id=cp.coordinate_source_record_id,point_origin_file=cp.point_origin_file,point_origin_sha256=cp.point_origin_sha256,point_origin_locator=cp.point_origin_locator,point_ledger_path=cp.point_ledger_path,own_point=True,formation_date='2020-05-16',all_available_native_years_continuity=True,boundary_comparability='UNKNOWN')
st=[dict(scope_id=scope,place='Петровское',census_year=y,status='formal_named_NP_created2020_earlier_military_predecessor1953_sourceyear_count_UNKNOWN'if y<2021 else'actual_separate_own_published_observation',own_population=1102 if y==2021 else'',calendar_zero_imputed=False,physical_population_absence_asserted=False,predecessor_source_year_value='UNKNOWN')for y in [2002,2010,2021]]
ab=dict(scope_id=scope,exact_owned_prior_namesake_rows_regionwide_json=old[['source_record_id','settlement_name','settlement_type','district_raw','population']].to_json(orient='records',force_ascii=False),proper_native_county='Ленинский район',exact_named_prior_county_matches=0,selected_2010_county_classifier_diagnostic='2010importdistrictblank; absence corroborated fullMoscow source names/independentcountycontext inventory, not blankdistrictfilter alone',all_actual_native_roster_path=str(M/'moscow_native_all_years_stage68.csv.gz'),all_actual_native_roster_sha256=sha(M/'moscow_native_all_years_stage68.csv.gz'),physical_predecessor_counts_unknown_not_zero=True)
# Independently derived2010 county disambiguates all ownname rivals.
a=pd.read_csv(M/'native_all_with_independent_county.csv.gz');same=a[a.census_year.eq(2010)&a.name_norm.eq('петровское')];assert not same.derived_oldcounty.str.contains('Ленинский',na=False).any();same.to_csv(O/'Petrovskoye_native2010_all_rivals_county_witnesses.csv',index=False)
for n,rows in [('accepted_newly_formed_lifecycle_events.csv',[ev]),('accepted_newly_formed_native_credit_union.csv',[cr]),('accepted_newly_formed_native_observations.csv',[ob]),('accepted_newly_formed_available_year_statuses.csv',st),('selected_prior_ownnamed_absence_witnesses.csv',[ab])]:pd.DataFrame(rows).to_csv(O/n,index=False)
print('Petrovskoye2021gain',1102)
