from pathlib import Path
import gzip,json,urllib.request,urllib.parse,datetime,hashlib
O=Path(__file__).parent
names=['Михалёвский сельский округ (Московская область)','Михалёвский сельский округ','Красный Холм (Воскресенский район)','Красный Холм (Воскресенский городской округ)','Красный Холм (Белоозёрский)','Белоозёрский','Михалёво (Воскресенский район)','Луговая (Лобня)','Лобня','Лаговский сельский округ','Центральная усадьба совхоза «Подольский»','Лаговское','Подольский (посёлок, Московская область)','Сергеевка (Подольский район)','Пушкино (село, Московская область)','Старое Пушкино','Светлый (Электроугли)','Светлый (Ногинский район)','Вишняковские Дачи','Ткацкой Фабрики (Московская область)','Ткацкой Фабрики (Красногорский район)','Опалиха','Совхозный (Серебряно-Прудский район)','Совхозный сельский округ (Московская область)','Поповка (сельское поселение Сафоновское)','Поповка (городское поселение Кратово)','Кудиново (Московская область)','Ямкино','Центральная усадьба совхоза имени Чапаева','Центральная усадьба совхоза имени 50-летия Октября','Центральная усадьба совхоза Шеметово','Звенигород','Поречье (Звенигород)']
u='https://ru.wikipedia.org/w/api.php?'+urllib.parse.urlencode(dict(action='query',titles='|'.join(names),prop='revisions|pageprops|coordinates',rvprop='ids|content|timestamp',rvslots='main',format='json',redirects=1,colimit='max'))
try:
 with urllib.request.urlopen(urllib.request.Request(u,headers={'User-Agent':'SettlementResearch/1.0'}),timeout=40)as r:b=r.read(9000000);status=r.status
except urllib.error.HTTPError as e:
 (O/'fetch_batch8_failure.json').write_text(json.dumps({'status':e.code,'request_url':u,'retry_after':e.headers.get('Retry-After'),'bypass':False}));raise
f=O/'own_wikipedia_batch8.json.gz';f.write_bytes(gzip.compress(b));j=json.loads(b);rows=[dict(title=p['title'],missing='missing'in p,pageid=p.get('pageid'),revid=p.get('revisions',[{}])[0].get('revid'),point=p.get('coordinates'))for p in j.get('query',{}).get('pages',{}).values()];(O/'fetch_batch8_receipt.json').write_text(json.dumps(dict(utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),request_url=u,normal_TLS=True,status=status,sha256=hashlib.sha256(f.read_bytes()).hexdigest(),pages=rows),ensure_ascii=False,indent=2));print(json.dumps(rows,ensure_ascii=False))
