from pathlib import Path
import pandas as pd,json,gzip,hashlib,re,xlrd,math
O=Path(__file__).parent;sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();F=Path('/workspace/settlements-raw/data/interim/2021_tochno/data_allsettlements_anon_156_v20251217.parquet');raw21=pd.read_parquet(F,columns=['oktmo','mun_upper','mun_lower','settlement','population','okato_dadata','oktmo_dadata','latitude_dadata','longitude_dadata']);lenin=raw21.iloc[27687];chkalov=raw21.iloc[27645];assert str(lenin.oktmo)=='29608464101' and str(chkalov.oktmo)=='29608432101';assert 'Дзержинский' in lenin.mun_upper and 'Ленина' in lenin.mun_lower and 'Чкаловский' in chkalov.mun_lower;assert float(lenin.latitude_dadata)==float(chkalov.latitude_dadata)and float(lenin.longitude_dadata)==float(chkalov.longitude_dadata)
A=Path('/workspace/settlements-raw/data/raw/wikipedia_articles/batch_02231.json.gz');J=json.load(gzip.open(A));pages=J['payload']['query']['pages'];pi=next(i for i,p in enumerate(pages)if p['title']=='Совхоз имени Ленина (Калужская область)');page=pages[pi];txt=page['revisions'][0]['slots']['main']['content'];assert 'Дзержинский' in txt and 'Село Совхоз имени Ленина' in txt and 'статус                   = Село' in txt

def coord(axis):
 v={k:float(x.replace(',','.'))for k,x in re.findall(r'\|\s*'+axis+r'_(deg|min|sec)\s*=\s*([0-9.,]+)',txt)};return v['deg']+v.get('min',0)/60+v.get('sec',0)/3600
lat,lon=coord('lat'),coord('lon')
def in_ring(x,y,r):
 inside=False
 for a,b in zip(r,r[1:]+r[:1]):
  x1,y1=a;x2,y2=b
  if (y1>y)!=(y2>y) and x<(x2-x1)*(y-y1)/(y2-y1)+x1:inside=not inside
 return inside

def in_poly(x,y,g):
 assert g['type']=='Polygon';r=g['coordinates'];return in_ring(x,y,r[0])and not any(in_ring(x,y,h)for h in r[1:])
G=O/'own_residential_geometry_lookup.json.gz';features=json.load(gzip.open(G));lg=next(x for x in features if x['osm_id']==18952767);cg=next(x for x in features if x['osm_id']==293206975);assert lg['category']==cg['category']=='place'and lg['type']==cg['type']=='village';assert lg['extratags']['official_status']=='ru:село'and lg['extratags']['wikipedia']=='ru:Совхоз имени Ленина (Калужская область)';assert 'Дзержинский'in lg['address']['county']and 'Дзержинский'in cg['address']['county'];oldlat=float(lenin.latitude_dadata);oldlon=float(lenin.longitude_dadata);assert in_poly(oldlon,oldlat,cg['geojson'])and not in_poly(oldlon,oldlat,lg['geojson'])and in_poly(lon,lat,lg['geojson'])
S=['2010:013_f60b2d2bcf_5._20Belg_Bryan_Vlad_Voron_Ivanov_Kalug_20L1_ethn_2010.xls:Data Sheet:12122','2021:data_allsettlements_anon_156_v20251217.parquet:parquet:27688'];P=pd.read_parquet('/dev/shm/over500-20261009/eleventh-application/applied_point_snapshot.parquet').set_index('target_source_record_id');R=[];N=[];W=[];ledgercache={};reason='Knownwrong copied DaData physicalpoint: raw2021 distinctownселоСовхозим.Ленина/fullOKTMO29608464101/ownLeninСП and raw2021селоСовхозЧкаловский29608432101/ownChkalovskyСП share identicalcoordinate. IndependentnamedOSMownresidentialpolygons establish commonpoint actually insideChkalovsky and outsideLenin; ownqualifiedLeninarticlepoint54.7066667,36.0808333 lies inside ownLeninpolygon and matches explicitсело/Дзержинский/owncouncil. Correct onlycoordinateclaims for2010Lenin545/currentLenin603; preserveChkalovsky claim, nativecounts and identity graph. No farmPOI/municipalcentroid/recipientpoint or censusboundary assertion.'
for sid in S:
 q=P.loc[sid];ledger=Path(q.point_ledger_path)
 if str(ledger)not in ledgercache:ledgercache[str(ledger)]=pd.read_parquet(ledger)if ledger.suffix=='.parquet'else pd.read_csv(ledger,keep_default_na=False)
 old=ledgercache[str(ledger)].set_index('target_source_record_id').loc[sid];assert sha(old.point_origin_file)==old.point_origin_sha256 and float(old.latitude)==oldlat and float(old.longitude)==oldlon;native=dict(source_file=str(F),sha256=sha(F),row_1based=27688,raw_fields=lenin.fillna('').to_dict())
 if sid.startswith('2010'):
  nf=Path('/workspace/settlements-raw/data/raw/2010/013_f60b2d2bcf_5._20Belg_Bryan_Vlad_Voron_Ivanov_Kalug_20L1_ethn_2010.xls');sh=xlrd.open_workbook(str(nf)).sheet_by_name('Data Sheet');cells=sh.row_values(12121);assert 'село Совхоз им. Ленина'in cells and 545 in cells;native=dict(source_file=str(nf),sha256=sha(nf),row0=12121,raw_cells=cells,accepted_prior_own_source_donor_2021_ownfields=lenin.fillna('').to_dict())
 wi=len(W);W.append(dict(target_source_record_id=sid,active_point_claim=old.to_dict(),active_ledger=str(ledger),active_ledger_sha256=sha(ledger),native_witness=native,distinctChkalovsky_native_ownfields=chkalov.fillna('').to_dict(),raw2021file=str(F),raw2021sha256=sha(F),actual_qualified_own_article_page=page,article_source_file=str(A),article_source_sha256=sha(A),actual_named_own_residential_polygons=features,geometry_source_file=str(G),geometry_source_sha256=sha(G),geometry_predicates=dict(oldpoint_inside_Chkalovsky=True,oldpoint_outside_Lenin=True,new_article_point_inside_Lenin=True),reason=reason,point_accuracy_and_census_boundary_unknown=True))
 R.append(dict(target_source_record_id=sid,rejection_status='reviewed_rejected_coordinate_claim_only',old_latitude=old.latitude,old_longitude=old.longitude,origin_ledger=str(ledger),origin_ledger_sha256=sha(ledger),old_point_origin_file=old.point_origin_file,old_point_origin_sha256=old.point_origin_sha256,old_point_origin_locator=old.point_origin_locator,old_coordinate_source_record_id=old.coordinate_source_record_id,rejection_reason=reason,evidence_file=str(O/'point_correction_witnesses.json.gz'),evidence_locator=f'[{wi}]'))
 N.append(dict(target_source_record_id=sid,latitude=lat,longitude=lon,coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_source_record_id=f'wikipedia:ru:pageid={page["pageid"]}',point_origin_file=str(A),point_origin_sha256=sha(A),point_origin_locator=f'payload.query.pages[{pi}].revisions[0].slots.main.content;owninfoboxcoordinate',point_origin_kind='direct_qualified_own_selo_article_coordinate_inside_independent_own_named_residential_polygon',coordinate_binding_rule=reason,point_use_inference='Explicit representative ownphysicalсело corepoint inference; retrospectivefor2010, censusday measurement/populationboundaries unknown.',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,external_provider_ID_binding_asserted=True,evidence_file=str(O/'point_correction_witnesses.json.gz'),evidence_locator=f'[{wi}]'))
R=pd.DataFrame(R);out=O/'accepted_point_rejection_delta.csv';R.to_csv(out,index=False);back=pd.read_csv(out);assert all(float(a)==float(b)for a,b in zip(back.old_latitude,R.old_latitude))and all(float(a)==float(b)for a,b in zip(back.old_longitude,R.old_longitude));pd.DataFrame(N).to_csv(O/'accepted_point_use_delta.csv',index=False);pd.DataFrame(columns=['from_source_record_id','to_source_record_id','relation','decision_status','admission_method','admission_rule','evidence_file','evidence_locator']).to_csv(O/'accepted_identity_edge_delta.csv',index=False)
with gzip.open(O/'point_correction_witnesses.json.gz','wt')as f:json.dump(W,f,ensure_ascii=False)
pd.DataFrame([dict(source_record_id=sid,disposition='withdraw_known_wrongChkalovsky_site_point_replace_ownLenin_selo_point',population_values_modified=False,identity_edges_added=False)for sid in S]+[dict(source_record_id='2010:013_f60b2d2bcf_5._20Belg_Bryan_Vlad_Voron_Ivanov_Kalug_20L1_ethn_2010.xls:Data Sheet:12068',disposition='retained_ownChkalovsky_point_inside_independent_named_own_residential_polygon',population_values_modified=False,identity_edges_added=False)]).to_csv(O/'record_dispositions.csv',index=False)
m=dict(active_point_rejections=2,accepted_own_point_replacements=2,population_values_modified=False,identity_edges_added=0,apply_order='reject_claims_before_admit_replacements',validation=dict(actual_native2021_owncodes_councils_county_and_commoncoordinates_checked=True,native2010_ownwhole_selo_row_reopened=True,exact_active_ledger_hash_and_rejection_float_equality_checked=True,own_named_residential_polygon_predicates_verified=True,farmPOI_or_adminpolygon_not_used=True),frozen_files=[dict(name=f.name,sha256=sha(f),bytes=f.stat().st_size)for f in sorted(O.iterdir())if f.is_file()]);(O/'freeze_manifest.json').write_text(json.dumps(m,ensure_ascii=False,indent=2));print('2 rejections + 2 ownpoint replacements; Chkalovsky retained')
