from pathlib import Path
import pandas as pd,json,gzip,hashlib,xlrd
O=Path(__file__).parent.resolve();M=O.parent/'over1000_moscow_20261009';L=O.parent/'over1000_moscow_last10_sources_20261009';sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest()
d=pd.read_csv(M/'moscow_native_all_years_stage68.csv.gz');p=pd.read_csv(M/'moscow_ownpoint_snapshot68.csv.gz').drop_duplicates('target_source_record_id',keep='last').set_index('target_source_record_id');credited=set(pd.read_csv(O.parent/'main_axis_residual_application68_20261008/applied_primary_credited_UID_roster.csv.gz').source_record_id)
f=L/'own_wikipedia_batch9.json.gz';pgs={pg['title']:pg for pg in json.load(gzip.open(f,'rt'))['query']['pages'].values()}
raw=Path('/workspace/settlements-raw/data/raw/2002/010_3e630cc803_02c_Moskovskaya-oblast.xls');sh=xlrd.open_workbook(str(raw)).sheet_by_index(0)
configs=[('Центральной Усадьбы совхоза им. 50-летия Великого Октября',3866,2809,'Кудиново','Кудиновский сельский округ','2004-03-24','24 марта 2004'),('Центральной Усадьбы совхоза Подольский',4618,2998,'Железнодорожный','Железнодорожный (городской округ Подольск)','2006-08-18','18 августа 2006')]
obs=[];pts=[];ev=[];ed=[];cr=[];ct=[];rw=[];ex=[];wi=[];st=[]
for name,row,pop,receiver,title,date,term in configs:
 sid=f'2002:010_3e630cc803_02c_Moskovskaya-oblast.xls:Sheet1:{row}';old=d[d.source_record_id.eq(sid)].iloc[0];assert int(old.population)==pop and sid not in credited
 if row==3866:
  current=d[(d.census_year==2021)&d.name_norm.eq('кудиново')&d.settlement_type.eq('село')];assert len(current)==1;cur=current.iloc[0]
  pf=O/'own_historical_photo_1164869.html.gz';j=json.loads((O/'photo_1164869_owngeo_witness.json').read_text());assert j['cid']==1164869 and 'Жилые дома для рабочих совхоза имени 50-летия Великого Октября'==j['title'];lat,lon=j['geo'];pl='Pastvu:1164869;init.photo.photo.geo;title=Жилые дома для рабочих совхоза имени 50-летия Великого Октября;photoyear1970';pcs='Pastvu:1164869:geo';kind='own_former_NP_named_historical_worker_residential_housing_manual_geotag_representative_point';binding='Exact own farm propername worker residential houses in native Noginsk Kudinovsky county. The old published NP is this uniquely named central estate; literal 2004 inclusion confirms former NP identity. Photograph sourced to Noginsk museum holdings, 1970. Housing reference point, not receiving Kudinovo point, factory, church or census-day coordinate; exact boundaries UNKNOWN.'
 else:
  cur=d[d.source_record_id.eq('2021:data_allsettlements_anon_156_v20251217.parquet:parquet:69296')].iloc[0]
  pf=O/'Podolsky_own_house210.json.gz';jj=json.load(gzip.open(pf,'rt'));j=next(x for x in jj if x.get('osm_id')==305060674);assert j['category']=='building' and j['type']=='apartments' and j['address']['house_number']=='210';lat,lon=float(j['lat']),float(j['lon']);pl='Nominatim:OSMway305060674;building/apartments;address=Большая Серпуховская210;lat,lon';pcs='OSM:way:305060674';kind='own_former_NP_qualified_legacy_residential_house_address_independent_geolocation_representative_point'
  af=O/'Podolsky_own_legacy_qualified_residential_address210.html.gz';txt=gzip.open(af,'rt').read();assert '210' in txt and 'ЦЕНТРАЛЬНОЙ УСАДЬБЫ' in txt
  binding='Independent public legacy residential address explicitly names own former NP: МОСКОВСКАЯ ОБЛ.,ПОДОЛЬСКИЙ Р-Н,П ЦЕНТРАЛЬНОЙ УСАДЬБЫ СВХ ПОДОЛЬСКИЙ,УЛ БОЛЬШАЯ СЕРПУХОВСКАЯ,Д210. Independently geolocated exact same residential apartment house210 OSM305060674. Address-to-house reference point, not receiving Railway NP point or county office214В. No census-day measurement or centroid claim.'
  wi.append(dict(source_record_id=sid,source_path=str(af),source_sha256=sha(af),source_locator='HTML own legacy legal address;postal142180;Большая Серпуховская210;NPnameЦентральнойУсадьбыСВХПодольский',literal_binding=binding))
 cg=d[d.root.eq(cur.root)];assert len(cg)==3 and set(cg.census_year)=={2002,2010,2021} and set(cg.source_record_id)<=credited and all(x in p.index for x in cg.source_record_id)
 pg=pgs[title];loc=f'pageid={pg["pageid"]};revision={pg["revisions"][0]["revid"]}';lines=[dict(line=i,text=l) for i,l in enumerate(pg['revisions'][0]['slots']['main']['*'].splitlines(),1) if term in l];assert lines
 scope=f'over1000_moscow_last5_included_{row}';ph=sha(pf)
 obs.append(dict(scope_id=scope,place=name,year=2002,source_record_id=sid,native_population=pop,native_population_quality=old.population_value_quality,latitude=lat,longitude=lon,own_point=True,recipient_city=receiver,receiving_NP_actual_type=cur.settlement_type,event_date=date,event_date_precision='day',event_relation='included_in',same_place_identity_asserted=False,receiving_city_2021_source_record_id=cur.source_record_id,receiving_city_2021_count_context_only=int(cur.population),child_2021_population_assigned=False,is_additive_to_original_final_mixed_census_axis=False,already_in_baseline68_primary_native_ID_union=False,new_native_population_if_event_admitted=pop,whole_city_roster_closure_asserted=False,population_boundary_comparability_asserted=False,native_values_quality_preserved=True))
 pts.append(dict(scope_id=scope,target_source_record_id=sid,source_record_id=sid,latitude=lat,longitude=lon,coordinate_admission_status='reviewed_rule_accepted',decision_status='reviewed_rule_accepted',coordinate_source_record_id=pcs,source_sha256=ph,source_locator=pl,point_origin_file=str(pf),point_origin_sha256=ph,point_origin_locator=pl,point_origin_kind=kind,own_locality_point=True,recipient_point_assigned_to_child=False,new_ordinary_point_use_proposed=sid not in p.index,point_temporal_interpretation='Independent qualified own former NP residential reference point, retrospective native2002 spatial use; no direct censusday coordinate claim',direct_historical_coordinate_measurement=False,provider_binding_asserted=False,boundary_comparability_asserted=False))
 ev.append(dict(scope_id=scope,former_locality=name,recipient_city=receiver,receiving_NP_type=cur.settlement_type,event_date=date,date_precision='day',relation='included_in',same_place=False,event_source_file=str(f),event_source_sha256=sha(f),event_source_locator=loc,event_source_quality='secondary_literal_dated_former_NP_inclusion_own_county_or_receiver_article',event_date_role='Quoted dated inclusion/actdate; operative exactday not independently imputed',decision_status='accepted_secondary_article_included_in',primary_law_source_reopened=False,boundary_comparability='UNKNOWN',roster_closed=False,sum_city_equals_children_asserted=False))
 ed.append(dict(scope_id=scope,from_source_record_id=sid,to_source_record_id=cur.source_record_id,relation='included_in',event_date=date,date_precision='day',event_source_file=str(f),event_source_sha256=sha(f),event_source_locator=loc,same_place=False,graph_union_allowed=False,whole_city_roster_closure_asserted=False,modern_boundary_reconstruction=False))
 cr.append(dict(scope_id=scope,source_record_id=sid,year=2002,source_population=pop,new_population_on_separate_transformation_path_axis=pop,own_historical_point_verified=True,receiving_city_actual_2002_2010_2021_context_verified=True,is_additive_to_original_final_mixed_census_axis=False,ordinary_three_census_same_place_claim=False))
 vals=sh.row_values(row-1);assert int(vals[2])==pop;rw.append(dict(source_record_id=sid,year=2002,native_population=pop,native_quality=old.population_value_quality,source_path=str(raw),source_sha256=sha(raw),source_locator=f'Sheet1:row{row}',raw_cells_json=json.dumps(vals[:8],ensure_ascii=False),matches_native_population=True))
 ex.append(dict(scope_id=scope,source_path=str(f),source_sha256=sha(f),source_locator=loc,literal_excerpts_json=json.dumps(lines,ensure_ascii=False)))
 wi.append(dict(source_record_id=sid,source_path=str(pf),source_sha256=ph,source_locator=pl,literal_binding=binding,geographic_record_json=json.dumps(j,ensure_ascii=False)))
 for y in [2002,2010,2021]:st.append(dict(scope_id=scope,place=name,year=y,status='actual_separate_own_published_observation' if y==2002 else 'ceased_as_separate_locality_included_in_recipient_before_census',own_population=pop if y==2002 else '',unknown_is_zero=False,recipient_population_assigned_to_child=False,boundary_comparability='UNKNOWN'))
 for r in cg.itertuples():
  cp=p.loc[r.source_record_id];ct.append(dict(scope_id=scope,recipient_city=receiver,receiving_NP_actual_type=r.settlement_type,census_year=r.census_year,source_record_id=r.source_record_id,population=r.population,population_value_quality=r.population_value_quality,latitude=cp.latitude,longitude=cp.longitude,point_ledger_path=cp.point_ledger_path,is_receiving_city_context_only=True,new_national_credit_population=0,child_count_substituted=False,already_in_baseline68_primary_credit=True))
for n,rows in [('accepted_historical_observations.csv',obs),('accepted_former_locality_own_points.csv',pts),('accepted_inclusion_events.csv',ev),('accepted_included_in_event_edges.csv',ed),('accepted_direct_event_native_credit_union.csv',cr),('actual_receiving_city_three_census_context.csv',ct),('event_native_raw_row_witnesses.csv',rw),('literal_own_inclusion_source_excerpts.csv',ex),('accepted_available_year_statuses.csv',st),('independent_own_residential_geographic_binding_witnesses.csv',wi)]:pd.DataFrame(rows).to_csv(O/n,index=False)
a=pd.read_csv(M/'assigned79_native_UIDs.csv');a[a.source_record_id.isin([x['source_record_id'] for x in cr])].to_csv(O/'assigned79_additional_ready_UIDs.csv',index=False);h=a[a.source_record_id.str.endswith((':1568',':4801',':2538'))].copy();assert len(h)==3 and h.population.sum()==8197;h['status']='dated_absorption_known_independent_own_former_NP_point_still_unresolved';h.to_csv(O/'remaining3_literal_native_holds.csv',index=False)
receipt=dict(status='FINAL_FROZEN',baseline=68,included_in_events=2,historical_observations=2,receiving_context_observations=6,included_native2002_population_gain=5807,assigned79_additional_ready_records=2,all_prior_packets_plus_this_ready_assigned_records=76,remaining_assigned_records=3,remaining_assigned_population=8197,ordinary_identity_edges=0,own_former_NP_points=2,native_population_edits=0,parent_point_assignment=False,fake_child_future_counts=False,boundary_comparability='UNKNOWN',qualified_own_point_quality='Kudinovo exactownfarmworkerresidentialhousing historical photograph manualgeotag; Podolsky explicitownformerNPlegacyhouse210address plus independent exactresidentialhouseOSMpoint. NeitherclaimsNPcentroidorcensusdaymeasurement.')
(O/'FINAL_packet_receipt.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n')
manifest=dict(status='FINAL_FROZEN',baseline=68,files=[dict(path=f.name,bytes=f.stat().st_size,sha256=sha(f)) for f in sorted(O.iterdir()) if f.is_file()and not f.name.startswith('FINAL_manifest')]);(O/'FINAL_manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n');h=sha(O/'FINAL_manifest.json');(O/'FINAL_manifest.sha256').write_text(h+'  FINAL_manifest.json\n');print(receipt);print(h)
