import pandas as pd,duckdb,json,sys
from pathlib import Path
O=Path(__file__).parent;sys.path.insert(0,'/workspace/russian-settlements-research/research_rebuild/mass_linkage');from current_chain_state_20261007 import distance_km
c=duckdb.connect();d=pd.read_csv(O/'existing_full3_point_conflicts.csv');ids=d[d.year==2021].source_record_id.tolist(); w=c.execute('select * from read_parquet(?) where source_record_id in (select unnest(?))',['/workspace/settlements-work/wikidata/wide_v5/wide_point_bindings.parquet',ids]).fetchdf();w.to_csv(O/'independent_current_code_point_witnesses.csv',index=False)
rows=[]
for root,g in d.groupby('root',sort=False):
 modern=g[g.year==2021].iloc[0]; old=g[(g.haspoint)&(g.year!=2021)].iloc[0]; p=json.loads(old.point_json);code=p.get('coordinate_source_record_id','').split(':')[-1];raw=c.execute('select * from read_parquet(?) where historical_okato=?',['/workspace/settlements-work/sources/geokladr_raw_verification/geokladr_okato_2011_raw_parsed.parquet',code]).fetchdf(); candidates=w[w.source_record_id==modern.source_record_id];summary=[]
 for z in candidates.to_dict('records'):
  pts=json.loads(z['points_json']); dist=min([distance_km((modern.latitude,modern.longitude),(a["latitude"],a["longitude"])) for a in pts] or [9999]);summary.append({'qid':z['wikidata_qid'],'label':z['wikidata_tsv_ru_labels_json'],'admin':z['wikidata_tsv_ru_admin_labels_json'],'name_exact':bool(z['wikidata_name_exact_label']),'competition':bool(z['entity_competition_across_tsv_or_truthy']),'distance_current_km':dist,'okato':z['wikidata_tsv_okato_exact_values_json'],'source_okato':z['source_okato_projection_raw'],'url':z['wikidata_tsv_article_urls_json']})
 rows.append({'root':root,'name':modern['name'],'total_population':modern.component_population_sum,'current_county':modern.county,'old_county':g[g.year==2002].iloc[0].county,'old_raw_code':code,'old_raw_name':raw.iloc[0].name1_raw_text if len(raw) else '', 'old_raw_type':raw.iloc[0].settlement_type_raw if len(raw) else '', 'current_old_distance_km':distance_km((modern.latitude,modern.longitude),(old.latitude,old.longitude)),'independent_witnesses':json.dumps(summary,ensure_ascii=False),'raw_json':raw.to_json(orient='records',force_ascii=False)})
s=pd.DataFrame(rows);s.to_csv(O/'source_binding_screen.csv',index=False);print(s.drop(columns=['root','raw_json']).to_string(index=False))
