from pathlib import Path
import pandas as pd,json,gzip,hashlib,re
O=Path(__file__).parent;D=pd.read_pickle('/dev/shm/over500-20261009/east_enriched.pkl');by=D.set_index('source_record_id',drop=False);P=pd.read_parquet('/dev/shm/over500-20261009/points_compact.parquet').fillna('').drop_duplicates('target_source_record_id',keep='last').set_index('target_source_record_id');F=O/'own_articles.json.gz';sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();J=json.load(gzip.open(F));pages={p['title']:p for p in J['query']['pages'].values()if'missing'not in p};edges=[];pts=[];wit=[];status=[];events=[]
def point(rows,pg=None,donor=None):
 if donor is None:
  assert pg and pg.get('coordinates');co=pg['coordinates'][0];a=dict(latitude=co['lat'],longitude=co['lon'],coordinate_source_record_id=f'ruwiki:page{pg["pageid"]}:revision{pg["revisions"][0]["revid"]}',point_origin_file=str(F),point_origin_sha256=sha(F),point_origin_locator=f'page{pg["pageid"]}:revision{pg["revisions"][0]["revid"]}:coordinates[0]',point_origin_kind='independent_own_locality_article_named_coordinate')
 else:a={k:donor[k]for k in ['latitude','longitude','coordinate_source_record_id','point_origin_file','point_origin_sha256','point_origin_locator','point_origin_kind']}
 for sid in rows:
  if sid in P.index:continue
  pts.append(dict(target_source_record_id=sid,**a,coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_binding_rule='sourcecounty_own_named_article_alias_or_dated_lifecycle_and_native_unique_object_binding',point_use_inference='Retrospective representative own-locality point continuity inference; exact census-date measurement and population boundaries unknown.',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,external_provider_ID_binding_asserted=False))
def alias(old,current,title,terms):
 a=by.loc[old];b=by.loc[current];g=D[D.root.eq(b.root)];assert a.root!=b.root and not set(g.census_year)&{a.census_year};assert a.region_norm==b.region_norm and a.county==b.county and a.type_norm==b.type_norm
 pg=pages[title];txt=pg['revisions'][0]['slots']['main']['*'];excerpt=[dict(line=i,text=l)for i,l in enumerate(txt.splitlines(),1)if any(term in l for term in terms)];assert excerpt
 rivals=D[(D.region_norm==a.region_norm)&D.name_norm.isin([a.name_norm,b.name_norm])&D.county.eq(a.county)];assert not rivals.census_year.duplicated().any()
 wid=len(wit);wit.append(dict(old_source_id=old,current_source_id=current,raw_name_old=a.settlement_name,raw_name_current=b.settlement_name,county=a.county,native_rivals=rivals.source_record_id.tolist(),source_file=str(F),source_sha256=sha(F),pageid=pg['pageid'],revision=pg['revisions'][0]['revid'],own_article_excerpt=excerpt,interpretation='Literal own named article alias or sourcecounty-resolved printed spelling variation; counts preserved and not identity evidence alone.'))
 edges.append(dict(from_source_record_id=old,to_source_record_id=current,relation='same_place',decision_status='checked_rule_accepted',admission_method='sourcecounty_unique_native_own_name_variant_and_independent_own_article_corroboration',admission_rule='Unique own name variant within independently matching native sourcecounty and type; own article corroborates locality spelling or dated own2002 count; no sameyear rival, split or merger assertion.',population_boundary_comparability_asserted=False,evidence_file=str(O/'identity_point_witnesses.json.gz'),evidence_locator=f'[{wid}]'))
 donor=next((P.loc[s]for s in g.source_record_id if s in P.index),None);point([old]+g.source_record_id.tolist(),pg=pg,donor=donor)
alias('2002:066_76aa869929_Altai_krai1.xls:Sheet1:1343','2021:data_allsettlements_anon_156_v20251217.parquet:parquet:40011','Бажево',['Бажово','Первомайском'])
alias('2002:064_d017f142fc_Tyva.xls:Sheet1:226','2021:data_allsettlements_anon_156_v20251217.parquet:parquet:153162','Кундус-Туг',['Кундустуг','Каа-Хемском'])
alias('2002:044_42b3ed3cfc_Tataria.xls:Sheet1:4090','2021:data_allsettlements_anon_156_v20251217.parquet:parquet:133068','Старые Уруссу',['Уруссы','2002 = 835','Ютазинск'])
alias('2002:044_42b3ed3cfc_Tataria.xls:Sheet1:3758','2021:data_allsettlements_anon_156_v20251217.parquet:parquet:132762','Большая Елга',['2002 = 863','Рыбно-Слободск'])
# A dated disappearance establishes an available-year route; it never supplies a zero2021 or ordinary3 claim.
for title,reg,norm,date,needle in [('Бубновка (Иркутская область)','иркутская','бубновка','2019-05-27','Упразднён в 2019'),('Горно-Чуйский','иркутская','горно чуйский','2019-11-01','Упразднён в ноябре 2019'),('Согдиондон','иркутская','согдиондон','2019-03-05','Упразднён в марте 2019'),('Мессо','ямало ненецкий','мессо','2006-10-06','В 2006'),('Полярный (Ямало-Ненецкий автономный округ)','ямало ненецкий','полярный','2006','Исключён из учётных данных в 2006')]:
 pg=pages[title];txt=pg['revisions'][0]['slots']['main']['*'];ls=[dict(line=i,text=l)for i,l in enumerate(txt.splitlines(),1)if needle in l];assert ls
 g=D[D.region_norm.eq(reg)&D.name_norm.eq(norm)];assert len(g)>0 and not g.census_year.duplicated().any()and 2021 not in set(g.census_year)
 ids=g.source_record_id.tolist();sid=ids[0];scope='east_lifecycle_'+str(pg['pageid']);loc=f'page{pg["pageid"]}:revision{pg["revisions"][0]["revid"]}';events.append(dict(scope_id=scope,place=title,relation='settlement_abolished',event_date=date,date_precision='day_of_cited_act'if len(date)>4 else'year',decision_status='accepted_secondary_own_article_literal_dated_abolition',event_source_file=str(F),event_source_sha256=sha(F),event_source_locator=loc,ordinary_same_place=False,boundary_comparability='UNKNOWN',own_actual_observed_years=','.join(map(str,sorted(g.census_year))),physical_abolition_on_exact_day_asserted=False,affected_source_uids='|'.join(ids),literal_excerpt=json.dumps(ls,ensure_ascii=False)))
 for s in ids:
  for yr in [2002,2010,2021]:
   status.append(dict(target_source_record_id=s,scope_id=scope,year=yr,year_status='observed_source_year'if yr in set(g.census_year)else'not_applicable_post_abolition',evidence_source=str(F),evidence_locator=loc,interpretation='Own locality official abolition reported by dated own article; absent later count remains unknown, never zero; separate lifecycle available-year route.'))
 donor=next((P.loc[s]for s in ids if s in P.index),None);point(ids,pg=pg,donor=donor)
 if g.root.nunique()>1:
  assert title=='Горно-Чуйский';edges.append(dict(from_source_record_id=ids[0],to_source_record_id=ids[1],relation='same_place',decision_status='checked_rule_accepted',admission_method='unique_native_urban_own_name_and_own_article_county_dated_abolition',admission_rule='Only Gorno-Chuisky own NP in Irkutsk native urban2002 and rural/urban2010 registries; own locality article independently fixes Mamsko-Chuisky county and dated2019 abolition; no modern successor invented.',population_boundary_comparability_asserted=False,evidence_file=str(F),evidence_locator=loc))
with gzip.open(O/'identity_point_witnesses.json.gz','wt')as f:json.dump(wit,f,ensure_ascii=False)
pd.DataFrame(edges).to_csv(O/'accepted_identity_edge_delta.csv',index=False);pd.DataFrame(pts).drop_duplicates('target_source_record_id').to_csv(O/'accepted_point_use_delta.csv',index=False);pd.DataFrame(events).to_csv(O/'accepted_typed_lifecycle_event_delta.csv',index=False);pd.DataFrame(status).to_csv(O/'accepted_available_year_statuses.csv',index=False);print(len(edges),len(pts),len(events),len(status))
