from pathlib import Path
import json,gzip,hashlib,re,html
import pandas as pd
R=Path('/workspace/russian-settlements-research');O=Path(__file__).parent;C=R/'research_rebuild/evidence/moscow_large_residual_actionable_20261008'
def sha(p):
 with p.open('rb') as f:return hashlib.file_digest(f,'sha256').hexdigest()
proof=json.loads((C/'ryazanovskoye_complete19_candidate_receipt.json').read_text());native=pd.read_csv(C/'ryazanovskoye_complete19_native_closure.csv').fillna('');assert len(native)==38 and native.source_record_id.nunique()==38 and not native.already_in_stage25_mixed_union.any()
entities=json.load(gzip.open(C/'municipal_entities.json.gz','rt'))['entities'];e=entities['Q5470559'];p625=e['claims']['P625'];assert len(p625)==1
p=p625[0];v=p['mainsnak']['datavalue']['value'];assert e['labels']['ru']['value']=='Поселение Рязановское'
point={'scope_id':'moscow2012_ryazanovskoye_complete19','scope_grain':'whole_transferred_municipal_territory','coordinate_source_record_id':'Q5470559','municipal_entity_label':e['labels']['ru']['value'],'latitude':v['latitude'],'longitude':v['longitude'],'source_declared_precision_degrees':v['precision'],'P625_statement_id':p['id'],'rank':p['rank'],'point_origin_file':str(C/'municipal_entities.json.gz'),'point_origin_sha256':sha(C/'municipal_entities.json.gz'),'point_origin_locator':'entities.Q5470559.claims.P625[0]','point_origin_kind':'wikidata_own_municipal_scope_representative_P625','coordinate_admission_status':'reviewed_secondary_municipal_scope_point_accepted','point_temporal_interpretation':'Modern municipal territorial representative; not measured census-date point','individual_NP_point_uses_created':0,'boundary_comparability_asserted':False}
pd.DataFrame([point]).to_csv(O/'accepted_municipal_representative_points.csv',index=False)
claims={r['year']:r for r in proof['municipal_actual_census_claims']};obs=[]
for y,count,grain in [(2002,14345,'printed_Ryazanovsky_rural_council_complete19_native_roster'),(2010,16500,'published_municipal_Ryazanovskoye_census_total'),(2021,28810,'published_Moscow_Ryazanovskoye_municipal_census_total')]:
 r={'scope_id':point['scope_id'],'observation_id':f"moscow2012_ryazanovskoye_complete19:{y}",'census_year':y,'population':count,'observation_grain':grain,'scope_kind':'complete_transferred_municipal_territory','settlement_name':'Рязановское','settlement_type':'municipal_territorial_scope_not_individual_NP','decision_status':'qualified_accepted_secondary_complete_transferred_municipal_scope','selected_source_record_id':'','is_additive_settlement_record':False,'national2021_credit_population':0,'own_NP_series_asserted':False,'same_place_edge_created':False,'population_boundary_comparability_asserted':False,'modern_boundary_harmonized':False,'municipal_point_scope_id':point['scope_id'],'latitude':v['latitude'],'longitude':v['longitude'],'point_precision_source_degrees':v['precision'],'native_members_count':19 if y in [2002,2010] else 0,'native_constituent_sum':14345 if y==2002 else (16499 if y==2010 else ''),'native_population_and_quality_preserved':True,'municipal_entity':'Q5470559'}
 if y==2002:r.update(population_value_quality='direct_published_rural_council_census_total_complete_native_child_roster',population_source_file=native.raw_source_path.iloc[0],population_source_sha256=native.raw_source_sha256.iloc[0],population_source_locator='Sheet1!C4684; printed Ryazanovsky rural council; all19children4685–4703; nextparent4704',population_date='2002 census',date_precision='census_year',population_references_json='')
 else:
  claim=claims[y];assert any(ref.get('snaks',{}).get('P248') for ref in claim['references'])
  r.update(population_value_quality='secondary_explicit_census_referenced_municipal_total',population_source_file=str(C/'municipal_entities.json.gz'),population_source_sha256=sha(C/'municipal_entities.json.gz'),population_source_locator=claim['statement_id'],population_date=claim['date']['time'],date_precision=claim['date']['precision'],population_references_json=json.dumps(claim['references'],ensure_ascii=False))
 obs.append(r)
pd.DataFrame(obs).to_csv(O/'accepted_transferred_municipal_scope_observations.csv',index=False)
# Constituent selected IDs alone create national old-year credit; municipal observations remain nonadditive.
oldstatus=pd.read_csv(R/'research_rebuild/work/moscow_large_residual_actionable_20261008/remaining_moscow_mixed_uncredited.csv').set_index('source_record_id')
native['native_individual_own_point_available_baseline25']=native.source_record_id.map(lambda sid:bool(oldstatus.loc[sid,'has_own_point']) if sid in oldstatus.index else False)
native['individual_point_status_provenance']='stage24 regional residual snapshot; stage25 accepted deltas contain no MoscowOblastrows; no additional individual points admitted'
native['decision_status']='qualified_accepted_secondary_complete_transferred_municipal_scope_constituent';native['is_exclusive_constituent_at_own_scope']=True;native['is_additive_to_ordinary_selected_denominator']=False;native['point_assigned_to_individual_NP']=False
native.to_csv(O/'accepted_native_scope_constituents.csv',index=False)
# Preserve exact positive legal/membership evidence and actual boundary agreement text, with their separate limitations.
article=(C/'ryazanovskoye_literal_roster_and_transfer_excerpt.txt').read_text();(O/'legal_literal_roster_and_transfer_excerpt.txt').write_text(article)
legal=R/'research_rebuild/evidence/moskovskiy_leninsky_moscow_inclusion_20261005/source_moscow_boundary_agreement.html';text=html.unescape(re.sub('<[^>]+>',' ',legal.read_text()));text=' '.join(text.split());start=text.find('1.Стороны');end=text.find('5.Соглашение',start)
if start<0:start=text.find('1. Стороны')
excerpt=text[start:end] if start>=0 and end>start else text
(O/'actual_2011_boundary_agreement_excerpt.txt').write_text('Actual cached boundary agreement 07December2011№372; source https://moscow-gov.ru/doc/116078; mapped agreement establishes transfer effective1July2012. It does not literally enumerate Ryazanovskoye; the municipality-specific positive membership/whole-transfer evidence is the own municipal article quoting65/2005-ОЗ and official Moscow portal. No map boundary reconstruction asserted.\n\n'+excerpt)
pins=json.loads((C/'closed_scope_source_manifest.json').read_text());pins[str(legal)]=sha(legal)
for p in [C/'ryazanovskoye_complete19_candidate_receipt.json',C/'ryazanovskoye_complete19_native_closure.csv',C/'ryazanovskoye_literal_roster_and_transfer_excerpt.txt']:pins[str(p)]=sha(p)
(O/'source_manifest.json').write_text(json.dumps(pins,ensure_ascii=False,indent=2))
(O/'README.md').write_text('Prepared complete Ryazanovskoye municipal-transfer scope, baseline25.\n\nThree whole-scope observations distinguish the actual2002 printed rural-council census total14345 and later2010/2021 municipal census totals16500/28810. All19 native children in each historical year are complete; their protected2010 sum16499 is preserved separately, with a one-person difference from the municipal count.38 exclusive old selected source IDs are uncredited atbaseline25 and can add national mixed14345/16499 if root integrates this qualified scope.2021 observations are blankselectedID/nonadditive under already credited Moscow; no2021national extra credit.\n\nThis is a distinct transferred municipal territorial/event grain, neither ordinary same-place identity nor ownNP full3 nor named-city merger. The own municipal entity Q5470559 supplies one representative point; its declared precision1/60degree is preserved. It is not assigned to any individual NP. Boundary comparability remains unknown.\n\nLiteral legal roster names, complete source hierarchy, protected native rows, source hashes, actual mapped2011transfer agreement excerpt and municipality-specific published transfer statement are attached. The agreement itself does not enumerate municipalities; the explicit Ryazanovskoye evidence is separately quoted with its original legal/official references. No boundary geometry was reconstructed. Other incomplete transferred scopes remain held in the Moscow residual candidate pack.\n\nRoot integration pending. No loader/report/Git/source/old accepted packet was edited.\n')
receipt={'status':'prepared_reviewed_complete_transferred_municipal_scope_application_root_integration_pending','baseline_stage':25,'scope_id':point['scope_id'],'grain':'complete_transferred_municipal_territory_not_ownNP_or_named_city_merger','scope_observations':3,'native_constituents':38,'complete_members_by_year':{'2002':19,'2010':19},'actual_new_unique_old_selected_population':{'2002':14345,'2010':16499},'national2021_additional_population':0,'ordinary_graph_edges':0,'ordinary_point_uses':0,'ordinary_full3_population_delta':{'2002':0,'2010':0,'2021':0},'municipal2010_minus_native_protected_sum':1,'boundary_comparability':'unknown_not_asserted','protected_native_population_quality_preserved':True,'modernpoint_individual_NP_assignments':0,'source_manifest_sha256':sha(O/'source_manifest.json'),'loader_report_git_mutated':False,'output_sha256':{p.name:sha(p) for p in O.iterdir() if p.is_file() and p.name!='application_receipt.json'}}
(O/'application_receipt.json.tmp').write_text(json.dumps(receipt,ensure_ascii=False,indent=2));(O/'application_receipt.json.tmp').replace(O/'application_receipt.json');print(json.dumps(receipt['actual_new_unique_old_selected_population']))
