from pathlib import Path
import sys,json,re,math,importlib.util
import pandas as pd,duckdb,xlrd
R=Path('/workspace/russian-settlements-research');sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from working_state_20261007 import load
from current_chain_state_20261007 import sha,normalize,distance_km
from apply_unique_county_name_bridge_20261007 import county_key
O=Path(__file__).parent;s=load(39);r=json.loads((O/'application_receipt.json').read_text());sp=importlib.util.spec_from_file_location('root_finite',R/'research_rebuild/evidence/large_native_suffix_and_former_name_application_20261008/apply.py');fm=importlib.util.module_from_spec(sp);sp.loader.exec_module(fm);before=fm.finite_metrics(s);assert before=={'histories':138335,'populations_by_year':{'2002':126682581,'2010':123845680,'2021':124452211}};r['baseline_stage']=39;r['baseline']=s.metrics();r['before_finite_all3_all_points']=before;r['original_candidate_stage']=38;r['input_pins']={str(p):sha(p) for p in s.inputs};r['input_pins'].update({str(O/n):sha(O/n) for n in ['refined_native2010_candidates.csv.gz','all_literal_native2010_source_checks.csv.gz']})
for mapping in ['input_pins','raw_source_pins']:
 for p,h in r[mapping].items():assert sha(Path(p))==h,p
for n,h in r['accepted_ledger_pins'].items():assert sha(O/n)==h,n
edge=O/'accepted_identity_edge_delta.csv.gz';point=O/'accepted_point_use_delta.csv.gz';s.add_deltas([edge],[point]);fa439=fm.finite_metrics(s);assert fa439['histories']-before['histories']==439;assert {y:fa439['populations_by_year'][y]-before['populations_by_year'][y] for y in before['populations_by_year']}=={'2002':10608,'2010':6299,'2021':2500}
e=pd.read_csv(edge,keep_default_na=False).to_dict('records');pp=pd.read_csv(point,keep_default_na=False).to_dict('records');q=pd.read_csv(O/'printed_railway_descriptor_alias_followup_candidates.csv.gz',keep_default_na=False);out=[];holds=[];c=duckdb.connect();SEL=Path('/workspace/settlements-delivery/continuation-consolidated-20261003/selected_observations.parquet');meta=c.execute('select source_record_id,source_sheet,source_row,source_name_raw from read_parquet(?) where census_year=2010',[str(SEL)]).fetchdf().set_index('source_record_id');occupied={(int(s.by_id.loc[sid].census_year),p['latitude'],p['longitude']):sid for sid,p in s.point_rows.items()}
def desc(v):
 t=normalize(v);t=re.sub(r'^(?:ж[.]?\s*д[.]?|ж/д)\s+станц(?:ии|ия)\s+','железнодорожной станции ',t);return re.sub('[^а-яa-z0-9]+',' ',t).strip()
for z in q.to_dict('records'):
 sid,cid,oid=z['target2010_source_record_id'],z['current2021_source_record_id'],z['old2002_source_record_id'];a,cur,old=[s.by_id.loc[x] for x in [sid,cid,oid]];cp,op=[s.point_rows[x] for x in [cid,oid]];key=desc(cur.settlement_name);base=re.sub('^железнодорожной станции ','',key);why=[]
 sourcepeers=s.obs[s.obs.census_year.eq(2010)&s.obs.region_norm.eq(cur.region_norm)&s.obs.settlement_name.map(desc).eq(key)];currentpeers=s.obs[s.obs.census_year.eq(2021)&s.obs.region_norm.eq(cur.region_norm)&s.obs.settlement_name.map(lambda x:desc(x).endswith(base))].copy();competitors=currentpeers[(currentpeers.source_record_id.ne(cid))&(~currentpeers.type_norm.isin(['село','деревня','хутор','аул']))]
 if len(sourcepeers)!=1 or sourcepeers.iloc[0].source_record_id!=sid or len(competitors):why.append('unresolved_source_or_current_physical_role_competitor')
 if s.years[s.uf.find(cid)]!={2002,2021} or s.uf.find(oid)!=s.uf.find(cid) or s.years[s.uf.find(sid)]&{2002,2021}:why.append('repeated_year_or_endpoints')
 if any(x in s.conflicting_point_targets for x in [sid,cid,oid]):why.append('active_point_conflict')
 if distance_km((cp['latitude'],cp['longitude']),(op['latitude'],op['longitude']))>5:why.append('old_current_point_contradiction')
 if (2010,cp['latitude'],cp['longitude']) in occupied and occupied[(2010,cp['latitude'],cp['longitude'])]!=sid:why.append('distinct_2010_ownNP_point_collision')
 if not county_key(a.district_raw) or county_key(a.district_raw)!=county_key(old.district_raw):why.append('native_county_conflict')
 if not all(math.isfinite(float(p[k])) for p in [cp,op] for k in ['latitude','longitude']):why.append('nonfinite_point')
 if not .5<=a.population/old.population<=2 or not .5<=cur.population/a.population<=2:why.append('population_ratio_without_other_strong_owncode')
 m=meta.loc[sid];raw=Path('/workspace/settlements-raw')/a.source_file;book=xlrd.open_workbook(str(raw),on_demand=True);sh=book.sheet_by_name(m.source_sheet);row=int(m.source_row);vals=sh.row_values(row-1);rawlabel=m.source_name_raw
 if sum(isinstance(v,str) and normalize(v)==normalize(rawlabel) for v in vals)!=1 or not any(isinstance(v,(int,float)) and v==a.population for v in vals):why.append('literal_own_label_count_failure')
 headers=[{'row1based':i+1,'caption':v} for i in range(row-1) for v in sh.row_values(i) if isinstance(v,str) and re.search(r'\bрайон\b|\bр-н\b|\bулус\b',normalize(v)) and county_key(v)==county_key(a.district_raw)]
 if not headers:
  schema=[(i,j,sh.cell_value(i,j)) for i in range(min(8,sh.nrows)) for j in range(min(6,sh.ncols)) if normalize(str(sh.cell_value(i,j))) in {'район','р-н','р н'}]
  if schema:
   hi,col,cap=schema[0];parents=[(i+1,sh.cell_value(i,col)) for i in range(hi+1,row) if isinstance(sh.cell_value(i,col),str) and sh.cell_value(i,col).strip() not in ['','–','--','-']]
   if parents and county_key(parents[-1][1])==county_key(a.district_raw):
    num,caption=parents[-1];nextrows=[i+1 for i in range(row,sh.nrows) if isinstance(sh.cell_value(i,col),str) and sh.cell_value(i,col).strip() not in ['','–','--','-']];headers=[{'row1based':num,'caption':caption,'county_column1based':col+1,'column_header_raw':cap,'column_header_row1based':hi+1,'next_block_row1based':nextrows[0] if nextrows else sh.nrows+1,'rule':'literal dedicated county column with next nonblank boundary; selected native county agrees'}]
 if not headers:why.append('no_literal_own_county_header_in_source')
 proof={'raw_target_file':str(raw),'raw_target_sha256':sha(raw),'raw_target_locator':f'sheet={sh.name};row1based={row}','raw_target_label':rawlabel,'raw_population_unmodified':a.population,'source_county':a.district_raw,'literal_parent_header':headers[-1] if headers else None,'typed_descriptor_alias_rule':z['typed_descriptor_alias_rule'],'all_regional_source_role_competitors':sourcepeers.source_record_id.tolist(),'all_current_base_name_competitors':[{'id':x.source_record_id,'name':x.settlement_name,'type':x.type_norm,'county':x.district_raw} for x in currentpeers.itertuples()],'historical_current_point_distance_km':distance_km((cp['latitude'],cp['longitude']),(op['latitude'],op['longitude']))}
 if why:holds.append({**z,'reason':' | '.join(why),'source_proof':json.dumps(proof,ensure_ascii=False)});continue
 s.union(sid,cid);er={'from_source_record_id':sid,'to_source_record_id':cid,'relation':'same_place','decision_status':'checked_rule_accepted','admission_rule':'literal printed railway descriptor abbreviation; whole ownNP label/count and printed county; all regional/current physical-role competitors; accepted02/21 ownpoint continuity <=5km','source_binding_proof':json.dumps(proof,ensure_ascii=False),'population_boundary_comparability_asserted':False,'boundary_comparability':'UNKNOWN','population_values_and_quality':'unchanged_selected_native_sources'};e.append(er)
 p={k:cp.get(k,'') for k in ['latitude','longitude','coordinate_source_record_id','source_sha256','source_locator','point_origin_file','point_origin_sha256','point_origin_locator','point_origin_kind']};p.update(target_source_record_id=sid,coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_binding_rule='retrospective use of independently admitted current ownNP point through native2010 source role and accepted02/21 core',point_use_inference='retrospective_continuity_not_historical_coordinate_measurement',point_claim_quality='auto_rule',population_boundary_comparability_asserted=False);pp.append(p);s.point_rows[sid]=dict(p,point_ledger_path=str(point));out.append({**z,'source_binding_proof':json.dumps(proof,ensure_ascii=False)});r['raw_source_pins'][str(raw)]=sha(raw)
after=s.metrics();fa=fm.finite_metrics(s);pd.DataFrame(e).to_csv(edge,index=False,compression={'method':'gzip','mtime':0});pd.DataFrame(pp).to_csv(point,index=False,compression={'method':'gzip','mtime':0});pd.DataFrame(out).to_csv(O/'accepted_printed_descriptor_alias_witness.csv.gz',index=False,compression={'method':'gzip','mtime':0});pd.DataFrame(holds).to_csv(O/'printed_descriptor_alias_holds.csv.gz',index=False,compression={'method':'gzip','mtime':0});r.update(accepted_edges=len(e),accepted_point_uses=len(pp),after=after,after_finite_all3_all_points=fa,net_finite_all3_all_points={'histories':fa['histories']-before['histories'],'populations_by_year':{y:fa['populations_by_year'][y]-before['populations_by_year'][y] for y in before['populations_by_year']}},net_native_strict_UID_union_gain={y:{'rows':after[y]['covered_rows']-r['baseline'][y]['covered_rows'],'population':after[y]['covered_population']-r['baseline'][y]['covered_population']} for y in after},accepted_ledger_pins={p.name:sha(p) for p in [edge,point]},canonical_loader_replay='passed_actual39_original439_plus_literal_alias_supplement',canonical_source_and_input_hash_validation='passed',descriptor_alias_additional_cases=len(out));s.add_deltas([edge],[point]);assert s.metrics()==after;assert fm.finite_metrics(s)==fa;r['final_combined_CSV_gz_transport_replay']='passed';(O/'application_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2));print(json.dumps({k:r[k] for k in ['accepted_edges','accepted_point_uses','net_finite_all3_all_points','descriptor_alias_additional_cases']}))
