from pathlib import Path
import sys,json,re,collections,ast
import pandas as pd,duckdb
R=Path('/workspace/russian-settlements-research');sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from working_state_20261007 import load
from current_chain_state_20261007 import normalize,sha,distance_km
from apply_unique_county_name_bridge_20261007 import county_key
O=Path(__file__).parent;E=O.parent;s=load(38);pins={str(p):sha(p) for p in s.inputs};before=s.metrics()
DESIGNATOR=r'(?:поселок городского типа|рабочий поселок|дачный поселок|курортный поселок|пгт|рп|кп|дп|город|село|деревня|поселок|хутор|станица|аул|слобода|станция|разъезд|железнодорожная станция|железнодорожный разъезд)'
def namekey(v):
 text=normalize(v);text=re.sub(r'^'+DESIGNATOR+r'\s+','',text);text=re.sub(r'\s*\('+DESIGNATOR+r'\)\s*$','',text);text=re.sub(r'\s*,\s*'+DESIGNATOR+r'\s*$','',text);text=re.sub(r'\s+'+r'(?:пгт|рп|кп|дп)'+r'\s*$','',text);return re.sub(r'[^а-яa-z0-9]+',' ',text).strip()
def code(v):
 if pd.isna(v):return ''
 try:return str(int(v))
 except:return str(v).removesuffix('.0')
neutralfile=E/'cross_county_independent_point_bridge_20261007/build_neutral_subset.py';tree=ast.parse(neutralfile.read_text());pairs=ast.literal_eval(next(x.value for x in tree.body if isinstance(x,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='pairs' for t in x.targets)));neutral={frozenset([county_key(a),county_key(b)]) for a,b in pairs.items()};pins[str(neutralfile)]=sha(neutralfile)
context={}
for p in [Path('/workspace/settlements-work/secondary_2010_county_context_batch_20261007/all_selected_competitor_county_context.csv.gz'),Path('/workspace/settlements-work/cached_wikipedia_history_mass_20261008/refreshed_2010_context/all_selected_competitor_county_context.csv.gz')]:
 pins[str(p)]=sha(p);f=pd.read_csv(p,keep_default_na=False,dtype=str)
 for z in f.to_dict('records'):
  county=z.get('inferred_county_key',z.get('inferred_county',z.get('county','')))
  if county:context[z['source_record_id']]={**z,'context_source_file':str(p)}
o=s.obs[s.obs.census_year.eq(2010)].copy();o['k']=o.settlement_name.map(namekey);o['county']=o.district_raw.map(county_key);blank=o.county.eq('');o.loc[blank,'county']=o.loc[blank,'source_record_id'].map(lambda sid:context.get(sid,{}).get('inferred_county_key',context.get(sid,{}).get('inferred_county',context.get(sid,{}).get('county',''))));o['code']=o.okato.map(code);idx={k:g for k,g in o.groupby(['k','region_norm'])};rows=[];candidates=[];holds=[]
for root,g in s.obs.groupby('root',sort=False):
 if set(g.census_year)!={2002,2021} or len(g)!=2 or not g.is_additive_settlement_record.fillna(False).all() or g.region_norm.isin(['москва','санкт петербург','севастополь','крым']).any():continue
 old=g[g.census_year.eq(2002)].iloc[0];cur=g[g.census_year.eq(2021)].iloc[0];ids=list(g.source_record_id)
 if not all(x in s.point_rows and x not in s.conflicting_point_targets for x in ids):continue
 op,cp=s.point_rows[old.source_record_id],s.point_rows[cur.source_record_id];agreement=distance_km((op['latitude'],op['longitude']),(cp['latitude'],cp['longitude']));keys={namekey(old.settlement_name),namekey(cur.settlement_name)};options={z['source_record_id']:z for key in keys for z in idx.get((key,cur.region_norm),pd.DataFrame()).to_dict('records')};oc,cc=county_key(old.district_raw),county_key(cur.district_raw);compatible=[x for x in options.values() if x['is_additive_settlement_record'] and x['county'] and (x['county'] in {oc,cc} or frozenset([x['county'],oc]) in neutral or frozenset([x['county'],cc]) in neutral)];literal_regionunique=len(options)==1;positive=[]
 for z in options.values():
  sid=z['source_record_id'];years=s.years[s.uf.find(sid)];countyok=z in compatible;mp=s.point_rows.get(sid);pointdist=distance_km((mp['latitude'],mp['longitude']),(cp['latitude'],cp['longitude'])) if mp else None;pops=[old.population,z['population'],cur.population];ratio02=float(z['population']/old.population) if old.population>0 else None;ratio21=float(cur.population/z['population']) if z['population']>0 else None;ratiook=all(x is None or .5<=x<=2 for x in [ratio02,ratio21]);codepositive=bool(z['code']) and z['code'] in {code(old.okato),code(cur.okato)};quality=z['population_value_quality'];row={'old2002_source_record_id':old.source_record_id,'current2021_source_record_id':cur.source_record_id,'target2010_source_record_id':sid,'old2002_name':old.settlement_name,'current_name':cur.settlement_name,'native2010_name':z['settlement_name'],'region':cur.region_norm,'old2002_county':old.district_raw,'current2021_county':cur.district_raw,'native2010_county_printed':z['district_raw'],'native2010_county_context':z['county'],'county_compatible':countyok,'native2010_type':z['settlement_type'],'native2010_is_additive':bool(z['is_additive_settlement_record']),'native2010_population':z['population'],'native2010_population_quality':quality,'old2002_population':old.population,'current2021_population':cur.population,'population_ratio_2010_to2002':ratio02,'population_ratio_2021_to2010':ratio21,'adjacent_population_ratio_0_5_to2_or_actual_zero':ratiook,'actual_zero_observed':any(x==0 for x in pops),'native_own_code_agreement':codepositive,'all_same_normalized_name_region2010_candidates':len(options),'historical_current_point_distance_km':agreement,'native2010_existing_point_distance_km':pointdist,'native2010_component_years':json.dumps(sorted(years)),'component_join_graph_compatible':not ({2002,2021}&years),'native2010_source_file':z['source_file'],'native2010_source_locator':z['source_locator'],'context_proof_json':json.dumps(context.get(sid,{}),ensure_ascii=False),'candidate_only':True};candidates.append(row)
  if literal_regionunique and countyok and agreement<=5 and (pointdist is None or pointdist<=5) and ratiook and not ({2002,2021}&years) and z['is_additive_settlement_record']:positive.append(row)
 route='positive_unique_region_native2010_candidate' if len(positive)==1 else 'regional2010_competing_name_candidates' if len(options)>1 else 'single_native2010_context_ratio_graph_or_point_hold' if options else 'no_literal2010_native_target';rows.append({'current2021_source_record_id':cur.source_record_id,'old2002_source_record_id':old.source_record_id,'name':cur.settlement_name,'old2002_name':old.settlement_name,'region':cur.region_norm,'old2002_county':old.district_raw,'current2021_county':cur.district_raw,'population2002':old.population,'population2021':cur.population,'max_population_weight':max(old.population,cur.population),'point_agreement_km':agreement,'all_region2010_name_candidates':len(options),'county_compatible_candidates':len(compatible),'route':route})
f=pd.DataFrame(rows).sort_values('max_population_weight',ascending=False);cf=pd.DataFrame(candidates);f.to_csv(O/'all_missing2010_components.csv.gz',index=False,compression={'method':'gzip','mtime':0});cf.to_csv(O/'all_regional2010_native_candidates.csv.gz',index=False,compression={'method':'gzip','mtime':0});f.head(100).to_csv(O/'all_components_top100.csv',index=False);pos=cf[cf.current2021_source_record_id.isin(f[f.route.eq('positive_unique_region_native2010_candidate')].current2021_source_record_id)];pos.to_csv(O/'source_positive_unique_region_candidates.csv.gz',index=False,compression={'method':'gzip','mtime':0});summary=f.groupby('route').agg(components=('name','size'),population2002=('population2002','sum'),population2021=('population2021','sum'),max_weight=('max_population_weight','sum')).sort_values('max_weight',ascending=False);summary.to_csv(O/'all_scope_route_summary.csv');r={'stage':38,'scope':'ALL ordinary {2002,2021} components with both accepted ownpoints','components':len(f),'population2002':int(f.population2002.sum()),'population2021':int(f.population2021.sum()),'max_weight':int(f.max_population_weight.sum()),'source_positive_unique_region_candidates':len(pos),'positive_native2010_population':int(pos.native2010_population.sum()),'positive_population2002':int(pos.old2002_population.sum()),'positive_population2021':int(pos.current2021_population.sum()),'baseline':before,'routes':summary.reset_index().to_dict('records'),'input_pins':pins,'candidate_only':True,'source_counts_unchanged':True,'no_network':True};(O/'inventory_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2));print(json.dumps({k:v for k,v in r.items() if k not in ['input_pins','baseline']},ensure_ascii=False))
