from pathlib import Path
import json,gzip,re,sys
import pandas as pd,duckdb
R=Path('/workspace/russian-settlements-research');sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from current_chain_state_20261007 import sha,normalize,distance_km
O=Path(__file__).parent;E=O.parent;f=pd.read_csv(O/'disjoint_cached_claim_inventory.csv.gz',keep_default_na=False);f['current_native_oktmo']=f.current_native_oktmo.astype(str);claims=pd.read_csv(O/'cached_dated2002_claims.csv.gz',keep_default_na=False);claims=claims[claims.explicit_census2002_proof&claims.own_entity_bound];SEL=Path('/workspace/settlements-delivery/continuation-consolidated-20261003/selected_observations.parquet');c=duckdb.connect(config={'threads':1,'memory_limit':'500MB'});native=c.execute('select source_record_id,census_year,settlement_name,settlement_type,region_norm,district_raw,population,population_value_quality,population_scope,is_additive_settlement_record,oktmo,okato,source_file,source_path,source_sha256,source_locator from read_parquet(?)',[str(SEL)]).fetchdf();by=native.set_index('source_record_id');current=native[native.census_year.eq(2021)&native.is_additive_settlement_record.fillna(False)].copy();current['code']=current.oktmo.map(lambda x:str(int(x)) if pd.notna(x) else '');codenum=current[current.code.ne('')].groupby('code').source_record_id.nunique().to_dict();ownerids=set();priorq=set();priorids=set()
for pp in (E/'native2010_remaining_county_rule_mass_20261008').glob('baseline49_union_*.gz'):
 ff=pd.read_csv(pp,dtype=str,keep_default_na=False)
 if 'source_record_id' in ff:priorids.update(ff.source_record_id)

entities={};holds=[];rows=[];credits=[];witness=[];rawpins={};usedq=set();physical={'Q532','Q5084','Q486972','Q2514025','Q15078955','Q24258416','Q27062006','Q27517483'}
for a in f[f.explicit_census2002_unique_population].to_dict('records'):
 if a.get('existing_native2010_current_point_distance_km',0)>5:holds.append({'sid':a['current_source_record_id'],'name':a['name'],'reason':'accepted_native_component_point_contradiction'});continue
 sid=a['current_source_record_id'];nid=a['native2010_source_record_id'];cs=claims[claims.current_source_record_id.eq(sid)];qs=set(cs.qid)
 if sid in ownerids or nid in priorids or qs&priorq:holds.append({'sid':sid,'name':a['name'],'reason':'existing_owner_or_qualified_selectedID_or_QID_credit'});continue
 if len(qs)!=1:holds.append({'sid':sid,'name':a['name'],'reason':'multiple_bound_own_QIDs_for_same2002_population'});continue
 q=next(iter(qs));claim=cs.iloc[0].to_dict();path=Path(claim['raw_entity_file'])
 if path not in entities:
  b=path.read_bytes();assert sha(path)==claim['raw_entity_sha256'];d=json.loads(gzip.decompress(b) if path.name.endswith('.gz') else b);entities[path]=d.get('entities',d.get('payload',{}).get('entities',{}));rawpins[str(path)]=sha(path)
 entity=entities[path][q];p31={x.get('mainsnak',{}).get('datavalue',{}).get('value',{}).get('id') for x in entity.get('claims',{}).get('P31',[]) if x.get('rank')!='deprecated'};label=entity.get('labels',{}).get('ru',{}).get('value','');desc=entity.get('descriptions',{}).get('ru',{}).get('value','');names={normalize(label)}|{normalize(x['value']) for x in entity.get('aliases',{}).get('ru',[])};nameexact=bool({normalize(a['name']),normalize(a['native2010_name'])}&names)
 if a['post2002_foundation_cached']:holds.append({'sid':sid,'name':a['name'],'reason':'cached_post2002_foundation_conflicts_with2002_identity','qid':q});continue
 if not nameexact:holds.append({'sid':sid,'name':a['name'],'reason':'current_native_own_name_not_explicit_cached','qid':q});continue
 if re.match(r'^(?:муниципал|городской округ|сельское поселение|район\b|сельсовет|часть города|квартал|микрорайон)',desc,re.I):holds.append({'sid':sid,'name':a['name'],'reason':'cached_item_admin_or_subdivision_grain','qid':q});continue
 if not p31&physical and not re.match(r'^(?:село|деревня|пос[её]лок|хутор|станица|аул|сельский насел)',desc,re.I):holds.append({'sid':sid,'name':a['name'],'reason':'own_populated_locality_class_not_explicit_cached','qid':q,'P31':json.dumps(sorted(p31))});continue
 if codenum.get(a['current_native_oktmo'],0)!=1:holds.append({'sid':sid,'name':a['name'],'reason':'native2021_same_own_OKTMO_competition','qid':q});continue
 if q in usedq:raise ValueError('Repeated QID')
 statementid=re.search(r'\[(.*)\]$',claim['raw_locator']).group(1);st=next(x for x in entity['claims']['P1082'] if x.get('id')==statementid);assert float(st['mainsnak']['datavalue']['value']['amount'])==claim['population2002'];assert not st.get('qualifiers',{}).get('P518') and st.get('rank')!='deprecated';assert any(x.get('datavalue',{}).get('value',{}).get('time')==claim['date'] for x in st['qualifiers']['P585'])
 for tid,pop,yy in [(sid,a['population2021'],2021),(nid,a['population2010'],2010)]:assert by.loc[tid,'population']==pop and by.loc[tid,'census_year']==yy and by.loc[tid,'is_additive_settlement_record']
 point={'target_source_record_id':sid,'latitude':a['current_point_latitude'],'longitude':a['current_point_longitude'],'coordinate_source_record_id':a['current_point_source_record_id'],'point_origin_file':a['current_point_origin_file'],'point_origin_sha256':a['current_point_origin_sha256'],'point_origin_locator':a['current_point_origin_locator']};tid='cached_current_bound02:'+q;scope='cached_current_bound_secondary2002_mass_20261008';proofclass='actual_P585_year2002_with_literal_P459_census_method' if 'Q39825' in json.loads(claim['P459_method_ids_json']) else 'exact2002_census_date' if str(claim['date']).startswith('+2002-10-09') else 'literal_cached2002_census_reference_label_or_title_or_URL'
 common={'trajectory_id':tid,'settlement_name':a['name'],'region_norm':a['region'],'county_context':a['current_county'],'latitude':a['current_point_latitude'],'longitude':a['current_point_longitude'],'decision_status':'qualified_accepted_secondary_census_referenced_own_item','ordinary_NP3_asserted':False,'boundary_comparability_asserted':False,'point_binding_json':json.dumps(point,ensure_ascii=False),'scope':scope,'boundary_comparability':'UNKNOWN','wikidata_id':q,'own_item_binding':'direct_admitted_own_point_QID_or_exact_native_own_code_and_cached_own_P625_within1km','own_physical_description':desc,'own_code_positive':claim['native_code_exact_cached_claim'],'own_name_or_alias_positive':nameexact,'admin_source_positive':False,'optional_Wiki_coordinates_imported':False,'coordinate_bounds':'UNKNOWN','error_rate':'uncalibrated','accepted_physical_three_observed_census_year_path':True,'accepted_scoped_representative_point':True,'population_primary_reference_verified':False,'native_current_source_record_id':sid,'point_origin_file':a['current_point_origin_file'],'point_origin_sha256':a['current_point_origin_sha256'],'point_origin_locator':a['current_point_origin_locator'],'historical_point_direct_measurement_asserted':False,'source_population_is_census_known':True,'creation_or_status_date_after2002_requires_boundary_review':a['post2002_foundation_cached']}
 for yy,oid,pop in [(2002,'',claim['population2002']),(2010,nid,a['population2010']),(2021,sid,a['population2021'])]:
  n=by.loc[oid] if oid else None;nativeflag=bool(oid);source='/workspace/settlements-raw/'+str(n.source_file) if nativeflag else str(path);hash=str(n.source_sha256) if nativeflag and pd.notna(n.source_sha256) else ('' if nativeflag else claim['raw_entity_sha256']);locator=str(n.source_locator) if nativeflag and pd.notna(n.source_locator) else ('selected own census source_record_id='+oid if nativeflag else claim['raw_locator']);nativecontext={'name':n.settlement_name,'type':n.settlement_type,'region':n.region_norm,'county':str(n.district_raw),'quality':n.population_value_quality,'scope':str(n.population_scope)} if nativeflag else {}
  rows.append({**common,'year':yy,'population_source_value':pop,'source_record_id':oid,'population_quality':n.population_value_quality if nativeflag else 'secondary_explicit_census_reference_date_or_title_primary_not_independently_verified','grain':'own physical locality selected native census observation' if nativeflag else 'own physical locality actual dated secondary census observation','nonadditive_observation':not nativeflag,'source_path':source,'source_sha256':hash,'source_locator':locator,'retrospective_point_use_is_continuity_inference':yy!=2021,'selected_credit_previously_present':False,'selected_source_sha256_as_loaded':hash if nativeflag else '', 'declared_date':f'+{yy}-00-00T00:00:00Z' if nativeflag else claim['date'],'date_precision':9 if nativeflag else claim['precision'],'census_proof_class':'existing_selected_native_census_row_in_accepted_own_NP_component' if nativeflag else proofclass,'census_reference_titles_json':'[]' if nativeflag else claim['reference_titles_json'],'P248_ids_json':'[]' if nativeflag else claim['reference_ids_json'],'P248_labels_json':'[]' if nativeflag else claim['reference_item_labels_json'],'reference_urls_json':'[]' if nativeflag else claim['reference_urls_json'],'statement_id':'' if nativeflag else statementid,'raw_secondary_statement_json':'' if nativeflag else claim['raw_statement_json'],'P459_method_ids_json':'[]' if nativeflag else claim['P459_method_ids_json'],'historical_native_selected_source_ID_binding_asserted':nativeflag and yy!=2021,'native_existing_component_binding':nativeflag,'native_population_scope_legacy_null':nativeflag and pd.isna(n.population_scope),'native_source_context_json':json.dumps(nativecontext,ensure_ascii=False)})
  if nativeflag:credits.append({'source_record_id':oid,'year':yy,'source_population':pop,'trajectory_id':tid,'scope':scope,'previously_credited':oid in priorids,'net_new_selected_ID_credit':oid not in priorids})
 witness.append({'current_source_record_id':sid,'native2010_source_record_id':nid,'qid':q,'label':label,'description':desc,'physical_P31_ids':json.dumps(sorted(p31)),'own_native2021_code_competitors':codenum[a['current_native_oktmo']],'native2021_own_code':a['current_native_oktmo'],'own_point_direct_QID':claim['bound_by_direct_point_QID'],'own_P625_within1km':claim['own_P625_within1km'],'2002_statement_id':statementid,'explicit2002_census_proof_class':proofclass,'entity_source':str(path),'entity_sha256':claim['raw_entity_sha256'],'native_identity_edges_or_point_ledger_modified':False,'post2002_creation_or_status_dates':a['cached_foundation_dates_json']});usedq.add(q)
out=pd.DataFrame(rows,columns=list(rows[0]) if rows else ['year','source_record_id','nonadditive_observation','population_source_value']);cr=pd.DataFrame(credits,columns=list(credits[0]) if credits else ['source_record_id','year','source_population','trajectory_id','scope','previously_credited','net_new_selected_ID_credit']);assert cr.source_record_id.is_unique and out[out.year.eq(2002)].source_record_id.eq('').all() and out[out.year.eq(2002)].nonadditive_observation.all();out.to_csv(O/'accepted_qualified_physical_observations.csv',index=False);cr.to_csv(O/'accepted_selected_source_id_credit_union.csv',index=False);pd.DataFrame(witness).to_csv(O/'qualified_own_source_binding_witness.csv',index=False);pd.DataFrame(holds).to_csv(O/'qualified_packet_holds.csv',index=False);receipt={'baseline_stage':'explicit51+frozen52+six_cached_alias_native','qualified_series':len(usedq),'qualified_observations':len(out),'secondary2002_nonadditive_population_display_only':int(out.loc[out.year.eq(2002),'population_source_value'].sum()),'net_selected_source_ID_credit_by_year':{str(y):{'rows':int(cr.year.eq(y).sum()),'population':int(cr.loc[cr.year.eq(y),'source_population'].sum())} for y in [2002,2010,2021]},'ordinary_NP3_edges_or_points_added':0,'historical_native2002_UID_binding_asserted':False,'population_primary_reference_verified':False,'historical_coordinate_measurement_asserted':False,'point_quality':'auto_rule_continuity_inference','boundary_comparability':'UNKNOWN','new_API_requests':0,'selected_source_sha256':sha(SEL),'no_previous_qualified_QID_overlap':True,'input_pins':{**json.loads((O/'receipt.json').read_text())['input_pins'],**rawpins},'output_hashes':{p.name:sha(p) for p in [O/'accepted_qualified_physical_observations.csv',O/'accepted_selected_source_id_credit_union.csv',O/'qualified_own_source_binding_witness.csv']}};(O/'qualified_application_receipt.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2));print(json.dumps({k:v for k,v in receipt.items() if k not in ['input_pins','output_hashes']},ensure_ascii=False))
