from pathlib import Path
import sys,ast,json,re,collections
import duckdb,pandas as pd
R=Path('/workspace/russian-settlements-research');O=Path(__file__).parent;AL=O.parent/'temporal_source_alias_reserve_20261008';B=O.parent/'grounded_current_carrier_expansion_20261008';A=O.parent/'main_axis_residual_application65_20261008';sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from current_chain_state_20261007 import normalize,sha,distance_km
from apply_unique_county_name_bridge_20261007 import county_key
tree=ast.parse((B/'discover_closed_geometry.py').read_text());exec(compile(ast.Module(body=[n for n in tree.body if isinstance(n,ast.FunctionDef) and n.name in ['nm','ty']],type_ignores=[]),'closed_names','exec'))
OBS=A/'applied_state_observations.parquet';P=A/'applied_point_snapshot.parquet';F=A/'applied_remaining_primary.csv.gz';G=O.parent/'temporal_after_new_current_points_20261008/resolved_candidate_geometry.parquet';S=Path('/workspace/settlements-delivery/continuation-consolidated-20261003/selected_observations.parquet');K=Path('/workspace/settlements-work/grounded_current_carrier_expansion_20261008/source_positive_coded_current_candidates.parquet');RAW=Path('/workspace/settlements-raw/data/interim/2021_tochno/data_allsettlements_anon_156_v20251217.parquet');c=duckdb.connect();c.execute("set memory_limit='768MB'");c.execute("set threads=1");c.execute("set preserve_insertion_order=false");c.execute('create view obs as select * from read_parquet(?)'.replace('?', "'"+str(OBS).replace("'","''")+"'"));c.execute('create view geom as select * from read_parquet(?)'.replace('?', "'"+str(G).replace("'","''")+"'"));c.execute('create view points as select target_source_record_id,latitude,longitude from read_parquet(?)'.replace('?', "'"+str(P).replace("'","''")+"'"));c.execute('create view remainder as select source_record_id from read_csv_auto(?)'.replace('?', "'"+str(F).replace("'","''")+"'"));c.execute('create view coded as select target_source_record_id from read_parquet(?)'.replace('?', "'"+str(K).replace("'","''")+"'"));c.execute('create view rawcurrent as select row_number()over() rn,okato_dadata from read_parquet(?)'.replace('?', "'"+str(RAW).replace("'","''")+"'"));c.execute('create view captions as select source_record_id,source_name_raw from read_parquet(?)'.replace('?', "'"+str(S).replace("'","''")+"'"));query="""
select a.source_record_id from_source_record_id,b.source_record_id to_source_record_id,a.census_year from_year,a.settlement_name from_name,b.settlement_name to_name,a.settlement_type from_type,b.settlement_type to_type,a.district_raw from_county,b.district_raw to_county,a.region_norm region,a.population from_population,b.population to_population,a.root old_root,b.root current_root,g.*,p.latitude grounded_current_latitude,p.longitude grounded_current_longitude,cap.source_name_raw native_source_caption
from obs a join remainder r using(source_record_id) join geom g using(source_record_id) join obs b on b.census_year=2021 and b.region_norm=a.region_norm and b.is_additive_settlement_record join points p on p.target_source_record_id=b.source_record_id left join captions cap on cap.source_record_id=a.source_record_id
where a.census_year in (2002,2010) and a.is_additive_settlement_record and a.root<>b.root and g.provider='RCSI' and regexp_full_match(cast(g.source_own_code as varchar),'[0-9]{11}') and cast(g.source_own_code as varchar)=regexp_replace(cast(b.oktmo as varchar),'\\.0$','')
union all
select a.source_record_id from_source_record_id,b.source_record_id to_source_record_id,a.census_year from_year,a.settlement_name from_name,b.settlement_name to_name,a.settlement_type from_type,b.settlement_type to_type,a.district_raw from_county,b.district_raw to_county,a.region_norm region,a.population from_population,b.population to_population,a.root old_root,b.root current_root,g.*,p.latitude grounded_current_latitude,p.longitude grounded_current_longitude,cap.source_name_raw native_source_caption
from obs a join remainder r using(source_record_id) join geom g using(source_record_id) join rawcurrent rr on cast(g.source_own_code as varchar)=regexp_replace(cast(rr.okato_dadata as varchar),'\\.0$','') join obs b on b.census_year=2021 and cast(split_part(b.source_record_id,':',-1) as bigint)=rr.rn and b.region_norm=a.region_norm and b.is_additive_settlement_record join coded k on k.target_source_record_id=b.source_record_id join points p on p.target_source_record_id=b.source_record_id left join captions cap on cap.source_record_id=a.source_record_id
where a.census_year in (2002,2010) and a.is_additive_settlement_record and a.root<>b.root and g.provider='GeoKLADR2011'
""";d=c.execute(query).fetchdf();c.close();caption128={};pins={str(q):sha(q) for q in [OBS,P,F,G,S,K,RAW,A/'application_receipt.json']}
for q in [O.parent/'original_2002_population_control_residual_20261008/finalized_stage64_source100/accepted_source_observation_metadata_100.csv',O.parent/'residual_source_followup_20261008/finalized_Tver28_source_addon/accepted_Tver28_source_metadata.csv']:
 pins[str(q)]=sha(q);caption128.update(pd.read_csv(q,keep_default_na=False).set_index('source_record_id').source_name_raw.to_dict())
roots=set(d.old_root)|set(d.current_root);cc=duckdb.connect();cc.execute("set memory_limit='128MB'");cc.register('neededroots',pd.DataFrame({'root':list(roots)}));rootyears=cc.execute('select o.root,list(o.census_year) component_years,list(o.source_record_id) ids from read_parquet(?) o join neededroots n using(root) group by o.root',[str(OBS)]).fetchdf().set_index('root').to_dict('index');cc.close();event=set()
for q in [O.parent/'main_axis_residual_application63_20261008/lifecycle_round2_accepted_source_UID_credit_union.csv',O.parent/'remaining_large_lifecycle_residual_20261008/accepted_direct_event_native_credit_union.csv']:
 if q.exists():pins[str(q)]=sha(q);event.update(pd.read_csv(q).source_record_id)
for n in ['direct_inclusion_transformation_path_native_credit_union.csv','formation_path_native_credit_union.csv','named_merger_lineage_constituents.csv','complete_territorial_scope_constituents.csv','complete_publisher_partition_members.csv']:
 q=O.parent/'working_full_chain_20261007'/n
 if q.exists():pins[str(q)]=sha(q);event.update(pd.read_csv(q).source_record_id)
event.add('2002:010_3e630cc803_02c_Moskovskaya-oblast.xls:Sheet1:3968');rows=[];held=[];counts=collections.Counter()
for z in d.astype(object).where(pd.notna(d),'').to_dict('records'):
 sid=z['from_source_record_id'];cap=caption128.get(sid,z['native_source_caption']);reason=[];prov=z['provider'];code=str(z['source_own_code']);name=z['raw_classifier_name'] if prov=='GeoKLADR2011' else z['source_name'];dc=distance_km((float(z['latitude']),float(z['longitude'])),(float(z['grounded_current_latitude']),float(z['grounded_current_longitude'])));hc=county_key(z['from_county']);mc=county_key(z['to_county']);sc=county_key(z['source_county']);ids=list(rootyears[z['old_root']]['ids'])+list(rootyears[z['current_root']]['ids']);years=list(rootyears[z['old_root']]['component_years'])+list(rootyears[z['current_root']]['component_years'])
 if re.search(r'\b(?:часть|части|частью|всего|население)\b',normalize(cap)):reason.append('explicit statisticalpart/aggregate sourcecaption excludes wholeNP identity')
 if not z['physical_NP_positive'] or nm(name)!=nm(z['from_name']):reason.append('published named-code sourcebody not literal whole nativeoldNP')
 if dc>5 and (not hc or hc!=mc):reason.append('far unacceptedcandidate lacks positiveprintedhistorical/currentcounty agreement')
 if sc and mc and sc!=mc:reason.append('sourcebody/currentcounty contradiction withoutdatedtransferproof')
 if len(set(years))!=len(years):reason.append('actualsameyear componentrepetition')
 if any(i in event for i in ids):reason.append('published nonordinary lifecycle/territorialscope')
 rec={**z,'candidate_geometry_only_nohistoricalmeasurement':True,'historical_native_code_asserted':False,'published_modern_named_object_code':code,'modern_code_namespace_route':'modern_RCSI_own_OKTMO_to_actual_current_native_own_OKTMO' if prov=='RCSI' else 'dated_Geo2011_CP2009_NP_OKATO_to_current_sourcepositive_owncoded_FIAS_NP','code_provider_identifier_transfer_asserted':False,'literal_native_names_equal':nm(z['from_name'])==nm(z['to_name']),'oldsource_coordinate_distance_to_current_km':dc,'old_far_unaccepted_geometry_not_hard_contradiction':dc>5,'positive_printed_historical_county':hc,'component_source_ids_json':json.dumps(ids),'native_source_caption':cap}
 if reason:held.append({**rec,'held_reason':'; '.join(reason)});counts.update(set(reason))
 else:rows.append(rec)
for n,x,cols in [('candidate_identity_pairs.csv.gz',rows,['from_source_record_id']),('held_code_alias_routes.csv.gz',held,['from_source_record_id','held_reason'])]:pd.DataFrame(x,columns=None if x else cols).to_csv(O/n,index=False,compression={'method':'gzip','mtime':0})
r={'baseline_stage':65,'candidate_pairs':len(rows),'held_pairs':len(held),'accepted_edges':0,'accepted_points':0,'query_join_route_rows':len(d),'memory_limit_sql_MB':768,'all_actual128_sourceobs_included':True,'explicit_partialcaption_excluded_beforealiasnormalization':True,'old_candidate_population_by_year':{str(y):sum(float(z['from_population']) for z in rows if int(z['from_year'])==y) for y in [2002,2010]},'literal_candidate_pairs':sum(z['literal_native_names_equal'] for z in rows),'different_name_codealias_pairs':sum(not z['literal_native_names_equal'] for z in rows),'far_unaccepted_old_candidate_pairs_positivecountycode':sum(z['old_far_unaccepted_geometry_not_hard_contradiction'] for z in rows),'outcomes':dict(counts),'sourcepublished_code_is_modern_object_code_not_native_historical_code':True,'no_State_load':True,'input_pins':pins,'output_pins':{q.name:sha(q) for q in O.glob('*.csv.gz')}};(O/'candidate_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n');print(json.dumps({k:v for k,v in r.items() if k not in ['input_pins','output_pins']},ensure_ascii=False))
