from pathlib import Path
import pandas as pd,json,gzip,hashlib,re,xlrd
O=Path(__file__).parent;A=Path('research_rebuild/evidence/over500_east_exact_duplicate_point_sources_20261009');sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();D=pd.read_pickle('/dev/shm/over500-20261009/east_enriched.pkl');C=pd.read_csv('/dev/shm/over500-20261009/seventh-application/over500_exact_coordinate_collisions.csv');C=C[C.region_norm.isin(['бурятия','свердловская'])];P=pd.read_parquet('/dev/shm/over500-20261009/seventh-application/applied_point_snapshot.parquet').set_index('target_source_record_id');R=[];N=[];W=[];raw=[]
for _,t in C.iterrows():
 sid=t.source_record_id;q=P.loc[sid];ledger=Path(q.point_ledger_path);old=(pd.read_parquet(ledger)if ledger.suffix=='.parquet'else pd.read_csv(ledger,keep_default_na=False)).set_index('target_source_record_id').loc[sid];assert sha(old.point_origin_file)==old.point_origin_sha256
 title={'Михайловка':'Михайловка (Закаменский район)','Хуртага':'Хуртага','Починок':'Починок (Свердловская область)','Тарасково':'Тарасково (Свердловская область)'}[t.settlement_name];f=A/('pochinok_own_article.json.gz'if t.settlement_name=='Починок'else'qualified_four_articles.json.gz');j=json.load(gzip.open(f));page=next(v for v in j['query']['pages'].values()if v['title']==title);txt=page['revisions'][0]['slots']['main']['*'] if '*'in page['revisions'][0]['slots']['main']else page['revisions'][0]['slots']['main']['content'];assert ('Закаменск'if t.region_norm=='бурятия'else'Новоуральск')in txt
 def coord(axis):
  vals={k:float(v.replace(',','.'))for k,v in re.findall(r'\|\s*'+axis+r'_(deg|min|sec)\s*=\s*([0-9.,]+)',txt)};assert 'deg'in vals;return vals['deg']+vals.get('min',0)/60+vals.get('sec',0)/3600
 lat,lon=coord('lat'),coord('lon');assert abs(lon-float(old.longitude))>.05;wi=len(W);reason='Knownwrong sharedcoordinate contradicted by direct qualifiedown article/county/site and independent ownnamed residential OSM footprint. Duplicate alone was not rejectionbasis. Each of the two named physicallocalities has distinct ownsite; inheritedWikidata oldpoint lies outside bothownsite positions. Withdraw onlycoordinate claim; identity/counts unchanged.'
 nf=Path('/workspace/settlements-raw')/t.source_file
 if t.census_year==2021:
  x=pd.read_parquet(nf,columns=['oktmo','okato_dadata','mun_lower','settlement','population']).iloc[int(sid.rsplit(':',1)[1])-1];cells=x.fillna('').to_dict()
 else:
  sh=xlrd.open_workbook(str(nf)).sheet_by_name(sid.rsplit(':',2)[1]);cells=sh.row_values(int(sid.rsplit(':',1)[1])-1)
 raw.append(dict(source_record_id=sid,native_file=str(nf),native_sha256=sha(nf),raw_values=cells));W.append(dict(target_source_record_id=sid,active_claim=old.to_dict(),ledger=str(ledger),ledger_sha256=sha(ledger),actual_qualified_own_article_page=page,source_file=str(f),source_sha256=sha(f),independent_OSM_source_receipt=str(A/'receipt.json'),independent_OSM_receipt_sha256=sha(A/'receipt.json'),reason=reason,corrected_latitude=lat,corrected_longitude=lon))
 R.append(dict(target_source_record_id=sid,rejection_status='reviewed_rejected_coordinate_claim_only',old_latitude=old.latitude,old_longitude=old.longitude,origin_ledger=str(ledger),origin_ledger_sha256=sha(ledger),old_point_origin_file=old.point_origin_file,old_point_origin_sha256=old.point_origin_sha256,old_point_origin_locator=old.point_origin_locator,old_coordinate_source_record_id=old.coordinate_source_record_id,rejection_reason=reason,evidence_file=str(O/'point_correction_witnesses.json.gz'),evidence_locator=f'[{wi}]'))
 N.append(dict(target_source_record_id=sid,latitude=lat,longitude=lon,coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_source_record_id=f'wikipedia:ru:pageid={page["pageid"]}',point_origin_file=str(f),point_origin_sha256=sha(f),point_origin_locator=f'query.pages[{page["pageid"]}].revisions[0].slots.main;owninfoboxcoordinate',point_origin_kind='direct_qualified_own_article_point',coordinate_binding_rule='Literal nativeownname and qualified samecounty/localphysicaltype bind independentownarticle; sourceyear continuity follows existing admitted ownidentity component. Correct ownsite independently corroborated by named residentialOSM footprint; wrongsharedWikidata claim rejected separately.',point_use_inference='Explicit representative ownsite point inference, retrospective for historicalobservations; exactcensusday and boundaries unknown.',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,external_provider_ID_binding_asserted=True,evidence_file=str(O/'point_correction_witnesses.json.gz'),evidence_locator=f'[{wi}]'))
R=pd.DataFrame(R);R.to_csv(O/'accepted_point_rejection_delta.csv',index=False);back=pd.read_csv(O/'accepted_point_rejection_delta.csv');assert all(float(a)==float(b)for a,b in zip(back.old_latitude,R.old_latitude))and all(float(a)==float(b)for a,b in zip(back.old_longitude,R.old_longitude));pd.DataFrame(N).to_csv(O/'accepted_point_use_delta.csv',index=False);pd.DataFrame(columns=['from_source_record_id','to_source_record_id','relation','decision_status','admission_method','admission_rule','evidence_file','evidence_locator']).to_csv(O/'accepted_identity_edge_delta.csv',index=False);pd.DataFrame([dict(source_record_id=n['target_source_record_id'],disposition='withdraw_wrongsharedpoint_replace_independent_qualifiedownsite',population_values_modified=False,identity_edges_added=False)for n in N]).to_csv(O/'record_dispositions.csv',index=False)
for f,v in [('point_correction_witnesses.json.gz',W),('native_source_witnesses.json.gz',raw)]:
 with gzip.open(O/f,'wt')as z:json.dump(v,z,ensure_ascii=False)
m=dict(active_point_rejections=len(R),accepted_own_point_uses=len(N),identity_edges_added=0,population_values_modified=False,apply_order='reject_points_before_admit_replacements',validation=dict(exact_active_ledger_hashes_checked=True,rejection_parser_float_equality=True,native_rows_reopened=True,direct_own_article_site_and_county_checked=True),frozen_files=[dict(name=f.name,sha256=sha(f),bytes=f.stat().st_size)for f in sorted(O.iterdir())if f.is_file()]);(O/'freeze_manifest.json').write_text(json.dumps(m,ensure_ascii=False,indent=2));print(len(N))
