exec(open('/workspace/settlements-work/large_absorbed_city_closed_scope_mass_20261008/scan.py').read().split('configs=')[0].replace('s=load();', 's=load(stage=37);'))
import math,collections,hashlib
O=E/'next_absorbed_city_closed_scopes_followup_20261008';REPORT=E/'working_full_chain_20261007';from current_chain_state_20261007 import sha
cfg=[('Тольятти','самарская',6909,6918,'053_f7f2b62d26_Samarskaja_new.xls',27,29,'016_802d308e41_8._20Or_Penz_Perm_Samar_Saratov_Uly_2010.xls','!!!',0,0,719632,0),('Улан-Удэ','бурятия',8184,8196,'063_3ec7f8316e_buriatia1.xls',4,18,'008_342f3c208b_16._20Сиб_ФО_2010.xls','Sib',11202,11202,404426,0),('Пермь','пермский',6643,6656,'051_46e3ecb0a0_02c_Permskaja_obl.xls',3,5,'016_802d308e41_8._20Or_Penz_Perm_Samar_Saratov_Uly_2010.xls','!!!',7787,7789,991170,8)]
prior=set();f=s.obs.assign(root=s.obs.source_record_id.map(s.uf.find),point=s.obs.source_record_id.isin(s.point_rows),finite=s.obs.population.notna());ag=f.groupby('root').agg(years=('census_year','nunique'),point=('point','all'),finite=('finite','all'));roots=set(ag.index[(ag.years==3)&ag.point&ag.finite]);prior.update(f.loc[f.root.isin(roots),'source_record_id'])
for filename in ['complete_publisher_partition_members.csv','qualified_scope_source_id_credit_union.csv','named_merger_lineage_constituents.csv']:prior.update(pd.read_csv(REPORT/filename).source_record_id)
for folder in ['large_absorbed_city_closed_scope_application_20261008','remaining_absorbed_city_published_closures_application_20261008','nakhoda_complete_published_scope_aux5_application_20261008','city_territory_mass_followup_application_20261008','city_territory_mass_final_two_application_20261008','next_absorbed_city_closed_scopes_application_20261008']:
 prior.update(pd.read_csv(E/folder/'accepted_constituent_credit_union.csv').source_record_id)
for folder in ['complete_transferred_municipal_scope_application_20261008','moscow_complete_scope_mass_application_20261008']:
 prior.update(pd.read_csv(E/folder/'accepted_native_scope_constituents.csv').source_record_id)
text=Path('/workspace/settlements-work/large_absorbed_city_closed_scope_mass_20261008/tom1.txt').read_text();controls=[];members=[];groups=[];points=[];proof=[];net=[];holds=[];hashcache={}
def h(p):
 if str(p) not in hashcache:hashcache[str(p)]=sha(p)
 return hashcache[str(p)]
for city,region,start,end,ruralfile,ra,rb,file2010,sheet2010,cstart,cend,parent2010,ruralcontrol2010 in cfg:
 group='published_closed_city_scope_'+city.replace('-','_');cityrows=o[o.name_norm.str.replace('-',' ',regex=False).eq(city.lower().replace('ё','е').replace('-',' '))&o.region_norm.eq(region)&o.type_norm.eq('город')]
 if len(cityrows)!=3:holds.append({'city':city,'reason':'owncitythree selectedrows notunique','hits':len(cityrows)});continue
 current=cityrows[cityrows.census_year.eq(2021)].iloc[0];p=s.point_rows[current.source_record_id];ownmembers={};selected2002=o[o.census_year.eq(2002)&o.source_file.eq('data/raw/2002_official_tom1/1_TOM_01_04.xls')&o.source_row.between(start,end)&o.is_additive_settlement_record]
 assert all('с подчиненными' not in z for z in selected2002.source_name_raw)
 rural=o.iloc[:0]
 if ruralfile:
  rural=o[o.census_year.eq(2002)&o.source_file.eq('data/raw/2002/'+ruralfile)&o.source_row.between(ra,rb)&o.is_additive_settlement_record]
 ownmembers[2002]=pd.concat([selected2002,rural]);total2002=int(ownmembers[2002].population.sum());parent2002=int(sh.cell_value(start-1,1))
 if total2002!=parent2002:holds.append({'city':city,'reason':'2002closure mismatch','atomic':total2002,'parent':parent2002});print('HOLD2002',city,total2002,parent2002,flush=True);continue
 # Closed original2010 rawcityblock: propercity then allsmall ruralchildren until nextcity; parent/rural controls from primarytable5.
 raw2010book=xlrd.open_workbook('/workspace/settlements-raw/data/raw/2010/'+file2010);raw2010sheet=raw2010book.sheet_by_name(sheet2010);regional2010=o[o.census_year.eq(2010)&o.source_file.eq('data/raw/2010/'+file2010)&o.source_sheet.eq(sheet2010)&o.source_row.between(cstart+1,cend)&o.is_additive_settlement_record]
 if city=='Волжский':
  extra=o[o.census_year.eq(2010)&o.region_norm.eq(region)&o.name_norm.eq('краснооктябрьский')&o.type_norm.eq('пгт')];assert len(extra)==1 and int(extra.iloc[0].population)==12834;assert len(regional2010)==0
 else:
  extra=o.iloc[:0]
  if len(regional2010)!=cend-cstart and city!='Пермь':
   missing=set(range(cstart+1,cend+1))-set(regional2010.source_row.astype(int));holds.append({'city':city,'reason':'original2010roster contains selectednative omissions requiring actualaux or primaryoverrides','missing_raw_rows_json':json.dumps([{'row':n,'original_row':raw2010sheet.row_values(n-1)[:11]} for n in sorted(missing)],ensure_ascii=False)});print('HOLD2010',city,sorted(missing),flush=True);continue
 ownmembers[2010]=pd.concat([cityrows[cityrows.census_year.eq(2010)],extra,regional2010]);primary2010=cityrows[cityrows.census_year.eq(2010)].iloc[0];lines=text.splitlines();hits=[(n,l) for n,l in enumerate(lines) if re.match(r'^\s*г\.\s+'+re.escape(city)+r'\s+с подчиненными',l)] if city=='Пермь' else [(n,l) for n,l in enumerate(lines) if re.match(r'^\s*г\.\s+'+re.escape(city)+r'\s+'+str(parent2010)+r'\s',l)];assert hits
 n,line=hits[0];above='\n'.join(lines[max(0,n-2):n]);below='\n'.join(lines[n+1:n+23]);assert str(parent2010) in (line+'\n'+below) and (str(ruralcontrol2010) in below if ruralcontrol2010 else True)
 pc=parent2010
 ownnames2002=set(zip(rural.type_norm,rural.name_norm));ownnames2010=set(zip(regional2010.type_norm,regional2010.name_norm))
 # Kopeysk/Artyomrural rosters explicitlyequal across2002/2010/current; Nakhoda2002contains twoabsorbedadditionalsmallNPs, currentroster differs withoutannexationclaim.
 if city in ['Копейск','Артем']:pass # Crossyear individualequivalence notasserted; printedownrosters retained.
 scope=raw[raw.region.eq(raw.iloc[int(current.source_row)-1].region)&raw.mun_upper.eq(raw.iloc[int(current.source_row)-1].mun_upper)];nps=scope[scope.object_level.eq('Населенный пункт')];par=scope[scope.object_level.eq('Муниципалитет верхнего уровня')];assert len(par)==1 and int(par.iloc[0].population)==int(nps.population.sum());curmembers=o[o.census_year.eq(2021)&o.source_row.isin(nps.index+1)&o.source_file.eq(current.source_file)];assert len(curmembers)==len(nps) and int(curmembers.population.sum())==int(par.iloc[0].population);ownmembers[2021]=curmembers
 pointprov=dict(p)
 if not pointprov.get('point_origin_file'):pointprov.update(point_origin_file=p['point_ledger_path'],point_origin_sha256=h(Path(p['point_ledger_path'])),point_origin_locator='target_source_record_id='+current.source_record_id,point_origin_kind='frozen_admitted_representative_point_assertion_not_original_measurement')
 points.append({'group':group,'parent_source_record_id':current.source_record_id,'latitude':p['latitude'],'longitude':p['longitude'],'scope_point_role':'representative_scope','historical_constituent_own_point_asserted':False,'point_provenance_json':json.dumps(pointprov,ensure_ascii=False),'candidate_only':True})
 for year,g in ownmembers.items():
  assert g.source_record_id.is_unique and g.population.notna().all();aux=6 if city=='Пермь' and year==2010 else 0;total=int(g.population.sum())+aux;ids=list(g.source_record_id);control=parent2002 if year==2002 else pc if year==2010 else int(par.iloc[0].population);assert control==total if year!=2010 else True
  controls.append({'group':group,'year':year,'printed_parent_or_complete_city_control':control,'complete_selected_atomic_sum':total,'difference_not_allocated':control-total,'protected2010_difference_not_distributed':year==2010,'member_count':len(g),'roster_complete':True,'parent_credited_as_NP':False,'source_quality_difference_preserved':True})
  groups.append({'group':group,'census_year':year,'observation_id':'published_scope:'+group+':'+str(year),'population':total,'actual_published_auxiliary_population_sum':aux,'native_selected_population_sum':int(g.population.sum()),'constituent_count':len(g),'source_record_ids_json':json.dumps(ids,ensure_ascii=False),'population_derivation':'sum_all_complete_published_city_scope_atomic_NP_leaves','roster_complete':True,'population_series_scope':'complete published city-associated territory byyear; changed composition allowed; not constant modernboundary','boundary_comparability':'UNKNOWN','ordinary_same_place':False,'point_role':'representative_scope','representative_parent_source_record_id':current.source_record_id,'latitude':p['latitude'],'longitude':p['longitude'],'point_provenance_json':json.dumps(pointprov,ensure_ascii=False),'candidate_only':True,'no_fake_2021_child_population':True,'exact_annexation_roster_claimed':False})
  new=g[~g.source_record_id.isin(prior)];net.append({'group':group,'year':year,'unique_new_source_IDs':len(new),'new_native_population_if_scope_admitted':int(new.population.sum()),'source_record_ids_json':json.dumps(list(new.source_record_id),ensure_ascii=False)})
  for r in g.itertuples():
   path=Path('/workspace/settlements-raw')/r.source_file;loc=str(r.source_sheet)+'!row_1based='+str(r.source_row);members.append({'group':group,'census_year':year,'source_record_id':r.source_record_id,'settlement_name':r.settlement_name,'settlement_type':r.settlement_type,'population':int(r.population),'source_population_quality':r.population_value_quality,'source_file':str(path),'source_file_sha256':h(path),'source_row_locator':loc,'source_population_unmodified':True,'exclusive_source_ID_credit':True,'ordinary_same_place':False,'already_in_existing_source_ID_union':r.source_record_id in prior,'own_native_point_available':r.source_record_id in s.point_rows,'candidate_only':True,'source_grain_role':'atomic_NP_in_complete_published_scope'})
 proof.append({'group':group,'year':2002,'federal_parent_row':start,'federal_block_end':end,'parent_raw_row':json.dumps(sh.row_values(start-1),ensure_ascii=False),'federal_source_file':'/workspace/settlements-raw/data/raw/2002_official_tom1/1_TOM_01_04.xls','federal_source_sha256':h(Path('/workspace/settlements-raw/data/raw/2002_official_tom1/1_TOM_01_04.xls')),'rural_file':ruralfile or 'none; urbanonly scope','rural_block_start':ra,'rural_block_end':rb,'rural_atomic_count':len(rural),'rural_atomic_population':int(rural.population.sum())})
 proof.append({'group':group,'year':2010,'raw_complete_city_line':line,'raw_before':above,'raw_after':below,'primary_parent_control':parent2010,'primary_rural_control':ruralcontrol2010,'selected_primary_city_value':int(primary2010.population),'raw_secondary_city_count':'NOT_PUBLISHED_OWNCITY_ROW','secondary_city_not_used_as_primary':True,'raw_block_start':cstart,'raw_block_end':cend,'raw_sheet':sheet2010,'raw_original2010_file':'/workspace/settlements-raw/data/raw/2010/'+file2010,'raw_original2010_sha256':h(Path('/workspace/settlements-raw/data/raw/2010/'+file2010)),'raw_city_block_and_nextcity_json':json.dumps([raw2010sheet.row_values(k-1)[:11] for k in (range(cstart,cend+2) if cstart else [])],ensure_ascii=False),'raw_pdf_page_1based':text[:text.find(line)].count('\f')+1,'source_file':'/workspace/settlements-raw/data/raw/2010_official_tom1/tom-1-chislennost-i-razmeshchenie-naseleniya.pdf','source_sha256':h(Path('/workspace/settlements-raw/data/raw/2010_official_tom1/tom-1-chislennost-i-razmeshchenie-naseleniya.pdf')),'own_selected_primary_source_record_id':primary2010.source_record_id})
 for r in scope.itertuples():proof.append({'group':group,'year':2021,'object_level':r.object_level,'object_name':r.object_name,'population':int(r.population),'oktmo':r.oktmo,'raw_row_1based':r.Index+1,'source_file':str(rawpath),'source_sha256':h(rawpath),'aggregate_control_only':r.object_level!='Населенный пункт'})
for name,d in [('candidate_group_observations',groups),('candidate_constituent_credit_union',members),('candidate_representative_scope_points',points),('printed_controls_atomic_conservation',controls),('complete_scope_source_witnesses',proof),('net_source_ID_union_potential',net),('held_group_scope',holds)]:pd.DataFrame(d).to_csv(O/(name+'.csv'),index=False)
receipt={'status':'candidate_only_complete_published_city_hierarchy_scopes','groups':len(points),'observations':len(groups),'atomic_members':len(members),'net_gain_by_year':{int(y):{'rows':int(g.unique_new_source_IDs.sum()),'population':int(g.new_native_population_if_scope_admitted.sum())} for y,g in pd.DataFrame(net).groupby('year')},'boundary_comparability':'UNKNOWN','exact_annexation_roster_claimed':False,'no_missingyear_childcounts_or_coordinates_created':True,'published_rosters_closed_all_years':True,'printed_controls_exact2002_and2021':True,'protected2010_control_disagreement_not_allocated':True,'source_values_modified':False,'current_scope_member_count_can_differ_byyear':True,'baseline_loader_stage':37,'baseline37_not_future_report_witness':True,'existing_scope_exclusions':'explicit baseline loader37 finite ordinary all3-ownpoint source-IDunion plus existing complete partitions,qualifiedphysical,named10,all14 cityscopes,Ryazan,Moscow5; no county representative points credited','source_manifest':hashcache,'outputs':{p.name:sha(p) for p in O.glob('*.csv')}};(O/'candidate_receipt.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n');print(json.dumps({k:v for k,v in receipt.items() if k not in ['outputs','source_manifest']},ensure_ascii=False));print(pd.DataFrame(net).drop(columns='source_record_ids_json').to_string(index=False));print('bytes',sum(p.stat().st_size for p in O.iterdir() if p.is_file()))
