import json,zipfile,hashlib
from pathlib import Path
import duckdb
from research_rebuild.mass_linkage.apply_reviewed_large_inclusion_scope_20261004 import sha, SELECTED, SELECTED_SHA
C=Path('/workspace/settlements-work/continuation_20261004');F=C/'independent_review/national_absorbed8_scope_review_v1';O=C/'root/accepted_somovo2010_selected_scope';assert not O.exists()
refs=json.loads((F/'accepted_scoped_inclusion_references.json').read_text());r=next(r for r in refs if r['year']==2010);original=json.loads(json.dumps(r));db=duckdb.connect(config={'threads':1,'memory_limit':'256MB'})
assert sha(SELECTED)==SELECTED_SHA
proper='2010:pub-11-1-4.pdf:pdf_page_4:16';sid=r['source_record_id'];refpath='/workspace/settlements-work/continuation_20261003/population2010/tom1_table5_extraction/official_2010_table5_reference.parquet'
ss=db.execute('select source_record_id,census_year,settlement_name,settlement_type,population,population_scope,is_additive_settlement_record,population_value_quality,region_norm from read_parquet(?) where source_record_id in(select unnest(?))',[str(SELECTED),[sid,proper]]).fetch_arrow_table().to_pylist();assert len(ss)==2;rows={x['source_record_id']:x for x in ss};s=rows[sid];p=rows[proper]
assert (s['census_year'],s['settlement_name'],s['settlement_type'],s['population'],s['population_scope'],s['is_additive_settlement_record'])==(2010,'Сомово','пгт',13605,'settlement',True)
assert (p['census_year'],p['settlement_name'],p['settlement_type'],p['population'],p['population_scope'],p['is_additive_settlement_record'])==(2010,'Воронеж','город',889680,'settlement',True) and s['region_norm']==p['region_norm']=='воронежская'
primary=db.execute('select reference_id,label_raw,row_kind,population,region_raw from read_parquet(?) where reference_id in(select unnest(?))',[refpath,['ROSSTAT2010:T5:p20:l12',sid,'ROSSTAT2010:T5:p20:l13']]).fetch_arrow_table().to_pylist();pr={x['reference_id']:x for x in primary}
assert pr['ROSSTAT2010:T5:p20:l12']['label_raw']=='г. Воронеж' and pr['ROSSTAT2010:T5:p20:l12']['population']==889680 and pr['ROSSTAT2010:T5:p20:l12']['row_kind']=='settlement'
assert pr[sid]['population']==13605 and pr[sid]['row_kind']=='settlement' and pr['ROSSTAT2010:T5:p20:l13']['row_kind']=='aggregate'
previous=json.loads((C/'root/accepted_national_absorbed8_scope/application_receipt.json').read_text());point=next(x for x in json.loads((C/'root/accepted_national_absorbed8_scope/accepted_scoped_point_uses.json').read_text()) if x['historical_place_qid']=='Q4428718');point=dict(point,target_source_record_id=sid,target_year=2010)
r['old_same_year_city_proper_source_record_id']=proper;r['point_row']=point;r['national_2010_credit']=True;r['national_credit_basis']='Existing selected additive source membership, not ROSSTAT source-ID prefix; count once only when old/current city proper are represented'
r['review_limits']=[x for x in r['review_limits'] if 'auxiliary selected' not in x];r['population_value_quality']=s['population_value_quality'];r['root_source_alias_correction']={'original_parent_locator':original['old_same_year_city_proper_source_record_id'],'original_parent_actual_role':'intracity district aggregate','correct_official_city_proper_locator':'ROSSTAT2010:T5:p20:l12','selected_same_census_city_proper_source_id':proper,'primary_context_rows':primary,'no_population_value_or_selected_source_layer_changed':True}
O.mkdir();paths={}
for name,data in [('accepted_scoped_inclusion_references.json',[r]),('accepted_scoped_point_uses.json',[point])]:p=O/name;p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n');paths[name]=sha(p)
receipt={'status':'applied_reviewed_secondary_reported_large_inclusion_references','observation_references':1,'new_scoped_point_uses':1,'old2010_existing_population_reference_sum':13605,'ordinary_NP3_admission':False,'source_population_values_modified':False,'legal_acts_independently_verified':False,'modern_boundary_harmonized':False,'outputs':paths,'inputs':{str(SELECTED):SELECTED_SHA,str(F/'review_receipt.json'):sha(F/'review_receipt.json'),str(C/'root/accepted_national_absorbed8_scope/application_receipt.json'):sha(C/'root/accepted_national_absorbed8_scope/application_receipt.json'),refpath:sha(refpath)},'script_sha256':sha(__file__),'correction':'Frozen earlier review/source-ID-prefix inference retained as history; exact selected membership and actual primary row hierarchy control this successor'}
(O/'application_receipt.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n');print(receipt['status'],13605)
