from pathlib import Path
import sys,json,math,collections,importlib.util
import pandas as pd
R=Path('/workspace/russian-settlements-research');sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from working_state_20261007 import load
from current_chain_state_20261007 import sha,distance_km
O=Path(__file__).parent;s=load(41);before=s.metrics();sp=importlib.util.spec_from_file_location('root_finite',R/'research_rebuild/evidence/large_native_suffix_and_former_name_application_20261008/apply.py');fm=importlib.util.module_from_spec(sp);sp.loader.exec_module(fm);fb=fm.finite_metrics(s);assert fb=={'histories':138779,'populations_by_year':{'2002':126699637,'2010':123858446,'2021':124461058}}
f=pd.read_csv(O/'source_positive_native2010_candidates.csv.gz',keep_default_na=False);raw=pd.read_csv(O/'actual_native2010_raw_source_checks.csv.gz',keep_default_na=False).set_index('target2010_source_record_id');v=json.loads((O/'literal_source_validation_receipt.json').read_text());pins={str(p):sha(p) for p in s.inputs}
for p,h in v['raw_source_pins'].items():assert sha(Path(p))==h,p
for p in [O/'source_positive_native2010_candidates.csv.gz',O/'all_region_all_year_competitors.csv.gz',O/'actual_native2010_raw_source_checks.csv.gz']:pins[str(p)]=sha(p)
occupied=collections.defaultdict(set)
for sid,p in s.point_rows.items():occupied[(int(s.by_id.loc[sid].census_year),p['latitude'],p['longitude'])].add(sid)
edges=[];points=[];witness=[];held=[]
for z in f.to_dict('records'):
 sid,cid,oid=[z[k] for k in ['target2010_source_record_id','current2021_source_record_id','old2002_source_record_id']];a=s.by_id.loc[sid];cp,op=[s.point_rows[x] for x in [cid,oid]];targetpoint=s.point_rows.get(sid);rc=s.uf.find(cid);why=[]
 if s.uf.find(oid)!=rc or s.years[rc]!={2002,2021}:why.append('actual41_endpoint_pair_no_longer_missing2010')
 if s.years[s.uf.find(sid)]&{2002,2021}:why.append('actual41_repeated_census_year_or_target_already_full3')
 if any(x in s.conflicting_point_targets for x in [sid,cid,oid]):why.append('active_point_conflict')
 if not all(math.isfinite(float(p[k])) for p in [op,cp] for k in ['latitude','longitude']):why.append('nonfinite_ownpoint')
 if distance_km((op['latitude'],op['longitude']),(cp['latitude'],cp['longitude']))>5 or targetpoint and distance_km((targetpoint['latitude'],targetpoint['longitude']),(cp['latitude'],cp['longitude']))>5:why.append('independent_ownpoint_contradiction_over5km')
 if sid not in s.point_rows and occupied[(2010,cp['latitude'],cp['longitude'])]-{sid}:why.append('different2010_native_ownNP_already_uses_same_donor_point')
 rr=raw.loc[sid];assert rr.literal_source_passed and rr.protected_native_population==a.population and rr.protected_native_quality==a.population_value_quality
 if why:held.append({**z,'reason':' | '.join(why)});continue
 proof={'source_original_row_binding':rr.to_dict(),'all_selected_native02_10_21_regional_competitors_before_any_graph_gate':json.loads(z['all_competing_selected_sources_json']),'strict_region_name_unique_all3_sourceyears':z['strict_all_three_year_region_name_unique'],'compatible_printed_type_region_unique_all3_sourceyears':z['typed_all_three_year_region_name_unique'],'native2010_physical_np_role':z['native2010_printed_role'],'population_ratio_risk_flag_only':z['growth_flag'],'genuine_native_zero_preserved':z['genuine_zero_present'],'old02_point_origin':op,'current21_point_origin':cp,'old02_current21_point_distance_km':distance_km((op['latitude'],op['longitude']),(cp['latitude'],cp['longitude'])),'historical_coordinate_measurement_asserted':False,'population_or_boundary_equality_asserted':False};body=json.dumps(proof,ensure_ascii=False,default=str)
 edges.append({'from_source_record_id':sid,'to_source_record_id':cid,'relation':'same_place','decision_status':'checked_rule_accepted','admission_rule':'whole-region ownNP name and compatible printed type uniqueness across all selected2002/2010/2021 source leaves before graph filters; original own2010 label/count; independent admitted02/21 ownpoints <=5km','source_binding_proof':body,'population_boundary_comparability_asserted':False,'boundary_comparability':'UNKNOWN','source_population_and_quality':'unchanged_selected_native_sources'});s.union(sid,cid)
 if sid not in s.point_rows:
  p={k:cp.get(k,'') for k in ['latitude','longitude','coordinate_source_record_id','source_sha256','source_locator','point_origin_file','point_origin_sha256','point_origin_locator','point_origin_kind']};p.update(target_source_record_id=sid,coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_binding_rule='whole-region source-bound ownNP identity; retrospective reuse of admitted receiving current ownpoint',point_use_inference='retrospective_continuity_not_historical_coordinate_measurement',point_claim_quality='auto_rule',population_boundary_comparability_asserted=False);points.append(p);s.point_rows[sid]=dict(p,point_ledger_path=str(O/'accepted_point_use_delta.csv.gz'));occupied[(2010,cp['latitude'],cp['longitude'])].add(sid)
 witness.append({**z,'raw_source_binding':json.dumps(rr.to_dict(),ensure_ascii=False,default=str),'actual41_current_point_origin_file':cp.get('point_origin_file',''),'actual41_current_point_origin_sha256':cp.get('point_origin_sha256',''),'actual41_current_point_origin_locator':cp.get('point_origin_locator','')})
after=s.metrics();fa=fm.finite_metrics(s);edge=O/'accepted_identity_edge_delta.csv.gz';point=O/'accepted_point_use_delta.csv.gz';pd.DataFrame(edges).to_csv(edge,index=False,compression={'method':'gzip','mtime':0});pd.DataFrame(points).to_csv(point,index=False,compression={'method':'gzip','mtime':0});pd.DataFrame(witness).to_csv(O/'accepted_source_binding_witness.csv.gz',index=False,compression={'method':'gzip','mtime':0});pd.DataFrame(held).to_csv(O/'actual41_application_holds.csv.gz',index=False,compression={'method':'gzip','mtime':0});s.add_deltas([edge],[point]);assert s.metrics()==after
r={'baseline_stage':41,'source_preparation_stage':39,'accepted_edges':len(edges),'accepted_point_uses':len(points),'held_after_actual41_checks':len(held),'baseline':before,'after':after,'before_finite_all3_all_points':fb,'after_finite_all3_all_points':fa,'net_finite_all3_all_points':{'histories':fa['histories']-fb['histories'],'populations_by_year':{y:fa['populations_by_year'][y]-fb['populations_by_year'][y] for y in fb['populations_by_year']}},'all_sourceyear_competitors_before_graph_filter':True,'native_populations_quality_source_labels_unchanged':True,'historical_coordinate_measurement_asserted':False,'boundary_comparability':'UNKNOWN','actual41_CSV_gz_transport_replay':'passed','raw_source_pins':v['raw_source_pins'],'input_pins':pins,'accepted_ledger_pins':{p.name:sha(p) for p in [edge,point]},'actual44_overlap_requires_root_composition_not_blind_gain_sum':True};(O/'application_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2));print(json.dumps({k:r[k] for k in ['baseline_stage','accepted_edges','accepted_point_uses','held_after_actual41_checks','net_finite_all3_all_points']}))
