from pathlib import Path
import pandas as pd,duckdb,xlrd,re,json,sys
from bs4 import BeautifulSoup
R=Path('/workspace/russian-settlements-research');sys.path.insert(0,str(R/'research_rebuild/mass_linkage'));from current_chain_state_20261007 import normalize,sha
O=Path(__file__).parent;f=pd.read_csv(O/'source_positive_native2010_candidates.csv.gz',keep_default_na=False);SEL=Path('/workspace/settlements-delivery/continuation-consolidated-20261003/selected_observations.parquet');c=duckdb.connect();meta=c.execute('select source_record_id,source_row,source_sheet,source_name_raw,population,population_value_quality from read_parquet(?)where census_year=2010',[str(SEL)]).fetchdf().set_index('source_record_id');books={};pins={str(SEL):sha(SEL)};out=[]
html=Path('/workspace/settlements-work/sources/r2-missing/arkhangelsk_2010_archived_original.html');trs=BeautifulSoup(html.read_bytes(),'html.parser').table.find_all('tr');pins[str(html)]=sha(html)
doc=Path('/workspace/settlements-work/sources/r2-missing/murmansk_population.doc');text=Path('/workspace/settlements-work/continuation_20261004/independent_review/murmansk_population.txt');pins[str(doc)]=sha(doc);pins[str(text)]=sha(text);ledger=Path('/workspace/settlements-work/continuation_20261003/primary_population_next_cohort_probe_v1/regional_assets/murmansk/murmansk_2010_population_by_sex_full_table_ledger.csv');pins[str(ledger)]=sha(ledger);mf=pd.read_csv(ledger,keep_default_na=False).set_index('source_record_id')
for z in f.to_dict('records'):
 sid=z['target2010_source_record_id'];m=meta.loc[sid];label=m.source_name_raw;population=m.population;quality=m.population_value_quality;vals=[];kind='';loc='';path=None;passed=False;dash=False
 if sid.startswith('ARK2010:'):
  num=int(re.search(r'tr(\d+)$',sid).group(1));cells=[' '.join(td.get_text(' ',strip=True).split()) for td in trs[num].find_all(['td','th'])];path=html;loc=f'table1;tr_zero_based={num};row1based={num+1}';kind='printed_whole_population_railway_or_rural_own_NP_leaf';vals=cells;passed=normalize(cells[0])==normalize(label) and any(re.fullmatch('[0-9 ]+',v) and int(v.replace(' ',''))==population for v in cells[1:])
 elif sid.startswith('MURMANSK2010:'):
  mm=mf.loc[sid];lines=[line for line in text.read_text().splitlines() if normalize(line.split('\t')[0])==normalize(label)];path=doc;loc=f'table1;row1based={int(m.source_row)}';kind='published_whole_population_own_np_row';vals=lines;dash=str(mm.raw_population).strip()=='-';passed=len(lines)==1 and normalize(mm.label_raw)==normalize(label) and ((not dash and int(mm.raw_population)==population) or (dash and population==0 and quality=='reviewed_context_specific_dash_interpretation'))
 elif str(z['native2010_source_file']).endswith('.xls'):
  path=Path('/workspace/settlements-raw')/z['native2010_source_file']
  if path not in books:books[path]=xlrd.open_workbook(str(path),on_demand=True);pins[str(path)]=sha(path)
  sh=books[path].sheet_by_name(m.source_sheet);rn=int(m.source_row);vals=sh.row_values(rn-1);loc=f'sheet={sh.name};row1based={rn}';kind='printed_own_NP_whole_count_XLS_row';passed=sum(isinstance(v,str) and normalize(v)==normalize(label) for v in vals)==1 and any((isinstance(v,(int,float)) and v==population) or (isinstance(v,str) and re.fullmatch('[0-9]+',v.strip()) and int(v.strip())==population) for v in vals)
 # Literal prefixes distinguish own NP roles from aggregate rows.
 ownlabel=not bool(re.search(r'все население|всего|городское население|сельское население|сельсовет|сельский совет|сельское поселение',normalize(label)))
 out.append({'target2010_source_record_id':sid,'raw_source_file':str(path),'raw_source_sha256':pins.get(str(path),''),'raw_locator':loc,'raw_own_label':label,'protected_native_population':population,'protected_native_quality':quality,'raw_row_witness':json.dumps(vals,ensure_ascii=False),'own_np_label_not_aggregate_caption':ownlabel,'literal_source_passed':bool(passed and ownlabel),'protected_reviewed_dash_to_zero_unchanged':dash,'source_own_np_role':kind})
pd.DataFrame(out).to_csv(O/'actual_native2010_raw_source_checks.csv.gz',index=False,compression={'method':'gzip','mtime':0});r={'candidate_cases':len(f),'literal_source_passes':sum(z['literal_source_passed'] for z in out),'raw_source_pins':pins,'no_source_population_or_quality_edit':True,'raw_dash_is_not_newly_imputed_zero':True};(O/'literal_source_validation_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2));print(json.dumps({k:v for k,v in r.items() if k!='raw_source_pins'}))
