from pathlib import Path
import pandas as pd,json,xlrd,re,hashlib
O=Path(__file__).parent;sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();members=pd.read_csv(O/'candidate_constituent_credit_union.csv',keep_default_na=False);proof=[]
configs=[('Тюмень','058_a73d73c7dd_02c-Tyumen_obl_new.xls',3,38,'003_eb441570b1_11._20Урал_ФО_2010.xls','Урал',2490,2494,2512,4,7),('Самара','053_f7f2b62d26_Samarskaja_new.xls',3,8,'016_802d308e41_8._20Or_Penz_Perm_Samar_Saratov_Uly_2010.xls','!!!',1310,1319,1320,5,6),('Новоалтайск','066_76aa869929_Altai_krai1.xls',44,45,'008_342f3c208b_16._20Сиб_ФО_2010.xls','Sib',1619,1620,1619,4,5)]
for city,file02,a,b,file10,sheet,start,leaf_start,end,labelcol,popcol in configs:
 group='published_closed_city_scope_'+city;p=Path('/workspace/settlements-raw/data/raw/2002')/file02;s=xlrd.open_workbook(str(p)).sheet_by_index(0);native=members[members.group.eq(group)&members.census_year.eq(2002)&members.source_file.eq(str(p))];native_rows={int(float(z.split('row_1based=')[-1])) for z in native.source_row_locator};raw_atoms=set()
 for n in range(a,b+1):
  rr=s.row_values(n-1);idx=next((i for i,z in enumerate(rr) if isinstance(z,str) and re.match(r'^\s*(?:пос[её]лок|деревня|село|починок|железнодорожная (?:станция|казарма|будка)|станция)\s+',z,re.I)),None)
  if idx is not None:raw_atoms.add(n)
 assert raw_atoms==native_rows,(city,raw_atoms-native_rows,native_rows-raw_atoms)
 proof.append({'group':group,'year':2002,'raw_file':str(p),'raw_sha256':sha(p),'raw_sheet':s.name,'raw_start':a,'raw_end':b,'all_original_named_atomic_rows_equal_native_selected_rows':True,'raw_atomic_count':len(raw_atoms),'raw_atomic_population_sum':int(native.population.sum()),'next_city_boundary_explicit':True,'raw_complete_block_and_next_header_json':json.dumps([{'row_1based':n,'row':s.row_values(n-1)[:8]} for n in range(a,b+2)],ensure_ascii=False)})
 p=Path('/workspace/settlements-raw/data/raw/2010')/file10;s=xlrd.open_workbook(str(p)).sheet_by_name(sheet);native=members[members.group.eq(group)&members.census_year.eq(2010)&members.source_file.eq(str(p))];native_rows={int(float(z.split('row_1based=')[-1])) for z in native.source_row_locator};raw_atoms=set(range(leaf_start,end+1));assert native_rows==raw_atoms,(city,native_rows,raw_atoms)
 proof.append({'group':group,'year':2010,'raw_file':str(p),'raw_sha256':sha(p),'raw_sheet':s.name,'raw_start':start,'raw_end':end,'all_original_named_atomic_rows_equal_native_selected_rows':True,'raw_atomic_count':len(raw_atoms),'raw_atomic_population_sum':int(native.population.sum()),'next_city_boundary_explicit':True,'raw_complete_block_and_next_header_json':json.dumps([{'row_1based':n,'row':s.row_values(n-1)[:11]} for n in range(start,end+2)],ensure_ascii=False),'literal_source_parent_col3':city if city!='Новоалтайск' else 'none; literal owncity source row followed immediately by next city','intracity_districts_nonadditive_to_NP_roster':True})
# Urban-only Volzhsky source roster and retained official same-year pgt override.
p=Path('/workspace/settlements-raw/data/raw/2010/004_486e984bdc_12._20Астр_Волгог_Ростов.xls');s=xlrd.open_workbook(str(p)).sheet_by_name('Южный');rr=s.row_values(1945);assert rr[6]=='Краснооктябрьский рп' and int(rr[7])==12741
text=Path('/workspace/settlements-work/large_absorbed_city_closed_scope_mass_20261008/tom1.txt').read_text();lines=text.splitlines();idx=next(i for i,z in enumerate(lines) if re.match(r'^\s*г\. Волжский с подчиненными',z));block='\n'.join(lines[idx:idx+5]);assert '327089' in block and '314255' in block and '12834' in block
v=members[members.group.eq('published_closed_city_scope_Волжский')&members.census_year.eq(2010)&members.settlement_type.eq('пгт')].iloc[0];assert int(v.population)==12834 and v.source_population_quality=='reviewed_primary_reported_value';pdf=Path(v.source_file);assert sha(pdf)==v.source_file_sha256
pd.DataFrame([{'group':v.group,'year':2010,'native_source_record_id':v.source_record_id,'native_type':v.settlement_type,'native_own_name':v.settlement_name,'native_population':v.population,'native_quality':v.source_population_quality,'primary_source_file':str(pdf),'primary_sha256':sha(pdf),'primary_literal_complete_city_block':block,'primary_pdf_page_1based':text[:text.find(lines[idx])].count('\f')+1,'protected_secondary_alternative_population':12741,'protected_secondary_source_file':str(p),'protected_secondary_sha256':sha(p),'protected_secondary_sheet':'Южный','protected_secondary_raw_row_1based':1946,'protected_secondary_original_raw_row_json':json.dumps(rr[:11],ensure_ascii=False),'protected_secondary_alternative_not_substituted_or_distributed':True,'same_year_literal_primary_urban_source_used':True}]).to_csv(O/'original2010_primary_urban_override_witness.csv',index=False)
pd.DataFrame(proof).to_csv(O/'original2002_2010_complete_city_rural_block_closures.csv',index=False)
w=pd.read_csv(O/'complete_scope_source_witnesses.csv',keep_default_na=False)
for i,z in w.iterrows():
 if z.year==2010 and z.group in ['published_closed_city_scope_Тюмень','published_closed_city_scope_Самара']:w.loc[i,'raw_secondary_city_count']='NOT_PUBLISHED_OWNCITY_ROW; intracity district anchor only, not credited as NP';w.loc[i,'full_raw_city_block_witness']='original2002_2010_complete_city_rural_block_closures.csv'
w.to_csv(O/'complete_scope_source_witnesses.csv',index=False)
r=json.loads((O/'candidate_receipt.json').read_text());r['baseline_loader_stage']=34;r['source_year_territory_changes_explicit_not_modern_boundary_harmonization']=True;r['municipal_county_district_scope_credit_proposed']=False;r['original_complete2002_and2010_rural_rosters_and_nextcity_boundaries_reopened']=True;r['2010_primary_urban_override_raw_proved']=True;r['protected2010_parent_differences_not_distributed']={'Тюмень':9,'Самара':2,'Волжский':0,'Новоалтайск':0};r['frozen_review_packet']=True;r['outputs']={p.name:sha(p) for p in O.glob('*.csv')};r['code_sha256']={p.name:sha(p) for p in O.glob('*.py')};(O/'candidate_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n')
(O/'README.md').write_text('Four complete literal published city-associated territorial candidates: Тюмень/Волжский/Новоалтайск/Самара.12observations74nativeatomic references;63original XLS bindings plus full02/10rural blocks and nextcity boundaries reopened. Net nativeUID potential after actual loader34+existingqualified/named/city/municipal credits96593/35734/0. Tyumen564180/604807/847488, Volzhsky324224/327089/321479, Novoaltaysk73544/70437/73049, Samara1176428/1164812/1173393.02/21all parent controls exact.2010complete protected native rosters retained; primary city-associated controls differ9Tyumen/2Samara, not allocated. Volzhsky selected actualprimary urban Krasnooktyabrsky12834 is explicitly under own city source327089; rawprotected12741 alternative preserved separately. Sourceyear composition changes are explicit; current owncity point is only representative_scope for complete published territory. No claim formerNP=city same_place, legalannexation, constant modern boundary, or historical individual child point. Entirecounty district aggregates are not proposed. Samara sourceroster is a city jurisdiction trace, never an assertion that Priбрежный was legally annexed. Candidate only; no shared accepted/report/helper/Git mutation.\n')
print('frozen4',r['net_gain_by_year'],'bytes',sum(p.stat().st_size for p in O.iterdir() if p.is_file()))
