import sys,json,re,gzip,collections,importlib.util
from pathlib import Path
import pandas as pd,duckdb
O=Path(__file__).parent;R=Path('/workspace/russian-settlements-research');E=O.parent;sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from current_chain_state_20261007 import normalize,distance_km
from apply_unique_county_name_bridge_20261007 import county_key
import current_chain_state_20261007 as module
original_sha=module.sha;hc={}
def sha(p):
 p=Path(p);st=p.stat();key=(str(p),st.st_size,st.st_mtime_ns)
 if key not in hc:hc[key]=original_sha(p)
 return hc[key]
module.sha=sha
from frozen_working_state58 import load
s=load(58);src=E/'native_singleton_rural_mass_20261008/frozen_finite.py';sp=importlib.util.spec_from_file_location('ff',src);ff=importlib.util.module_from_spec(sp);sp.loader.exec_module(ff);before=ff.finite(s);protected=s.obs[['source_record_id','population','population_value_quality']].copy();graph={i:s.uf.find(i) for i in s.by_id.index};inputfile=O/'Geo_vs_independent_owncoded_TSV_points.csv.gz';f=pd.read_csv(inputfile,keep_default_na=False);allcomparisons=f.copy();inventory=pd.read_csv(O/'corrected_carrier_component_inventory.csv.gz',keep_default_na=False);geo=inventory[inventory.point_json.map(lambda x:'GeoKLADR' in json.loads(x).get('point_origin_kind',''))];corroborated=set(allcomparisons.loc[allcomparisons.owncoded_coordinate_distance_km.le(5),'current_source_record_id']);conflict=f[f.owncoded_coordinate_distance_km.gt(5)].copy();missing=geo[~geo.current_source_record_id.isin(set(allcomparisons.current_source_record_id))].copy();extra=[]
for a in missing.to_dict('records'):
 pp=json.loads(a['point_json']);extra.append({'current_source_record_id':a['current_source_record_id'],'name':a['name'],'years_json':a['years_json'],'native2021_own_code':a['native2021_own_code'],'Geo_own_code':pp['coordinate_source_record_id'],'Geo_latitude':pp['latitude'],'Geo_longitude':pp['longitude'],'own_coded_TSV_QID':'','TSV_own_oktmo_literal':'','TSV_own_okato_literal':'','TSV_label':'','TSV_admin_label':'','TSV_latitude':None,'TSV_longitude':None,'owncoded_coordinate_distance_km':None,'TSV_line1based':'','TSV_raw_line':''})
f=pd.concat([conflict,pd.DataFrame(extra)],ignore_index=True);wanted=set(f.own_coded_TSV_QID)-{''};pins={str(p):sha(p) for p in [O/'corrected_carrier_component_inventory.csv.gz',inputfile,O/'overlay.py',O/'frozen_working_state58.py',src,*s.inputs]};TSV=Path('/workspace/settlements-raw/data/raw/wikimedia/wikidata_oktmo_entities.tsv');pins[str(TSV)]=sha(TSV)
entities={};files={};alllabels={};paths=set()
for root,pattern in [('/workspace/settlements-raw/data/raw/wikidata_entities_full','*.json.gz'),('/workspace/settlements-work/wikidata_secondary_full3_expansion_20261007','*.json.gz'),('/workspace/settlements-work/additional_uncached_census_histories_20261008','*.json.gz'),('/workspace/settlements-work/continuation_20261004/R4/residual_alias_fetch/raw_entity_batches','*.json')]:paths.update(Path(root).glob(pattern))
for p in sorted(paths):
 try:
  data=json.loads(gzip.decompress(p.read_bytes()) if p.name.endswith('.gz') else p.read_bytes());es=data.get('entities',data.get('payload',{}).get('entities',{}))
 except (ValueError,OSError,AttributeError):continue
 if not isinstance(es,dict):continue
 for q,e in es.items():
  if not isinstance(e,dict):continue
  label=e.get('labels',{}).get('ru',{}).get('value','')
  if label:alllabels[q]=label
  if q in wanted and (q not in entities or len(e.get('claims',{}))>len(entities[q].get('claims',{}))):entities[q]=e;files[q]=p
RAW=Path('/workspace/settlements-raw/data/interim/2021_tochno/data_allsettlements_anon_156_v20251217.parquet');c=duckdb.connect(config={'threads':1});raw=c.execute('select row_number() over() rn,object_level,object_name,oktmo,mun_upper,mun_lower,population from read_parquet(?)',[str(RAW)]).fetchdf().set_index('rn');c.close();pins[str(RAW)]=sha(RAW)
def parish(v):
 v=normalize(v);v=re.sub(r'\b(?:сельское поселение|сельское|поселение|сельсовет|сельский совет|сельская администрация|муниципальное образование)\b',' ',v);v=' '.join(re.sub('[^а-яa-z0-9]+',' ',v).split())
 if v.endswith('ское'):v=v[:-2]+'ий'
 return v
def val(sn):return sn.get('datavalue',{}).get('value')
def cleanname(v):return normalize(re.sub(r'^(?:село|деревня|пос[её]лок|хутор|станица|аул|город|станция)\s+','',re.sub(r'\s*\([^)]*\)\s*$','',str(v)),flags=re.I))
physical={'Q5084','Q532','Q192287','Q515','Q3957','Q486972','Q2023000','Q2514025','Q15078955','Q24258416','Q27062006','Q27517483'};members=collections.defaultdict(list)
for sid in s.by_id.index:members[s.uf.find(sid)].append(sid)
rejections=[];points=[];witness=[];risks=[];ownpoints={};original=dict(s.point_rows)
for sid,g in f.groupby('current_source_record_id',sort=False):
 z=g.iloc[0].to_dict();q=z['own_coded_TSV_QID'];e=entities.get(q,{});cs=e.get('claims',{});own=raw.loc[int(sid.rsplit(':',1)[1])];row=s.by_id.loc[sid];old=original[sid];types={val(x.get('mainsnak',{})).get('id') for x in cs.get('P31',[]) if isinstance(val(x.get('mainsnak',{})),dict) and x.get('rank')!='deprecated'};codes764={str(val(x.get('mainsnak',{}))) for x in cs.get('P764',[]) if x.get('rank')!='deprecated'};codes721={str(val(x.get('mainsnak',{}))) for x in cs.get('P721',[]) if x.get('rank')!='deprecated'};freshcode=any(v.isdigit() and int(v)==int(str(own.oktmo)) for v in codes764) or str(z['Geo_own_code']) in codes721
 names={e.get('labels',{}).get('ru',{}).get('value','')}|{x['value'] for x in e.get('aliases',{}).get('ru',[])};label=str(z['TSV_label']);tsvlabel=re.sub(r'"@ru$', '',label).strip('"');namematch=cleanname(row.settlement_name) in {cleanname(v) for v in names} or cleanname(tsvlabel)==cleanname(row.settlement_name);adminlabel=str(z['TSV_admin_label']);adminlabel=re.sub(r'"@ru$', '',adminlabel).strip('"');adminmatch=bool(parish(adminlabel)) and parish(adminlabel)==parish(own.mun_lower);county_admin_match=bool(county_key(adminlabel)) and county_key(adminlabel)==county_key(own.mun_upper);own_context_match=adminmatch or county_admin_match
 tsvxy=(float(z['TSV_latitude']),float(z['TSV_longitude'])) if q else None;ps=[val(x.get('mainsnak',{})) for x in cs.get('P625',[]) if x.get('rank')!='deprecated'];codedcoords=[(v['latitude'],v['longitude']) for v in ps if isinstance(v,dict) and 'latitude' in v];unique=set(codedcoords);freshpoint=len(unique)==1;freshxy=next(iter(unique)) if freshpoint else None;tsvcoord_corroborated=freshpoint and bool(tsvxy) and distance_km(freshxy,tsvxy)<=1;selectedxy=freshxy if freshpoint else tsvxy
 # Independent literal P764/P721 code + correct fullraw own NP/parish, physical cached class, actual coded TSV point; source TSV alone does not override grain/context/code contradictions.
 own_typed_classifier=bool(re.match(r'^(?:село|деревня|пос[её]лок|хутор|станица|аул|город|станция)\s+',str(own.object_name),re.I))
 physical_role=bool(types&physical) or (not types and own_typed_classifier and own_context_match)
 safe=(bool(q) and len(g)==1 and physical_role and namematch and (freshcode or own_context_match) and (not unique or len(unique)==1) and (not freshpoint or tsvcoord_corroborated))
 if q in files:pins[str(files[q])]=sha(files[q])
 component=members[s.uf.find(sid)];affected=[]
 for target in component:
  if target not in original:continue
  pp=original[target]
  if pp['point_origin_file']!=old['point_origin_file'] or str(pp.get('coordinate_source_record_id',''))!=str(old.get('coordinate_source_record_id','')) or (pp['latitude'],pp['longitude'])!=(old['latitude'],old['longitude']):continue
  affected.append(target);ledger=pp['point_ledger_path'];pins[ledger]=sha(Path(ledger));rejections.append({'target_source_record_id':target,'rejection_status':'reviewed_rejected_coordinate_claim_only','old_latitude':pp['latitude'],'old_longitude':pp['longitude'],'origin_ledger':ledger,'origin_ledger_sha256':pins[ledger],'actual_point_origin_file':pp['point_origin_file'],'actual_point_origin_sha256':pp.get('point_origin_sha256',''),'actual_point_origin_locator':pp.get('point_origin_locator',''),'case':sid,'reason':('Own Geo code binds locality; independent owncoded physical point contradicts coordinate by over5km' if q else 'Own Geo code binds locality but coordinate lacks independent physical corroboration under failed Geo recovery rule')+'; identity preserved; exact historical clones affected'})
  if safe:
   origin=files[q] if freshpoint else TSV;locator='entities.'+q+'.claims.P625/P721/P764/P31' if freshpoint else 'line1based='+str(z['TSV_line1based'])+';own P764/P721/coord/adminLabel';points.append({'target_source_record_id':target,'latitude':selectedxy[0],'longitude':selectedxy[1],'coordinate_admission_status':'reviewed_extension_rule_accepted','coordinate_source_record_id':q,'point_origin_file':str(origin),'point_origin_sha256':pins[str(origin)],'point_origin_locator':locator,'point_origin_kind':'independent_owncoded_cached_Wikidata_point' if freshpoint else 'independent_owncoded_TSV_point_with_cached_physical_class_and_current_parish','coordinate_binding_rule':'Literal own P764/P721 coded TSV entity with own current native code (numeric source-format equivalence retained beside original code) and exact typed own Geo classifier code; physical cached own NP class; literal own name; actual fullraw own subordinate parish/admin context or nondeprecated direct coded entity claim; source literal point verified; competing entities/coordinates held; own Geo coordinate rejected separately from own ID binding','historical_census_coordinate_asserted':False,'point_use_inference':'own locality representative point reused by existing source-supported continuity','native2021_own_oktmo_raw':str(own.oktmo),'native2021_own_official_oktmo_TSV':z['TSV_own_oktmo_literal'],'rejected_Geo_coordinate_source_record_id':old['coordinate_source_record_id'],'case':sid})
 if safe:ownpoints[sid]=q
 compdata=s.obs[s.obs.root.eq(s.uf.find(sid))];risks.append({'current_source_record_id':sid,'name':row.settlement_name,'full3':s.years[s.uf.find(sid)]=={2002,2010,2021},'recovered':safe,'component_population2002':float(compdata.loc[compdata.census_year.eq(2002),'population'].sum()),'component_population2010':float(compdata.loc[compdata.census_year.eq(2010),'population'].sum()),'component_population2021':float(compdata.loc[compdata.census_year.eq(2021),'population'].sum())})
 witness.append({**z,'cached_entity_file':str(files.get(q,'')),'cached_entity_sha256':pins.get(str(files.get(q,'')),''),'cached_entity_raw_json':json.dumps(e,ensure_ascii=False),'independent_typed_own_classifier_role':own_typed_classifier,'physical_role_binding_accepted':physical_role,'physical_P31_ids_json':json.dumps(sorted(x for x in types if x)),'nondeprecated_current_P764_claims_json':json.dumps(sorted(codes764)),'nondeprecated_current_P721_claims_json':json.dumps(sorted(codes721)),'own_raw_2021_parish':own.mun_lower,'TSV_parish_matches_raw_current_own':adminmatch,'TSV_county_matches_raw_current_own':county_admin_match,'fresh_entity_own_P764_or_P721_match':freshcode,'fresh_entity_single_P625':freshpoint,'fresh_P625_corroborates_TSV_within1km':tsvcoord_corroborated,'point_recovered':safe,'affected_active_source_IDs_json':json.dumps(affected),'identity_edges_modified':False})
for filename,data,cols in [('point_use_rejections.csv.gz',rejections,['target_source_record_id','rejection_status','old_latitude','old_longitude','origin_ledger','origin_ledger_sha256']),('accepted_point_use_delta.csv.gz',points,['target_source_record_id','latitude','longitude','coordinate_admission_status']),('owncoded_coordinate_consistency_witnesses.csv.gz',witness,None),('coordinate_conflict_population_risk.csv.gz',risks,None)]:
 (pd.DataFrame(data) if data else pd.DataFrame(columns=cols)).to_csv(O/filename,index=False,compression={'method':'gzip','mtime':0,'compresslevel':9})
s.reject_point_uses(O/'point_use_rejections.csv.gz');s.add_deltas(point_paths=[O/'accepted_point_use_delta.csv.gz']);after=ff.finite(s);pd.testing.assert_frame_equal(protected,s.obs[protected.columns]);assert graph=={i:s.uf.find(i) for i in s.by_id.index};outputs=['point_use_rejections.csv.gz','accepted_point_use_delta.csv.gz','owncoded_coordinate_consistency_witnesses.csv.gz','coordinate_conflict_population_risk.csv.gz'];r={'baseline_stage':58,'status':'bulk ownGeo versus independent owncoded cached point overlay; actual58 State API replay passed','Geo_recovered_current_carriers_checked':len(geo),'independent_owncoded_coordinate_comparisons':len(allcomparisons),'within5km_owncoded_corroborated_Geo_carriers_retained':len(corroborated),'over5km_conflict_carriers':conflict.current_source_record_id.nunique(),'uncorroborated_Geo_current_carriers_held':len(missing),'recovered_current_carriers':len(ownpoints),'Geo_rule_without_independent_coordinate_corroboration_rejected':True,'held_current_carriers':len(risks)-len(ownpoints),'rejection_uses':len(rejections),'replacement_point_uses':len(points),'before_finite':before,'after_finite':after,'net_finite_population_by_year':{y:after['populations_by_year'][y]-before['populations_by_year'][y] for y in before['populations_by_year']},'input_pins':pins,'output_pins':{n:sha(O/n) for n in outputs},'raw_census_population_quality_unchanged':True,'identity_edges_unchanged':True,'Geo_ID_binding_not_asserted_wrong_when_Geo_coordinate_rejected':True};(O/'application_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n');print(json.dumps({k:v for k,v in r.items() if k not in ['input_pins','output_pins']},ensure_ascii=False))
