from pathlib import Path
import pandas as pd,gzip,json,re,hashlib
O=Path(__file__).parent;D=pd.read_pickle('/dev/shm/over500-20261009/east_enriched.pkl');by=D.set_index('source_record_id',drop=False);P=pd.read_parquet('/dev/shm/over500-20261009/points_compact.parquet').fillna('').drop_duplicates('target_source_record_id',keep='last').set_index('target_source_record_id');cache={x['page']['title']:x for x in json.load(gzip.open(O/'cached_own_pages.json.gz'))};edge=[];pts=[];wit=[];dis=[]
CASES=[(1503,'Улуелга (Белорецкий район)','улуелга','белорецкий',['станции Улу-Елга','2007']),(153,'Озёрное (Башкортостан)','озерное','абзелиловский',['Озерного отделения совхоза','Озёрного отделения','2007','2005']),(207,'Атавды','атавды','абзелиловский',['4-го отделения','2007','2005']),(3086,'Ишемгул','ишемгул','зианчуринский',['усадьбы совхоза','Иняк','2007']),(3097,'Арсёново (Башкортостан)','арсеново','зианчуринский',['усадьбы Сакмарского совхоза','2007']),(4761,'Первомайская (Башкортостан)','первомайская','мелеузовский',['усадьбы','Арслановского','Араслановского','2007']),(5100,'Родниковка (Башкортостан)','родниковка','миякинский',['Миякинской РТС','2007']),(844,'Сосновка (Баймакский район)','сосновка','баймакский',['Сосновского отделения','Сосновское отделение','2008','2005'])]
for ordinal,title,nn,co,terms in CASES:
 print(title)
 sid=f'2002:041_4b428edd23_Bashkiria_new.xls:Sheet1:{ordinal}';a=by.loc[sid];g=D[D.census_year.eq(2021)&D.region_norm.eq('башкортостан')&D.name_norm.eq(nn)&D.county.eq(co)];assert len(g)==1 and a.county==co;b=g.iloc[0];g=D[D.root.eq(b.root)];
 if set(g.census_year)=={2021}:
  mid=D[D.census_year.eq(2010)&D.region_norm.eq('башкортостан')&D.name_norm.eq(nn)&D.county.eq(co)];assert len(mid)==1 and mid.type_norm.iloc[0]==b.type_norm;g=pd.concat([g,mid]);edge.append(dict(from_source_record_id=mid.source_record_id.iloc[0],to_source_record_id=b.source_record_id,relation='same_place',decision_status='checked_rule_accepted',admission_method='unique_exact_own_name_type_and_native_county',admission_rule='Only own named2010 and2021 Sосновка in Баймакскийcounty, same village type; cached ownarticle confirms county and prior Сосновскоеотделение history.',population_boundary_comparability_asserted=False,evidence_file=str(O/'identity_point_witnesses.json.gz'),evidence_locator='[7]'))
 assert 2002 not in set(g.census_year)and set(g.census_year)=={2010,2021};c=cache[title];pg=c['page'];text=pg['revisions'][0]['slots']['main']['content'];ls=[dict(line=i,text=l)for i,l in enumerate(text.splitlines(),1)if any(t.lower()in l.lower()for t in terms)];assert len(ls)>1
 wid=len(wit);wit.append(dict(target_source_record_id=sid,current_source_record_id=b.source_record_id,old_name_raw=a.settlement_name,old_type_raw=a.settlement_type,old_county=a.district_raw,current_name_raw=b.settlement_name,current_type_raw=b.settlement_type,current_county=b.district_raw,source_file=c['source_path'],source_sha256=c['source_sha256'],pageid=pg['pageid'],revision=pg['revisions'][0]['revid'],literal_excerpt=ls,current_native_rivals=g.source_record_id.tolist(),interpretation='Dated own locality renaming and where applicable documented2005 settlement category change; own same NP continuity; original population quality/counts untouched.'))
 edge.append(dict(from_source_record_id=sid,to_source_record_id=b.source_record_id,relation='same_place',decision_status='checked_rule_accepted',admission_method='literal_dated_own_locality_alias_and_sourcecounty_native_continuity',admission_rule='Own locality cached article literal former name and dated renaming, independently matching source county, no2002 member in current two-year component; published type retained; no boundary equivalence assertion.',population_boundary_comparability_asserted=False,evidence_file=str(O/'identity_point_witnesses.json.gz'),evidence_locator=f'[{wid}]'))
 donor=next(P.loc[s]for s in g.source_record_id if s in P.index)
 for target in [sid]+g.source_record_id.tolist():
  if target in P.index:continue
  pts.append(dict(target_source_record_id=target,**{k:donor[k]for k in ['latitude','longitude','coordinate_source_record_id','point_origin_file','point_origin_sha256','point_origin_locator','point_origin_kind']},coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_binding_rule='literal_dated_own_article_same_locality_rename_and_sourcecounty_native_identity',point_use_inference='Explicit retrospective representative point for renamed continued physical locality; census-date measurement and population boundaries unknown.',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,external_provider_ID_binding_asserted=False,current_carrier_source_record_id=donor.name))
 for target in [sid]+g.source_record_id.tolist():dis.append(dict(source_record_id=target,disposition='accepted_literal_dated_rename_ordinary_same_place_with_own_point',case=title))
with gzip.open(O/'identity_point_witnesses.json.gz','wt')as f:json.dump(wit,f,ensure_ascii=False)
pd.DataFrame(edge).to_csv(O/'accepted_identity_edge_delta.csv',index=False);pd.DataFrame(pts).to_csv(O/'accepted_point_use_delta.csv',index=False);pd.DataFrame(dis).to_csv(O/'record_dispositions.csv',index=False);print(len(edge),len(pts))
