from pathlib import Path
import pandas as pd,json,gzip,hashlib,xlrd
O=Path(__file__).parent;M=Path('/workspace/russian-settlements-research/research_rebuild/evidence/over1000_moscow_20261009');E=O.parent;sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();d=pd.read_csv(M/'moscow_native_all_years_stage68.csv.gz');p=pd.read_csv(M/'moscow_ownpoint_snapshot68.csv.gz').drop_duplicates('target_source_record_id',keep='last').set_index('target_source_record_id');credited=set(pd.read_csv(E/'main_axis_residual_application68_20261008/applied_primary_credited_UID_roster.csv.gz').source_record_id);pgs={}
for f in list(M.glob('own_wikipedia_batch*.json.gz'))+list((O.parent/'over1000_moscow_remaining13_20261009').glob('own_wikipedia_batch*.json.gz')):
 for pg in json.load(gzip.open(f,'rt'))['query']['pages'].values():
  if 'missing'not in pg:pgs[pg['title']]=(pg,f)
bio='2002:010_3e630cc803_02c_Moskovskaya-oblast.xls:Sheet1:5450';usp='2021:data_allsettlements_anon_156_v20251217.parquet:parquet:70212';ur=d[d.source_record_id.eq(usp)].iloc[0].root
assert len(d[d.source_record_id.eq(bio)])==1 and set(d[d.root.eq(ur)].census_year)=={2010,2021};d.loc[d.source_record_id.eq(bio),'root']=ur
p.loc[bio]=p.loc[usp];p.loc[bio,'coordinate_source_record_id']=usp
configs=[('Луговая','2002:1_TOM_01_04.xls:0:1040','Лобня','Луговая (Лобня)','2004-01-22','day','1976',None),('Светлый','2002:010_3e630cc803_02c_Moskovskaya-oblast.xls:Sheet1:3811','Электроугли','Вишняковские Дачи','2005-02-15','day','Светлый',-2),('совхоза Серебряные Пруды','2002:010_3e630cc803_02c_Moskovskaya-oblast.xls:Sheet1:5449','Успенский','Совхозный сельский округ (Московская область)','2003-01-10','day','10 января 2003',7690630),('Центральной Усадьбы совхоза им. Чапаева','2002:010_3e630cc803_02c_Moskovskaya-oblast.xls:Sheet1:3920','Ямкино','Ямкино (Московская область)','2004-02-18','day','18.02.2004',-3)]
pointrows=[];obs=[];points=[];events=[];edges=[];credits=[];contexts=[];raws=[];excerpts=[];statuses=[];geo=pd.read_csv(M/'raw2011_geo_all_ownname_candidates.csv',dtype=str);rawfile=Path('/workspace/settlements-raw/data/raw/2002/010_3e630cc803_02c_Moskovskaya-oblast.xls');rawfederal=Path('/workspace/settlements-raw/data/raw/2002_official_tom1/1_TOM_01_04.xls');geoDBF=Path('/workspace/settlements-raw/data/raw/historical_geography/geokladr_okato_2011/okato.dbf');sh2=xlrd.open_workbook(str(rawfile)).sheet_by_index(0);shfed=xlrd.open_workbook(str(rawfederal)).sheet_by_index(0)
for name,sid,recipient,title,date,precision,term,georec in configs:
 old=d[d.source_record_id.eq(sid)].iloc[0];assert sid not in credited;pg,f=pgs[title];txt=pg['revisions'][0]['slots']['main']['*'];lines=[dict(line=i,text=l)for i,l in enumerate(txt.splitlines(),1)if term in l or (name=='Светлый' and '15 февраля 2005' in l)];assert lines;loc=f'pageid={pg["pageid"]};revision={pg["revisions"][0]["revid"]}';source=sha(f)
 cg=d[d.name_norm.eq(recipient.lower().replace('ё','е'))];cg=cg[cg.settlement_type.eq('город')]if recipient in ['Пушкино','Электроугли','Волоколамск','Лобня']else cg[cg.settlement_type.isin(['село','деревня','посёлок'])];cur=cg[cg.census_year.eq(2021)];assert len(cur)==1,(name,'receivercurrent',len(cur));cur=cur.iloc[0];cg=d[d.root.eq(cur.root)];assert len(cg)==3 and set(cg.census_year)=={2002,2010,2021};assert (set(cg.source_record_id)<=credited or recipient=='Успенский') and all(s in p.index for s in cg.source_record_id),(name,'receiver');scope='over1000_moscow_geonames_included_'+str(sid.rsplit(':',1)[1]);pop=int(old.population)
 if sid in p.index and georec is None:
  cp=p.loc[sid];lat,lon=cp.latitude,cp.longitude;pf=cp.point_origin_file;ph=cp.point_origin_sha256;pl=cp.point_origin_locator;pk=cp.point_origin_kind;pcs=cp.coordinate_source_record_id
 elif georec==-3:
  hf=O/'Chapaev_own_historical_photo_1171604.html.gz';hj=json.loads((O/'Chapaev_historical_photo_1171604_owngeo_witness.json').read_text());assert hj['cid']==1171604 and hj['year']==1977 and 'Центральная усадьба, дом 10' in hj['address'];lat,lon=hj['geo'];pf=str(hf);ph=sha(hf);pl='Pastvu:cid1171604;init.photo.photo.geo;ownhistoricalestateaddress=Центральнаяусадьбадом10;photoyear1977';pk='own_former_NP_qualified_historical_address_manual_geotag_representative_point';pcs='Pastvu:1171604:geo'
  pointrows.append(dict(source_record_id=sid,source_path=pf,source_sha256=ph,source_locator=pl,raw_geographic_record_json=json.dumps(hj,ensure_ascii=False),native_binding='Own historical Chapaev centralestate housing settlement explicitlynamed andfulladdressCentralEstatehouse10 atnativeproperNoginskYamkino county. Manualgeotag ofownNPaddress representativepoint, notNPcentroid orcensusdaymeasurement. Nearbyseparatehistoricalestatephoto1171597 independentlycorroboratesarea; water-towerfacilitypoint excluded. No receivingYamkino pointsubstitution.'))
 elif georec==-2:
  nf=O/'nominatim2.json.gz';nr=json.load(gzip.open(nf,'rt'));assert len(nr)==1 and nr[0]['osm_id']==7790795 and nr[0]['category']=='place' and nr[0]['type']=='suburb';no=nr[0];lat,lon=float(no['lat']),float(no['lon']);pf=str(nf);ph=sha(nf);pl='result[0]:OSMrelation7790795;place/suburb;ownname=Светлый микрорайон;fields=lat,lon';pk='own_named_former_NP_independent_OSM_named_residential_suburb_representative_point';pcs='OSM:relation:7790795'
  pointrows.append(dict(source_record_id=sid,source_path=pf,source_sha256=ph,source_locator=pl,raw_geographic_record_json=json.dumps(no,ensure_ascii=False),native_binding='Exact own formerSvetly settlement modernplace/suburb reference feature within actualreceivingElectric; printednative3811 ownposelok subordinateVDachi, explicit9Aug2004 inclusion confirms properlocality. Notreceivertownpoint, road, factory orstation.'))
 elif georec:
  import zipfile
  zp=Path('/workspace/settlements-raw/data/raw/coordinate_candidates/geonames_RU_20260907.zip')
  with zipfile.ZipFile(zp).open('RU.txt') as gf:
   for lineno,bb in enumerate(gf,1):
    cc=bb.decode().rstrip('\n').split('\t')
    if cc[0]==str(georec):break
   else:raise AssertionError(georec)
  assert cc[6]=='P' and cc[10]=='47';lat,lon=float(cc[4]),float(cc[5]);pf=str(zp);ph=sha(zp);pl=f'RU.txt:line{lineno};geonameid={georec};feature={cc[7]};fields=latitude,longitude;ownname={cc[1]};aliases={cc[3]}';pk='own_named_former_NP_GeoNames_cached_retained_PPL_or_PPLH_point';pcs='GeoNames:'+str(georec)
  binding={'7690630':'Own Sovkhozny PPL in Serebryanye Prudy54.4344/38.7082, printed2002sameСовхозныйcountycentre NPсовхозСеребряныеПруды. Exactowncountyarticle connectscentralestate1932properfarmname and2003inclusion intoBiokhim renamedUspensky. Farm7690324FRMandKlinSovkhozny7601300excluded; currentreceiverpointnotassignedoldchild.','472431':'Own PPLH historical-locality name Volokolamets plus exact alias Sovkhoz Volokolamskiy corresponds printed Volokolamsk county and documented prior name; no city point substitution.','495392':'Own Shchekino PPL near Volokolamsk at56.07511/35.92963; competing Klin Shchekino49539156.13333/36.68333 explicitly excluded by source county. Exact source-name and county spatial context distinguish Moscow rivals.','570450':'Own PPL record explicit aliases Poselok Buzhaninovo; separate station13255731 featureRSTN excluded. Native2002 ownposelok and coexisting selo distinguished by explicit settlement-type alias; no station or receiver point substitution.'}[str(georec)]
  pointrows.append(dict(source_record_id=sid,geonameid=georec,source_path=pf,source_sha256=ph,source_locator=pl,raw_geonames_cells_json=json.dumps(cc,ensure_ascii=False),native_binding=binding))

 else:
  co=pg['coordinates'][0];lat,lon=co['lat'],co['lon'];pf=str(f);ph=source;pl=loc+':coordinates[0]';pk='own_named_former_NP_Wikipedia_physical_reference_point';pcs=pl
 obs.append(dict(scope_id=scope,place=name,year=2002,source_record_id=sid,native_population=pop,native_population_quality=old.population_value_quality,latitude=lat,longitude=lon,own_point=True,recipient_city=recipient,receiving_NP_actual_type=cur.settlement_type,event_date=date,event_date_precision=precision,event_relation='included_in',same_place_identity_asserted=False,receiving_city_2021_source_record_id=cur.source_record_id,receiving_city_2021_count_context_only=int(cur.population),child_2021_population_assigned=False,is_additive_to_original_final_mixed_census_axis=False,already_in_baseline68_primary_native_ID_union=False,new_native_population_if_event_admitted=pop,whole_city_roster_closure_asserted=False,population_boundary_comparability_asserted=False,native_values_quality_preserved=True))
 points.append(dict(scope_id=scope,target_source_record_id=sid,source_record_id=sid,latitude=lat,longitude=lon,coordinate_admission_status='reviewed_rule_accepted',decision_status='reviewed_rule_accepted',coordinate_source_record_id=pcs,source_sha256=ph,source_locator=pl,point_origin_file=pf,point_origin_sha256=ph,point_origin_locator=pl,point_origin_kind=pk,own_locality_point=True,recipient_point_assigned_to_child=False,new_ordinary_point_use_proposed=sid not in p.index,point_temporal_interpretation='Independent modern retained ownformerNP physical reference point used retrospectively for native2002; no censusday directcoordinate claim',direct_historical_coordinate_measurement=False,provider_binding_asserted=False,boundary_comparability_asserted=False))
 events.append(dict(scope_id=scope,former_locality=name,recipient_city=recipient,receiving_NP_type=cur.settlement_type,event_date=date,date_precision=precision,relation='included_in',same_place=False,event_source_file=str(f),event_source_sha256=source,event_source_locator=loc,event_source_quality='secondary_literal_dated_former_NP_inclusion_own_or_receiver_article',event_date_role='Literal dated inclusion wording; cited actdate not independently promoted to operative day',decision_status='accepted_secondary_article_included_in',primary_law_source_reopened=False,boundary_comparability='UNKNOWN',roster_closed=False,sum_city_equals_children_asserted=False))
 edges.append(dict(scope_id=scope,from_source_record_id=sid,to_source_record_id=cur.source_record_id,relation='included_in',event_date=date,date_precision=precision,event_source_file=str(f),event_source_sha256=source,event_source_locator=loc,same_place=False,graph_union_allowed=False,whole_city_roster_closure_asserted=False,modern_boundary_reconstruction=False))
 credits.append(dict(scope_id=scope,source_record_id=sid,year=2002,source_population=pop,new_population_on_separate_transformation_path_axis=pop,own_historical_point_verified=True,receiving_city_actual_2002_2010_2021_context_verified=True,is_additive_to_original_final_mixed_census_axis=False,ordinary_three_census_same_place_claim=False))
 if name=='Луговая':
  lf=O/'Lugovaya2004_inclusion_mirrored_legal_text.html.gz';lt=(O/'Lugovaya2004_literal_text.txt').read_text();assert'от 22 января 2004' in lt and'Объединить дачный поселок Луговая' in lt
  lloc='Moscowiki:legalact_ru50000200400047;oldid360649;decree22Jan2004no11-PG;paragraphs1-2';lh=sha(lf)
  for rr in [events[-1],edges[-1]]:rr.update(event_source_file=str(lf),event_source_sha256=lh,event_source_locator=lloc)
  events[-1]['event_source_quality']='secondary_mirror_full_literal_legal_text_with_actdate_and_publication_metadata';events[-1]['event_date_role']='Quotedlegalactdate22Jan2004; publication03Feb2004 and07Feb2004 retained; operativeeffective exactday not independentlyimputed';events[-1]['earlier1976_claim_resolution']='1976 administrativesubordination, notseparateNPcessation; native2002publication explicitlypgtunderLobnya. Quarterinfobox1976incorporationrejected asstatgrainmislabel.'
 if name=='Светлый':
  events[-1]['relation']='included_in_via_documented_intermediate_NP';events[-1]['first_inclusion_date']='2004-08-09';events[-1]['intermediate_native_source_record_id']='2002:1_TOM_01_04.xls:0:1221';events[-1]['intermediate_NP']='Вишняковские Дачи';edges[-1]['relation']='included_in_via_documented_intermediate_NP';edges[-1]['first_inclusion_date']='2004-08-09';edges[-1]['intermediate_native_source_record_id']='2002:1_TOM_01_04.xls:0:1221';obs[-1]['event_relation']='included_in_via_documented_intermediate_NP';obs[-1]['first_inclusion_date']='2004-08-09'
 if recipient=='Успенский':
  events[-1]['requires_ordinary_receiver_Biokhim5450_to_Uspensky70212_rename_delta']=True;events[-1]['recipient_original2002_name']='Биохимзавода';events[-1]['recipient_rename_date']='2003-05-14';events[-1]['generic_formation_successor2002_label_not_imputed']=True
 rowno=int(sid.rsplit(':',1)[1]);sf=rawfederal if'1_TOM'in sid else rawfile;ss=shfed if'1_TOM'in sid else sh2;vals=ss.row_values(rowno-1);assert any(str(v).replace('.0','')==str(pop)for v in vals);raws.append(dict(source_record_id=sid,year=2002,native_population=pop,native_quality=old.population_value_quality,source_path=str(sf),source_sha256=sha(sf),source_locator=f'{ss.name}:row{rowno}',raw_cells_json=json.dumps(vals[:8],ensure_ascii=False),matches_native_population=True));excerpts.append(dict(scope_id=scope,source_path=str(lf) if name=='Луговая' else str(f),source_sha256=lh if name=='Луговая' else source,source_locator=lloc if name=='Луговая' else loc,literal_excerpts_json=json.dumps([dict(text=lt)] if name=='Луговая' else lines,ensure_ascii=False)))
 for y in [2002,2010,2021]:statuses.append(dict(scope_id=scope,place=name,year=y,status='actual_separate_own_published_observation'if y==2002 else'ceased_as_separate_locality_included_in_recipient_before_census',own_population=pop if y==2002 else'',unknown_is_zero=False,recipient_population_assigned_to_child=False,boundary_comparability='UNKNOWN'))
 for r in cg.itertuples():
  cp=p.loc[r.source_record_id];contexts.append(dict(scope_id=scope,recipient_city=recipient,receiving_NP_actual_type=r.settlement_type,census_year=r.census_year,source_record_id=r.source_record_id,population=r.population,population_value_quality=r.population_value_quality,latitude=cp.latitude,longitude=cp.longitude,point_ledger_path=cp.point_ledger_path,is_receiving_city_context_only=True,new_national_credit_population=0,child_count_substituted=False,already_in_baseline68_primary_credit=r.source_record_id in credited))
for n,rows in [('accepted_historical_observations.csv',obs),('accepted_former_locality_own_points.csv',points),('accepted_inclusion_events.csv',events),('accepted_included_in_event_edges.csv',edges),('accepted_direct_event_native_credit_union.csv',credits),('actual_receiving_city_three_census_context.csv',contexts),('event_native_raw_row_witnesses.csv',raws),('literal_own_inclusion_source_excerpts.csv',excerpts),('accepted_available_year_statuses.csv',statuses)]:pd.DataFrame(rows).to_csv(O/n,index=False)
print('events',len(events),'old02credit',sum(r['source_population']for r in credits),'contexts',len(contexts))

pd.DataFrame(pointrows).to_csv(O/'independent_own_GeoNames_binding_witnesses.csv',index=False)
