from pathlib import Path
import sys,json,collections,re,ast,math,gzip
import pandas as pd
R=Path('/workspace/russian-settlements-research');sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from working_state_20261007 import load,PARTITION_MEMBERS
from current_chain_state_20261007 import normalize,distance_km,sha
from apply_unique_county_name_bridge_20261007 import county_key
O=Path(__file__).parent;E=O.parents[1];I=O.parent/'candidate_native_context_current_ownpoint.csv.gz';s=load(32);pins={str(p):sha(p)for p in s.inputs};pins[str(I)]=sha(I);d=pd.read_csv(I,keep_default_na=False);d=d[d.existing_same_place_component&d.missing_point_source_IDs_json.map(lambda v:not json.loads(v))].drop_duplicates('to_source_record_id')
credit=set();creditreason=collections.defaultdict(set)
for p,label in [(PARTITION_MEMBERS,'complete_partition'),(E/'working_full_chain_20261007/qualified_scope_source_id_credit_union.csv','qualified_secondary_or_scoped_native_reference'),(E/'working_full_chain_20261007/named_merger_lineage_constituents.csv','named_merger_constituent'),(E/'working_full_chain_20261007/complete_territorial_scope_constituents.csv','complete_territorial_constituent')]:
 pins[str(p)]=sha(p);f=pd.read_csv(p,dtype=str,keep_default_na=False)
 for c in f:
  if c=='source_record_id':
   for sid in f[c]:credit.add(sid);creditreason[sid].add(label)
# The extra accepted city/subordinate roster and municipal transfer packs are also native-ID references, never invented third-year NP observations.
for folder in ['qualified_scoped_municipal_three_census_20261008','city_primary2002_mass_application_20261008','source_closed_city_territory_application_20261008']:
 p=E/folder
 if p.exists():
  for fpath in p.glob('*credit*csv'):
   pins[str(fpath)]=sha(fpath);f=pd.read_csv(fpath,dtype=str,keep_default_na=False)
   for c in f:
    if c=='source_record_id':
     for sid in f[c]:credit.add(sid);creditreason[sid].add(folder)
def code(v):
 if pd.isna(v):return ''
 x=str(v);return x[:-2]if x.endswith('.0')else x
obs=s.obs.copy();obs['n']=obs.name_norm.map(normalize);obs['r']=obs.region_norm.map(normalize);obs['code']=obs.okato.map(code);idx={k:g for k,g in obs.groupby(['census_year','n','r'])};codeidx={k:g for k,g in obs[obs.code.ne('')].groupby(['census_year','code'])};members={k:g for k,g in obs.groupby('root')}
aliaspath=E/'cross_county_independent_point_bridge_20261007/build_neutral_subset.py';tree=ast.parse(aliaspath.read_text());pairs=ast.literal_eval(next(x.value for x in tree.body if isinstance(x,ast.Assign)and any(isinstance(t,ast.Name)and t.id=='pairs'for t in x.targets)));neutral={frozenset([county_key(a),county_key(b)])for a,b in pairs.items()};pins[str(aliaspath)]=sha(aliaspath)
qcode=collections.defaultdict(set);T=Path('/workspace/settlements-raw/data/raw/wikimedia/wikidata_oktmo_entities.tsv');pins[str(T)]=sha(T)
for line in T.open():
 v=line.rstrip().split('\t');qs=re.findall(r'Q\d+',v[0])if v else[]
 if not qs or len(v)<3:continue
 for c in re.findall(r'\d{8,11}',v[1]+' '+v[2]):qcode[c].add(qs[0])
rows=[];candidates=[]
for z in d.to_dict('records'):
 sid=z['to_source_record_id'];cur=s.by_id.loc[sid];group=members[s.uf.find(sid)];years=set(group.census_year);missing=({2002,2010,2021}-years)
 if len(missing)!=1:continue
 my=next(iter(missing));currentcounty=county_key(cur.district_raw);exact=idx.get((my,normalize(cur.name_norm),normalize(cur.region_norm)),pd.DataFrame());cc=codeidx.get((my,code(cur.okato)),pd.DataFrame())if code(cur.okato)else pd.DataFrame();ids=set(exact.source_record_id)if len(exact)else set();ids.update(cc.source_record_id if len(cc)else []);cand=[]
 for x in sorted(ids):
  old=s.by_id.loc[x];own=bool(old.is_additive_settlement_record);oldcounty=county_key(old.district_raw);samecounty=bool(oldcounty)and(oldcounty==currentcounty or frozenset([oldcounty,currentcounty])in neutral);already2021=2021 in s.years[s.uf.find(x)];ptype=normalize(old.type_norm);typecompat=(ptype==normalize(cur.type_norm)or ptype in ['село','деревня','поселок','хутор','станица']and normalize(cur.type_norm)in ['село','деревня','поселок','хутор','станица']);candidate={'trajectory_current_source_record_id':sid,'missing_year':my,'missing_selected_source_record_id':x,'missing_source_native_name':old.settlement_name,'missing_source_type':old.settlement_type,'missing_source_county':old.district_raw,'missing_source_population':None if pd.isna(old.population)else float(old.population),'missing_source_population_quality':old.population_value_quality,'missing_source_file':old.source_file,'missing_source_locator':old.source_locator,'same_exact_native_name':normalize(old.name_norm)==normalize(cur.name_norm),'same_native_code':bool(code(cur.okato))and code(old.okato)==code(cur.okato),'county_same_or_reviewed_neutral_caption':samecounty,'type_compatible_or_rural_change':typecompat,'is_own_additive_native_record':own,'already_in_accepted_current_component':already2021,'already_credited_native_ID':x in credit,'accepted_component_years':json.dumps(sorted(s.years[s.uf.find(x)]))};cand.append(candidate);candidates.append(candidate)
 unclaimed=[x for x in cand if x['is_own_additive_native_record']and not x['already_in_accepted_current_component']];context=[x for x in unclaimed if x['county_same_or_reviewed_neutral_caption']and x['type_compatible_or_rural_change']];codepositive=[x for x in unclaimed if x['same_native_code']];unioncredit=[x for x in group.source_record_id if x in credit];existingknown={str(int(x.census_year)):None if pd.isna(x.population)else float(x.population)for x in group.itertuples()};cp=s.point_rows[sid];qids=set(re.findall(r'\bQ\d+\b',str(cp.get('coordinate_source_record_id',''))+' '+str(cp.get('point_origin_locator',''))));qids|=qcode.get(code(cur.okato),set());qids|=qcode.get(code(cur.oktmo),set())
 if unioncredit:route='excluded_existing_native_source_ID_credit_union'
 elif len(codepositive)==1:route='existing_missing_year_native_code_candidate_source_binding_needed'
 elif len(context)==1:route='existing_exact_name_county_type_native_row_source_binding_needed'
 elif unclaimed:route='existing_exact_name_native_rows_county_or_competitor_resolution_needed'
 elif cand:route='existing_native_exact_name_or_code_already_attached_to_other_current_object'
 else:route='no_selected_exact_name_or_current_code_third_year_row_observed_source_needed'
 rows.append({'trajectory_current_source_record_id':sid,'missing_year':my,'name':cur.settlement_name,'region':cur.region_norm,'current_county':cur.district_raw,'current_type':cur.settlement_type,'current_native_okato':code(cur.okato),'current_native_oktmo':code(cur.oktmo),'existing_years':json.dumps(sorted(years)),'existing_source_IDs_json':json.dumps(list(group.source_record_id)),'population_2002':existingknown.get('2002',''),'population_2010':existingknown.get('2010',''),'population_2021':existingknown.get('2021',''),'maximum_observed_population':max(v for v in existingknown.values()if v is not None),'sum_existing_native_population':sum(v for v in existingknown.values()if v is not None),'exact_name_third_year_selected_rows':len(exact),'same_current_code_third_year_selected_rows':len(cc),'unclaimed_own_native_candidates':len(unclaimed),'positive_county_type_native_candidates':len(context),'positive_owncode_native_candidates':len(codepositive),'route':route,'existing_credit_source_IDs_json':json.dumps(unioncredit),'existing_credit_scopes_json':json.dumps(sorted({v for x in unioncredit for v in creditreason[x]})),'current_ownpoint_qids_json':json.dumps(sorted(qids)),'current_ownpoint_origin_file':cp.get('point_origin_file',''),'current_ownpoint_origin_locator':cp.get('point_origin_locator',''),'historical_creation_absorption_or_namechange_asserted':False,'actual_missing_count_observed':bool(unclaimed),'ordinary_identity_admission_asserted':False})
f=pd.DataFrame(rows);f.to_csv(O/'temporal_gap_trajectories.csv.gz',index=False,compression={'method':'gzip','mtime':0});cf=pd.DataFrame(candidates);cf.to_csv(O/'selected_missing_year_native_candidates.csv.gz',index=False,compression={'method':'gzip','mtime':0});active=f[f.route.ne('excluded_existing_native_source_ID_credit_union')];summary=active.groupby(['missing_year','region','route']).agg(trajectories=('name','size'),maximum_observed_population=('maximum_observed_population','sum'),known2002=('population_2002',lambda x:pd.to_numeric(x,errors='coerce').sum()),known2010=('population_2010',lambda x:pd.to_numeric(x,errors='coerce').sum()),known2021=('population_2021',lambda x:pd.to_numeric(x,errors='coerce').sum())).reset_index().sort_values('maximum_observed_population',ascending=False);summary.to_csv(O/'temporal_gap_routes_by_region.csv',index=False);pd.concat([g.nlargest(20,'maximum_observed_population')for _,g in active.groupby('missing_year')]).to_csv(O/'top20_each_missing_year.csv',index=False);summary.head(30).to_csv(O/'top30_route_region_groups.csv',index=False)
r={'status':'temporal_diagnostic_only_no_missing_counts_created','baseline_stage':32,'input_two_year_trajectories':len(f),'existing_native_union_credit_excluded':int(f.route.eq('excluded_existing_native_source_ID_credit_union').sum()),'active_two_year_trajectories':len(active),'by_missing_year':{str(y):{'trajectories':len(g),'maximum_observed_population_weight':int(g.maximum_observed_population.sum()),'existing_native_population_by_year':{str(yy):int(pd.to_numeric(g[f'population_{yy}'],errors='coerce').sum())for yy in [2002,2010,2021]},'routes':g.route.value_counts().to_dict()}for y,g in active.groupby('missing_year')},'routes_by_max_observed_population':active.groupby('route').maximum_observed_population.sum().astype(int).to_dict(),'unknown_creation_or_absorption_never_asserted_from_absence':True,'current_QID_binding_not_new_admission':True,'coordinates_or_source_counts_modified':False,'input_pins':pins,'outputs':{p.name:sha(p)for p in O.glob('*.csv*')}};(O/'diagnostic_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2));print(json.dumps({k:r[k]for k in ['input_two_year_trajectories','existing_native_union_credit_excluded','active_two_year_trajectories','by_missing_year','routes_by_max_observed_population']},ensure_ascii=False))
