from pathlib import Path
import pandas as pd,json,gzip,hashlib,xlrd
O=Path(__file__).parent;B=O.parent;D=pd.read_pickle('/dev/shm/over500-20261009/east_enriched.pkl');R=pd.read_csv(B/'assigned.csv').fillna('');by=D.set_index('source_record_id');par={};points=set(pd.read_parquet('/dev/shm/over500-20261009/points_compact.parquet',columns=['target_source_record_id']).target_source_record_id);events=set();edge_total=0;point_total=0;packets=[B]+[B/f'subbatch{k}'for k in range(2,8)]
def find(a):
 if a not in par:par[a]=a
 if par[a]!=a:par[a]=find(par[a])
 return par[a]
for z in packets:
 E=pd.read_csv(z/'accepted_identity_edge_delta.csv');P=pd.read_csv(z/'accepted_point_use_delta.csv');edge_total+=len(E);point_total+=len(P);points.update(P.target_source_record_id)
 for e in E.itertuples():par[find(by.loc[e.from_source_record_id,'root'])]=find(by.loc[e.to_source_record_id,'root'])
 if(z/'accepted_available_year_statuses.csv').exists():events.update(pd.read_csv(z/'accepted_available_year_statuses.csv').target_source_record_id)
D['newroot']=D.root.map(find);years=D.groupby('newroot').census_year.agg(lambda x:','.join(map(str,sorted(set(x)))));rows=[]
for r in R.itertuples():
 root=find(by.loc[r.source_record_id,'root']);yr=years[root];part='часть'in r.name_norm;own=r.source_record_id in points;route=bool(r.has_admitted_route)or yr=='2002,2010,2021'or r.source_record_id in events
 rows.append(dict(source_record_id=r.source_record_id,census_year=r.census_year,settlement_name=r.settlement_name,region_norm=r.region_norm,effective_population=r.effective_population,baseline_ownpoint=r.has_ownpoint,baseline_admitted_route=r.has_admitted_route,result_ownpoint=own,result_admitted_route_predicted=route,result_component_years=yr,disposition='typed_literal_part_exempt_from_whole_NP_ownpoint_target'if part else'resolved_ownpoint_and_admitted_route'if own and route else'ownpoint_resolved_temporal_route_still_unknown'if own else'temporal_route_resolved_ownpoint_still_unknown'if route else'ownpoint_and_route_still_unknown',result_measurement='Local seven-packet native component+point replay diagnostic; root actual full-state API integration controls final credit.'))
pd.DataFrame(rows).to_csv(O/'all235_exact_record_dispositions.csv',index=False);pd.DataFrame(rows)[pd.DataFrame(rows).disposition.ne('resolved_ownpoint_and_admitted_route')].to_csv(O/'remaining_exact_record_dispositions.csv',index=False)
F=Path('/dev/shm/settlements-stage71-20261009/accepted_large_record_scope_classification_overlay.csv');S=pd.read_csv(F);part=R[R.name_norm.str.contains('часть')];sid=part.source_record_id.iloc[0];s=S[S.source_record_id.eq(sid)];
if len(s)==0:
 r=part.iloc[0];a={c:'' for c in S.columns};a.update(source_record_id=sid,census_year=2002,source_name=r.settlement_name,source_type=r.settlement_type,region_norm=r.region_norm,district_raw=r.district_raw,source_population=r.population,scope_class='literal_part_source_observation',whole_named_NP_ownpoint_target=False,scope_review_status='checked_literal_part_source_scope_accepted',stage68_component_root=r.root,stage68_has_own_point=False,ordinary_identity_or_population_equivalence_asserted=False,source_count_or_quality_changed=False,evidence_basis='Native own census source literal part2 designation independently read back in raw Sheet1 row0=1676; same scope semantics as accepted stage71 literalpart overlay.',source_scope_exclusion_rationale='Source leaf is an explicit numbered part of own named NP; retain its766 published persons as a part count, not wholeNP ownpointtarget. No recipientpoint assigned.',source_count_raw_population_retained=True,population_value_modified_or_allocated=False,source_file=r.source_file,source_locator=sid);s=pd.DataFrame([a]);
assert len(s)==1 and not bool(s.whole_named_NP_ownpoint_target.iloc[0]);s.to_csv(O/'accepted_literal_part_scope_classification_delta.csv',index=False)
raw=Path('/workspace/settlements-raw/data/raw/2002/041_4b428edd23_Bashkiria_new.xls');sh=xlrd.open_workbook(str(raw)).sheet_by_name('Sheet1');rr=int(sid.rsplit(':',1)[1])-1;assert'часть 2'in str(sh.row_values(rr));sha=lambda x:hashlib.sha256(Path(x).read_bytes()).hexdigest();(O/'literal_part_reuse_witness.json').write_text(json.dumps(dict(source_record_id=sid,source_file=str(raw),source_sha256=sha(raw),source_locator=f'Sheet1:row0={rr}',raw_cells=sh.row_values(rr),analogous_accepted_scope_schema_file=str(F),analogous_accepted_scope_schema_sha256=sha(F),classification='literal_part_source_observation',whole_named_NP_ownpoint_target=False,population_value_preserved=766.0,counts_modified=False),ensure_ascii=False,indent=2))
summary=dict(assigned_native_UIDs=len(R),accepted_edge_rows_all_packets=edge_total,accepted_point_rows_all_packets=point_total,separate_lifecycle_events=5,local_dispositions=pd.DataFrame(rows).disposition.value_counts().to_dict(),ordinary_component_years_unique=not(D[D.root.isin(par)].groupby(['newroot','census_year']).size()>1).any(),actual_API_application_pending_root=True);(O/'handoff_receipt.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2));(O/'freeze_manifest.json').write_text(json.dumps(dict(packets=[dict(path=str(z),manifest_sha256=sha(z/'freeze_manifest.json'))for z in packets],frozen_files=[dict(name=f.name,sha256=sha(f),bytes=f.stat().st_size)for f in sorted(O.iterdir())if f.is_file()and f.name!='freeze_manifest.json']),ensure_ascii=False,indent=2));print(summary)
