from pathlib import Path
import pandas as pd,json,hashlib,shutil,gzip
E=Path('/workspace/russian-settlements-research/research_rebuild/evidence');I=E/'remaining_moscow_complete_sourceyear_scopes_20261008';O=Path(__file__).parent;sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
r=json.loads((I/'candidate_receipt.json').read_text());assert r['candidate_folder_frozen'] and r['scope_count']==6 and r['baseline_stage']==39
for fn,h in r['outputs'].items():assert sha(I/fn)==h
pins=json.loads((I/'source_manifest.json').read_text())
for p,h in pins.items():assert sha(p)==h
status='applied_complete_sourceyear_municipal_scope_secondary_sources'
for src,dst in [('candidate_scope_observations.csv','accepted_transferred_municipal_scope_observations.csv'),('candidate_native_scope_constituents.csv','accepted_native_scope_constituents.csv'),('candidate_municipal_representative_points.csv','accepted_municipal_representative_points.csv'),('sourceyear_scope_changes.csv','accepted_sourceyear_composition_change_qualifiers.csv')]:
 d=pd.read_csv(I/src,keep_default_na=False);d['decision_status']='qualified_accepted_complete_sourceyear_municipal_scope_secondary_sources';d['same_place_identity_asserted']=False;d['modern_boundary_series_asserted']=False;d['historical_representative_is_territorial_inference_only']=True;d['scope_year_link_relation']='sourceyear_territorial_composition_change_or_legal_transformation_boundary_unknown';d['individual_NP_point_assigned']=False
 d.to_csv(O/dst,index=False)
m=pd.read_csv(O/'accepted_native_scope_constituents.csv',keep_default_na=False);assert len(m)==267 and m.selected_native_source_ID.sum()==251 and m[m.selected_native_source_ID].source_record_id.is_unique
aux=m[~m.selected_native_source_ID];assert len(aux)==16 and aux.native_population.eq('').all();assert aux.native_population_quality.eq('raw_count_blank_unknown_not_zero').sum()==15;assert aux.native_population_quality.eq('actual_raw_zero_absent_selected_layer_nonadditive').sum()==1
aux.to_csv(O/'auxiliary_raw_leaf_rows.csv',index=False);aux[aux.native_population_quality.eq('raw_count_blank_unknown_not_zero')].to_csv(O/'auxiliary_unknown_count_rows.csv',index=False);aux[aux.native_population_quality.eq('actual_raw_zero_absent_selected_layer_nonadditive')].to_csv(O/'auxiliary_actual_raw_zero_row.csv',index=False)
for fn in ['source_controls.csv','exact_literal2010_roster_to_raw_bindings.csv','literal2002_parent_nextparent_closures.csv','explicit_baseline39_candidate_native_ID_exclusions.csv','verified_six_net_native_mass_rank.csv','remaining_five_scope_status.csv','all21_municipality_inventory.csv','source_manifest.json','baseline39_input_context_hashes.json','actual_raw_reopened_rows.csv.gz','legal_literal_rosters_and_scope_changes.txt.gz']:
 shutil.copyfile(I/fn,O/fn);assert sha(O/fn)==sha(I/fn)
o=pd.read_csv(O/'accepted_transferred_municipal_scope_observations.csv');assert len(o)==18 and o.scope_id.nunique()==6
for z in o.itertuples():
 g=m[m.scope_id.eq(z.scope_id)&m.year.eq(z.census_year)];assert len(g)==z.native_members_count
 if z.census_year==2002:assert g.raw_population.astype(float).sum()==z.population
 assert not z.own_NP_series_asserted and not z.same_place_edge_created
assert m.groupby('year').new_native_population_if_scope_admitted.sum().to_dict()=={2002:32733,2010:33327}
r.update(status=status,root_loader_integration_pending=True,baseline39_union_not_future45_witness=True,root_authorization='Root explicitly accepted6 wholepublishedsourceyear ruralmunicipalpredecessor scopes. Other2 urbanpredecessor properPGT observations and Mosrentgen formationbranch keptOUTSIDE6completeownscope application. No authenticgrain conversion, ordinarysameplace, fakechild2021counts or administrativepointprojection.',source_controls_raw_checked=True,exact_literal2010_roster_members_verified=127,unknown_counts_preserved=True,actual_raw_zero_auxiliary_preserved=True,whole2010_sum_closure_asserted=False,same_place_identity_asserted=False,full_modern_boundary_series_asserted=False,native_chosen_counts_quality_unmodified=True,input_packet_sha256={str(I/fn):sha(I/fn) for fn in r['outputs']}|{str(I/'candidate_receipt.json'):sha(I/'candidate_receipt.json')},outputs={p.name:sha(p) for p in O.iterdir() if p.is_file() and p.name!='apply.py'},code_sha256={'apply.py':sha(O/'apply.py')})
(O/'application_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n');(O/'README.md').write_text('Applied6 completepublishedsourceyear municipalpredecessor scopes,18wholeobservations267rawleaf references251nativeIDs/15unknowncountaux/1genuinepublishedzeroaux. Native baseline39exclusive32733/33327/0; future45report recomputes uniqueUIDunion. Actual2002wholeprintedcouncilcontrols exact with literalallchildren and nextparent;2010wholeindependentlycensusreferencedmunicipaltotals retained separately fromcompleteprotectedknown/unknownrawrosters;2021wholemunicipaltotals observed, noNPchild2021counts. AllownmunicipalP625 points representative_scope only; zeroordinaryidentityedges and zeroindividualNPpointassignments. Sourceyearcompositionchanges explicit, boundariesUNKNOWN, no constantmodernbounds or populationredistribution. Raw/legal proofs copiedunchangedcompressed. UrbanPGTpredecessor formationpaths and Mosrentgen twoexistingpredecessor branch remainOUTSIDEthese6appliedscopes. Rootintegrationpending separately.\n');print(status,r['conditional_new_unique_native_population'])
