from pathlib import Path
import pandas as pd,json,gzip,hashlib,re,xlrd
O=Path(__file__).parent;R=pd.read_csv(O.parent/'remaining81_native_point_targets.csv').fillna('');D=pd.read_pickle('/dev/shm/over500-20261009/east_enriched.pkl');sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();W=[];P=[];raw=[]
S=[('Рябово','Рябово (село, Увинский район)','batch_02097.json.gz','Увинский','94244865005','Native ownпоселокРябово lies strictly between existingacceptedОльховка2401→2010Ольховка12203 and separately enumeratedдеревняРябово2405→2010деревняРябово12205; unique insidecounterpart isселоРябово12204/current157229. Publishedphysicaltypechange preserved, no sameplaceedge; directowncodedarticlepoint94244865005 selected, same-namevillage94244865006 and knownwrongGeo57.59334,52.52265 rejected.'),('Трубочево','Трубачево (Шегарский район)','batch_02445.json.gz','Шегарский','Больше-Трубочёвское','Native ownселоТрубочево matches uniqueШегарский owncodedarticle69258876001/69658455101 with explicit historicalБольше-Трубочёвское spelling, sourcecitation same2002Tomskaya.xls and nativeRussian95 corroboration. DifferentТомскийпоселокТрубачево retained as different physicalplace; sourceprintedspelling retained, no generic vowel replacement rule.'),('Мурадымово','Мурадым (Аургазинский район)','batch_01530.json.gz','Аургазинский','Образовано в 2002','Native single wholepostmerger2002census leafМурадымово862 inАургазинский binds currentwholeМурадым representativecore. Article explicit16May2002 formation by merger precedesOct2002census; no native separatelyenumeratedСтаромурадымово/Новомурадымово constituents, no countsum or constituent sameplaceedge/eventcredit asserted.') ]
for name,title,batch,county,needle,rule in S:
 t=R[R.settlement_name.eq(name)].iloc[0];d=D[D.source_record_id.eq(t.source_record_id)].iloc[0];assert county.lower() in t.district_raw.lower();F=Path('/workspace/settlements-raw/data/raw/wikipedia_articles')/batch;J=json.load(gzip.open(F));pi=next(i for i,p in enumerate(J['payload']['query']['pages'])if p['title']==title);page=J['payload']['query']['pages'][pi];text=page['revisions'][0]['slots']['main']['content'];assert needle in text and county in text
 def coord(axis):
  vals={k:float(v.replace(',','.')) for k,v in re.findall(r'\|\s*'+axis+r'_(deg|min|sec)\s*=\s*([0-9.,]+)',text)};assert 'deg'in vals;return vals['deg']+vals.get('min',0)/60+vals.get('sec',0)/3600
 extra={}
 if name=='Рябово':
  anchors=[]
  for o,q in [(2401,12203),(2405,12205)]:
   old=D[D.source_record_id.eq('2002:045_9dc3ed048e_02c__Udmurtia.xls:Sheet1:'+str(o))].iloc[0];new=D[D.source_record_id.eq('2010:017_68e0e4537e_9._20Basq_Mari_Mord_Tatar_Udm_Chuv_2010.xls:!!!:'+str(q))].iloc[0];assert old.root==new.root;anchors.append(dict(old=old.fillna('').to_dict(),new=new.fillna('').to_dict()))
  inside=D[D.census_year.eq(2010)&D.region_norm.eq(t.region_norm)&D.source_record_id.str.contains('!!!:')&D.ord.gt(12203)&D.ord.lt(12205)];assert len(inside)==1 and inside.iloc[0].settlement_name=='Рябово' and inside.iloc[0].type_norm=='село';extra=dict(accepted_anchor_witnesses=anchors,unique_inside_counterpart=inside.fillna('').to_dict('records'),known_wrong_rawGeo_rejected=True)
 if name=='Мурадымово':
  rivals=D[D.census_year.eq(2002)&D.region_norm.eq(t.region_norm)&D.county.eq('аургазинский')&D.settlement_name.str.contains('Мурад',case=False)];assert len(rivals)==1 and rivals.iloc[0].source_record_id==t.source_record_id;assert '16 мая 2002' in text;extra=dict(whole2002_native_postmerger_leaf=rivals.fillna('').to_dict('records'),formation_before_census=True,ordinary_constituent_same_place_edge_added=False)
 lat,lon=coord('lat'),coord('lon');idx=len(W);W.append(dict(target_source_record_id=t.source_record_id,native_name=name,native_type=t.settlement_type,native_county=t.district_raw,population_preserved=t.population,raw_article_page=page,additional_ownplace_witness=extra,source_file=str(F),source_sha256=sha(F),rule=rule,explicit_retrospective_point_inference=True,historical_censusday_accuracy_unknown=True))
 P.append(dict(target_source_record_id=t.source_record_id,latitude=lat,longitude=lon,coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_source_record_id=f'wikipedia:ru:pageid={page["pageid"]}',point_origin_file=str(F),point_origin_sha256=sha(F),point_origin_locator=f'payload.query.pages[{pi}].revisions[0].slots.main.content;lat_deg/min/sec,lon_deg/min/sec',point_origin_kind='direct_own_article_infobox_point_explicit_native_name_alias',coordinate_binding_rule=rule,point_use_inference='Explicit retrospective own-locality representative point inference; exact censusday coordinate and population boundaries unknown.',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,external_provider_ID_binding_asserted=True,evidence_file=str(O/'point_binding_witnesses.json.gz'),evidence_locator=f'[{idx}]'))
 f=Path('/workspace/settlements-raw')/d.source_file;b=xlrd.open_workbook(str(f));sh=b.sheet_by_name(t.source_record_id.rsplit(':',2)[1]);row=int(t.source_record_id.rsplit(':',1)[1])-1;raw.append(dict(source_record_id=t.source_record_id,source_file=str(f),sha256=sha(f),raw_row0=row,raw_cells=sh.row_values(row)))
pd.DataFrame(P).to_csv(O/'accepted_point_use_delta.csv',index=False);pd.DataFrame(columns=['from_source_record_id','to_source_record_id','relation','decision_status','admission_method','admission_rule','evidence_file','evidence_locator']).to_csv(O/'accepted_identity_edge_delta.csv',index=False);pd.DataFrame([dict(source_record_id=p['target_source_record_id'],disposition='accepted_independently_bound_own_article_point',ordinary_identity_edges_added=False,missing_year_population_assigned=False)for p in P]).to_csv(O/'record_dispositions.csv',index=False)
for n,v in [('point_binding_witnesses.json.gz',W),('native_source_row_witnesses.json.gz',raw)]:
 with gzip.open(O/n,'wt')as f:json.dump(v,f,ensure_ascii=False)
m=dict(baseline_stage=71,accepted_own_point_uses=len(P),identity_edges_added=0,population_values_modified=False,validation=dict(actual_cached_revision_reopened=True,native_raw_rows_reopened=True,county_and_explicit_own_alias_bound=True),frozen_files=[dict(name=f.name,sha256=sha(f),bytes=f.stat().st_size)for f in sorted(O.iterdir())if f.is_file()]);(O/'freeze_manifest.json').write_text(json.dumps(m,ensure_ascii=False,indent=2));print(len(P))
