from pathlib import Path
import pandas as pd,xlrd,gzip,json,hashlib,math
R=Path('/workspace/russian-settlements-research');O=Path(__file__).parent;P=R/'research_rebuild/evidence/over500_moscow_20261009';B=R/'publication/stage71';pins={}
def sha(f):
 f=Path(f);v=hashlib.sha256(f.read_bytes()).hexdigest();pins[str(f)]=v;return v
ids=['2002:010_3e630cc803_02c_Moskovskaya-oblast.xls:Sheet1:2477','2010:010_711691e352_2._20Kostrom_Kur_Lip_Moscow_MoscObl_Orlov_2010.xls:Data Sheet:10257','2021:data_allsettlements_anon_156_v20251217.parquet:parquet:67448'];sha(B/'applied_state_observations.parquet');d=pd.read_parquet(B/'applied_state_observations.parquet');native=d[d.source_record_id.isin(ids)].copy();assert len(native)==3;assert native[native.census_year.isin([2010,2021])].root.nunique()==1
sha(B/'applied_point_snapshot.parquet');pt=pd.read_parquet(B/'applied_point_snapshot.parquet');old=pt[pt.target_source_record_id.isin(ids)].copy();assert len(old)==2;assert set(zip(old.latitude.astype(float),old.longitude.astype(float)))=={(55.1081449,38.8673108)}
f=P/'own_wikipedia_batch1.json.gz';sha(f);q=next(x for x in json.load(gzip.open(f,'rt'))['query']['pages'].values() if x.get('pageid')==551956);txt=q['revisions'][0]['slots']['main']['*'];co=q['coordinates'][0];assert q['revisions'][0]['revid']==147489198 and (co['lat'],co['lon'])==(55.17028,38.65);assert all(x in txt for x in ['46222819020','Непецинскому сельскому поселению','Коломенского района','8 км к северо-западу'])
f=Path('/workspace/settlements-raw/data/raw/historical_classifiers/okato_142_2009/dump-142_2009.sql');sha(f);lines=f.read_text().splitlines();line=lines[97709];assert '46222819020' in line and 'п Возрождение' in line;parent=next(x for x in lines if x.startswith('46222819') and 'Непецинский' in x);assert 'Непецинский' in parent
f=Path('/workspace/settlements-raw/data/raw/2002/010_3e630cc803_02c_Moskovskaya-oblast.xls');sha(f);s=xlrd.open_workbook(f).sheet_by_name('Sheet1');assert 'Отделения "Возрождение"' in s.cell_value(2476,1) and float(s.cell_value(2476,2))==599;assert 'Непецинский' in s.cell_value(2448,1) and 'Коломенский район' in s.cell_value(2365,1)
f=Path('/workspace/settlements-raw/data/raw/2010/010_711691e352_2._20Kostrom_Kur_Lip_Moscow_MoscObl_Orlov_2010.xls');sha(f);s10=xlrd.open_workbook(f).sheet_by_name('Data Sheet');assert s10.cell_value(10256,3)=='посёлок Возрождение' and float(s10.cell_value(10256,4))==574
f=Path('/workspace/settlements-raw/data/interim/2021_tochno/data_allsettlements_anon_156_v20251217.parquet');sha(f);raw=pd.read_parquet(f,columns=['object_name','object_level','population','oktmo','region','mun_upper','mun_lower','latitude_dadata','longitude_dadata']);rv=raw.iloc[67447].to_dict();assert 'Возрождение' in rv['object_name'] and rv['population']==434 and str(rv['oktmo'])=='46738000206' and 'Коломна' in rv['mun_upper']
f=R/'research_rebuild/evidence/over1000_moscow_20261009/native_all_with_independent_county.csv.gz';sha(f);county=pd.read_csv(f);assert county.set_index('source_record_id').loc[ids[1],'derived_oldcounty']=='Коломенский район'
rivals=d[d.region_norm.eq('московская')&d.name_norm.eq('возрождение')][['source_record_id','census_year','settlement_name','settlement_type','district_raw','oktmo','okato','root']];rivals.to_csv(O/'native_namesake_inventory.csv',index=False)
x1,y1,x2,y2=map(math.radians,[55.1081449,38.8673108,55.17028,38.65]);km=6371.0088*2*math.asin(math.sqrt(math.sin((x2-x1)/2)**2+math.cos(x1)*math.cos(x2)*math.sin((y2-y1)/2)**2))
for f in [P/'accepted_point_rejection_delta.csv',P/'accepted_point_use_delta.csv',P/'Vozrozhdenie_coordinate_correction_sourceproof.json']:sha(f)
rejs=pd.read_csv(P/'accepted_point_rejection_delta.csv');assert set(rejs.target_source_record_id)==set(ids[1:]);
for z in rejs.to_dict('records'):assert sha(z['origin_ledger'])==z['origin_ledger_sha256']
receipt={'decision_status':'checked_rule_accepted','review_scope':'Vozrozhdenie representative coordinate correction only; no entire batch review','correction_supported':True,'rejected_existing_point_UIDs':ids[1:],'old_point':[55.1081449,38.8673108],'replacement_own_article_point':[55.17028,38.65],'old_to_replacement_km':km,'replacement_is_direct_own_article_coordinate_claim':True,'provider_identifier_binding_asserted':False,'2010_2021_identity_already_accepted_stage71':True,'raw2021_record':rv,'historical_2009_OKATO_literal':line,'historical_classifier_parent_literal':parent,'own_article_pageid':551956,'own_article_revision':147489198,'own_article_title':q['title'],'raw2002_context':{'Sheet1!B2366':s.cell_value(2365,1),'Sheet1!B2449':s.cell_value(2448,1),'Sheet1!B2477':s.cell_value(2476,1),'Sheet1!C2477':s.cell_value(2476,2)},'raw2010_context':{'Data Sheet!D10257':s10.cell_value(10256,3),'Data Sheet!E10257':s10.cell_value(10256,4)},'same_region_namesake_excluded':'Ступинский район / Городской округ Ступино деревня Возрождение has distinct accepted component, native type and native codes; not the Коломна посёлок','2002_identity_extension_review_scope':'Independent original2002 Nepetsinsky/Kolomensky context supports ownership-designator correspondence, but correction approval targets existing2010/2021 points. No prior2002 point existed to reject.','quality_and_population_unchanged':True,'exact_census_date_coordinate_asserted':False,'boundary_comparability_asserted':False,'spatial_wording_erratum':'Correction packet says old point southeast of Kolomna. The demonstrated claim is old point15.44km from own locality coordinate; do not inherit the unverified compass phrase.','state_or_packet_mutations':0}
(O/'review_receipt.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2,default=str));(O/'input_manifest.json').write_text(json.dumps(pins,indent=2));print(json.dumps({k:receipt[k] for k in ['correction_supported','old_to_replacement_km','rejected_existing_point_UIDs']},indent=2))
