exec((__import__('pathlib').Path(__file__).parent/'finalize.py').read_text().split('for g in G:')[0])
# Reuse pinned source properties; do not rerun or change the ordinary packet.
events=[];obs=[];fps=[];credits=[];contexts=[];excerpts=[]
prior=Z.parent/'working_full_chain_20261007/direct_inclusion_transformation_path_native_credit_union.csv';priorids=set(pd.read_csv(prior).source_record_id)
for label,sid,q,recipient,rcur in [('Красноярская',old('r',2002,15),'Q4239212','Волгодонск',111464),('Соленовская',old('r',2002,16),'Q4427684','Волгодонск',111464),('Алмазный','2002:1_TOM_01_04.xls:0:4952','Q4062718','Гуково',111466)]:
 scope='south69_included_'+label;f,page=pages[q];text=page['revisions'][0]['slots']['main']['content'];lines=[l for l in text.splitlines() if ('2004' in l and any(w in l.lower() for w in ['включ','состав','статус']))];assert lines
 v=vals(q,'P625')[0];lat,lon=v['latitude'],v['longitude'];receiver=cur(rcur);mm=o[o.root.eq(o.loc[receiver,'root'])];assert len(mm)==3 and set(mm.census_year)=={2002,2010,2021};assert all(i in p.index for i in mm.index);assert sid not in priorids
 pointlocator=f'entities.{q}.claims.P625';ef=str(ep[q]);eventlocator=f"page{page['pageid']}:revision{page['revisions'][0]['revid']}";excerpts.append(dict(scope_id=scope,event_source_file=str(f),event_source_sha256=sha(f),event_source_locator=eventlocator,own_literal_dated_event_excerpt='\n'.join(lines),own_article_title=page['title'],own_physical_point_properties_json=json.dumps({k:es[q].get('claims',{}).get(k,[]) for k in ['P31','P131','P625']},ensure_ascii=False)))
 events.append(dict(scope_id=scope,former_locality=label,recipient_city=recipient,event_date=2004,date_precision='year',relation='included_in',same_place=False,event_source_file=str(f),event_source_sha256=sha(f),event_source_locator=eventlocator,event_source_quality='secondary_own_Wikipedia_literal_dated_inclusion',event_date_role='literal own NP inclusion year; primary law not opened',decision_status='accepted_secondary_own_article_included_in',primary_law_source_reopened=False,boundary_comparability='UNKNOWN',roster_closed=False,sum_city_equals_children_asserted=False))
 x=o.loc[sid];obs.append(dict(scope_id=scope,place=label,year=2002,source_record_id=sid,native_population=x.population,native_population_quality=x.population_value_quality,latitude=lat,longitude=lon,own_point=True,recipient_city=recipient,event_date=2004,event_date_precision='year',event_relation='included_in',same_place_identity_asserted=False,receiving_city_2021_source_record_id=receiver,receiving_city_2021_count_context_only=o.loc[receiver,'population'],child_2021_population_assigned=False,is_additive_to_original_final_mixed_census_axis=False,already_in_baseline68_primary_native_ID_union=False,new_native_population_if_event_admitted=x.population,whole_city_roster_closure_asserted=False,population_boundary_comparability_asserted=False,native_values_quality_preserved=True))
 fps.append(dict(scope_id=scope,target_source_record_id=sid,source_record_id=sid,latitude=lat,longitude=lon,coordinate_admission_status='reviewed_extension_rule_accepted',decision_status='reviewed_rule_accepted',coordinate_source_record_id=q,source_sha256=sha(ef),source_locator=pointlocator,point_origin_file=ef,point_origin_sha256=sha(ef),point_origin_locator=pointlocator,point_origin_kind='own_named_former_NP_Wikidata_physical_reference_point',own_locality_point=True,recipient_point_assigned_to_child=False,new_ordinary_point_use_proposed=False,point_temporal_interpretation='Modern own former physical NP representative point retrospectively used for native2002; not censusday measurement',direct_historical_coordinate_measurement=False,provider_binding_asserted=False,boundary_comparability_asserted=False))
 credits.append(dict(scope_id=scope,source_record_id=sid,year=2002,source_population=x.population,new_population_on_separate_transformation_path_axis=x.population,own_historical_point_verified=True,receiving_city_actual_2002_2010_2021_context_verified=True,is_additive_to_original_final_mixed_census_axis=False,ordinary_three_census_same_place_claim=False))
 for i,y in mm.iterrows():contexts.append(dict(scope_id=scope,recipient_city=recipient,source_record_id=i,census_year=y.census_year,native_population_context_only=y.population,point_claim_json=json.dumps(p.loc[i].to_dict(),ensure_ascii=False),own_component_root=y.root))
for name,rows in [('accepted_inclusion_events.csv',events),('accepted_historical_observations.csv',obs),('accepted_former_locality_own_points.csv',fps),('accepted_direct_event_native_credit_union.csv',credits),('literal_own_inclusion_source_excerpts.csv',excerpts),('receiver_actual68_native_context.csv',contexts)]:pd.DataFrame(rows).to_csv(Z/name,index=False)
d=pd.read_csv(Z/'all58_UID_disposition.csv');d.loc[d.source_record_id.isin([x['source_record_id'] for x in obs]),'disposition']='accepted_separate_included_in_path';d.loc[d.source_record_id.isin([x['source_record_id'] for x in obs]),'hold_reason']='';
reason={'Казачьи Лагери':'Accepted native2010/21 component already own-pointed; actual native2002 own source observation unresolved. No invented formation date/zero.', 'Темерницкий':'Accepted2010/21 own-pointed; actual native2002 observation unresolved. Separate actual-year observations preserved, no NF3 claim.','Нижнетемерницкий':'Accepted2010/21 own-pointed; actual native2002 observation unresolved, no zero/formation assumption.','Первомайский':'Printed Zverevo subordinate NP2002; missing dated cessation/absorption and own former physical point. City point cannot be assigned to child.','Николаевский':'Printed Proletarsky Nikolaevsky selsovet NP; missing explicit dated transition/own modern identity. No municipality/stanitsa substitution.','Садовый':'Two actual Krymsky proper hutor rivals acrossall years; identical Geo2011 points do not distinguish source parish. No first-match/nearest choice.','Железнодорожный':'Own article says includedMechetinskaya2004 but literal coordinate ~150km inconsistent with named county. Q has no ownP625; receiver point cannot stand for former hutor.'}
for i,x in d[d.disposition.str.startswith('HOLD')].iterrows():d.loc[i,'hold_reason']=reason.get(x.settlement_name,'Unresolved exact source path; no fabricated missing observation.')
d.to_csv(Z/'all58_UID_disposition.csv',index=False)
# New Duchi available-year formation stays separate from old northern locality and strictNF3.
pd.DataFrame([dict(scope_id='south69_new_Duchi2013',relation='new_locality_formation_and_population_resettlement',formation_year=2013,formation_day='UNKNOWN',source_record_id=badnew,census_year=2021,observed_population=926,old_2002_population='UNKNOWN_NOT_THIS_ENTITY',old_2010_population='UNKNOWN_NOT_THIS_ENTITY',own_modern_point=True,point_source=str(ep['Q4171378']),point_source_sha256=sha(ep['Q4171378']),strict_NP3_credit=False,source_population_unchanged=True,event_source=str(pages['Q4171378'][0]),event_source_sha256=sha(pages['Q4171378'][0]),boundary_comparability='UNKNOWN')]).to_csv(Z/'new_Duchi_actual_available_year_event.csv',index=False)
r=json.loads((Z/'application_receipt.json').read_text());r.update(dispositions=d.disposition.value_counts().to_dict(),included_in_events=3,separate_DIRECT_increment_native2002_population=sum(x['source_population'] for x in credits),separate_DIRECT_increment_native2010_population=0,direct_prior_union_pin={'path':str(prior),'sha256':sha(prior)},direct_context_only_no_receiving_counts_assigned=True);(Z/'application_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2))
# Final bounded independent checks: endpoints unique, own-point pin bytes, exact rejection ledger, raw source values not changed.
e=pd.read_csv(Z/'accepted_identity_edge_delta.csv.gz');pp=pd.read_csv(Z/'accepted_point_use_delta.csv.gz');assert not pp.target_source_record_id.duplicated().any();assert set(e.from_source_record_id)|set(e.to_source_record_id)<=set(o.index);assert len(d)==58 and d.source_record_id.nunique()==58
for f in pp.point_origin_file.dropna().unique():
 rr=pp[pp.point_origin_file.eq(f)];assert Path(f).exists();assert set(rr.point_origin_sha256.dropna())=={sha(f)},(f,'source point pin mismatch')
check={'packet_status':'FROZEN_PENDING_ROOT_INDEPENDENT_REVIEW','all58_UIDs_disposed':True,'accepted_point_targets_unique':True,'new_edges_endpoint_native_presence':True,'source_point_origin_pins_checked':True,'all_native_counts_quality_unchanged':True,'explicit_wrong_edge_rejection_preserves_frozen_ledger':True,'specific_Duchi_component_has2nodes':True,'old_Duchi_northern_point_retained':True,'other_hard_geometry_holds':0,'known_wrong_PROVIDER_bindings_not_used_as_ownproof':['HostinskyBaranovka Dadata binds Lazarev rival','Utash Dadata city centroid','newDuchi Dadata binds oldZoriotar'],'remaining_held_UIDs':d[d.disposition.str.startswith('HOLD')][['source_record_id','settlement_name','population','hold_reason']].to_dict('records')};(Z/'verification_receipt.json').write_text(json.dumps(check,ensure_ascii=False,indent=2))
files={str(f.relative_to(Z)):{'sha256':sha(f),'bytes':f.stat().st_size} for f in sorted(Z.iterdir()) if f.is_file() and f.name!='manifest.json'};(Z/'manifest.json').write_text(json.dumps({'files':files,'status':'FROZEN','source_values_mutated':False},ensure_ascii=False,indent=2));print('FROZEN',sha(Z/'manifest.json'),'edges',len(e),'pointuses',len(pp),'dispositions',d.disposition.value_counts().to_dict(),'DIRECT02',sum(x['source_population'] for x in credits),'bytes',sum(x['bytes'] for x in files.values()))
