import sys,json,gzip,copy,math,importlib.util
from pathlib import Path
import pandas as pd
R=Path('/workspace/russian-settlements-research');O=Path(__file__).parent;P=O.parent/'whole_region_type_unique_followup';B=O.parent/'existing_ownpoint_native02_mass';sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from current_chain_state_20261007 import sha
r7=json.loads((P/'application_receipt.json').read_text());f=pd.read_csv(P/'whole_region_exact_type_native02_candidates.csv.gz',dtype=str,keep_default_na=False);z=f[f.name.eq('Арамиль')].iloc[0].to_dict();dp=json.loads(z['current_own_point_json']);ep=Path(dp['point_origin_file']);assert sha(ep)==dp['point_origin_sha256']
with gzip.open(ep,'rt') as h:e=json.load(h)['entities']['Q15266326']
codes=[str(v.get('mainsnak',{}).get('datavalue',{}).get('value','')) for v in e['claims'].get('P764',[]) if v.get('rank')!='deprecated'];assert z['current_oktmo']=='65729000106' and z['current_oktmo'] in codes
coords=[v.get('mainsnak',{}).get('datavalue',{}).get('value',{}) for v in e['claims'].get('P625',[]) if v.get('rank')!='deprecated'];assert any(p.get('latitude')==float(dp['latitude']) and p.get('longitude')==float(dp['longitude']) for p in coords)
assert e['sitelinks']['ruwiki']['title']=='Арамиль (посёлок)'
rule='Exact literal name plus unchanged printed поселок NP class unique across all selected NPs in each whole region/year; all OTHER-class city rivals retained. Current2010/2021 own NP point independently admitted under Q15266326, own article Арамиль(посёлок), exact own/native OKTMO65729000106 and actual P625. Distinct city has ownOKTMO65729000001/Q103694 and is7.27km away. Shared raw publisher OKATO65241503000 is explicitly ambiguous/wrong for поселок and remains unchanged; independently positive physical NP identity and ownOKTMO binding permit retrospective continuity. Protected original2002ownNP count/name/quality unchanged.'
edge={'from_source_record_id':z['old_source_record_id'],'to_source_record_id':z['current_source_record_id'],'relation':'same_place','decision_status':'checked_rule_accepted','case':'Арамиль_поселок_native2002','admission_rule':rule,'source_binding_proof':'accepted_source_binding.csv.gz;all_name_class_competitors.csv.gz;original_native02_leaf.csv.gz;actual_own_entity_binding.json','population_boundary_comparability_asserted':False,'municipal_event_date':'UNKNOWN'}
pd.DataFrame([edge]).to_csv(O/'accepted_identity_edge_delta.csv',index=False)
dp={k:v for k,v in dp.items() if k!='point_ledger_path'};dp.update(target_source_record_id=z['old_source_record_id'],coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_binding_rule=rule,historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,point_use_inference='modern_own_representative_point_on_source_bound_native2002_identity',publisher_current_OKATO_binding_quality='ambiguous_wrong_city_OKATO_in_raw_publisher; retained unchanged',independently_bound_current_OKTMO='65729000106',independently_bound_own_QID='Q15266326')
pd.DataFrame([dp]).to_csv(O/'accepted_point_use_delta.csv',index=False);pd.DataFrame([z]).to_csv(O/'accepted_source_binding.csv.gz',index=False,compression='gzip')
for source,target,col,key in [('all_native_literal_region_name_competitors.csv.gz','all_name_class_competitors.csv.gz','target_current_source_record_id',z['current_source_record_id']),('verified_original_native02_leaf_rows.csv.gz','original_native02_leaf.csv.gz','source_record_id',z['old_source_record_id'])]:
 d=pd.read_csv(P/source,dtype=str,keep_default_na=False);d[d[col].eq(key)].to_csv(O/target,index=False,compression='gzip')
(O/'actual_own_entity_binding.json').write_text(json.dumps({'source_file':str(ep),'source_sha256':sha(ep),'qid':'Q15266326','independent_prior_point_admission_ledger':json.loads(z['current_own_point_json'])['point_ledger_path'],'own_current_native_OKTMO':z['current_oktmo'],'actual_P764_values':codes,'actual_P625_claims':coords,'own_ru_label':e['labels']['ru'],'own_ru_description':e['descriptions']['ru'],'own_article':e['sitelinks']['ruwiki'],'raw_publisher_OKATO':z['current_okato'],'provider_OKATO_quality':'shared city code is wrong/ambiguous for поселок; not asserted bound','independent_provider_ID_binding':'own/native currentOKTMO and ownQID are exact positively bound','physical_point_quality':'independently admitted own поселок point; distinct from city'},ensure_ascii=False,indent=2))
oldraw=pd.read_csv(O/'original_native02_leaf.csv.gz',dtype=str,keep_default_na=False).iloc[0];pins={str(ep):sha(ep),oldraw.source_path:oldraw.source_sha256,str(P/'application_receipt.json'):sha(P/'application_receipt.json'),str(P/'accepted_identity_edge_delta.csv'):sha(P/'accepted_identity_edge_delta.csv'),str(P/'accepted_point_use_delta.csv'):sha(P/'accepted_point_use_delta.csv')}
before=copy.deepcopy(r7['after']);after=copy.deepcopy(before);pop={'2002':989,'2010':1983,'2021':1860}
for y,v in pop.items():
 m=after[y];m['covered_population']+=v;m['covered_rows']+=1;m['residual_rows']-=1;m['coverage_percent']=100*m['covered_population']/m['denominator_selected_ordinary_population'];m['gap_to_99_percent']=max(0,math.ceil(.99*m['denominator_selected_ordinary_population'])-m['covered_population'])
bf=r7['after_finite_all3_all_points'];af={'histories':bf['histories']+1,'populations_by_year':{y:bf['populations_by_year'][y]+v for y,v in pop.items()}}
names=['accepted_identity_edge_delta.csv','accepted_point_use_delta.csv','accepted_source_binding.csv.gz','all_name_class_competitors.csv.gz','original_native02_leaf.csv.gz','actual_own_entity_binding.json']
r={'baseline_kind':'actual39_plus_frozen_NEW3_plus_frozen_typed7_explicit_composition','baseline_stage':39,'baseline_additional_applications':[str(B/'application_receipt.json'),str(P/'application_receipt.json')],'status':'Source-positive frozen CSV prepared; root actual43 StateAPI composition/replay pending','metric_provenance':'Expected marginal metrics derived exactly from frozen typed7 actual composed replay and protected989/1983/1860 NP counts; no claim of actual43 replay in this receipt','accepted_cases':1,'edges':1,'point_uses':1,'before':before,'after':after,'before_finite_all3_all_points':bf,'after_finite_all3_all_points':af,'net_finite_all3_all_points':{'histories':1,'populations_by_year':pop},'input_pins':pins,'output_pins':{n:sha(O/n) for n in names},'native_populations_quality_source_spelling_unchanged':True,'historical_census_coordinate_asserted':False,'provider_raw_wrong_OKATO_quality_explicitly_separate_from_physical_identity':True}
(O/'application_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2))
code=(P/'apply.py').read_text();start=code.index("if __name__ == '__main__':");code=code[:start]+"if __name__ == '__main__':\n    from working_state_20261007 import load\n    state=load(39)\n    for path in [O.parent/'existing_ownpoint_native02_mass/apply.py',O.parent/'whole_region_type_unique_followup/apply.py']:\n        spec=importlib.util.spec_from_file_location('prior_frozen',path)\n        module=importlib.util.module_from_spec(spec);spec.loader.exec_module(module);module.apply(state)\n    apply(state)\n    print('Explicit composed baseline source/output pins and exact StateAPI replay passed')\n";(O/'apply.py').write_text(code)
print(json.dumps({'edges':1,'points':1,'baseline':'explicit39+NEW3+typed7','expected_before_finite':bf,'expected_after_finite':af,'net':r['net_finite_all3_all_points'],'receipt_sha256':sha(O/'application_receipt.json')},ensure_ascii=False))
