"""Bounded source roster inventory; refuses partial Voronezh event scope credits."""
import sys,json,re,gzip
from pathlib import Path
import pandas as pd,duckdb,xlrd
ROOT=Path('/workspace/russian-settlements-research');sys.path.insert(0,str(ROOT/'research_rebuild/mass_linkage'))
from current_chain_state_20261007 import sha,normalize
from working_state_20261007 import load
O=Path(__file__).parent;SELECTED=Path('/workspace/settlements-delivery/continuation-consolidated-20261003/selected_observations.parquet')
URBAN=Path('/workspace/settlements-raw/data/raw/2002_official_tom1/1_TOM_01_04.xls');RURAL=Path('/workspace/settlements-raw/data/raw/2002/004_f58b08b4f6_02c_Voronezhskaja.xls');XLS2010=Path('/workspace/settlements-raw/data/raw/2010/013_f60b2d2bcf_5._20Belg_Bryan_Vlad_Voron_Ivanov_Kalug_20L1_ethn_2010.xls');CITYCACHE=Path('/workspace/settlements-raw/data/raw/wikipedia_articles/batch_00452.json.gz')
s=load(21);c=duckdb.connect();obs=c.execute("select source_record_id,census_year,settlement_name,settlement_type,region_norm,district_raw,population,is_additive_settlement_record,population_value_quality,source_file,source_sheet,source_row,source_locator from read_parquet(?) where region_norm='воронежская'",[str(SELECTED)]).fetchdf();out=[]
for asset,sheet,year,start,end in [(URBAN,'0',2002,354,374),(RURAL,'Sheet1',2002,4,71),(XLS2010,'Data Sheet',2010,8524,8552)]:
 b=xlrd.open_workbook(str(asset));sh=b.sheet_by_index(0) if sheet=='0' else b.sheet_by_name(sheet)
 for row in range(start,end+1):
  cells=sh.row_values(row-1);texts=[(i,v) for i,v in enumerate(cells) if isinstance(v,str) and v.strip()];native_label=texts[-1][1] if asset==XLS2010 else texts[0][1] if texts else '';labelindex=texts[-1][0] if asset==XLS2010 and texts else texts[0][0] if texts else 0
  num=[]
  for v in cells[labelindex+1:]:
   try:
    if str(v).strip():num.append(float(v))
   except:pass
  q=obs[(obs.census_year==year)&obs.source_file.eq(str(asset).replace('/workspace/settlements-raw/',''))&obs.source_sheet.astype(str).eq(sheet)&obs.source_row.eq(row)]
  oldnorm=normalize(native_label);native_np=bool(re.match(r'^(?:пгт|село|пос[её]лок|насел[её]нный пункт|с\.|п\.)\s',oldnorm))
  out.append({'census_year':year,'source_file':str(asset),'source_sha256':sha(asset),'source_sheet':sheet,'source_row_1based':row,'native_label':native_label,'actual_first_count':num[0] if num else None,'native_NP_label':native_np,'raw_row':' | '.join(str(v) for v in (cells[:8] if asset==XLS2010 else cells) if v!=''),'selected_source_record_ids':' | '.join(q.source_record_id),'selected_names':' | '.join(q.settlement_name),'selected_population_quality':' | '.join(q.population_value_quality.fillna('')),'selected_additive_flags':' | '.join(map(str,q.is_additive_settlement_record)),'event_roster_admitted':False})
pd.DataFrame(out).to_csv(O/'literal_native_parent_hierarchy_inventory.csv',index=False)
q=[r for r in out if r['census_year']==2010 and 8530<=r['source_row_1based']<=8551];assert len(q)==22 and all(a['native_NP_label'] for a in q);pd.DataFrame(q).to_csv(O/'observed_2010_subordinate_22_names_NOT_complete_event_roster.csv',index=False)
parents=obs[(obs.settlement_name=='Воронеж')&obs.census_year.isin([2002,2010,2021])];parents.to_csv(O/'actual_receiving_city_observations.csv',index=False);cur=parents[parents.census_year.eq(2021)].iloc[0];p=s.point_rows[cur.source_record_id];(O/'admitted_receiving_parent_point.json').write_text(json.dumps({'stage':21,'source_record_id':cur.source_record_id,'point':p,'point_ledger_sha256':sha(Path(p['point_ledger_path'])),'role':'representative_event_scope_only_not_individual_constituent_points','candidate_only':True},ensure_ascii=False,indent=2,default=str)+'\n')
receipts={'status':'WHOLE_GROUP_HOLD_COMPLETE_EVENT_ROSTER_AND_NATIVE_BINDINGS','candidate_only':True,'active_state':21,'event_witness':'Secondary receiving-city and own localities document 2011 inclusion; exact cited law title dated24December2010 and CNTD identifier469702421 recovered from own locality article.','act_number_verified':False,'act_number_asserted':None,'complete_named_24_roster_recovered':False,'direct2010_closed_native_NP_entries':22,'native2002_parent_control':928410,'native2002_city_population':848752,'native2002_all_subordinates_control_difference':79658,'native2010_22_entry_raw_sum_not_admitted':int(sum(z['actual_first_count'] for z in q)),'observations_credited':0,'event_scope_group_sums_emitted':0,'actual_net_gain':{str(y):0 for y in [2002,2010,2021]},'historical_point_transfer_to_constituents':False,'boundary_comparability':'UNKNOWN','reason':'No independent full24 legal/event roster has been recovered. Closed2010 regional block has22 names; secondary administration history also mentions28 historical localities; raw2002 hierarchy contains extra small children under urban parents. Those are different source grains, not interchangeable complete event rosters. No inferred missing zeros, partial sum or constant-boundary assertion.','official_authentication_gate_applied':False,'remaining_blocker':'complete event membership and hierarchy binding, not legal publisher authentication','inputs':{str(v):sha(v) for v in [SELECTED,URBAN,RURAL,XLS2010,CITYCACHE,Path(__file__)]},'outputs':{p.name:{'sha256':sha(p),'bytes':p.stat().st_size} for p in O.iterdir() if p.is_file() and p.name not in ['receipt.json']}}
(O/'receipt.json').write_text(json.dumps(receipts,ensure_ascii=False,indent=2)+'\n');print(json.dumps({k:receipts[k] for k in ['status','complete_named_24_roster_recovered','direct2010_closed_native_NP_entries','actual_net_gain']}))
