from pathlib import Path
import pandas as pd,json,gzip,hashlib,xlrd
O=Path(__file__).parent;D=pd.read_pickle('/dev/shm/over500-20261009/east_enriched.pkl');P=pd.read_parquet('/dev/shm/over500-20261009/points_compact.parquet').set_index('target_source_record_id');sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();rows=[];W=[];raw=[]
S=[('2002:051_46e3ecb0a0_02c_Permskaja_obl.xls:Sheet1:561','2021:data_allsettlements_anon_156_v20251217.parquet:parquet:99014',557,'г. Чусовой','Кутамыш'),('2002:041_4b428edd23_Bashkiria_new.xls:Sheet1:6003','2010:017_68e0e4537e_9._20Basq_Mari_Mord_Tatar_Udm_Chuv_2010.xls:!!!:3896',5999,'Юматовский сельсовет','Юматово')]
for sid,did,parentrow,parenttext,name in S:
 t=D[D.source_record_id.eq(sid)].iloc[0];d=D[D.source_record_id.eq(did)].iloc[0];q=P.loc[did];assert 'станци' in t.settlement_name and 'станци' in d.settlement_name;assert sha(q.point_origin_file)==q.point_origin_sha256
 f=Path('/workspace/settlements-raw')/t.source_file;b=xlrd.open_workbook(str(f));sh=b.sheet_by_name('Sheet1');rn=int(sid.rsplit(':',1)[1])-1;assert parenttext in str(sh.row_values(parentrow));assert name in str(sh.row_values(rn))
 rivals=D[D.region_norm.eq(t.region_norm)&D.settlement_name.str.contains(name,regex=False,na=False)];wid=len(W);rule='Distinct literal station-settlement ownname and native explicit parent county/council select independently accepted own station-settlement representative point. Bare same-name village and separately named sanatorium retained as different places. Station designator normalized only станция/пристанции/станции for this exactnamedplace; no infrastructure node or recipient center transfer.'
 W.append(dict(target_source_record_id=sid,accepted_point_donor=did,donor_native_observation=d.fillna('').to_dict(),donor_accepted_own_point=q.to_dict(),native_target=t.fillna('').to_dict(),all_region_same_basename_type_rivals=rivals.fillna('').to_dict('records'),rule=rule,retrospective_point_inference=True,historical_censusday_coordinate_asserted=False))
 raw.append(dict(source_record_id=sid,source_file=str(f),sha256=sha(f),raw_row0=rn,raw_cells=sh.row_values(rn),parent_row0=parentrow,parent_cells=sh.row_values(parentrow)))
 r=q.to_dict();r.update(target_source_record_id=sid,coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_binding_rule=rule,point_use_inference='Explicit retrospective own physical station-settlement representative point inference; censusday measurement and population boundaries unknown.',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,external_provider_ID_binding_asserted=True,evidence_file=str(O/'point_binding_witnesses.json.gz'),evidence_locator=f'[{wid}]');rows.append(r)
pd.DataFrame(rows).to_csv(O/'accepted_point_use_delta.csv',index=False);pd.DataFrame(columns=['from_source_record_id','to_source_record_id','relation','decision_status','admission_method','admission_rule','evidence_file','evidence_locator']).to_csv(O/'accepted_identity_edge_delta.csv',index=False);pd.DataFrame([dict(source_record_id=r['target_source_record_id'],disposition='accepted_literal_own_station_settlement_point',ordinary_identity_edges_added=False,missing_year_population_assigned=False)for r in rows]).to_csv(O/'record_dispositions.csv',index=False)
for n,v in [('point_binding_witnesses.json.gz',W),('native_source_row_witnesses.json.gz',raw)]:
 with gzip.open(O/n,'wt')as f:json.dump(v,f,ensure_ascii=False)
m=dict(baseline_stage=71,accepted_own_point_uses=len(rows),identity_edges_added=0,population_values_modified=False,validation=dict(native_raw_rows_and_parent_headings_reopened=True,accepted_donor_origin_hash_checked=True,literal_distinct_station_settlement_role_checked=True),frozen_files=[dict(name=f.name,sha256=sha(f),bytes=f.stat().st_size)for f in sorted(O.iterdir())if f.is_file()]);(O/'freeze_manifest.json').write_text(json.dumps(m,ensure_ascii=False,indent=2));print(len(rows))
