from pathlib import Path
import pandas as pd,json,re,duckdb,xlrd,struct,hashlib,sys
sys.path.insert(0,"/workspace/russian-settlements-research/research_rebuild/mass_linkage")
from current_chain_state_20261007 import distance_km
O=Path(__file__).parent;d=pd.read_csv(O/'exact_context_code_candidates.csv',dtype={'historical_exact_own_code':str});c=duckdb.connect();rows=[];books={};publisher='/workspace/settlements-raw/data/interim/2021_tochno/data_allsettlements_anon_156_v20251217.parquet'
for z in d.to_dict('records'):
 sid=z['from_source_record_id'];_,file,sheet,rn=sid.split(':');rn=int(rn);path=Path('/workspace/settlements-raw')/z['old_source_file'];b=books.setdefault(str(path),xlrd.open_workbook(str(path)));sh=b.sheet_by_name(sheet) if sheet in b.sheet_names() else b.sheet_by_index(int(sheet));vals=sh.row_values(rn-1);li=next(j for j,v in enumerate(vals) if z['name'].lower().replace('ё','е') in str(v).lower().replace('ё','е'));label=str(vals[li]);nums=[float(str(v).replace(' ','')) for v in vals[li+1:] if re.fullmatch(r'[0-9]+(?:\.[0-9]+)?',str(v).replace(' ',''))];assert nums and nums[0]==z['population_2002'],(sid,vals);assert z['name'].lower().replace('ё','е') in label.lower().replace('ё','е'),(sid,label);context=[]
 for j in range(max(0,rn-150),rn-1):
  v=sh.row_values(j);t=' '.join(str(x) for x in v[:3]);
  if re.search('район|сельсовет|округ|администрац',t,re.I):context.append({'row_1based':j+1,'label':t})
 rn21=int(z['to_source_record_id'].rsplit(':',1)[1]);raw=c.execute('with r as(select row_number()over() rn,* from read_parquet(?)) select object_name,settlement,mun_upper,mun_lower,settlement_dadata,settlement_type_full_dadata,okato_dadata,latitude_dadata,longitude_dadata,fias_level_dadata,population from r where rn=?',[publisher,rn21]).fetchone();point=json.loads(z['own_point_donor_json']);pointmatch=(float(raw[7]),float(raw[8]))==(point['latitude'],point['longitude']);ownlabel=str(raw[4]).lower().replace('ё','е')==z['name'].lower().replace('ё','е');rawcode=str(raw[6]);rawcode=rawcode[:-2] if rawcode.endswith('.0') else rawcode;assert rawcode==z['historical_exact_own_code'];assert ownlabel,(z["name"],raw);modern_distance=distance_km((float(raw[7]),float(raw[8])),(point["latitude"],point["longitude"]))
 rows.append({'from_source_record_id':sid,'to_source_record_id':z['to_source_record_id'],'name':z['name'],'actual_2002_label':label,'actual_2002_first_population':nums[0],'actual_2002_raw_row_json':json.dumps(vals,ensure_ascii=False),'actual_2002_recent_geographic_headers_json':json.dumps(context[-4:],ensure_ascii=False),'actual_current_object_name':raw[0],'actual_current_settlement_label':raw[1],'actual_current_county':raw[2],'actual_current_submunicipality':raw[3],'actual_provider_own_label':raw[4],'actual_provider_own_type':raw[5],'actual_provider_own_okato':rawcode,'provider_fias_level':raw[9],'actual_current_population':raw[10],'exact_original_provider_point_match':pointmatch,'independent_provider_point_to_active_km':modern_distance,'independent_provider_point_within5km':modern_distance<=5,'exact_own_label_code_match':True,'original_census_population_pass':True,'railway_settlement_own_np_witness':bool(re.search('н.п.|насел',str(raw[0]),re.I))})
pd.DataFrame(rows).to_csv(O/'actual_source_row_witnesses.csv',index=False);print(pd.DataFrame(rows)[['name','actual_2002_label','actual_current_object_name','actual_provider_own_type','provider_fias_level','railway_settlement_own_np_witness']].to_string(index=False))
