import sys,json
from pathlib import Path
import pandas as pd,duckdb
R=Path('/workspace/russian-settlements-research');sys.path.insert(0,str(R/'research_rebuild/mass_linkage'));from working_state_20261007 import load
from current_chain_state_20261007 import normalize
from apply_unique_county_name_bridge_20261007 import county_key
O=Path(__file__).parent;s=load(24);d=s.obs[s.obs.census_year.isin([2002,2010]) & ~s.obs.region_norm.isin(["москва","санкт петербург","севастополь","крым"])].copy();d['haspoint']=d.source_record_id.isin(s.point_rows);d['full3']=d.source_record_id.map(lambda x:s.years[s.uf.find(x)]=={2002,2010,2021});d=d[~d.haspoint&~d.full3&d.is_additive_settlement_record.fillna(False)];d['county_key']=d.district_raw.map(county_key)
summ=d.groupby(['census_year','region_norm','source_file'],dropna=False).agg(rows=('source_record_id','size'),population=('population','sum'),missing_county=('county_key',lambda x:sum(x.str.len()<3))).reset_index().sort_values('population',ascending=False);summ.to_csv(O/'residual_source_families.csv',index=False);d.nlargest(200,'population').to_csv(O/'top200_unpointed_missing_full3.csv',index=False)
c=duckdb.connect();h=c.execute('select source_record_id,historical_okato_2009_raw,historical_okato_2011_raw,name_raw_2009,name_raw_2011,latitude_from_lat,longitude_from_long,historical_name_exact,historical_type_exact,historical_named_point_candidate,possible_unlocated_historical_competitor,source_region_name_type_count,historical_key_region_name_type_count from read_parquet(?) where source_record_id in (select unnest(?))',['/workspace/settlements-work/coordinates/historical_named_candidates_v4/historical_named_point_candidates.parquet',d.source_record_id.tolist()]).fetchdf();j=d.merge(h,on='source_record_id',how='left');summary=j.groupby(['census_year','historical_name_exact','historical_type_exact','historical_named_point_candidate'],dropna=False).agg(rows=('source_record_id','size'),population=('population','sum')).reset_index();summary.to_csv(O/'historical_existing_candidate_axes.csv',index=False);print(summ.head(24).to_string(index=False));print(summary.to_string(index=False));j[j.historical_name_exact.fillna(False)].nlargest(120,'population').to_csv(O/'top120_existing_exact_raw_candidates.csv',index=False)
# Same native literal-name and geographic county candidates, without requiring type equality.
o=s.obs[s.obs.is_additive_settlement_record.fillna(False)].copy();o['n']=o.name_norm.map(normalize);o['r']=o.region_norm.map(normalize);o['d']=o.district_raw.map(county_key);o['pointed']=o.source_record_id.isin(s.point_rows)
a=d.copy();a['n']=a.name_norm.map(normalize);a['r']=a.region_norm.map(normalize);a['d']=a.county_key
pairs=a[a.d.str.len()>=3].merge(o[o.census_year.eq(2021)&o.d.str.len().ge(3)],on=['n','r','d'],suffixes=('_old','_current'));pairs=pairs[pairs.source_record_id_old.map(s.uf.find)!=pairs.source_record_id_current.map(s.uf.find)];pairs['compatible_years']=[not(s.years[s.uf.find(x)]&s.years[s.uf.find(y)]) for x,y in pairs[['source_record_id_old','source_record_id_current']].itertuples(index=False,name=None)];print('literal name county residual pairs',len(pairs),'pointed current',sum(pairs.pointed),'compatible year',sum(pairs.compatible_years));pairs.nlargest(200,'population_old').to_csv(O/'top200_exact_native_county_residual_pairs.csv',index=False)
