import pandas as pd,pathlib,json,gzip,hashlib,xlrd
P=pathlib.Path('/workspace/russian-settlements-research/research_rebuild/evidence/over500_south_final_points_20261009');R=pd.read_csv('/dev/shm/over500-20261009/south_remaining.csv');S='/dev/shm/settlements-stage71-20261009/applied_point_snapshot.parquet';A=pd.read_parquet(S);OBS=pd.read_parquet('/dev/shm/settlements-stage71-20261009/applied_state_observations.parquet');N=pd.read_parquet('/dev/shm/over500-20261009/south_native_current.parquet').reset_index();Z=OBS[OBS.census_year==2021].merge(N,on='source_record_id',suffixes=('','_native'));W=pd.read_csv('research_rebuild/evidence/over500_south_remaining_points_20261009/native_source_witnesses.csv.gz');rawctx=json.load(open('/dev/shm/over500-20261009/south_remaining_roster_context.json'));out=[];contexts=[];inv=[];cache={}
def h(f):
 if f not in cache:cache[f]=hashlib.sha256(pathlib.Path(f).read_bytes()).hexdigest()
 return cache[f]
cases=[('2010:002_027be52979_10._20СевКаз_ФО_20(без_20Даг)_202010.xls:СК:110',127273,'Explicit rawcountyBudyonno contradicts contiguous own locality roster Александрийская108,имКирова109,Балковский111,Роговой112,Краснокумское114; all unique nativeGeorgievsky. OwnnativeGeorgievskyТерский selected, separateBudyonnoТерский raw2010row102 retained.'),('2010:010_711691e352_2._20Kostrom_Kur_Lip_Moscow_MoscObl_Orlov_2010.xls:Data Sheet:7430',59912,'Native sourceТроицкое7430,Вишенки7431,Головинщино7432 formTroitsky council end roster; precedingTopovsky andnextБольшаяКузьминка startsLipetsky. OwnТроицкийcouncil target distinctsame-nameLipetskyЛенинский.'),('2010:010_711691e352_2._20Kostrom_Kur_Lip_Moscow_MoscObl_Orlov_2010.xls:Data Sheet:7640',60166,'Native target startsBerezovsky/Terbunsky roster: Воейково7641,Ивановка7642,Киреевка7643,Олымовка7644,Становляновка7645. SeparateStanovlyanskyОстровский namesake excluded.'),('2010:011_040325482b_3._20Ryaz_Smol_Tambov_Tula_Jaroslavl_20L1_20ethn_2010.xls:Data Sheet:9074',129144,'OwnЛысогорский rosterЛысыеГоры9073+Козьмодемьяновка9074; separateMalinovsky roster beginsМалиновка9075,Голдымское9076/9077. SamecountyБеломестнокриушинский namesake excluded.'),('2010:013_f60b2d2bcf_5._20Belg_Bryan_Vlad_Voron_Ivanov_Kalug_20L1_ethn_2010.xls:Data Sheet:8384',15927,'Target startsTernovsky municipal roster afterTalovskyШанинское lastУчасток37; followsАлешки,КрасныеВыселки,Никитская,Братки,Есипово. Native targettypeсело selects ownАлександровское; samecountyпосёлокКиселинское retained as typed rival.'),('2010:016_802d308e41_8._20Or_Penz_Perm_Samar_Saratov_Uly_2010.xls:!!!:297',114925,'Target startsElkhovskyБерезовка council roster afterVolzhskyЧерноречье lastРамушки; nextКубаньОзеро298+Идея299 match same ownBerezovka council; separatesamecountyдеревняКрасныеДома typed rival retained.'),('2010:016_802d308e41_8._20Or_Penz_Perm_Samar_Saratov_Uly_2010.xls:!!!:468',115133,'OwnAlexandrovka council/KinelCherkassky startswithtarget followedМалореченск469,Безречье470,Степановка471,Березовка472; previousKinelskyЧубовка roster endsСырейка467. RegionalnamesakeKinelМалаяМалышевка excluded.'),('2010:017_68e0e4537e_9._20Basq_Mari_Mord_Tatar_Udm_Chuv_2010.xls:!!!:6768',63927,'Target closesnativeКраснопресненский rosterКраснаяПресня6764,ЗеленаяРоща6765,КрасныйОктябрь6766,Крутенькое6767; nextКрасныйШадым6769 startsdifferentcouncil. SamecountyКрасношадымский/Новомамангинский namesakes retained/excluded byprinted roster.')]
for uid,donorno,note in cases:
 t=R[R.source_record_id==uid].iloc[0].copy();t.source_path=W[W.source_record_id==uid].iloc[0].source_file;u='2021:data_allsettlements_anon_156_v20251217.parquet:parquet:'+str(donorno);b=A[A.target_source_record_id==u];assert len(b)==1; b=b.iloc[0];assert pd.notna(b.latitude) and pd.notna(b.longitude);donor=Z[Z.source_record_id==u].iloc[0];assert donor.type_norm==t.type_norm
 prefix,row=uid.rsplit(':',1);sheet=prefix.rsplit(':',1)[-1];s=xlrd.open_workbook(t.source_path).sheet_by_name(sheet)
 ctx=[]
 for no in range(max(1,int(row)-5),min(s.nrows,int(row)+6)+1):ctx.append(dict(row_1based=no,literal=s.row_values(no-1)))
 contexts.append(dict(target_source_record_id=uid,source_file=t.source_path,source_sha256=h(t.source_path),sheet=sheet,literal_sequence=ctx,selected_native_current=N[N.source_record_id==u].iloc[0].to_dict(),rationale=note))
 alternatives=Z[(Z.region_norm==t.region_norm)&(Z.name_norm==t.name_norm)];inv.append(dict(target_source_record_id=uid,all_type_region_native_candidates=alternatives[['source_record_id','settlement_name','settlement_type','mun_upper','mun_lower','oktmo_native']].to_dict('records')))
 out.append(dict(target_source_record_id=uid,coordinate_source_record_id=u,latitude=b.latitude,longitude=b.longitude,coordinate_admission_status='reviewed_extension_rule_accepted',admission_rule='native_printed_roster_sequence_with_unique_own_type_code_county_or_council_and_accepted_ownpoint',coordinate_origin_ledger=S,coordinate_origin_ledger_sha256=h(S),coordinate_origin_ledger_locator='target_source_record_id='+u,point_origin_file=b.point_origin_file,point_origin_sha256=b.point_origin_sha256,point_origin_locator=b.point_origin_locator,point_origin_kind=b.point_origin_kind,point_temporal_interpretation='Accepted own locality representative retrospectively reused; no census date measurement or boundary equivalence; rawsource county/type retained',direct_historical_coordinate_measurement=False,boundary_comparability_asserted=False,native_code_binding_asserted=False,source_binding_note=note,source_context_witness_file=str(P/'native_roster_context.json.gz')))
pd.DataFrame(out).to_csv(P/'accepted_point_use_delta.csv',index=False)
for name,data in [('native_roster_context',contexts),('all_type_native_rival_inventory',inv)]:
 with gzip.GzipFile(filename=str(P/(name+'.json.gz')),mode='wb',mtime=0) as f:f.write(json.dumps(data,ensure_ascii=False,indent=2).encode())
print('accepted',len(out))
