import pandas as pd,pathlib,json,gzip,hashlib,xlrd,shutil
P=pathlib.Path('research_rebuild/evidence/over500_south_final_points_20261009');a=pd.read_csv(P/'accepted_point_use_delta.csv').fillna('');S='/dev/shm/settlements-stage71-20261009/applied_point_snapshot.parquet';snap=pd.read_parquet(S);new=[]
for row,current in [(1228,121426),(1229,121427)]:
 uid=f'2010:002_027be52979_10._20СевКаз_ФО_20(без_20Даг)_202010.xls:СК:{row}';u=f'2021:data_allsettlements_anon_156_v20251217.parquet:parquet:{current}';b=snap[snap.target_source_record_id==u].iloc[0];new.append(dict(target_source_record_id=uid,coordinate_source_record_id=u,latitude=b.latitude,longitude=b.longitude,coordinate_admission_status='reviewed_extension_rule_accepted',admission_rule='independent_native2002_2009_2021_ordered_coded_roster_pair_resolves_native2010_duplicate_type_label',coordinate_origin_ledger=S,coordinate_origin_ledger_sha256=hashlib.sha256(pathlib.Path(S).read_bytes()).hexdigest(),coordinate_origin_ledger_locator='target_source_record_id='+u,point_origin_file=b.point_origin_file,point_origin_sha256=b.point_origin_sha256,point_origin_locator=b.point_origin_locator,point_origin_kind=b.point_origin_kind,point_temporal_interpretation='Own representative reused retrospectively; raw2010 duplicate station label preserved; no type eventdate or censusdate coordinate measurement',direct_historical_coordinate_measurement=False,boundary_comparability_asserted=False,native_code_binding_asserted=False,source_binding_note='Independent primary ordered four-leaf rosterНовоосетинская→станицаЧерноярская→посёлокЧерноярский→Елбаево2002; raw2009 owncodes90230835002/003; native2021 sameordered paircodes90630435106/111.2010 pair1228/1229 repeatsstationtype: firstboundstanitsa, secondboundstation byordered nativecode/type context, not populations.',source_context_witness_file=str((P/'chernoyarskaya_native_pair_context.json.gz').resolve())))
ctx=[]
for p,sheet,rows in [('/workspace/settlements-raw/data/raw/2002/034_e4218f10b9_02c_N.Osetia.xls','Sheet1',range(237,245)),('/workspace/settlements-raw/data/raw/2010/002_027be52979_10._20СевКаз_ФО_20(без_20Даг)_202010.xls','СК',range(1223,1232))]:
 s=xlrd.open_workbook(p).sheet_by_name(sheet);ctx.append(dict(source_file=p,sha256=hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest(),sheet=sheet,rows=[dict(row_1based=i,literal=s.row_values(i-1)) for i in rows]))
n=pd.read_parquet('/dev/shm/over500-20261009/south_native_current.parquet').reset_index();ctx.append(dict(native_current=n[n.source_record_id.str.endswith(tuple(':'+str(i) for i in range(121424,121429)))].to_dict('records')));cl=pd.read_parquet('/dev/shm/over500-20261009/raw_classifier.parquet');ctx.append(dict(classifier=cl[cl.historical_okato.isin(['90230835001','90230835002','90230835003','90230835004'])].to_dict('records')))
with gzip.GzipFile(filename=str(P/'chernoyarskaya_native_pair_context.json.gz'),mode='wb',mtime=0) as f:f.write(json.dumps(ctx,ensure_ascii=False,indent=2).encode())
# exact own former city-locality place node, distinct region homonym excluded
uid='2002:039_1d4b1f6286_02c_Volgograd.xls:Sheet1:26';o=pd.read_csv('/dev/shm/over500-20261009/south_osm/candidates.csv');q=o[(o.source_record_id==uid)&(o.osm_id==3040189941)].iloc[0];raw=pathlib.Path('/dev/shm/over500-20261009/south_osm/object_node_3040189941.json.gz');b=json.load(gzip.open(raw))['body']['elements'][0];assert b['tags']['place']=='suburb' and b['tags']['name']=='Горная Поляна';shutil.copyfile(raw,P/raw.name);cap=P/('nominatim_'+pathlib.Path(q.capture).name);shutil.copyfile(q.capture,cap);new.append(dict(target_source_record_id=uid,coordinate_source_record_id='OSM:node:3040189941:version='+str(b['version']),latitude=b['lat'],longitude=b['lon'],coordinate_admission_status='reviewed_extension_rule_accepted',admission_rule='native_city_subordinate_council_own_exact_named_former_locality_OSM_place_node',point_origin_file=str((P/raw.name).resolve()),point_origin_sha256=hashlib.sha256(raw.read_bytes()).hexdigest(),point_origin_locator='body.elements[type=node;id=3040189941];lat,lon',point_origin_kind='OSM_own_named_former_locality_place_node',point_temporal_interpretation='Own former locality representative; no censusdate measurement or receiving city point projection',direct_historical_coordinate_measurement=False,boundary_comparability_asserted=False,native_code_binding_asserted=False,source_binding_note='Native2002ownпосёлокГорнаяПоляна underГорнополянскийсельсовет subordinateВолгоград; exactownnodeГорнаяПоляна/Sovetsky/Volgograd retained; distinctLeninskyхутор anditsownarticle excluded.',source_context_witness_file='/workspace/russian-settlements-research/research_rebuild/evidence/over500_south_remaining_points_20261009/native_source_witnesses.csv.gz'))
pd.concat([a,pd.DataFrame(new)],ignore_index=True).to_csv(P/'accepted_point_use_delta.csv',index=False);print('added',len(new))
