import pandas as pd,pathlib,json,gzip,hashlib,shutil
P=pathlib.Path('research_rebuild/evidence/over500_south_final_points_20261009');B=pathlib.Path('research_rebuild/evidence/over500_south_20261009');D=pathlib.Path('/dev/shm/over500-20261009/final_history');uid='2002:039_1d4b1f6286_02c_Volgograd.xls:Sheet1:26';scope='over500_south_final_gornaya_polyana_included';recipient='2021:data_allsettlements_anon_156_v20251217.parquet:parquet:5771';obs=pd.read_parquet('/dev/shm/settlements-stage71-20261009/applied_state_observations.parquet');t=obs[obs.source_record_id==uid].iloc[0];source=None
for f in D.glob('*.json.gz'):
 d=json.load(gzip.open(f));pages=list(d['body']['query']['pages'].values())
 if pages[0].get('title')=='Горная Поляна (Волгоград)':source=f;page=pages[0];break
assert source is not None;dest=P/source.name;shutil.copyfile(source,dest);sf=str(dest.resolve());sha=hashlib.sha256(dest.read_bytes()).hexdigest();loc=f'body.query.pages[{page["pageid"]}];revision={page["revisions"][0]["revid"]};lead literal2010 includedinСоветскийрайонВолгоград; citationdocs.cntd.ru/document/441518167';event=pd.read_csv(B/'accepted_inclusion_events.csv').iloc[0].copy();event.scope_id=scope;event.former_locality='Горная Поляна';event.recipient_city='Волгоград';event.event_date='2010';event.event_source_file=sf;event.event_source_sha256=sha;event.event_source_locator=loc;pd.DataFrame([event]).to_csv(P/'accepted_inclusion_events.csv',index=False)
edge=pd.read_csv(B/'accepted_included_in_event_edges.csv').iloc[0].copy();edge.scope_id=scope;edge.from_source_record_id=uid;edge.to_source_record_id=recipient;edge.event_date='2010';edge.event_source_file=sf;edge.event_source_sha256=sha;edge.event_source_locator=loc;pd.DataFrame([edge]).to_csv(P/'accepted_included_in_event_edges.csv',index=False)
credit=pd.read_csv(B/'accepted_direct_event_native_credit_union.csv').iloc[0].copy();credit.scope_id=scope;credit.source_record_id=uid;credit.source_population=t.population;credit.new_population_on_separate_transformation_path_axis=t.population;credit.own_historical_point_verified=True;credit.receiving_city_actual_2002_2010_2021_context_verified=True;pd.DataFrame([credit]).to_csv(P/'accepted_direct_event_native_credit_union.csv',index=False)
statuses=[]
for year in [2002,2010,2021]:statuses.append(dict(scope_id=scope,place='Горная Поляна',year=year,status='actual_separate_own_published_observation' if year==2002 else 'included_in_receiving_city_own_count_UNKNOWN',own_population=t.population if year==2002 else 'UNKNOWN',unknown_is_zero=False,recipient_population_assigned_to_child=False,boundary_comparability='UNKNOWN'))
pd.DataFrame(statuses).to_csv(P/'accepted_available_year_statuses.csv',index=False)
city=obs[(obs.name_norm=='волгоград')&(obs.region_norm=='волгоградская')];assert set(city.census_year)=={2002,2010,2021};pd.DataFrame([dict(scope_id=scope,source_record_id=q.source_record_id,census_year=q.census_year,city='Волгоград',population=q.population,context_only=True,child_population_assigned=False,source_file=q.source_file) for _,q in city.iterrows()]).to_csv(P/'receiving_city_context.csv',index=False)
print('included_in2010 child sourcepopulation',t.population)
