import pandas as pd,pathlib,json,gzip,hashlib,shutil
P=pathlib.Path('/workspace/russian-settlements-research/research_rebuild/evidence/over500_south_final_points_20261009');previous=pd.read_csv('/workspace/russian-settlements-research/research_rebuild/evidence/over500_south_remaining_points_20261009/accepted_point_use_delta.csv');r=pd.read_csv('/dev/shm/over500-20261009/south_remaining.csv');r=r[~r.source_record_id.isin(previous.target_source_record_id)];a=pd.read_csv(P/'accepted_point_use_delta.csv').fillna('');assert len(r)==16 and len(a)==13 and not a.target_source_record_id.duplicated().any();r.to_csv(P/'input_scope_16.csv.gz',index=False,compression={'method':'gzip','mtime':0});cache={}
def h(p):
 if p not in cache:cache[p]=hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
 return cache[p]
checks=[]
for _,q in a.iterrows():checks.append(dict(target_source_record_id=q.target_source_record_id,origin_hash_pass=h(q.point_origin_file)==q.point_origin_sha256,coordinate_range_pass=30<float(q.latitude)<80 and 15<float(q.longitude)<180))
assert all(c['origin_hash_pass'] and c['coordinate_range_pass'] for c in checks);pd.DataFrame(checks).to_csv(P/'validation_point_source_checks.csv',index=False)
D=pathlib.Path('/dev/shm/over500-20261009/final_history');dest=P/'fresh_history_source_attempts';dest.mkdir(exist_ok=True)
for f in D.iterdir():
 if f.is_file():shutil.copyfile(f,dest/f.name)
shutil.copyfile('/dev/shm/over500-20261009/south_final_dbf_names.csv',P/'raw_geo_own_name_scan.csv');shutil.copyfile('/dev/shm/over500-20261009/south_remaining_roster_context.json',P/'native_current_roster_candidate_context.json')
old_disp=pd.read_csv('/workspace/russian-settlements-research/research_rebuild/evidence/over500_south_remaining_points_20261009/point_only_dispositions.csv.gz').fillna('');disp=[]
for _,t in r.iterrows():
 q=a[a.target_source_record_id==t.source_record_id];status='accepted_ownpoint' if len(q) else 'ownpoint_UNKNOWN_after_captured_source_exhaustion';reason=q.iloc[0].source_binding_note if len(q) else ('No separate ordinal-specific ownfeature inrawGeoDBF/GeoNamesRU/fresh ownWiki/exactNominatim; currentunifiedЯрославка hasownpoint but cannot be assigned to either earlier first/second settlement without a former-name spatial witness. No mergerdate invented.' if 'Ярославка' in t.settlement_name else 'PrintedКантышевскаяadministration; raw2009classifier,fullrawGeoDBF ownnamescan,GeoNamesownname/alternatenames,ownWiki literal/qualifiedtitles andNominatim exactliteral all failto supply ownfeature. CurrentКантышево hasnoГиреевский sourcewitness; guessedГазиЮрт excluded.')
 prev=old_disp[old_disp.source_record_id==t.source_record_id].iloc[0];disp.append(dict(source_record_id=t.source_record_id,settlement_name=t.settlement_name,status=status,point_specific_reason=reason,previous_captured_attempts=prev.osm_queries,new_primary_roster_review='native_roster_context.json.gz',new_raw_geo_scan='raw_geo_own_name_scan.csv',fresh_article_attempts='fresh_history_source_attempts',GeoNames_source_file='/workspace/settlements-raw/data/raw/coordinate_candidates/geonames_RU_20260907.zip',population_unchanged=True,unknown_is_zero=False,temporal_route_gap_not_used_as_point_block=True))
pd.DataFrame(disp).to_csv(P/'point_only_dispositions.csv.gz',index=False,compression={'method':'gzip','mtime':0})
pd.DataFrame(columns=['from_source_record_id','to_source_record_id','relation','decision_status','admission_rule']).to_csv(P/'accepted_identity_edge_delta.csv',index=False)
for f in ['roster_hunt','final_roster_points','final_exception_points','fetch_final_history','fetch_final_history2','final_lifecycle','freeze_final_south']:shutil.copyfile('/dev/shm/over500-20261009/'+f+'.py',P/(f+'.py'))
receipt=dict(input_targets=16,accepted_point_uses=13,accepted_identity_edges=0,accepted_typed_inclusion_events=1,remaining_ownpoint_UNKNOWN=3,coordinate_source_hashes_all_pass=True,counts_modified=0,population_scope_modified=0,raw_coordinates_modified=0,point_coordinate_duplicates_asserted_allowed_only_when_same_ownfeature=False);(P/'validation_receipt.json').write_text(json.dumps(receipt,indent=2))
(P/'README.md').write_text('''Thirteen of sixteen remaining southern whole-settlement targets above500 receive supported own locality representative points. The exact original sixteen targetIDs and all decisions are retained. Three former settlement ownpoints remainUNKNOWN after actual captured source-path exhaustion: ЯрославкаПервая, ЯрославкаВторая andГиреевский. No unified/receiving village point is projected onto them.

Printed primary roster order, own native type/code and county/council context resolve namesakes. Full all-type rival inventories are retained. Native2010Терский rawBudyonno field contradicts the consecutiveGeorgievsky own-place block; the point uses that block and preserves the raw discrepancy. The Черноярская pair is resolved by the independent2002,2009coded and2021ordered pair within the same four-leaf roster. Native2010repeatedstationtype is preserved and flagged; populations are not matching criteria.

Пальна-Михайловский uses fresh ownpage1553110/revision155498328 and its explicitformerestate label. ГорнаяПоляна uses its exactownVolgograd former-locality place-node; the Leninsky хутор namesake is excluded. Its fresh ownarticle separately supports typed included_inVolgograd2010, with year-only secondary source precision. The cited act date is not promoted to an operative day. Receivingcity actual2002/2010/2021 context is retained separately; no citypoint/count or boundary comparability is assigned to the child.

All thirteen point-origin hashes and coordinate ranges pass. Native counts, scopes, raw coordinates and imported native fields remain unchanged. Full-three-year temporal routes are not point admission prerequisites. Root alone owns state/loader/Git integration. This packet is immutable after handoff.
''')
manifest={'packet_files':{str(p):h(str(p)) for p in P.rglob('*') if p.is_file() and p.name!='hash_manifest.json'},'external_point_sources':{str(t.point_origin_file):t.point_origin_sha256 for _,t in a.iterrows()},'GeoNames_source_sha256':h('/workspace/settlements-raw/data/raw/coordinate_candidates/geonames_RU_20260907.zip'),'primary_current_source_inputs':'/workspace/russian-settlements-research/research_rebuild/evidence/over500_south_remaining_points_20261009/source_inputs.json'};(P/'hash_manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2));print(receipt)
