from pathlib import Path
import json,pandas as pd
from research_rebuild.mass_linkage.coverage import sha,identity_sets
w=Path('/workspace/settlements-work');s=w/'coordinates/graph_delta_propagation_v1';oldpath=w/'coordinates/accepted_extension_noncity_v1/accepted_point_uses.parquet';old=pd.read_parquet(oldpath);correct=pd.read_parquet(w/'coordinates/accepted_extension_v2/accepted_point_uses.parquet');correct_ids=set(correct.target_source_record_id);base=pd.concat([correct,old[~old.target_source_record_id.isin(correct_ids)]],ignore_index=True);assert len(base)==304112 and base.target_source_record_id.is_unique
for col in ['target_source_record_id','target_year','latitude','longitude','point_origin_file','point_origin_sha256','point_origin_locator']:
 assert old.set_index('target_source_record_id').sort_index().reset_index()[col].equals(base.set_index('target_source_record_id').sort_index().reset_index()[col])
p=pd.read_parquet(s/'staged_point_uses.parquet');receipt=json.loads((s/'receipt.json').read_text());assert sha(s/'staged_point_uses.parquet')==receipt['output']['staged_point_uses']['sha256'];assert len(p)==1087 and not set(p.target_source_record_id)&set(base.target_source_record_id)
graphpath=w/'identity/accepted_historical_v2/accepted_identity_edges.parquet';graph=pd.read_parquet(graphpath);selected=pd.read_parquet(receipt['inputs']['selected_r2']['path']);nodes=selected.set_index('source_record_id');_,_,_=identity_sets(selected,graph);edges=graph.set_index('decision_id').to_dict('index');carriers=base[base.target_year.eq(2021)].set_index('target_source_record_id')
for row in p.itertuples(index=False):
 carrier=carriers.loc[row.inference_modern_point_use_target_source_record_id];assert (row.latitude,row.longitude)==(carrier.latitude,carrier.longitude)
 assert (row.point_origin_file,row.point_origin_sha256,row.point_origin_locator)==(carrier.point_origin_file,carrier.point_origin_sha256,carrier.point_origin_locator)
 assert row.target_year in (2002,2010) and nodes.loc[row.target_source_record_id].census_year==row.target_year
 cur=row.target_source_record_id
 for did in json.loads(row.inference_identity_path_decision_ids_json):
  edge=edges[did];assert edge['relation']=='same_place' and edge['decision_status']!='pending_independent_application_review'
  a,b=edge['from_source_record_id'],edge['to_source_record_id'];assert cur in (a,b);cur=b if cur==a else a
 assert cur==row.inference_modern_point_use_target_source_record_id
 assert not row.admission_allowed and not row.boundary_comparability_asserted and not row.direct_historical_coordinate_measurement
quality=pd.read_parquet('/workspace/settlements-baseline/output/observation_quality.parquet',columns=['source_record_id','provider_coordinate_conflict']).set_index('source_record_id')
heldids={rid for rid in p.target_source_record_id if rid in quality.index and quality.loc[rid,'provider_coordinate_conflict']==True};assert len(heldids)==24
accepted=p[~p.target_source_record_id.isin(heldids)].copy();accepted['coordinate_admission_status']='reviewed_extension_rule_accepted';accepted['coordinate_quality']='automatically_accepted_checked_rule';accepted['admission_allowed']=True
out=w/'coordinates/accepted_final_v1';out.mkdir();p[p.target_source_record_id.isin(heldids)].to_parquet(out/'additional_legacy_point_conflict_holds.parquet',index=False)
review={'review_id':'final_graph_point_delta_root_independent_application_review_20261003','verdict':'APPROVE 1063 of the 1087 staged retrospective uses; hold all 24 unresolved legacy point-conflict targets.','reviewed_application_receipt_sha256':sha(s/'receipt.json'),'reviewed_staged_sha256':sha(s/'staged_point_uses.parquet'),'whole_delta_actual_path_and_carrier_coordinate_origin_checks':1087,'accepted_new_uses':len(accepted),'additional_conflict_holds':len(heldids),'review_script_sha256':sha(Path(__file__)),'limits':'Accepted same-place graph plus modern representative point spatial continuity only, not exact historic measurement/boundary or population comparability. Missing query receipt is not a veto.'};(out/'review.json').write_text(json.dumps(review,ensure_ascii=False,indent=2)+'\n');accepted['coordinate_application_review_sha256']=sha(out/'review.json');result=pd.concat([base,accepted],ignore_index=True);assert result.target_source_record_id.is_unique;path=out/'accepted_point_uses.parquet';result.to_parquet(path,index=False);r={'status':'accepted_final_working_coordinate_layer','rows':len(result),'new_graph_delta_uses':len(accepted),'base_coordinate_values_unchanged':True,'moscow_2002_quality_corrected_to_individually_reviewed':True,'origin_addendum_sha256':sha(w/'coordinates/extension_application_review_v1/origin_acceptance_addendum_v2.json'),'review_sha256':sha(out/'review.json'),'output':{'path':str(path),'sha256':sha(path)}};(out/'acceptance_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n');print(json.dumps(r))
