import json,hashlib,math
from pathlib import Path
import pandas as pd
p=Path(__file__).parent
pins=json.loads((p/'input_pins.json').read_text())
def sha(f):return hashlib.sha256(Path(f).read_bytes()).hexdigest()
for f,h in pins.items():assert sha(f)==h,f
def km(a,b):
 lat1,lat2=map(math.radians,[a[0],b[0]]);dlat=lat2-lat1;dlon=math.radians(b[1]-a[1]);return 6371.0088*2*math.asin(math.sqrt(math.sin(dlat/2)**2+math.cos(lat1)*math.cos(lat2)*math.sin(dlon/2)**2))
rawp='/workspace/settlements-raw/data/interim/2021_tochno/data_allsettlements_anon_156_v20251217.parquet';r=pd.read_parquet(rawp,columns=['object_name','oktmo','mun_upper','mun_lower','population','settlement_with_type_dadata','fias_level_dadata','okato_dadata','oktmo_dadata','latitude_dadata','longitude_dadata']).iloc[98568].to_dict()
gn=[57.6339,55.1258];alt=[58.247,57.1542];prov=[r['latitude_dadata'],r['longitude_dadata']]
alternate={'actual_raw2021_row1based':98569,'actual_raw2021_provider_fields':r,'admitted_GN_id':'6267030','admitted_lat_lon':gn,'alternate_GN_id':'8061468','alternate_feature_code':'PPLQ','alternate_lat_lon':alt,'both_ADM1':'RU.90','both_ADM2':'UNKNOWN','admitted_to_alternate_km':km(gn,alt),'actual_typed_provider_to_admitted_km':km(prov,gn),'actual_typed_provider_to_alternate_km':km(prov,alt),'abandoned_alias_sameplace_or_other_namesake':'UNKNOWN; no assertion of alternate administrative identity','resolution':'Full original2021 roster contains exactly one ownname NP across all regional NP types including blank populations. Actual own row describes Ohan locality and retains typed ownname provider point near admitted PPL. Original2002 published Ohan county and accepted historical typed component corroborate admitted locality context. Provider code bridge is not asserted. PPLQ omission from current roster or featurecode alone is not treated as a disambiguator.'}
(p/'Sychi_alternate_GN_assessment.json').write_text(json.dumps(alternate,ensure_ascii=False,indent=2,default=str))
receipt={'status':'PASS_four_bounded_GeoNames_anchor_rule_checks','carriers_checked':4,'actual_conflicts':0,'selection_rule_file':'selection_rule.json','selected_names':['Мокшино','Крутая Осыпь','Высокое','Сычи'],'rule_checks':['Actual RU.txt line, ID, P/PPL class, coordinate and literal Cyrillic alternate name reopened.','Actual RU ADM1 record reopened and exact native Russian region label matched.','Entire raw2021 typed NP roster scanned per region without population or subtype filtering; exactly one ownname NP for each selected carrier.','Eight historical native XLS own rows reopened exactly; own typed locality labels and published2002 county contexts agree with accepted trajectories.','Existing accepted historical identity is preserved; no observed contradictory relocation/merger evidence.'],'historical_county_limit':'Sparse2010 tables do not independently repeat county at every leaf. This bounded point review uses existing accepted component identity, reopened properNP2010 leaf and published2002 county; arbitrary earlier nonempty2010 district cells are not interpreted as leaf county assignments.','Sychi_note_file':'Sychi_alternate_GN_assessment.json','official_modern_GN_NP_code_asserted':False,'GN_admin2_when_absent':'UNKNOWN','inherited_oldyear_coordinates':'Retrospective continuity inference, not historical measurement.','limitations':'Four deterministic concrete checks; no representative sample, calibrated confidence interval or population-accuracy claim. No universal PPLQ exclusion.','source_packet_immutable':True,'input_pins_file':'input_pins.json','output_pins':{f.name:sha(f) for f in p.iterdir() if f.is_file() and f.name!='receipt.json'}}
(p/'receipt.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2));print('PASS; bytes',sum(f.stat().st_size for f in p.iterdir() if f.is_file()),'Sychi distances',alternate['admitted_to_alternate_km'],alternate['actual_typed_provider_to_admitted_km'])
