from pathlib import Path
import pandas as pd,duckdb,re,sys,json,collections,math
R=Path('/workspace/russian-settlements-research');O=Path(__file__).parent;E=O.parent;sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from current_chain_state_20261007 import normalize,sha,distance_km
RAW=Path('/workspace/settlements-raw/data/interim/2021_tochno/data_allsettlements_anon_156_v20251217.parquet');S=Path('/workspace/settlements-delivery/continuation-consolidated-20261003/selected_observations.parquet');P=E/'primary_residual_mass_application_20261008/applied_point_snapshot.parquet';SCREEN=Path('/workspace/settlements-work/coordinates/ledger/coordinate_screen.parquet')
c=duckdb.connect();f=c.execute('select source_record_id,settlement_name,settlement_type,region_norm,district_raw,population,oktmo,population_value_quality,source_name_raw,source_locator from read_parquet(?) where census_year=2021 and is_additive_settlement_record',[str(S)]).fetchdf();raw=c.execute('select row_number() over() rn,object_level,object_name,oktmo,region,mun_upper,mun_lower,population,settlement_fias_id_dadata,settlement_with_type_dadata,settlement_type_full_dadata,settlement_dadata,fias_id_dadata,fias_level_dadata,okato_dadata,oktmo_dadata,qc_geo_dadata,latitude_dadata,longitude_dadata from read_parquet(?)',[str(RAW)]).fetchdf().astype(object).fillna('');ps=c.execute('select source_record_id,latitude,longitude from read_parquet(?)',[str(P)]).fetchdf().set_index('source_record_id').to_dict('index');c.close();pins={str(q):sha(q) for q in [RAW,S,P,SCREEN]};extra=[]
for n in ['current_positive_residual_point_sources_20261008','current_remaining_cached_named_sources_20261008']:
 q=E/n/'accepted_point_use_delta.csv.gz';x=pd.read_csv(q,dtype=str,keep_default_na=False);pins[str(q)]=sha(q)
 for z in x.to_dict('records'):ps[z['target_source_record_id']]=z
raw=raw.set_index('rn');rd=f.set_index('source_record_id').to_dict('index')
def code(v):
 v=str(v).strip().removesuffix('.0');return v.zfill(11) if v.isdigit() and len(v) in [10,11] else v
np=raw[raw.object_level.eq('Населенный пункт')].copy();np['codekey']=np.oktmo.map(code);codes=np.groupby('codekey').size().to_dict();np['fias']=np.fias_id_dadata.astype(str);fiascodes=np[np.fias.ne('')].groupby('fias').codekey.nunique().to_dict();xycodes=collections.defaultdict(set)
for z in np.to_dict('records'):
 try:xy=(float(z['latitude_dadata']),float(z['longitude_dadata']))
 except (ValueError,TypeError):continue
 if math.isfinite(xy[0]) and math.isfinite(xy[1]):xycodes[xy].add(z['codekey'])
def bare(v):return ' '.join(re.sub(r'[^а-яa-z0-9]+',' ',normalize(v).replace('_x000d_','')).split())
def lexical(v,rail=False):
 v=normalize(v).replace('_x000d_','');v=re.sub(r'\bим\.?\s+','имени ',v);v=re.sub(r'\bсвх\b','совхоза',v);v=re.sub(r'\b(?:n|№)\s*(\d)',r'номер \1',v);v=re.sub(r'ж\.?\s*[д/]\.?\s*','железнодорожная ',v);v=v.replace('ж/д','железнодорожная');v=re.sub(r'\bжелезнодорожн(?:ая|ой|ого)\b','железнодорожная',v)
 if rail:v=re.sub(r'^\s*(?:при\s+)?(?:железнодорожная\s+)?(?:станци[яи]|разъезда?|ст\.)\s+','',v);v=re.sub(r',?\s*железнодорожная\s+станция\s*$','',v)
 return bare(v)
def typ(v):return {'сельский поселок':'поселок','поселок сельского типа':'поселок','поселок городского типа':'пгт','рабочий поселок':'пгт','рп':'пгт','д':'деревня','с':'село','п':'поселок','г':'город'}.get(normalize(v),normalize(v))
physical={'поселок','село','деревня','город','пгт','хутор','станица','аул','слобода','железнодорожный объект','станция','разъезд','починок','аал','арбан','кордон','заимка','участок','местечко'};occupied=collections.defaultdict(set)
for sid,z in ps.items():
 if sid.startswith('2021:'):occupied[(float(z['latitude']),float(z['longitude']))].add(sid)
out=[];holds=[];counts=collections.Counter();actualrawsha=pins[str(RAW)]
for sid,z in rd.items():
 r=raw.loc[int(sid.rsplit(':',1)[1])].to_dict();reasons=[];nativecode=code(r['oktmo']);provider=code(r['oktmo_dadata']);rail=any(t in normalize(z['settlement_name']) for t in ['станци','ж.д','ж/д','разъезд']) or typ(z['settlement_type'])=='железнодорожный объект';st,pt=typ(z['settlement_type']),typ(r['settlement_type_full_dadata']);compatible=st==pt or st=='поселок' and pt in ['поселок и(при) станция(и)','поселок при железнодорожной станции','станция'] or st=='железнодорожный объект' and pt in ['железнодорожная станция','железнодорожный разъезд','станция','разъезд']
 if r['object_level']!='Населенный пункт' or st not in physical:reasons.append('actual native object not physical typed NP')
 if nativecode!=provider or not re.fullmatch(r'\d{11}',nativecode):reasons.append('native/provider own OKTMO not exact full11digits')
 if str(r['fias_level_dadata'])!='6' or not str(r['fias_id_dadata']) or r['fias_id_dadata']!=r['settlement_fias_id_dadata']:reasons.append('provider object not own settlement FIAS level6')
 if codes.get(nativecode)!=1 or fiascodes.get(str(r['fias_id_dadata']))!=1:reasons.append('native code or FIAS binds multiple actual native codes')
 if not compatible:reasons.append('actual provider type contradicts native physical subtype')
 if lexical(z['settlement_name'],rail)!=lexical(r['settlement_dadata'],rail):reasons.append('own source/provider literal names disagree under closed lexical aliases')
 if normalize(r['object_name'])!=normalize(z['source_name_raw']) or (pd.notna(z['population']) and str(r['population'])!='' and float(r['population'])!=float(z['population'])):reasons.append('native selected/publisher ownlabel or total mismatch')
 try:xy=float(r['latitude_dadata']),float(r['longitude_dadata'])
 except (ValueError,TypeError):xy=None
 if xy is None or not (41<=xy[0]<=82 and 19<=xy[1]<=180):reasons.append('provider ownpoint invalid Russia envelope')
 if xy and len(xycodes[xy])>1:reasons.append('provider coordinate shared by distinct native own codes')
 if xy and occupied[xy]-{sid}:reasons.append('ownpoint occupied by another accepted current native NP')
 row={**z,'target_source_record_id':sid,'latitude':xy[0] if xy else '', 'longitude':xy[1] if xy else '', 'already_accepted_ownpoint':sid in ps,'native_own_OKTMO':nativecode,'provider_own_OKTMO':provider,'provider_own_name':r['settlement_dadata'],'provider_own_type':r['settlement_type_full_dadata'],'provider_FIAS_level':r['fias_level_dadata'],'provider_fias_id':r['fias_id_dadata'],'own_native_code_count_full_roster':codes.get(nativecode,0),'FIAS_distinct_native_codes_full_roster':fiascodes.get(str(r['fias_id_dadata']),0),'provider_samepoint_distinct_native_codes':len(xycodes[xy]) if xy else 0,'raw_native_provider_ownobject_json':json.dumps(r,ensure_ascii=False,default=str),'point_origin_file':str(RAW),'point_origin_sha256':actualrawsha,'point_origin_locator':f'parquet_1basedrow={sid.rsplit(":",1)[1]};own object_name/oktmo;settlement_dadata;FIASlevel6;latitude_dadata;longitude_dadata','point_origin_kind':'raw2021_exactnative_ownOKTMO_literaltyped_level6_FIAS_NP_point','coordinate_source_record_id':r['fias_id_dadata'],'coordinate_admission_status':'candidate_only_source_positive_current_carrier_pending_actual63_screen','query_journal_required':False,'Wiki_P31_required':False,'provider_ID_and_point_binding_separately_checked':True}
 if reasons:row['held_reason']='; '.join(sorted(set(reasons)));holds.append(row);counts.update(set(reasons))
 else:out.append(row);counts['positive_already_accepted' if sid in ps else 'positive_missing_current_ownpoint']+=1
W=Path('/workspace/settlements-work/grounded_current_carrier_expansion_20261008');W.mkdir(exist_ok=True)
pd.DataFrame(out).drop(columns=['raw_native_provider_ownobject_json']).to_parquet(W/'source_positive_coded_current_candidates.parquet',index=False,compression='zstd');pd.DataFrame(holds).drop(columns=['raw_native_provider_ownobject_json']).astype(str).to_parquet(W/'raw_coded_current_holds.parquet',index=False,compression='zstd');pd.DataFrame([z for z in out if not z['already_accepted_ownpoint']]).to_csv(O/'source_positive_missing_current_candidates.csv.gz',index=False,compression={'method':'gzip','mtime':0});receipt={'status':'candidate_only_source_positive_full_raw2021_coded_current_binding_pending_actual63_compatibility','no_State_load':True,'native_rows_screened':len(f),'source_positive':len(out),'positive_missing_current_ownpoint':sum(not x['already_accepted_ownpoint'] for x in out),'missing_carrier_known2021_population':sum(float(x['population']) for x in out if not x['already_accepted_ownpoint'] and pd.notna(x['population'])),'outcomes':dict(counts),'rule':'actual full raw2021 own NP/source total/own11digit OKTMO and provider own samecode; unique native code and FIAS native code; own primary=settlement FIASlevel6; literal ownname under closed lexical normalization and physical typed subtype; no shared provider coordinates or accepted current occupation; no Wiki P31/query journal necessary. Current positive point candidate is independently sourced, never identity by proposed historic edges. Actual63 component compatibility and allrivals screen still required.','input_pins':pins,'output_pins':{str(q):sha(q) for q in [W/'source_positive_coded_current_candidates.parquet',W/'raw_coded_current_holds.parquet',O/'source_positive_missing_current_candidates.csv.gz']},'use_conditions':'Pinned Tochno/Rosstat raw2021 publisher Dadata fields; current locality representative, provider measurement date unknown; no address/parcel accuracy or census-date measurement asserted'};(O/'raw_coded_current_candidate_receipt.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n');print(json.dumps({k:v for k,v in receipt.items() if k not in ['input_pins','output_pins']},ensure_ascii=False))
