from pathlib import Path
import pandas as pd,duckdb,json,hashlib
R=Path('/workspace/russian-settlements-research');O=Path(__file__).parent;A=R/'research_rebuild/evidence/main_axis_residual_application63_20261008';S='/workspace/settlements-delivery/continuation-consolidated-20261003/selected_observations.parquet'
def sha(p):
 h=hashlib.sha256()
 with open(p,'rb') as f:
  for z in iter(lambda:f.read(1024*1024),b''):h.update(z)
 return h.hexdigest()
c=duckdb.connect();f=c.execute('select source_record_id,census_year,population,is_additive_settlement_record,region_norm from read_parquet(?)',[S]).fetchdf();ps=set(c.execute('select target_source_record_id as source_record_id from read_parquet(?)',[str(A/'applied_point_snapshot.parquet')]).fetchdf().source_record_id);c.close();cs=pd.read_csv(A/'applied_component_snapshot.csv.gz',dtype=str);f=f.merge(cs[['source_record_id','root']],on='source_record_id',validate='one_to_one');f['own']=f.source_record_id.isin(ps);f['finite']=f.population.notna() & f.is_additive_settlement_record;g=f.groupby('root').agg(n=('source_record_id','size'),ny=('census_year','nunique'),own=('own','all'),finite=('finite','all'));good=set(g.index[(g.n==3)&(g.ny==3)&g.own&g.finite]);q=f[f.root.isin(good)&~f.region_norm.isin(['москва','санкт петербург','севастополь'])&~((f.census_year==2021)&f.region_norm.eq('крым'))];base={str(y):{'rows':int(len(z)),'population':int(z.population.sum())} for y,z in q.groupby('census_year')};expected={'2002':{'rows':141698,'population':127003410},'2010':{'rows':141698,'population':124135845},'2021':{'rows':141698,'population':124759422}};assert base==expected,(base,expected)
e=pd.read_csv(O/'accepted_identity_edge_delta.csv.gz',dtype=str,keep_default_na=False);p=pd.read_csv(O/'accepted_point_use_delta.csv.gz',dtype=str,keep_default_na=False);gain=pd.read_csv(O/'exact_net_primary_source_ID_union_gain.csv.gz');receipt=json.loads((O/'admission_receipt.json').read_text());assert e.decision_status.eq('checked_rule_accepted').all();assert p.coordinate_admission_status.eq('reviewed_extension_rule_accepted').all();assert not p.target_source_record_id.duplicated().any();assert not p.target_source_record_id.isin(ps).any();assert not gain.source_record_id.duplicated().any();assert not e[['from_source_record_id','to_source_record_id']].duplicated().any();assert gain.population.ge(0).all();assert gain.source_record_id.isin(set(pd.read_csv(A/'applied_remaining_primary.csv.gz',usecols=['source_record_id']).source_record_id)).all();assert set(p.target_source_record_id).issubset(set(f.source_record_id));assert (gain.merge(f[['source_record_id','population']],on='source_record_id',suffixes=('_new','_native')).population_new==gain.merge(f[['source_record_id','population']],on='source_record_id',suffixes=('_new','_native')).population_native).all()
assert f.set_index('source_record_id').loc[p.target_source_record_id].census_year.isin([2002,2010]).all()
import sys
sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from current_chain_state_20261007 import normalize
rawcheck=pd.read_csv(O/'actual_native_raw_source_checks.csv.gz',dtype=str,keep_default_na=False);first_count_checks=0
for z in rawcheck.to_dict('records'):
 if not z.get('raw_row_cells_json') or z['literal_label_population_passed']!='True':continue
 v=json.loads(z['raw_row_cells_json']);name=normalize(z['raw_name']);pos=[i for i,a in enumerate(v) if isinstance(a,str) and normalize(a)==name]+[i+1 for i in range(len(v)-1) if isinstance(v[i],str) and isinstance(v[i+1],str) and normalize(v[i]+' '+v[i+1])==name]
 ns=[float(a) for a in v[min(pos)+1:] if isinstance(a,(int,float)) or (isinstance(a,str) and a.isdigit())] if pos else []
 assert ns and ns[0]==float(z['protected_native_population']),z['source_record_id'];first_count_checks+=1
receipt['first_printed_numeric_native_total_checks']=first_count_checks
receipt['baseline_finite_full3_reproduced']=base;receipt['validation']={'canonical_statuses_passed':True,'unique_edges_targets_UID_gains_passed':True,'no_existing_point_replaced':True,'native_population_unchanged_passed':True,'no_current_point_duplicates_with_joint81':True,'exact_primary_residual_UID_union':True};cur=pd.read_csv(O/'accepted_current_point_delta.csv.gz',dtype=str,keep_default_na=False);assert len(cur)==53 and cur.coordinate_admission_status.eq('reviewed_extension_rule_accepted').all() and not cur.target_source_record_id.isin(ps).any();assert not cur.target_source_record_id.duplicated().any();receipt['new_current_ownpoints']=len(cur);receipt['current_point_replacements']=0;receipt['accepted_edges_by_method']=e.admission_method.value_counts().to_dict();receipt['accepted_points_by_native_year']=f.set_index('source_record_id').loc[p.target_source_record_id].census_year.value_counts().to_dict();receipt['packet_status']='FINAL_READY_IMMUTABLE_PENDING_ROOT_CANONICAL_STAGE64_APPLICATION';receipt['output_pins']={q.name:sha(q) for q in O.glob('*.csv.gz')};(O/'admission_receipt.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n')
# Distinguish candidate reserve from admitted population gains.
h=pd.read_csv(O/'geometry_held_identity_pairs.csv.gz');un=pd.read_csv(O/'parish_held_identity_pairs.csv.gz');reserve={'geometry_admission_holds':h.held_reason.value_counts().to_dict(),'top_held_geometry':h.sort_values('from_population',ascending=False).head(30).fillna('').to_dict('records'),'candidate_geometry_resolver_outcomes':json.loads((R/'research_rebuild/evidence/temporal_after_new_current_points_20261008/candidate_geometry_resolver_receipt.json').read_text())['outcomes'],'geometry_candidate_outcomes':json.loads((O/'geometry_candidate_receipt.json').read_text())['outcomes'],'accepted_main_gain':receipt['actual_formation_plus_direct_native_UID_delta'],'accepted_vs_candidate_distinction':True,'parish_holds':un.held_reason.value_counts().to_dict(),'source_positive_admission_holds':pd.read_csv(O/'admission_holds.csv.gz').held_reason.value_counts().to_dict(), 'parish_candidate_pairs':json.loads((O/'parish_candidate_receipt.json').read_text())['candidate_pairs']};(O/'reserve_receipt.json').write_text(json.dumps(reserve,ensure_ascii=False,indent=2)+'\n');(O/'FINAL_manifest.json').write_text(json.dumps({q.name:{'bytes':q.stat().st_size,'sha256':sha(q)} for q in sorted(O.iterdir()) if q.is_file() and q.name!='FINAL_manifest.json'},ensure_ascii=False,indent=2)+'\n');print(json.dumps({'baseline':base,'edges':len(e),'points':len(p),'gain':receipt['actual_formation_plus_direct_native_UID_delta'],'receipt_sha':sha(O/'admission_receipt.json')},ensure_ascii=False))
