from pathlib import Path
import struct,json,gzip,re,hashlib,pandas as pd,pyarrow.parquet as pq,xlrd
D=Path(__file__).parent;E=D.parent.parent;sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
old=D.parent/'mosrentgen_formation_branch_candidate';oldrec=json.loads((old/'candidate_branch_receipt.json').read_text())
for fn,h in oldrec['outputs'].items():assert sha(old/fn)==h
for p,h in oldrec['source_manifest'].items():assert sha(p)==h
predobs=E/'moscow_complete_scope_mass_application_20261008/accepted_transferred_municipal_scope_observations.csv';predm=E/'moscow_complete_scope_mass_application_20261008/accepted_native_scope_constituents.csv';pred=pd.read_csv(predobs,keep_default_na=False);pred=pred[pred.census_year.eq(2002)&pred.scope_id.isin(['moscow_sourceyear_sosenskoye','moscow_sourceyear_moskovsky'])];assert len(pred)==2
pm=pd.read_csv(predm,keep_default_na=False);pm=pm[pm.year.eq(2002)&pm.scope_id.isin(pred.scope_id)];assert pm.selected_native_source_ID.all() and pm.source_record_id.is_unique
for r in pred.itertuples():
 g=pm[pm.scope_id.eq(r.scope_id)];assert len(g)==r.native_members_count and g.native_population.astype(float).sum()==r.population
pred.assign(graph_role='existing_shared2002predecessor_wholeterritory_reference_ONLY',new_population_credit=0,new_observation_created=False).to_csv(D/'existing2002_shared_predecessor_observation_references.csv',index=False);pm.assign(graph_role='existing_complete2002predecessor_native_context_ONLY',new_population_credit=0).to_csv(D/'existing2002_complete_predecessor_native_contexts.csv',index=False)
# Reopen complete2002printed ruralcouncil brackets, not modern subsets.
p02=Path('/workspace/settlements-raw/data/raw/2002/010_3e630cc803_02c_Moskovskaya-oblast.xls');s=xlrd.open_workbook(str(p02)).sheet_by_index(0);proof=[]
for scope,a,b in [('moscow_sourceyear_sosenskoye',2692,2707),('moscow_sourceyear_moskovsky',2681,2691)]:
 g=pm[pm.scope_id.eq(scope)];rows=set(g.raw_row_1based.astype(int));atoms=set()
 for n in range(a+1,b+1):
  label=str(s.cell_value(n-1,1))
  if re.match(r'^\s*(?:пос[её]лок|деревня|село)\s+',label,re.I):atoms.add(n)
 assert rows==atoms and float(s.cell_value(a-1,2))==g.native_population.astype(float).sum()
 proof.append(dict(scope_id=scope,year=2002,graph_role='complete_existing_predecessor_context_no_newownMosrentgen2002',raw_file=str(p02),raw_sha256=sha(p02),raw_parent_row_1based=a,literal_parent=s.cell_value(a-1,1),whole_parent_count=float(s.cell_value(a-1,2)),raw_leaf_count=len(rows),next_parent_row_1based=b+1,literal_next_parent=s.cell_value(b,1),all_original_named_leaves_match_existing_selectedIDs=True,raw_complete_bracket_json=json.dumps([dict(row_1based=n,raw=s.row_values(n-1)[:6]) for n in range(a,b+2)],ensure_ascii=False)))
pd.DataFrame(proof).to_csv(D/'original2002_complete_shared_predecessor_brackets.csv',index=False)
# Independently observed wholemunicipal2010/2021 and ownmunicipalpoint remain separategrain.
obs=pd.read_csv(old/'candidate_branch_whole_municipal_observations.csv',keep_default_na=False);assert set(obs.census_year)=={2010,2021};assert obs.set_index('census_year').population.to_dict()=={2010:17004,2021:21390};obs['authentic_source_grain']='whole_published_sourceyear_municipal_territory_NOT_individual_NP';obs['root_formation_branch_pending']=True;obs.to_csv(D/'candidate_whole_municipal_observations.csv',index=False)
leaves=pd.read_csv(old/'candidate_branch_native2010_roster.csv',keep_default_na=False);assert len(leaves)==3 and leaves.source_record_id.is_unique and leaves.native_population.sum()==12350
p10=Path('/workspace/settlements-raw/data/raw/2010/010_711691e352_2._20Kostrom_Kur_Lip_Moscow_MoscObl_Orlov_2010.xls');s10=xlrd.open_workbook(str(p10)).sheet_by_name('Data Sheet')
for r in leaves.itertuples():assert s10.cell_value(int(r.raw_row_1based)-1,4)==r.native_population
leaves['authentic_source_grain']='actual_individual_NP_2010_leaf_in_complete_published_municipal_roster';leaves['national2021_child_population_created']=False;leaves['ownNP2021_population']='';leaves['candidate_conditional_sourceUID_credit_only']=True;leaves.to_csv(D/'candidate_complete2010_native_constituents.csv',index=False)
rows=[dict(year=2010,raw_file=str(p10),raw_sha256=sha(p10),raw_sheet='Data Sheet',raw_row_1based=n,role='complete2010wholemunicipalrawroster' if 10440<=n<=10442 else 'adjacentdifferentmunicipalcontext',raw_original_row_json=json.dumps(s10.row_values(n-1)[:6],ensure_ascii=False)) for n in range(10439,10444)];pd.DataFrame(rows).to_csv(D/'original2010_complete_roster_and_adjacent_contexts.csv',index=False)
# Independentlyownphysical settlement point, not municipalityP625.
dbf=Path('/workspace/settlements-raw/data/interim/historical_geography/geokladr_okato_2011/okato.dbf');parsed=Path('/workspace/settlements-work/sources/geokladr_raw_verification/geokladr_okato_2011_raw_parsed.parquet');geo=pq.read_table(parsed,filters=[('historical_okato','==','46228826014')]).to_pandas();assert len(geo)==1;g=geo.iloc[0];assert not g.is_deleted and g.settlement_type_raw=='п' and g.kladr=='5001400004800'
with dbf.open('rb') as h:
 head=h.read(32);hl,rl=struct.unpack('<HH',head[8:12]);fields=[];off=1
 while True:
  d=h.read(32)
  if d[0]==13:break
  name=d[:11].split(b'\0')[0].decode();fields.append((name,off,d[16]));off+=d[16]
 loc=hl+(int(g.record_number_1based)-1)*rl;assert loc==g.record_byte_offset_0based;h.seek(loc);raw=h.read(rl);assert raw[:1]==b' ';vals={name:raw[o:o+n].decode('cp1251') for name,o,n in fields};assert vals['NAME1'].strip()==g.name_raw and float(vals['LAT'])==g.latitude_from_lat and float(vals['LONG'])==g.longitude_from_long
sql=Path('/workspace/settlements-raw/data/raw/historical_classifiers/okato_142_2009/dump-142_2009.sql');cp=Path('/workspace/settlements-work/sources/raw_okato_2009_verification_v1/raw_classifier.parquet');classifier=pq.read_table(cp,filters=[('historical_okato','==','46228826014')]).to_pandas();assert len(classifier)==1;c=classifier.iloc[0];assert c.is_settlement_raw=='t' and c.status=='поселок сельского типа'
with sql.open() as h:
 for n,l in enumerate(h,1):
  if n==int(c.source_line_1based):sqlrow=l.rstrip('\n');break
assert c.historical_okato in sqlrow and c.name_raw in sqlrow
factory=leaves[leaves.native_name.str.contains('Мосрентген')].iloc[0]
point=dict(source_record_id=factory.source_record_id,census_year=2010,own_native_name=factory.native_name,own_native_type=factory.native_type,latitude=g.latitude_from_lat,longitude=g.longitude_from_long,point_grain='own_physical_individual_settlement_NOT_municipalP625',raw_source_file=str(dbf),raw_source_sha256=sha(dbf),raw_record_number_1based=int(g.record_number_1based),raw_byte_offset_0based=int(g.record_byte_offset_0based),raw_updated_at=g.source_updated_at,raw_ownNP_name=g.name_raw,raw_ownNP_type=g.settlement_type_raw,raw_okato=g.historical_okato,raw_kladr=g.kladr,original_DBFFields_json=json.dumps(vals,ensure_ascii=False),classifier_file=str(sql),classifier_sha256=sha(sql),classifier_line_1based=int(c.source_line_1based),classifier_is_settlement_raw=c.is_settlement_raw,original_classifier_line=sqlrow,point_grade='Cached2011physicalownsettlementpoint; inferredcontinuity to2010nativeNP, notexactcensusdaymeasurement',municipal_P625_substituted=False,ownNP2021_count_created=False,ordinary_pointuse_applied=False,candidate_only=True)
pd.DataFrame([point]).to_csv(D/'candidate_separate_own_properNP_physical_point.csv',index=False)
# Eventgraph references actualexisting predecessor observations; sharedcredit nevercopied.
edges=[]
for r in pred.itertuples():edges.append(dict(from_observation_id=r.observation_id,from_grain='existing_whole2002published_ruralcouncil',to_observation_id='moscow_formation_branch_mosrentgen:2010',to_grain='own_whole2010sourceyear_municipality',relation='documented2005_municipal_formation_from_portions_of_two_existing_predecessor_territories',effective_year=2005,predecessor_UID_credit_newly_added=False,source_population_allocated_to_modern_subset=False,ordinary_same_place=False,boundary_comparability='UNKNOWN',candidate_only=True))
for r in leaves.itertuples():edges.append(dict(from_observation_id=r.source_record_id,from_grain='own_actual2010individual_NP',to_observation_id='moscow_formation_branch_mosrentgen:2010',to_grain='own_whole2010sourceyear_municipality',relation='contained_in_complete_published2010municipal_roster',effective_year=2010,predecessor_UID_credit_newly_added=False,source_population_allocated_to_modern_subset=False,ordinary_same_place=False,boundary_comparability='UNKNOWN',candidate_only=True))
edges.append(dict(from_observation_id='moscow_formation_branch_mosrentgen:2010',from_grain='own_whole2010sourceyear_municipality',to_observation_id='moscow_formation_branch_mosrentgen:2021',to_grain='own_whole2021sourceyear_municipality',relation='sourceyear_wholemunicipal_trace_after_documented2012Moscowtransfer',effective_year='2012-07-01transfer;sourceboundariesUNKNOWN',predecessor_UID_credit_newly_added=False,source_population_allocated_to_modern_subset=False,ordinary_same_place=False,boundary_comparability='UNKNOWN',candidate_only=True));pd.DataFrame(edges).to_csv(D/'candidate_separate_formation_and_containment_edges.csv',index=False)
formation=(old/'cached_formation_excerpt.txt').read_text();assert '2005' in formation and 'Сосенского сельского округа' in formation and 'Московского сельского округа' in formation;pf=E/'moscow_large_residual_actionable_20261008/municipal_pages.json.gz';pg=next(p for p in json.load(gzip.open(pf,'rt'))['query']['pages'].values() if p.get('pageprops',{}).get('wikibase_item')=='Q4373595');t=pg['revisions'][0]['slots']['main']['*'];transfer='\n'.join(z for z in t.splitlines() if '2012' in z and ('июл' in z or 'состав' in z));assert transfer;(D/'cached2005formation_2012transfer_excerpt.txt').write_text(formation+'\n'+transfer+'\n')
controls=[dict(year=2010,whole_municipal_observation=17004,all3_native2010_roster_sum=12350,control_difference_unallocated=4654,roster_complete=True,leaf2021_population_created=False,raw_counts_redistributed=False),dict(year=2021,whole_municipal_observation=21390,all3_native2010_roster_sum='',control_difference_unallocated='',roster_complete='wholemunicipalobserved, noindividualNP2021countsasserted',leaf2021_population_created=False,raw_counts_redistributed=False)];pd.DataFrame(controls).to_csv(D/'sourceyear_whole_control_and_unallocated_difference.csv',index=False)
pins=oldrec['source_manifest']|{str(p):sha(p) for p in [predm,p02,dbf,parsed,sql,cp]};receipt=dict(status='frozen_candidate_separate_two_predecessor_mosrentgen_formation_branch',own_observed_municipal_years=[2010,2021],existing2002_predecessor_observation_references=2,own2002_Mosrentgen_municipal_observations=0,constructed10336_modern_subset_whole=False,whole2010_population=17004,whole2021_population=21390,all3_actual_selected_native2010_constituents=3,conditional2010_native_population_credit_cap=12350,protected_or_scope_difference4654_unallocated=True,existing2002_sourceUIDs_newly_credited=0,national2021_new_credit=0,ordinary3year_or_originalmixed99_claim=False,ordinary_graph_or_pointuses_modified=False,separate_own2010_factoryNP_physical_point_available=True,physical_point_source_municipal=False,network_requests=0,root_separate_event_adapter_acceptance_pending=True,source_manifest=pins,outputs={p.name:sha(p) for p in D.glob('*.csv')},code_sha256={'build.py':sha(D/'build.py')});(D/'candidate_branch_receipt.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n');print(json.dumps({k:receipt[k] for k in ['status','conditional2010_native_population_credit_cap','existing2002_sourceUIDs_newly_credited','separate_own2010_factoryNP_physical_point_available','network_requests']},ensure_ascii=False))
