from pathlib import Path
import pandas as pd,json,xlrd,re,hashlib,shutil
E=Path('/workspace/russian-settlements-research/research_rebuild/evidence');O=E/'remaining_absorbed_city_published_closures_20261008';D=pd.read_csv(O/'candidate_constituent_credit_union.csv');books={};proof=[]
for r in D[D.census_year.isin([2002,2010])].itertuples():
 if not r.source_file.endswith('.xls'):continue
 if r.source_file not in books:books[r.source_file]=xlrd.open_workbook(r.source_file)
 sn,n=r.source_row_locator.split('!row_1based=');b=books[r.source_file];s=b.sheet_by_index(0) if sn=='0' else b.sheet_by_name(sn);rr=s.row_values(int(float(n))-1)
 if r.census_year==2010:
  if sn=='Урал':value=int(rr[7]);lab=str(rr[4])
  else:value=int(rr[5]);lab=str(rr[4])
 else:
  ix=next(i for i,z in enumerate(rr) if isinstance(z,str) and r.settlement_name.lower().replace('ё','е') in z.lower().replace('ё','е'));value=int(float(rr[ix+1]));lab=str(rr[ix])
 assert value==r.population,(r.source_record_id,value,r.population)
 proof.append({'group':r.group,'source_record_id':r.source_record_id,'year':r.census_year,'raw_original_file':r.source_file,'raw_original_sha256':r.source_file_sha256,'raw_locator':r.source_row_locator,'raw_atomic_label':lab,'raw_value':value,'selected_value':r.population,'source_quality':r.source_population_quality,'raw_original_row_first_columns_json':json.dumps(rr[:11],ensure_ascii=False),'selected_values_unmodified':True})
pd.DataFrame(proof).to_csv(O/'original_atomic_raw_row_bindings.csv',index=False)
for name in ['build.py','verify.py']:shutil.copy(Path('/workspace/settlements-work/remaining_absorbed_city_published_closures_20261008')/name,O/name)
g=pd.read_csv(O/'candidate_group_observations.csv');edges=[]
for group,x in g.groupby('group'):
 for a,b in [(2002,2010),(2010,2021)]:edges.append({'group':group,'from_observation_id':x[x.census_year.eq(a)].iloc[0].observation_id,'to_observation_id':x[x.census_year.eq(b)].iloc[0].observation_id,'relation':'complete_published_city_territorial_hierarchy_trace','ordinary_same_place':False,'boundary_comparability':'UNKNOWN','candidate_only':True,'exact_annexation_roster_claimed':False,'event_relations_effective_date':'UNKNOWN'})
pd.DataFrame(edges).to_csv(O/'candidate_scope_edges.csv',index=False);p=O/'candidate_receipt.json';r=json.loads(p.read_text());r['all_original_xls_atomic_rows_reopened']=len(proof);r['2010_closure_evidence']='Exact raw owncity block followed by complete publishedrural NP list until next city; corroborated by independent2002/current completeassociated ruralrosters and primary2010parent/ruralcontrols. Values protected; sourcequalitydifference retained, not missingpopulation allocated.';r['remaining_Nakhoda_hold']='Originaldirect2002population маякПоворотный5 exists in exact publishedruralatomicblock; absentselectedNP table, nofake nativecredit/rawgap allocation performed';paths=[E/'working_full_chain_20261007/coverage_receipt.json',E/'working_full_chain_20261007/qualified_scope_source_id_credit_union.csv',E/'working_full_chain_20261007/named_merger_lineage_constituents.csv',E/'working_full_chain_20261007/complete_publisher_partition_members.csv'];r['baseline_inputs_sha256']={str(p):hashlib.sha256(p.read_bytes()).hexdigest() for p in paths};r['outputs']={p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in O.glob('*.csv')};p.write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n')
(O/'README.md').write_text('''# Remainingcompact cityterritory closures, candidate only\n\nTwo complete changing publishedterritorial traces: Копейск and Артем,6 censusobservations40 nativeatomic members. Potentialnewselected-IDcredit2002=107,236(13IDs),2010=2,027(3IDs),2021=1,827(3IDs). Noapplication,helper,loader,report orGit mutation.\n\n2002federalallcity/subordinates controls close regionalrural leaves. Bothcurrent2021rawmunicipalparents close to everyNP (Копейск4,Артем6). Original2010ethnic cityblock has all3/5 ruralNPs until nextcity, corroborated by published2002/currentchildrosters and primary2010ruralcontrols. This is completepublished sourcehierarchy, not individualcrossyearNP identity or exactannexationroster.\n\nPrimary2010owncity values137601/102603 replace protectedcity alternatives130669/98450 only as memberselection, neveroverwritingoriginalvalues. Protectedrural sourcevalues stayunchanged. Копейск selected139757 vsprimary139756 difference-1; Артем selected111862 vsprimary112061 difference199. Differences explicitlyretained andneverallocated.\n\nEveryoriginalXLSatomic binding reopened with sameNP rawlabel/nativevalue. Underlying2010source_quality remains secondary_confidentiality_protected_value_exact_scope_unverified. Current admittedowncitypoint represents wholeterritory scope only; boundariesUNKNOWN, historicalchildpoints/missingyearcounts notinvented.\n\nНаходка held: original2002namedphysical маякПоворотный5 is absentselectedNP dataset. Its rawrowexists, but selectedsum178808 doesnotclose178813 parent. Nozero substitute or inventedselectedID/credit wasused. Otherfive remainingcity scopes requirelarger printed2010ruralclosure work and are not proposed. Reproduce build.py,verify.py using frozenreport inputs.\n''');print('verifiedrawatomicrows',len(proof),'bytes',sum(p.stat().st_size for p in O.iterdir() if p.is_file()))
