from pathlib import Path
import pandas as pd,json,gzip,hashlib,xlrd
O=Path(__file__).parent;B=O.parent;sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();d=pd.read_parquet('/dev/shm/over500-moscow-complete-batch5.parquet');pgs={}
for f in[O/'six_historical_county_context_articles.json.gz',O/'Yudinsky_owncounty_article.json.gz',B/'batch4_ownpoint_followup/own_wikipedia_batch6.json.gz']:
 for pg in json.load(gzip.open(f,'rt'))['query']['pages'].values():
  if'revisions'in pg:pgs[pg['title']]=(pg,f)
raw=Path('/workspace/settlements-raw/data/raw/2002/010_3e630cc803_02c_Moskovskaya-oblast.xls');sh=xlrd.open_workbook(str(raw)).sheet_by_index(0);p=pd.read_parquet('/dev/shm/over500-moscow-points.parquet').set_index('target_source_record_id');configs=[(273,65277,'Ченецкий сельский округ','2004-04-22','22 апреля 2004 года','included_in','Ченецкий'),(3859,68500,'Буньковский сельский округ (Московская область)','2004-03-26','26 марта 2004 года','included_in','Буньковский'),(3860,68477,'Буньковский сельский округ (Московская область)','2004-09-10','10 сентября 2004 года','included_in','Буньковский'),(4184,68897,'Юдинский сельский округ (Одинцовский район)','2004-08-09','9 августа 2004 года','merged_into','Юдинский'),(6888,71168,'Гребнево (Московская область)','2004-05-05','5 мая 2004 года','included_in','Гребневский'),(9,68669,'Звенигород','2003-10-07','07.10.2003','included_in',None)];rows=[];context=[]
for n,cn,title,date,term,relation,sub in configs:
 z=d[d.census_year.eq(2002)&d.source_record_id.str.endswith(':'+str(n))];assert len(z)==1;r=z.iloc[0];cur=d[d.census_year.eq(2021)&d.source_record_id.str.endswith(':'+str(cn))].iloc[0];pg,f=pgs[title];txt=pg['revisions'][0]['slots']['main']['*'];assert term in txt,(title,term);head=next((i+1,sh.row_values(i))for i in range(n-2,-1,-1)if'сельский округ'in str(sh.cell_value(i,1)))if sub else None;assert not sub or sub in head[1][1];rr=sh.row_values(n-1);assert any(str(v).replace('.0','')==str(int(r.population))for v in rr);loc=f'pageid={pg["pageid"]};revision={pg["revisions"][0]["revid"]}';scope='over500_moscow_historical_'+str(n);rows.append(dict(scope_id=scope,source_record_id=r.source_record_id,former_NP_name=r.settlement_name,former_NP_type=r.settlement_type,native_year=2002,native_population=int(r.population),native_quality=r.population_value_quality,native_source_path=str(raw),native_source_sha256=sha(raw),native_locator='Sheet1:row'+str(n),literal_native_row=rr,literal_original_subcounty_heading=head,source_original_county=r.derived_oldcounty if sub else'PublishedmunicipalZvenigorodsubordinateNPblock',event_relation=relation,event_date=date,date_precision='day',event_date_role='Literaldatedinclusion/mergerorquotedactdate; operative-dateprecisionnotpromoted',event_source_file=str(f),event_source_sha256=sha(f),event_source_locator=loc,literal_event_source_wholetext=txt,receiving_native2021_source_record_id=cur.source_record_id,receiving_native2021_own_code=cur.oktmo,receiving_native2021_name=cur.settlement_name,receiving_native2021_actual_type=cur.settlement_type,receiving_population_context_only=int(cur.population),own_point_admitted=False,point_binding_pending_separate_own_housing_or_named_neighborhood_source=True,recipient_point_not_assigned=True,unknown_is_zero=False,child_population_afterevent_not_fabricated=True,ordinaryUF_union_not_proposed=True,population_boundary_comparability='UNKNOWN'))
 for m in d[d.after_root.eq(cur.after_root)].itertuples():
  cp=p.loc[m.source_record_id]if m.source_record_id in p.index else None;context.append(dict(scope_id=scope,recipient_city=cur.settlement_name,receiving_NP_actual_type=m.settlement_type,census_year=m.census_year,source_record_id=m.source_record_id,population=m.population,population_value_quality=m.population_value_quality,latitude=cp.latitude if cp is not None else'',longitude=cp.longitude if cp is not None else'',is_receiving_city_context_only=True,new_national_credit_population=0,child_count_substituted=False))
(O/'six_native_event_binding_preparation.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2,default=str));pd.DataFrame(context).to_csv(O/'actual_receiving_NP_available_census_context.csv',index=False);print('sourcebound historical native leaves6, datedevents6, receivingactualobservations',len(context),'ownpointadmissionpending')
