from pathlib import Path
import pandas as pd,xlrd,json,gzip,hashlib,math,re
Z=Path(__file__).parent;B=Z.parent/'over1000_bash_amur_20261009';A=Z.parent/'main_axis_residual_application68_20261008';sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();cols=['source_record_id','root','census_year','settlement_name','settlement_type','region_norm','district_raw','population','population_value_quality','is_additive_settlement_record','oktmo','okato','source_file'];o=pd.read_parquet(A/'applied_state_observations.parquet',columns=cols).set_index('source_record_id',drop=False);pc=['target_source_record_id','latitude','longitude','coordinate_admission_status','point_origin_file','point_origin_sha256','point_origin_locator','point_origin_kind','point_ledger_path'];p=pd.read_parquet(A/'applied_point_snapshot.parquet',columns=pc).set_index('target_source_record_id',drop=False)
cur=lambda n:f'2021:data_allsettlements_anon_156_v20251217.parquet:parquet:{n}';rural='2002:041_4b428edd23_Bashkiria_new.xls:Sheet1:5834';urban='2002:1_TOM_01_04.xls:0:5224';niko='2002:081_6a22d6b5c5_Amur.xls:Sheet1:154';niko33='2002:081_6a22d6b5c5_Amur.xls:Sheet1:400';B10='2010:017_68e0e4537e_9._20Basq_Mari_Mord_Tatar_Udm_Chuv_2010.xls:!!!:'
ids={rural,urban,cur(148581),cur(148583),niko,niko33,cur(60932),cur(60669)};roots=set(o.loc[list(ids),'root']);members=o[o.root.isin(roots)];members.reset_index(drop=True).to_csv(Z/'specific_actual68_component_members.csv',index=False);p[p.index.isin(members.index)].reset_index(drop=True).to_csv(Z/'specific_actual68_active_point_claims.csv',index=False)
ledger=Path('/workspace/settlements-work/continuation_20261004/accepted_graph25_bounded_cases_20261005/accepted_identity_edges.parquet');ec=['decision_id','relation','from_source_record_id','to_source_record_id','decision_status','decision_rule'];ed=pd.read_parquet(ledger,columns=ec);bad=ed[ed.from_source_record_id.eq(rural)&ed.to_source_record_id.eq(cur(148581))];assert len(bad)==1;br=bad.to_dict('records')[0];br.update(rejection_status='reviewed_rejected_identity_claim_only',origin_ledger_path=str(ledger),origin_ledger_sha256=sha(ledger),reason='wrongsame-name02rural386→formerlyPGTlarge5595; independentproper2002PGT5663 separate; 2008Govrename andprintedNurkeevo bindsrural toOldSubkh781/711',specific_split_scope='only rural5834 vs large148581; preserve10large3784→21large148581 and10old3788→21old148583',source_population_changed=False);pd.DataFrame([br]).to_csv(Z/'reviewed_identity_edge_rejection.csv',index=False)
pr=p.loc[rural].to_dict();assert '148581' in pr['point_origin_locator'];pr.update(rejection_status='reviewed_rejected_coordinate_claim_only',active_point_ledger_sha256=sha(pr['point_ledger_path']),reason='inheritedrepresentativepoint bindingderivedfromrejectedwrongidentity; actualoriginbelongs otherpublishedlargeSubkhNP80251861001/80651461101, correctOldruralcarrier80251861003/80651461111; nohistoricalpointmeasurementormoveclaim',recommended_replacement_source_record_id=cur(148583),recommended_latitude=p.loc[cur(148583),'latitude'],recommended_longitude=p.loc[cur(148583),'longitude']);pd.DataFrame([pr]).to_csv(Z/'point_use_rejection_witness.csv',index=False)
# Reopened source bytes and independent own-article literal properties; every raw count/quality is retained.
rows=[];articles=[]
def getpages(j):
 if isinstance(j,dict):
  if isinstance(j.get('pages'),list):yield from j['pages']
  for x in j.values():yield from getpages(x)
 elif isinstance(j,list):
  for x in j:yield from getpages(x)
for f in [B/'version2/live_candidate_article_pages.json.gz',B/'version3/targeted_primary_article_pages.json.gz']:
 for pg in getpages(json.loads(gzip.open(f,'rt').read())):
  if pg.get('title') in ['Субханкулово','Старое Субханкулово','Ургаза','Берёзовка (Ивановский район)']:
   t=pg['revisions'][0]['slots']['main']['content'];articles.append(dict(article_title=pg['title'],source_file=str(f),source_sha256=sha(f),pageid=pg['pageid'],revision=pg['revisions'][0]['revid'],literal_source_text=t))
checkids=[rural,urban,B10+'3784',B10+'3788','2002:081_6a22d6b5c5_Amur.xls:Sheet1:203','2010:009_81f8a0e73c_17._20ДВ_ФО_2010.xls:ДВ:1329','2002:041_4b428edd23_Bashkiria_new.xls:Sheet1:838',niko,'2010:009_81f8a0e73c_17._20ДВ_ФО_2010.xls:ДВ:1246']
for i in checkids:
 x=o.loc[i];f=Path('/workspace/settlements-raw')/x.source_file;part=i.split(':');sn=part[-2];rn=int(part[-1]);bk=xlrd.open_workbook(f);s=bk.sheet_by_name(sn) if sn in bk.sheet_names() else bk.sheet_by_index(int(sn));v=s.row_values(rn-1);context=[dict(physical_row_1based=j+1,cells=s.row_values(j)) for j in range(max(0,rn-5),min(s.nrows,rn+3))];headers=[dict(physical_row_1based=j+1,cells=s.row_values(j)) for j in range(rn-1) if any(t in str(s.row_values(j)) for t in ['район','сельсовет','сельский округ','подчинен'])][-6:];rows.append(dict(source_record_id=i,source_file=str(f),source_sha256=sha(f),sheet=s.name,physical_row_1based=rn,literal_cells_json=json.dumps(v,ensure_ascii=False),literal_physical_neighbor_context_json=json.dumps(context,ensure_ascii=False),header_path_json=json.dumps(headers,ensure_ascii=False),source_population=x.population,source_population_quality=x.population_value_quality,source_scope_is_proper_NP=bool(x.is_additive_settlement_record),physical_neighbors_are_county_proof=(x.region_norm!='амурская')))
pd.DataFrame(rows).to_csv(Z/'reopened_target_native_source_rows.csv.gz',index=False,compression={'method':'gzip','mtime':0});pd.DataFrame(articles).to_csv(Z/'own_article_literal_source_claims.csv.gz',index=False,compression={'method':'gzip','mtime':0})
# Current OWN typed provider/code proof. Keep all same-name/type rivals rather than selecting nearest.
rf=Path('/workspace/settlements-raw/data/interim/2021_tochno/data_allsettlements_anon_156_v20251217.parquet');raw=pd.read_parquet(rf);ni=[148581,148583,60719,144624,60669,60932];cc=['object_level','object_name','oktmo','region','mun_upper','mun_lower','population','settlement_dadata','settlement_type_full_dadata','fias_level_dadata','oktmo_dadata','okato_dadata','latitude_dadata','longitude_dadata'];rv=raw.iloc[[n-1 for n in ni]][cc].copy();rv.insert(0,'native2021_source_row_1based',ni);rv.to_json(Z/'current_OWN_provider_literal_properties.json',orient='records',force_ascii=False)
# Proved v3 wrong claim plus distinct current Zeysky point, not a defective owncurrent coordinate.
ve=pd.read_csv(B/'version3/accepted_identity_edge_delta.csv');vr=ve[ve.from_source_record_id.eq(niko)&ve.to_source_record_id.eq(cur(60932))];assert len(vr)==1;vr=vr.copy();vr['review_status']='reviewed_rejected_candidate_identity_claim_only';vr['review_reason']='actualprimary originalorder literalBureysky/Novobureysky header contradictsZeysky; currentZeysky already hasdifferentproper02Nik33';vr['candidate_ledger_sha256']=sha(B/'version3/accepted_identity_edge_delta.csv');vr.to_csv(Z/'reviewed_v3_Nikolaevka_candidate_rejection.csv',index=False)
proof=pd.read_csv(Z/'Amur_original_order_primary_county_proof.csv');assert 'Бурейский' in proof[proof.physical_row_1based.eq(154)].literal_own_header_path_json.iloc[0];assert 'Березовский сельсовет' in proof[proof.physical_row_1based.eq(203)].literal_own_header_path_json.iloc[0]
claims=[dict(case='old ruralSubkh386',verdict='positive old02→Old10/21 physicalrename identity AFTER specificbaselinewrongedge+point rejection',source02_route='published rural properNP386 atNurkeevsky sourceparish; notPGT5663; 2008renameGov60 +2008parishtransfertoSubkh retained',point_route='ownOldarticlecode80251861003/currentownnative80651461111; current148583OWNpoint; do notreuse148581largepoint',strict_population_value_rewrite=False),dict(case='PGTSubkh5663/highmassordinary',verdict='positive properPGT02→large10/21 after wrongruralremoved; statuschange2006 isnotphysicalidentity rejection',source02_route='officialurban2002typedPGT5663 independentofrural386; ownarticlefounded1946PGT convertedVillage2006',point_route='ownarticlecode80251861001/currentown80651461101; current148581OWNpoint; nooldruralpointassignment',strict_population_value_rewrite=False),dict(case='Nikolaevka1092',verdict='rejectZeyskyclaim; literalprimaryBUREYAheaders permit correctedsourcepositivecandidate60669, to be builtbyowner',source02_route='sortbyactualoriginalsourceindex196 under194Bureyskydistrict and195Novobureyskysubordinates; originalnumericindexNOTclassifiercode',point_route='currentZeysky60932point independentOWNZeysky remains validfor33lineage, not1092; correctedcurrent60669ownBureya code10515000106/rawFIAS6 point',strict_population_value_rewrite=False),dict(case='Berezovka3593/highmassordinary',verdict='positive ownIvanovcounty typedSelo across02/10/21; rawphysicalflankargument replacedbyactualoriginalorderliteralprimaryheaders',source02_route='physical203/original338 directlyunder337Berezovskyselsovet,329Ivanovskyruralcouncils; ownarticlePgt1981–1991 predatescensus02',point_route='current60719 ownnative10528000121/rawFIAS6; ownArticlephysicalcoordinates0.60km; excludesownZeyskyBerezovka',strict_population_value_rewrite=False),dict(case='Urgaza2902/highmassordinary',verdict='positive sourceownformerCentralEstate typedNP→Urgaza rename2007, nofactory/municipalitypoint',source02_route='raw02properCentralEstateZilairSovkhoz publishedNP2902 ownBaymakcounty; ownarticlequotedGov5722007renamesexistingSelo',point_route='current144624ownnative80606413101 properSelo/sourceowntypedcurrent; fullrawownpoint and ownarticle supported',strict_population_value_rewrite=False)]
pd.DataFrame(claims).to_csv(Z/'specific_source_claim_crosscheck.csv',index=False)
r=dict(status='FROZEN_INDEPENDENT_SPECIFIC_SOURCE_CHECK',no_State_load=True,no_national_replay=True,no_shared_or_other_agent_changes=True,Subkh_old_rural_and_oldPGT_grains_bothproper=True,Subkh_baselinewrongedge_rejection_REQUIRED=br['decision_id'],Subkh_old_rural_wrongcarrierpoint_rejection_REQUIRED=True,Nikolaevka1092_Zeysky_REJECTED=True,Nikolaevka1092_actual_primary_county='Бурейский',three_highmass_ordinary_checks=['PGTSubkh5663','Berezovka3593','Urgaza2902'],primarysourcepopquality_unchanged=True,sourceproof_paths=['Amur_original_order_primary_county_proof.csv','reopened_target_native_source_rows.csv.gz','own_article_literal_source_claims.csv.gz'],no_coordinate_accuracy_from_population_or_proximity_asserted=True,input_pins={str(f):dict(sha256=sha(f),bytes=f.stat().st_size) for f in [A/'applied_state_observations.parquet',A/'applied_point_snapshot.parquet',B/'version3/accepted_identity_edge_delta.csv',B/'version3/accepted_point_use_delta.csv',ledger]});(Z/'verification_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2));files={f.name:dict(sha256=sha(f),bytes=f.stat().st_size) for f in sorted(Z.iterdir()) if f.is_file() and f.name!='manifest.json'};(Z/'manifest.json').write_text(json.dumps(dict(status='FROZEN',files=files),ensure_ascii=False,indent=2));print('FROZEN',sha(Z/'manifest.json'),'BYTES',sum(x['bytes'] for x in files.values()))
