from pathlib import Path
import pandas as pd,duckdb,json,gzip,hashlib,xlrd
E=Path('/workspace/russian-settlements-research/research_rebuild/evidence');O=Path(__file__).parent;B=E/'main_axis_residual_application68_20261008';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
source=O/'live_exact_semkhoz_kerva.json.gz';pages=json.load(gzip.open(source,'rt'))['query']['pages'];pages={p['title']:p for p in pages.values()};state=B/'applied_state_observations.parquet';conn=duckdb.connect();d=conn.execute("select * from read_parquet(?) where region_norm='московская' and name_norm in ('семхоз','керва','сергиев посад','шатура')",[str(state)]).fetchdf();pt=conn.execute("select * from read_parquet(?) where target_source_record_id in (select unnest(?))",[str(B/'applied_point_snapshot.parquet'),d.source_record_id.tolist()]).fetchdf().set_index('target_source_record_id');conn.close();remaining=pd.read_csv(B/'applied_remaining_primary.csv.gz');credited=pd.read_csv(B/'applied_primary_credited_UID_roster.csv.gz');rawfile=Path('/workspace/settlements-raw/data/raw/2002_official_tom1/1_TOM_01_04.xls');rawsheet=xlrd.open_workbook(str(rawfile)).sheet_by_index(0)
pins={str(p):sha(p)for p in [source,state,B/'applied_point_snapshot.parquet',B/'applied_remaining_primary.csv.gz',B/'applied_primary_credited_UID_roster.csv.gz',rawfile]};obs=[];points=[];events=[];edges=[];credits=[];contexts=[];raws=[];excerpts=[];statuses=[]
for name,parent,rowno in [('Семхоз','Сергиев Посад',1324),('Керва','Шатура',1391)]:
 sid=f'2002:1_TOM_01_04.xls:0:{rowno}';old=d[d.source_record_id.eq(sid)].iloc[0];assert sid in set(remaining.source_record_id) and sid not in set(credited.source_record_id);vals=rawsheet.row_values(rowno-1);assert vals[1]==old.population and name in vals[0] and 'пгт'in vals[0];pg=pages[name];rev=pg['revisions'][0];txt=rev['slots']['main'].get('content',rev['slots']['main'].get('*',''));co=pg['coordinates'];assert len(co)==1;lat,lon=co[0]['lat'],co[0]['lon'];loc=f'page{pg["pageid"]}:revision{rev["revid"]}';lines=[{'line':i,'text':l}for i,l in enumerate(txt.splitlines(),1)if '2004'in l and ('включ'in l or 'присоедин'in l)];assert lines and any(parent in q['text']or(parent=='Шатура'and'Шатур'in q['text'])for q in lines);cg=d[d.name_norm.eq(parent.lower())&d.type_norm.eq('город')];assert len(cg)==3 and set(cg.census_year)=={2002,2010,2021}and cg.root.nunique()==1 and all(x in pt.index for x in cg.source_record_id) and set(cg.source_record_id)<=set(credited.source_record_id);cur=cg[cg.census_year.eq(2021)].iloc[0];scope='next69_included_'+name.lower();pop=int(old.population)
 obs.append(dict(scope_id=scope,place=name,year=2002,source_record_id=sid,native_population=pop,native_population_quality=old.population_value_quality,latitude=lat,longitude=lon,own_point=True,recipient_city=parent,event_date='2004',event_date_precision='year',event_relation='included_in',same_place_identity_asserted=False,receiving_city_2021_source_record_id=cur.source_record_id,receiving_city_2021_count_context_only=int(cur.population),child_2021_population_assigned=False,is_additive_to_original_final_mixed_census_axis=False,already_in_baseline68_primary_native_ID_union=False,new_native_population_if_event_admitted=pop,whole_city_roster_closure_asserted=False,population_boundary_comparability_asserted=False,native_values_quality_preserved=True))
 points.append(dict(scope_id=scope,target_source_record_id=sid,source_record_id=sid,latitude=lat,longitude=lon,coordinate_admission_status='reviewed_rule_accepted',decision_status='reviewed_rule_accepted',coordinate_source_record_id=loc+':coordinates[0]',source_sha256=sha(source),source_locator=loc+':coordinates[0]',point_origin_file=str(source),point_origin_sha256=sha(source),point_origin_locator=loc+':coordinates[0]',point_origin_kind='own_named_former_NP_Wikipedia_physical_reference_point',own_locality_point=True,recipient_point_assigned_to_child=False,new_ordinary_point_use_proposed=True,point_temporal_interpretation='Current physical ownformerNP article point used retrospectively for native2002; not direct censusday measurement',direct_historical_coordinate_measurement=False,provider_binding_asserted=False,boundary_comparability_asserted=False))
 events.append(dict(scope_id=scope,former_locality=name,recipient_city=parent,event_date='2004',date_precision='year',relation='included_in',same_place=False,event_source_file=str(source),event_source_sha256=sha(source),event_source_locator=loc,event_source_quality='secondary_own_Wikipedia_literal_dated_inclusion',event_date_role='literal2004 ownNP inclusion year; Kerva cited29September2004 actdate not promoted to operative day',decision_status='accepted_secondary_own_article_included_in',primary_law_source_reopened=False,boundary_comparability='UNKNOWN',roster_closed=False,sum_city_equals_children_asserted=False))
 edges.append(dict(scope_id=scope,from_source_record_id=sid,to_source_record_id=cur.source_record_id,relation='included_in',event_date='2004',date_precision='year',event_source_file=str(source),event_source_sha256=sha(source),event_source_locator=loc,same_place=False,graph_union_allowed=False,whole_city_roster_closure_asserted=False,modern_boundary_reconstruction=False))
 credits.append(dict(scope_id=scope,source_record_id=sid,year=2002,source_population=pop,new_population_on_separate_transformation_path_axis=pop,own_historical_point_verified=True,receiving_city_actual_2002_2010_2021_context_verified=True,is_additive_to_original_final_mixed_census_axis=False,ordinary_three_census_same_place_claim=False))
 raws.append(dict(source_record_id=sid,year=2002,native_population=pop,native_quality=old.population_value_quality,source_path=str(rawfile),source_sha256=sha(rawfile),source_locator=f'worksheet0;Excelrow={rowno};populationcolumn=B;namecolumn=A',raw_cells_json=json.dumps(vals[:4],ensure_ascii=False),matches_native_population=True));excerpts.append(dict(scope_id=scope,source_path=str(source),source_sha256=sha(source),source_locator=loc,literal_excerpts_json=json.dumps(lines,ensure_ascii=False)))
 for y in [2002,2010,2021]:statuses.append(dict(scope_id=scope,place=name,year=y,status='actual_separate_own_published_observation'if y==2002 else'ceased_as_separate_locality_included_in_recipient_before_census',own_population=pop if y==2002 else'',unknown_is_zero=False,recipient_population_assigned_to_child=False,boundary_comparability='UNKNOWN'))
 for cr in cg.itertuples():
  cp=pt.loc[cr.source_record_id];contexts.append(dict(scope_id=scope,recipient_city=parent,census_year=cr.census_year,source_record_id=cr.source_record_id,population=cr.population,population_value_quality=cr.population_value_quality,latitude=cp.latitude,longitude=cp.longitude,point_ledger_path=str(B/'applied_point_snapshot.parquet'),is_receiving_city_context_only=True,new_national_credit_population=0,child_count_substituted=False,already_in_baseline68_primary_credit=True))
for n,a in [('accepted_historical_observations.csv',obs),('accepted_former_locality_own_points.csv',points),('accepted_inclusion_events.csv',events),('accepted_included_in_event_edges.csv',edges),('accepted_direct_event_native_credit_union.csv',credits),('actual_receiving_city_three_census_context.csv',contexts),('native_raw_row_witnesses.csv',raws),('literal_own_inclusion_source_excerpts.csv',excerpts),('accepted_available_year_statuses.csv',statuses)]:pd.DataFrame(a).to_csv(O/n,index=False)
rec=dict(status='reviewed_two_actual68_remaining_old_NP_direct_inclusions_root_replay_pending',baseline_stage=68,accepted_event_cases=2,distinct_remaining_native_UIDs=2,conditional_new_UID_population_by_year={'2002':5669,'2010':0,'2021':0},receiving_city_context_UIDs=6,receiving_city_new_credit=0,new_retrospective_own_points=2,ordinary_same_place_edges_added=0,unknown_population_imputed=False,primary_acts_reopened=False,boundary_comparability='UNKNOWN',input_pins=pins,output_pins={p.name:sha(p)for p in O.glob('*.csv')});(O/'ready_two_packet_receipt.json').write_text(json.dumps(rec,ensure_ascii=False,indent=2));assert sum(p.stat().st_size for p in O.iterdir()if p.is_file())<5_000_000;print(json.dumps({k:v for k,v in rec.items()if k!='input_pins'and k!='output_pins'}))
