from pathlib import Path
import pandas as pd,json,gzip,hashlib
E=Path('/workspace/russian-settlements-research/research_rebuild/evidence');O=Path(__file__).parent;BASE=E/'main_axis_residual_application68_20261008';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
r=pd.read_csv(O/'stage68_actual_remaining_primary.csv.gz');credited=pd.read_csv(BASE/'applied_primary_credited_UID_roster.csv.gz');assert r.source_record_id.is_unique and not set(r.source_record_id)&set(credited.source_record_id)
old=r[r.census_year.isin([2002,2010])].sort_values('population',ascending=False).head(100).copy();prior=pd.read_csv(E/'mass_lifecycle_cached_residual_20261008/bounded_mass500_source_dispositions.csv');pm=prior.set_index('source_record_id');sourceholds=pd.read_csv(E/'remaining_large_lifecycle_residual_20261008/held_targets.csv');sm={a.place:a.reason for a in sourceholds.itertuples()};rows=[]
for z in old.itertuples():
 if z.settlement_name in sm:reason=sm[z.settlement_name]
 elif z.source_record_id in pm.index:reason=str(pm.loc[z.source_record_id,'reason'])
 else:reason='No existing independently bound own-NP dated absorption/rename event source available in inspected bounded caches. Current/municipal captions or source absence do not establish a terminal locality event.'
 rows.append({'source_record_id':z.source_record_id,'census_year':z.census_year,'settlement_name':z.settlement_name,'settlement_type':z.settlement_type,'region_norm':z.region_norm,'district_raw':z.district_raw,'population':z.population,'native_quality':z.population_value_quality,'component_years':z.component_years,'has_own_point':z.has_own_point,'status':'held_no_complete_new_source_pinned_lifecycle_case','reason':reason,'actual_stage68_primary_UID_uncredited':True,'new_credit_population':0})
pd.DataFrame(rows).to_csv(O/'bounded_actual68_event_holds.csv',index=False)
x=json.load(gzip.open(O/'region_point_compatible_cache_candidates.json.gz','rt'));holds=[]
for q in x:
 if q['title']=='Красный Октябрь (Киржачский район)':reason='Own article is accepted Kirzhach former pgt10323; residual native2002 row3091217 and native2010 942 are other same-region homonym. Region/name match alone cannot bind receiving city.'
 elif q['title']=='Садовый (Минераловодский район)':reason='1915 rename precedes the census series; 2015 abolition concerns municipal council. No own-NP dated disappearance or rename within target interval.'
 elif q['title']=='Старые Турбаслы':reason='Administrative 1996 transfer predates historical2002 observation; source does not establish cessation of separately observed NP. Own counts persist through2021.'
 else:reason='Centralny own NP persists in2010 and2021. Municipal/admin context wording is not a documented own-NP absorption or rename resolving missing2002.'
 holds.append({'source_record_id':q['source_record_id'],'year':q['census_year'],'population':q['population'],'title':q['title'],'source_path':q['sourcepath'],'source_sha256':q['sha256'],'source_locator':f"page{q['pageid']}:revision{q['revision']}",'reason':reason,'new_credit':0})
pd.DataFrame(holds).to_csv(O/'literal_cached_positive_keyword_holds.csv',index=False)
pins={str(p):sha(p)for p in [BASE/'application_receipt.json',BASE/'applied_remaining_primary.csv.gz',BASE/'applied_primary_credited_UID_roster.csv.gz',BASE/'applied_state_observations.parquet',E/'mass_lifecycle_cached_residual_20261008/final_packet_receipt.json',E/'mass_lifecycle_cached_residual_20261008/bounded_mass500_source_dispositions.csv',E/'remaining_large_lifecycle_residual_20261008/held_targets.csv']}
for q in x:pins[q['sourcepath']]=sha(Path(q['sourcepath']))
(O/'input_pins.json').write_text(json.dumps(pins,ensure_ascii=False,indent=2))
rec={'status':'bounded_actual68_cached_lifecycle_screen_complete_explicit_holds_no_new_admission','baseline_stage':68,'priority_native_UIDs':len(old),'priority_native_population_by_year':{str(y):int(g.population.sum())for y,g in old.groupby('census_year')},'cache_API_file_inventory':len(set(Path('/tmp/next69_cached_paths').read_text().splitlines()+Path('/tmp/next69_extra_cached_paths').read_text().splitlines())),'literal_keyword_name_hits':122,'region_intro_and_ownpoint_compatible_hits':len(x),'distinct_compatible_titles':len(set(q['title']for q in x)),'new_ready_events':0,'new_ordinary_edges':0,'new_point_uses':0,'incremental_primary_UID_population_by_year':{'2002':0,'2010':0,'2021':0},'admitted_previous_transformations_repeated':False,'new_network_requests':0,'source_population_or_quality_changes':False,'fake_successor_or_child2021_counts':False,'whole_city_modern_boundary_sums':False,'source_scope_limit':'Reuse earlier bounded3300rawarticle cache screen only via frozen extracted/source-pinned records; additional26ownAPIcached files checked against actual68 residual IDs. No repeated bulk raw archive scan. Point/node existence and municipal transitions do not supply absent lifecycle evidence.'}
(O/'receipt.json').write_text(json.dumps(rec,ensure_ascii=False,indent=2));files=[{'path':str(p),'sha256':sha(p),'bytes':p.stat().st_size}for p in O.iterdir()if p.is_file()and p.name!='manifest.json'];(O/'manifest.json').write_text(json.dumps({'files':files,'total_bytes':sum(z['bytes']for z in files)},ensure_ascii=False,indent=2));print(json.dumps(rec,ensure_ascii=False));print('bytes',sum(z['bytes']for z in files))
