from pathlib import Path
import json,hashlib,pandas as pd,sys,math
R=Path('/workspace/russian-settlements-research');E=R/'research_rebuild/evidence';I=E/'additional_large_city_scope_mass_20261008';O=Path(__file__).parent;sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from working_state_20261007 import load
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
candidate=json.loads((I/'candidate_receipt.json').read_text());assert candidate['triplets']==48 and candidate['edges']==candidate['point_uses']==90 and candidate['frozen_review_packet']
for p,h in candidate['outputs'].items():assert sha(I/p)==h
for p,h in candidate['source_manifest'].items():assert sha(p)==h
edge=pd.read_csv(I/'candidate_identity_edge_delta.csv',keep_default_na=False);edge['decision_status']='checked_rule_accepted';assert edge.relation.eq('same_place').all();edge['coordinate_application_family']='auto_rule';edge['application_inference_kind']='inferred_continuity';edge.to_csv(O/'accepted_identity_edge_delta.csv',index=False)
point=pd.read_csv(I/'candidate_point_use_delta.csv',keep_default_na=False);point['coordinate_admission_status']='reviewed_extension_rule_accepted';point['coordinate_application_family']='auto_rule';point['application_inference_kind']='inferred_continuity';point['coordinate_quality']='independently_admitted_current_own_NP_point_source_bound_individual_continuity';point['direct_historical_coordinate_measurement']=False;point['coordinate_measurement_date_unknown']=True;point['modern_boundary_harmonized']=False;point['current_own_point_source_ledger']=point.point_ledger_path;point.to_csv(O/'accepted_point_use_delta.csv',index=False)
print('deltasfrozen; loadstage30',flush=True);s=load(stage=30)
# Strict ordinary series, exactly one selected individual NP per year, all three ownpoint uses and finite native populations.
def strict_ids(state):
 f=state.obs.copy();f['root']=f.source_record_id.map(state.uf.find);f['ownpoint']=f.source_record_id.isin(state.point_rows);f['finite']=f.population.map(lambda x:pd.notna(x) and math.isfinite(float(x)));g=f.groupby('root').agg(n=('source_record_id','size'),years=('census_year','nunique'),ownpoint=('ownpoint','all'),finite=('finite','all'));roots=set(g.index[(g.n==3)&(g.years==3)&g.ownpoint&g.finite]);return set(f.loc[f.root.isin(roots),'source_record_id'])
scopes=set()
for name in ['complete_publisher_partition_members.csv','qualified_scope_source_id_credit_union.csv','named_merger_lineage_constituents.csv']:scopes.update(pd.read_csv(E/'working_full_chain_20261007'/name).source_record_id)
for folder in ['large_absorbed_city_closed_scope_application_20261008','remaining_absorbed_city_published_closures_application_20261008','nakhoda_complete_published_scope_aux5_application_20261008','city_territory_mass_followup_application_20261008','city_territory_mass_final_two_application_20261008']:scopes.update(pd.read_csv(E/folder/'accepted_constituent_credit_union.csv').source_record_id)
for folder in ['complete_transferred_municipal_scope_application_20261008','moscow_complete_scope_mass_application_20261008']:scopes.update(pd.read_csv(E/folder/'accepted_native_scope_constituents.csv').source_record_id)
trip=pd.read_csv(I/'individual_unique_three_year_candidates.csv',keep_default_na=False);before=strict_ids(s);before_union=before|scopes;baseline_inputs={str(p):sha(p) for p in s.inputs};before_weak=s.metrics()
for p in point.itertuples():
 current=s.point_rows[p.coordinate_source_record_id];assert (float(p.latitude),float(p.longitude))==(current['latitude'],current['longitude']);assert p.point_origin_file==current['point_origin_file'] and p.point_origin_sha256==current['point_origin_sha256'];assert sha(p.point_origin_file)==p.point_origin_sha256
s.add_deltas([O/'accepted_identity_edge_delta.csv'],[O/'accepted_point_use_delta.csv']);after=strict_ids(s);after_union=after|scopes;assert before<=after
proof=[];claimed=set()
for t in trip.itertuples():
 ids={t.id2002,t.id2010,t.id2021};claimed.update(ids);assert ids<=after and len({s.uf.find(z) for z in ids})==1
 rows=s.obs[s.obs.source_record_id.map(s.uf.find).eq(s.uf.find(t.id2021))];assert set(rows.source_record_id)==ids and len(rows)==3 and set(rows.census_year)=={2002,2010,2021};assert all(sid in s.point_rows for sid in ids);assert all(pd.notna(z) and math.isfinite(float(z)) for z in rows.population)
 for y,sid in [(2002,t.id2002),(2010,t.id2010),(2021,t.id2021)]:
  row=s.by_id.loc[sid];own=s.point_rows[sid];proof.append({'case':t.case,'county':t.county,'source_record_id':sid,'year':y,'native_population':int(row.population),'native_population_quality':row.population_value_quality,'exact_one_per_year_three_member_component':True,'ownpoint_admitted':True,'coordinate_application_family':own.get('coordinate_application_family','independently_existing_ownpoint'),'application_inference_kind':own.get('application_inference_kind','independently_existing_ownpoint'),'latitude':own['latitude'],'longitude':own['longitude'],'point_origin_file':own['point_origin_file'],'point_origin_sha256':own['point_origin_sha256'],'active_point_ledger':own['point_ledger_path'],'new_strict_id':sid not in before,'new_exclusive_mixed_union_id':sid not in before_union})
assert claimed<=after;new=after_union-before_union;assert new<=claimed
byyear={}
for y,g in s.obs.groupby('census_year'):
 y=int(y);b=g[g.source_record_id.isin(before_union)];a=g[g.source_record_id.isin(after_union)];n=g[g.source_record_id.isin(new)];byyear[y]={'exclusive_net_native_population_added':int(n.population.sum()),'new_unique_native_source_IDs':len(n),'strict_finite_all_three_ownpoint_union_before_population':int(b.population.sum()),'strict_finite_all_three_ownpoint_union_after_population':int(a.population.sum())}
pd.DataFrame(proof).to_csv(O/'actual_loader_replay_individual_strict_components.csv',index=False)
assert {y:z['exclusive_net_native_population_added'] for y,z in byyear.items()}=={2002:3770,2010:3931,2021:6039}
r={'status':'applied_sourcecounty_unique_homonym_rule','baseline_stage':30,'baseline_code_commit':'3e541e1','root_loader_integration_pending':True,'in_memory_actual_loader_replay_passed':True,'triplets':48,'exact_one_per_year_all_three_ownpoint_finite_triplets_after_actual_replay':48,'edges':len(edge),'point_uses':len(point),'coordinate_application_family':'auto_rule','application_inference_kind':'inferred_continuity','sourcecounty_uniqueness_not_global_regional_name_uniqueness':True,'all_regional_homonyms_enumerated_before_point_filter':True,'no_county_or_city_receiving_point_projected_to_childNP':True,'source_values_and_population_qualities_unchanged':True,'no_unknown_population_imputed':True,'by_year':byyear,'weak_metrics_before_for_diagnostics_only':before_weak,'weak_metrics_after_for_diagnostics_only':s.metrics(),'source_manifest':candidate['source_manifest'],'input_packet_sha256':{str(I/p):sha(I/p) for p in candidate['outputs']}|{str(I/'candidate_receipt.json'):sha(I/'candidate_receipt.json')},'baseline_loader_inputs_sha256_not_current_mutable_report_witnesses':baseline_inputs,'root_authorization':'Root explicitly approved48 individual sourcecounty-unique homonym ownNP triplets conditional actualstage30loader replay exactoneperyear/allownpoints/exclusive UIDnet; passed. No wholecounty representative points or aggregate target numerator credit.','outputs':{p.name:sha(p) for p in O.glob('*.csv')}};(O/'application_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n');(O/'README.md').write_text('Applied48 individual sourcecounty-unique homonym NP triples. Actual stage30 State.add_deltas replay passed: every merged component has exactly3selectedindividualNPobservations, one per2002/2010/2021, finite unmodified native values and3ownpoint uses. Exclusive mixed native UID population gains3770/3931/6039.90same_place edges checked_rule_accepted;90pointuses reviewed_extension_rule_accepted /auto_rule/inferred_continuity. Each current NP ownpoint was independently admitted before application; sourcefile/SHA/coordinates checked against existingpoint carrier. County context only; all regional homonym rivals remain in the unchanged candidate compressed sourcewitness. Unresolved rivals stay held. Candidate witness files untouched, applied semantic-status deltas written only here. Root integration pending separately; no shared loader/report/Git edits.\n');print(json.dumps({k:r[k] for k in ['status','triplets','edges','point_uses','by_year','root_loader_integration_pending']},ensure_ascii=False),flush=True)
