from pathlib import Path
import pandas as pd,json,hashlib,shutil
E=Path('/workspace/russian-settlements-research/research_rebuild/evidence');I=E/'next_absorbed_city_closed_scopes_20261008';O=Path(__file__).parent;sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();r=json.loads((I/'candidate_receipt.json').read_text());assert r['frozen_review_packet'] and r['baseline_loader_stage']==34
for name,h in r['outputs'].items():assert sha(I/name)==h
for path,h in r['source_manifest'].items():assert sha(path)==h
STATUS='applied_complete_published_city_territorial_scope';axis='published_complete_city_territory_scope'
config=[('candidate_group_observations.csv','accepted_group_observations.csv'),('candidate_constituent_credit_union.csv','accepted_constituent_credit_union.csv'),('candidate_representative_scope_points.csv','accepted_representative_scope_points.csv'),('candidate_scope_edges.csv','accepted_scope_edges.csv')]
for src,dst in config:
 d=pd.read_csv(I/src,keep_default_na=False);d['candidate_only']=False;d['decision_status']=STATUS;d['identity_axis']=axis;d['source_grain']='city_with_published_subordinates';d['boundary_comparability']='UNKNOWN';d['ordinary_same_place']=False;d['exact_annexation_roster_claimed']=False;d['legal_annexation_asserted']=False;d['historical_constituent_own_point_asserted']=False;d['historical_individual_point_asserted']=False
 if 'point_role' in d:d['point_role']='representative_scope'
 if 'scope_point_role' in d:d['scope_point_role']='representative_scope'
 if src=='candidate_group_observations.csv':
  assert d.group.nunique()==4 and len(d)==12
  for group,g in d.groupby('group'):assert set(g.census_year)=={2002,2010,2021} and g.roster_complete.all()
 if src=='candidate_constituent_credit_union.csv':
  assert len(d)==74 and d.source_record_id.is_unique and d.source_population_unmodified.all();d['additive_only_within_complete_published_year_group']=True;d['separate_population_credit_in_addition_to_group']=False
 if src=='candidate_representative_scope_points.csv':assert len(d)==4 and d.group.is_unique
 if src=='candidate_scope_edges.csv':assert len(d)==8;d['event_relations_effective_date']='UNKNOWN'
 d.to_csv(O/dst,index=False)
for name in ['printed_controls_atomic_conservation.csv','complete_scope_source_witnesses.csv','original_atomic_raw_row_bindings.csv','original2002_2010_complete_city_rural_block_closures.csv','original2010_primary_urban_override_witness.csv','net_source_ID_union_potential.csv']:
 shutil.copy(I/name,O/name);assert sha(O/name)==sha(I/name)
n=pd.read_csv(I/'net_source_ID_union_potential.csv');assert dict(n.groupby('year').new_native_population_if_scope_admitted.sum())=={2002:96593,2010:35734,2021:0};assert dict(n.groupby('year').unique_new_source_IDs.sum())=={2002:38,2010:20,2021:0}
o=pd.read_csv(O/'accepted_group_observations.csv',keep_default_na=False);m=pd.read_csv(O/'accepted_constituent_credit_union.csv',keep_default_na=False)
for z in o.itertuples():
 own=m[m.group.eq(z.group)&m.census_year.eq(z.census_year)];assert len(own)==z.constituent_count and int(own.population.sum())==int(z.population) and set(own.source_record_id)==set(json.loads(z.source_record_ids_json))
controls=pd.read_csv(O/'printed_controls_atomic_conservation.csv');assert controls[controls.year.isin([2002,2021])].difference_not_allocated.eq(0).all();assert controls[controls.year.eq(2010)].set_index('group').difference_not_allocated.to_dict()=={'published_closed_city_scope_Тюмень':9,'published_closed_city_scope_Волжский':0,'published_closed_city_scope_Новоалтайск':0,'published_closed_city_scope_Самара':2}
r.update(status=STATUS,candidate_only=False,identity_axis=axis,source_grain='city_with_published_subordinates',ordinary_graph_changed=False,ordinary_point_uses_changed=False,legal_annexation_asserted=False,point_role='representative_scope',historical_individual_point_asserted=False,root_loader_integration_pending=True,baseline_loader_stage=34,baseline34_net_not_future_report_witness=True,root_authorization='Root explicitly approved4 complete published sourceyear city-associated scopes on separate changing territorialtrace axis: Tyumen,Volzhsky,Novoaltaysk,Samara. No ordinarysameplace, exactlegalannexation, county representative projection or sourcepopulation edits. Existing selectedprimary2010Krasnooktyabrsky12834 retained as exact native source; protecteddifferences9Tyumen/2Samara retained unallocated.',input_packet_sha256={str(I/p):sha(I/p) for p in r['outputs']}|{str(I/'candidate_receipt.json'):sha(I/'candidate_receipt.json')})
r['net_gain_against_explicit_baseline34']=r.pop('net_gain_by_year');r['net_gain']=r['net_gain_against_explicit_baseline34'];r['outputs']={p.name:sha(p) for p in O.glob('*.csv')};r['code_sha256']={'apply.py':sha(O/'apply.py')};(O/'application_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n')
(O/'README.md').write_text('Applied4 complete published sourceyear city-associated scopes, separate territorialtrace axis: Tyumen/Volzhsky/Novoaltaysk/Samara.12observations74 nativeatomicrefs,4existing owncity representative_scope points,8territorial relations. Explicit actualloader34 baseline nativeUIDgain96593/35734/0; later integrated report recalculates exclusiveunion. Source controls and hierarchy witnesses copied byte-for-byte from frozen candidate;02/21parentcontrols exact;2010protected sourceyear deviations9Tyumen/2Samara unallocated. Direct selectedprimary Krasnooktyabrsky12834 matches original literal Volzhsky block327089; protectedalternative12741 preserved separately. No sourcepopulation/quality modification, ordinarysameplace, exactlegalannexation, modernboundary harmonization, historical individual childpoint or county point projection. Samara sourceyear territory trace doesnot assert legalannexation of Priбрежный. Root integration pending separately.\n');print(json.dumps({k:r[k] for k in ['status','groups','observations','atomic_members','net_gain_against_explicit_baseline34']},ensure_ascii=False))
