from pathlib import Path
import pandas as pd,json,gzip,hashlib,xlrd,duckdb
O=Path(__file__).parent;B=O.parent;sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();d=pd.read_parquet('/dev/shm/over500-moscow-after-homonyms.parquet');p=pd.concat([pd.read_parquet('/dev/shm/over500-moscow-points.parquet'),pd.read_csv(B/'accepted_point_use_delta.csv'),pd.read_csv(O/'accepted_point_use_delta.csv')],ignore_index=True).drop_duplicates('target_source_record_id',keep='last').set_index('target_source_record_id');edges=pd.read_csv(O/'accepted_identity_edge_delta.csv').to_dict('records');pts=pd.read_csv(O/'accepted_point_use_delta.csv').to_dict('records');proof=[]
pgs={}
for dr in [B,O]:
 for f in dr.glob('own_wikipedia_batch*.json.gz'):
  for pg in json.load(gzip.open(f,'rt'))['query']['pages'].values():
   if pg.get('coordinates'):pgs[pg['title']]=(pg,f)
raw2=Path('/workspace/settlements-raw/data/raw/2002/010_3e630cc803_02c_Moskovskaya-oblast.xls');raw10=Path('/workspace/settlements-raw/data/raw/2010/010_711691e352_2._20Kostrom_Kur_Lip_Moscow_MoscObl_Orlov_2010.xls');b2=xlrd.open_workbook(str(raw2)).sheet_by_index(0);b10=xlrd.open_workbook(str(raw10)).sheet_by_name('Data Sheet')
# Printed singular/plural alias disambiguated by own type and exact independently dated2002 ownpopulation witness, not by name stemming alone.
old=d[d.source_record_id.eq('2002:010_3e630cc803_02c_Moskovskaya-oblast.xls:Sheet1:6623')].iloc[0];cur=d[d.source_record_id.eq('2021:data_allsettlements_anon_156_v20251217.parquet:parquet:70929')].iloc[0];pg,f=pgs['Пустоши (Московская область)'];txt=pg['revisions'][0]['slots']['main']['*'];assert '46257834001'in txt;assert old.type_norm==cur.type_norm=='поселок';assert 'Пустошинский поселковый округ'in b2.cell_value(6621,1);assert int(old.population)==716;tf=B/'own_population_template_expansions.json.gz';tb=next(x for x in json.load(gzip.open(tf,'rt'))if x['title']=='Пустоши (Московская область)');assert '>716<'in tb['response']['expandtemplates']['wikitext'];full=d[d.after_root.isin([old.after_root,cur.after_root])];assert not full.census_year.duplicated().any();co=pg['coordinates'][0];loc=f'pageid={pg["pageid"]};revision={pg["revisions"][0]["revid"]}';case='moscow_Pustosha_poselok_literal_plural_alias'
edges.append(dict(from_source_record_id=old.source_record_id,to_source_record_id=cur.source_record_id,relation='same_place',decision_status='checked_rule_accepted',case=case,admission_rule='Literal native poselok singular/plural spelling variation; own exact original Pustoshinsky poselok context and independent ownarticle historicalcode46257834001 +dated2002population716; physical samecounty seloPustosha513 retained as different type/object; existing ownpoint2010-2021 continuity',source_binding_proof=str(O/'literal_alias_source_witnesses.json'),population_boundary_comparability_asserted=False,municipal_event_date='UNKNOWN'));pts.append(dict(target_source_record_id=old.source_record_id,latitude=co['lat'],longitude=co['lon'],coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_source_record_id='Wikipedia:page'+str(pg['pageid']),source_sha256=sha(f),source_locator=loc+':coordinates[0]',point_origin_file=str(f),point_origin_sha256=sha(f),point_origin_locator=loc+':coordinates[0]',point_origin_kind='own_Wikipedia_qualified_native_locality_representative_point',case=case,coordinate_binding_rule='Literal poselok source context+own historicalcode and own2002witness; seloPustosha different object excluded',point_use_inference='own_modern_representative_point_on_source_bound_native_identity',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,secondary_population_not_substituted_for_native=True));d.loc[d.after_root.eq(old.after_root),'after_root']=cur.after_root;proof.append(dict(case=case,source_path=str(f),source_sha256=sha(f),source_locator=loc,own_article=txt,own2002count_template_path=str(tf),own2002count_template_sha256=sha(tf),literal2002_rows=[(i+1,b2.row_values(i)[:5])for i in range(6618,6624)],source2002_path=str(raw2),source2002_sha256=sha(raw2)))
# Parser omitted a published ordinary locality because its type was slobodka, not a census-year gap.
sid='2010:010_711691e352_2._20Kostrom_Kur_Lip_Moscow_MoscObl_Orlov_2010.xls:Data Sheet:8364';assert sid not in set(d.source_record_id);vals=b10.row_values(8363);assert vals[3]=='слободка  Алёшино'and vals[4]==258;old=d[d.source_record_id.eq('2002:010_3e630cc803_02c_Moskovskaya-oblast.xls:Sheet1:368')].iloc[0];cur=d[d.source_record_id.eq('2021:data_allsettlements_anon_156_v20251217.parquet:parquet:65693')].iloc[0];assert old.population==235 and old.type_norm=='слободка';assert cur.settlement_name=='слободка Алёшино'and cur.population==514;assert old.derived_oldcounty==cur.derived_oldcounty=='Воскресенский район';assert cur.source_record_id in p.index;assert str(b2.cell_value(367,1)).strip()=='слободка Алёшино';pg,f=pgs['Алёшино (городской округ Воскресенск)'];txt=pg['revisions'][0]['slots']['main']['*'];loc=f'pageid={pg["pageid"]};revision={pg["revisions"][0]["revid"]}';cp=p.loc[cur.source_record_id];case='moscow_Aloshino_literal_slobodka_parser_omission';cols='source_record_id census_year settlement_name settlement_type name_norm type_norm region_norm district_raw population population_scope is_additive_settlement_record population_value_quality latitude longitude oktmo okato source_file source_path source_sha256 source_locator'.split();new=dict.fromkeys(cols,'');new.update(source_record_id=sid,census_year=2010,settlement_name='Алёшино',settlement_type='слободка',name_norm='алешино',type_norm='слободка',region_norm='московская',district_raw='',population=258,population_scope='ordinary_settlement',is_additive_settlement_record=True,population_value_quality='secondary_confidentiality_protected_value_exact_scope_unverified',source_file='data/raw/2010/'+raw10.name,source_path=str(raw10),source_sha256=sha(raw10),source_locator='Data Sheet:row8364;labelcol4;countcol5');pd.DataFrame([new],columns=cols).to_csv(O/'accepted_additional_observations_20col.csv',index=False);pd.DataFrame([dict(source_record_id=sid,source_admission_status='reviewed_published_ordinary_locality_parser_omission_accepted',source_grade='secondary_confidentiality_protected_compilation_of_2010_census',source_sheet='Data Sheet',source_row=8364,independent_official_primary_locality_count_verified=False,source_primary_grade=False,direct_official_primary_locality_value=False,primary_credit_from_source_alone=False,own_point_admitted=False,temporal_identity_admitted=False,source_population_modified=False)]).to_csv(O/'accepted_additional_observation_metadata.csv',index=False)
for ss in [old.source_record_id,sid]:
 edges.append(dict(from_source_record_id=ss,to_source_record_id=cur.source_record_id,relation='same_place',decision_status='checked_rule_accepted',case=case,admission_rule='Exact literal complete native type+name label slobodkaAloshino in2002/2010, carried as a complete name with generic typein2021; actual source county Voskresensk and ownarticle; published2010row258 recovered from parser omission, not missing-year invention',source_binding_proof=str(O/'literal_alias_source_witnesses.json'),population_boundary_comparability_asserted=False,municipal_event_date='UNKNOWN'));pts.append(dict(target_source_record_id=ss,latitude=cp.latitude,longitude=cp.longitude,coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_source_record_id=cur.source_record_id,source_sha256=cp.point_origin_sha256,source_locator=cp.point_origin_locator,point_origin_file=cp.point_origin_file,point_origin_sha256=cp.point_origin_sha256,point_origin_locator=cp.point_origin_locator,point_origin_kind=cp.point_origin_kind,case=case,coordinate_binding_rule='Exact complete native slobodka+Aloshino printed label within own original sourcecounty; accepted current ownpoint continuity',point_use_inference='own_modern_representative_point_on_source_bound_native_identity',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,secondary_population_not_substituted_for_native=True))
proof.append(dict(case=case,source2002_file=str(raw2),source2002_sha256=sha(raw2),source2002_locator='Sheet1:row368',source2002_raw=b2.row_values(367)[:8],source2010_file=str(raw10),source2010_sha256=sha(raw10),source2010_locator='Data Sheet:row8364',source2010_raw=vals[:8],source2010_native_bracket=[(i+1,b10.row_values(i)[:8])for i in range(8359,8368)],source2010_absent_in_baseline71=True,source2010_published_value_preserved=258,source2010_grade_preserved_as_secondary_protected=True,own_article_path=str(f),own_article_sha256=sha(f),own_article_locator=loc,own_article_text=txt))
d.loc[d.after_root.eq(old.after_root),'after_root']=cur.after_root;rr=new.copy();rr.update(latitude=float('nan'),longitude=float('nan'));rr.update(root=sid,after_root=cur.after_root,derived_oldcounty='Воскресенский район');d=pd.concat([d,pd.DataFrame([rr])],ignore_index=True);d.to_parquet('/dev/shm/over500-moscow-after-aliases.parquet',index=False);pd.DataFrame(edges).drop_duplicates(['from_source_record_id','to_source_record_id']).to_csv(O/'accepted_identity_edge_delta.csv',index=False);pd.DataFrame(pts).drop_duplicates('target_source_record_id',keep='last').to_csv(O/'accepted_point_use_delta.csv',index=False);(O/'literal_alias_source_witnesses.json').write_text(json.dumps(proof,ensure_ascii=False,indent=2));print('newsourceobs1 pop258, aliases2, addededges3 andpoints3')
