from pathlib import Path
import pandas as pd,json,gzip,hashlib,xlrd
O=Path(__file__).parent;B=O.parent;sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();d=pd.read_parquet('/dev/shm/over500-moscow-after-correction.parquet');p=pd.concat([pd.read_parquet('/dev/shm/over500-moscow-points.parquet'),pd.read_csv(B/'accepted_point_use_delta.csv')],ignore_index=True).drop_duplicates('target_source_record_id',keep='last').set_index('target_source_record_id');pgs={}
for dr in [B,B.parent/'over1000_moscow_20261009']:
 for f in dr.glob('own_wikipedia_batch*.json.gz'):
  for pg in json.load(gzip.open(f,'rt'))['query']['pages'].values():
   if 'missing'not in pg:pgs[pg['title']]=(pg,f)
# Dates preserve secondary wording/act-date precision; no statutory operative-date claim.
configs=[('Новая Деревня (Пушкинский район)','новая деревня','Пушкинский район','пушкино','2003-07-31','31.07.2003'),('Новая (Балашиха)','новая','Балашихинский район','балашиха','2003-06-10','10 июня 2003'),('Порохово (Волоколамск)','порохово','Волоколамский район','волоколамск','2003','2003 года'),('Данилково (городской округ Мытищи)','данилково','Мытищинский район','федоскино','2015-09-09','9 сентября 2015'),('Посёлок ОПХ «Толстопальцево»','опытного производственного хозяйства толстопальцево','Наро-Фоминский район','марушкино','2004-05-17','17.05.2004'),('Посёлок Тучковского автодорожного техникума','тучковского автодорожного техникума','Рузский район','тучково','2003-11-13','13.11.2003'),('Посёлок совхоза «Орешково»','совхоза орешково','Луховицкий район','орешково','2011-03-22','22.03.2011')]
rows={n:[]for n in ['accepted_point_use_delta.csv','accepted_identity_edge_delta.csv','accepted_historical_observations.csv','accepted_former_locality_own_points.csv','accepted_inclusion_events.csv','accepted_included_in_event_edges.csv','accepted_direct_event_native_credit_union.csv','actual_receiving_city_three_census_context.csv','event_native_raw_row_witnesses.csv','literal_own_inclusion_source_excerpts.csv','accepted_available_year_statuses.csv']};b2=Path('/workspace/settlements-raw/data/raw/2002/010_3e630cc803_02c_Moskovskaya-oblast.xls');b10=Path('/workspace/settlements-raw/data/raw/2010/010_711691e352_2._20Kostrom_Kur_Lip_Moscow_MoscObl_Orlov_2010.xls');books={2002:xlrd.open_workbook(str(b2)).sheet_by_index(0),2010:xlrd.open_workbook(str(b10)).sheet_by_name('Data Sheet')}
for title,name,county,recipient,date,term in configs:
 pg,f=pgs[title];txt=pg['revisions'][0]['slots']['main']['*'];assert term in txt,(title,term);co=pg['coordinates'][0];loc=f'pageid={pg["pageid"]};revision={pg["revisions"][0]["revid"]}';scope='over500_moscow_event_'+str(pg['pageid']);old=d[d.name_norm.eq(name)&d.derived_oldcounty.eq(county)&d.census_year.lt(2021)];assert len(old)>0 and not old.census_year.duplicated().any();cg=d[d.name_norm.eq(recipient)].copy();cg=cg[cg.derived_oldcounty.eq(county)]if len(cg[cg.census_year.eq(2021)])>1 else cg;cur=cg[cg.census_year.eq(2021)];cur=cur.iloc[0]if len(cur)==1 else cg.sort_values('census_year').iloc[-1];receiver=cur.source_record_id;cg=d[d.after_root.eq(cur.after_root)];precision='day'if len(date)==10 else'year';lines=[dict(line=i,text=l)for i,l in enumerate(txt.splitlines(),1)if term in l or'объедин'in l or'Включён'in l or'Включена'in l];rows['literal_own_inclusion_source_excerpts.csv'].append(dict(scope_id=scope,source_path=str(f),source_sha256=sha(f),source_locator=loc,literal_excerpts_json=json.dumps(lines,ensure_ascii=False)));rows['accepted_inclusion_events.csv'].append(dict(scope_id=scope,former_locality=title,recipient_city=cur.settlement_name,receiving_NP_type=cur.settlement_type,event_date=date,date_precision=precision,relation='merged_into'if recipient=='орешково'else'included_in',same_place=False,event_source_file=str(f),event_source_sha256=sha(f),event_source_locator=loc,event_source_quality='secondary_literal_dated_former_NP_inclusion_own_article',event_date_role='Literal inclusion or cited act date; no exact operative-date promotion',decision_status='accepted_secondary_article_included_in',primary_law_source_reopened=False,boundary_comparability='UNKNOWN',roster_closed=False,sum_city_equals_children_asserted=False))
 for r in old.itertuples():
  pop=int(r.population);sid=r.source_record_id
  point=dict(scope_id=scope,target_source_record_id=sid,source_record_id=sid,latitude=co['lat'],longitude=co['lon'],coordinate_admission_status='reviewed_extension_rule_accepted',decision_status='reviewed_rule_accepted',coordinate_source_record_id='Wikipedia:page'+str(pg['pageid']),source_sha256=sha(f),source_locator=loc+':coordinates[0]',point_origin_file=str(f),point_origin_sha256=sha(f),point_origin_locator=loc+':coordinates[0]',point_origin_kind='own_named_former_NP_Wikipedia_physical_reference_point',own_locality_point=True,recipient_point_assigned_to_child=False,new_ordinary_point_use_proposed=sid not in p.index,point_temporal_interpretation='Independent retained ownformerNP physical reference point used retrospectively; no censusday directcoordinate claim',direct_historical_coordinate_measurement=False,provider_binding_asserted=False,boundary_comparability_asserted=False)
  rows['accepted_former_locality_own_points.csv'].append(point)
  if sid not in p.index:rows['accepted_point_use_delta.csv'].append(point)
  rows['accepted_historical_observations.csv'].append(dict(scope_id=scope,place=r.settlement_name,year=r.census_year,source_record_id=sid,native_population=pop,native_population_quality=r.population_value_quality,latitude=co['lat'],longitude=co['lon'],own_point=True,recipient_city=cur.settlement_name,receiving_NP_actual_type=cur.settlement_type,event_date=date,event_date_precision=precision,event_relation='included_in',same_place_identity_asserted=False,receiving_city_2021_source_record_id=receiver if cur.census_year==2021 else'',receiving_city_2021_count_context_only=int(cur.population)if cur.census_year==2021 else'',child_2021_population_assigned=False,is_additive_to_original_final_mixed_census_axis=False,ordinary_three_census_same_place_claim=False,population_boundary_comparability_asserted=False,native_values_quality_preserved=True))
  rows['accepted_included_in_event_edges.csv'].append(dict(scope_id=scope,from_source_record_id=sid,to_source_record_id=receiver,relation='merged_into'if recipient=='орешково'else'included_in',event_date=date,date_precision=precision,event_source_file=str(f),event_source_sha256=sha(f),event_source_locator=loc,same_place=False,graph_union_allowed=False,whole_city_roster_closure_asserted=False,modern_boundary_reconstruction=False))
  rows['accepted_direct_event_native_credit_union.csv'].append(dict(scope_id=scope,source_record_id=sid,year=r.census_year,source_population=pop,new_population_on_separate_transformation_path_axis=pop,own_historical_point_verified=True,receiving_city_actual_available_census_context_verified=True,is_additive_to_original_final_mixed_census_axis=False,ordinary_three_census_same_place_claim=False))
  n=int(sid.rsplit(':',1)[-1]);vals=books[r.census_year].row_values(n-1);assert any(str(v).replace('.0','')==str(pop)for v in vals);sf=b2 if r.census_year==2002 else b10;rows['event_native_raw_row_witnesses.csv'].append(dict(source_record_id=sid,year=r.census_year,native_population=pop,native_quality=r.population_value_quality,source_path=str(sf),source_sha256=sha(sf),source_locator=f'{books[r.census_year].name}:row{n}',raw_cells_json=json.dumps(vals[:8],ensure_ascii=False),matches_native_population=True))
 if len(old)==2 and old.after_root.nunique()==2:
  z=old.sort_values('census_year');rows['accepted_identity_edge_delta.csv'].append(dict(from_source_record_id=z.iloc[0].source_record_id,to_source_record_id=z.iloc[-1].source_record_id,relation='same_place',decision_status='checked_rule_accepted',case=scope,admission_rule='Literal sourcebound own name/type and original native county; exact ownformerNP secondary lifecycle article and own point; two actual native observations before sourced inclusion',source_binding_proof=str(O/'event_native_raw_row_witnesses.csv')+';'+str(O/'literal_own_inclusion_source_excerpts.csv'),population_boundary_comparability_asserted=False,municipal_event_date=date))
 years=set(old.census_year)
 for y in [2002,2010,2021]:rows['accepted_available_year_statuses.csv'].append(dict(scope_id=scope,place=title,year=y,status='actual_separate_own_published_observation'if y in years else'ceased_as_separate_locality_included_in_recipient_before_census'if y>int(date[:4])else'UNKNOWN_missing_native_year_no_birth_or_disappearance_inferred',own_population=int(old[old.census_year.eq(y)].population.iloc[0])if y in years else'',unknown_is_zero=False,recipient_population_assigned_to_child=False,boundary_comparability='UNKNOWN'))
 for z in cg.itertuples():
  cp=p.loc[z.source_record_id]if z.source_record_id in p.index else None;rows['actual_receiving_city_three_census_context.csv'].append(dict(scope_id=scope,recipient_city=cur.settlement_name,receiving_NP_actual_type=z.settlement_type,census_year=z.census_year,source_record_id=z.source_record_id,population=z.population,population_value_quality=z.population_value_quality,latitude=cp.latitude if cp is not None else'',longitude=cp.longitude if cp is not None else'',is_receiving_city_context_only=True,new_national_credit_population=0,child_count_substituted=False))
for n,v in rows.items():
 if v:pd.DataFrame(v).to_csv(O/n,index=False)
print({n:len(v)for n,v in rows.items()})
