from pathlib import Path
import pandas as pd,json,hashlib
O=Path(__file__).parent;B=O.parent;sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();d=pd.read_parquet('/dev/shm/over500-moscow-observations.parquet');new=pd.read_csv(O/'accepted_additional_observations_20col.csv');new['root']=new.source_record_id;d=pd.concat([d,new],ignore_index=True);split_sid='2010:010_711691e352_2._20Kostrom_Kur_Lip_Moscow_MoscObl_Orlov_2010.xls:Data Sheet:11157';d.loc[d.source_record_id.eq(split_sid),'root']=split_sid;parent={x:x for x in d.root.unique()};years={x:set(z.census_year)for x,z in d.groupby('root')}
def find(x):
 while parent[x]!=x:x=parent[x]
 return x
rd=d.set_index('source_record_id').root.to_dict();ef=pd.concat([pd.read_csv(B/'accepted_identity_edge_delta.csv'),pd.read_csv(O/'accepted_identity_edge_delta.csv')],ignore_index=True)
for r in ef.itertuples():
 a,b=find(rd[r.from_source_record_id]),find(rd[r.to_source_record_id])
 if a==b:continue
 assert not years[a]&years[b],(r.case,a,b,years[a],years[b]);parent[a]=b;years[b]|=years[a]
d['after_root']=d.root.map(find);d.to_parquet('/dev/shm/over500-moscow-complete-batch2.parquet',index=False);pf=pd.concat([pd.read_csv(B/'accepted_point_use_delta.csv'),pd.read_csv(O/'accepted_point_use_delta.csv')]);own=set(pd.read_parquet('/dev/shm/over500-moscow-points.parquet').target_source_record_id)|set(pf.target_source_record_id);g={x:z for x,z in d.groupby('after_root')};a=pd.read_csv(B/'assigned111.csv');a['after_root']=a.source_record_id.map(d.set_index('source_record_id').after_root);a['after_years']=a.after_root.map(lambda x:','.join(map(str,sorted(set(g[x].census_year)))));a['after_ownpoint']=a.source_record_id.isin(own);a['component_all_ownpoints']=a.after_root.map(lambda x:set(g[x].source_record_id)<=own);a['component_member_UIDs']=a.after_root.map(lambda x:'|'.join(g[x].source_record_id));eventIDs=set(pd.read_csv(O/'accepted_direct_event_native_credit_union.csv').source_record_id)
a['disposition']=a.apply(lambda x:'accepted_ordinary_full3_route'if x.after_years=='2002,2010,2021'and x.component_all_ownpoints else'accepted_dated_inclusion_or_merger_available_native_route'if x.source_record_id in eventIDs and x.after_ownpoint else'accepted_available_two_year_series_missing_year_UNKNOWN'if ','in x.after_years and x.component_all_ownpoints else'held_ownpoint_or_temporal_route_needs_independent_source',axis=1);a.to_csv(O/'all111_dispositions_after_batch2.csv',index=False);a[a.disposition.str.startswith('held')].to_csv(O/'remaining_assigned_holds.csv',index=False)
statuses=[];obs=[]
for root in set(a[a.disposition.eq('accepted_available_two_year_series_missing_year_UNKNOWN')].after_root):
 z=g[root];scope='over500_moscow_available_'+root;ys=set(z.census_year)
 for y in [2002,2010,2021]:
  rr=z[z.census_year.eq(y)];statuses.append(dict(scope_id=scope,year=y,status='actual_own_published_observation_on_source_bound_same_place_component'if y in ys else'UNKNOWN_missing_native_year_no_birth_or_disappearance_inferred',own_population=int(rr.population.iloc[0])if y in ys else'',unknown_is_zero=False,recipient_population_assigned_to_child=False,boundary_comparability='UNKNOWN',component_member_UIDs='|'.join(z.source_record_id)))
 for r in z.itertuples():obs.append(dict(scope_id=scope,source_record_id=r.source_record_id,year=r.census_year,native_population=r.population,native_population_quality=r.population_value_quality,own_point=True,ordinary_three_census_same_place_claim=False,is_additive_to_original_final_mixed_census_axis=False,missing_year_population_fabricated=False))
pd.DataFrame(statuses).to_csv(O/'accepted_ordinary_available_year_statuses.csv',index=False);pd.DataFrame(obs).to_csv(O/'accepted_available_year_observations.csv',index=False)
receipt=dict(status='batch2_frozen_reviewed_delta_ready_for_root_replay',new_identity_edges=len(pd.read_csv(O/'accepted_identity_edge_delta.csv')),new_point_rows=len(pd.read_csv(O/'accepted_point_use_delta.csv')),new_secondary_native_observations=1,new_actual_source_population=258,dated_events=len(pd.read_csv(O/'accepted_inclusion_events.csv')),actual_historical_event_leaves=len(eventIDs),assigned111_dispositions=a.disposition.value_counts().to_dict(),all_new_components_no_same_year_collision=True,native_values_or_quality_changed=0,unknown_counts_as_zero=0,secondary_count_equal_native_claimed=False,national_credit_gain_not_claimed=True);(O/'BATCH2_receipt.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2));files=[f for f in O.iterdir()if f.is_file()and not f.name.startswith('BATCH2_manifest')];manifest=[dict(path=str(f),sha256=sha(f),bytes=f.stat().st_size)for f in sorted(files)];(O/'BATCH2_manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2));(O/'BATCH2_manifest.sha256').write_text(sha(O/'BATCH2_manifest.json')+'\n');print(json.dumps(receipt,ensure_ascii=False));print(a[a.disposition.str.startswith('held')][['census_year','settlement_name','after_ownpoint','after_years']].to_string(index=False))
