from pathlib import Path
import pandas as pd,json,gzip,hashlib,xlrd,re
from bs4 import BeautifulSoup
from urllib.parse import urlparse,parse_qs
O=Path(__file__).parent;A=Path('research_rebuild/evidence/over500_east_alternative_point_sources_20261009');D=pd.read_pickle('/dev/shm/over500-20261009/east_enriched.pkl');sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();W=[];P=[];raw=[]
S=[('2002:041_4b428edd23_Bashkiria_new.xls:Sheet1:825',2,'Сайгафар','80206807005'),('2010:017_68e0e4537e_9._20Basq_Mari_Mord_Tatar_Udm_Chuv_2010.xls:!!!:750',1,'Надеждино (Белебеевский район)','80209801002')]
for sid,n,title,code in S:
 t=D[D.source_record_id.eq(sid)].iloc[0];F=A/f'additional_v6_rendered_{n}.json.gz';J=json.load(gzip.open(F));assert J['parse']['title']==title;soup=BeautifulSoup(J['parse']['text']['*'],'html.parser');txt=soup.get_text(' ',strip=True);assert code in txt;href=next(a['href']for a in soup.find_all('a',href=True)if 'geohack' in a['href']);parts=parse_qs(urlparse(href).query)['params'][0].split('_');assert parts[3]=='N'and parts[7]=='E';lat=float(parts[0])+float(parts[1])/60+float(parts[2])/3600;lon=float(parts[4])+float(parts[5])/60+float(parts[6])/3600
 nf=Path('/workspace/settlements-raw')/t.source_file;sh=xlrd.open_workbook(str(nf)).sheet_by_name(sid.rsplit(':',2)[1]);rn=int(sid.rsplit(':',1)[1])-1;cells=sh.row_values(rn);context=[]
 if n==2:
  assert t.population==663 and cells[4]==97 and 'Акмурунский сельсовет' in str(sh.row_values(819));assert 'Комсомольское отделение' in txt and 'поселка Комсомольского отделения Акмурунского сельсовета' in txt and '2008' in txt and '663' in txt and '97' in txt;context=[dict(row0=819,cells=sh.row_values(819))];rule='Native exactoldКомсомольскогоОтделения ownпоселок663/bash97 under explicitАкмурунскийсельсовет matches ownrenderedСайгафар exactformername, explicit2005typeconversion and2008rename, owncode80206807005, same2002count663/ethnic97 corroboration. DifferentЗилаирскийsameoldname839 excluded; no merger or generic estatepoint.'
 else:
  assert t.population==701 and t.settlement_name=='Надеждино' and '701' in txt and '( 2010 )' in txt and 'Белебеевский' in txt and 'Аксаковский' in txt;anchors=[]
  for k in [751,752,753]:
   a=D[D.source_record_id.eq(sid.rsplit(':',1)[0]+':'+str(k))].iloc[0];peers=D[D.root.eq(a.root)&D.census_year.eq(2021)];assert len(peers)==1 and peers.iloc[0].county=='белебеевский';anchors.append(dict(native2010=a.fillna('').to_dict(),accepted_current_peer=peers.iloc[0].fillna('').to_dict()))
  context=[dict(row0=k,cells=sh.row_values(k))for k in range(748,753)];assert 'Приютово' in str(sh.row_values(748));rule='Native exactownселоНадеждино2010count701 is sourcecontextually inБелебеевский block: immediately after uniquePGTПриютово and immediately before three independent acceptedБелебеевский ownlocalitiesАксаково/Баженово/Екатериновка. Ownrenderedarticle exactсело/county/code80209801002 explicitly publishes same2010census701 as independentcorroboration. OtherКалтасинский/АургазинскийНадеждино retained as homonyms; blanknativecounty preserved, no countonly matching or full3 claim.'
 raw.append(dict(source_record_id=sid,native_file=str(nf),sha256=sha(nf),raw_row0=rn,raw_cells=cells,source_context=context));wi=len(W);W.append(dict(target_source_record_id=sid,native_observation=t.fillna('').to_dict(),rendered_source_file=str(F),rendered_source_sha256=sha(F),pageid=J['parse']['pageid'],revid=J['parse']['revid'],retained_actual_rendered_ownsource_html=J['parse']['text']['*'],actual_geohack_coordinate_href=href,owncode=code,rule=rule,context_accepted_peers=anchors if n==1 else [],census_count_preserved=True,sourcepoint_positional_accuracy_unknown=True))
 P.append(dict(target_source_record_id=sid,latitude=lat,longitude=lon,coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_source_record_id=f'wikipedia:ru:pageid={J["parse"]["pageid"]}',point_origin_file=str(F),point_origin_sha256=sha(F),point_origin_locator='parse.text.*;infoboxGeohackhrefparams',point_origin_kind='direct_source_bound_own_article_rendered_infobox_coordinate',coordinate_binding_rule=rule,point_use_inference='Explicit ownlocality representative point inference; censusday measurement and population boundaries unknown.',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,external_provider_ID_binding_asserted=True,evidence_file=str(O/'point_binding_witnesses.json.gz'),evidence_locator=f'[{wi}]'))
pd.DataFrame(P).to_csv(O/'accepted_point_use_delta.csv',index=False);pd.DataFrame(columns=['from_source_record_id','to_source_record_id','relation','decision_status','admission_method','admission_rule','evidence_file','evidence_locator']).to_csv(O/'accepted_identity_edge_delta.csv',index=False);pd.DataFrame([dict(source_record_id=p['target_source_record_id'],disposition='accepted_owncoded_rendered_article_point_with_native_scope_witness',ordinary_identity_edges_added=False,missing_year_population_assigned=False)for p in P]).to_csv(O/'record_dispositions.csv',index=False)
for n,v in [('point_binding_witnesses.json.gz',W),('native_source_row_witnesses.json.gz',raw)]:
 with gzip.open(O/n,'wt')as f:json.dump(v,f,ensure_ascii=False)
m=dict(baseline_stage=71,accepted_own_point_uses=2,identity_edges_added=0,population_values_modified=False,validation=dict(actual_rendered_infobox_coordinates_reparsed=True,native_raw_scope_rows_reopened=True,explicit_owncodes_verified=True,census_values_independent_corroboration_not_countonly_identity=True),frozen_files=[dict(name=f.name,sha256=sha(f),bytes=f.stat().st_size)for f in sorted(O.iterdir())if f.is_file()]);(O/'freeze_manifest.json').write_text(json.dumps(m,ensure_ascii=False,indent=2));print(2)
