from pathlib import Path
import pandas as pd,json,gzip,hashlib,xlrd,struct,base64
O=Path(__file__).parent;A=Path('research_rebuild/evidence/over500_east_final_five_sources_20261009');sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();sid='2002:041_4b428edd23_Bashkiria_new.xls:Sheet1:5291';D=pd.read_pickle('/dev/shm/over500-20261009/east_enriched.pkl');t=D[D.source_record_id.eq(sid)].iloc[0];nf=Path('/workspace/settlements-raw')/t.source_file;sh=xlrd.open_workbook(str(nf)).sheet_by_name('Sheet1');assert t.population==633 and 'Новые Турналы' in str(sh.row_values(5290)) and 'Турналинский сельсовет' in str(sh.row_values(5289));assert 'деревня Турналы' in str(sh.row_values(5293))
G=pd.read_parquet('/workspace/settlements-work/sources/geokladr_raw_verification/geokladr_okato_2011_raw_parsed.parquet');g=G[G.historical_okato.eq('80247865001')].iloc[0];F=Path('/workspace/settlements-raw/data/raw/historical_geography/geokladr_okato_2011/okato.dbf');assert sha(F)==g.source_sha256
with F.open('rb')as f:
 h=f.read(32);hlen,rlen=struct.unpack('<HH',h[8:12]);f.seek(int(g.record_byte_offset_0based));b=f.read(rlen)
assert b'58.273756'in b and b'55.334728'in b;article=Path('/workspace/settlements-raw/data/raw/wikipedia_articles/batch_02462.json.gz');J=json.load(gzip.open(article));p=next(p for p in J['payload']['query']['pages']if p['title']=='Турналы');txt=p['revisions'][0]['slots']['main']['content'];assert 'Новые Турналы'in txt and '80247865001'in txt and 'Турналинский'in txt
rule='NativeownселоНовыеТурналы633 underТурналинский differs separatelycountedдеревняТурналы202. ActualdatedtopographicN40-021 map terrain1983/edition1990 explicitly labels EAST ownНов.Турналы builtresidentialcore versus WEST separateТурналы. OwncodedrawGeo2011село80247865001 point55.33472858.273756 falls eastoldcore; qualifiedarticle code/council/explicitformerNewTurнали history supports sourcebinding. Wrongwestarticlecoordinate and secondarycombined2002population835/ethnicoldsmallplace excluded from ownpoint/countuse. No mergedwholecentroid, recipientpoint, ordinaryedge, populationaggregation or eventcredit. Retrospective ownoldphysicalcore point; precise censusday and boundaries unknown.'
w=dict(target_source_record_id=sid,raw_native_file=str(nf),raw_native_sha256=sha(nf),raw_target_row0=5290,raw_target_cells=sh.row_values(5290),raw_parent_row0=5289,raw_parent_cells=sh.row_values(5289),distinct_smallplace_row0=5293,distinct_smallplace_cells=sh.row_values(5293),raw_owncoded_Geo=g.fillna('').to_dict(),actual_map_georeferencing_receipt=json.loads((A/'turnaly_georeferencing_receipt.json').read_text()),actual_map_georeferencing_receipt_sha256=sha(A/'turnaly_georeferencing_receipt.json'),actual_DBFrlen=rlen,actual_DBRecord_base64=base64.b64encode(b).decode(),actual_own_history_article=p,article_file=str(article),article_sha256=sha(article),map_file=str(A/'n-40-021.jpg'),map_sha256=sha(A/'n-40-021.jpg'),actually_viewed_ownlabel_crop=str(A/'novye_turnaly_ownlabel_crop.png'),ownlabel_crop_sha256=sha(A/'novye_turnaly_ownlabel_crop.png'),actually_viewed_datedcaption_crop=str(A/'turnaly_dated_caption_crop.png'),datedcaption_crop_sha256=sha(A/'turnaly_dated_caption_crop.png'),rule=rule)
with gzip.open(O/'point_binding_witnesses.json.gz','wt')as f:json.dump([w],f,ensure_ascii=False)
p=dict(target_source_record_id=sid,latitude=float(g.latitude_from_lat),longitude=float(g.longitude_from_long),coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_source_record_id='geokladr_okato2011:80247865001',point_origin_file=str(F),point_origin_sha256=sha(F),point_origin_locator=f'DBF_record_1based={int(g.record_number_1based)};DBF_byte_offset_0based={int(g.record_byte_offset_0based)};OKATO2011_raw=80247865001',point_origin_kind='direct_owncoded_raw_Geo2011_point_independently_bound_to_dated_own_residential_core',coordinate_binding_rule=rule,point_use_inference='Retrospective ownoldresidentialcore representative point, censusday/boundary unknown.',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,external_provider_ID_binding_asserted=True,evidence_file=str(O/'point_binding_witnesses.json.gz'),evidence_locator='[0]');pd.DataFrame([p]).to_csv(O/'accepted_point_use_delta.csv',index=False);pd.DataFrame(columns=['from_source_record_id','to_source_record_id','relation','decision_status','admission_method','admission_rule','evidence_file','evidence_locator']).to_csv(O/'accepted_identity_edge_delta.csv',index=False);pd.DataFrame([dict(source_record_id=sid,disposition='accepted_owncoded_point_in_independently_dated_oldcore_footprint',population_values_modified=False,ordinary_identity_edges_added=False)]).to_csv(O/'record_dispositions.csv',index=False);m=dict(accepted_own_point_uses=1,identity_edges_added=0,population_values_modified=False,validation=dict(native_wholeleaf_and_separate_smallplace_reopened=True,rawDBFbytes_and_hash_verified=True,actualdated_ownlabels_and_caption_visually_reviewed=True,combinedcount_and_westrecipientcoordinate_excluded=True),frozen_files=[dict(name=f.name,sha256=sha(f),bytes=f.stat().st_size)for f in sorted(O.iterdir())if f.is_file()]);(O/'freeze_manifest.json').write_text(json.dumps(m,ensure_ascii=False,indent=2));print(1)
