from pathlib import Path
import sys,json,hashlib,gzip,re,time
import pandas as pd
ROOT=Path('/workspace/russian-settlements-research');E=ROOT/'research_rebuild/evidence';O=Path(__file__).parent;C=E/'wikidata_actual_full3_mass_reserve_20261007';sys.path.insert(0,str(ROOT/'research_rebuild/mass_linkage'))
from working_state_20261007 import load,PARTITION_MEMBERS
from current_chain_state_20261007 import sha
T=time.monotonic();s=load(18);c=pd.read_csv(C/'candidate_nonadditive_physical_observations.csv').fillna('');item=pd.read_csv(C/'reference_confirmed_full3_reserve.csv').fillna('').set_index('qid');srcpins={};witness=E/'large_observed_year_recovery_20261007/own_pages.json.gz';article=json.load(gzip.open(witness,'rt'));page=next(p for p in article['query']['pages'] if p.get('title')=='Бердыкель');rev=page['revisions'][0];txt=rev['slots']['main']['content'];m=re.search(r'По данным.*?2010.*?Примыкание.*?</ref>',txt,re.S);assert m;scopeclaim=m.group(0)
# Authoritative known aggregate witness defeats own-item year-only population claim.
heldq={'Q4230262'};held=[];existing={sid for sid in s.point_rows if s.years[s.uf.find(sid)]=={2002,2010,2021}};exclusions={}
files=[PARTITION_MEMBERS,O/'preapplication_qualified_credit_ids_frozen.csv']+[E/d/'accepted_constituent_credit_union.csv' for d in ['named_urban_merger_application_20261007','next_named_urban_merger_application_20261007','further_urban_merger_application_20261007']]+[E/'recreated_named_locality_event_application_20261007/accepted_qualified_physical_observations.csv']
for p in files:
 f=pd.read_csv(p,dtype=str).fillna('');ids=set()
 for col in f.columns:
  if 'source_record_id'in col:ids.update(f[col])
 ids.discard('');existing.update(ids);exclusions[str(p)]={'sha256':sha(p),'source_ids':sorted(ids)}
rows=[];credit=[]
for q,g in c.groupby('wikidata_id',sort=False):
 t=item.loc[q];sid=str(g[g.census_year==2021].current2021_source_record_id.iloc[0]);native=s.by_id.loc[sid];point=s.point_rows[sid]
 assert set(g.census_year)=={2002,2010,2021};assert native.census_year==2021
 if q in heldq:
  held.append({'wikidata_id':q,'name':native.settlement_name,'held_scope':'2010 own settlement grain unproven; known includes Primykanie','secondary2010_population':float(g[g.census_year==2010].population.iloc[0]),'witness_file':str(witness),'witness_sha256':sha(witness),'revision':rev['revid'],'witness_claim':scopeclaim});continue
 if sid in existing:
  held.append({'wikidata_id':q,'name':native.settlement_name,'held_scope':'current native2021 source ID already credited in stage18/partition/qualified/named union','current_source_record_id':sid});continue
 for r in g.itertuples():
  iscurrent=r.census_year==2021;pop=float(native.population) if iscurrent else float(r.population)
  # Secondary historical values are observations of this accepted physical series,
  # never additive census rows and never an admission of conditional old selected IDs.
  rec={'trajectory_id':'wikidata_secondary_full3:'+q,'year':int(r.census_year),'population_source_value':pop,'source_record_id':sid if iscurrent else '', 'settlement_name':native.settlement_name,'region_norm':native.region_norm,'county_context':native.district_raw,'latitude':float(point['latitude']),'longitude':float(point['longitude']),'population_quality':native.population_value_quality if iscurrent else 'secondary_census_reference_year_only_primary_not_independently_verified','grain':'existing selected settlement observation' if iscurrent else 'own physical locality dated secondary census-reference observation','nonadditive_observation':not iscurrent,'source_path':(str(native.source_path) if pd.notna(native.source_path) and str(native.source_path) else '/workspace/settlements-raw/'+str(native.source_file)) if iscurrent else r.source_file,'source_sha256':(str(native.source_sha256) if pd.notna(native.source_sha256) else '') if iscurrent else r.source_sha256,'source_locator':'selected source_record_id='+sid if iscurrent else r.source_locator,'decision_status':'qualified_accepted_secondary_census_referenced_own_item','ordinary_NP3_asserted':False,'boundary_comparability_asserted':False,'point_origin_file':point.get('point_origin_file',''),'point_origin_sha256':point.get('point_origin_sha256',''),'point_origin_locator':point.get('point_origin_locator',''),'point_binding_json':json.dumps(point,ensure_ascii=False),'retrospective_point_use_is_continuity_inference':not iscurrent,'selected_credit_previously_present':False if iscurrent else None,'selected_source_sha256_as_loaded':str(native.source_sha256) if iscurrent and pd.notna(native.source_sha256) else '', 'scope':'secondary_census_referenced_own_physical_locality','boundary_comparability':'UNKNOWN','wikidata_id':q,'secondary_population_source_value':float(r.population),'secondary_source_path':r.source_file,'secondary_source_sha256':r.source_sha256,'secondary_source_locator':r.source_locator,'secondary_statement_id':r.statement_id,'observation_declared_date':r.declared_date,'date_precision':int(r.date_precision),'date_assignment_status':'explicit_census_P248_reference_year_only_no_exact_day_asserted','census_reference_ids':r.census_reference_ids,'census_reference_labels_json':r.census_reference_labels_json,'own_item_binding':t.identity_binding,'own_physical_description':t.description,'optional_Wiki_P625_count':int(t.P625_count),'optional_Wiki_P625_coordinate_source_ambiguity':int(t.P625_count)!=1,'optional_Wiki_coordinates_imported':False,'historical_conditional_native_IDs_not_admitted':r.existing_selected_source_candidates_json,'coordinate_bounds':'UNKNOWN','error_rate':'uncalibrated'}
  if iscurrent and (pd.isna(native.source_sha256) or not str(native.source_sha256)):rec['source_sha256']='';rec['source_hash_gap_flag']='selected native source hash empty; preserved explicitly'
  rows.append(rec)
 credit.append({'source_record_id':sid,'year':2021,'source_population':float(native.population),'scope':'secondary_census_referenced_own_physical_locality','trajectory_id':'wikidata_secondary_full3:'+q,'already_credited_stage18_union':False,'credit_status':'accepted_existing_native_2021_source_ID_only'})
f=pd.DataFrame(rows);assert not f[['trajectory_id','year']].duplicated().any();assert f.nonadditive_observation.sum()==2*f.trajectory_id.nunique();assert all(set(g.year)=={2002,2010,2021} for _,g in f.groupby('trajectory_id'));assert not f.ordinary_NP3_asserted.any();f.to_csv(O/'accepted_qualified_physical_observations.csv',index=False);pd.DataFrame(credit).to_csv(O/'accepted_current_source_id_credit_union.csv',index=False);pd.DataFrame(held).to_csv(O/'scope_or_precredit_holds.csv',index=False)
# Pin immutable state inputs plus actual raw secondary statements and reference payloads.
paths=list(dict.fromkeys(s.inputs+[ROOT/'research_rebuild/mass_linkage/working_state_20261007.py',ROOT/'research_rebuild/mass_linkage/current_chain_state_20261007.py',C/'candidate_nonadditive_physical_observations.csv',C/'reference_confirmed_full3_reserve.csv',C/'census_reference_checks.csv',C/'fixed15_and_largest5_source_checks.csv',witness]+[Path(p) for p in f.secondary_source_path.unique()]+list(Path('/workspace/settlements-work/wikidata_actual_full3_mass_reserve_20261007').glob('*.gz'))))
for p in paths:srcpins[str(p)]={'sha256':sha(p),'bytes':p.stat().st_size}
sourcecredits=pd.DataFrame(credit);receipt={'status':'applied_qualified_secondary_census_referenced_own_physical_series','baseline_stage':18,'accepted_series':int(f.trajectory_id.nunique()),'accepted_observations':len(f),'historical_secondary_nonadditive_observations':int(f.nonadditive_observation.sum()),'native2021_observations':int((~f.nonadditive_observation).sum()),'net_selected_source_id_credit_by_year':{'2002':{'rows':0,'population':0},'2010':{'rows':0,'population':0},'2021':{'rows':len(credit),'population':int(sourcecredits.source_population.sum())}},'qualified_actual_secondary_value_sums_not_national_credit':{str(int(y)):int(g.population_source_value.sum()) for y,g in f.groupby('year')},'scope_holds':held,'boundary_comparability':'UNKNOWN','error_rate':'uncalibrated','ordinary_graph_modified':False,'historical_conditional_native_ids_admitted':False,'protected_source_values_modified':False,'current_points':'accepted independent own points retained; optional Wiki coordinates not imported','year_only_reference_quality':'explicit P248 census bulletin labels; primary bulletin not independently authenticated','wall_seconds':time.monotonic()-T,'inputs':srcpins,'preexisting_credit_exclusion_inputs':exclusions,'outputs':{p.name:sha(p) for p in [O/'accepted_qualified_physical_observations.csv',O/'accepted_current_source_id_credit_union.csv',O/'scope_or_precredit_holds.csv']}}
(O/'application_receipt.json').write_text(json.dumps(receipt,indent=2,ensure_ascii=False));print(json.dumps({k:v for k,v in receipt.items() if k not in ['inputs','preexisting_credit_exclusion_inputs','scope_holds']},ensure_ascii=False))
