from pathlib import Path
import sys,json,ast,collections,math
import pandas as pd,duckdb
R=Path('/workspace/russian-settlements-research');sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from working_state_20261007 import load
from current_chain_state_20261007 import normalize,sha,distance_km
from apply_unique_county_name_bridge_20261007 import county_key
O=Path(__file__).parent;E=O.parent;s=load(39);before=s.metrics();candidate=O/'candidate_source_bound_spatial_edges.csv';f=pd.read_csv(candidate,keep_default_na=False);aliaspath=E/'cross_county_independent_point_bridge_20261007/build_neutral_subset.py';tree=ast.parse(aliaspath.read_text());pairs=ast.literal_eval(next(x.value for x in tree.body if isinstance(x,ast.Assign)and any(isinstance(t,ast.Name)and t.id=='pairs'for t in x.targets)));neutral={frozenset([county_key(a),county_key(b)]) for a,b in pairs.items()};holds=[];edges=[];points=[];witness=[];native=[];occupied=collections.defaultdict(set)
for sid,p in s.point_rows.items():occupied[(int(s.by_id.loc[sid,'census_year']),p['latitude'],p['longitude'])].add(sid)
def code(v):return '' if pd.isna(v) else str(v).removesuffix('.0')
for a in f.to_dict('records'):
 sid,bid=a['from_source_record_id'],a['to_source_record_id'];old,cur=s.by_id.loc[sid],s.by_id.loc[bid];ra,rb=s.uf.find(sid),s.uf.find(bid);reason='';d1,d2=a['raw_historical_county'],county_key(cur.district_raw);same=bool(d1 and d2) and(d1==d2 or frozenset([d1,d2])in neutral);exactcode=bool(code(old.okato)) and code(old.okato)==code(cur.okato);typematch=normalize(old.type_norm)==normalize(cur.type_norm)
 if not(same or exactcode):reason='actual_native_current_vs_historical_county_not_positively_continuous'
 if not typematch:reason='native_physical_type_different_without_documented_transition'
 if ra==rb or s.years[ra]&s.years[rb] or s.years[ra]|s.years[rb]!={2002,2010,2021}:reason='batch_repeated_year_or_no_new_three_year_history'
 ids=[x for x in s.obs.source_record_id if s.uf.find(x) in [ra,rb]];cp=json.loads(a['current_own_point_json'])
 if any(x in s.conflicting_point_targets for x in ids):reason='active_component_point_alternative'
 if any(x in s.point_rows and distance_km((s.point_rows[x]['latitude'],s.point_rows[x]['longitude']),(cp['latitude'],cp['longitude']))>5 for x in ids):reason='component_point_conflict'
 if any(x not in s.point_rows and occupied[(int(s.by_id.loc[x,'census_year']),cp['latitude'],cp['longitude'])] for x in ids):reason='same_year_ownpoint_collision'
 if reason:holds.append({**a,'hold_reason':reason});continue
 edge={**a,'relation':'same_place','decision_status':'checked_rule_accepted','admission_rule':'Actual archived own NP classifier name/type/code/county and raw point; current exact physical name/type plus positive same/approved-neutral county or exact native own code; all name rivals before graph filtering and source-year uniqueness','native_old_printed_code_asserted':bool(code(old.okato)),'boundary_comparability_asserted':False,'population_primary_value_or_quality_modified':False,'provider_ID_binding_status':'raw_coordinate_auxiliary_provider_ID_not_admitted; independently_positive_current_ownpoint_reused','current_county_positive':same,'native_own_code_positive':exactcode};edge.pop('current_own_point_json');edges.append(edge);s.union(sid,bid)
 for x in ids:
  rr=s.by_id.loc[x];native.append({'source_record_id':x,'year':int(rr.census_year),'population_source_value':rr.population,'population_quality':rr.population_value_quality,'settlement_name':rr.settlement_name,'settlement_type':rr.settlement_type,'native_okato':code(rr.okato),'native_oktmo':code(rr.oktmo),'source_file':rr.source_file,'source_locator':rr.source_locator,'source_sha256_as_loaded':rr.source_sha256})
  if x in s.point_rows:continue
  pp=dict(cp);pp.pop('point_ledger_path',None);pp.update(target_source_record_id=x,coordinate_admission_status='reviewed_extension_rule_accepted',native_old_printed_code_asserted=False,boundary_comparability_asserted=False,point_temporal_interpretation='Modern own representative, not a measured census-date coordinate',admission_rule='Modern own point reused over actual native name/type/county and archived own-code auxiliary spatial corroboration; providerID not auto-bound');points.append(pp);s.point_rows[x]=dict(pp,point_ledger_path=str(O/'accepted_point_use_delta.csv'));occupied[(int(rr.census_year),pp['latitude'],pp['longitude'])].add(x)
 witness.append(a|{'own_native_old_NP_type_positive':True,'all_current_namesakes_before_graph_filter':True,'all_old_same_year_namesakes_and_source_context_checked':True,'native_county_continuity_positive':same,'own_native_code_continuity_positive':exactcode,'old_raw_point_admitted_as_coordinate':False,'provider_ID_automatically_bound':False})
pd.DataFrame(edges).to_csv(O/'accepted_identity_edge_delta.csv',index=False);pd.DataFrame(points).to_csv(O/'accepted_point_use_delta.csv',index=False);pd.DataFrame(witness).to_csv(O/'accepted_source_binding_witnesses.csv.gz',index=False,compression={'method':'gzip','mtime':0});pd.DataFrame(holds).to_csv(O/'final_hard_holds.csv',index=False);pd.DataFrame(native).drop_duplicates('source_record_id').to_csv(O/'accepted_native_observation_pins.csv.gz',index=False,compression={'method':'gzip','mtime':0});after=s.metrics();pins=json.load(open(O/'inventory_receipt.json'))['input_pins'];pins[str(candidate)]=sha(candidate);pins[str(aliaspath)]=sha(aliaspath)
for x in native:
 p=Path('/workspace/settlements-raw')/x['source_file']
 if p.exists():pins[str(p)]=sha(p)
for a in witness:
 p=json.loads(a['current_own_point_json']);f1=Path(p['point_origin_file']);assert sha(f1)==p['point_origin_sha256'];pins[str(f1)]=sha(f1)
receipt={'baseline_stage':39,'status':'accepted_positive_archived_ownpoint_auxiliary_native_continuity_batch','accepted_edges':len(edges),'accepted_point_uses':len(points),'accepted_full3_histories':len(edges),'accepted_old_native_by_year':{str(y):{'rows':len(g),'population':int(g.old_population.sum())} for y,g in pd.DataFrame(edges).groupby('from_year')}if edges else{},'before':before,'after':after,'actual_net_ordinary_population_gain':{str(y):after[y]['covered_population']-before[y]['covered_population'] for y in before},'actual_net_ordinary_rows_gain':{str(y):after[y]['covered_rows']-before[y]['covered_rows'] for y in before},'final_holds':len(holds),'hard_hold_reasons':dict(collections.Counter(x['hold_reason'] for x in holds)),'historical_coordinate_measurement_asserted':False,'old_raw_providerID_automatically_bound':False,'boundary_comparability_asserted':False,'original_population_and_quality_preserved':True,'no_network':True,'input_pins':pins,'output_pins':{p.name:sha(p) for p in O.glob('*.csv*')}};(O/'application_receipt.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2));print(json.dumps({k:v for k,v in receipt.items() if k not in ['before','after','input_pins','output_pins']},ensure_ascii=False))
