from pathlib import Path
import json,gzip,hashlib
import pandas as pd,duckdb
O=Path(__file__).parent
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
f=pd.read_csv(O/'accepted_identity_edge_delta.csv',dtype={'historical_okato_2009_raw':str,'historical_okato_2011_raw':str},keep_default_na=False);f['status']='accepted_native_physical_continuity_with_archived_raw_ownpoint_auxiliary';f.to_csv(O/'accepted_identity_edge_delta.csv',index=False);r=json.load(open(O/'application_receipt.json'));r['output_pins']={p.name:sha(p) for p in O.glob('*.csv*')};(O/'application_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2))
for p,h in r['input_pins'].items():assert sha(p)==h,p
for p,h in r['output_pins'].items():assert sha(O/p)==h,p
n=pd.read_csv(O/'accepted_native_observation_pins.csv.gz',keep_default_na=False);points=pd.read_csv(O/'accepted_point_use_delta.csv',keep_default_na=False);assert n.source_record_id.is_unique;assert points.target_source_record_id.is_unique;assert f.from_source_record_id.is_unique;assert f.to_source_record_id.is_unique;assert f.current_point_previously_admitted.all();assert not f.boundary_comparability_asserted.any();assert f.current_county_positive.all();assert len(n)==3*len(f)
c=duckdb.connect(config={'threads':1,'memory_limit':'200MB'});selected='/workspace/settlements-delivery/continuation-consolidated-20261003/selected_observations.parquet';native=c.execute('select source_record_id,census_year,population,population_value_quality,settlement_name,settlement_type from read_parquet(?) where source_record_id in(select unnest(?))',[selected,list(n.source_record_id)]).fetchdf().set_index('source_record_id')
for x in n.to_dict('records'):
 a=native.loc[x['source_record_id']];assert int(a.census_year)==int(x['year']);assert float(a.population)==float(x['population_source_value']);assert a.population_value_quality==x['population_quality'];assert a.settlement_name==x['settlement_name'];assert a.settlement_type==x['settlement_type']
historical='/workspace/settlements-work/coordinates/historical_named_candidates_v4/all_historical_named_objects.parquet';h=c.execute('select historical_okato_2009_raw,record_number_1based,source_line_1based,name_raw_2009,name_raw_2011,latitude_from_lat,longitude_from_long,historical_name_exact,historical_type_exact,historical_code_structure_compatible,is_deleted from read_parquet(?)where historical_okato_2009_raw in(select unnest(?))',[historical,list(f.historical_okato_2009_raw.astype(str))]).fetchdf()
for x in f.to_dict('records'):
 a=h[(h.historical_okato_2009_raw.astype(str)==str(x['historical_okato_2009_raw']))&h.record_number_1based.eq(x['old_raw_record_1based'])];assert len(a)==1;a=a.iloc[0];assert a.historical_name_exact and a.historical_type_exact and a.historical_code_structure_compatible and not a.is_deleted;assert a.latitude_from_lat==x['old_raw_latitude'] and a.longitude_from_long==x['old_raw_longitude'];assert a.name_raw_2009==x['old_raw_name_2009'];assert a.name_raw_2011==x['old_raw_name_2011'];assert a.source_line_1based==x['old_raw_classifier_line_1based'];assert x['current_candidates_within_5km']==1 and x['distance_km']<=5
for x in points.to_dict('records'):assert sha(x['point_origin_file'])==x['point_origin_sha256'];assert x['coordinate_admission_status']=='reviewed_extension_rule_accepted'
qualified=pd.read_csv(O.parent/'working_full_chain_20261007/qualified_scope_source_id_credit_union.csv',dtype=str,keep_default_na=False);overlap=set(n.source_record_id)&set(qualified.source_record_id);out={'status':'raw_own_classifier_name_type_code_row_coordinates_native_ID_year_population_quality_and_point_origin_hashes_verified','baseline_stage':39,'accepted_histories':len(f),'native_observations_verified':len(n),'new_point_uses_verified':len(points),'existing_report_qualified_native_ID_overlap':sorted(overlap),'historical_raw_providerID_automatically_admitted':False,'historical_raw_point_directly_admitted':False,'application_receipt_sha256':sha(O/'application_receipt.json')};(O/'verification_receipt.json').write_text(json.dumps(out,ensure_ascii=False,indent=2));print(json.dumps(out,ensure_ascii=False))
