from pathlib import Path
import sys,json,collections,math,re,time
import pandas as pd
O=Path(__file__).parent;E=O.parent;ROOT=E.parents[1];A=E/'wikidata_secondary_full3_expansion_application_20261007';sys.path.insert(0,str(ROOT/'research_rebuild/mass_linkage'))
from working_state_20261007 import load,PARTITION_MEMBERS
from current_chain_state_20261007 import normalize,distance_km,sha
T=time.monotonic();s=load(21);f=pd.read_csv(A/'accepted_qualified_physical_observations.csv').fillna('');scopecredits=set();pins={}
for p in [PARTITION_MEMBERS,E/'wikidata_secondary_full3_application_20261007/preapplication_qualified_credit_ids_frozen.csv',E/'wikidata_secondary_full3_application_20261007/accepted_qualified_physical_observations.csv',E/'current_unpointed_own_wiki_mass_application_20261007/accepted_qualified_physical_observations.csv',E/'existing_event_scope_application_20261007/accepted_selected_source_id_credit_union.csv',A/'accepted_current_source_id_credit_union.csv']+[E/d/'accepted_constituent_credit_union.csv' for d in ['named_urban_merger_application_20261007','next_named_urban_merger_application_20261007','further_urban_merger_application_20261007']]:
 d=pd.read_csv(p,dtype=str).fillna('');pins[str(p)]=sha(p)
 for col in d.columns:
  if 'source_record_id'in col:scopecredits.update(d[col])
covered={sid for sid in s.point_rows if s.years[s.uf.find(sid)]=={2002,2010,2021}}|scopecredits
# Explicit wrapper-only administrative normalization; no district stemming/fuzzy matching.
def county(v):
 x=normalize(v)
 for t in ['муниципальный район','муниципальный округ','городской округ','сельский район','район','город','округ']:x=re.sub(r'(?<!\w)'+t+r'(?!\w)',' ',x)
 return ' '.join(x.split())
rows=s.obs.copy();rows['exact_name']=rows.settlement_name.map(normalize);rows['exact_type']=rows.type_norm.map(normalize);rows['county_key']=rows.district_raw.map(county);index=collections.defaultdict(list)
for r in rows.itertuples():index[(int(r.census_year),r.exact_name,r.exact_type,r.region_norm)].append(r)
comp=[];candidates=[];held=[];seencomps=set()
def point(r):
 if r.source_record_id in s.point_rows:return s.point_rows[r.source_record_id],'accepted_old_point'
 if pd.notna(r.latitude) and pd.notna(r.longitude) and -90<=r.latitude<=90 and -180<=r.longitude<=180:return {'latitude':r.latitude,'longitude':r.longitude},'unreviewed_selected_raw_point_constraint_only'
 return None,'no_old_coordinate'
def context(r):return {'source_record_id':r.source_record_id,'year':r.census_year,'name':r.settlement_name,'type':r.settlement_type,'region':r.region_norm,'county':r.district_raw,'population':None if pd.isna(r.population) else float(r.population),'oktmo':None if pd.isna(r.oktmo) else str(r.oktmo),'okato':None if pd.isna(r.okato) else str(r.okato),'population_quality':r.population_value_quality,'is_additive':bool(r.is_additive_settlement_record),'source_file':r.source_file,'source_locator':None if pd.isna(r.source_locator) else str(r.source_locator)}
for q,g in f.groupby('wikidata_id',sort=False):
 current=g[g.year==2021].iloc[0];sid=current.source_record_id;n=rows[rows.source_record_id==sid].iloc[0];root=s.uf.find(sid);cp=s.point_rows[sid];currentpeers=index[(2021,n.exact_name,n.exact_type,n.region_norm)];currentcounty=[r for r in currentpeers if r.county_key==n.county_key];members=rows[(rows.root==root)&rows.census_year.isin([2002,2010])]
 for year in (2002,2010):
  hist=g[g.year==year].iloc[0];pop=float(hist.population_source_value);allold=index[(year,n.exact_name,n.exact_type,n.region_norm)];exact=[r for r in allold if pd.notna(r.population) and float(r.population)==pop];ownmembers=members[members.census_year==year];accepted_member_ids=set(ownmembers.source_record_id);options={r.source_record_id:r for r in exact}
  for r in ownmembers.itertuples():options[r.source_record_id]=r
  for r in allold+currentpeers:
   key=(q,year,r.source_record_id)
   if key not in seencomps:comp.append({'wikidata_id':q,'history_year':year,'current_target_source_record_id':sid,**context(r)});seencomps.add(key)
  if not options:held.append({'wikidata_id':q,'history_year':year,'current_source_record_id':sid,'name':n.settlement_name,'secondary_actual_census_population':pop,'hold_reason':'no_exact_name_type_region_actual_count_native_row_or_already_accepted_component_row','all_old_typed_name_region_competitors':len(allold),'all_current_typed_name_region_competitors':len(currentpeers)});continue
  for osid,r in options.items():
   op,pk=point(r);distance=distance_km((cp['latitude'],cp['longitude']),(op['latitude'],op['longitude'])) if op else None;existing_component=osid in accepted_member_ids;oldcounty=[p for p in allold if p.county_key==r.county_key];count_matches=pd.notna(r.population) and float(r.population)==pop;county_match=bool(n.county_key) and n.county_key==r.county_key;native_grain=bool(r.is_additive_settlement_record) and (pd.isna(r.population_scope) or not any(w in str(r.population_scope).lower() for w in ['aggregate','municipality','district_total','federal_city_region']));coordinate_ok=distance is None or distance<=5;basis=[];reasons=[]
   if existing_component:basis.append('already_accepted_same_place_component_to_current_native_NP')
   elif count_matches and county_match and len(oldcounty)==1 and len(currentcounty)==1 and native_grain:basis.append('exact_name_type_region_actual_census_count_with_printed_native_county_and_full_current_old_county_exclusivity')
   else:
    if not county_match:reasons.append('historical_county_not_exactly_bound_after_wrapper_normalization')
    if len(oldcounty)!=1 or len(currentcounty)!=1:reasons.append('same_county_typed_name_competitor_not_unique')
    if not count_matches:reasons.append('secondary_count_not_native_actual_value; no_existing_binding')
   if not native_grain:reasons.append('nonsettlement_or_nonadditive_native_grain')
   if not coordinate_ok:reasons.append('old_coordinate_disagrees_over5km')
   status='strong_binding_candidate_not_admitted' if basis and native_grain and coordinate_ok else 'held_potential_only'
   candidates.append({'wikidata_id':q,'trajectory_id':hist.trajectory_id,'history_year':year,'old_native_source_record_id':osid,'current_native_source_record_id':sid,'name_current':n.settlement_name,'name_old':r.settlement_name,'type_current':n.settlement_type,'type_old':r.settlement_type,'region':n.region_norm,'native_old_population':None if pd.isna(r.population) else float(r.population),'secondary_actual_census_population':pop,'secondary_equals_native_actual_population':bool(count_matches),'native_population_quality':r.population_value_quality,'native_population_scope_as_loaded':'' if pd.isna(r.population_scope) else r.population_scope,'native_population_scope_missing_legacy_flag':pd.isna(r.population_scope),'current_county':n.district_raw,'old_printed_native_county':r.district_raw,'county_normalization_rule':'only remove municipality/район/город/округ wrappers; no stemming/fuzzy equivalence','county_exact_after_wrappers':county_match,'old_all_typed_name_region_competitors':len(allold),'old_exact_population_candidates':len(exact),'old_same_county_typed_name_competitors':len(oldcounty),'current_all_typed_name_region_competitors':len(currentpeers),'current_same_county_typed_name_competitors':len(currentcounty),'old_coordinate_status':pk,'old_coordinate_distance_km':distance,'old_point_binding_json':json.dumps(op,ensure_ascii=False) if op else '', 'current_point_binding_json':json.dumps(cp,ensure_ascii=False),'binding_basis':';'.join(basis),'status':status,'hold_reason':';'.join(reasons),'already_credited_latest21_scope_union':osid in covered,'conditional_net_native_population':float(r.population) if status.startswith('strong') and osid not in covered and pd.notna(r.population) else 0,'native_source_file':r.source_file,'native_source_sha256_as_loaded':'' if pd.isna(r.source_sha256) else r.source_sha256,'native_source_locator':'' if pd.isna(r.source_locator) else r.source_locator,'native_oktmo_selected_field_not_assumed_raw_binding':'' if pd.isna(r.oktmo) else str(r.oktmo),'native_okato_selected_field_not_assumed_raw_binding':'' if pd.isna(r.okato) else str(r.okato),'secondary_source_path':hist.source_path,'secondary_source_sha256':hist.source_sha256,'secondary_source_locator':hist.source_locator,'secondary_statement_id':hist.statement_id,'secondary_census_proof_class':hist.census_proof_class,'secondary_declared_date':hist.declared_date,'secondary_date_precision':hist.date_precision,'secondary_reference_titles_json':hist.census_reference_titles_json,'secondary_P248_labels_json':hist.P248_labels_json,'protected_native_value_preserved':True,'edge_admitted':False,'population_credit_admitted':False})
cand=pd.DataFrame(candidates);dup=cand[cand.status.eq('strong_binding_candidate_not_admitted')].groupby('old_native_source_record_id').current_native_source_record_id.nunique();bad=set(dup[dup>1].index);cand.loc[cand.old_native_source_record_id.isin(bad),'status']='held_potential_only';cand.loc[cand.old_native_source_record_id.isin(bad),'hold_reason']='old_native_source_ID_maps_to_multiple_current_NPs';cand.loc[cand.old_native_source_record_id.isin(bad),'conditional_net_native_population']=0;cand.to_csv(O/'native_history_binding_candidates.csv',index=False);pd.DataFrame(comp).to_csv(O/'full_old_and_current_competitors.csv',index=False);pd.DataFrame(held).to_csv(O/'missing_native_candidates.csv',index=False);summary=[]
for y,d in cand.groupby('history_year'):
 good=d[d.status.eq('strong_binding_candidate_not_admitted')&~d.already_credited_latest21_scope_union].drop_duplicates('old_native_source_record_id');summary.append({'year':int(y),'strong_uncredited_native_ID_candidates':len(good),'conditional_net_native_population_potential':int(good.native_old_population.sum()),'already_accepted_component_source_ID_candidates':int(good.binding_basis.str.contains('already_accepted').sum()),'new_context_binding_source_ID_candidates':int((~good.binding_basis.str.contains('already_accepted')).sum()),'actual_admitted_gain':0})
pd.DataFrame(summary).to_csv(O/'conditional_native_source_ID_net_potential.csv',index=False)
for p in dict.fromkeys(s.inputs+[A/'accepted_qualified_physical_observations.csv',ROOT/'research_rebuild/mass_linkage/working_state_20261007.py',Path(__file__)]):pins[str(p)]=sha(p)
receipt={'status':'candidate_only_native_census_binding_potential','cohort':'approved455 pointed expansion only; other398 cohort excluded','baseline_stage':21,'qualified_history_counts_not_added_to_national_coverage':True,'binding_options':len(cand),'full_competitor_rows':len(comp),'missing_native_year_options':len(held),'by_year':summary,'coordinate_rule':'old existing coordinate must agree≤5km; absent oldcoordinate remains explicit currentpointcontinuity inference','numeric_equality_rule':'2002 unbound rows require exact actualcensus count plus exact typed name/region/printed county exclusivity; numericalsimilarity alone never binds protected2010','old_selected_codes':'preserved candidate fields, never assumed direct raw code unless separately source checked','ordinary_edges_created':0,'admitted_native_IDs':0,'wall_seconds':time.monotonic()-T,'inputs':pins};(O/'receipt.json').write_text(json.dumps(receipt,indent=2,ensure_ascii=False));print(json.dumps(summary));print('options',len(cand),'competitors',len(comp),'missing',len(held))
