import json,re,hashlib,sys,duckdb
from pathlib import Path
import pandas as pd
O=Path(__file__).parent;P=O.parent.parent;R=Path('/workspace/russian-settlements-research');sys.path.insert(0,str(R/'research_rebuild/mass_linkage'))
from current_chain_state_20261007 import normalize
f=pd.read_csv(O/'current_owncode_cached_coordinate_inventory.csv.gz',keep_default_na=False);f=f[f.coordinate_available];rej=pd.read_csv(P/'point_use_rejections.csv.gz',keep_default_na=False);RAW=Path('/workspace/settlements-raw/data/interim/2021_tochno/data_allsettlements_anon_156_v20251217.parquet');db=duckdb.connect(config={'threads':1});raw=db.execute('select row_number() over() rn,object_name,oktmo,mun_lower,mun_upper from read_parquet(?)',[str(RAW)]).fetchdf().set_index('rn');db.close();tsv='/workspace/settlements-raw/data/raw/wikimedia/wikidata_oktmo_entities.tsv';sh=hashlib.sha256(Path(tsv).read_bytes()).hexdigest();points=[];ws=[]
def cl(v):return normalize(re.sub(r'^(?:деревня|село|пос[её]лок|хутор|станица|аул|станция)\s+','',re.sub(r'\s*\([^)]*\)\s*$','',str(v)),flags=re.I))
for sid,g in f.groupby('current_source_record_id'):
 a=g.iloc[0].to_dict();r=raw.loc[int(sid.rsplit(':',1)[1])];fields=a['TSV_raw_line'].split('\t');label=fields[4].removesuffix('@ru').strip('"');parish=fields[7].removesuffix('@ru').strip('"');coords={tuple(map(float,re.fullmatch(r'POINT\(([-.0-9]+) ([-.0-9]+)\)',v).groups())) for v in g.TSV_coordinate_literal};qs=set(g.QID);typed=bool(re.match(r'^(?:деревня|село|пос[её]лок|хутор|станица|аул|станция)\s+',str(r.object_name),re.I));safe=len(coords)==1 and len(qs)==1 and typed and cl(label)==cl(r.object_name) and normalize(parish)==normalize(r.mun_lower);assert safe,(sid,label,parish,r.to_dict());lon,lat=next(iter(coords));targets=rej.loc[rej['case'].eq(sid),'target_source_record_id'].tolist();assert targets
 for target in targets:points.append({'target_source_record_id':target,'latitude':lat,'longitude':lon,'coordinate_admission_status':'reviewed_extension_rule_accepted','coordinate_source_record_id':a['QID'],'point_origin_file':tsv,'point_origin_sha256':sh,'point_origin_locator':'lines1based='+','.join(map(str,g.TSV_line1based))+'; fields own-currentP764/physicalname/adminLabel/coordinate','point_origin_kind':'independent_current_owncoded_TSV_physical_locality_point','coordinate_binding_rule':'Exact current own P764 (numeric source-format equivalence explicit), typed original native NP, literal name and same raw current parish, sole entity and sole physical coordinate; repeated identical source rows collapsed; no historical Geo OKATO equivalence asserted','historical_census_coordinate_asserted':False,'point_use_inference':'representative own current physical point reused by existing source-supported continuity','case':sid})
 ws.append({**a,'actual_raw_object_name':r.object_name,'actual_raw_current_code':r.oktmo,'actual_raw_current_parish':r.mun_lower,'actual_raw_county':r.mun_upper,'exact_name_and_parish_match':safe,'all_literal_TSV_rows_json':json.dumps(g.TSV_raw_line.tolist(),ensure_ascii=False),'all_TSV_row_locators_json':json.dumps(g.TSV_line1based.tolist()),'accepted_target_IDs_json':json.dumps(targets),'historical_Geo_code_validation_claimed':False})
pd.DataFrame(points).to_csv(O/'accepted_point_use_delta.csv.gz',index=False,compression={'method':'gzip','mtime':0});pd.DataFrame(ws).to_csv(O/'accepted_current_owncoded_point_witnesses.csv.gz',index=False,compression={'method':'gzip','mtime':0});receipt=json.loads((O/'inventory_receipt.json').read_text());receipt.update({'accepted_carriers':len(ws),'accepted_point_uses':len(points),'actual_raw_native_source_pin':{str(RAW):hashlib.sha256(RAW.read_bytes()).hexdigest()},'no_secondary_sidecar_positive':'Q23976086 has no source coordinate; previous59hold remains','population_or_identity_mutation':False});(O/'acceptance_receipt.json').write_text(json.dumps(receipt,indent=2)+'\n');print(len(ws),len(points))
