from pathlib import Path
import pandas as pd,json,hashlib,xlrd,re
z=Path(__file__).parent.resolve();b=z.parent/'large_existing_credited_south_ownpoints_20261009/batch1_fortythree_ownpoint_uses';sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();x=pd.read_csv(b/'accepted_point_use_delta.csv');r=pd.read_csv(z.parent/'large_existing_credit_missing_ownpoint_20261009/south_exact_roster.csv');rows=[]
for suffix in ['Voronezhskaja.xls:Sheet1:15','KBR.xls:Sheet1:37','KCR.xls:нпп:127']:
 v=x[x.target_source_record_id.str.endswith(suffix)].iloc[0];a=r[r.source_record_id==v.target_source_record_id].iloc[0];f=Path(v.point_origin_file);assert sha(f)==v.point_origin_sha256;j=json.load(open(f));raw=Path('/workspace/settlements-raw')/a.source_file;s=xlrd.open_workbook(str(raw)).sheet_by_name(a.source_record_id.split(':')[-2]);i=int(a.source_record_id.split(':')[-1])-1;native=[dict(physical_row_1based=k+1,literal=s.row_values(k)[:7])for k in range(max(0,i-3),i+1)]
 if isinstance(j,list):
  q=j[0];assert abs(float(q['lat'])-v.latitude)<1e-7 and abs(float(q['lon'])-v.longitude)<1e-7;assert q['category']=='place'and q['type']=='suburb';literal=q;reason='OwnnamedphysicalformerNP/suburb, exacttypedprimaryNP/name andownhistoricalcity/county; pointfield belongsownnode/way notparentwhole. ForUpperKamennomost retainswholejointscope association separately; newpoint genuinelyownformerUpperquarter, notsharedjointcentre.'
 else:
  p=j['query']['pages'];p=p.values()if isinstance(p,dict)else p;pid=int(re.search('page(\\d+)',v.point_origin_locator).group(1));q=next(t for t in p if t.get('pageid')==pid);co=q['coordinates'][0];assert abs(co['lat']-v.latitude)<1e-7 and abs(co['lon']-v.longitude)<1e-7;t=q['revisions'][0]['slots']['main'];txt=t.get('content',t.get('*',''));assert 'Дугулубгей'in txt and '2008'in txt;literal=dict(title=q['title'],coordinates=q['coordinates'],own_infobox_and_lead=txt[:4000]);reason='ProperphysicalSELОownpageinfoboxpoint; explicitformernameДугулубгейuntil2008 bridgesoldnativeДугулубгей toownmodernДыгулыбгей, explicitGOБаксан andoldBaksan sourcecounty. CoordAddon population/type metadata notusedasNPgrainproof.'
 assert v.retrospective_point_use_is_continuity_inference and not v.historical_census_coordinate_asserted
 rows.append(dict(source_record_id=a.source_record_id,stratum='south',selection='FIXED3_OF12',review_status='PASS_OWN_SOURCE_POINT_CLAIM',canonical_delta=str(b/'accepted_point_use_delta.csv'),canonical_delta_sha256=sha(b/'accepted_point_use_delta.csv'),canonical_manifest_sha256=sha(b/'FINAL_manifest.json'),point_origin_file=str(f),point_origin_sha256=sha(f),own_source_literal=literal,native_source_file=str(raw),native_source_sha256=sha(raw),native_primary_hierarchy_literal=native,reason=reason,new_identity_or_event_admission=False,sourcecounts_reaudited=False,historical_measurement_claim=False))
(z/'south_fixed3_literal_reviews.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2,default=str));print('3sourceclaimspass; full12pending')
