import json,hashlib
from pathlib import Path
import pandas as pd
Z=Path(__file__).resolve().parent;E=Z.parent;sha=lambda p:hashlib.file_digest(Path(p).open('rb'),'sha256').hexdigest()
d=pd.read_csv(E/'baseline_fullraw_point_code_conflict_scan_20261008/seven_full3_current_carrier_binding_conflicts.csv',dtype=str);raw=pd.read_parquet(d.point_origin_file.iloc[0],columns=['object_level','object_name','oktmo','population','mun_upper','mun_lower','oktmo_dadata','fias_id_dadata','latitude_dadata','longitude_dadata']);code=lambda x:str(int(float(x)))
for r in d.itertuples():
 own=raw.iloc[int(r.raw_own_row)-1];other=raw.iloc[int(r.other_raw_row)-1];assert own.object_level==other.object_level=='Населенный пункт';assert own.object_name==r.raw_own_label and other.object_name==r.other_label;assert code(own.oktmo)==r.native_own_code and code(other.oktmo)==r.other_code==code(own.oktmo_dadata);assert int(own.population)==int(r.population) and int(other.population)==int(r.other_population);assert own.fias_id_dadata==other.fias_id_dadata;assert (float(own.latitude_dadata),float(own.longitude_dadata))==(float(other.latitude_dadata),float(other.longitude_dadata))==(float(r.latitude),float(r.longitude));assert own.mun_upper==r.raw_own_county and own.mun_lower==r.raw_own_subordinate_context
w=json.loads((Z/'native_point_witnesses.json').read_text());sql=Path('/workspace/settlements-raw/data/raw/historical_classifiers/okato_142_2009/dump-142_2009.sql').read_text().splitlines()
for r in w:assert sql[r['classifier_source_line_1based']-1]==r['classifier_raw_line'] and r['own_OKATO'] in r['classifier_raw_line'] and r['classifier_literal_name'] in r['classifier_raw_line']
geo=pd.read_parquet('/workspace/settlements-work/sources/geokladr_raw_verification/geokladr_okato_2011_raw_parsed.parquet');own=geo[geo.historical_okato.eq('15244844012')].iloc[0];other=geo[geo.historical_okato.eq('15244828015')].iloc[0];assert (own.latitude_from_lat,own.longitude_from_long)==(other.latitude_from_lat,other.longitude_from_long)
held_geo=dict(own_code=own.historical_okato,other_code=other.historical_okato,shared_latitude=own.latitude_from_lat,shared_longitude=own.longitude_from_long,own_record_number=int(own.record_number_1based),other_record_number=int(other.record_number_1based),parsed_geo_file='/workspace/settlements-work/sources/geokladr_raw_verification/geokladr_okato_2011_raw_parsed.parquet',parsed_geo_sha256=sha('/workspace/settlements-work/sources/geokladr_raw_verification/geokladr_okato_2011_raw_parsed.parquet'),raw_geo_file='/workspace/settlements-raw/data/interim/historical_geography/geokladr_okato_2011/okato.dbf',raw_geo_sha256=sha('/workspace/settlements-raw/data/interim/historical_geography/geokladr_okato_2011/okato.dbf'),use='rejected_as_independent_physical_disambiguation_not_admitted')
(Z/'independent_literal_source_checks.json').write_text(json.dumps(dict(status='passed',actual_2021_own_and_other_NP_pairs_checked=7,ownclassifier_literal_rows_checked=len(w),held_roshcha_geopoint_source=held_geo,code_sha256=sha(Path(__file__))),ensure_ascii=False,indent=2)+'\n');print('PASS actual raw own/other NP pairs and literal classifier rows')
