from pathlib import Path
import pandas as pd,duckdb,json,re,ast,unicodedata,hashlib,resource,time,collections
R=Path('/workspace/russian-settlements-research');E=R/'research_rebuild/evidence';B=E/'main_axis_residual_application66_20261008';O=Path(__file__).resolve().parent;START=time.monotonic();C=duckdb.connect(config={'threads':1,'memory_limit':'128MB'});OBS=str(B/'applied_state_observations.parquet');LEFT=str(B/'applied_remaining_primary.csv.gz');SEL='/workspace/settlements-delivery/continuation-consolidated-20261003/selected_observations.parquet'
def normalize(v):return re.sub(r'\s+',' ',str(v or '').lower().replace('ё','е')).strip()
RULE=E/'current_cached_ownarticle_residual_expansion_20261008/review_articles.py';t=ast.parse(RULE.read_text());exec(compile(ast.Module(body=[n for n in t.body if isinstance(n,ast.FunctionDef) and n.name in ['bare','namekey','county','typekey']],type_ignores=[]),str(RULE),'exec'))
allnative=C.execute('select source_record_id,census_year,settlement_name,type_norm,region_norm,district_raw from read_parquet(?) where census_year in(2002,2021) and is_additive_settlement_record',[OBS]).fetchdf();allnative['namekey']=allnative.settlement_name.map(namekey);counties={x:county(x) for x in allnative.district_raw.fillna('').unique()};allnative['countykey']=allnative.district_raw.fillna('').map(counties);neg=collections.defaultdict(list);unplaced=collections.defaultdict(list)
for q in allnative.itertuples(index=False):
 neg[(q.census_year,q.region_norm,q.namekey,q.countykey)].append(q.source_record_id)
 if not q.countykey:unplaced[(q.census_year,q.region_norm,q.namekey)].append(q.source_record_id)
remaining=C.execute('select * from read_csv_auto(?) where census_year in(2002,2021)',[LEFT]).fetchdf();remaining['namekey']=remaining.settlement_name.map(namekey);remaining['countykey']=remaining.district_raw.fillna('').map(lambda x:counties.get(x,county(x)))
T={'деревня','село','поселок','хутор','станица','аул','слобода','починок','выселок','станция','разъезд','населенный пункт','железнодорожный объект','железнодорожная станция','железнодорожный разъезд','поселок при станции','поселок и при станция и'}
old=remaining[remaining.census_year.eq(2002)&remaining.population_scope.isna()&remaining.type_norm.isin(T)];cur=remaining[remaining.census_year.eq(2021)&remaining.has_own_point&~remaining.component_years.astype(str).str.contains(r'(?:^|,)2002(?:,|$)',regex=True)]
idx=collections.defaultdict(list)
for q in old.to_dict('records'):
 if q['countykey']:idx[(q['region_norm'],q['namekey'],q['countykey'])].append(q)
rows=[];matchedcur=set()
for q in cur.to_dict('records'):
 key=(q['region_norm'],q['namekey'],q['countykey'])
 for a in idx.get(key,[]):
  matchedcur.add(q['source_record_id']);cy=set(map(int,str(q['component_years']).split(',')));oy=set(map(int,str(a['component_years']).split(',')));cn=neg[(2021,*key)];on=neg[(2002,*key)];reasons=[]
  if len(cn)!=1:reasons.append('multiple_current_alltype_samecounty_namesakes')
  if len(on)!=1:reasons.append('multiple_2002_alltype_samecounty_namesakes')
  if cy&oy:reasons.append('actual_component_sameyear_overlap')
  ct,ot=typekey(q['type_norm']),typekey(a['type_norm']);exact=ct==ot
  rows.append({'current_source_record_id':q['source_record_id'],'historic_source_record_id':a['source_record_id'],'current_name':q['settlement_name'],'historic_name':a['settlement_name'],'current_type':q['type_norm'],'historic_type':a['type_norm'],'region':q['region_norm'],'closed_name_key':q['namekey'],'closed_county_key':q['countykey'],'current_native_county':q['district_raw'],'historic_native_county':a['district_raw'],'current_population2021':q['population'],'historic_population2002':a['population'],'current_component_root':q['root'],'historic_component_root':a['root'],'current_component_years':str(q['component_years']),'historic_component_years':str(a['component_years']),'current_alltype_samecounty_namesake_count':len(cn),'historic_alltype_samecounty_namesake_count':len(on),'current_alltype_samecounty_namesake_source_IDs_json':json.dumps(cn,ensure_ascii=False),'historic_alltype_samecounty_namesake_source_IDs_json':json.dumps(on,ensure_ascii=False),'current_unplaced_same_region_name_rival_source_IDs_json':json.dumps(unplaced.get((2021,q['region_norm'],q['namekey']),[]),ensure_ascii=False),'historic_unplaced_same_region_name_rival_source_IDs_json':json.dumps(unplaced.get((2002,q['region_norm'],q['namekey']),[]),ensure_ascii=False),'same_exact_type_after_closed_wrappers':exact,'potential_combined_years':','.join(map(str,sorted(cy|oy))),'component_overlap_guard_passed':not bool(cy&oy),'cached_county_uniqueness_guard_passed':len(cn)==len(on)==1,'metadata_hold_reasons':';'.join(reasons),'candidate_only':True,'identity_admission':False,'raw_county_scope_verified_here':False,'population_scope_NULL_not_aggregate_assertion':True})
f=pd.DataFrame(rows);uids=sorted(set(f.current_source_record_id)|set(f.historic_source_record_id));sourcecols=['source_record_id','source_file','source_path','source_sha256','source_locator','population_value_quality','population_scope'];source=C.execute('select '+','.join(sourcecols)+' from read_parquet(?) where source_record_id in(select unnest(?))',[OBS,uids]).fetchdf().set_index('source_record_id');meta=C.execute('select source_record_id,source_sheet,source_row,source_name_raw,entity_grain_status from read_parquet(?) where source_record_id in(select unnest(?))',[SEL,uids]).fetchdf().set_index('source_record_id');pt=C.execute('select source_record_id,latitude,longitude,coordinate_source_record_id,coordinate_admission_status,point_origin_file,point_origin_sha256,point_origin_locator,point_origin_kind,point_ledger_path from read_parquet(?) where source_record_id in(select unnest(?))',[str(B/'applied_point_snapshot.parquet'),uids]).fetchdf().set_index('source_record_id')
for prefix,col in [('current','current_source_record_id'),('historic','historic_source_record_id')]:
 for field in sourcecols[1:]:f[prefix+'_'+field]=f[col].map(source[field].to_dict())
 for field in ['source_sheet','source_row','source_name_raw','entity_grain_status']:f[prefix+'_'+field]=f[col].map(meta[field].to_dict())
 f[prefix+'_canonical_native_raw_locator']=f[col].map(lambda sid:str(source.loc[sid,'source_locator']) if pd.notna(source.loc[sid,'source_locator']) and str(source.loc[sid,'source_locator']).strip() else 'sheet='+str(meta.loc[sid,'source_sheet'])+';row1based='+str(meta.loc[sid,'source_row']))
 f[prefix+'_actual66_accepted_point_json']=f[col].map(lambda sid:json.dumps(pt.loc[sid].to_dict(),ensure_ascii=False,default=str) if sid in pt.index else '')
assert len(matchedcur)==2750,len(matchedcur);out=O/'stage66_current_positive_samecounty_NULL2002_metadata_candidates.csv.gz';f.to_csv(out,index=False,compression={'method':'gzip','mtime':0});counts={}
for k,g in f.groupby('current_component_years'):
 one=g.drop_duplicates('current_source_record_id');eligible=g[g.cached_county_uniqueness_guard_passed&g.component_overlap_guard_passed];eu=eligible.drop_duplicates('current_source_record_id');counts[str(k)]={'all_candidate_pairs':len(g),'current_UIDs':len(one),'current_population2021':int(one.current_population2021.sum()),'unique_cached_county_disjoint_component_pairs':len(eligible),'eligible_current_UIDs':len(eu),'eligible_current_population2021':int(eu.current_population2021.sum()),'exact_type_eligible_pairs':int(eligible.same_exact_type_after_closed_wrappers.sum())}
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();r={'status':'read_only_metadata_candidate_export_no_identity_admission','baseline_stage':66,'candidate_current_UIDs':len(matchedcur),'earlier_full_NULLscope_footprint_current_UIDs':2804,'excluded_current_UIDs_with_only_already_credited_old_counterparts':54,'both_county_keys_nonblank_and_equal_required':True,'name_region_only_or_blank_county_match_allowed':False,'candidate_pairs':len(f),'current_population2021_unique_UIDs':int(f.drop_duplicates('current_source_record_id').current_population2021.sum()),'by_current_component_years':counts,'full_negative_rivals':'All additive native2002/2021 observations acrossALLtypes; cached closed samecounty typed-name counts plus unplaced same-region name rivals. NULLscope allowed. Explicit nonadditive excluded. Sourcecounty metadata is not verified scope evidence.','raw_source_locators':'Canonical originalselected source_sheet/source_row/source_name_raw included; no raw body/header parse, raw point source retesting or source-grade upgrade. Originalsource hash may be blank and author must pin actualraw bytes on admission.','source_grade_and_population_unchanged':True,'source_downloads':0,'State_loads':0,'API_applications':0,'output':{'path':str(out),'sha256':sha(out),'bytes':out.stat().st_size},'input_pins':{str(p):sha(p) for p in [Path(OBS),Path(LEFT),B/'applied_point_snapshot.parquet',Path(SEL),RULE,Path(__file__)]},'seconds':round(time.monotonic()-START,3),'peak_RSS_MB':resource.getrusage(resource.RUSAGE_SELF).ru_maxrss/1024};(O/'stage66_samecounty_NULLscope_candidate_export_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n');print(json.dumps({k:r[k] for k in ['candidate_current_UIDs','candidate_pairs','by_current_component_years','output','peak_RSS_MB','seconds']},ensure_ascii=False));C.close()
