from pathlib import Path
import json,gzip,urllib.request,urllib.parse,urllib.error,ssl,hashlib,datetime
O=Path(__file__).parent;r=json.loads((O/'own_article_locator_witnesses.json').read_text());titles={q:urllib.parse.unquote(sorted(set(v['url']for v in vs if v['url']))[0].split('/wiki/',1)[1]).replace('_',' ')for q,vs in r.items()};url='https://ru.wikipedia.org/w/api.php?'+urllib.parse.urlencode({'action':'query','prop':'revisions|pageprops','titles':'|'.join(titles.values()),'rvprop':'ids|timestamp|content','rvslots':'main','redirects':1,'format':'json','formatversion':2});receipt={'source_titles':titles,'request_url':url,'retrieved_at_UTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'TLS_certificate_verification':True,'API_requests':1,'no_retries':True}
try:
 with urllib.request.urlopen(urllib.request.Request(url,headers={'User-Agent':'RussianSettlementCensusResearch/2026-10-08 (bounded own-article coordinate evidence,21 articles)'}),timeout=30,context=ssl.create_default_context()) as resp:
  receipt['HTTP_status']=resp.status;receipt['headers_exact']=resp.headers.as_string();receipt['Retry_After_exact']=resp.headers.get('Retry-After');raw=resp.read(3000001);assert len(raw)<=3000000;d=json.loads(raw);packed=gzip.compress(raw,mtime=0);p=O/'own_article_API_response.json.gz';p.write_bytes(packed);receipt.update({'source_path':str(p),'source_sha256':hashlib.sha256(packed).hexdigest(),'compressed_bytes':len(packed),'raw_bytes':len(raw),'page_records':len(d.get('query',{}).get('pages',[]))})
except urllib.error.HTTPError as exc:receipt.update({'HTTP_status':exc.code,'headers_exact':exc.headers.as_string(),'Retry_After_exact':exc.headers.get('Retry-After'),'network_hold_no_retry':True})
except Exception as exc:receipt['error']=str(exc)
(O/'article_network_receipt.json').write_text(json.dumps(receipt,indent=2,ensure_ascii=False));print(json.dumps({k:v for k,v in receipt.items() if k not in ('source_titles','request_url','headers_exact')},ensure_ascii=False))
