from pathlib import Path
import sys,json,gzip,re,time,pandas as pd,pyarrow.parquet as pq,duckdb
O=Path(__file__).parent;E=O.parent;ROOT=O.parents[2];sys.path.insert(0,str(ROOT/'research_rebuild/mass_linkage'))
from working_state_20261007 import load,PARTITION_MEMBERS
from current_chain_state_20261007 import sha,normalize,distance_km
T=time.monotonic();s=load(25);f=pd.read_csv(O/'own_article_component_point_screen.csv').fillna('');loc=json.loads((O/'own_article_locator_witnesses.json').read_text());articles=json.loads(gzip.decompress((O/'own_article_API_response.json.gz').read_bytes()));pages={p.get('pageprops',{}).get('wikibase_item'):p for p in articles['query']['pages']};rp=Path('/workspace/settlements-raw/data/interim/2021_tochno/data_allsettlements_anon_156_v20251217.parquet');raw=pq.read_table(rp,columns=['object_level','object_name','oktmo','region','mun_upper','mun_lower','settlement','population','settlement_with_type_dadata','settlement_type_dadata','settlement_dadata','okato_dadata','oktmo_dadata','latitude_dadata','longitude_dadata','qc_geo_dadata']).to_pandas();raw=raw.astype(object).where(pd.notna(raw),None)
credited=set();inputs=[]
for root,g in s.obs.groupby('root'):
 if set(g.census_year)=={2002,2010,2021} and g.population.notna().all() and all(x in s.point_rows for x in g.source_record_id):credited.update(g.source_record_id)
paths=[PARTITION_MEMBERS,E/'additional_complete_partition_application_20261007/accepted_exclusive_member_projection.csv',E/'wikidata_secondary_full3_application_20261007/preapplication_qualified_credit_ids_frozen.csv']+[E/d/'accepted_qualified_physical_observations.csv' for d in ['wikidata_secondary_full3_application_20261007','current_unpointed_own_wiki_mass_application_20261007','existing_event_scope_application_20261007','wikidata_secondary_full3_expansion_application_20261007','remaining_large_own_points_followup_application_20261007','cached_secondary_native_year_mass_application_20261008','additional_uncached_census_histories_application_20261008']]+[E/d/'accepted_constituent_credit_union.csv' for d in ['named_urban_merger_application_20261007','next_named_urban_merger_application_20261007','further_urban_merger_application_20261007','voronezh_closed_roster_application_20261008']]+[E/'native_from_secondary_census_binding_application_20261007/accepted_native_source_id_credit_union.csv',E/'old_native_from_existing_secondary_binding_application_20261007/accepted_native_reference_credit_union.csv']
for p in paths:
 d=pd.read_csv(p,dtype=str).fillna('');inputs.append(p)
 for col in d:
  if 'source_record_id' in col:credited.update(v for v in d[col] if v)
proposals=[];rejections=[];replacements=[];holds=[];contexts=[];credits=[];c=duckdb.connect();geop=Path('/workspace/settlements-work/sources/geokladr_raw_verification/geokladr_okato_2011_raw_parsed.parquet')
for t in f.to_dict('records'):
 q=t['wikidata_id'];sid=t['current_source_record_id'];cur=s.by_id.loc[sid];rnum=int(sid.rsplit(':',1)[1]);rr=raw.iloc[rnum-1].to_dict();assert float(rr['population'])==float(cur.population) and (normalize(rr['object_name'])==normalize(cur.settlement_name) or normalize(rr['object_name']).endswith(' '+normalize(cur.settlement_name))),(q,rnum,rr,cur.settlement_name)
 codes={code for row in loc[q] for code in re.findall(r'\d{8,11}',row['parts'][1]+' '+row['parts'][2])};nativecode=str(cur.oktmo);nativecodes={str(cur.oktmo),str(cur.okato)};positive=bool(codes&nativecodes);ownarticlecodes=set(json.loads(t['article_printed_codes_json']));articlecodepositive=bool(ownarticlecodes&codes);g=s.obs[s.obs.root==s.uf.find(sid)];pointchecks=json.loads(t['active_points_article_distances_json']);wiki=json.loads(t['own_P625_article_distances_json']);p=pages[q];text=p['revisions'][0]['slots']['main']['content'];knownmerge=q=='Q1050596';oldsource=[]
 for point in pointchecks:
  actual=s.point_rows.get(point['source_record_id']);assert actual and actual['latitude']==point['latitude'] and actual['longitude']==point['longitude']
  code=re.search(r'(?:OKATO:|OKATO2011_raw=)(\d{8,11})',str(point.get('coordinate_source_record_id',''))+';'+str(point.get('point_origin_locator','')))
  if code:
   gr=c.execute('select * from read_parquet(?) where historical_okato=?',[str(geop),code[1]]).fetchdf();gr=gr.astype(object).where(pd.notna(gr),None);oldsource.extend(gr.to_dict('records'))
 contexts.append({'qid':q,'current_source_record_id':sid,'selected_native_name':cur.settlement_name,'selected_native_type':cur.settlement_type,'selected_native_region':cur.region_norm,'selected_native_county':cur.district_raw,'selected_native_population':float(cur.population),'selected_native_oktmo':str(cur.oktmo),'selected_native_okato':str(cur.okato),'raw_current_publisher_row_1based':rnum,'raw_current_publisher_row_json':json.dumps(rr,ensure_ascii=False),'raw_current_publisher_source_path':str(rp),'raw_current_publisher_source_sha256':sha(rp),'own_QID_TSV_exact_native_code':positive,'own_article_printed_code_positive':articlecodepositive,'raw_Geo2011_source_rows_json':json.dumps(oldsource,ensure_ascii=False),'source_point_type_MODERN_2011_not_census_coordinate':True})
 reason='';mode='';donor=None;bad=[]
 if not positive:reason='own_native_code_population_item_binding_not_positive'
 elif not t['article_latitude'] or not t['article_longitude']:reason='own_article_has_no_literal_coordinate'
 elif q=='Q13203560':
  ap=(float(t['article_latitude']),float(t['article_longitude']));assert articlecodepositive;mode='both_modern_provider_points_contradicted_by_own_article_literal_DMS_exact_printed_native_code_and_own_county_type';bad=pointchecks;donor={'source_record_id':'Wikipedia:page='+str(t['article_page_id'])+';revision='+str(t['article_revision_id']),'target_source_record_id':sid,'latitude':ap[0],'longitude':ap[1],'coordinate_source_record_id':'Wikipedia:page='+str(t['article_page_id'])+';revision='+str(t['article_revision_id']),'point_origin_file':t['source_article_path'],'point_origin_sha256':t['source_article_sha256'],'point_origin_locator':t['source_article_locator']+';literal_DMS='+t['literal_DMS_fields_json'],'point_origin_kind':'wikipedia_own_article_literal_DMS_point','article_distance_km':0,'coordinate_admission_status':'candidate_own_article_code_context_positive'}
 else:
  ap=(float(t['article_latitude']),float(t['article_longitude']));near=[v for v in pointchecks if v['article_distance_km']<=1.5];far=[v for v in pointchecks if v['article_distance_km']>5];wikinear=[v for v in wiki if v['article_distance_km']<=1.5];donor=min(near,key=lambda v:v['article_distance_km']) if near else None
  if not donor or not far:reason='no_coherent_near_own_article_point_and_clear_contradicted_active_claim'
  elif not wikinear and donor.get('point_origin_kind')=='wikidata_P625_point_claim':reason='current_Wiki_item_coordinate_without_other_positive_point_corroboration'
  else:
   bad=[v for v in far if v.get('point_origin_kind') in ['geokladr_2011_raw_dbf_coordinate','raw_named_typed_geo2011_object','tochno_2021_dadata_raw_parquet_point','wikidata_P625_point_claim']]
   if len(bad)!=len(far):reason='unresolved_frozen_or_other_point_source'
   elif any(v.get('coordinate_admission_status')=='frozen_r5b_reviewed_baseline_preserved' for v in bad):reason='preserve_frozen_individually_reviewed_baseline_point'
   else:mode='contradicted_modern_provider_representative; own_article_literal_point_code_type_county_and_coherent_admitted_donor'
 if reason:holds.append({**t,'hold_reason':reason,'current_native_code_positive':positive,'own_article_printed_code_positive':articlecodepositive});continue
 for v in bad:
  active=s.point_rows[v['source_record_id']];rejections.append({'target_source_record_id':v['source_record_id'],'rejection_status':'candidate_coordinate_claim_only_rejection','old_latitude':v['latitude'],'old_longitude':v['longitude'],'origin_ledger':active['point_ledger_path'],'origin_ledger_sha256':sha(Path(active['point_ledger_path'])),'reason':mode,'provider_identifier_binding_status':'UNKNOWN; coordinate correctness resolved separately from provider identifier binding','old_point_json':json.dumps(active,ensure_ascii=False),'own_article_revision_id':t['article_revision_id'],'own_article_point_distance_km':v['article_distance_km'],'candidate_only':True})
  replacement={k:z for k,z in donor.items() if k not in ['source_record_id','article_distance_km','point_ledger_path']};replacement.update({'target_source_record_id':v['source_record_id'],'coordinate_admission_status':'candidate_reviewed_extension_rule','review_rule':mode,'independent_own_article_path':t['source_article_path'],'independent_own_article_sha256':t['source_article_sha256'],'independent_own_article_locator':t['source_article_locator'],'independent_own_article_latitude':ap[0],'independent_own_article_longitude':ap[1],'coordinate_temporal_interpretation':'Modern own representative applied retrospectively to native accepted identity; no census-date measurement or boundary harmonization assertion','candidate_only':True});replacements.append(replacement)
 full3eligible=not knownmerge and set(g.census_year)=={2002,2010,2021} and g.population.notna().all()
 proposals.append({'wikidata_id':q,'current_source_record_id':sid,'name':cur.settlement_name,'current_population':float(cur.population),'proposal':mode,'rejected_targets_json':json.dumps([v['source_record_id']for v in bad]),'donor_source_record_id':donor['source_record_id'],'donor_article_distance_km':donor['article_distance_km'],'maximum_rejected_article_distance_km':max(v['article_distance_km']for v in bad),'article_printed_code_positive':articlecodepositive,'native_code_own_QID_positive':positive,'known_post2002_constituent_merger':knownmerge,'qualified_native_full3_eligible_no_ordinary_assertion':full3eligible,'secondary_missingyear_sourceproof_not_yet_selected':not full3eligible and not knownmerge,'boundary_comparability':'UNKNOWN','historical_point_direct_measurement_asserted':False,'candidate_only':True})
 if full3eligible:
  for n in g.itertuples():credits.append({'source_record_id':n.source_record_id,'year':int(n.census_year),'source_population':float(n.population),'wikidata_id':q,'already_credited':n.source_record_id in credited,'net_new_selected_ID_potential':n.source_record_id not in credited,'candidate_only':True})
 elif knownmerge:holds.append({**t,'hold_reason':'coordinate_correction_proposed_only; literal_own_article_2005_merger_changes2002_territorial_grain; no ordinary_or_qualified_full3_admission','current_native_code_positive':positive,'own_article_printed_code_positive':articlecodepositive})
for name,data in [('coordinate_rejection_proposals.csv',rejections),('coordinate_replacement_proposals.csv',replacements),('candidate_resolved_components.csv',proposals),('held_components.csv',holds),('native_provider_code_and_raw_point_checks.csv',contexts),('qualified_native_source_ID_net_potential.csv',credits)]:pd.DataFrame(data).to_csv(O/name,index=False)
cr=pd.DataFrame(credits);receipt={'status':'coordinate_and_qualified_native_potential_only','baseline_stage':25,'own_articles_directly_examined':21,'source_API_requests':1,'HTTP_status':200,'coordinate_correction_proposed_components':len(proposals),'coordinate_claim_rejections_proposed':len(rejections),'replacement_points_proposed':len(replacements),'literal_coordinate_or_samegrain_holds':len(holds),'qualified_native_full3_series_ready':int(sum(p['qualified_native_full3_eligible_no_ordinary_assertion']for p in proposals)),'qualified_native_source_ID_net_potential':{str(y):{'rows':int(g.net_new_selected_ID_potential.sum()),'population':int(g.loc[g.net_new_selected_ID_potential,'source_population'].sum())}for y,g in cr.groupby('year')},'actual_admitted_gain':0,'ordinary_edges_or_points_applied':0,'boundary_comparability':'UNKNOWN','error_rate':'uncalibrated','coordinate_provider_binding':'UNKNOWN kept separate from coordinate correctness','wall_seconds':time.monotonic()-T,'source_pins':{str(p):sha(p)for p in dict.fromkeys(s.inputs+paths+[rp,geop,O/'own_article_API_response.json.gz',O/'own_article_locator_witnesses.json',O/'article_network_receipt.json',Path(__file__)])},'outputs':{p.name:sha(p) for p in O.glob('*.csv')}};(O/'receipt.json').write_text(json.dumps(receipt,indent=2,ensure_ascii=False));print(json.dumps({k:v for k,v in receipt.items()if k not in ['source_pins','outputs']},ensure_ascii=False))
