from pathlib import Path
import pandas as pd,json,sys
O=Path(__file__).parent;ROOT=O.parents[2];sys.path.insert(0,str(ROOT/'research_rebuild/mass_linkage'));from working_state_20261007 import load
from current_chain_state_20261007 import sha
s=load(25);f=pd.read_csv(O/'candidate_resolved_components.csv').fillna('');screen=pd.read_csv(O/'own_article_component_point_screen.csv').set_index('wikidata_id');rows=[];sourcepins={}
for t in f[f.qualified_native_full3_eligible_no_ordinary_assertion].to_dict('records'):
 q=t['wikidata_id'];curid=t['current_source_record_id'];g=s.obs[s.obs.root==s.uf.find(curid)];point=s.point_rows[curid];ar=screen.loc[q];assert set(g.census_year)=={2002,2010,2021};assert q not in ['Q1050596','Q18807511'];assert t['native_code_own_QID_positive']
 for n in g.itertuples():
  assert n.is_additive_settlement_record and pd.notna(n.population);path=Path('/workspace/settlements-raw/'+str(n.source_file));rawhash=sha(path)if path.is_file()else '';sourcepins[str(path)]=rawhash;loadedhash=''if pd.isna(n.source_sha256)else str(n.source_sha256)
  r={'trajectory_id':'resolved_modern_provider_native:'+q,'year':int(n.census_year),'population_source_value':float(n.population),'source_record_id':n.source_record_id,'settlement_name':n.settlement_name,'region_norm':n.region_norm,'county_context':n.district_raw,'latitude':point['latitude'],'longitude':point['longitude'],'population_quality':n.population_value_quality,'grain':'own physical locality existing accepted-component native census observation','nonadditive_observation':False,'source_path':str(path),'source_sha256':loadedhash,'source_locator':'selected own census source_record_id='+n.source_record_id,'decision_status':'candidate_only_after_coordinate_rejection_application','ordinary_NP3_asserted':False,'boundary_comparability_asserted':False,'point_binding_json':json.dumps(point,ensure_ascii=False),'retrospective_point_use_is_continuity_inference':int(n.census_year)!=2021,'selected_source_sha256_as_loaded':loadedhash,'scope':'remaining_large_current_component_point_conflicts_20261008','boundary_comparability':'UNKNOWN','wikidata_id':q,'declared_date':f'+{int(n.census_year)}-00-00T00:00:00Z','date_precision':9,'census_proof_class':'existing_selected_native_census_row_in_accepted_own_NP_component','census_reference_titles_json':'[]','P248_ids_json':'[]','P248_labels_json':'[]','P459_method_ids_json':'[]','reference_urls_json':'[]','statement_id':'','own_item_binding':'exact_existing_native_code_own_article_QID_type_county_current_publisher_row','optional_Wiki_coordinates_imported':False,'coordinate_bounds':'UNKNOWN','error_rate':'uncalibrated','accepted_physical_three_observed_census_year_path':False,'candidate_physical_three_observed_census_year_path':True,'accepted_scoped_representative_point':False,'historical_native_selected_source_ID_binding_asserted':int(n.census_year)!=2021,'population_primary_reference_verified':False,'native_current_source_record_id':curid,'native_existing_component_binding':True,'native_population_scope_legacy_null':pd.isna(n.population_scope),'native_raw_file_sha256_checked':rawhash,'native_raw_source_missing_flag':not path.is_file(),'native_source_context_json':json.dumps({'source_record_id':n.source_record_id,'name':n.settlement_name,'type':n.settlement_type,'region':n.region_norm,'county':None if pd.isna(n.district_raw)else n.district_raw,'population':float(n.population),'quality':n.population_value_quality,'scope':None if pd.isna(n.population_scope)else n.population_scope,'source_file':str(n.source_file)},ensure_ascii=False),'own_article_revision_id':ar.article_revision_id,'own_article_coordinate_source_path':ar.source_article_path,'own_article_coordinate_source_sha256':ar.source_article_sha256,'own_article_coordinate_source_locator':ar.source_article_locator,'own_article_literal_latitude':ar.article_latitude,'own_article_literal_longitude':ar.article_longitude,'historical_point_direct_measurement_asserted':False,'conditional_coordinate_claim_rejections_required':True}
  for k in ['point_origin_file','point_origin_sha256','point_origin_locator']:r[k]=point.get(k,'')
  rows.append(r)
pd.DataFrame(rows).to_csv(O/'review_ready_qualified_native_observations.csv',index=False);checks=pd.read_csv(O/'native_provider_code_and_raw_point_checks.csv');checks['status']='checked_actual_raw_current_row_code_type_name_population_and_article_own_QID_literal_point; candidate_only';checks.to_csv(O/'bounded_all21_source_checks.csv',index=False)
r=json.loads((O/'receipt.json').read_text());r['native_projected_observations']=len(rows);r['native_population_count_quality_checks']=len(rows);r['bounded_all21_raw_current_and_article_source_checks']=21;r['actual_secondary_missingyear_proofs']=0;r['native_raw_source_pins']=sourcepins;r['historical_scope_holds']=['Shafranovo literal2005threeconstituentmerger','Yubileyny creationact13Nov2002 aftercensus'];r['outputs'].update({p.name:sha(p)for p in O.glob('*.csv')});r['source_pins'].update({str(p):sha(p)for p in [O/'project_native_sidecar.py',O/'own_article_event_scope_snippets.json',O/'missing_year_proof.py',O/'census_reference_label_source_witnesses.json']});tmp=O/'receipt.tmp';tmp.write_text(json.dumps(r,indent=2,ensure_ascii=False));tmp.replace(O/'receipt.json');print({'native_projected_observations':len(rows),'CSV_sha':sha(O/'review_ready_qualified_native_observations.csv'),'evidence_total_bytes':sum(p.stat().st_size for p in O.iterdir()if p.is_file())})
