from pathlib import Path
import pandas as pd,json,hashlib,xlrd,shutil
E=Path('/workspace/russian-settlements-research/research_rebuild/evidence');O=E/'nakhoda_complete_published_scope_aux5_20261008';P=Path('/workspace/settlements-raw/data/raw/2002/079_983a1a85f7_Primor_krai_1.xls');sh=xlrd.open_workbook(str(P)).sheet_by_name('Sheet1');raw=sh.row_values(34);assert raw[1].strip()=='маяк Поворотный' and int(raw[2])==5;h=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
aux={'raw_file':str(P),'raw_sha256':h(P),'raw_sheet':'Sheet1','raw_row_1based':35,'raw_label':raw[1].strip(),'raw_type':'маяк','population':5,'selected_source_record_id':'','population_quality':'direct_primary_census_named_atomic_leaf_absent_selectedNP_layer','national_additive_credit':False,'geometry_scope':'existingcurrentНаходка receivingcityrepresentative point representscomplete publishedterritory only; historicalindividual маякcoordinate notasserted','raw_original_row_json':json.dumps(raw,ensure_ascii=False)}
pd.DataFrame([aux]).to_csv(O/'actual_primary_auxiliary2002_atom.csv',index=False)
m=pd.read_csv(O/'candidate_constituent_credit_union.csv',keep_default_na=False);m['nonadditive_auxiliary_raw_atom']=m.source_record_id.eq('');m['native_selected_ID_credit']=m.source_record_id.ne('');m['exclusive_source_ID_credit']=m.source_record_id.ne('');m.to_csv(O/'candidate_constituent_credit_union.csv',index=False)
g=pd.read_csv(O/'candidate_group_observations.csv',keep_default_na=False)
for i,r in g.iterrows():
 members=m[m.census_year.eq(r.census_year)];native=members.source_record_id.ne('');g.loc[i,'native_selected_member_count']=int(native.sum());g.loc[i,'actual_primary_auxiliary_member_count']=int((~native).sum());g.loc[i,'native_selected_population_sum']=int(members.loc[native,'population'].sum());g.loc[i,'actual_primary_auxiliary_population_sum']=int(members.loc[~native,'population'].sum());g.loc[i,'auxiliary_primary_provenance_json']=json.dumps(aux,ensure_ascii=False) if r.census_year==2002 else '{}'
 assert g.loc[i,'native_selected_population_sum']+g.loc[i,'actual_primary_auxiliary_population_sum']==r.population
 assert set(json.loads(r.source_record_ids_json))==set(members.loc[native,'source_record_id'])
g.to_csv(O/'candidate_group_observations.csv',index=False)
assert list(g.sort_values('census_year').population)==[178813,160760,141035];assert len(m)==15 and m.source_record_id.eq('').sum()==1 and m.source_record_id.ne('').sum()==14
proof=[];books={}
for r in m[m.census_year.isin([2002,2010])].itertuples():
 if not r.source_file.endswith('.xls'):continue
 if r.source_file not in books:books[r.source_file]=xlrd.open_workbook(r.source_file)
 sn,n=r.source_row_locator.split('!row_1based=');s=books[r.source_file].sheet_by_index(0) if sn=='0' else books[r.source_file].sheet_by_name(sn);rr=s.row_values(int(float(n))-1)
 if r.census_year==2010:idx=4;value=int(rr[5])
 else:idx=next(i for i,z in enumerate(rr) if isinstance(z,str) and r.settlement_name.lower().replace('ё','е') in z.lower().replace('ё','е'));value=int(float(rr[idx+1]))
 assert value==r.population;proof.append({'source_record_id':r.source_record_id,'year':r.census_year,'label_raw':rr[idx],'raw_type':r.settlement_type,'population':value,'source_file':r.source_file,'source_sha256':r.source_file_sha256,'source_locator':r.source_row_locator,'raw_original_row_json':json.dumps(rr[:11],ensure_ascii=False),'selected_native_ID_credit':bool(r.source_record_id),'population_values_unmodified':True})
pd.DataFrame(proof).to_csv(O/'original_atomic_source_row_verification.csv',index=False)
pd.DataFrame([{'group':g.iloc[0].group,'from_observation_id':g[g.census_year.eq(a)].iloc[0].observation_id,'to_observation_id':g[g.census_year.eq(b)].iloc[0].observation_id,'relation':'complete_published_city_territorial_hierarchy_trace','ordinary_same_place':False,'boundary_comparability':'UNKNOWN','candidate_only':True,'exact_annexation_roster_claimed':False,'event_relations_effective_date':'UNKNOWN'} for a,b in [(2002,2010),(2010,2021)]]).to_csv(O/'candidate_scope_edges.csv',index=False)
p=O/'candidate_receipt.json';r=json.loads(p.read_text());r.update(actual2002_complete_scope_decomposition={'selected_native_atomic_population':178808,'actual_direct_primary_auxiliary_named_leaf_population':5,'complete_published_scope':178813},national_auxiliary_population_credit=0,all_original_xls_atomic_rows_reopened=len(proof),primary2010_and2021_control_exact=True,unselected_auxiliary_observation_never_assigned_nativeID=True,geometry_scope='Current admittedownНаходкаcity representative point forcompleteassociatedterritory; neverhistoricalindividual маяк/town point');r['outputs']={p.name:h(p) for p in O.glob('*.csv')};r['baseline_25_inputs_sha256']={str(p):h(p) for p in [E/'working_full_chain_20261007/coverage_receipt.json',E/'working_full_chain_20261007/qualified_scope_source_id_credit_union.csv',E/'working_full_chain_20261007/named_merger_lineage_constituents.csv',E/'working_full_chain_20261007/complete_publisher_partition_members.csv']};p.write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n')
for name in ['build.py','finalize.py']:shutil.copy(Path('/workspace/settlements-work/nakhoda_complete_published_scope_aux5_20261008')/name,O/name)
(O/'README.md').write_text('''# Находка complete publishedterritory with actualprimaryauxiliary5, candidate only\n\nOne actualthree-census territorialtrace:178813(2002),160760(2010),141035(2021);15 atomicobservations,14 native selectedIDs andone actualdirectprimary2002namedleaf absentselectedNP layer. Potentialnational selected-IDgain2002=28864(3IDs:Врангель15346,Ливадия12961,Козьмино557),2010/2021zero. Actualprimaryauxiliary5 earns zero selectedcredit.\n\n2002complete scope is178808native atomicpopulation +actualprimary маякПоворотный5. Originalcensus2002 PrimorregionalXLS Sheet1row35 explicitlyprints namedtype маякПоворотный, count5, under пгтВрангель withinНаходка. Rawtype/label/count/filehash/row andcompletegeometryscope arepreserved; blank selectedID/nonadditive=true. NoinventednativeID/zero/partial reconstruction.\n\nFederal2002city/subordinates178813 closes3urban +Анна518,Козьмино557,маякПоворотный5,Душкино600. 2010wholecityhierarchy160760 closes nativeprimaryowncity159719 +rawclosed3rural NPblock563/86/392=1041. Protected cityalternative159010 retainedseparately, not substituted. Raw2021parent141035 hasexactlycity139931 plus3rural119/390/595, allnativevalues unchanged. Both2010/2021controls exact.\n\nCurrentownreceivingcitypoint is representative_scope forcomplete territoryonly; nohistoricalindividual маяк orformer-town coordinate assertion. BoundariesUNKNOWN, changingcompositionallowed, noexactannexation/legalroster claim. Candidateonly; noaccepted/helper/loader/report/Git mutations. Reproduce build.py thenfinalize.py.\n''');print('members15/native14/aux1',list(g.sort_values('census_year').population),'bytes',sum(p.stat().st_size for p in O.iterdir() if p.is_file()))
