from pathlib import Path
import pandas as pd,json,hashlib,math
Z=Path(__file__).parent;B=Z/'batch1_source_ready';B.mkdir(exist_ok=True);A=Z.parent/'main_axis_residual_application68_20261008';o=pd.read_parquet(A/'applied_state_observations.parquet');sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();uid='2002:061_e177b0a77d_Chel_abinskaja1.xls:Sheet1:263';a=o[o.source_record_id.eq(uid)].iloc[0].to_dict();assert a['population']==2219 and a['settlement_name']=='Приуральский';wiki=Z/'wiki_initial.json';p=next(p for p in json.loads(wiki.read_text())['query']['pages'] if p['title']=='Приуральский (Челябинская область)');assert p['pageprops']['wikibase_item']=='Q15254859';scope='last_priuralsky_included_magnitogorsk';rid='2021:data_allsettlements_anon_156_v20251217.parquet:parquet:161421';b=o[o.source_record_id.eq(rid)].iloc[0].to_dict();lat=53.327274;lon=58.990761;locator='page7979610:revision152591868; ownNPinfoboxlat_deg53.327274lon_deg58.990761; ownnameposelokAgapovsky; historyincludedMagnitogorsk2004'
rule='UniqueChelyabinskownname/typeАгаповский/Приуральскийcouncil native2002row263. OwnarticleQ15254859explicitformerПриуральскийАгаповский and owndecimalpoint; sourcearticle2219native2002statementcorroborates notidentitybyequalpopulation. DistinctПриморский2002row259underПриморскийcouncil andcurrent159913 excluded;Komi/Orenburgsame-nameplaceexcludedbyregion. OwnhistoricalNPpointnotreceivingMagnitogorskpoint. Secondaryownarticleexplicitexclusion/inclusion2004 citesЗСЧелябинской29.04.2004No1218; primaryportalHTTP503,primaryactnotreopened. Laterindividualpublishedchildcountsunknownnotzero; nowholecityallocation.'
point=dict(target_source_record_id=uid,latitude=lat,longitude=lon,coordinate_admission_status='reviewed_rule_accepted',coordinate_source_record_id='Wikipedia:Q15254859:revision152591868',point_origin_file=str(wiki),point_origin_sha256=sha(wiki),point_origin_locator=locator,point_origin_kind='own_former_locality_Wikipedia_infobox_decimal_point',admission_rule=rule,own_locality_point=True,recipient_point_assigned_to_child=False,retrospective_point_use_is_continuity_inference=True,direct_historical_coordinate_measurement=False,historical_census_coordinate_asserted=False,provider_identifier_binding_asserted=False,coordinate_time_interpretation='ownformerNPmodernrepresentativepoint reused2002 asphysicalcontinuityinference; exactcensusdaymeasurementunknown',population_values_modified=False)
event=dict(scope_id=scope,former_locality='Приуральский',recipient_city='Магнитогорск',event_date='2004',date_precision='year',relation='included_in',same_place=False,event_source_file=str(wiki),event_source_sha256=sha(wiki),event_source_locator='page7979610:revision152591868; ownliteralhistory exclusion2004and includedMagnitogorsk; citedact29.04.2004No1218',event_source_quality='secondary_own_Wikipedia_literal_dated_inclusion',event_date_role='reportedexclusionandinclusionyear; citedactdate2004-04-29separatefromeffectiveeventdate',decision_status='accepted_secondary_own_article_included_in',primary_law_source_reopened=False,primary_act_url='https://docs.cntd.ru/document/802010433',primary_act_attempt_status='HTTP503Unavailable',boundary_comparability='UNKNOWN',roster_closed=False,sum_city_equals_children_asserted=False)
credit=dict(scope_id=scope,source_record_id=uid,year=2002,source_population=a['population'],new_population_on_separate_transformation_path_axis=a['population'],own_historical_point_verified=True,receiving_city_actual_2002_2010_2021_context_verified=True,is_additive_to_original_final_mixed_census_axis=False,ordinary_three_census_same_place_claim=False)
hist=dict(scope_id=scope,place='Приуральский',year=2002,source_record_id=uid,native_population=a['population'],native_population_quality=a['population_value_quality'],latitude=lat,longitude=lon,own_point=True,recipient_city='Магнитогорск',event_date='2004',event_date_precision='year',event_relation='included_in',same_place_identity_asserted=False,receiving_city_2021_source_record_id=rid,receiving_city_2021_count_context_only=b['population'],child_2021_population_assigned=False,is_additive_to_original_final_mixed_census_axis=False,already_in_baseline68_primary_native_ID_union=False,new_native_population_if_event_admitted=a['population'],whole_city_roster_closure_asserted=False,population_boundary_comparability_asserted=False,native_values_quality_preserved=True)
scopes=[];checks=[]
for year in [2002,2010,2021]:
 q=o[o.region_norm.eq('челябинская')&o.census_year.eq(year)];m=q[q.name_norm.str.contains('приураль|приморск|магнитогорск',na=False)];checks.append(dict(census_year=year,region='челябинская',selected_native_region_record_count=len(q),exact_knownalias_receiver_rivals_UIDs=json.dumps(m.source_record_id.tolist()),scope='completecertified68selectedregionalnativepublication; unknownchildcountnotzero; aggregateпрочие28218not allocated'))
 scopes.append(dict(scope_id=scope,census_year=year,source_record_id=uid if year==2002 else '',available_year_status='native_finite_historical_observation_ownpoint_accepted' if year==2002 else 'individual_child_published_count_unavailable_after_reported_inclusion;unknown_not_zero',decision_status='checked_rule_accepted',receiver_context_source_record_id=rid if year==2021 else '',rule=rule))
pd.DataFrame(checks).to_csv(B/'complete_selected_native_publication_scope_checks.csv',index=False)
for fn,rows in [('accepted_point_use_delta.csv',[point]),('accepted_inclusion_events.csv',[event]),('accepted_direct_event_native_credit_union.csv',[credit]),('accepted_historical_observations.csv',[hist]),('accepted_actual_available_year_observations.csv',[dict(a,scope_id=scope,decision_status='checked_rule_accepted',native_values_quality_preserved=True)]),('accepted_actual_available_year_scopes.csv',scopes),('accepted_typed_context_edges.csv',[dict(scope_id=scope,from_source_record_id=uid,to_source_record_id=rid,from_year=2002,to_year=2021,relation='included_in',decision_status='checked_typed_context_accepted',graph_union_allowed=False,same_place=False,child_population_assigned=False,rule=rule)]),('reviewed_wrong_fuzzy_link_rejections.csv',[dict(from_source_record_id=uid,rejected_to_source_record_id='2021:data_allsettlements_anon_156_v20251217.parquet:parquet:159913',relation='same_place',decision_status='reviewed_wrong_name_own_source_competitor_rejected',rule='2002ownПриморскийrow259 andПриуральскийrow263distinctcouncils; nofuzzyaliasadmission')])]:pd.DataFrame(rows).to_csv(B/fn,index=False)
pd.DataFrame(columns=['from_source_record_id','to_source_record_id','relation','decision_status']).to_csv(B/'accepted_identity_edge_delta.csv',index=False)
o[o.region_norm.eq('челябинская')&o.name_norm.eq('магнитогорск')].to_csv(B/'receiver_native_observations_context_only.csv',index=False)
prior=Z.parent/'over1000_rest_20261009/A112_v34_final_four_uid_source_scopes';inputs=[p for p in Z.iterdir() if p.is_file() and p.suffix in ['.json','.csv','.xml','.html']]+[A/'applied_state_observations.parquet',Path('/workspace/settlements-raw/data/raw/2002/061_e177b0a77d_Chel_abinskaja1.xls')]+[prior/f for f in ['receipt.json','README.md','source_observation_witnesses.csv','unresolved_scope_status.csv']];pins=lambda fs:{str(f):dict(sha256=sha(f),bytes=f.stat().st_size) for f in fs};(B/'FINAL_manifest.json').write_text(json.dumps(dict(status='FINAL_FROZEN_SOURCE_READY',native_UIDs=1,native_raw_population=2219,own_points=1,direct_event_path_credits=1,ordinary_same_place_edges=0,raw_population_quality_modified=False,recipient_points_projected=False,no_child_count_allocation=True,input_pins=pins(inputs),output_pins=pins(list(B.glob('*.csv')))),ensure_ascii=False,indent=2));print('FINAL lastПриуральский2219ready')
