from pathlib import Path
import pandas as pd,xlrd,json,hashlib,datetime,time,resource,duckdb
O=Path(__file__).parent;PACK=O.parent;OLD=PACK/'history_proposals';F=OLD/'raw_verified_five_history_counterpart_proposals.csv.gz';f=pd.read_csv(F,dtype=str,keep_default_na=False);sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();pins={str(F):sha(F)};out=[];start=time.monotonic();east=Path('/workspace/settlements-raw/data/raw/2010/009_81f8a0e73c_17._20ДВ_ФО_2010.xls');pins[str(east)]=sha(east);b=xlrd.open_workbook(str(east),on_demand=True);s=b.sheet_by_name('ДВ')
for z in f.to_dict('records'):
 if z['current_settlement_name'].startswith('Хемчик'):continue
 rn=int(z['historic_source_record_id'].rsplit(':',1)[1]);begin=720 if rn==721 else 751;end=731 if rn==721 else 785
 assert begin<=rn<end;assert s.cell_value(begin-1,3)==z['historical_county_header_literal'];assert str(s.cell_value(end-1,3)).strip() and s.cell_value(end-1,3)!=s.cell_value(begin-1,3);assert all(not str(s.cell_value(i,3)).strip() for i in range(begin,end-1));assert s.cell_value(begin-1,2)==s.cell_value(end-1,2)
 z.update(scope_revision='positive2010sourcecountyblockboundedbynextprintedcountytransition_samepublishedregion',source_county_block_start_onebased=begin,source_county_block_end_exclusive_onebased=end,source_county_block_end_header_row_json=json.dumps(s.row_values(end-1),ensure_ascii=False),source_hierarchy_independent_county_binding_established=True,prior_naive_county_carry_superseded=True,status='RAW_SOURCE_BOUND_COUNTERPART_PROPOSAL_NOT_IDENTITY_ADMISSION');out.append(z)
b.release_resources();del b,s
p=Path('/workspace/settlements-raw/data/raw/2002/064_d017f142fc_Tyva.xls');pins[str(p)]=sha(p);b=xlrd.open_workbook(str(p),on_demand=True);s=b.sheet_by_name('Sheet1');z=next(z for z in f.to_dict('records') if z['current_settlement_name'].startswith('Хемчик'));assert '2002:064_d017f142fc_Tyva.xls:Sheet1:40' in json.loads(z['historic_component_members_json']);assert s.cell_value(2,0).strip()=='Бай-Тайгинский кожуун - все сельское население';assert s.cell_value(38,0).strip()=='Хемчикский сумон';assert s.cell_value(39,0).strip()=='село Хемчик';nextcounty=next(i+1 for i in range(40,s.nrows) if 'кожуун - все сельское население' in str(s.cell_value(i,0)));assert nextcounty>40
RAW='/workspace/settlements-raw/data/interim/2021_tochno/data_allsettlements_anon_156_v20251217.parquet';rn=int(z['current_source_record_id'].rsplit(':',1)[1]);c=duckdb.connect();native=c.execute('select * from (select row_number() over() rn,object_level,object_name,region,mun_upper,mun_lower,oktmo from read_parquet(?)) where rn=?',[RAW,rn]).fetchdf().to_dict('records')[0];c.close();assert native['mun_upper']=='Бай-Тайгинский муниципальный район' and native['mun_lower']=='Сельское поселение Хемчикский';pins[RAW]=sha(RAW)
z.update(scope_revision='2010countycarryinsufficient_replaced_byexistingaccepted2002_2010historicalcomponent2002explicitcountyandspecificsumon',historical_raw_source_county_2010_binding_asserted=False,historical_county_positive_member_source_record_id='2002:064_d017f142fc_Tyva.xls:Sheet1:40',historical_county_positive_raw_origin_file=str(p),historical_county_positive_raw_origin_sha256=pins[str(p)],historical_county_positive_raw_origin_locator='Sheet1:countyrow3;parishrow39;physicalNProw40',historical_county_positive_raw_county_row_json=json.dumps(s.row_values(2),ensure_ascii=False),historical_county_positive_raw_parish_row_json=json.dumps(s.row_values(38),ensure_ascii=False),historical_county_positive_raw_NP_row_json=json.dumps(s.row_values(39),ensure_ascii=False),historical_2002_county_block_end_exclusive_onebased=nextcounty,current_primary_native_row_reopened_json=json.dumps(native,ensure_ascii=False),specific_parish_bridge='literal proper Хемчикский:2002 Хемчикский сумон;2021 Сельское поселение Хемчикский; samepropercounty typed селоХемчик; acceptedold2002_2010identity retained',source_hierarchy_independent_county_binding_established=True,prior_naive_county_carry_superseded=True,status='RAW_SOURCE_BOUND_COUNTERPART_PROPOSAL_NOT_IDENTITY_ADMISSION');out.append(z);b.release_resources();del b,s
pd.DataFrame(out).sort_values('current_population2021',key=lambda x:pd.to_numeric(x,errors='coerce'),ascending=False).to_csv(O/'scope_verified_five_history_counterpart_proposals.csv.gz',index=False,compression={'method':'gzip','mtime':0});r={'source_bound_proposals':5,'unique_current_population2021':922,'naive_last_nonblank_county_cell_is_not_identity_evidence':True,'scope_verified2010bounded_county_blocks':4,'scope_verified_existing2002_2010component2002_county_and_specific_parish':1,'immutable_prior_proposal_packet_preserved_not_admitted':True,'input_pins':pins,'seconds':time.monotonic()-start,'peak_RSS_MB':resource.getrusage(resource.RUSAGE_SELF).ru_maxrss/1024,'identity_edges_or_point_uses_admitted':0};(O/'scope_revision_receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2));manifest={str(p):sha(p) for p in O.iterdir() if p.is_file()};(O/'frozen_scope_asset_manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2));print(json.dumps(r,ensure_ascii=False));print('manifest',sha(O/'frozen_scope_asset_manifest.json'))
