from pathlib import Path
import pandas as pd,json,gzip,hashlib,xlrd,io
O=Path(__file__).parent;sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();sid='2021:data_allsettlements_anon_156_v20251217.parquet:parquet:163719';ledger=Path('/workspace/russian-settlements-research/research_rebuild/evidence/main_axis_residual_application64_20261008/accepted_point_use_delta.csv.gz');old=pd.read_csv(ledger,keep_default_na=False).set_index('target_source_record_id').loc[sid];article=Path(old.point_origin_file);J=json.load(gzip.open(article));p=next(p for p in J['query']['pages']if p['pageid']==9115140);assert p['title']=='Чиршкасы (Синьяльское сельское поселение)';txt=p['revisions'][0]['slots']['main']['content'];assert 'Синьяльское сельское поселение' in txt
F=Path('/workspace/settlements-raw/data/interim/2021_tochno/data_allsettlements_anon_156_v20251217.parquet');raw21=pd.read_parquet(F,columns=['oktmo','mun_lower','settlement','population','latitude_dadata','longitude_dadata','oktmo_dadata','okato_dadata']);own=raw21.iloc[163718];sinyal=raw21.iloc[163711];assert str(own.oktmo)=='97644482101'and 'Чиршкасинское' in own.mun_lower and str(sinyal.oktmo)=='97644460156'and 'Синьяльское' in sinyal.mun_lower
B=Path('/workspace/settlements-raw/data/raw/2002/046_228ab1ba5a_Chuvashia_1.xls');sh=xlrd.open_workbook(str(B)).sheet_by_name('Sheet1');assert 'Чиршкасинский сельсовет' in str(sh.row_values(1770));assert 'Чиршкасы' in str(sh.row_values(1771));reason='Wrong actualownplace homonym: target2021ownOKTMO97644482101 explicitlyЧиршкасинскоеСП (504), but activepoint ownarticlepage9115140 is explicitlyСиньяльскоеСП, corresponding to distinctcurrentrow163712/97644460156 (91). Nativeold2002Чиршкасы1772 also explicitlyunderЧиршкасинскийсельсовет. InheritedDaData/Q18806434 binding resolveswrongSinyalhomonym; knownwrongcoordinate withdrawn, no population or identity change.'
w=dict(target_source_record_id=sid,active_point_ledger=str(ledger),active_point_ledger_sha256=sha(ledger),active_point_row=old.to_dict(),wrong_point_article_file=str(article),wrong_point_article_sha256=sha(article),actual_wrong_article_page=p,native2021_file=str(F),native2021_sha256=sha(F),target_native_ownrow_1based=163719,target_native_ownfields=own.fillna('').to_dict(),distinct_sinyal_native_ownrow_1based=163712,distinct_sinyal_native_ownfields=sinyal.fillna('').to_dict(),old_native2002_file=str(B),old_native2002_sha256=sha(B),old_native2002_target_row0=1771,old_native2002_target_cells=sh.row_values(1771),old_native2002_parent_row0=1770,old_native2002_parent_cells=sh.row_values(1770),reason=reason,replacement_found=False,source_probe_receipt='own_chirshkasinsky_query_receipt.json')
with gzip.open(O/'wrong_homonym_rejection_witness.json.gz','wt')as f:json.dump([w],f,ensure_ascii=False)
r=dict(target_source_record_id=sid,rejection_status='reviewed_rejected_coordinate_claim_only',old_latitude=old.latitude,old_longitude=old.longitude,origin_ledger=str(ledger),origin_ledger_sha256=sha(ledger),old_point_origin_file=old.point_origin_file,old_point_origin_sha256=old.point_origin_sha256,old_point_origin_locator=old.point_origin_locator,old_coordinate_source_record_id=old.coordinate_source_record_id,rejection_reason=reason,evidence_file=str(O/'wrong_homonym_rejection_witness.json.gz'),evidence_locator='[0]');R=pd.DataFrame([r]);out=O/'accepted_point_rejection_delta.csv'
for fmt in [None,'%.17e','%.18e','%.20e']:
 R.to_csv(out,index=False,float_format=fmt);v=pd.read_csv(out).iloc[0]
 if float(v.old_latitude)==float(old.latitude)and float(v.old_longitude)==float(old.longitude):break
else:raise ValueError('Exact API rejection float equality could not be preserved')
pd.DataFrame(columns=['target_source_record_id','latitude','longitude','coordinate_admission_status','coordinate_source_record_id','point_origin_file','point_origin_sha256','point_origin_locator','point_origin_kind']).to_csv(O/'accepted_point_use_delta.csv',index=False);pd.DataFrame(columns=['from_source_record_id','to_source_record_id','relation','decision_status','admission_method','admission_rule','evidence_file','evidence_locator']).to_csv(O/'accepted_identity_edge_delta.csv',index=False);pd.DataFrame([dict(source_record_id=sid,disposition='withdraw_known_wrong_Sinyal_homonym_point_no_replacement_yet',population_values_modified=False)]).to_csv(O/'record_dispositions.csv',index=False);m=dict(baseline_stage=71,active_point_rejections=1,accepted_own_point_uses=0,identity_edges_added=0,population_values_modified=False,validation=dict(exact_active_point_ledger_and_hash_verified=True,rejection_parser_float_equality_verified=True,rawnative_fullowncodes_and_councils_reopened=True,actual_article_municipality_contradiction_verified=True,replacement_search_durable_zero_response=True),frozen_files=[dict(name=f.name,sha256=sha(f),bytes=f.stat().st_size)for f in sorted(O.iterdir())if f.is_file()]);(O/'freeze_manifest.json').write_text(json.dumps(m,ensure_ascii=False,indent=2));print(1)
