from pathlib import Path
import pandas as pd,json,gzip,re,xlrd,hashlib
O=Path(__file__).parent;D=pd.read_pickle('/dev/shm/over500-20261009/east_enriched.pkl');by=D.set_index('source_record_id',drop=False);P=pd.read_parquet('/dev/shm/over500-20261009/points_compact.parquet').fillna('').drop_duplicates('target_source_record_id',keep='last').set_index('target_source_record_id');I=pd.read_csv('/dev/shm/over500-20261009/wiki_cached_title_index.csv.gz');raw=Path('/workspace/settlements-raw/data/raw/2002/045_9dc3ed048e_02c__Udmurtia.xls');sh=xlrd.open_workbook(str(raw)).sheet_by_name('Sheet1');sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();E=[];pt=[];w=[];di=[]
CASES=[(1106,'Кушья',156201,'игринский','604'),(1109,'Лоза (Лозинское сельское поселение)',156203,'игринский','станция Лоза'),(2205,'Пижил (станция)',157094,'сюмсинский','692 человека в 2002'),(990,'Люкшудья (село, Завьяловский район)',156121,'завьяловский','станция и поселок Люкшудья преобразовывается')]
for ordinal,title,curord,co,term in CASES:
 old=f'2002:045_9dc3ed048e_02c__Udmurtia.xls:Sheet1:{ordinal}';cur=f'2021:data_allsettlements_anon_156_v20251217.parquet:parquet:{curord}';a=by.loc[old];b=by.loc[cur];g=D[D.root.eq(b.root)];assert set(g.census_year)=={2010,2021}and a.county==co and b.county==co
 rc=sh.row_values(ordinal-1);assert re.search('пос[её]лок и станция',str(rc[0]),re.I)and float(str(rc[1]))==a.population
 idx=I[I.article_title.eq(title)].iloc[0];f=Path(idx.cache_file);j=json.load(gzip.open(f));p=next(x for x in j['payload']['query']['pages']if x['title']==title);txt=p['revisions'][0]['slots']['main']['content'];assert term in txt
 # Printed historical council distinguishes the station-settlement complex from same-name nearby villages.
 heading=next(str(sh.cell_value(k,0)).strip()for k in range(ordinal-2,max(-1,ordinal-100),-1)if'сельсовет'in str(sh.cell_value(k,0)).lower())
 nn=re.sub(r'^и станция\s*','',a.name_norm);rivals=D[D.region_norm.eq('удмуртская')&D.county.eq(co)&D.name_norm.isin([a.name_norm,nn])];wid=len(w);w.append(dict(target_source_record_id=old,current_source_record_id=cur,raw2002_file=str(raw),raw2002_sha256=sha(raw),raw2002_row0=ordinal-1,raw2002_cells=rc,raw_prior_council=heading,raw_scope='One enumerated own settlement census leaf with combined settlement/station designator, one published count; nearby village of same name retained as separate competing own census leaf. No separate station count summed.',native_name_type_rivals=rivals[['source_record_id','census_year','type_norm','county','root']].to_dict('records'),current_native_own_oktmo=str(b.oktmo),article_file=str(f),article_sha256=sha(f),pageid=p['pageid'],revision=p['revisions'][0]['revid'],own_article_literal_excerpt=[dict(line=n,text=l)for n,l in enumerate(txt.splitlines(),1)if term in l or'станци'in l or'сельсовет'in l],semantic_census_type_designator_preserved=True,exact_population_boundary_equivalence_asserted=False))
 E.append(dict(from_source_record_id=old,to_source_record_id=cur,relation='same_place',decision_status='checked_rule_accepted',admission_method='one_native_census_leaf_combined_station_settlement_designator_own_article_physical_continuity',admission_rule='Published2002 поселок и станция is one enumerated named NP leaf with one count; owncounty and council fixes physical station-settlement object; independently named ownarticle confirms station history or own2002 count and where explicit dated2004 transformation; distinct same-name villages retained. No merging oldcensusleafs or population-boundary equivalence.',population_boundary_comparability_asserted=False,evidence_file=str(O/'identity_point_witnesses.json.gz'),evidence_locator=f'[{wid}]'))
 donor=next(P.loc[s]for s in g.source_record_id if s in P.index)
 pt.append(dict(target_source_record_id=old,**{k:donor[k]for k in ['latitude','longitude','coordinate_source_record_id','point_origin_file','point_origin_sha256','point_origin_locator','point_origin_kind']},coordinate_admission_status='reviewed_extension_rule_accepted',coordinate_binding_rule='sourcecounty_historical_one_station_settlement_census_leaf_own_article_physical_lineage',point_use_inference='Own station-settlement representative point inferred retrospectively by admitted physical locality continuity; no separate railway infrastructure point or historical censusmeasurement claim.',historical_census_coordinate_asserted=False,population_boundary_comparability_asserted=False,external_provider_ID_binding_asserted=False,current_carrier_source_record_id=donor.name))
 for sid in [old]+g.source_record_id.tolist():di.append(dict(source_record_id=sid,disposition='accepted_one_enumerated_station_settlement_census_leaf_physical_continuity',raw_source_type_designator_preserved=True))
with gzip.open(O/'identity_point_witnesses.json.gz','wt')as f:json.dump(w,f,ensure_ascii=False)
pd.DataFrame(E).to_csv(O/'accepted_identity_edge_delta.csv',index=False);pd.DataFrame(pt).to_csv(O/'accepted_point_use_delta.csv',index=False);pd.DataFrame(di).to_csv(O/'record_dispositions.csv',index=False);print(len(E),len(pt))
